### ISSUE TITLE
Gzip or XZ compressed movie files

### ISSUE THREAD

**Issue by bforsbe** [3dem/relion#100]
Originally reported by: **Bharat Reddy (Bitbucket: [barureddy](https://bitbucket.org/barureddy), GitHub: [barureddy](https://github.com/barureddy))**

----------------------------------------

The movie files we are collecting are quite large, but are highly compressible (sometimes upto 90%) wtih gzip or xz. If relion and associated programs could use the compressed versions of movie files, that would greatly reduce the hard drive space requirements and in turn might actually speed up certain IO operations. 

----------------------------------------
- Bitbucket: https://bitbucket.org/tcblab/relion2-beta/issue/100

**Comment by biochem-fan** [comment]
One should use LZW- or ZIP-TIFF.
