### ISSUE TITLE
license of downloaded pretrained model weights (Relion ver. 5.0-beta)

### ISSUE THREAD

**Issue by machine-etal** [3dem/relion#1000]
I am so glad that Relion ver. 5.0-beta released!
I tried to install it, and during the installation process, the pretrained model weights (used in Blush, ModelAngelo, and class_ranker) were downloaded.

What should I consider the license of these models?
Can these models be used for commercial research (e.g., Cryo-EM SPA) as well as Relion itself?

**Comment by biochem-fan** [comment]
> Can these models be used for commercial research (e.g., Cryo-EM SPA) as well as Relion itself?

Yes :)

**Comment by machine-etal** [comment]
Thank you for your prompt response.
