### ISSUE TITLE
Compilation issues in "make" step: relion_gpu_util_generated_cuda_ml_optimiser.cu.o.Release.cmake:280

### ISSUE THREAD

**Issue by walidabualafia** [3dem/relion#1002]
**I am having a great deal of trouble getting Relion-5.0 to make/compile. The error is described in greater detail below.**

Whenever I run the cmake step, it completes successfully. Throws some warnings here and there, mostly about deprecation, but nothing serious. I am using `cmake/3.27.3`.

However, when I run `make -j <some_num_threads>`, I get the following error. I got the error even when I tried to run `make` on a single core.

```
CMake Error at relion_gpu_util_generated_cuda_ml_optimiser.cu.o.Release.cmake:280 (message):
  Error generating file
  /longer/path/removed/relion/build/src/apps/CMakeFiles/relion_gpu_util.dir/__/acc/cuda/./relion_gpu_util_generated_cuda_ml_opti
miser.cu.o

make[2]: *** [src/apps/CMakeFiles/relion_gpu_util.dir/build.make:3183: src/apps/CMakeFiles/relion_gpu_util.dir/__/acc/cuda/relion_gpu_util_generated_cuda_
ml_optimiser.cu.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:385: src/apps/CMakeFiles/relion_gpu_util.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```

**Environment:**
 - OS: RHEL 8.8 (Ootpa)
 - MPI runtime: OpenMPI 4.1.1
 - RELION version: Relion-5.0 (I git cloned it yesterday, and checked out branch ver5.0)
 - Memory: 8GB/core (usually try to compile with 8 cores so 64GB, but variable)
 - GPU: 4 NVIDIA A100-SXM
 
**Loaded Modules:**
- `cmake/3.27.3`
- `go/1.13`
- `openucx/1.10.1`
- `openmpi/4.1.1`
- `fltk/1.37`
- `gcc/9.1.0`
- `mamba/1.4.2`
- `cuda12.0.1/toolkit`

**Job options:**
 - Type of job: Compilation
 - Number of threads: I tried multi-threaded and single-threaded installs
 - Full `cmake` command:
   ```cmake
   cmake -DCMAKE_INSTALL_PREFIX=/some/custom/location/relion/install/5.0 -DDoublePrec_CPU=OFF ..
   ```
- Full `make` command:
   ```
   make -j 8
   ``` 

**Error message:**
```
/some/custom/location/relion/vendor/relion/src/acc/acc_ml_optimiser_impl.h(1235): error: a reference of type "double &" (not const-qualified) cannot be initialized with a value of type "float"
          detected during instantiation of "void accDoExpectationOneParticle(MlClass *, unsigned long, int, AccPtrFactory) [with MlClass=MlOptimiserCuda]"
/some/custom/location/relion/vendor/relion/src/acc/cuda/cuda_ml_optimiser.cu(284): here

/some/custom/location/relion/vendor/relion/src/acc/acc_ml_optimiser_impl.h(1235): error: a reference of type "double &" (not const-qualified) cannot be initialized with a value of type "float"
          detected during instantiation of "void accDoExpectationOneParticle(MlClass *, unsigned long, int, AccPtrFactory) [with MlClass=MlOptimiserCuda]"
/some/custom/location/relion/vendor/relion/src/acc/cuda/cuda_ml_optimiser.cu(284): here

/some/custom/location/relion/vendor/relion/src/acc/acc_ml_optimiser_impl.h(1235): error: a reference of type "double &" (not const-qualified) cannot be initialized with a value of type "float"
          detected during instantiation of "void accDoExpectationOneParticle(MlClass *, unsigned long, int, AccPtrFactory) [with MlClass=MlOptimiserCuda]"
/some/custom/location/relion/vendor/relion/src/acc/cuda/cuda_ml_optimiser.cu(284): here

/some/custom/location/relion/vendor/relion/src/acc/acc_ml_optimiser_impl.h(1540): error: a reference of type "double &" (not const-qualified) cannot be initialized with a value of type "float"
          detected during instantiation of "void accDoExpectationOneParticle(MlClass *, unsigned long, int, AccPtrFactory) [with MlClass=MlOptimiserCuda]"
/some/custom/location/relion/vendor/relion/src/acc/cuda/cuda_ml_optimiser.cu(284): here

/some/custom/location/relion/vendor/relion/src/acc/acc_ml_optimiser_impl.h(1540): error: a reference of type "double &" (not const-qualified) cannot be initialized with a value of type "float"
          detected during instantiation of "void accDoExpectationOneParticle(MlClass *, unsigned long, int, AccPtrFactory) [with MlClass=MlOptimiserCuda]"
/some/custom/location/relion/vendor/relion/src/acc/cuda/cuda_ml_optimiser.cu(284): here

/some/custom/location/relion/vendor/relion/src/acc/acc_ml_optimiser_impl.h(1540): error: a reference of type "double &" (not const-qualified) cannot be initialized with a value of type "float"
          detected during instantiation of "void accDoExpectationOneParticle(MlClass *, unsigned long, int, AccPtrFactory) [with MlClass=MlOptimiserCuda]"
/some/custom/location/relion/vendor/relion/src/acc/cuda/cuda_ml_optimiser.cu(284): here

/some/custom/location/relion/vendor/relion/src/acc/acc_ml_optimiser_impl.h(2995): error: a reference of type "double &" (not const-qualified) cannot be initialized with a value of type "float"
          detected during instantiation of "void accDoExpectationOneParticle(MlClass *, unsigned long, int, AccPtrFactory) [with MlClass=MlOptimiserCuda]"
/some/custom/location/relion/vendor/relion/src/acc/cuda/cuda_ml_optimiser.cu(284): here

/some/custom/location/relion/vendor/relion/src/acc/acc_ml_optimiser_impl.h(2995): error: a reference of type "double &" (not const-qualified) cannot be initialized with a value of type "float"
          detected during instantiation of "void accDoExpectationOneParticle(MlClass *, unsigned long, int, AccPtrFactory) [with MlClass=MlOptimiserCuda]"
/some/custom/location/relion/vendor/relion/src/acc/cuda/cuda_ml_optimiser.cu(284): here

/some/custom/location/relion/vendor/relion/src/acc/acc_ml_optimiser_impl.h(2995): error: a reference of type "double &" (not const-qualified) cannot be initialized with a value of type "float"
          detected during instantiation of "void accDoExpectationOneParticle(MlClass *, unsigned long, int, AccPtrFactory) [with MlClass=MlOptimiserCuda]"
/some/custom/location/relion/vendor/relion/src/acc/cuda/cuda_ml_optimiser.cu(284): here

9 errors detected in the compilation of "/some/custom/location/relion/vendor/relion/src/acc/cuda/cuda_ml_optimiser.cu".
CMake Error at relion_gpu_util_generated_cuda_ml_optimiser.cu.o.Release.cmake:280 (message):
  Error generating file
  /some/custom/location/relion/vendor/relion/build/src/apps/CMakeFiles/relion_gpu_util.dir/__/acc/cuda/./relion_gpu_util_generated_cuda_ml_optimiser.cu.o


make[2]: *** [src/apps/CMakeFiles/relion_gpu_util.dir/build.make:3183: src/apps/CMakeFiles/relion_gpu_util.dir/__/acc/cuda/relion_gpu_util_generated_cuda_ml_optimiser.cu.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:385: src/apps/CMakeFiles/relion_gpu_util.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```

**Useful Information:**
I am using the conda environment that should have all the downloaded ML models.

All help would be appreciated. Thanks! :)

**Comment by biochem-fan** [comment]
Indeed this looks like a bug. Meanwhile, could you please avoid using `-DDoublePrec_CPU=OFF`?

**Comment by walidabualafia** [comment]
Thanks for your response, @biochem-fan.

I just tried to compile without `-DDoublePrec_CPU=OFF`, but unfortunately, it fails with exactly the same error. Any other suggestions I can try?

I have no other `cmake` flags except for `-DCMAKE_INSTALL_PREFIX=/some/location`

Thanks again!

**Comment by biochem-fan** [comment]
Did you delete your build folder before rerunning `cmake`?

**Comment by biochem-fan** [comment]
I fixed the single precision build in commit 0dada4d. With this, both `-DDoublePrec_CPU=OFF` and `-DDoublePrec_CPU=ON` should work.

**Comment by jiangq99920032** [comment]
I had a related installation problem. I was installing RELION5.0.0 in a Fedora 41 system with CUDA12.9.  Cmake was successful, but "make -j 1" gave out the following errors. 
----
/usr/local/cuda/include/cuda/std/__utility/forward.h: In instantiation of ‘constexpr _Tp&& cuda::std::__4::forward(remove_reference_t<_Tp>&) [with _Tp = void*]’:
/usr/local/cuda/include/cuda/std/__utility/forward.h:31:1: error: use of built-in trait ‘__remove_reference(_Tp)’ in function signature; use library traits instead
   31 | _CCCL_NODISCARD _LIBCUDACXX_HIDE_FROM_ABI constexpr _Tp&& forward(remove_reference_t<_Tp>& __t) noexcept
      | ^~~~~~~
/usr/local/cuda/include/cuda/std/__utility/forward.h: In instantiation of ‘constexpr _Tp&& cuda::std::__4::forward(remove_reference_t<_Tp>&) [with _Tp = void*&]’:
/usr/local/cuda/include/cuda/std/__utility/forward.h:31:1: error: use of built-in trait ‘__remove_reference(_Tp)’ in function signature; use library traits instead
/usr/local/cuda/include/cuda/std/__utility/forward.h: In instantiation of ‘constexpr _Tp&& cuda::std::__4::forward(remove_reference_t<_Tp>&) [with _Tp = cub::CUB_200802_SM_500::SmVersion(int&, int)::<lambda(int&)>]’:
/usr/local/cuda/include/cuda/std/__utility/forward.h:31:1: error: use of built-in trait ‘__remove_reference(_Tp)’ in function signature; use library traits instead
/usr/local/cuda/include/cuda/std/__utility/forward.h: In instantiation of ‘constexpr _Tp&& cuda::std::__4::forward(remove_reference_t<_Tp>&) [with _Tp = cub::CUB_200802_SM_500::PtxVersion(int&, int)::<lambda(int&)>]’:
/usr/local/cuda/include/cuda/std/__utility/forward.h:31:1: error: use of built-in trait ‘__remove_reference(_Tp)’ in function signature; use library traits instead
/usr/local/cuda/include/cuda/std/__utility/forward.h: In instantiation of ‘constexpr _Tp&& cuda::std::__4::forward(remove_reference_t<_Tp>&) [with _Tp = __builtin_new_allocator::__builtin_new_deleter]’:
/usr/local/cuda/include/cuda/std/__utility/forward.h:31:1: error: use of built-in trait ‘__remove_reference(_Tp)’ in function signature; use library traits instead
/usr/local/cuda/include/cuda/std/__utility/move.h: In instantiation of ‘constexpr cuda::std::__4::remove_reference_t<_Tp>&& cuda::std::__4::move(_Tp&&) [with _Tp = __builtin_new_allocator::__builtin_new_deleter&]’:
/usr/local/cuda/include/cuda/std/__utility/move.h:32:1: error: use of built-in trait ‘__remove_reference(_Tp)’ in function signature; use library traits instead
   32 | _CCCL_NODISCARD _LIBCUDACXX_HIDE_FROM_ABI constexpr remove_reference_t<_Tp>&& move(_Tp&& __t) noexcept
      | ^~~~
/usr/local/cuda/include/cuda/std/__utility/move.h: In instantiation of ‘constexpr cuda::std::__4::remove_reference_t<_Tp>&& cuda::std::__4::move(_Tp&&) [with _Tp = int&]’:
/usr/local/cuda/include/cuda/std/__utility/move.h:32:1: error: use of built-in trait ‘__remove_reference(_Tp)’ in function signature; use library traits instead
CMake Error at relion_gpu_util_generated_cuda_projector_plan.cu.o.Release.cmake:280 (message):
  Error generating file
  /home/jiangq/relion/build/src/apps/CMakeFiles/relion_gpu_util.dir/__/acc/cuda/./relion_gpu_util_generated_cuda_projector_plan.cu.o

-----------
I wonder if you ever encountered this type of problem with the making of relion_gpu_util_generated_cuda_projector_plan.cu.o

Thanks for your sharing.

**Comment by biochem-fan** [comment]
Did you make sure your GCC version is compatible with CUDA 12.9?

**Comment by jiangq99920032** [comment]
yes. It is gcc14.3, and is compatible.

**Comment by jiangq99920032** [comment]
I will give it a trial.

**Comment by jiangq99920032** [comment]
For the current time being, we had cryosparc v4.7.1 job running.  Did you even have an earlier version CUDA running in parallel for Relion installation with proper communications to the GPU drivers?

**Comment by biochem-fan** [comment]
A new version of the NVIDIA driver can run binaries compiled by an older version of the CUDA SDK. Thus, do not change the driver version and just install an older CUDA SDK for RELION; do not delete the new CUDA SDK other applications depend on.

**Comment by jiangq99920032** [comment]
OK. Thanks.
