### ISSUE TITLE
Connection refused while downloading during cmake

### ISSUE THREAD

**Issue by diffracteD** [3dem/relion#1003]
Hi,
I'm trying to install relion5.0 on my server but having this 'connection refused' error while doing cmake. However, ModelAngelo got downloaded quite easily.
The cmake output is as follows:
```
(relion-5.0) [user@server-02 build]$ cmake ..
CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


-- BUILD TYPE set to the default type:  'Release'
-- Setting fallback CUDA_ARCH=50
-- CUDA enabled - Building CUDA-accelerated version of RELION
-- Setting cpu precision to double
-- Setting accelerated code precision to single
CMake Warning (dev) at CMakeLists.txt:191 (FIND_PACKAGE):
  Policy CMP0146 is not set: The FindCUDA module is removed.  Run "cmake
  --help-policy CMP0146" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

This warning is for project developers.  Use -Wno-dev to suppress it.

-- Using cuda wrapper to compile....
-- Cuda version is >= 7.5 and single-precision build, enable double usage warning.
-- MPI_INCLUDE_PATH : /usr/local/include
-- MPI_LIBRARIES : /usr/local/lib/libmpi.so
-- MPI_CXX_INCLUDE_PATH : /usr/local/include
-- MPI_CXX_LIBRARIES : /usr/local/lib/libmpi.so
-- CMAKE_C_COMPILER : /usr/bin/cc
-- CMAKE_CXX_COMPILER : /usr/bin/c++
-- MPI_C_COMPILER : /usr/local/bin/mpicc
-- MPI_CXX_COMPILER : /usr/local/bin/mpicxx
-- CMAKE_CXX_COMPILER_ID : GNU
-- Could NOT find FLTK (missing: FLTK_LIBRARIES FLTK_INCLUDE_DIR) 
-- No FLTK installation was found
-- --------------------------------------------------------
-- -------- NO EXISTING FLTK LIBRARIES WHERE FOUND. -------
-- -------------- FLTK WILL BE DOWNLOADED AND -------------
-- --------------- BUILT DURING COMPILE-TIME. -------------
-- --------------------------------------------------------
-- ---- A WORKING INTERNET CONNECTION WILL BE REQUIRED. ---
-- --------------------------------------------------------
-- no previous fltk found, the following paths are set for libs/headers TO BE built
CMake Warning (dev) at /home/user/.conda/envs/relion-5.0/lib/python3.10/site-packages/cmake/data/share/cmake-3.27/Modules/ExternalProject.cmake:3136 (message):
  The DOWNLOAD_EXTRACT_TIMESTAMP option was not given and policy CMP0135 is
  not set.  The policy's OLD behavior will be used.  When using a URL
  download, the timestamps of extracted files should preferably be that of
  the time of extraction, otherwise code that depends on the extracted
  contents might not be rebuilt if the URL changes.  The OLD behavior
  preserves the timestamps from the archive instead, but this is usually not
  what you want.  Update your project to the NEW behavior or specify the
  DOWNLOAD_EXTRACT_TIMESTAMP option with a value of true to avoid this
  robustness issue.
Call Stack (most recent call first):
  /home/user/.conda/envs/relion-5.0/lib/python3.10/site-packages/cmake/data/share/cmake-3.27/Modules/ExternalProject.cmake:4345 (_ep_add_download_command)
  cmake/BuildFLTK.cmake:47 (externalproject_add)
  CMakeLists.txt:443 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- FLTK_INCLUDE_DIR: /home/user/relion/external/fltk/include
-- FLTK_LIBRARIES:   /home/user/relion/external/fltk/lib/libfltk.so
-- Found FFTW
-- FFTW_PATH: /usr/include
-- FFTW_INCLUDES: /usr/include
-- FFTW_LIBRARIES: /usr/lib64/libfftw3f.so;/usr/lib64/libfftw3.so
-- Could NOT find JPEG (missing: JPEG_LIBRARY JPEG_INCLUDE_DIR) 
-- Will try to find Conda environment (name: relion-5.0) and its Python executable...
-- Found Conda executable: /usr/local/anaconda3/condabin/conda
-- Found Conda environment (name: relion-5.0) and its Python executable.
-- Using Python executable: /home/user/.conda/envs/relion-5.0/bin/python
-- Will try to find Torch home directory...
-- Using Torch home: /home/user/.cache/torch
-- Will attempts to download model weights for dependent packages...
Attempting to download weights for class ranker...
Traceback (most recent call last):
  File "/home/user/.conda/envs/relion-5.0/lib/python3.10/urllib/request.py", line 1565, in ftp_open
    fw = self.connect_ftp(user, passwd, host, port, dirs, req.timeout)
  File "/home/user/.conda/envs/relion-5.0/lib/python3.10/urllib/request.py", line 1585, in connect_ftp
    return ftpwrapper(user, passwd, host, port, dirs, timeout,
  File "/home/user/.conda/envs/relion-5.0/lib/python3.10/urllib/request.py", line 2406, in __init__
    self.init()
  File "/home/user/.conda/envs/relion-5.0/lib/python3.10/urllib/request.py", line 2415, in init
    self.ftp.connect(self.host, self.port, self.timeout)
  File "/home/user/.conda/envs/relion-5.0/lib/python3.10/ftplib.py", line 158, in connect
    self.sock = socket.create_connection((self.host, self.port), self.timeout,
  File "/home/user/.conda/envs/relion-5.0/lib/python3.10/socket.py", line 845, in create_connection
    raise err
  File "/home/user/.conda/envs/relion-5.0/lib/python3.10/socket.py", line 833, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/user/.conda/envs/relion-5.0/lib/python3.10/site-packages/relion_classranker/command_line.py", line 101, in main
    model, model_path = install_and_load_model(
  File "/home/user/.conda/envs/relion-5.0/lib/python3.10/site-packages/relion_classranker/command_line.py", line 53, in install_and_load_model
    torch.hub.download_url_to_file(model_list[name][0], model_path_gz, hash_prefix=model_list[name][1])
  File "/home/user/.conda/envs/relion-5.0/lib/python3.10/site-packages/torch/hub.py", line 611, in download_url_to_file
    u = urlopen(req)
  File "/home/user/.conda/envs/relion-5.0/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/home/user/.conda/envs/relion-5.0/lib/python3.10/urllib/request.py", line 519, in open
    response = self._open(req, data)
  File "/home/user/.conda/envs/relion-5.0/lib/python3.10/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/home/user/.conda/envs/relion-5.0/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/home/user/.conda/envs/relion-5.0/lib/python3.10/urllib/request.py", line 1582, in ftp_open
    raise URLError(exp) from exp
urllib.error.URLError: <urlopen error [Errno 111] Connection refused>
Installing Classranker model (v1.0)...

---------------------------------- PYTHON ERROR ---------------------------------
   Has RELION been provided a Python interpreter with the correct environment?
   The interpreter can be passed to RELION either during Cmake configuration by
     using the Cmake flag -DPYTHON_EXE_PATH=<path/to/python/interpreter>.
   NOTE: For some modules TORCH_HOME needs to be set to find pretrained models
---------------------------------------------------------------------------------

  Using python executable: /home/user/.conda/envs/relion-5.0/bin/python

Attempting to download weights for Blush...
Traceback (most recent call last):
  File "/home/user/.conda/envs/relion-5.0/lib/python3.10/urllib/request.py", line 1565, in ftp_open
    fw = self.connect_ftp(user, passwd, host, port, dirs, req.timeout)
  File "/home/user/.conda/envs/relion-5.0/lib/python3.10/urllib/request.py", line 1585, in connect_ftp
    return ftpwrapper(user, passwd, host, port, dirs, timeout,
  File "/home/user/.conda/envs/relion-5.0/lib/python3.10/urllib/request.py", line 2406, in __init__
    self.init()
  File "/home/user/.conda/envs/relion-5.0/lib/python3.10/urllib/request.py", line 2415, in init
    self.ftp.connect(self.host, self.port, self.timeout)
  File "/home/user/.conda/envs/relion-5.0/lib/python3.10/ftplib.py", line 158, in connect
    self.sock = socket.create_connection((self.host, self.port), self.timeout,
  File "/home/user/.conda/envs/relion-5.0/lib/python3.10/socket.py", line 845, in create_connection
    raise err
  File "/home/user/.conda/envs/relion-5.0/lib/python3.10/socket.py", line 833, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/user/.conda/envs/relion-5.0/lib/python3.10/site-packages/relion_blush/command_line.py", line 275, in main
    model, model_path = install_and_load_model(
  File "/home/user/.conda/envs/relion-5.0/lib/python3.10/site-packages/relion_blush/util.py", line 817, in install_and_load_model
    torch.hub.download_url_to_file(model_list[name][0], model_path_gz, hash_prefix=model_list[name][1])
  File "/home/user/.conda/envs/relion-5.0/lib/python3.10/site-packages/torch/hub.py", line 611, in download_url_to_file
    u = urlopen(req)
  File "/home/user/.conda/envs/relion-5.0/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/home/user/.conda/envs/relion-5.0/lib/python3.10/urllib/request.py", line 5Installing Blush model (v1.0)...
19, in open
    response = self._open(req, data)
  File "/home/user/.conda/envs/relion-5.0/lib/python3.10/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/home/user/.conda/envs/relion-5.0/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/home/user/.conda/envs/relion-5.0/lib/python3.10/urllib/request.py", line 1582, in ftp_open
    raise URLError(exp) from exp
urllib.error.URLError: <urlopen error [Errno 111] Connection refused>

---------------------------------- PYTHON ERROR ---------------------------------
   Has RELION been provided a Python interpreter with the correct environment?
   The interpreter can be passed to RELION either during Cmake configuration by
     using the Cmake flag -DPYTHON_EXE_PATH=<path/to/python/interpreter>.
   NOTE: For some modules TORCH_HOME needs to be set to find pretrained models
---------------------------------------------------------------------------------

  Using python executable: /home/user/.conda/envs/relion-5.0/bin/python

Attempting to download weights for ModelAngelo...
Please make sure you have set the environment variable TORCH_HOME 
to a suitable directory, visible to all relevant users!
Successful!
Path to model is /home/user/.cache/torch/hub/checkpoints/model_angelo_v1.0/nucleotides
Please make sure you have set the environment variable TORCH_HOME 
to a suitable directory, visible to all relevant users!
Successful!
Path to model is /home/user/.cache/torch/hub/checkpoints/model_angelo_v1.0/nucleotides_no_seq
One or more download tasks failed. See above error messages.
CMake Warning at CMakeLists.txt:555 (message):
  Failed to download model weights.You could ignore this.The downloads will
  be attempted again when the model weights are required later.NOTE: You can
  skip this step by setting -DFETCH_WEIGHTS=OFF


-- Building static libs (larger build size and binaries)
Running apps/CMakeLists.txt...
-- CMAKE_BINARY_DIR:/home/user/relion/build
-- Git commit ID: 73965084a80ec8cbfaaa49343be7415a03753a0e
-- Configuring done (12.5s)
-- Generating done (0.3s)
-- Build files have been written to: /home/user/relion/build

```
Please advise. 
Thanks

**Comment by biochem-fan** [comment]
Doesn't your network admin block outbound FTP?
The file is ftp://ftp.mrc-lmb.cam.ac.uk/pub/dari/blush_v1.0.ckpt.gz.

@dkimanius we should provide other download options; ModelAngelo uses Zenodo.

**Comment by ckywong** [comment]
Our institute also blocks outbound FTP connection.  Alternative download options, e.g., https, will be very helpful.  Thank you!

**Comment by diffracteD** [comment]
Got the issue resolved. My network admin raised an IP exception to this ftp server and installation went smoothly.
Thanks for the advise.

**Comment by biochem-fan** [comment]
Until we set up an alternative download server, a workaround is as follows:

1. Download `ftp://ftp.mrc-lmb.cam.ac.uk/pub/dari/blush_v1.0.ckpt.gz` via a network that does not block FTP.
2. Decompress it.
3. Copy `blush_v1.0.ckpt` as `$TORCH_HOME/checkpoints/relion_blush/v1.0.ckpt`. The destination is `~/.cache/torch/hub/checkpoints/relion_blush` by default if `$TORCH_HOME` is not set.
4. Also make an empty file called `v1.0_installed.txt` in the same directory.

**Comment by biochem-fan** [comment]
Let's keep this open until we set up an alternative download site.

**Comment by unaginekomoyashi** [comment]
Thank you for your comment.

**Comment by dkimanius** [comment]
This issue is fixed in this [commit of the Blush repo](https://github.com/3dem/relion-blush/commit/80fb1cdfa93eef736544dbd6b23b3875ff2be506). As we now download from Zenodo.

**Comment by biochem-fan** [comment]
@dkimanius Thanks! Can you also upload classranker weights to Zenodo? It is also in LMB's FTP at the moment.

**Comment by ryao-mdanderson** [comment]
Dear Relion5-beta release support team: @dkimanius 
 I have a similar question.
 When I tried cmake command:
   $ cmake -DCMAKE_INSTALL_PREFIX=/risapps/rhel8/relion/5.0 -DPYTHON_EXE_PATH=/risapps/rhel8/miniconda3/py39_4.12.0/envs/relion-5.0/bin/python -DTORCH_HOME_PATH=/risapps/rhel8/relion/5.0/torch-home/ .. | tee cmake.log

Hit the download error message:
Attempting to download weights for class ranker...
Traceback (most recent call last):
  File "/risapps/rhel8/miniconda3/py39_4.12.0/envs/relion-5.0/lib/python3.10/urllib/request.py", line 1565, in ftp_open
 .....
 urllib.error.URLError: <urlopen error [Errno 110] Connection timed out>
Installing Classranker model (v1.0)...
...
Attempting to download weights for Blush...
Installing Blush model (v1.0)...
Downloading model weights from:
   https://zenodo.org/records/10072731/files/blush_v1.0.ckpt.gz
.....
Blush model (v1.0) loaded successfully from checkpoint /risapps/rhel8/relion/5.0/torch-home/hub/checkpoints/relion_blush/v1.0.ckpt
No job target was specified for Blush regularization... exiting!
Attempting to download weights for ModelAngelo...
  0%|          | 0.00/1.98G [00:00<?, ?B/s]Please make sure you have set the environment variable TORCH_HOME 
to a suitable directory, visible to all relevant users!
Setting up bundle with name: nucleotides for the first time.
100%|██████████| 1.98G/1.98G [06:44<00:00, 5.27MB/s] 
Traceback (most recent call last):
  File "/risapps/rhel8/miniconda3/py39_4.12.0/envs/relion-5.0/lib/python3.10/urllib/request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
......
NOTE: You can skip this step by setting -DFETCH_WEIGHTS=OFF
...

Please help to upload classranker weights and ModelAngelo weights to Zenodo.
If you have instruction for manually download and set up, please advise. Thank you!

Regards,
Rong

**Comment by ryao-mdanderson** [comment]
Hello Relion support:

Our HPC cluster compute nodes do not have internet access. while running relion5 beta, notice
the application is trying download some and failed as shown below:
---------------------------------------------------------------------------------------------------------------------------------
Downloading: "https://dl.fbaipublicfiles.com/fair-esm/models/esm1b_t33_650M_UR50S.pt" to /risapps/rhel8/relion/5.0/torch-home/hub/checkpoints/esm1b_t33_650M_UR50S.pt
 (where /risapps/rhel8/relion/5.0/torch-home/ is defined as $torch_home)

Is there an alternative to have all the required files download once manually and set up to use?

Thank you for your advise.
Rong

**Comment by dkimanius** [comment]
All the required files are downloaded during the cmake configuration, which is once before install, and this requires internet access. 

Unfortunetly we don't provide instructions on how to do this manually. 

But, if you have a system that has internet access, you can install Relion on it and copy the torch_home directory over to the one without internet. You will of course also need to install the python dependencies, which are defined in the environment.yml. When you have an environment setup with all the deep-leaning weights, run cmake again with the flag -DFETCH_WEIGHTS=OFF, so it doens't try to download them again. 

However, do this at your own risk, as it's likely there will be a bunch of issues and cryptic error messages we won't be able to help you solve.

**Comment by ryao-mdanderson** [comment]
Hello @dkimanius:

Thank you very much for the reply. I will try what you suggested.

**Comment by ryao-mdanderson** [comment]
It will be good to know all the external sites (domain names or IP addresses) that all the models are stored.
With this information, we can request firewall open on these sites on our cluster login node so that we can build Relion simpler in the future.

Thank you!

**Comment by dkimanius** [comment]
I need to check, but I think almost all of them are on Zenodo. Like the one set of weights that fails in your error message is: https://zenodo.org/records/10072731/files/blush_v1.0.ckpt.gz

**Comment by ryao-mdanderson** [comment]
Hello @dkimanius :

 I tried build relion on a standalone server which has internet access. Refer to my communication with https://github.com/3dem/relion/issues/1072. This goal is to download data models.

  I failed make process at 58%, however, I am seeing make process accesses two ftp sites:
    Using src='ftp://ftp.mrc-lmb.cam.ac.uk/pub/scheres/fltk-1.3.5-source.tar.gz'
    Using src='ftp://ftp.mrc-lmb.cam.ac.uk/pub/dari/class_ranker_0.1.3_torch_1.0.1.pt.tar.gz'

 at the end of exited make process, noticed the following contents in my test build
 [ris_hpc_apps@r1drpswdev3 external]$ ls -lrt
 total 0
 drwxr-xr-x. 3 ris_hpc_apps rists 74 Jan 24 10:35 torch_models
 drwxr-xr-x. 3 ris_hpc_apps rists 50 Jan 24 10:35 fltk
 [ris_hpc_apps@r1drpswdev3 external]$ ls -lrt torch_models/
 total 2140
 -rw-r--r--. 1 ris_hpc_apps rists 2190018 Jan 24 10:35 class_ranker_0.1.3_torch_1.0.1.pt.tar.gz
 drwxr-xr-x. 2 ris_hpc_apps rists      47 Jan 24 10:35 class_ranker

 I do not see the download from Zenodo. I do not find  models (e.g. Blush, ModelAngelo and DynaMight). I wonder if the download complete?  

 I attached my build log here, please advise.  Thank you very much!
[relion5-r1drpswdev3.txt](https://github.com/3dem/relion/files/14041887/relion5-r1drpswdev3.txt)
