### ISSUE TITLE
--pipeline-control option prevents relion_python_modelangelo from running

### ISSUE THREAD

**Issue by andreanans** [3dem/relion#1009]
Hi, 

We're having an issue running ModelAngelo jobs in Relion 5.0beta-commit-cff855

It appears as though the --pipeline-control ModelAngelo/jobXXX flag is appended to the relion_python_modelangelo command, which leads to the an unrecognised argument error in ModelAngelo
A typical command and error would be the following:

relion_python_modelangelo build_no_seq  -v Import/job001/sample_map.mrc -o ModelAngelo/job002/ -d 0 --pipeline-control ModelAngelo/job002

 "-c: error: unrecognised arguments: ModelAngelo/job002"

If we omit the --pipeline-control flag then the job runs normally.

Is there anything in our set-up that would cause this issue?

Thank you

Andrea

**Comment by andreanans** [comment]
Hi Kiarash,

Looks like it's 1.0.1

**Comment by scheres** [comment]
Hmmmm, the latest model-angelo version is 1.0.8. How did you install model-angelo? Did you use these commands in the installation instructions?
conda env create -f environment.yml

**Comment by andreanans** [comment]
Yes, I actually just re-created the conda environment just in case.
