### ISSUE TITLE
Cannot build in a new workstation. (unsupported GNU version)

### ISSUE THREAD

**Issue by stav-ros** [3dem/relion#1010]
Hi gang, is it possible to provide a conda environment for those of us less skilled in understanding why we would get errors like the following:

```
[  0%] Building NVCC (Device) object src/apps/CMakeFiles/relion_jaz_gpu_util.dir/__/jaz/cuda/relion_jaz_gpu_util_generated_test00.cu.o
[  0%] Built target copy_scripts
In file included from /usr/include/cuda_runtime.h:83,
                 from <command-line>:
/usr/include/crt/host_config.h:132:2: error: #error -- unsupported GNU version! gcc versions later than 12 are not supported! The nvcc flag '-allow-unsupported-compiler' can be used to override this version check; however, using an unsupported host compiler may cause compilation failure or incorrect run time execution. Use at your own risk.
  132 | #error -- unsupported GNU version! gcc versions later than 12 are not supported! The nvcc flag '-allow-unsupported-compiler' can be used to override this version check; however, using an unsupported host compiler may cause compilation failure or incorrect run time execution. Use at your own risk.
      |  ^~~~~
CMake Error at relion_jaz_gpu_util_generated_test00.cu.o.Release.cmake:220 (message):
  Error generating
  /home/.../software/relion/build/src/apps/CMakeFiles/relion_jaz_gpu_util.dir/__/jaz/cuda/./relion_jaz_gpu_util_generated_test00.cu.o

```

cmake has finished successfully so I am not able to understand why there is an error during make. I have tried making an environment with gcc version 11 but then when compiling other errors arose.

It might be helpful to address this by suggesting a conda enviroment just for Relion5.

**Comment by biochem-fan** [comment]
Please do not build RELION within conda environment unless you understand its implications. Cannot you use system's GCC?

**Comment by stav-ros** [comment]
> Please do not build RELION within a conda environment unless you understand its implications. Your NVIDIA CUDA SDK is installed outside conda (i.e. `/usr/include/cuda_runtime.h`). Mixing it with conda's GCC is not a good idea.
> 
> We wrote:
> 
> > Warning:
> > You should NOT activate this relion-5.0 conda environment when compiling and using RELION; RELION activates it automatically only when necessary. Otherwise, system-wide installation of compilers/libraries/MPI runtime might get mixed up with those provided by conda, leading to compilation failures or runtime errors. The same applies to other software packages that provide their own libraries/MPI runtime, such as CCPEM, CCP4, EMAN2, DIALS, PHENIX.
> > https://relion.readthedocs.io/en/release-5.0/Installation.html
> 
> **Cannot you deactivate conda and use system's GCC?**

I am using system's GCC and it is failing, that's why I am asking if it would be better to use a conda environment

> **Please write the version of CUDA SDK and GCC.**

**CUDA:**nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Fri_Jan__6_16:45:21_PST_2023
Cuda compilation tools, release 12.0, V12.0.140
Build cuda_12.0.r12.0/compiler.32267302_0

**GCC:**gcc (Ubuntu 13.2.0-4ubuntu3) 13.2.0
Copyright (C) 2023 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by biochem-fan** [comment]
Why is your system's GCC version so high? Even Ubuntu 23.04 comes with GCC 12.2.

Install `gcc-10` package and use `update-alternatives` to make it the default.
Otherwise you shold explicitly specify it by `CC`, `CXX` and OpenMPI's `OMPI_CC` and `OMPI_CXX` environmental variables.
