### ISSUE TITLE
Wrong Movies link in 5.0 tutorial

### ISSUE THREAD

**Issue by mcahn** [3dem/relion#1013]
By following the instructions here: https://relion.readthedocs.io/en/release-5.0/SPA_tutorial/Introduction.html one downloads this file: `relion50_tutorial_precalculated_results.tar.gz`.  In that file there is a Movies link:

`Movies -> ../Tutorial4.0/Movies/`

but there is no `../Tutorial4.0/Movies/` to link to. Perhaps it should be:

`Movies -> ../relion30_tutorial/Movies`

**Comment by biochem-fan** [comment]
Well, one should not make a symbolic link by a relative path.
https://relion.readthedocs.io/en/release-5.0/SPA_tutorial/Preprocessing.html

So the precalculated example should not actually contain the Movie link.
I will add this to the documentation.

**Comment by mcahn** [comment]
Just to be clear, the issue is not that the link is relative.  It's that it is included in the tutorial data, and points to something non-existent.  It could be deleted from the data, or it could point to the Movies folder in the relion30_tutorial directory, which does exist.  (I also cannot think of a reason why links should not be relative).

**Comment by biochem-fan** [comment]
> I also cannot think of a reason why links should not be relative

This is a long standing restriction in RELION.
