### ISSUE TITLE
blush is not a valid relion argument

### ISSUE THREAD

**Issue by diffracteD** [3dem/relion#1018]
Hi,
Installation of relion5 went without any errors. However, when I try to re-run a 3D classification job (previously run on relion4.0) with "`Use Blush Regularization True`" the job starts but with a warning as follows:
```
The following warnings were encountered upon command-line parsing: 
WARNING: Option --blush	is not a valid RELION argument
```
Command being ran is: ``which relion_refine_mpi` --continue Class3D/job006/run_it060_optimiser.star --o Class3D/job047/run --dont_combine_weights_via_disc --pool 30 --pad 2  --iter 100 --tau2_fudge 10 --particle_diameter 380 --oversampling 1 --healpix_order 2 --offset_range 5 --offset_step 2 --j 8 --gpu ""  --pipeline_control Class3D/job047/`

I'm not sure if this means that blush is not running. 
Please advise.

Thanks

**Comment by biochem-fan** [comment]
Does your `PATH` point to RELION 5.0?
Check not only your login shell but also your job submission script.

**Comment by diffracteD** [comment]
Thanks. I had module sourcing relion4 at the same time. I believe that raised the conflict. The warning is gone once they were silenced.
