### ISSUE TITLE
Polishing: plot of Movement tracks and their linear fits

### ISSUE THREAD

**Issue by bforsbe** [3dem/relion#102]
Originally reported by: **ncoudray (Bitbucket: [ncoudray](https://bitbucket.org/ncoudray), GitHub: Unknown)**

----------------------------------------

Hi,

 I have been doing the polishing step (using movies of helical tubes) and was checking the results by looking at the pdfs. 
 
 Are the plots in the Polish/job028/Micrographs/name_ID_movie_input.eps files supposed to represent the movements of the particles on each movie? If so, I was expecting that the X-Y coordinates of the lines on the plot would correspond to the position of my tube on the image. But it's not the case for me: the X-Y positions of the red and black lines are completely different from where the tubes are. Am I misinterpreting the plot, or is it a bug?

Thanks,
Nicolas

----------------------------------------
- Bitbucket: https://bitbucket.org/tcblab/relion2-beta/issue/102

**Comment by biochem-fan** [comment]
No longer relevant.
