### ISSUE TITLE
Class3D continue with blush

### ISSUE THREAD

**Issue by h-ehara** [3dem/relion#1031]
**Describe your problem**

When continuing Class3d jobs (previously run with blush), it seems that blush is de-activated.

This is probably a GUI-related problem, and adding --blush to the additional arguments field can help.

Regards,

**Comment by biochem-fan** [comment]
Thanks for your report. I will fix this.

**Comment by biochem-fan** [comment]
My commit 792fc5d and @dkimanius's 1e841ca8 should fix this issue.
