### ISSUE TITLE
Compile issue: CMakeList Variables not transfered to CMakeCache in ver5.0

### ISSUE THREAD

**Issue by mstabrin** [3dem/relion#1032]
Hello Everybody,

**Describe your problem**

During the build of the Relion ver5.0 branch I encountered a weird cmake behavior which might also be related to other gpu issues for other users regarding ver5.0, but I am not 100% sure.
I tried to reproduce it on multiple machines with difference cmake versions and so far it was reproducible.
Depending on the machine and cuda used, it was showing an error regarding a missing `-arch` used or was just silently ignored.

It seems that some CMake variables are just ignored and not filled.
For example the CUDA_NVCC_FLAGS_RELEASE, but there are several other variables used as well.
I mention this one specifically, because it is releated to the missing `-arch` error I sometimes got.
I attach the CMakeCache created by the command `cmake ..` on the ver5.0 and the ver4.0 branch, respectively.
[CMakeCache_v5.txt](https://github.com/3dem/relion/files/13377621/CMakeCache_v5.txt)
[CMakeCache_v4.txt](https://github.com/3dem/relion/files/13377629/CMakeCache_v4.txt)

I tried several cmake versions (3.14, 3.20, 3.27), but they all showed the same behavior.

Solutions and ideas for solutions:  
1. I added `message` blocks to identify the issue and it seems to be related to the name of the variable. If I change one character of `CUDA_NVCC_FLAGS_RELEASE` to for example `CUDA_NVCC_FLAGS_RELEASEE`, this variable is actually filled and shows up in the cache properly.

2. If I replace every occurance of `set(VAR value CACHE STRING "")` by just `set(VAR value)` things just work. So I think it might be due to the way caching works. I read that `local` cmake variables override `cached` cmake variables. So maybe those variables are locally assigned during `FIND_PACKAGE(CUDA)` or something? I am not too familiar with the underlying mechanisms of CMAKE at this point.

However, I could successfully install relion ver5.0 after my solution 2., but it feels more like fighting a symptom rather than a solution to the issue.

Best,
Markus Stabrin

**Comment by biochem-fan** [comment]
Is this related to https://cmake.org/cmake/help/latest/policy/CMP0077.html#policy:CMP0077 or https://cmake.org/cmake/help/latest/policy/CMP0126.html? CMake keeps changing too much for us...

Why do you want to specify `CUDA_NVCC_FLAGS_RELEASE` from the command line?

**Comment by mstabrin** [comment]
Hello @biochem-fan ,

I do not want to change it. It just does not get set during the cmake command.
I was just running `cmake ..`, but I realised that the variables were just empty afterwards.

So if you run `cmake ..`, the resulting cmake files have this variable empty, while they are not in the relion 4 branch.
For example, in `src/apps/CMakeFiles/relion_gpu_util.dir/__/acc/cuda/cuda_kernels/./relion_gpu_util_generated_helper.cu.o.cmake` 

Relion 5
```make
set(CUDA_NVCC_EXECUTABLE "/mnt/beegfs/software/em/cuda/cuda_10.0/bin/nvcc") # path
set(CUDA_NVCC_FLAGS  ;; ) # list
# Build specific configuration flags
set(CUDA_NVCC_FLAGS_RELEASE  ; )
set(CUDA_NVCC_FLAGS_DEBUG  ; )
set(CUDA_NVCC_FLAGS_MINSIZEREL  ; )
set(CUDA_NVCC_FLAGS_RELWITHDEBINFO  ; )
```

Relion 4
```
set(CUDA_NVCC_EXECUTABLE "/mnt/beegfs/software/em/cuda/cuda_10.0/bin/nvcc") # path
set(CUDA_NVCC_FLAGS  ;; ) # list
# Build specific configuration flags
set(CUDA_NVCC_FLAGS_RELEASE -arch=sm_50  -D__INTEL_COMPILER --default-stream per-thread --std=c++11 --disable-warnings ; )
set(CUDA_NVCC_FLAGS_DEBUG -arch=sm_50  -D__INTEL_COMPILER --default-stream per-thread --std=c++11 ; )
set(CUDA_NVCC_FLAGS_MINSIZEREL  ; )
set(CUDA_NVCC_FLAGS_RELWITHDEBINFO -arch=sm_50  -D__INTEL_COMPILER --default-stream per-thread --std=c++11 ; )
```

**Comment by biochem-fan** [comment]
Hmm, I am using CMake 3.16.3 and nvcc 11.6 but these variables are cached properly.

**Comment by oliverdutton** [comment]
Had the same issue with other versions of nvcc. Following dockerfile compiled for me.
```
FROM nvcr.io/nvidia/cuda:11.6.2-cudnn8-devel-ubuntu20.04
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && \
    apt-get install -y  git build-essential mpi-default-bin mpi-default-dev libfftw3-dev libtiff-dev libpng-dev ghostscript libxft-dev libfreetype6-dev libssl-dev curl wget && \
    rm -rf /var/lib/apt/lists/*
RUN curl -Ls https://micro.mamba.pm/api/micromamba/linux-64/latest | tar -xvj bin/micromamba
RUN git clone https://github.com/3dem/relion.git && cd relion && git checkout ver5.0 && \
    micromamba install -y -n base -f environment.yml && \
    micromamba clean --all --yes 
RUN wget http://www.cmake.org/files/v3.16/cmake-3.16.3.tar.gz && tar -xvf cmake-3.16.3.tar.gz && cd cmake-3.16.3 && ./configure && make -j 48 && make install
ARG MAMBA_DOCKERFILE_ACTIVATE=1
SHELL ["micromamba", "run", "-n", "base", "/bin/bash", "-c"]
RUN ldconfig && cd relion && cd build && cmake .. 
RUN cd relion/build && make -j 48
ENTRYPOINT ["micromamba", "run", "-n", "base", "/bin/bash", "-c"]
```

**Comment by biochem-fan** [comment]
I reproduced this issue on one system but am not sure what condition triggers this.
I have to investigate.

**Comment by mstabrin** [comment]
Interesting :/

So it seems to be system dependent.

If you get some answers, I would be very interested :)

**Comment by biochem-fan** [comment]
`grep -r NVCC_FLAGS_RELEASE relion-[45]/{src,cmake,CMakeLists.txt}` does not show any differences.

```
set(RELION_NVCC_FLAGS_RELEASE "${RELION_NVCC_FLAGS} --disable-warnings" CACHE STRING "")
set(CUDA_NVCC_FLAGS_RELEASE    "${RELION_NVCC_FLAGS_RELEASE}" CACHE STRING "")
```

**Comment by mstabrin** [comment]
It really does not.
What helped for me was to remove `CACHE STRING ""` from the `set()` command and things worked.

so instead of 
`set(CUDA_NVCC_FLAGS_RELEASE    "${RELION_NVCC_FLAGS_RELEASE}" CACHE STRING "")`
to use 
`set(CUDA_NVCC_FLAGS_RELEASE    "${RELION_NVCC_FLAGS_RELEASE}")`

Then the variable is not cached, but set properly in the final files

**Comment by biochem-fan** [comment]
What I don't understand is that RELION 4.0 also has `CACHE STRING ""` but works fine.

**Comment by mstabrin** [comment]
Indeed, I am also completely clueless about this behavior, but I am also not too familiar with how cmake works.
What I found is that local variables shadow cached variables.
I wonder if "CUDA_NVCC_FLAGS_RELEASE" is somewhere set somewhere else during finding the cuda package and dependencies or something.

**Comment by biochem-fan** [comment]
`grep CUDA_NVCC_FLAGS_RELEASE` does not show anything suspicious. Neither does [FindCUDA.cmake](https://github.com/Kitware/CMake/blob/master/Modules/FindCUDA.cmake) set it. If it did, both RELION 4.0 and 5.0 would be affected.

**Comment by biochem-fan** [comment]
I binary-searched the cause.
The commit 2c61af8 is OK, while the next commit f16b6c1 is broken.
Unfortunately this commit is huge, so we need more investigations.

**Comment by biochem-fan** [comment]
The following patch seems to fix the issue.
I will check whether this breaks the HIP version.

```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 8a33949c..9ae10130 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -185,7 +185,11 @@ if(MDT_TYPE_CHECK)
     add_definitions(-DMETADATA_TABLE_TYPE_CHECK)
 endif()
 
-if(CUDA)
+# ----------------------------------------------------------INCLUDE ALL BUILD TYPES---
+#This *has* to be AFTER project() but BEFORE find_package(CUDA)
+include(${CMAKE_SOURCE_DIR}/cmake/BuildTypes.cmake)
+
+ if(CUDA)
     # -----------------------------------------------------------------------------CUDA--
     # DOC: http://www.cmake.org/cmake/help/v3.0/module/FindCUDA.html
     FIND_PACKAGE(CUDA)
@@ -250,10 +254,6 @@ elseif(ALTCPU)
                SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fhonor-infinities -fhonor-nans -fsigned-zeros")
        endif()
 endif()
-
-# ----------------------------------------------------------INCLUDE ALL BUILD TYPES---
- #This *has* to be AFTER project()
- include(${CMAKE_SOURCE_DIR}/cmake/BuildTypes.cmake)
```

**Comment by biochem-fan** [comment]
`find_package(HIP)` must be done BEFORE `BuildTypes.cmake`, while `find_package(CUDA)` must be done AFTER `BuildTypes.cmake`. This is ugly...
