### ISSUE TITLE
Missing Parameters in .star file

### ISSUE THREAD

**Issue by shashi-skd** [3dem/relion#1035]
Hi,
I am ulitising cryoDRGN to run the heterogeneous reconstruction of the RAG complex (EMPIAR)-10049. While the initial training, we need to create the poses.pkl using Relion .star file, but, I got the error KeyError: '_rlnAngleRot'. I noticed that there are many missing parameters in the allimg.star file. Please have a look into this and let me know how I can approach this to resolve this issue. 
I look forward to hearing from you.
Please have a look into attached snapshot of two .star file where larger screen shows the actual .star file how it usually like and inset shows the .star file of EMPIAR-10049.
![star_files_comparison_RAG](https://github.com/3dem/relion/assets/68693325/9195cda6-3022-425b-ba6a-58b833cac1b6)

**Comment by biochem-fan** [comment]
You have to run Refine3D to get alignment parameters.

**Comment by shashi-skd** [comment]
@biochem-fan Can you please explain in a little detail?
Thanks in advance.

**Comment by biochem-fan** [comment]
Have you ever went through the RELION tutorial? If not, please do so to learn basic concepts.

Anyway, this is not a RELION bug. For usage questions, please use the CCPEM mailing list.
