### ISSUE TITLE
Relion 4.0.0 initial 3D GPU/noGPU refinement doesn't seem to put multiple threads to different CPUs

### ISSUE THREAD

**Issue by mopk** [3dem/relion#1048]
I try to benchmark RELION 4.0.0 initial 3D refinement with no GPU (Use GPU acceleration? - No) yet on numerous CPUs. I choose 1 MPI and 8 or, let's say, next time 64 threads. It's a Slurm cluster. A compute node starts and takes the job successfully. Iterations run yet too slow. Then I check resources utilization.
It turns out that the problem is that all the threads compete for one CPU only. The rest of CPUs is not used at all.

Same job type using multiple GPUs works the same way putting all the CPU threads to the same CPU (CPU 0 is the only one showing any load (100%) in my 64 CPU machine). When using GPUs I put to Which GPUs to use: field values like 0,1,2,3 or 01,2,3,0,1,2,3 or 0,1,2,3,4,5,6,7 depending on how many GPUs (4 or 8) and threads I try. NoGPU way has no such configuration.
I check where the threads are put by using top/htop with appropriate options and columns configured.

Is it by RELION 4.0.0 3D initial refinement implementation that all the threads fall on only one CPU?
Or may it be some glitch of OpenMPI I use?

**Environment:**
 - OS: CentOS 7
 - MPI runtime: OpenMPI 4.1.1-GCC-11.2.0
 - RELION version 4.0.0 
 - Memory: 512 GB (a compute node)
 - GPU: N/A

**Dataset:**
 - Box size: 256 px
 - Pixel size: 0.66 Å/px
 - Number of particles: about 1,000,000

**Job options:**
 - Type of job: 3D initial model
 - Number of MPI processes: 1
 - Number of threads: 64
 - Full command:
   ```
   relion_refine --o InitialModel/job030/run --iter 200 --grad --denovo_3dref --i Select/job027/particles.star --ctf --K 5 --sym C1 --flatten_solvent --zero_mask --dont_combine_weights_via_disc --preread_images --pool 3 --pad 1 --particle_diameter 140 --oversampling 1 --healpix_order 1 --offset_range 6 --offset_step 2 --auto_sampling --tau2_fudge 4 --j 64 --pipeline_control InitialModel/job030/
   ```

**Error message:**
N/A as there's no error

**Comment by biochem-fan** [comment]
This is not RELION's issue. This is enforced by OpenMPI (CPU pinning) and/or SLURM (cgroup resource restriction).
Did you request enough cores to SLURM?

P.S. We no longer support RELION 4.0.0. Please upgrade to at least RELION 4.1.x.

**Comment by mopk** [comment]
Thank you.
I applied OpenMPI mpirun option --bind-to none in my standard submission script in the following way:
```
mpirun --bind-to none <the rest of my options and arguments>
```
and it worked like a charm loading my multiple CPUs spreading multiple threads of 1 MPI process evenly among them.
