### ISSUE TITLE
Movie Refinement Error

### ISSUE THREAD

**Issue by bforsbe** [3dem/relion#105]
Originally reported by: **Matthew Belousoff (Bitbucket: [mbelouso](https://bitbucket.org/mbelouso), GitHub: Unknown)**

----------------------------------------

Hey there,

When I launch a movie refinement, it extracts the movie particles with no problems but when it gets the second step of refinement I keep getting the following error:

```
#!txt
MlModel::adjustGroupsForMovies ERROR: cannot find Micrographs/0001 among the groups of the model!
File: /usr/local/src/RELION/2.0beta12/relion2-beta/src/ml_model.cpp line: 686

```

This is the command that I used:

```
#!command

`which relion_preprocess_mpi` --i MotionCorr/MotionCorr/corrected_micrograph_movies.star --reextract_data_star Refine3D/job030/run_it017_data.star --part_dir MovieRefine/job044/ --list_star MovieRefine/job044/micrographs_movie_list.star --join_nr_mics 50 --extract --extract_movies --extract_size 400 --movie_name movie --first_movie_frame 1 --last_movie_frame 8 --avg_movie_frames 1 --max_mpi_nodes 8 --norm --bg_radius 160 --white_dust -1 --black_dust -1 --invert_contrast
`which relion_refine_mpi` --o MovieRefine/job044/run_ravg3_off1 --continue Refine3D/AutoRefine1/run_it017_optimiser.star --process_movies_in_batches --realign_movie_frames MovieRefine/job044/micrographs_movie_list.star --movie_frames_running_avg 3 --movie_name movie --sigma_off 1 --skip_rotate --skip_maximize  --j 1
```

----------------------------------------
- Bitbucket: https://bitbucket.org/tcblab/relion2-beta/issue/105

**Comment by martinpev** [comment]
Getting this today. Did you resolve this?

**Comment by dominikaherbst** [comment]
I had the same issue with RELION version 2.1.0

Here my workaround:
My GroupNames contained the full path to the micrographs with the file extension. 
In line 777 /src/ml_model.cpp compares the data name (_rlnMicrographName) with the GroupName without Extension.
After I removed the path and the extension in the _GroupNams of (awk scripting):
run_it017_half1_model.star, 
run_it017_half2_model.star, 
added the same _rlnGroupName, to run_it017_data.star,
and added the _rlnGroupName, to all movie extracted star files (all files in listed in micrographs_movie_list.star)
it worked!

It seems like group_names[id].withoutExtension() causes trouble if the particles have never been regrouped before. As soon as the groups are regrouped, the GroupNames are different from the mocrograph/movie names and don't contain extensions.

**Comment by joshbufton** [comment]
Hi there,

I am also having the same issue and have been struggling to solve it. Could you please clarify what you did in a bit more detail so I could also try? Do you have the awk scripts you used by any chance? 

Many thanks,
Josh

**Comment by biochem-fan** [comment]
Not relevant for 3.0. Closing.
