### ISSUE TITLE
 somthing wrong while installing

### ISSUE THREAD

**Issue by HNUWangpx** [3dem/relion#1057]
I encountered some issues while installing 

 environments:
 	Ubuntu 18.04.6 LTS (GNU/Linux 5.4.0-150-generic x86_64)
 	gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
 	g++ (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
 	cuda_12.1.r12.1/compiler.32688072_0
 	mpirun (Open MPI) 5.0.0

I performed the following actions:
	git clone https://github.com/3dem/relion.git
	cd relion
	git checkout master # or ver4.0; see below
	mkdir build
	cd build
	sudo cmake ..
	sudo make

After "sudo make" , it does not work:
*** full error output ***
[  2%] Built target class_ranker_model_file
[  2%] Built target copy_scripts
[  3%] Built target OWN_FLTK
[  3%] Building NVCC (Device) object src/apps/CMakeFiles/relion_gpu_util.dir/__/acc/cuda/cuda_kernels/relion_gpu_util_generated_helper.cu.o
nvcc fatal   : redefinition of argument 'std'
CMake Error at relion_gpu_util_generated_helper.cu.o.Release.cmake:219 (message):
  Error generating
  /home/user/software/relion/build/src/apps/CMakeFiles/relion_gpu_util.dir/__/acc/cuda/cuda_kernels/./relion_gpu_util_generated_helper.cu.o

src/apps/CMakeFiles/relion_gpu_util.dir/build.make:112: recipe for target 'src/apps/CMakeFiles/relion_gpu_util.dir/__/acc/cuda/cuda_kernels/relion_gpu_util_generated_helper.cu.o' failed
make[2]: *** [src/apps/CMakeFiles/relion_gpu_util.dir/__/acc/cuda/cuda_kernels/relion_gpu_util_generated_helper.cu.o] Error 1
CMakeFiles/Makefile2:2395: recipe for target 'src/apps/CMakeFiles/relion_gpu_util.dir/all' failed
make[1]: *** [src/apps/CMakeFiles/relion_gpu_util.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

We appreciate your help and your patience!

**Comment by biochem-fan** [comment]
As you can see in https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html,
CUDA 12.1 does not officially support Ubuntu 18.04 (which is past its end of life) and GCC 7.5.0.
I strongly argue you to update your system.

General check points:
- Make sure your compilers, `PATH`, `LD_LIBRARY_PATH` etc are not messed up by `modules`, `conda` etc. Deactivate them if necessary.
- Do not run `cmake` and `make` with `sudo`. Run them normally and only use `sudo` for `make install`.
- Delete your build directory before retrying.
- `cmake` should have printed the detected compiler versions. Check if it makes sense.

**Comment by HNUWangpx** [comment]
I also tried CUDA 10.2，but the same problem occurred

**Comment by HNUWangpx** [comment]
I tried CUDA 10.2 again, it seems work. Thank you very much!
