### ISSUE TITLE
Lack of warning / error when no files are found during import.

### ISSUE THREAD

**Issue by bforsbe** [3dem/relion#106]
Originally reported by: **A.G. Murachelli (Bitbucket: [SixmaDNA](https://bitbucket.org/SixmaDNA), GitHub: Unknown)**

----------------------------------------

Currently, if no file is found during import (e.g. Input files: *.mrcs instead of Micrographs/*.mrcs), relion does not warn the user and produces an empty star file that only contains a header. 

subsequently, displaying that star file will produce an error:
 
'Cannot read file  It does not exist'
File: /Xsoftware64/EM/relion2-beta/src/image.h line: 157

Likely, relion tries to open a file with an empty list as an argument, and fails.

subsequent jobs (e.g. motion correction) will just hang without any notice on stdout or stderr and will need to be manually marked as completed

A possible solution is to warn the user that no files have been found during import, and abort the import job in the first place. 
Also useful would be to warn the user if any or all the files in the star file are not present before starting a job.

----------------------------------------
- Bitbucket: https://bitbucket.org/tcblab/relion2-beta/issue/106

**Comment by biochem-fan** [comment]
No longer an issue.
