### ISSUE TITLE
Scheduled job does not create a symbolic link in folder

### ISSUE THREAD

**Issue by bforsbe** [3dem/relion#108]
Originally reported by: **Marcus Fislage (Bitbucket: [mfislage](https://bitbucket.org/mfislage), GitHub: [mfislage](https://github.com/mfislage))**

----------------------------------------

Every time I use schedule job I find that in the output directory (eg /Extract or /Autopick etc) Relion only creates the job folder (eg job010) but it does not create the symbolic link with the current job name linking to the job number. 

----------------------------------------
- Bitbucket: https://bitbucket.org/tcblab/relion2-beta/issue/108

**Comment by biochem-fan** [comment]
Already fixed.
