### ISSUE TITLE
Error running blush refinement 

### ISSUE THREAD

**Issue by dougbevan** [3dem/relion#1091]
This is a template for reporting bugs. Please fill in as much information as you can.

Greetings.  We are getting the following error when trying to use the blush refinement feature (all other features working fine).

Error message below.

**Environment:**
 - OS: Rocky 8
 - MPI runtime: OpenMPI 4
 - RELION version 5
 - Memory: 128GB
 - GPU: 2080 Ti

**Error message:**

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/cryoem/relion5beta-030124/miniconda3/envs/relion-5.0/lib/python3.10/site-packages/relion_blush/command_line.py", line 275, in main
    model, model_path = install_and_load_model(
  File "/opt/cryoem/relion5beta-030124/miniconda3/envs/relion-5.0/lib/python3.10/site-packages/relion_blush/util.py", line 814, in install_and_load_model
    os.makedirs(dest_dir, exist_ok=True)
  File "/opt/cryoem/relion5beta-030124/miniconda3/envs/relion-5.0/lib/python3.10/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/opt/cryoem/relion5beta-030124/miniconda3/envs/relion-5.0/lib/python3.10/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/opt/cryoem/relion5beta-030124/miniconda3/envs/relion-5.0/lib/python3.10/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  [Previous line repeated 1 more time]
  File "/opt/cryoem/relion5beta-030124/miniconda3/envs/relion-5.0/lib/python3.10/os.py", line 225, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/root/.cache'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/cryoem/relion5beta-030124/miniconda3/envs/relion-5.0/lib/python3.10/site-packages/relion_blush/command_line.py", line 275, in main
    model, model_path = install_and_load_model(
  File "/opt/cryoem/relion5beta-030124/miniconda3/envs/relion-5.0/lib/python3.10/site-packages/relion_blush/util.py", line 814, in install_and_load_model
    os.makedirs(dest_dir, exist_ok=True)
  File "/opt/cryoem/relion5beta-030124/miniconda3/envs/relion-5.0/lib/python3.10/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/opt/cryoem/relion5beta-030124/miniconda3/envs/relion-5.0/lib/python3.10/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/opt/cryoem/relion5beta-030124/miniconda3/envs/relion-5.0/lib/python3.10/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  [Previous line repeated 1 more time]
  File "/opt/cryoem/relion5beta-030124/miniconda3/envs/relion-5.0/lib/python3.10/os.py", line 225, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/root/.cache'
 
Something went wrong in the external Python call...
Command: relion_python_blush Refine3D/job008/run_it001_half2_class001_external_reconstruct.star  --gpu ,
 
---------------------------------- PYTHON ERROR ---------------------------------
   Has RELION been provided a Python interpreter with the correct environment?
   The interpreter can be passed to RELION either during Cmake configuration by
     using the Cmake flag -DPYTHON_EXE_PATH=<path/to/python/interpreter>.
   NOTE: For some modules TORCH_HOME needs to be set to find pretrained models
---------------------------------------------------------------------------------
 
  Using python executable: /opt/cryoem/relion5beta-030124/miniconda3/envs/relion-5.0/bin/python
 
 
 
Something went wrong in the external Python call...
Command: relion_python_blush Refine3D/job008/run_it001_half1_class001_external_reconstruct.star  --gpu ,
 
---------------------------------- PYTHON ERROR ---------------------------------
   Has RELION been provided a Python interpreter with the correct environment?
   The interpreter can be passed to RELION either during Cmake configuration by
     using the Cmake flag -DPYTHON_EXE_PATH=<path/to/python/interpreter>.
   NOTE: For some modules TORCH_HOME needs to be set to find pretrained models
---------------------------------------------------------------------------------
 
  Using python executable: /opt/cryoem/relion5beta-030124/miniconda3/envs/relion-5.0/bin/python
 
 
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:
 
  Process name: [[29056,1],1]
  Exit code:    1
--------------------------------------------------------------------------

**Comment by biochem-fan** [comment]
> File "/opt/cryoem/relion5beta-030124/miniconda3/envs/relion-5.0/lib/python3.10/os.py", line 225, in makedirs
> mkdir(name, mode)
> PermissionError: [Errno 13] Permission denied: '/root/.cache'

Your model weight is stored in the administrator's area, which is inaccessible from normal users.
Please make a globally readable model directory (e.g. `/opt/cryoem/relion-weights`), set it to the `TORCH_HOME` environmental variable and reinstall RELION. This will reinstall model weights.

**Comment by dougbevan** [comment]
Thanks for your assistance in solving this..  Yes, it looks like TORCH_HOME was set incorrectly, and also we had an FTP security issue to work around on our network (the weights were not downloaded anywhere.  All is fine now.

**Comment by donghuachensu** [comment]
Hi All,

I was doing a Refine3D job with Blush  on a cluster with the following environment and got a similar error (see run.out and run.err on the bottom). When I did the exactly same Refine3D job but without Blush, it worked successfully. Any suggestions would be greatly appreciated!


Environment:

    OS: RHEL 8.6

    MPI runtime: mpirun (Open MPI) 4.1.6rc4

    RELION version: 5.0-beta-3-commit-d08e4d

    Memory: 11264MiB

    GPU: NVIDIA GeForce RTX 2080 Ti 

Dataset:

    Box size: 384

    Pixel size: 1.4 Å/px

    Number of particles: 512,812

    Description: 

Job options:

    Type of job: Refine3D

    Number of MPI processes: 9

    Number of threads: 1

    Full command: `which relion_refine_mpi` --o Refine3D/job478/run --auto_refine --split_random_halves --i Select/job474/particles.star --ref Class3D/job415/run_it050_class001.mrc --trust_ref_size --ini_high 60 --blush  --dont_combine_weights_via_disc --scratch_dir /lscratch/tmp --pool 3 --pad 2  --ctf --particle_diameter 537 --flatten_solvent --zero_mask --solvent_mask MaskCreate/job418/mask.mrc --solvent_correct_fsc  --oversampling 1 --healpix_order 4 --auto_local_healpix_order 4 --offset_range 5 --offset_step 2 --sym C1 --low_resol_join_halves 40 --norm --scale  --j 1 --gpu ""  --pipeline_control Refine3D/job478/


Error message: 
run.out
Oversampling= 0 NrHiddenVariableSamplingPoints= 3150
 OrientationalSampling= 3.75 NrOrientations= 150
 TranslationalSampling= 2.8 NrTranslations= 21
=============================
 Oversampling= 1 NrHiddenVariableSamplingPoints= 100800
 OrientationalSampling= 1.875 NrOrientations= 1200
 TranslationalSampling= 1.4 NrTranslations= 84
=============================
 Expectation iteration 1
3.55/16.38 min ............~~(,_,">                                           [oo]
6.00/14.98 min .......................~~(,_,">
8.15/14.82 min ................................~~(,_,">
9.92/14.53 min ........................................~~(,_,">
11.53/14.72 min ..............................................~~(,_,">
13.13/14.63 min .....................................................~~(,_,">
14.23/14.47 min ..........................................................~~(,_,">
14.45/14.45 min ............................................................~~(,_,">
 Averaging half-reconstructions up to 59.7333 Angstrom resolution to prevent diverging orientations ...
 Note that only for higher resolutions the FSC-values are according to the gold-standard!
 Calculating solvent-corrected gold-standard FSC ...
 Maximization (with Blush regularization)...
000/??? sec ~~(,_,">                                                          [oo]


run.err:
 WARNING: FSC curve between unmasked maps never drops below 0.8. Using unmasked FSC as FSC_true... 
 WARNING: This message should go away during the later stages of refinement!

Something went wrong in the external Python call...
Command: relion_python_blush Refine3D/job478/run_it001_half1_class001_external_reconstruct.star  --gpu , 

---------------------------------- PYTHON ERROR ---------------------------------
   Has RELION been provided a Python interpreter with the correct environment?
   The interpreter can be passed to RELION either during Cmake configuration by
     using the Cmake flag -DPYTHON_EXE_PATH=<path/to/python/interpreter>.
   NOTE: For some modules TORCH_HOME needs to be set to find pretrained models
---------------------------------------------------------------------------------

  Using python executable: 

Something went wrong in the external Python call...
Command: relion_python_blush Refine3D/job478/run_it001_half2_class001_external_reconstruct.star  --gpu , 

---------------------------------- PYTHON ERROR ---------------------------------
   Has RELION been provided a Python interpreter with the correct environment?
   The interpreter can be passed to RELION either during Cmake configuration by
     using the Cmake flag -DPYTHON_EXE_PATH=<path/to/python/interpreter>.
   NOTE: For some modules TORCH_HOME needs to be set to find pretrained models
---------------------------------------------------------------------------------

  Using python executable: 

--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[6004,1],1]
  Exit code:    1
--------------------------------------------------------------------------

**Comment by donghuachensu** [comment]
@biochem-fan 
Do you have any suggestions about the above error I had? Our cluster Admin is waiting for what could be wrong for Relion5's installation. Thank you!

**Comment by biochem-fan** [comment]
@donghuachensu
I cannot answer unless you explain how you installed RELION.

**Comment by donghuachensu** [comment]
@biochem-fan 
Thanks for your reply. Our cluster admin told me that he found where the issue was on the Relion5's installation.
