### ISSUE TITLE
How to get blush model wieght installed and sourced in a location accessible to all?

### ISSUE THREAD

**Issue by abasle** [3dem/relion#1093]
Hello,

We follow the instruxction to get blush working with relion 5 and it works.

But following these instructions:
https://github.com/3dem/relion-blush?tab=readme-ov-file#model-weights

`sudo pip install .`

does install the model weight in root folder .cache. I'd imagine not using root would install in the user home .cache.

We would like to install the model weight in a folder of our choice where all users can access (read). How to setup relion 5 / blush to source the model weights from a central location?

Cheers,
Arnaud

**Comment by biochem-fan** [comment]
This is explained in the documentation.

> it’s recommended to set the TORCH_HOME directory by including the flag -DTORCH_HOME_PATH=path/to/torch/home. Otherwise, it will be downloaded to the default location (usually ~/.cache/torch).

https://relion.readthedocs.io/en/release-5.0/Installation.html#setup-a-conda-environment

If this is not clear enough, please reopen this issue.
