### ISSUE TITLE
merging dataset in relion

### ISSUE THREAD

**Issue by KMS-Rock** [3dem/relion#1095]
I have 10000 micrographs which I have split into 1000, 1000, and 8000 and analyzed up to 2D classification, can I merge all three and use to generate the 3D initial model and 3D classification in the relion. Any command to merge the three batch file, if yes which file from 2D output I should use?
Thanks

**Comment by biochem-fan** [comment]
Yes, use the Join Star job on particle STAR files.

Please don't ask usage questions here. These should be posted to the CCPEM mailing list. This GitHub is for bug reports.
