### ISSUE TITLE
3D classification fails on iteration 2, but only when multiple classes are requested

### ISSUE THREAD

**Issue by kbisikalo** [3dem/relion#1100]
This is a template for reporting bugs. Please fill in as much information as you can.

**Describe your problem**

I am trying to reprocess a relatively small dataset of particles exported from Cryosparc, and consistently running into the issue with 3D classification. No matter which reference model I use (initial reconstruction in relion on a refined map from cryosparc), the job fails at iteration 2,  but only when I set the number of classes to be more than 1. If it's just 1 class, it works with or without GPU acceleration, with or without MPI, etc. MPI works fine in other jobs. I am at a loss at this point, as having separating particles into clean and junk classes is the whole point for me to use this protocol . 

**Environment:**
 - OS: Ubuntu 22.04.4 LTS 
 - MPI runtime: (Open MPI) 4.1.2
 - RELION version: RELION-4.0.1-commit-e5c483
 - Memory: 512 Gb
 - GPU: single RTX A5000

**Dataset:**
 - Box size: 500 pix
 - Pixel size: 1,36 Å/px
 - Number of particles: 3-5k depending on stage from which I try to classify
 - Description: Flavivirus

**Job options:**
 - Type of job: Class3D
 - Number of MPI processes: 2
 - Number of threads: 15
 - Full command (see `note.txt` in the job directory):
   ```
   ``which relion_refine_mpi` --o Class3D/job090/run --i Class2D/job084/run_it300_data.star --ref InitialModel/job088/initial_model.mrc --firstiter_cc --ini_high 40 --dont_combine_weights_via_disc --preread_images  --pool 28 --pad 2  --ctf --iter 20 --tau2_fudge 3 --particle_diameter 600 --K 3 --flatten_solvent --strict_highres_exp 2 --oversampling 1 --healpix_order 2 --sigma_ang 1.66667 --offset_range 5 --offset_step 2 --allow_coarser_sampling --sym I2 --norm --scale  --j 15 --gpu ""  --pipeline_control Class3D/job090/
   ```

**Error message:**

Please cite the *full* error message as the example below.

```
in: /mnt/54a72433-dee5-4a88-a717-8505a73baa51/Relion/relion/src/healpix_sampling.cpp, line 915
ERROR: 
HealpixSampling::selectOrientationsWithNonZeroPriorProbability BUG: best_idir < 0
in: /mnt/54a72433-dee5-4a88-a717-8505a73baa51/Relion/relion/src/healpix_sampling.cpp, line 915
ERROR: 
HealpixSampling::selectOrientationsWithNonZeroPriorProbability BUG: best_idir < 0
=== Backtrace  ===
=== Backtrace  ===
//mnt/54a72433-dee5-4a88-a717-8505a73baa51/Relion/relion/build/bin/relion_refine_mpi(_ZN11RelionErrorC1ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES7_l+0x7d) [0x5b202350d63d]
//mnt/54a72433-dee5-4a88-a717-8505a73baa51/Relion/relion/build/bin/relion_refine_mpi(+0x73665) [0x5b20234a3665]
//mnt/54a72433-dee5-4a88-a717-8505a73baa51/Relion/relion/build/bin/relion_refine_mpi(_ZN11MlOptimiser27expectationSetupCheckMemoryEi+0xbe5) [0x5b20236da275]
//mnt/54a72433-dee5-4a88-a717-8505a73baa51/Relion/relion/build/bin/relion_refine_mpi(_ZN14MlOptimiserMpi11expectationEv+0x7db) [0x5b202353813b]
//mnt/54a72433-dee5-4a88-a717-8505a73baa51/Relion/relion/build/bin/relion_refine_mpi(_ZN14MlOptimiserMpi7iterateEv+0x1ff) [0x5b202354863f]
//mnt/54a72433-dee5-4a88-a717-8505a73baa51/Relion/relion/build/bin/relion_refine_mpi(main+0x79) [0x5b20234f8269]
/lib/x86_64-linux-gnu/libc.so.6(+0x29d90) [0x791d33e29d90]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x80) [0x791d33e29e40]
//mnt/54a72433-dee5-4a88-a717-8505a73baa51/Relion/relion/build/bin/relion_refine_mpi(_start+0x25) [0x5b20234fb805]
==================
ERROR: 
HealpixSampling::selectOrientationsWithNonZeroPriorProbability BUG: best_idir < 0
//mnt/54a72433-dee5-4a88-a717-8505a73baa51/Relion/relion/build/bin/relion_refine_mpi(_ZN11RelionErrorC1ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES7_l+0x7d) [0x61ad1874e63d]
//mnt/54a72433-dee5-4a88-a717-8505a73baa51/Relion/relion/build/bin/relion_refine_mpi(+0x73665) [0x61ad186e4665]
//mnt/54a72433-dee5-4a88-a717-8505a73baa51/Relion/relion/build/bin/relion_refine_mpi(_ZN11MlOptimiser27expectationSetupCheckMemoryEi+0xbe5) [0x61ad1891b275]
//mnt/54a72433-dee5-4a88-a717-8505a73baa51/Relion/relion/build/bin/relion_refine_mpi(_ZN14MlOptimiserMpi11expectationEv+0x7db) [0x61ad1877913b]
//mnt/54a72433-dee5-4a88-a717-8505a73baa51/Relion/relion/build/bin/relion_refine_mpi(_ZN14MlOptimiserMpi7iterateEv+0x1ff) [0x61ad1878963f]
//mnt/54a72433-dee5-4a88-a717-8505a73baa51/Relion/relion/build/bin/relion_refine_mpi(main+0x79) [0x61ad18739269]
/lib/x86_64-linux-gnu/libc.so.6(+0x29d90) [0x783111a29d90]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x80) [0x783111a29e40]
//mnt/54a72433-dee5-4a88-a717-8505a73baa51/Relion/relion/build/bin/relion_refine_mpi(_start+0x25) [0x61ad1873c805]
==================
ERROR: 
HealpixSampling::selectOrientationsWithNonZeroPriorProbability BUG: best_idir < 0
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 1 in communicator MPI_COMM_WORLD
with errorcode 1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
[dx3-970-30015.ad.helsinki.fi:58946] 1 more process has sent help message help-mpi-api.txt / mpi-abort
[dx3-970-30015.ad.helsinki.fi:58946] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages

```

**Comment by biochem-fan** [comment]
Does this happen only on this dataset? Are you aware that the symmetry convention for the icosahedral symmetry is different between RELION and CS?

**Comment by kbisikalo** [comment]
> Does this happen only on this dataset? Are you aware that the symmetry convention for the icosahedral symmetry is different between RELION and CS?

This is my first dataset that I am trying to process in RELION, so I don't know if it is a more general issue. I will be trying the relion  tutorial dataset to test that. 
I am aware of the convention differences, but that wouldn't explain the failure of the job with model generated in relion. 
Is there something more I can do to help diagnose the problem?

**Comment by biochem-fan** [comment]
> This is my first dataset that I am trying to process in RELION, so I don't know if it is a more general issue. I will be trying the relion tutorial dataset to test that.

Yes, this is a very good idea.

> that wouldn't explain the failure of the job with model generated in relion.

Initial model generation of highly symmetrical molecules is hard; does the initial model by RELION make sense?

During early stages of data processing, Class3D in C1 is often better, because bad particles do not have the symmetry.

**Comment by kbisikalo** [comment]
> Initial model generation of highly symmetrical molecules is hard; does the initial model by RELION make sense?
Yes, if I run it with the option of running in C1 and applying symmetry later I get a reasonable looking flavivirus.

> During early stages of data processing, Class3D in C1 is often better, because bad particles do not have the symmetry.
Okay! I have not thought about that, I will try this method ASAP.

**Comment by kbisikalo** [comment]
Okay, so after trying the same pipeline for the tutorial dataset, and trying to do 3D classification on my dataset with C1 symmetry, I am approaching conclusion that my dataset and particle might be the problem. Both the tutorial and C1 classification worked with no problems.

**Comment by biochem-fan** [comment]
With the I2 symmetry, does making the angular sampling finer help?

**Comment by kbisikalo** [comment]
That does not appear to be the case. The job still fails with the same error message.

**Comment by biochem-fan** [comment]
I see. Please continue processing (Refine3D, CtfRefine, etc) and see if the problem with I2 symmetry persists on cleaner particles.

**Comment by kbisikalo** [comment]
I have done another 6 round of 2d, and on those particles with a very fine sampling, 3d classification doesn't fail so far!

**Comment by biochem-fan** [comment]
Thanks for testing. I will close this issue.
