### ISSUE TITLE
error: unrecognized command line option ‘-std=c++14’

### ISSUE THREAD

**Issue by donghuachensu** [3dem/relion#1112]
Hi,

I am trying to compile relion5-beta but got this error during "make -j 8", any suggestions? Thanks.

[ 71%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/spherical-harmonics/SphericalHarmonics.cc.o
Linking CXX static library ../../lib/librelion_lib.a
[ 71%] Built target relion_lib
[ 71%] Building NVCC (Device) object src/apps/CMakeFiles/relion_jaz_gpu_util.dir/__/jaz/cuda/./relion_jaz_gpu_util_generated_test00.cu.o
nvcc warning : The -std=c++14 flag is not supported with the configured host compiler. Flag will be ignored.
cc: error: unrecognized command line option ‘-std=c++14’
CMake Error at relion_jaz_gpu_util_generated_test00.cu.o.cmake:206 (message):
  Error generating

  /xxx/relion/build/src/apps/CMakeFiles/relion_jaz_gpu_util.dir/__/jaz/cuda/./relion_jaz_gpu_util_generated_test00.cu.o

make[2]: *** [src/apps/CMakeFiles/relion_jaz_gpu_util.dir/__/jaz/cuda/./relion_jaz_gpu_util_generated_test00.cu.o] Error 1
make[1]: *** [src/apps/CMakeFiles/relion_jaz_gpu_util.dir/all] Error 2
make: *** [all] Error 2

**Comment by biochem-fan** [comment]
Please respect our issue template. What version of the CUDA SDK and the C++ compiler are you using?

**Comment by donghuachensu** [comment]
Sorry. I should have reported them.
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)
cuda/cuda_10.2.89_440.33.01_linux/bin/nvcc
NVIDIA GeForce 2080Ti

Are they too old?

**Comment by biochem-fan** [comment]
> Are they too old?

Yes. Please read our installation manual.

> C++ compiler:
> RELION 5.0 requires a C++ compiler that fully supports the C++14 standard. For GCC, this means [version 5.0 or later](https://gcc.gnu.org/projects/cxx-status.html#cxx14). Note that GCC 4.8, which comes with RedHat Enterprise Linux / Cent OS 7.x, is too old.
https://relion.readthedocs.io/en/latest/Installation.html#installation

**Comment by donghuachensu** [comment]
Thanks!
I have missed that part for sure.
