### ISSUE TITLE
3D classification: mpirun exited on signal 9

### ISSUE THREAD

**Issue by bforsbe** [3dem/relion#112]
Originally reported by: **hbwangnih (Bitbucket: [hbwangnih](https://bitbucket.org/hbwangnih), GitHub: Unknown)**

----------------------------------------

Hi,

I am doing 3Dcalssification on a small helical sample data set (~8000 particles). The command is:
`which relion_refine_mpi` --o Class3D/job016/run --i Select/job010/particles.sta
r --ref ref/3zys_helix_masked.mrc --firstiter_cc --ini_high 60 --dont_combine_we
ights_via_disc --pool 3 --ctf --ctf_corrected_ref --iter 25 --tau2_fudge 4 --par
ticle_diameter 550 --K 4 --flatten_solvent --zero_mask --oversampling 1 --healpi
x_order 4 --offset_range 10 --offset_step 2 --sym C1 --norm --scale  --helix --h
elical_inner_diameter 35 --helical_outer_diameter 410 --helical_z_percentage 0.3
 --helical_nr_asu 8 --helical_twist_initial 27.3 --helical_rise_initial 7.52 --h
elical_symmetry_search --helical_twist_min 26 --helical_twist_max 31 --helical_r
ise_min 7 --helical_rise_max 9 --sigma_tilt 5 --sigma_psi 5 --helical_sigma_dist
ance 0.666667 --j 4

I tried with different number of MPI and threads, but the job always stopped after a few minutes with the following message.

-------------------------------------
mpirun noticed that process rank 4 with PID 0 on node localhost exited on signal 9 (Killed).
-------------------------------------

Any idea?

thanks,
Huaibin

----------------------------------------
- Bitbucket: https://bitbucket.org/tcblab/relion2-beta/issue/112

**Comment by biochem-fan** [comment]
Old version.
