### ISSUE TITLE
Bad Extracted Particles with Edge and Fringe Artefacts

### ISSUE THREAD

**Issue by TimHo-droid** [3dem/relion#1144]
Hi there,

I'm currently using Relion 5.0 to process my dataset. I've followed the typical workflow or importing my micrographs, doing motion correction, followed by CTF estimation, then autopicking and finally particle extraction. 

I'm inspecting my extracted particles and I've noticed many of them looking as such (see attached image) 
![Screenshot from 2024-06-12 19-33-59](https://github.com/3dem/relion/assets/172551892/d41383fc-39f8-4cf9-8087-ba76a49d110c)
and I don't think I want to take these forward with 2D classification. Has anyone ever seen anything like this? 

I believe the ones with "barcode" (top left particle) is an artefact from extracted particles are the edge of the micrograph and the ones with the "fringes" (top right) is an artefact from the edge of the beam. Is there any way to avoid getting these bad extracted particles, by parameter changes or subset selection of the good particles? Please note: I've extracted about 2 million particles.

Thanks in advance!

**Comment by biochem-fan** [comment]
You don't have to worry about them; just proceed to Class2D. If the barcode is narrow, such particles can be used. If they are too wide, they will go to bad classes. Sample for frindges.

If you really care about barcodes, remove particles too close to the micrograph edges by filtering by rlnCoordinateX and Y. This can be done with awk, or Subset selection jobs.
