### ISSUE TITLE
Suggestion to relion 2 manual concerning re-extraction

### ISSUE THREAD

**Issue by bforsbe** [3dem/relion#115]
Originally reported by: **Marcus Fislage (Bitbucket: [mfislage](https://bitbucket.org/mfislage), GitHub: [mfislage](https://github.com/mfislage))**

----------------------------------------

Currently the manual states for re-extraction that one needs to input a _data.star file for this task. However, I wanted to do re-extraction after 3D classification followed by subset selection and re-grouping. The subset selection procedure only gives a particle.star file.
I hope it does not create further trouble down the line, but I used that particle.star file in particle extraction under the I/O tab in the field called refined particles star file.

If this is correct it would be nice if the manual mentions that one can also use the particle.star file after subset selection as an input file for "refined particles star file".

----------------------------------------
- Bitbucket: https://bitbucket.org/tcblab/relion2-beta/issue/115

**Comment by biochem-fan** [comment]
Too old issue.
