### ISSUE TITLE
Refine auto 3D error: Helical reconstruction

### ISSUE THREAD

**Issue by PoojaAsthana** [3dem/relion#1153]
Hi all,

I am running 3D auto-refine job for a helical reconstruction using relion 3.1.3, I have been running into the issue of using the wrong particle radius. I tried using different values but did not succeed. Can any of you point out what could be done to resolve this? Attached a screenshot of the run.err as well

Error: helix.cpp::chechParametersFor3DHelicalReconstruction(): Particle radius should be > 2 and < half the box size!

The details are:

Relion version: 3.1.3
No. of particles: 21,000
pixel size 0.865 rescaled to 3.44
mask diameter: 320 A
tube diameter: 1-320 A
Box size: 384 px rescaled to 96px
No. of MPI procs: 5
No. of threads: 30

From note.txt:
 ++++ Executing new job on Tue Jun 25 10:25:22 2024
 ++++ with the following command(s): 
`which relion_refine_mpi` --o Refine3D/job155/run --auto_refine --split_random_halves --i Extract/job137/particles.star --ref EMD_6350_96_3_44_lp10.mrc --firstiter_cc --ini_high 20 --dont_combine_weights_via_disc --pool 30 --pad 2  --skip_gridding  --ctf --particle_diameter 320 --flatten_solvent --zero_mask --oversampling 1 --healpix_order 4 --auto_local_healpix_order 5 --offset_range 55 --offset_step 2 --sym C1 --low_resol_join_halves 40 --norm --scale  --helix --helical_inner_diameter 1 --helical_outer_diameter 320 --ignore_helical_symmetry --sigma_tilt 5 --sigma_psi 3.33333 --sigma_rot 0 --helical_sigma_distance 0.666667 --helical_keep_tilt_prior_fixed --j 30 --gpu "0,1,2,3" --dont_check_norm --ignore_helical_symmetry --iter 1 --trust_ref_size option --pipeline_control Refine3D/job155/
 ++++ 

Thanks
<img width="829" alt="Screen Shot 2024-06-25 at 10 18 15 AM" src="https://github.com/3dem/relion/assets/139927640/fda17424-7d25-4046-9a80-032885ad7aa9">

**Comment by biochem-fan** [comment]
What was the solution? Please report how you fixed the issue for others.

**Comment by fenglinlimomo** [comment]
Hi [PoojaAsthana], I am experiencing the same error, I adjusted my helical outer diameter to make sure it is > 2 and < half box size, but it still doesn't work. Did you find a way to fix this error? Could you share your solution? Thank you in advance!
