### ISSUE TITLE
CUDA memory allocation problem in class2d

### ISSUE THREAD

**Issue by bforsbe** [3dem/relion#117]
Originally reported by: **Peng Ge (Bitbucket: [gepeng1983](https://bitbucket.org/gepeng1983), GitHub: [gepeng1983](https://github.com/gepeng1983))**

----------------------------------------

I have an issue running Relion2 (2.0.1) on K80 cards. For every run, the first iteration finishes ok, but on the second iteration, it shows an exception:
ERROR: unknown error in /home/pge/Software/relion2-beta-a6225608e270/src/gpu_utils/cuda_projector.cu at line 126 (error-code 30)
if cuda_texture is turned off, the error becomes
ERROR: unknown error in /home/pge/Software/relion2-beta-a6225608e270/src/gpu_utils/cuda_backprojector.cu at line 38 (error-code 30)
The lines that are generating the errors seem to be allocating for device memory.
If the broken run is continued, the then first iteration (iter 2) runs ok but it fails on the next iteration. The same dataset was working fine with the same code on a local workstation with two 1080 cards, without generating the same problem.

----------------------------------------
- Bitbucket: https://bitbucket.org/tcblab/relion2-beta/issue/117

**Comment by biochem-fan** [comment]
Old version.
