### ISSUE TITLE
Relion Job struck at - Relion MPI Setup - for multinode jobs

### ISSUE THREAD

**Issue by iam-mg-Harish** [3dem/relion#1171]
I had build Relion 5 with the following command, and while testing I observed that Class2D jobs submitted on a single node runs, but the same Job submitted as multinode jobs fails to start. I am using the same MPI which was used to build relion. There was no network issue between the nodes, I had tested an non relion MPI job with 2 nodes.

Environment:
 - OS: Amazon linux 2
 - MPI runtime: OpenMPI 4.1.6
 - RELION version Relion 5.0
 - Memory: aws g4dn.12xlarge node (192 GB RAM - 48vCPU)
 - GPU: 4 GPU - Nividia T4 16 GB

Dataset: relion50_tutorial_precalculated_results.tar.gz from ftp://ftp.mrc-lmb.cam.ac.uk/pub/scheres/relion50_tutorial_precalculated_results.tar.gz

Job options:
#!/bin/bash

#SBATCH --ntasks=24
#SBATCH --cpus-per-task=4
#SBATCH --partition=relion
#SBATCH --error=Class2D/job036/run.err
#SBATCH --output=Class2D/job036/run.out

mpirun `which relion_refine_mpi` --o Class2D/job036/run --iter 25 --i Extract/job012/particles.star --dont_combine_weights_via_disc --preread_images  --pool 30 --pad 2  --ctf  --tau2_fudge 2 --particle_diameter 200 --K 100 --flatten_solvent  --zero_mask  --center_classes  --oversampling 1 --psi_step 12 --offset_range 5 --offset_step 2 --norm --scale  --j 4 --gpu ""  --pipeline_control Class2D/job036/

Error message:
run.out
RELION version: 5.0-beta-3-commit-7d79f3
Precision: BASE=double, CUDA-ACC=single

 === RELION MPI setup ===
 + Number of MPI processes                 = 24
 + Number of threads per MPI process       = 4
 + Total number of threads therefore       = 96
 + Leader      (0) runs on host            = relion-dy-g5-queue-5

run.err
WARNING: Open MPI accepted a TCP connection from what appears to be a
another Open MPI process but cannot find a corresponding process
entry for that peer.

This attempted connection will be ignored; your MPI job may or may not
continue properly.

  Local host: relion-dy-g5-queue-6
  PID:        12503
--------------------------------------------------------------------------
[relion-dy-g5-queue-6][[43072,1],15][btl_tcp_endpoint.c:626:mca_btl_tcp_endpoint_recv_connect_ack] received unexpected process identifier [[43072,1],20]
[relion-dy-g5-queue-6][[43072,1],16][btl_tcp_endpoint.c:626:mca_btl_tcp_endpoint_recv_connect_ack] received unexpected process identifier [[43072,1],19]
[relion-dy-g5-queue-6][[43072,1],17][btl_tcp_endpoint.c:626:mca_btl_tcp_endpoint_recv_connect_ack] received unexpected process identifier [[43072,1],19]
[relion-dy-g5-queue-6][[43072,1],18][btl_tcp_endpoint.c:626:mca_btl_tcp_endpoint_recv_connect_ack] received unexpected process identifier [[43072,1],21]
[relion-dy-g5-queue-6][[43072,1],19][btl_tcp_endpoint.c:626:mca_btl_tcp_endpoint_recv_connect_ack] received unexpected process identifier [[43072,1],21]
[relion-dy-g5-queue-6][[43072,1],20][btl_tcp_endpoint.c:626:mca_btl_tcp_endpoint_recv_connect_ack] received unexpected process identifier [[43072,1],15]
[relion-dy-g5-queue-6][[43072,1],21][btl_tcp_endpoint.c:626:mca_btl_tcp_endpoint_recv_connect_ack] received unexpected process identifier [[43072,1],15]
[relion-dy-g5-queue-6][[43072,1],22][btl_tcp_endpoint.c:626:mca_btl_tcp_endpoint_recv_connect_ack] received unexpected process identifier [[43072,1],14]
[relion-dy-g5-queue-6][[43072,1],23][btl_tcp_endpoint.c:626:mca_btl_tcp_endpoint_recv_connect_ack] received unexpected process identifier [[43072,1],14]
[relion-dy-g5-queue-6][[43072,1],14][btl_tcp_endpoint.c:626:mca_btl_tcp_endpoint_recv_connect_ack] received unexpected process identifier [[43072,1],20]
[relion-dy-g5-queue-6][[43072,1],12][btl_tcp_endpoint.c:626:mca_btl_tcp_endpoint_recv_connect_ack] received unexpected process identifier [[43072,1],13]

cmake command and log:
-- The C compiler identification is GNU 7.3.1
-- The CXX compiler identification is GNU 7.3.1
-- Check for working C compiler: /opt/amazon/openmpi/bin/mpicc
-- Check for working C compiler: /opt/amazon/openmpi/bin/mpicc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /opt/amazon/openmpi/bin/mpicxx
-- Check for working CXX compiler: /opt/amazon/openmpi/bin/mpicxx -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- BUILD TYPE set to the default type:  'Release'
-- Using provided CUDA_ARCH=75
-- CUDA enabled - Building CUDA-accelerated version of RELION
-- Setting cpu precision to double
-- Setting accelerated code precision to single
-- Found CUDA: /usr/local/cuda (found version "12.2")
-- Using cuda wrapper to compile....
-- Cuda version is >= 7.5 and single-precision build, enable double usage warning.
-- Found MPI_C: /opt/amazon/openmpi/lib64/libmpi.so
-- Found MPI_CXX: /opt/amazon/openmpi/lib64/libmpi.so
-- MPI_INCLUDE_PATH : /opt/amazon/openmpi/include
-- MPI_LIBRARIES : /opt/amazon/openmpi/lib64/libmpi.so
-- MPI_CXX_INCLUDE_PATH : /opt/amazon/openmpi/include
-- MPI_CXX_LIBRARIES : /opt/amazon/openmpi/lib64/libmpi.so
-- CMAKE_C_COMPILER : /opt/amazon/openmpi/bin/mpicc
-- CMAKE_CXX_COMPILER : /opt/amazon/openmpi/bin/mpicxx
-- MPI_C_COMPILER : /opt/amazon/openmpi/bin/mpicc
-- MPI_CXX_COMPILER : /opt/amazon/openmpi/bin/mpicxx
-- Try OpenMP C flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Try OpenMP CXX flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Found OpenMP: -fopenmp
-- CMAKE_CXX_COMPILER_ID : GNU
-- Looking for XOpenDisplay in /usr/lib64/libX11.so;/usr/lib64/libXext.so
-- Looking for XOpenDisplay in /usr/lib64/libX11.so;/usr/lib64/libXext.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Looking for IceConnectionNumber in ICE
-- Looking for IceConnectionNumber in ICE - found
-- Found X11: /usr/lib64/libX11.so
-- --------------------------------------------------------
-- -------- NO EXISTING FLTK LIBRARIES WHERE FOUND. -------
-- -------------- FLTK WILL BE DOWNLOADED AND -------------
-- --------------- BUILT DURING COMPILE-TIME. -------------
-- --------------------------------------------------------
-- ---- A WORKING INTERNET CONNECTION WILL BE REQUIRED. ---
-- --------------------------------------------------------
-- no previous fltk found, the following paths are set for libs/headers TO BE built
-- FLTK_INCLUDE_DIR: /apps/relion/relion5/external/fltk/include
-- FLTK_LIBRARIES:   /apps/relion/relion5/external/fltk/lib/libfltk.so
-- --------------------------------------------------------
-- ------ REQUIRED FFTW LIBRARIES WHERE NOT FOUND. --------
-- -------------- FFTW WILL BE DOWNLOADED AND -------------
-- --------------- BUILT DURING COMPILE-TIME. -------------
-- --------------------------------------------------------
-- ---- A WORKING INTERNET CONNECTION WILL BE REQUIRED. ---
-- --------------------------------------------------------
-- Looking for sincos
-- Looking for sincos - found
-- Looking for __sincos
-- Looking for __sincos - not found
-- Found TIFF: /usr/lib64/libtiff.so (found version "4.0.3")
-- Found ZLIB: /usr/lib64/libz.so (found version "1.2.7")
-- Found PNG: /usr/lib64/libpng.so (found version "1.5.13")
-- Found JPEG: /usr/lib64/libjpeg.so
-- Using Python executable: /apps/miniconda3/envs/relion-5.0/bin/python
-- Will try to find Torch home directory...
-- Using Torch home: /apps/relion/relion-weights
-- Omitting download of model weights for dependent packages
-- Building static libs (larger build size and binaries)
Running apps/CMakeLists.txt...
-- CMAKE_BINARY_DIR:/apps/relion/relion5/build
-- Git commit ID: b978db95709703a2798aca79402019152861603c
-- CMAKE_C_FLAGS : -std=c99  -fopenmp
-- CMAKE_CXX_FLAGS : -fPIC -std=c++14  -fopenmp
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    ALLOW_CTF_IN_SAGD
    CudaTexture

-- Build files have been written to: /apps/relion/relion5/build

**Comment by iam-mg-Harish** [comment]
the command used for cmake is 
sudo cmake -DCMAKE_INSTALL_PREFIX=/apps/relion/relion5/installation_dir -DCUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda -DCUDA=ON -DCudaTexture=ON -DCUDA_ARCH=75 -DPYTHON_EXE_PATH=/apps/miniconda3/envs/relion-5.0/bin/python -DFORCE_OWN_TBB=ON -DMKLFFT=OFF -DFORCE_OWN_FLTK=ON -DFORCE_OWN_FFTW=ON -DALLOW_CTF_IN_SAGD=OFF -DFETCH_WEIGHTS=OFF -DTORCH_HOME_PATH=/apps/relion/relion-weights -DCMAKE_C_COMPILER=/opt/amazon/openmpi/bin/mpicc -DCMAKE_CXX_COMPILER=/opt/amazon/openmpi/bin/mpicxx -DMPI_C_COMPILER=/opt/amazon/openmpi/bin/mpicc -DMPI_CXX_COMPILER=/opt/amazon/openmpi/bin/mpicxx .. 2>&1 | tee cmake-log.`date '+%d%b%Y'`

**Comment by biochem-fan** [comment]
This is not a RELION bug but an AWS specific usage issue. Because RELION developers don't use AWS, we cannot help. You may be able to get an answer by asking at the CCPEM mailing list.
