### ISSUE TITLE
Conda "defaults" channel should be removed from environment.yml

### ISSUE THREAD

**Issue by jjv5** [3dem/relion#1178]
The defaults channel from Anaconda requires a license (per computer) for institutions over 200 people. Anaconda has begun enforcing this.  https://www.theregister.com/2024/08/08/anaconda_puts_the_squeeze_on/

Only python, pip and setuptools are installed by conda (the rest of deps are pip). These are all available from the conda-forge channel, which does not have licensing restrictions.

**Comment by biochem-fan** [comment]
Thank you very much for pointing this out. I will remove the line after testing it myself later today.

> Only python, pip and setuptools are installed by conda (the rest of deps are pip). These are all available from the conda-forge channel

Why do they (python, pip, setuptools) get installed from the "default" channel, even though "conda-forge" provides them and is listed earlier than the "default"?

**Comment by biochem-fan** [comment]
>> Only python, pip and setuptools are installed by conda (the rest of deps are pip). These are all available from the conda-forge channel
> 
> Why do they (python, pip, setuptools) get installed from the "default" channel, even though "conda-forge" provides them and is listed earlier than the "default"?

In my test, `conda list` confirmed all packages including these three came from `conda-forge` or `pypi`.

Anyway, I deleted the `default` channel to make sure (commit 12cf15d).
