### ISSUE TITLE
Miniforge installation for multiple user environment

### ISSUE THREAD

**Issue by robertthomasbyrne** [3dem/relion#1180]
Hi,

I am having some difficulty setting up Miniforge with Relion 5.0 in a multiple user environment as described here (https://relion.readthedocs.io/en/release-5.0/Installation.html). Briefly:

- Miniforge was installed in a subdirectory of DCMAKE_INSTALL_PREFIX (`/sw64/relion/5.0/amd_cuda-12.4/miniforge`) as follows:

`curl  -L -O "https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-$(uname)-$(uname -m).sh" --output-dir /sw64/relion/5.0/amd_cuda-12.4/miniforge`
`chmod 775 /sw64/relion/5.0/amd_cuda-12.4/miniforge/Miniforge3-$(uname)-$(uname -m).sh`
`/sw64/relion/5.0/amd_cuda-12.4/miniforge/Miniforge3-$(uname)-$(uname -m).sh -b -u -p /sw64/relion/5.0/amd_cuda-12.4/miniforge`
`export PATH="$/sw64/relion/5.0/amd_cuda-12.4/miniforge:$PATH"`

- The Relion 5.0 environment was created as follows:

`conda env create -f environment.yml`

- Relion 5.0 was then installed using the following `cmake` options:

`cmake \`
`-DCMAKE_INSTALL_PREFIX=/sw64/relion/5.0/amd_cuda-12.4 \`
`-DPYTHON_EXE_PATH=/sw64/relion/5.0/amd_cuda-12.4/miniforge/envs/relion-5.0/bin/python \`
`-DTORCH_HOME_PATH=/sw64/relion/5.0/amd_cuda-12.4/torch \`
`-DFORCE_OWN_FFTW=ON \`
`-DAMDFFTW=ON \`
`-DCUDA_ARCH=80`

The installation completed without any obvious problems. All users can successfully run jobs that do not require the Miniforge environment.

It seems that only the user who performed the installation can run jobs that require the Miniforge environment. For example, I can run a Dynamight job with the precalculated results from the betagal tutorial:

`user1@server 23:41:15 > relion_python_dynamight optimize-deformations  --refinement-star-file Refine3D/job029/run_data.star --output-directory DynaMight/test-1/ --initial-model Refine3D/job029/run_class001.mrc --n-gaussians 8000 --initial-threshold 0.015 --regularization-factor 1 --n-threads 1 --gpu-id 0`
`Training on GPU 0`
`Initializing the particle dataset`
`Assigning a diameter of 299 angstrom`
`...`

If a different user runs the same command, however, the job fails immediately. The output suggests that the Miniforge environment cannot be loaded successfully:

`user2@server 23:32:30 > relion_python_dynamight optimize-deformations  --refinement-star-file Refine3D/job029/run_data.star --output-directory DynaMight/test-1/ --initial-model Refine3D/job029/run_class001.mrc --n-gaussians 8000 --initial-threshold 0.015 --regularization-factor 1 --n-threads 1 --gpu-id 0`

`**Traceback** (most recent call last):
  File "<string>", line 1, in <module>
  File "/sw64/relion/5.0/amd_cuda-12.4/miniforge/envs/relion-5.0/lib/python3.10/site-packages/dynamight/__init__.py", line 2, in <module>
    from .inverse_deformations import optimize_inverse_deformations
  File "/sw64/relion/5.0/amd_cuda-12.4/miniforge/envs/relion-5.0/lib/python3.10/site-packages/dynamight/inverse_deformations/__init__.py", line 1, in <module>
    from .optimize_inverse_deformations import optimize_inverse_deformations
  File "/sw64/relion/5.0/amd_cuda-12.4/miniforge/envs/relion-5.0/lib/python3.10/site-packages/dynamight/inverse_deformations/optimize_inverse_deformations.py", line 13, in <module>
    from ..models.decoder import InverseDisplacementDecoder
  File "/sw64/relion/5.0/amd_cuda-12.4/miniforge/envs/relion-5.0/lib/python3.10/site-packages/dynamight/models/decoder.py", line 12, in <module>
    from dynamight.utils.utils_new import PointProjector, PointsToImages, \
  File "/sw64/relion/5.0/amd_cuda-12.4/miniforge/envs/relion-5.0/lib/python3.10/site-packages/dynamight/utils/utils_new.py", line 17, in <module>
    from sklearn.decomposition import PCA
  File "/sw64/relion/5.0/amd_cuda-12.4/miniforge/envs/relion-5.0/lib/python3.10/site-packages/sklearn/__init__.py", line 83, in <module>
    from .base import clone
  File "/sw64/relion/5.0/amd_cuda-12.4/miniforge/envs/relion-5.0/lib/python3.10/site-packages/sklearn/base.py", line 19, in <module>
    from .utils import _IS_32BIT
  File "/sw64/relion/5.0/amd_cuda-12.4/miniforge/envs/relion-5.0/lib/python3.10/site-packages/sklearn/utils/__init__.py", line 19, in <module>
    from . import _joblib, metadata_routing`

`  File "/sw64/relion/5.0/amd_cuda-12.4/miniforge/envs/relion-5.0/lib/python3.10/site-packages/sklearn/utils/_joblib.py", line 7, in <module>`
`    import joblib`
`ModuleNotFoundError: No module named 'joblib'`

`---------------------------------- PYTHON ERROR ---------------------------------`
`   Has RELION been provided a Python interpreter with the correct environment?`
`   The interpreter can be passed to RELION either during Cmake configuration by`
`     using the Cmake flag -DPYTHON_EXE_PATH=<path/to/python/interpreter>.`
`---------------------------------------------------------------------------------`

`  Using python executable: /sw64/relion/5.0/amd_cuda-12.4/miniforge/envs/relion-5.0/bin/python`

This is surprising since the path to the Python executable matches the path provided for DPYTHON_EXE_PATH.

Is it generally possible for multiple users to share a single Miniforge environment? If so, do the other users need to update their Miniforge installation (e.g. the `~/.condarc` or `~/.conda/environments.txt` files) so that the environment can be used?

Many thanks,
Rob

**Comment by biochem-fan** [comment]
> Is it generally possible for multiple users to share a single Miniforge environment?

I haven't tested this with Miniforge but it is definitely possible with Miniconda3. Because Miniforge and Miniconda3 are basically  the same except the default channel definitions, I guess this should work with Miniforge as well.

Does your problem occur with all users or only with a particular user? Doesn't the user set an incompatible `PYTHONHOME` and/or `PYTHONPATH` environmental variables in `.bashrc` etc?
