### ISSUE TITLE
Build and test for Linux/ARM64

### ISSUE THREAD

**Issue by odidev** [3dem/relion#1192]
## Description 

For aarch64 platform, I have built "RELION" from source. 

  

## Steps  

Following [STEPS](https://relion.readthedocs.io/en/latest/Installation.html) were used for the building and installation: 

  
~~~
$ sudo apt install cmake git build-essential mpi-default-bin mpi-default-dev libfftw3-dev libtiff-dev libpng-dev ghostscript libxft-dev 

$ git clone https://github.com/3dem/relion.git 

$ git checkout 3.1.0 

$ mkdir build 

$ cd build 

$ cmake .. 

$ make 
~~~
  

The binaries are produced in the build/bin directory. 

  

## Outcome 

To validate that the build was successful we ran version check. The version info returned matched expected value.  

  

All this information is also added to [Software Ecosystem Dashboard for Arm](https://www.arm.com/developer-hub/ecosystem-dashboard/).

**Comment by biochem-fan** [comment]
Thanks for testing. If this is not a bug report, may I close this issue?

**Comment by odidev** [comment]
Thanks for the response. We just build and run Relion on linux/ARM64. Yes, you can close the issue.
