### ISSUE TITLE
relion 4.0 GUI error in display 2D classification results

### ISSUE THREAD

**Issue by jxzhang24** [3dem/relion#1204]
finished 2D classification job ,and click display out :optimiser.star
terminal reported 

 WARNING: you cannot sort particles and use a maximum number of images. Ignoring the latter...
in: /lustre/home/EM-software/source/relion-4.0.1/src/strings.cpp, line 214
ERROR:
Error in textToFloat
=== Backtrace  ===
relion_display(_ZN11RelionErrorC1ERKSsS1_l+0x41) [0x423861]
relion_display(_Z11textToFloatPKciSs+0xc5) [0x440105]
relion_display(_ZN9Displayer4readEiPPc+0x7d2) [0x4e6f62]
relion_display(main+0x27) [0x41ca67]
/lib64/libc.so.6(__libc_start_main+0xf5) [0x2b7ace253445]
relion_display() [0x41d28f]
==================
ERROR:
Error in textToFloat

**Comment by biochem-fan** [comment]
Did it show a dialog box? Probably you put non-numerical values to text boxes.

**Comment by jxzhang24** [comment]
> Did it show a dialog box? Probably you put non-numerical values to text boxes.

![屏幕截图 2024-11-18 113014](https://github.com/user-attachments/assets/0cff9e3e-205e-4bfe-b949-fae7a5c231e2)
i didn't change any values, if click the display， it will report error.

**Comment by jxzhang24** [comment]
> Please try putting "3" or "-1" to `Sigma contrast`. The field must have a numerical value.
I put 3 and it looks good! Thank you very much
