### ISSUE TITLE
"Authorization required, but no authorization protocol specified" appears, and the MPI operation cannot continue

### ISSUE THREAD

**Issue by ThatIsMyUsername** [3dem/relion#1211]
Hello,
When I run the MPI task, I get the message "Authorization required, but no authorization protocol specified.
Authorization required, but no authorization protocol specified."

It's stuck here. It can't go on. Sometimes restarting the server will solve the problem. Sometimes it will fix itself the next day. But the problem comes up after a while.

If you can solve this problem, I would be very grateful!
![666666](https://github.com/user-attachments/assets/6578647d-120a-41d6-9604-b95e204caa61)

**Comment by biochem-fan** [comment]
Aren't you running RELION as `root`, which is highly discouraged?

See also:
- https://github.com/open-mpi/ompi/issues/11553
- https://stackoverflow.com/questions/48833451/no-protocol-specified-when-running-a-sudo-su-app-on-ubuntu-linux

**Comment by ThatIsMyUsername** [comment]
> Aren't you running RELION as `root`, which is highly discouraged?
> 
> See also:
> 
> * [Authorization required, but no authorization protocol specified open-mpi/ompi#11553](https://github.com/open-mpi/ompi/issues/11553)
> * https://stackoverflow.com/questions/48833451/no-protocol-specified-when-running-a-sudo-su-app-on-ubuntu-linux

No, I running things as normal user, and this user is newly created by me. I am looking for a feasible solution from the page you recommended.  I hope we can solve this problem.

**Comment by xinsheng44** [comment]
When it doesn't run normally, I use "ps aux | grep mpirun" to check the mpi running status, and found that only the mpi process I just ran was in sleep state. The following is the display result "wxs 706423 3.7 0.0 46984 6144 pts/118 S+ 21:50 0:00 mpirun -n 3 /data/wxs/relion_pipeline/relion-ver5.0/build/bin/relion_refine_mpi --o relion_29k_wxs_bin1.1/Refine3D/job009/run --auto_refine --split_random_halves --ios relion_29k_wxs_bin1.1/matching_optimisation_set.star --ref ". This situation has occurred many times. I hope to ask for your help

**Comment by biochem-fan** [comment]
If this is an OpenMPI issue, how about building RELION against other MPI runtime (e.g. Intel MPI or MPICH)?

**Comment by ThatIsMyUsername** [comment]
I just solved this problem by typing "export HWLOC_COMPONENTS=-gl". But I want to know how it works. Thank you very much.

**Comment by biochem-fan** [comment]
I am closing this because this is not a RELION problem but an OpenMPI issue.
