### ISSUE TITLE
relion_helix_toolbox doesn't work

### ISSUE THREAD

**Issue by bforsbe** [3dem/relion#122]
Originally reported by: **Jing_basel (Bitbucket: [Jing_basel](https://bitbucket.org/Jing_basel), GitHub: Unknown)**

----------------------------------------

Dear all,
I would like to use the region_helix_tool box to get rid of some particles with huge out of plane tilt angle and soon I realised no matter what I type after the "region_helix_toolbox" command, it always prints out a list of options followed by the same error message:

Only one option can be specified at one time! valid_options = 127
File: /scicore/home/basler/wangji/src/relion2.0beta/src/apps/helix_toolbox.cpp line: 294

Is there something specific need to be done to compile the helix_tool box? There are plenty nice options of this tool box, it would be great to have it work.

Thanks a lot,

Jing

----------------------------------------
- Bitbucket: https://bitbucket.org/tcblab/relion2-beta/issue/122

**Comment by munanbt2004** [comment]
Hi, 
I was trying to run a 2D class average in relion using GPU acceleration. I am getting this following error. Any idea what I am doing wrong.

ERROR: unknown error in /programs/x86_64-linux/relion/2.1b1_cu8.0/src/gpu_utils/cuda_projector.cu at line 126 (error-code 30)
[bc-gpu1:05575] *** Process received signal ***
[bc-gpu1:05575] Signal: Segmentation fault (11)
[bc-gpu1:05575] Signal code:  (-6)
[bc-gpu1:05575] Failing at address: 0x82ab000015c7
[bc-gpu1:05575] [ 0] /lib64/libpthread.so.0(+0xf5e0)[0x2b64806745e0]
[bc-gpu1:05575] [ 1] /lib64/libpthread.so.0(raise+0x2b)[0x2b64806744ab]
[bc-gpu1:05575] [ 2] /programs/x86_64-linux/relion/2.1b1_cu8.0/lib/librelion_gpu_util.so(_ZN13CudaProjector9setMdlDimEiiiiiii+0x5bb)[0x2b647f51e20b]
[bc-gpu1:05575] [ 3] /programs/x86_64-linux/relion/2.1b1_cu8.0/lib/librelion_gpu_util.so(_ZN14MlDeviceBundle22setupFixedSizedObjectsEv+0x252)[0x2b647f525c52]
[bc-gpu1:05575] [ 4] /programs/x86_64-linux/relion/2.1b1_cu8.0/lib/librelion_lib.so(_ZN14MlOptimiserMpi11expectationEv+0x118d)[0x2b64756f344d]
[bc-gpu1:05575] [ 5] /programs/x86_64-linux/relion/2.1b1_cu8.0/lib/librelion_lib.so(_ZN14MlOptimiserMpi7iterateEv+0x96)[0x2b64757014f6]
[bc-gpu1:05575] [ 6] /programs/x86_64-linux/relion/2.1b1_cu8.0/bin/relion_refine_mpi(main+0x69)[0x40a3a9]
[bc-gpu1:05575] [ 7] /lib64/libc.so.6(__libc_start_main+0xf5)[0x2b64808a2c05]
[bc-gpu1:05575] [ 8] /programs/x86_64-linux/relion/2.1b1_cu8.0/bin/relion_refine_mpi[0x40a511]
[bc-gpu1:05575] *** End of error message ***
ERROR: unknown error in /programs/x86_64-linux/relion/2.1b1_cu8.0/src/gpu_utils/cuda_projector.cu at line 126 (error-code 30)
[bc-gpu1:05576] *** Process received signal ***
[bc-gpu1:05576] Signal: Segmentation fault (11)
[bc-gpu1:05576] Signal code:  (-6)
[bc-gpu1:05576] Failing at address: 0x82ab000015c8
[bc-gpu1:05576] [ 0] /lib64/libpthread.so.0(+0xf5e0)[0x2b721ae745e0]
[bc-gpu1:05576] [ 1] /lib64/libpthread.so.0(raise+0x2b)[0x2b721ae744ab]
[bc-gpu1:05576] [ 2] /programs/x86_64-linux/relion/2.1b1_cu8.0/lib/librelion_gpu_util.so(_ZN13CudaProjector9setMdlDimEiiiiiii+0x5bb)[0x2b7219d1e20b]
[bc-gpu1:05576] [ 3] /programs/x86_64-linux/relion/2.1b1_cu8.0/lib/librelion_gpu_util.so(_ZN14MlDeviceBundle22setupFixedSizedObjectsEv+0x252)[0x2b7219d25c52]
[bc-gpu1:05576] [ 4] /programs/x86_64-linux/relion/2.1b1_cu8.0/lib/librelion_lib.so(_ZN14MlOptimiserMpi11expectationEv+0x118d)[0x2b720fef344d]
[bc-gpu1:05576] [ 5] /programs/x86_64-linux/relion/2.1b1_cu8.0/lib/librelion_lib.so(_ZN14MlOptimiserMpi7iterateEv+0x96)[0x2b720ff014f6]
[bc-gpu1:05576] [ 6] /programs/x86_64-linux/relion/2.1b1_cu8.0/bin/relion_refine_mpi(main+0x69)[0x40a3a9]
[bc-gpu1:05576] [ 7] /lib64/libc.so.6(__libc_start_main+0xf5)[0x2b721b0a2c05]
[bc-gpu1:05576] [ 8] /programs/x86_64-linux/relion/2.1b1_cu8.0/bin/relion_refine_mpi[0x40a511]
[bc-gpu1:05576] *** End of error message ***
ERROR: unknown error in /programs/x86_64-linux/relion/2.1b1_cu8.0/src/gpu_utils/cuda_projector.cu at line 126 (error-code 30)
[bc-gpu1:05577] *** Process received signal ***
[bc-gpu1:05577] Signal: Segmentation fault (11)
[bc-gpu1:05577] Signal code:  (-6)
[bc-gpu1:05577] Failing at address: 0x82ab000015c9
[bc-gpu1:05577] [ 0] /lib64/libpthread.so.0(+0xf5e0)[0x2b631af855e0]
[bc-gpu1:05577] [ 1] /lib64/libpthread.so.0(raise+0x2b)[0x2b631af854ab]
[bc-gpu1:05577] [ 2] /programs/x86_64-linux/relion/2.1b1_cu8.0/lib/librelion_gpu_util.so(_ZN13CudaProjector9setMdlDimEiiiiiii+0x5bb)[0x2b6319e2f20b]
[bc-gpu1:05577] [ 3] /programs/x86_64-linux/relion/2.1b1_cu8.0/lib/librelion_gpu_util.so(_ZN14MlDeviceBundle22setupFixedSizedObjectsEv+0x252)[0x2b6319e36c52]
[bc-gpu1:05577] [ 4] /programs/x86_64-linux/relion/2.1b1_cu8.0/lib/librelion_lib.so(_ZN14MlOptimiserMpi11expectationEv+0x118d)[0x2b631000444d]
[bc-gpu1:05577] [ 5] /programs/x86_64-linux/relion/2.1b1_cu8.0/lib/librelion_lib.so(_ZN14MlOptimiserMpi7iterateEv+0x96)[0x2b63100124f6]
[bc-gpu1:05577] [ 6] /programs/x86_64-linux/relion/2.1b1_cu8.0/bin/relion_refine_mpi(main+0x69)[0x40a3a9]
[bc-gpu1:05577] [ 7] /lib64/libc.so.6(__libc_start_main+0xf5)[0x2b631b1b3c05]
[bc-gpu1:05577] [ 8] /programs/x86_64-linux/relion/2.1b1_cu8.0/bin/relion_refine_mpi[0x40a511]
[bc-gpu1:05577] *** End of error message ***
ERROR: unknown error in /programs/x86_64-linux/relion/2.1b1_cu8.0/src/gpu_utils/cuda_projector.cu at line 126 (error-code 30)
[bc-gpu1:05574] *** Process received signal ***
[bc-gpu1:05574] Signal: Segmentation fault (11)
[bc-gpu1:05574] Signal code:  (-6)
[bc-gpu1:05574] Failing at address: 0x82ab000015c6
[bc-gpu1:05574] [ 0] /lib64/libpthread.so.0(+0xf5e0)[0x2aef95cfb5e0]
[bc-gpu1:05574] [ 1] /lib64/libpthread.so.0(raise+0x2b)[0x2aef95cfb4ab]
[bc-gpu1:05574] [ 2] /programs/x86_64-linux/relion/2.1b1_cu8.0/lib/librelion_gpu_util.so(_ZN13CudaProjector9setMdlDimEiiiiiii+0x5bb)[0x2aef94ba520b]
[bc-gpu1:05574] [ 3] /programs/x86_64-linux/relion/2.1b1_cu8.0/lib/librelion_gpu_util.so(_ZN14MlDeviceBundle22setupFixedSizedObjectsEv+0x252)[0x2aef94bacc52]
[bc-gpu1:05574] [ 4] /programs/x86_64-linux/relion/2.1b1_cu8.0/lib/librelion_lib.so(_ZN14MlOptimiserMpi11expectationEv+0x118d)[0x2aef8ad7a44d]
[bc-gpu1:05574] [ 5] /programs/x86_64-linux/relion/2.1b1_cu8.0/lib/librelion_lib.so(_ZN14MlOptimiserMpi7iterateEv+0x96)[0x2aef8ad884f6]
[bc-gpu1:05574] [ 6] /programs/x86_64-linux/relion/2.1b1_cu8.0/bin/relion_refine_mpi(main+0x69)[0x40a3a9]
[bc-gpu1:05574] [ 7] /lib64/libc.so.6(__libc_start_main+0xf5)[0x2aef95f29c05]
[bc-gpu1:05574] [ 8] /programs/x86_64-linux/relion/2.1b1_cu8.0/bin/relion_refine_mpi[0x40a511]
[bc-gpu1:05574] *** End of error message ***
ERROR: unknown error in /programs/x86_64-linux/relion/2.1b1_cu8.0/src/gpu_utils/cuda_projector.cu at line 127 (error-code 30)
ERROR: unknown error in /programs/x86_64-linux/relion/2.1b1_cu8.0/src/gpu_utils/cuda_projector.cu at line 127 (error-code 30)
