### ISSUE TITLE
running unblur creates no job/Micrographs subfolder

### ISSUE THREAD

**Issue by bforsbe** [3dem/relion#125]
Originally reported by: **Wolfgang Lugmayr (Bitbucket: [wlugmayr](https://bitbucket.org/wlugmayr), GitHub: Unknown)**

----------------------------------------

and therefore empty corrected*star files.

i run relion2 on a virtual machine image with ext4 filesystem and ubuntu 14.04.5 lts.
since i have no gpu there, i tried to run the tutorial with unblur.

unblur itself runs fine with a handmade link from a .mrcs file to .mrc on this environment.

relion2 creates a MotionCorr/unblur folder with an empty run.err, the run.* and some starfiles. the .gui_tmpout prints until "... using Tim Grant's UNBLUR ...", the .gui_tmperr file is empty.

on another real node, relion2 creates a MotionCorr/unblur/Micrographs folder and the corresponding scripts etc.

----------------------------------------
- Bitbucket: https://bitbucket.org/tcblab/relion2-beta/issue/125

**Comment by biochem-fan** [comment]
Unblur is no longer supported in RELION.
