### ISSUE TITLE
Suggestion for XXXcoresXXX

### ISSUE THREAD

**Issue by bforsbe** [3dem/relion#150]
Originally reported by: **ncoudray (Bitbucket: [ncoudray](https://bitbucket.org/ncoudray), GitHub: Unknown)**

----------------------------------------

Hi,

It is said that " XXXcoresXXX is the number of MPI processes times the number of threads". Unless I misunderstood, it looks like in most of the cases in RELION, the actual number of cores is

 ( Nb_of_MPI  - 1 ) * Nb_of_threads +1

because of  the MPI is the master and doesn't have any thread associated with it. It may be convenient to either change XXXcoresXXX  or create another variable which reflects this actual number of cores used in a master/slave situation,

Thanks,

Nicolas

----------------------------------------
- Bitbucket: https://bitbucket.org/tcblab/relion2-beta/issue/150

**Comment by biochem-fan** [comment]
This should be handled by a job submission system (or a wrapper).
