### ISSUE TITLE
relion_prepare_subtomograms.py crash under special case

### ISSUE THREAD

**Issue by bforsbe** [3dem/relion#154]
Originally reported by: **Lu Gan (Bitbucket: [lu_gan](https://bitbucket.org/lu_gan), GitHub: Unknown)**

----------------------------------------

The current version of this script will fail to create the particles_subtomo.star file if SkipCTFCorrection = True *and* Relion2 = True.

Under this condition, the script does not create the directory OutputDir/results. There's probably a more elegant solution, but I was able to fix this problem by inserting this one-liner between lines 388 and 389:
     
```
#!python
      os.system('mkdir %s' %(OutputDir + 'results'))
```

Lines 388 - 390 now read:

```
#!python
    if Relion2 == True:
      os.system('mkdir %s' %(OutputDir + 'results'))
      outputstarname_read =  OutputDir + 'results/micrographs_ctf.star'
```

----------------------------------------
- Bitbucket: https://bitbucket.org/tcblab/relion2-beta/issue/154

**Comment by biochem-fan** [comment]
We will not fix this script. We will have a completely new CryoET pipeline in the next major update.
