### ISSUE TITLE
Question: Slurm script for gpu cluster

### ISSUE THREAD

**Issue by bforsbe** [3dem/relion#156]
Originally reported by: **monash_lancew (Bitbucket: [monash_lancew](https://bitbucket.org/monash_lancew), GitHub: Unknown)**

----------------------------------------

We have been trying to run Relion on our gpu cluster and have had a number of errors when trying to do mulitnode job submission. Could you please provide suggestions/instructions?

The cluster nodes are 24 cores, 240GB ram, 4 x K80 gpus

9 mpi tasks with 4 threads per task over 2 nodes works by requesting 5 tasks per node. Trying to go to three nodes results in errors as the mpi ranks aren't distributed correctly. What settings need to be put into relion and the corresponding sbatch script that will allow for more than two nodes? 

----------------------------------------
- Bitbucket: https://bitbucket.org/tcblab/relion2-beta/issue/156

**Comment by JuhaHuiskonen** [comment]
It seems that this is still open?

One can achieve even GPU distribution by following the advice here: https://hpc.nih.gov/apps/RELION/index.html

Briefly, the idea is to create a SLURM hosts file with a script.  This file lists the first GPU node 5 times, and the rest 4 times.
