### ISSUE TITLE
Particle sorting with different size template

### ISSUE THREAD

**Issue by bforsbe** [3dem/relion#158]
Originally reported by: **Andreas Schenk (Bitbucket: [andschenk](https://bitbucket.org/andschenk), GitHub: [andschenk](https://github.com/andschenk))**

----------------------------------------

With Relion2 it is possible to autopick particles using references with a different pixel size by explicitly giving the reference pixel size in the GUI. But once these particles are picked and extracted they cannot be sorted using the same references, as the particle sorting doesn't give the option to specify the pixel size of the references. Running the sorting against these references will lead to the error:

ParticleSorter::calculateFeaturesOneParticle ERROR: References and images do not have the same size!

Having the reference pixel size option in Particle Sorting analog to the one in Autopicking would be very useful to sort the picked particles.

----------------------------------------
- Bitbucket: https://bitbucket.org/tcblab/relion2-beta/issue/158

**Comment by biochem-fan** [comment]
Particle sorting has been removed.
