### ISSUE TITLE
GUI crashes when read-only disk

### ISSUE THREAD

**Issue by bforsbe** [3dem/relion#167]
Originally reported by: **James Alexander Geraets (Bitbucket: [geraets](https://bitbucket.org/geraets), GitHub: [geraets](https://github.com/geraets))**

----------------------------------------

Clearly, relion GUI needs to be launched within a read-write disk environment. However disks can become read-only for a number of reasons; particularly a problem when e.g.X-forwarding the GUI from a remote cluster. The GUI will then crash when trying to submit a job, for example: 

Filename::touch ERROR: Cannot open file: .lock_default_pipeline.star
File: ... ... ... /src/filename.cpp line: 440

This should instead throw non-fatal error within the GUI, otherwise the job options selected are frustratingly lost to the user.

----------------------------------------
- Bitbucket: https://bitbucket.org/tcblab/relion2-beta/issue/167

**Comment by baibing7713661** [comment]
<img width="1165" alt="qq20171102-175450 2x" src="https://user-images.githubusercontent.com/21249922/32339885-5fe18e1a-bff9-11e7-9a2d-85d6f1197ede.png">
My hard disk has the read-write right but still errors occurs when executing relion, any suggestion?

**Comment by baibing7713661** [comment]
I have the same problem. A read-write right disk and this problem occurs when the second time running in the same working space. Any idea how to fix it?

**Comment by biochem-fan** [comment]
Use `--readonly`.
