### ISSUE TITLE
extract particles fails due to duplicate path...

### ISSUE THREAD

**Issue by bforsbe** [3dem/relion#169]
Originally reported by: **Josue Gomez Blanco (Bitbucket: [josuegbl](https://bitbucket.org/josuegbl), GitHub: [josuegbl](https://github.com/josuegbl))**

----------------------------------------

Maybe this issue is not an error, but I going to report just in case...
I have run an extract particles step in relion GUI. I select the path of the coordinates, and set its suffix. The command that I execute is: 

`which relion_preprocess_mpi` --i CtfFind/job008/micrographs_ctf.star --coord_dir AutoPick/job009/betagal/Micrographs/ --coord_suffix _autopick.star --part_star Extract/job015/particles.star --part_dir Extract/job015/ --extract --extract_size 100 --norm --bg_radius 37 --white_dust -1 --black_dust -1 --invert_contrast

After that, there are a warning: 
Warning: coordinate file AutoPick/job009/betagal/Micrographs/betagal/Micrographs/Falcon_2012_06_12-17_26_54_0_autopick.star does not exist...

Note that betagal/Micrographs is repeated in the path, although i wrote 
 --coord_dir AutoPick/job009/betagal/Micrographs/
 Of course, if I excecute changing the param "--coord_dir" to  AutoPick/job009/ instead of  
AutoPick/job009/betagal/Micrographs/, the extract particle run properly.
Is it the expected  behavior or there are a bug in the construction of the path to find the coordinates?
Thanks in advance.
JOsue

----------------------------------------
- Bitbucket: https://bitbucket.org/tcblab/relion2-beta/issue/169

**Comment by biochem-fan** [comment]
Not relevant for 3.0. Closing.
