### ISSUE TITLE
Class3D --always_cc problem

### ISSUE THREAD

**Issue by bforsbe** [3dem/relion#178]
Originally reported by: **Wolfgang Lugmayr (Bitbucket: [wlugmayr](https://bitbucket.org/wlugmayr), GitHub: Unknown)**

----------------------------------------

when we submit a job with the always_cc parameter we have to following error:

---
WARNING: There are only 0 particles in group 1
WARNING: There are only 0 particles in group 2
WARNING: There are only 0 particles in group 3
WARNING: There are only 0 particles in group 4
WARNING: There are only 0 particles in group 5
:
 Expectation iteration 1 of 1
  14/  14 sec ............................................................~~(,_,">
 Maximization ...
000/??? sec ~~(,_,">                                                          [oo] DIRECT_A1D_ELEM(sigma2, i)= -nan
BackProjector::reconstruct: ERROR: unexpectedly small, yet non-zero sigma2 value, this should not happen...a
File: /data/netapp/cssb-iss/sw/relion/2.0beta-git/src/backprojector.cpp line: 835
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 1 in communicator MPI_COMM_WORLD 
---

If we skip this parameter then it works and finds particles in the groups.

our call:

`which relion_refine_mpi` --o Class3D/job528/run --i ./Import/job526/test_5000.star --ref ./Import/job342/IR_6A.mrc --firstiter_cc --ini_high 8 --dont_combine_weights_via_disc --pool 3 --ctf --ctf_corrected_ref --iter 1 --tau2_fudge 4 --particle_diameter 400 --K 1 --flatten_solvent --zero_mask --solvent_mask ./MaskCreate/job345/mask.mrc --skip_align  --sym C1 --norm --scale  --j 1 --always_cc

----------------------------------------
- Bitbucket: https://bitbucket.org/tcblab/relion2-beta/issue/178

**Comment by bforsbe** [comment]
This should be fixed in v2.0.3

**Comment by bforsbe** [comment]
Not fixed. 2.0.0-2.0.6 fails on both CPU and GPU runs with --always_cc

**Comment by Howyoudoonething** [comment]
Is this bug fixed in the Relion/2.1.0? I encountered the same problem with the latest version of relion.

**Comment by biochem-fan** [comment]
Too old issue. Anyway, ` --always_cc` is not recommended.
