### ISSUE TITLE
Autorefine3d crashes with 640 box size

### ISSUE THREAD

**Issue by bforsbe** [3dem/relion#180]
Originally reported by: **Alexey Shvetsov (Bitbucket: [alexxy](https://bitbucket.org/alexxy), GitHub: [alexxy](https://github.com/alexxy))**

----------------------------------------

Hi!

I'm trying to use relion2 autorefine3d procedure for virus particle with I symmetry. Box size is 640 pixels. Pixel size is 0.859A. Autorefine constantly crashed with following error

idx= 0 ori_idx= 3170407311 idx_start= -1610927296 idx_stop= -939917296 packed_size= 3170407311
MlWsumModel::pack: idx != idx_stop-idx_start
File: ~/Src/relion2-beta/src/ml_model.cpp line: 1323

----------------------------------------
- Bitbucket: https://bitbucket.org/tcblab/relion2-beta/issue/180

**Comment by andschenk** [comment]
Hi Bjoern,

sorry to necro this thread, but we currently run into what I think is the same bug. 
In Relion 2.1b1 we try to run a 3D refine job with a box size of 720. After entering the last iteration, Relion stops with the following error message:

idx= 0ori_idx= 4511105467 idx_start= 18446744072098624320 idx_stop= 4511105467 packed_size= 4511105467
ERROR: 
MlWsumModel::pack: idx != idx_stop-idx_start

I quickly checked the ml_model code and the indexes are already defined as unsigned long long. To me it looks like there is a underflow in idx_start. Is there anything we can try to get the job to run with this huge box size? 
I saw that there is additional debug code for the packing. Would it help you if we switch on DEBUG_PACK and provide you the more detailed output?

Thanks,
Andreas

**Comment by bforsbe** [comment]
Hi Andreas,

I suspect the same. There are two instances in src/ml_model.cpp where idx_start is initialized as 
```
idx_start = piece * MAX_PACK_SIZE;
```
If the multiplication overflows the int "piece" before casting to ULL, we might help things by casting before the multiplication;
```
idx_start = (usigned long long)piece * MAX_PACK_SIZE;
```
It would be really helpful if you could make this modification on both positions ( in both MlWsumModel::pack and MlWsumModel::unpack ), recompile and run again (a continuation from the last completed iteration and the additional flag  ```--force_converge``` should still throw the same error). 

Thanks!

**Comment by andschenk** [comment]
Hi Bjoern,

I finally got around testing your suggested changes.  With the explicit casts for piece the 3D refine with the 720 box size runs through. Thank you for your help.

Best,
Andreas
