### ISSUE TITLE
GUI collapse menu suggestion

### ISSUE THREAD

**Issue by bforsbe** [3dem/relion#188]
Originally reported by: **kylelmorris (Bitbucket: [kylelmorris](https://bitbucket.org/kylelmorris), GitHub: [kylelmorris](https://github.com/kylelmorris))**

----------------------------------------

Hi guys, great job thank you, small suggestion. I ssh into my machine and run Relion this way often. On a 13inch display the GUI doesn't fit. It would be great if the GUI, particularly the job reporting panels could be resized. Maybe this is a pain or too fancy. Perhaps if sections could be collapsed then this would improve the screen economy? I don't always need to see the Finished jobs, Running jobs and Input to this job panels and need to know more what the run.out and run.err panels display and sometimes the other way around. 

Hope that helps! Thanks again for the great software!

----------------------------------------
- Bitbucket: https://bitbucket.org/tcblab/relion2-beta/issue/188

**Comment by lu-anaphase** [comment]
I'd like to second this enhancement suggestion. Now that I'm getting used to the pipeline as an electronic notebook of sorts, I've been using very long job names. To see the full name of a Finished or ScheduleJob, I've had to drag the slider on the lower portion of each panel. It would be more convenient to be able to resize the GUI as Kyle Morris suggested, if only to take advantage of the modern 16:9 monitor aspect ratio.

**Comment by biochem-fan** [comment]
We won't do this ourselves but a new GUI being developer by CCPEM might.
