### ISSUE TITLE
Out of memory Error in 3D auto-refine

### ISSUE THREAD

**Issue by YehudaHalfon** [3dem/relion#192]
Hi all, 
I wrote this on the CCPEM and was asked to open an issue here.

When we are running 3D auto-refine at the last Iteration (when it converge the data) it gives us this warning: "The available space on the GPU after initialization (188 MB) might be insufficient for the expectation step.", then it crushes with the error " ERROR: out of memory in /opt/relion-master/src/gpu_utils/cuda_backprojector.cu at line 41 (error-code 2)"

The box size is 400x400 and we have about 40k particles.

Our setup is:
2X Xeon E5-2623 V3
126 GiB RAm
4X GTX 1080 founder 

We run it at:
4 MPI
2 Threads 
With the flag --maxsig 500
and on a SSD scratch disk

Thanks a lot,
Yehuda Halfon

**Comment by dkimanius** [comment]
Could you also check the amount of free memory on the GPU before the start of the refinement? In case there are other processes taking up memory you'd expect this.

**Comment by YehudaHalfon** [comment]
According to nvidia-smi it's empty before.

**Comment by bforsbe** [comment]
could you post the complete command used?

**Comment by YehudaHalfon** [comment]
the command was
nvidia-smi -l 1

and the device mapping at the start (if understood you right) is this:
=== RELION MPI setup ===
 + Number of MPI processes             = 4
 + Number of threads per MPI process  = 2
 + Total number of threads therefore  = 8
 + Master  (0) runs on host            = ribos21l.weizmann.ac.il
 + Slave     1 runs on host            = ribos21l.weizmann.ac.il
 + Slave     2 runs on host            = ribos21l.weizmann.ac.il
 + Slave     3 runs on host            = ribos21l.weizmann.ac.il
 Running CPU instructions in double precision. 
 + On host ribos21l.weizmann.ac.il: free scratch space = 474 Gb.
 Copying particles to scratch directory: /raid0scratch/relion2/relion_volatile/
2.57/2.57 min ............................................................~~(,_,">
 Estimating initial noise spectra 
  40/  40 sec ............................................................~~(,_,">
 uniqueHost ribos21l.weizmann.ac.il has 3 ranks.
GPU-ids not specified for this rank, threads will automatically be mapped to available devices.
 Thread 0 on slave 1 mapped to device 0
 Thread 1 on slave 1 mapped to device 0
GPU-ids not specified for this rank, threads will automatically be mapped to available devices.
 Thread 0 on slave 2 mapped to device 1
 Thread 1 on slave 2 mapped to device 2
GPU-ids not specified for this rank, threads will automatically be mapped to available devices.
 Thread 0 on slave 3 mapped to device 2
 Thread 1 on slave 3 mapped to device 3

**Comment by bforsbe** [comment]
As explained in the tutorial, you need to add one rank which acts as a "master" rank and which distributes work to the other ranks. using 

`mpirun -n 4`

produces 3 slaves on 4 GPUs, which is difficult to set up automatically. In this case it is failing to do so in a good way, which we need to look into. But you can easily fix this and get much better performance by running

`mpirun -n 5 -j2`

Which is the recommended setting when using 4 GPUs. You can also try 

`mpirun -n 3 -j4`

But this is just a question of performance

**Comment by YehudaHalfon** [comment]
If I understand correctly I should run it as 
Number of MPI 5
Number of threads 2?

Will this help with my problem or is it just for future faster procedures?

**Comment by bforsbe** [comment]
That is correct. It will help with the memory-error you saw.

There is a line you did not show after the device mapping that warns you, were it will say
"device 2 is split between 2 slaves", meaning that two ranks are using the same GPU. This increases memory use and causes the "out-of-memory". Using 4 slaves (mpirun -n 5) will not result in the same "device 2 is split between 2 slaves"-warning.

**Comment by YehudaHalfon** [comment]
I'll try this now and will let you know.

**Comment by YehudaHalfon** [comment]
It works, 
Thanks a lot.

**Comment by GuShaocheng** [comment]
I have provided a directory that can be written, but the job would not create a sub-direcrory in here called relion_bolatile. Could you tell me why and how to set it ? Thanks !
