### ISSUE TITLE
Can't run relion_star_loopheader in 2.0.3

### ISSUE THREAD

**Issue by dtegunov** [3dem/relion#199]
Micrograph import won't work because of a problem with relion_star_loopheader. Manually running relion_star_loopheader without additional parameters produces:
```
: invalid option
Usage:  /bin/bash [GNU long option] [option] ...
        /bin/bash [GNU long option] [option] script-file ...
```

It works fine in an older beta version. Also, I had to chmod a+x relion_star_loopheader and a couple of other files in bin in order to run them, but this may be my mistake as I moved things around between different machines. It does resemble bug #31 though.

**Comment by catson4** [comment]
Did this problem get resolved? I'm having the same issue.
