### ISSUE TITLE
ibm Power PC

### ISSUE THREAD

**Issue by galmalca** [3dem/relion#200]
Is relion support ppc64le architecture?

**Comment by eriklindahl** [comment]
Power8 behaves just like x86, so the short answer is yes.

However, for now you'll get order(s)-of-magnitude  better performance with GPUs. You can get Power8 systems with GPUs, but you're not going to see any benefit compared to x86+GPU, and the latter solution is likely to be (much) cheaper.

Cheers,

Erik

Erik Lindahl <erik.lindahl@scilifelab.se>
Professor of Biophysics
Science for Life Laboratory
Stockholm University & KTH
Office (SciLifeLab): +46 8 524 81567
Cell (Sweden): +46 73 4618050
Cell (US): +1 267 3078746
