### ISSUE TITLE
MotionCor2 does not work with the latest version

### ISSUE THREAD

**Issue by barureddy** [3dem/relion#201]
When I run motioncorr2 with the openbeta, it works fine, but when I run it with the latest stable version (2.0.3), it fails and I get the following error:

`ERROR: movie Micrographs/FoilHole_9308474_Data_9272007_9272008_20161110_0812_frames.mrc does not have enough frames.
File: /programs/x86_64-linux/relion/2.0.3_icc/src/motioncorr_runner.cpp line: 474
ERROR: movie Micrographs/FoilHole_9300188_Data_9272007_9272008_20161109_2231_frames.mrc does not have enough frames.
File: /programs/x86_64-linux/relion/2.0.3_icc/src/motioncorr_runner.cpp line: 474
[nsit-dhcp-148-090.bsd.uchicago.edu:15397] 1 more process has sent help message help-mpi-api.txt / mpi-abort
[nsit-dhcp-148-090.bsd.uchicago.edu:15397] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages
ERROR: movie Micrographs/FoilHole_10330986_Data_9272007_9272008_20161110_1439_frames.mrc does not have enough frames.
File: /programs/x86_64-linux/relion/2.0.3_icc/src/motioncorr_runner.cpp line: 474
`
The command I use is 
``which relion_run_motioncorr_mpi` --i ./Import/job001/movies.star --o MotionCorr/job005/ --first_frame_sum 1 --last_frame_sum 40 --bin_factor 1 --motioncorr_exe /programs/x86_64-linux/motioncor2/20161019/MotionCor2 --bfactor 150 --use_motioncor2 --angpix 1.936 --patch_x 5 --patch_y 5 --other_motioncorr_args " -trunc 1 " --gpu 0:0:1:1 --dose_weighting --voltage 200 --dose_per_frame 1.68 --preexposure 0 --only_do_unfinished`

**Comment by bforsbe** [comment]
This is a new error, i.e. in v2.0.1 this error did not exist, so that explains why you did not see it before at least. The error itself indicates that the input .mrc does not have 40 frames. If it contains exactly 40 frames it might be that we need to adjust the internal numbering to 39, since the numbering starts at 0 in motionCor2. If you do have 40 frames, then you need not specify --last_frame_sum 40, since all frames are used by default.

**Comment by attamatti** [comment]
I don't think it's as simple as this...

We've encountered the same error, when attempting to align, for example, frames 3 - 47 of a 50 frame movie.  The error occurs even before Relion writes the motioncorr2 com file. The work around we use is to use first_frame_sum 1 and  last_frame_sum 0  then add --trunc and --throw commands in the additional motioncor parameters.

**Comment by barureddy** [comment]
I've tried the same at attamatti and it seems to work. The built in sliders do not work.

**Comment by barureddy** [comment]
I think my problem is related to bug 132.
