### ISSUE TITLE
Display from the console doesn't work for project directories with spaces in their names

### ISSUE THREAD

**Issue by jamesmkrieger** [3dem/relion#203]
I appreciate that spaces in directory names and filenames is something that should be avoided anyway but we have some anyway. When we call Display from the drop down menu in the top left of the relion v2.0.3 GUI and ask for a class2d model.star an error comes up in stdout/stderr saying the following.

lg-krieger_bsingh> +++ RELION: command line arguments (with defaults for optional ones between parantheses) +++
====== General options =====
                             --i () : Input STAR file, image or stack
                      --gui (false) : Use this to provide all other parameters through a GUI
           --display (rlnImageName) : Metadata label to display
                         --table () : Name of the table to read from in the input STAR file
                        --scale (1) : Relative scale
                        --black (0) : Pixel value for black (default is auto-contrast)
                        --white (0) : Pixel value for white (default is auto-contrast)
               --sigma_contrast (0) : Set white and black pixel values this many times the image stddev from the mean
         --read_whole_stack (false) : Read entire stacks at once (to speed up when many images of each stack are displayed)
  --show_fourier_amplitudes (false) : Show amplitudes of 2D Fourier transform?
  --show_fourier_phase_angles (false) : Show phase angles of 2D Fourier transforms?
====== Multiviewer options =====
                          --col (5) : Number of columns
             --apply_orient (false) : Apply the orientation as stored in the input STAR file angles and offsets
                    --ori_scale (1) : Relative scale for viewing individual images in multiviewer
            --sort (EMDL_UNDEFINED) : Metadata label to sort images on
                  --reverse (false) : Use reverse order (from high to low) in the sorting
                    --class (false) : Use this to analyse classes in input model.star file
                     --regroup (-1) : Number of groups to regroup saved particles from selected classes in (default is no regrouping)
               --allow_save (false) : Allow saving of selected particles or class averages
                       --fn_imgs () : Name of the STAR file in which to save selected images.
                      --fn_parts () : Name of the STAR file in which to save particles from selected classes.
                 --recenter (false) : Recenter the selected images to the center-of-mass of all positive pixel values.
               --max_nr_images (-1) : Only show this many images (default is show all)
====== Picking options =====
                     --pick (false) : Pick coordinates in input image
                        --coords () : STAR file with picked particle coordinates
            --particle_radius (100) : Particle radius in pixels
                      --lowpass (0) : Lowpass filter (in A) to filter micrograph before displaying
                     --highpass (0) : Highpass filter (in A) to filter micrograph before displaying
                      --angpix (-1) : Pixel size (in A) to calculate lowpass filter
                    --color_star () : STAR file with a column for red-blue coloring (a subset of) the particles
                   --color_label () : MetaDataLabel to color particles on (e.g. rlnParticleSelectZScore)
                        --blue (1.) : Value of the blue color
                         --red (0.) : Value of the red color
                         --verb (1) : Verbosity
MetaDataTable::read: File /data/em/GluA3/2017-02-08_data.star does not exists
File: /net/nfs1/public/EM/RELION/relion-2.0/src/metadata_table.cpp line: 752

The full path name would be /data/em/GluA3/2017-02-08 GluA3 nano collected/Class2D/job014/run_it025_model.star so it looks like the space handling is wrong.

**Comment by WilliamNicolas** [comment]
Hey,

I will not be able to help you but I get a similar error that prevents me for previewing the results of my autopicking results. Indeed I see in my sampled micrographs list the number of particles automatically detected but when I try to open one of them I get this error:

ERROR: 
MetaDataTable::read: File rlnAutopickFigureofMerit does not exists
File: /programs/x86_64-linux/relion/2.1_cu9.0/src/metadata_table.cpp line: 752

I noticed that when I go cd and ls in the job directory I see no micrographs folder. However in the parent directory (Autopick one) there is a micrographs folder that appeared.

I am wondering if for some reason RELION is not looking in the right folder....
