### ISSUE TITLE
Issues during installation 

### ISSUE THREAD

**Issue by Rafael-Ayala** [3dem/relion#205]
Hi,

I have recently tried to compile and install RELION 2 with GPU and MPI support, but got the following when running make:

[  1%] Building NVCC (Device) object src/apps/CMakeFiles/relion_gpu_util.dir/__/gpu_utils/relion_gpu_util_generated_cuda_autopicker.cu.o
[  2%] Building NVCC (Device) object src/apps/CMakeFiles/relion_gpu_util.dir/__/gpu_utils/cuda_kernels/relion_gpu_util_generated_helper.cu.o
Scanning dependencies of target copy_scripts
[  3%] Building NVCC (Device) object src/apps/CMakeFiles/relion_gpu_util.dir/__/gpu_utils/relion_gpu_util_generated_cuda_backprojector.cu.o
[  3%] Built target copy_scripts
[  4%] Building NVCC (Device) object src/apps/CMakeFiles/relion_gpu_util.dir/__/gpu_utils/relion_gpu_util_generated_cuda_benchmark_utils.cu.o
[  5%] Building NVCC (Device) object src/apps/CMakeFiles/relion_gpu_util.dir/__/gpu_utils/relion_gpu_util_generated_cuda_helper_functions.cu.o
[  5%] Building NVCC (Device) object src/apps/CMakeFiles/relion_gpu_util.dir/__/gpu_utils/relion_gpu_util_generated_cuda_ml_optimiser.cu.o
[  6%] Building NVCC (Device) object src/apps/CMakeFiles/relion_gpu_util.dir/__/gpu_utils/relion_gpu_util_generated_cuda_projector.cu.o
[  7%] Building NVCC (Device) object src/apps/CMakeFiles/relion_gpu_util.dir/__/gpu_utils/relion_gpu_util_generated_cuda_projector_plan.cu.o
Scanning dependencies of target relion_gpu_util
[  7%] Linking CXX shared library ../../lib/librelion_gpu_util.so
Error running link command: No such file or directory
make[2]: *** [lib/librelion_gpu_util.so] Error 2
make[1]: *** [src/apps/CMakeFiles/relion_gpu_util.dir/all] Error 2
make: *** [all] Error 2

I have seen simmilar errors reported in issues 4 and 187, but could not find any clear solution in those. Any help to solve this would be greatly appreciated

cmake completes without any apparent error, but here is the terminal output in case it is useful:

-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- Check for working C compiler: /bin/cc
-- Check for working C compiler: /bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /bin/c++
-- Check for working CXX compiler: /bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- BUILD TYPE set to the default type:  'Release'
-- Using provided CUDA_ARCH=52
-- Setting cpu precision to double
-- Setting gpu precision to single
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found CUDA: /usr/local/cuda (found version "7.5") 
-- Using cuda wrapper to compile....
-- Cuda version is >= 7.5 and single-precision build, enable double usage warning.
-- Found MPI_C: /usr/local/lib64/mpi/lib/libmpi.so  
-- Found MPI_CXX: /usr/local/lib64/mpi/lib/libmpi.so;/usr/local/lib64/mpi/lib/libmpi_cxx.so  
-- MPI_INCLUDE_PATH : /usr/local/lib64/mpi/include
-- MPI_LIBRARIES : /usr/local/lib64/mpi/lib/libmpi.so;/usr/local/lib64/mpi/lib/libmpi_cxx.so
-- MPI_CXX_INCLUDE_PATH : /usr/local/lib64/mpi/include
-- MPI_CXX_LIBRARIES : /usr/local/lib64/mpi/lib/libmpi.so;/usr/local/lib64/mpi/lib/libmpi_cxx.so
-- Looking for XOpenDisplay in /usr/lib64/libX11.so;/usr/lib64/libXext.so
-- Looking for XOpenDisplay in /usr/lib64/libX11.so;/usr/lib64/libXext.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Looking for IceConnectionNumber in ICE
-- Looking for IceConnectionNumber in ICE - found
-- Found X11: /usr/lib64/libX11.so
-- Found FLTK: /usr/local/lib/libfltk_images.a;/usr/local/lib/libfltk_forms.a;/usr/local/lib/libfltk.a  
-- X11 and FLTK were found
-- FLTK_LIBRARIES: /usr/local/lib/libfltk_images.a;/usr/local/lib/libfltk_forms.a;/usr/local/lib/libfltk.a;/usr/lib64/libSM.so;/usr/lib64/libICE.so;/usr/lib64/libX11.so;/usr/lib64/libXext.so;/usr/lib64/libm.so
-- Found FFTW: fftw3
-- FFTW_LIBRARIES: /usr/local/lib/libfftw3.a
-- Looking for sincos
-- Looking for sincos - found
-- Looking for __sincos
-- Looking for __sincos - not found
-- Building shared libs (smaller build size and binaries)
-- CMAKE_BINARY_DIR:/usr/local/src/relion/build
-- added autopick...
-- added autopick_mpi...
-- added display...
-- added find_tiltpairs...
-- added helix_toolbox...
-- added image_handler...
-- added maingui...
-- added manualpick...
-- added mask_create...
-- added particle_polish...
-- added particle_polish_mpi...
-- added particle_reposition...
-- added particle_sort...
-- added particle_sort_mpi...
-- added particle_symmetry_expand...
-- added pipeliner...
-- added postprocess...
-- added postprocess_mpi...
-- added preprocess...
-- added preprocess_mpi...
-- added project...
-- added reconstruct...
-- added refine...
-- added refine_mpi...
-- added run_ctffind...
-- added run_ctffind_mpi...
-- added run_motioncorr...
-- added run_motioncorr_mpi...
-- added stack_create...
-- added star_combine...
-- added star_compare...
-- added tiltpair_plot...
-- Configuring done
-- Generating done
-- Build files have been written to: /usr/local/src/relion/build

Thanks a lot in advance!

**Comment by bforsbe** [comment]
This; 

```
-- CMAKE_BINARY_DIR:/usr/local/src/relion/build
```

Indicates to me that you are building **within** /usr/local. As noted in[ issue 202](https://github.com/3dem/relion/issues/202), this is not recommended when using cmake & make. That issue was fixed by building into e.g. ~/Downloads and then **installing to** /usr/local;

```
cd relion ~/Downloads/relion
mkdir build
cd build
cmake -DCMAKE_INSTALL_PREFIX=/usr/local/relion -DCUDA_ARCH=52 ..
make -j 8 
sudo make install
```

**Comment by Rafael-Ayala** [comment]
Thanks a lot for the quick reply!

I did as you suggested and started installation again from scratch, this time downloading the source to ~/Downloads/relion and building there. However, I still got the same issue.

This is the output from cmake:

-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- BUILD TYPE set to the default type:  'Release'
-- Using provided CUDA_ARCH=52
-- Setting cpu precision to double
-- Setting gpu precision to single
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found CUDA: /usr/local/cuda (found version "7.5") 
-- Using cuda wrapper to compile....
-- Cuda version is >= 7.5 and single-precision build, enable double usage warning.
-- Found MPI_C: /usr/local/lib64/mpi/lib/libmpi.so  
-- Found MPI_CXX: /usr/local/lib64/mpi/lib/libmpi.so;/usr/local/lib64/mpi/lib/libmpi_cxx.so  
-- MPI_INCLUDE_PATH : /usr/local/lib64/mpi/include
-- MPI_LIBRARIES : /usr/local/lib64/mpi/lib/libmpi.so;/usr/local/lib64/mpi/lib/libmpi_cxx.so
-- MPI_CXX_INCLUDE_PATH : /usr/local/lib64/mpi/include
-- MPI_CXX_LIBRARIES : /usr/local/lib64/mpi/lib/libmpi.so;/usr/local/lib64/mpi/lib/libmpi_cxx.so
-- Looking for XOpenDisplay in /usr/lib64/libX11.so;/usr/lib64/libXext.so
-- Looking for XOpenDisplay in /usr/lib64/libX11.so;/usr/lib64/libXext.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Looking for IceConnectionNumber in ICE
-- Looking for IceConnectionNumber in ICE - found
-- Found X11: /usr/lib64/libX11.so
-- Found FLTK: /usr/local/lib/libfltk_images.a;/usr/local/lib/libfltk_forms.a;/usr/local/lib/libfltk.a  
-- X11 and FLTK were found
-- FLTK_LIBRARIES: /usr/local/lib/libfltk_images.a;/usr/local/lib/libfltk_forms.a;/usr/local/lib/libfltk.a;/usr/lib64/libSM.so;/usr/lib64/libICE.so;/usr/lib64/libX11.so;/usr/lib64/libXext.so;/usr/lib64/libm.so
-- Found FFTW: fftw3
-- FFTW_LIBRARIES: /usr/local/lib/libfftw3.a
-- Looking for sincos
-- Looking for sincos - found
-- Looking for __sincos
-- Looking for __sincos - not found
-- Building shared libs (smaller build size and binaries)
-- CMAKE_BINARY_DIR:/home/localadmin/Downloads/relion/build
-- added autopick...
-- added autopick_mpi...
-- added display...
-- added find_tiltpairs...
-- added helix_toolbox...
-- added image_handler...
-- added maingui...
-- added manualpick...
-- added mask_create...
-- added particle_polish...
-- added particle_polish_mpi...
-- added particle_reposition...
-- added particle_sort...
-- added particle_sort_mpi...
-- added particle_symmetry_expand...
-- added pipeliner...
-- added postprocess...
-- added postprocess_mpi...
-- added preprocess...
-- added preprocess_mpi...
-- added project...
-- added reconstruct...
-- added refine...
-- added refine_mpi...
-- added run_ctffind...
-- added run_ctffind_mpi...
-- added run_motioncorr...
-- added run_motioncorr_mpi...
-- added stack_create...
-- added star_combine...
-- added star_compare...
-- added tiltpair_plot...
-- Configuring done
-- Generating done
-- Build files have been written to: /home/localadmin/Downloads/relion/build

And this is the output from make:

[  1%] Building NVCC (Device) object src/apps/CMakeFiles/relion_gpu_util.dir/__/gpu_utils/cuda_kernels/relion_gpu_util_generated_helper.cu.o
[  2%] Building NVCC (Device) object src/apps/CMakeFiles/relion_gpu_util.dir/__/gpu_utils/relion_gpu_util_generated_cuda_autopicker.cu.o
[  3%] Building NVCC (Device) object src/apps/CMakeFiles/relion_gpu_util.dir/__/gpu_utils/relion_gpu_util_generated_cuda_backprojector.cu.o
Scanning dependencies of target copy_scripts
[  4%] Building NVCC (Device) object src/apps/CMakeFiles/relion_gpu_util.dir/__/gpu_utils/relion_gpu_util_generated_cuda_benchmark_utils.cu.o
[  5%] Building NVCC (Device) object src/apps/CMakeFiles/relion_gpu_util.dir/__/gpu_utils/relion_gpu_util_generated_cuda_helper_functions.cu.o
[  5%] Building NVCC (Device) object src/apps/CMakeFiles/relion_gpu_util.dir/__/gpu_utils/relion_gpu_util_generated_cuda_ml_optimiser.cu.o
[  6%] Building NVCC (Device) object src/apps/CMakeFiles/relion_gpu_util.dir/__/gpu_utils/relion_gpu_util_generated_cuda_projector.cu.o
[  6%] Built target copy_scripts
[  7%] Building NVCC (Device) object src/apps/CMakeFiles/relion_gpu_util.dir/__/gpu_utils/relion_gpu_util_generated_cuda_projector_plan.cu.o
Scanning dependencies of target relion_gpu_util
[  7%] Linking CXX shared library ../../lib/librelion_gpu_util.so
Error running link command: No such file or directory
make[2]: *** [lib/librelion_gpu_util.so] Error 2
make[1]: *** [src/apps/CMakeFiles/relion_gpu_util.dir/all] Error 2
make: *** [all] Error 2

Any help would be appreciated. Please let me know if you would like any other output. Thanks a lot again!

**Comment by Rafael-Ayala** [comment]
Update:

I managed to get further by running cmake and make as root, from /home/localadmin/Downloads/relion/build , but still got an error. This is the output of make:

Scanning dependencies of target copy_scripts
[  1%] Building NVCC (Device) object src/apps/CMakeFiles/relion_gpu_util.dir/__/gpu_utils/relion_gpu_util_generated_cuda_autopicker.cu.o
[  2%] Building NVCC (Device) object src/apps/CMakeFiles/relion_gpu_util.dir/__/gpu_utils/cuda_kernels/relion_gpu_util_generated_helper.cu.o
[  3%] Building NVCC (Device) object src/apps/CMakeFiles/relion_gpu_util.dir/__/gpu_utils/relion_gpu_util_generated_cuda_backprojector.cu.o
[  4%] Building NVCC (Device) object src/apps/CMakeFiles/relion_gpu_util.dir/__/gpu_utils/relion_gpu_util_generated_cuda_benchmark_utils.cu.o
[  5%] Building NVCC (Device) object src/apps/CMakeFiles/relion_gpu_util.dir/__/gpu_utils/relion_gpu_util_generated_cuda_helper_functions.cu.o
[  5%] Building NVCC (Device) object src/apps/CMakeFiles/relion_gpu_util.dir/__/gpu_utils/relion_gpu_util_generated_cuda_ml_optimiser.cu.o
[  6%] Building NVCC (Device) object src/apps/CMakeFiles/relion_gpu_util.dir/__/gpu_utils/relion_gpu_util_generated_cuda_projector.cu.o
[  6%] Built target copy_scripts
[  7%] Building NVCC (Device) object src/apps/CMakeFiles/relion_gpu_util.dir/__/gpu_utils/relion_gpu_util_generated_cuda_projector_plan.cu.o
Scanning dependencies of target relion_gpu_util
[  7%] Linking CXX shared library ../../lib/librelion_gpu_util.so
[  7%] Built target relion_gpu_util
Scanning dependencies of target relion_lib
[ 10%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/assembly.cpp.o
[ 10%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/CPlot2D.cpp.o
[ 10%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/args.cpp.o
[ 10%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/autopicker.cpp.o
[ 11%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/autopicker_mpi.cpp.o
[ 12%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/backprojector.cpp.o
[ 13%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/complex.cpp.o
[ 14%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/ctf.cpp.o
[ 14%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/ctffind_runner.cpp.o
[ 15%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/ctffind_runner_mpi.cpp.o
[ 16%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/displayer.cpp.o
[ 17%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/error.cpp.o
[ 17%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/euler.cpp.o
[ 18%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/exp_model.cpp.o
[ 19%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/fftw.cpp.o
[ 20%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/filename.cpp.o
[ 20%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/funcs.cpp.o
[ 21%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/gui_entries.cpp.o
[ 22%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/gui_jobwindow.cpp.o
[ 23%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/gui_mainwindow.cpp.o
[ 24%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/healpix_sampling.cpp.o
[ 24%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/helix.cpp.o
[ 25%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/image.cpp.o
[ 26%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/manualpicker.cpp.o
[ 27%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/mask.cpp.o
[ 27%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/matrix1d.cpp.o
[ 28%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/matrix2d.cpp.o
[ 29%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/memory.cpp.o
[ 30%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/metadata_container.cpp.o
[ 30%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/metadata_label.cpp.o
[ 31%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/metadata_table.cpp.o
[ 32%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/ml_model.cpp.o
[ 33%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/ml_optimiser.cpp.o
[ 34%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/ml_optimiser_mpi.cpp.o
[ 34%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/motioncorr_runner.cpp.o
[ 35%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/motioncorr_runner_mpi.cpp.o
[ 36%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/mpi.cpp.o
[ 37%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/multidim_array.cpp.o
[ 37%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/numerical_recipes.cpp.o
[ 38%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/parallel.cpp.o
[ 39%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/particle_polisher.cpp.o
[ 40%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/particle_polisher_mpi.cpp.o
[ 40%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/particle_sorter.cpp.o
[ 41%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/particle_sorter_mpi.cpp.o
[ 42%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/pipeliner.cpp.o
[ 43%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/postprocessing.cpp.o
[ 44%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/preprocessing.cpp.o
[ 44%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/preprocessing_mpi.cpp.o
[ 45%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/projector.cpp.o
[ 46%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/strings.cpp.o
[ 47%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/symmetries.cpp.o
[ 47%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/tabfuncs.cpp.o
[ 48%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/time.cpp.o
[ 49%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/transformations.cpp.o
[ 50%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/Healpix_2.15a/cxxutils.cc.o
[ 50%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/Healpix_2.15a/healpix_base.cc.o
[ 51%] Linking CXX shared library ../../lib/librelion_lib.so
/bin/ld: /usr/local/lib/libfftw3.a(mapflags.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/local/lib/libfftw3.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
make[2]: *** [lib/librelion_lib.so] Error 1
make[1]: *** [src/apps/CMakeFiles/relion_lib.dir/all] Error 2
make: *** [all] Error 2

**Comment by Rafael-Ayala** [comment]
Update 2:

Finally managed to compile without errors after recompiling both fftw and fltk with --enable-shared for ./configure

Thanks!

**Comment by bforsbe** [comment]
Glad to hear it!
