### ISSUE TITLE
Motioncorr and Unblur Error in 2.0.3

### ISSUE THREAD

**Issue by ninthpower** [3dem/relion#208]
We cannot seem to get Motioncorr (we're using motioncorr/2.1/bin/dosefgpu) or unblur to work and keep getting errors. We can run both of these packages on their own through the command line, but trying them through Relion 2.0.3 causes errors:

run.out:
 === RELION MPI setup ===
 + Number of MPI processes             = 10
 + Master  (0) runs on host            = mod-em2.rockefeller.edu
 =================
 + Slave     1 runs on host            = mod-em2.rockefeller.edu
 + Slave     2 runs on host            = mod-em2.rockefeller.edu
 + Slave     3 runs on host            = mod-em2.rockefeller.edu
 + Slave     4 runs on host            = mod-em2.rockefeller.edu
 + Slave     5 runs on host            = mod-em2.rockefeller.edu
 + Slave     6 runs on host            = mod-em2.rockefeller.edu
 + Slave     7 runs on host            = mod-em2.rockefeller.edu
 + Slave     8 runs on host            = mod-em2.rockefeller.edu
 + Slave     9 runs on host            = mod-em2.rockefeller.edu
gpu-ids not specified, threads will automatically be mapped to devices (incrementally).
 Using MOTIONCORR executable in: ../../../programs/x86_64-linux/motioncorr/2.1/bin/dosefgpu_driftcorr
 to correct beam-induced motion for the following micrographs: 
  * raw_data/cmgM10_T3_0001.tif
  * raw_data/cmgM10_T3_0002.tif
  * raw_data/cmgM10_T3_0003.tif
  * raw_data/cmgM10_T3_0004.tif
  * raw_data/cmgM10_T3_0005.tif
  * raw_data/cmgM10_T3_0006.tif
  * raw_data/cmgM10_T3_0007.tif
  * raw_data/cmgM10_T3_0008.tif
  * raw_data/cmgM10_T3_0009.tif
  * raw_data/cmgM10_T3_0010.tif
  * raw_data/cmgM10_T3_0011.tif
  * raw_data/cmgM10_T3_0012.tif
  * raw_data/cmgM10_T3_0013.tif
  * raw_data/cmgM10_T3_0014.tif
  * raw_data/cmgM10_T3_0015.tif
  * raw_data/cmgM10_T3_0016.tif
  * raw_data/cmgM10_T3_0018.tif
  * raw_data/cmgM10_T3_0019.tif
  * raw_data/cmgM10_T3_0020.tif
  * raw_data/cmgM10_T3_0021.tif
 Correcting beam-induced motions using Shawn Zheng's MOTIONCOR2 ...
   2/   2 sec ............................................................~~(,_,">

run.err:
 WARNING: there was an error executing: ../../../programs/x86_64-linux/motioncorr/2.1/bin/dosefgpu_driftcorr  -InTiff raw_data/cmgM10_T3_0005.tif -OutMrc MotionCorr/job007/raw_data/cmgM10_T3_0005.mrc -Bft 150 -OutStack 1 -Patch 1 1 -Gain GR130_vf_cw90.mrc -Kv 200 -FmDose 1.11 -PixSize 1.2 -InitDose 0  -trunc 1  -Gpu 0 >> MotionCorr/job007/raw_data/cmgM10_T3_0005.out 2>> MotionCorr/job007/raw_data/cmgM10_T3_0005.err
 WARNING: there was an error executing: ../../../programs/x86_64-linux/motioncorr/2.1/bin/dosefgpu_driftcorr  -InTiff raw_data/cmgM10_T3_0013.tif -OutMrc MotionCorr/job007/raw_data/cmgM10_T3_0013.mrc -Bft 150 -OutStack 1 -Patch 1 1 -Gain GR130_vf_cw90.mrc -Kv 200 -FmDose 1.11 -PixSize 1.2 -InitDose 0  -trunc 1  -Gpu 0 >> MotionCorr/job007/raw_data/cmgM10_T3_0013.out 2>> MotionCorr/job007/raw_data/cmgM10_T3_0013.err
 WARNING: there was an error executing: ../../../programs/x86_64-linux/motioncorr/2.1/bin/dosefgpu_driftcorr  -InTiff raw_data/cmgM10_T3_0009.tif -OutMrc MotionCorr/job007/raw_data/cmgM10_T3_0009.mrc -Bft 150 -OutStack 1 -Patch 1 1 -Gain GR130_vf_cw90.mrc -Kv 200 -FmDose 1.11 -PixSize 1.2 -InitDose 0  -trunc 1  -Gpu 0 >> MotionCorr/job007/raw_data/cmgM10_T3_0009.out 2>> MotionCorr/job007/raw_data/cmgM10_T3_0009.err
 WARNING: there was an error executing: ../../../programs/x86_64-linux/motioncorr/2.1/bin/dosefgpu_driftcorr  -InTiff raw_data/cmgM10_T3_0020.tif -OutMrc MotionCorr/job007/raw_data/cmgM10_T3_0020.mrc -Bft 150 -OutStack 1 -Patch 1 1 -Gain GR130_vf_cw90.mrc -Kv 200 -FmDose 1.11 -PixSize 1.2 -InitDose 0  -trunc 1  -Gpu 1 >> MotionCorr/job007/raw_data/cmgM10_T3_0020.out 2>> MotionCorr/job007/raw_data/cmgM10_T3_0020.err
 WARNING: there was an error executing: ../../../programs/x86_64-linux/motioncorr/2.1/bin/dosefgpu_driftcorr  -InTiff raw_data/cmgM10_T3_0011.tif -OutMrc MotionCorr/job007/raw_data/cmgM10_T3_0011.mrc -Bft 150 -OutStack 1 -Patch 1 1 -Gain GR130_vf_cw90.mrc -Kv 200 -FmDose 1.11 -PixSize 1.2 -InitDose 0  -trunc 1  -Gpu 1 >> MotionCorr/job007/raw_data/cmgM10_T3_0011.out 2>> MotionCorr/job007/raw_data/cmgM10_T3_0011.err
 WARNING: there was an error executing: ../../../programs/x86_64-linux/motioncorr/2.1/bin/dosefgpu_driftcorr  -InTiff raw_data/cmgM10_T3_0015.tif -OutMrc MotionCorr/job007/raw_data/cmgM10_T3_0015.mrc -Bft 150 -OutStack 1 -Patch 1 1 -Gain GR130_vf_cw90.mrc -Kv 200 -FmDose 1.11 -PixSize 1.2 -InitDose 0  -trunc 1  -Gpu 1 >> MotionCorr/job007/raw_data/cmgM10_T3_0015.out 2>> MotionCorr/job007/raw_data/cmgM10_T3_0015.err
 WARNING: there was an error executing: ../../../programs/x86_64-linux/motioncorr/2.1/bin/dosefgpu_driftcorr  -InTiff raw_data/cmgM10_T3_0003.tif -OutMrc MotionCorr/job007/raw_data/cmgM10_T3_0003.mrc -Bft 150 -OutStack 1 -Patch 1 1 -Gain GR130_vf_cw90.mrc -Kv 200 -FmDose 1.11 -PixSize 1.2 -InitDose 0  -trunc 1  -Gpu 1 >> MotionCorr/job007/raw_data/cmgM10_T3_0003.out 2>> MotionCorr/job007/raw_data/cmgM10_T3_0003.err
 WARNING: there was an error executing: ../../../programs/x86_64-linux/motioncorr/2.1/bin/dosefgpu_driftcorr  -InTiff raw_data/cmgM10_T3_0007.tif -OutMrc MotionCorr/job007/raw_data/cmgM10_T3_0007.mrc -Bft 150 -OutStack 1 -Patch 1 1 -Gain GR130_vf_cw90.mrc -Kv 200 -FmDose 1.11 -PixSize 1.2 -InitDose 0  -trunc 1  -Gpu 1 >> MotionCorr/job007/raw_data/cmgM10_T3_0007.out 2>> MotionCorr/job007/raw_data/cmgM10_T3_0007.err
 WARNING: there was an error executing: ../../../programs/x86_64-linux/motioncorr/2.1/bin/dosefgpu_driftcorr  -InTiff raw_data/cmgM10_T3_0001.tif -OutMrc MotionCorr/job007/raw_data/cmgM10_T3_0001.mrc -Bft 150 -OutStack 1 -Patch 1 1 -Gain GR130_vf_cw90.mrc -Kv 200 -FmDose 1.11 -PixSize 1.2 -InitDose 0  -trunc 1  -Gpu 0 >> MotionCorr/job007/raw_data/cmgM10_T3_0001.out 2>> MotionCorr/job007/raw_data/cmgM10_T3_0001.err
 WARNING: there was an error executing: ../../../programs/x86_64-linux/motioncorr/2.1/bin/dosefgpu_driftcorr  -InTiff raw_data/cmgM10_T3_0018.tif -OutMrc MotionCorr/job007/raw_data/cmgM10_T3_0018.mrc -Bft 150 -OutStack 1 -Patch 1 1 -Gain GR130_vf_cw90.mrc -Kv 200 -FmDose 1.11 -PixSize 1.2 -InitDose 0  -trunc 1  -Gpu 0 >> MotionCorr/job007/raw_data/cmgM10_T3_0018.out 2>> MotionCorr/job007/raw_data/cmgM10_T3_0018.err
 WARNING: there was an error executing: ../../../programs/x86_64-linux/motioncorr/2.1/bin/dosefgpu_driftcorr  -InTiff raw_data/cmgM10_T3_0002.tif -OutMrc MotionCorr/job007/raw_data/cmgM10_T3_0002.mrc -Bft 150 -OutStack 1 -Patch 1 1 -Gain GR130_vf_cw90.mrc -Kv 200 -FmDose 1.11 -PixSize 1.2 -InitDose 0  -trunc 1  -Gpu 0 >> MotionCorr/job007/raw_data/cmgM10_T3_0002.out 2>> MotionCorr/job007/raw_data/cmgM10_T3_0002.err
 WARNING: there was an error executing: ../../../programs/x86_64-linux/motioncorr/2.1/bin/dosefgpu_driftcorr  -InTiff raw_data/cmgM10_T3_0010.tif -OutMrc MotionCorr/job007/raw_data/cmgM10_T3_0010.mrc -Bft 150 -OutStack 1 -Patch 1 1 -Gain GR130_vf_cw90.mrc -Kv 200 -FmDose 1.11 -PixSize 1.2 -InitDose 0  -trunc 1  -Gpu 0 >> MotionCorr/job007/raw_data/cmgM10_T3_0010.out 2>> MotionCorr/job007/raw_data/cmgM10_T3_0010.err
 WARNING: there was an error executing: ../../../programs/x86_64-linux/motioncorr/2.1/bin/dosefgpu_driftcorr  -InTiff raw_data/cmgM10_T3_0014.tif -OutMrc MotionCorr/job007/raw_data/cmgM10_T3_0014.mrc -Bft 150 -OutStack 1 -Patch 1 1 -Gain GR130_vf_cw90.mrc -Kv 200 -FmDose 1.11 -PixSize 1.2 -InitDose 0  -trunc 1  -Gpu 0 >> MotionCorr/job007/raw_data/cmgM10_T3_0014.out 2>> MotionCorr/job007/raw_data/cmgM10_T3_0014.err
 WARNING: there was an error executing: ../../../programs/x86_64-linux/motioncorr/2.1/bin/dosefgpu_driftcorr  -InTiff raw_data/cmgM10_T3_0006.tif -OutMrc MotionCorr/job007/raw_data/cmgM10_T3_0006.mrc -Bft 150 -OutStack 1 -Patch 1 1 -Gain GR130_vf_cw90.mrc -Kv 200 -FmDose 1.11 -PixSize 1.2 -InitDose 0  -trunc 1  -Gpu 0 >> MotionCorr/job007/raw_data/cmgM10_T3_0006.out 2>> MotionCorr/job007/raw_data/cmgM10_T3_0006.err
 WARNING: there was an error executing: ../../../programs/x86_64-linux/motioncorr/2.1/bin/dosefgpu_driftcorr  -InTiff raw_data/cmgM10_T3_0004.tif -OutMrc MotionCorr/job007/raw_data/cmgM10_T3_0004.mrc -Bft 150 -OutStack 1 -Patch 1 1 -Gain GR130_vf_cw90.mrc -Kv 200 -FmDose 1.11 -PixSize 1.2 -InitDose 0  -trunc 1  -Gpu 1 >> MotionCorr/job007/raw_data/cmgM10_T3_0004.out 2>> MotionCorr/job007/raw_data/cmgM10_T3_0004.err
 WARNING: there was an error executing: ../../../programs/x86_64-linux/motioncorr/2.1/bin/dosefgpu_driftcorr  -InTiff raw_data/cmgM10_T3_0021.tif -OutMrc MotionCorr/job007/raw_data/cmgM10_T3_0021.mrc -Bft 150 -OutStack 1 -Patch 1 1 -Gain GR130_vf_cw90.mrc -Kv 200 -FmDose 1.11 -PixSize 1.2 -InitDose 0  -trunc 1  -Gpu 1 >> MotionCorr/job007/raw_data/cmgM10_T3_0021.out 2>> MotionCorr/job007/raw_data/cmgM10_T3_0021.err
 WARNING: there was an error executing: ../../../programs/x86_64-linux/motioncorr/2.1/bin/dosefgpu_driftcorr  -InTiff raw_data/cmgM10_T3_0012.tif -OutMrc MotionCorr/job007/raw_data/cmgM10_T3_0012.mrc -Bft 150 -OutStack 1 -Patch 1 1 -Gain GR130_vf_cw90.mrc -Kv 200 -FmDose 1.11 -PixSize 1.2 -InitDose 0  -trunc 1  -Gpu 1 >> MotionCorr/job007/raw_data/cmgM10_T3_0012.out 2>> MotionCorr/job007/raw_data/cmgM10_T3_0012.err
 WARNING: there was an error executing: ../../../programs/x86_64-linux/motioncorr/2.1/bin/dosefgpu_driftcorr  -InTiff raw_data/cmgM10_T3_0008.tif -OutMrc MotionCorr/job007/raw_data/cmgM10_T3_0008.mrc -Bft 150 -OutStack 1 -Patch 1 1 -Gain GR130_vf_cw90.mrc -Kv 200 -FmDose 1.11 -PixSize 1.2 -InitDose 0  -trunc 1  -Gpu 1 >> MotionCorr/job007/raw_data/cmgM10_T3_0008.out 2>> MotionCorr/job007/raw_data/cmgM10_T3_0008.err
 WARNING: there was an error executing: ../../../programs/x86_64-linux/motioncorr/2.1/bin/dosefgpu_driftcorr  -InTiff raw_data/cmgM10_T3_0016.tif -OutMrc MotionCorr/job007/raw_data/cmgM10_T3_0016.mrc -Bft 150 -OutStack 1 -Patch 1 1 -Gain GR130_vf_cw90.mrc -Kv 200 -FmDose 1.11 -PixSize 1.2 -InitDose 0  -trunc 1  -Gpu 1 >> MotionCorr/job007/raw_data/cmgM10_T3_0016.out 2>> MotionCorr/job007/raw_data/cmgM10_T3_0016.err
 WARNING: there was an error executing: ../../../programs/x86_64-linux/motioncorr/2.1/bin/dosefgpu_driftcorr  -InTiff raw_data/cmgM10_T3_0019.tif -OutMrc MotionCorr/job007/raw_data/cmgM10_T3_0019.mrc -Bft 150 -OutStack 1 -Patch 1 1 -Gain GR130_vf_cw90.mrc -Kv 200 -FmDose 1.11 -PixSize 1.2 -InitDose 0  -trunc 1  -Gpu 0 >> MotionCorr/job007/raw_data/cmgM10_T3_0019.out 2>> MotionCorr/job007/raw_data/cmgM10_T3_0019.err
GPL Ghostscript 9.19: Unrecoverable error, exit code 1

The error message sent to MotionCorr/job007/raw_data/cmgM10_T3_00XX.out shows an error from Motioncorr and the .err file from Motioncorr has nothing in it (<our tiff image>.out):
[user raw_data]$ more cmgM10_T3_0001.err
[user raw_data]$ more cmgM10_T3_0001.out
Undefined option: raw_data/cmgM10_T3_0001.tif .Abort.
Error: Failed to read parameters. Abort!

Looks like something is not being passed along to Motioncorr or Relion is pointing to the wrong place?

Thanks

**Comment by barureddy** [comment]
You need to convert your tif files to mrc. Motioncor v2.1, unblur, and Relion doesn't deal with tif files. Motioncor2 does deal with tif files but not within Relion.

**Comment by biochem-fan** [comment]
Not relevant for 3.0. Closing.
