### ISSUE TITLE
Class2D very slow on real data with 1M particles

### ISSUE THREAD

**Issue by jianSG** [3dem/relion#209]
I have tested benchmark data on a new GPU unit, with 4 * GTX1080 card. The GPUs are fully occupied and results meet the expectation well. 
But when I started on a real dataset with ~1M particles, it gets non-proportionally slow. No errors but very slow, take quite a few hours just to start first iteration and takes ~30-40 hours per round for 2D classification. The GPUs are only sporadically partially occupied. No matter how I play with MPI/thread/pre-read/copytoscratch/Pool/--maxsig tag, seems no improvement at all. 
This is not big particles, boxsize 164*164, ~929,000 particles, total size is ~90GB.  There must be clog up between CPU and GPU, but I am not sure where and how to find it. Thanks for any hints and help.

**Comment by bforsbe** [comment]
Could you provide some (as many as possible) of the coomands you used, and a representative output from one of the runs? 

It sounds like you are reading from a slow disk, but if you've tried a bunch of combination using pre-read and scratch, i'm not sure what to think. We should be able to work out more through the commands and output though.

**Comment by jianSG** [comment]
Here is the command. I have four GTX1080 card, and use 5 mpi jobs.
# RELION optimiser
# --o Class2D/job065/run --i Sort/job060/particles_sort.star --dont_combine_weights_via_disc --no_parallel_disc_io --preread_images --pool 30 --ctf -
-iter 25 --tau2_fudge 2 --particle_diameter 170 --K 100 --flatten_solvent --zero_mask --strict_highres_exp 15 --oversampling 1 --psi_step 20 --offset
_range 10 --offset_step 4 --norm --scale --j 10 --gpu 

Here is the output so far, please note this job is on a half million particle dataset.
_A interesting comparison is, when I run the same job on the same NFS mount, on another workstation with only TWO GTX1080, it actually two times faster than the 4GPU unit. There must something not right in the 4GPU unit, but not so obvious since nothing crash._
***************************************************************
laplace.3831hfi_wait_for_device: The /dev/hfi1_0 device failed to appear after 15.0 seconds: Connection timed out
laplace.3827hfi_wait_for_device: The /dev/hfi1_0 device failed to appear after 15.0 seconds: Connection timed out
laplace.3828hfi_wait_for_device: The /dev/hfi1_0 device failed to appear after 15.0 seconds: Connection timed out
laplace.3829hfi_wait_for_device: The /dev/hfi1_0 device failed to appear after 15.0 seconds: Connection timed out
laplace.3830hfi_wait_for_device: The /dev/hfi1_0 device failed to appear after 15.0 seconds: Connection timed out
 === RELION MPI setup ===
 + Number of MPI processes             = 5
 + Number of threads per MPI process  = 10
 + Total number of threads therefore  = 50
 + Master  (0) runs on host            = laplace
 + Slave     1 runs on host            = laplace
 + Slave     2 runs on host            = laplace
 + Slave     3 runs on host            = laplace
 + Slave     4 runs on host            = laplace
 =================
 Running CPU instructions in double precision. 
 + WARNING: Changing psi sampling rate (before oversampling) to 11.25 degrees, for more efficient GPU calculations
 Estimating initial noise spectra 
7.82/7.82 min ............................................................~~(,_,">
--------------------------------------------------------------------------
An MPI process has executed an operation involving a call to the
"fork()" system call to create a child process.  Open MPI is currently
operating in a condition that could result in memory corruption or
other system errors; your MPI job may hang, crash, or produce silent
data corruption.  The use of fork() (or system() or other calls that
create child processes) is strongly discouraged.  

The process that invoked fork was:

  Local host:          laplace (PID 3830)
  MPI_COMM_WORLD rank: 3

If you are *absolutely sure* that your application will successfully
and correctly survive a call to fork(), you may disable this warning
by setting the mpi_warn_on_fork MCA parameter to 0.
--------------------------------------------------------------------------
 uniqueHost laplace has 4 ranks.
GPU-ids not specified for this rank, threads will automatically be mapped to available devices.
 Thread 0 on slave 1 mapped to device 0
 Thread 1 on slave 1 mapped to device 0
 Thread 2 on slave 1 mapped to device 0
 Thread 3 on slave 1 mapped to device 0
 Thread 4 on slave 1 mapped to device 0
 Thread 5 on slave 1 mapped to device 0
 Thread 6 on slave 1 mapped to device 0
 Thread 7 on slave 1 mapped to device 0
 Thread 8 on slave 1 mapped to device 0
 Thread 9 on slave 1 mapped to device 0
GPU-ids not specified for this rank, threads will automatically be mapped to available devices.
 Thread 0 on slave 2 mapped to device 1
 Thread 1 on slave 2 mapped to device 1
 Thread 2 on slave 2 mapped to device 1
 Thread 3 on slave 2 mapped to device 1
 Thread 4 on slave 2 mapped to device 1
 Thread 5 on slave 2 mapped to device 1
 Thread 6 on slave 2 mapped to device 1
 Thread 7 on slave 2 mapped to device 1
 Thread 8 on slave 2 mapped to device 1
 Thread 9 on slave 2 mapped to device 1
GPU-ids not specified for this rank, threads will automatically be mapped to available devices.
 Thread 0 on slave 3 mapped to device 2
 Thread 1 on slave 3 mapped to device 2
 Thread 2 on slave 3 mapped to device 2
 Thread 3 on slave 3 mapped to device 2
 Thread 4 on slave 3 mapped to device 2
 Thread 5 on slave 3 mapped to device 2
 Thread 6 on slave 3 mapped to device 2
 Thread 7 on slave 3 mapped to device 2
 Thread 8 on slave 3 mapped to device 2
 Thread 9 on slave 3 mapped to device 2
GPU-ids not specified for this rank, threads will automatically be mapped to available devices.
 Thread 0 on slave 4 mapped to device 3
 Thread 1 on slave 4 mapped to device 3
 Thread 2 on slave 4 mapped to device 3
 Thread 3 on slave 4 mapped to device 3
 Thread 4 on slave 4 mapped to device 3
 Thread 5 on slave 4 mapped to device 3
 Thread 6 on slave 4 mapped to device 3
 Thread 7 on slave 4 mapped to device 3
 Thread 8 on slave 4 mapped to device 3
 Thread 9 on slave 4 mapped to device 3
 Estimating accuracies in the orientational assignment ... 
   3/   3 sec ............................................................~~(,_,">
 Auto-refine: Estimated accuracy angles= 30.1 degrees; offsets= 10.1 pixels
 CurrentResolution= 16.5491 Angstroms, which requires orientationSampling of at least 10.9091 degrees for a particle of diameter 170 Angstroms
 Oversampling= 0 NrHiddenVariableSamplingPoints= 67200
 OrientationalSampling= 11.25 NrOrientations= 32
 TranslationalSampling= 4 NrTranslations= 21
=============================
 Oversampling= 1 NrHiddenVariableSamplingPoints= 2150400
 OrientationalSampling= 5.625 NrOrientations= 256
 TranslationalSampling= 2 NrTranslations= 84
=============================
 Expectation iteration 1 of 25
3.26/3.26 hrs ............................................................~~(,_,">
 Maximization ...
   6/   6 sec ............................................................~~(,_,">
expectation                        : 13713.3 sec (13713254170 microsec/operation)
maximization                       : 5.682 sec (5682413 microsec/operation)
reconstruction                     : 5.681 sec (5681002 microsec/operation)
expectationSomeParticles           : 11678.2 sec (25554012 microsec/operation)
doThreadExpectationSomeParticles   : 10578.8 sec (23148377 microsec/operation)
 - EOP: getFourierTransforms       : 66.616 sec (145768 microsec/operation)
 - EOP: precalcShifts1             : 7.114 sec (15568 microsec/operation)
 - EOP: precalcShifts2             : 4.866 sec (5324 microsec/operation)
 - EOP: getAllSquaredDifferences1  : 22.513 sec (49264 microsec/operation)
 - EOP: getAllSquaredDifferences2  : 30.534 sec (66815 microsec/operation)
 - EOP: getD2: A                   : 3.066 sec (224 microsec/operation)
 - EOP: getD2: B                   : 0.021 sec (0 microsec/operation)
 - EOP: getD2: D                   : 143.53 sec (10528 microsec/operation)
 - EOP: getD2: E                   : 85.547 sec (6275 microsec/operation)
 - EOP: convertDiff2ToWeights1     : 33.938 sec (74262 microsec/operation)
 - EOP: convertDiff2ToWeights2     : 38.975 sec (85285 microsec/operation)
 - EOP: storeWeightedSums          : 260.934 sec (570972 microsec/operation)
 -  - EOPwsum: backproject         : 2.009 sec (4398 microsec/operation)
mpiWaitEndOfExpectation            : 43.215 sec (43215793 microsec/operation)
mpiCombineThroughNetwork           : 0.061 sec (61128 microsec/operation)
mpiSlaveWorking                    : 11678.2 sec (25554016 microsec/operation)
mpiSlaveWaiting1                   : 17.377 sec (37942 microsec/operation)
mpiSlaveWaiting2                   : 8.775 sec (19202 microsec/operation)
mpiSlaveWaiting3                   : 0.17 sec (373 microsec/operation)
 Estimating accuracies in the orientational assignment ... 
   1/   1 sec ............................................................~~(,_,">
 Auto-refine: Estimated accuracy angles= 30.1 degrees; offsets= 10 pixels
 CurrentResolution= 18.204 Angstroms, which requires orientationSampling of at least 12 degrees for a particle of diameter 170 Angstroms
 Oversampling= 0 NrHiddenVariableSamplingPoints= 67200
 OrientationalSampling= 11.25 NrOrientations= 32
 TranslationalSampling= 4 NrTranslations= 21
=============================
 Oversampling= 1 NrHiddenVariableSamplingPoints= 2150400
 OrientationalSampling= 5.625 NrOrientations= 256
 TranslationalSampling= 2 NrTranslations= 84
=============================
 Expectation iteration 2 of 25
7.70/7.70 hrs ............................................................~~(,_,">
 Maximization ...
2.23/2.23 min ............................................................~~(,_,">
expectation                        : 27746.2 sec (27746207945 microsec/operation)
maximization                       : 134.603 sec (134603736 microsec/operation)
reconstruction                     : 134.603 sec (134603009 microsec/operation)
expectationSomeParticles           : 27696 sec (69587893 microsec/operation)
doThreadExpectationSomeParticles   : 27342.8 sec (68700568 microsec/operation)
 - EOP: getFourierTransforms       : 119.763 sec (300913 microsec/operation)
 - EOP: precalcShifts1             : 3.93 sec (9874 microsec/operation)
 - EOP: precalcShifts2             : 1.761 sec (2212 microsec/operation)
 - EOP: getAllSquaredDifferences1  : 25.147 sec (63184 microsec/operation)
 - EOP: getAllSquaredDifferences2  : 72.662 sec (182568 microsec/operation)
 - EOP: getD2: A                   : 16.057 sec (1342 microsec/operation)
 - EOP: getD2: B                   : 0.026 sec (1 microsec/operation)
 - EOP: getD2: D                   : 284.365 sec (23778 microsec/operation)
 - EOP: getD2: E                   : 101.613 sec (8496 microsec/operation)
 - EOP: convertDiff2ToWeights1     : 10.289 sec (25852 microsec/operation)
 - EOP: convertDiff2ToWeights2     : 42.508 sec (106804 microsec/operation)
 - EOP: storeWeightedSums          : 279.549 sec (702386 microsec/operation)
 -  - EOPwsum: backproject         : 22.465 sec (564 microsec/operation)
mpiWaitEndOfExpectation            : 0 sec (69 microsec/operation)
mpiCombineThroughNetwork           : 1.311 sec (1311168 microsec/operation)
mpiSlaveWorking                    : 27696 sec (69587898 microsec/operation)
mpiSlaveWaiting1                   : 12.764 sec (31992 microsec/operation)
mpiSlaveWaiting2                   : 8.16 sec (20504 microsec/operation)
mpiSlaveWaiting3                   : 0.139 sec (349 microsec/operation)
 Estimating accuracies in the orientational assignment ... 
   1/   1 sec ............................................................~~(,_,">
 Auto-refine: Estimated accuracy angles= 30.1 degrees; offsets= 8.5 pixels
 CurrentResolution= 9.58105 Angstroms, which requires orientationSampling of at least 6.42857 degrees for a particle of diameter 170 Angstroms
 Oversampling= 0 NrHiddenVariableSamplingPoints= 67200
 OrientationalSampling= 11.25 NrOrientations= 32
 TranslationalSampling= 4 NrTranslations= 21
=============================
 Oversampling= 1 NrHiddenVariableSamplingPoints= 2150400
 OrientationalSampling= 5.625 NrOrientations= 256
 TranslationalSampling= 2 NrTranslations= 84
=============================
 Expectation iteration 3 of 25
8.45/8.45 hrs ............................................................~~(,_,">
 Maximization ...
   1/   1 sec ............................................................~~(,_,">
expectation                        : 30443.5 sec (30443532343 microsec/operation)
maximization                       : 0.574 sec (574551 microsec/operation)
reconstruction                     : 0.573 sec (573952 microsec/operation)
expectationSomeParticles           : 30404.2 sec (70707491 microsec/operation)
doThreadExpectationSomeParticles   : 29851.9 sec (69422975 microsec/operation)
 - EOP: getFourierTransforms       : 71.561 sec (166421 microsec/operation)
 - EOP: precalcShifts1             : 3.981 sec (9259 microsec/operation)
 - EOP: precalcShifts2             : 1.52 sec (1768 microsec/operation)
 - EOP: getAllSquaredDifferences1  : 19.921 sec (46329 microsec/operation)
 - EOP: getAllSquaredDifferences2  : 80.575 sec (187384 microsec/operation)
 - EOP: getD2: A                   : 11.662 sec (898 microsec/operation)
 - EOP: getD2: B                   : 0.027 sec (1 microsec/operation)
 - EOP: getD2: D                   : 324.017 sec (24970 microsec/operation)
 - EOP: getD2: E                   : 96.906 sec (7468 microsec/operation)
 - EOP: convertDiff2ToWeights1     : 17.511 sec (40724 microsec/operation)
 - EOP: convertDiff2ToWeights2     : 39.606 sec (92108 microsec/operation)
 - EOP: storeWeightedSums          : 325.966 sec (758062 microsec/operation)
 -  - EOPwsum: backproject         : 22.231 sec (517 microsec/operation)
mpiWaitEndOfExpectation            : 0 sec (82 microsec/operation)
mpiCombineThroughNetwork           : 0.065 sec (65653 microsec/operation)
mpiSlaveWorking                    : 30404.2 sec (70707496 microsec/operation)
mpiSlaveWaiting1                   : 13.987 sec (32452 microsec/operation)
mpiSlaveWaiting2                   : 7.56 sec (17583 microsec/operation)
mpiSlaveWaiting3                   : 0.165 sec (385 microsec/operation)
 Estimating accuracies in the orientational assignment ... 
   1/   1 sec ............................................................~~(,_,">
 Auto-refine: Estimated accuracy angles= 25.1 degrees; offsets= 6.4 pixels
 CurrentResolution= 7.585 Angstroms, which requires orientationSampling of at least 5.07042 degrees for a particle of diameter 170 Angstroms
 Oversampling= 0 NrHiddenVariableSamplingPoints= 67200
 OrientationalSampling= 11.25 NrOrientations= 32
 TranslationalSampling= 4 NrTranslations= 21
=============================
 Oversampling= 1 NrHiddenVariableSamplingPoints= 2150400
 OrientationalSampling= 5.625 NrOrientations= 256
 TranslationalSampling= 2 NrTranslations= 84
=============================
 Expectation iteration 4 of 25
1.11/8.51 hrs .......~~(,_,">

**Comment by bforsbe** [comment]
There's a whole lot of initial warnings about MPI and fork() and such things. I woul try sorting those out, because they seem to be messing with something. Are you using MPICH?

**Comment by jianSG** [comment]
The system I am using has TWO Xeon E5-2690 v4 2.4GHz, 14 Cores. Total 28 Cores / 56 with hyperthreading, 512 GB DDR4-2400 ECC (32GB*16), 2*1920GB SSD. FOUR GTX1080,8GB GDDR5X.
We use Open MPI, GCC4.8.5 on CentOS7
**'which mpicc'  /usr/lib64/openmpi/bin/mpicc**
**/usr/lib64/openmpi/bin/mpicc -v**
Using built-in specs.
COLLECT_GCC=/usr/bin/gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/4.8.5/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,objc,obj-c++,java,fortran,ada,go,lto --enable-plugin --enable-initfini-array --disable-libgcj --with-isl=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/cloog-install --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.8.5 20150623 (Red Hat 4.8.5-11) (GCC)

We do notice when we are using 5MPI * whatever thread 4-8  number. Only some of CPU cores are used to 100%, some are 0% . Seems all the threads are competing for some cores but not spread out evenly. Therefore the GPUs only partially used.
![screenshot from 2017-03-08 11-41-15](https://cloud.githubusercontent.com/assets/26193140/23689387/25a7e2e6-03f5-11e7-9dc2-bfcc41905ef5.png)
We can use as many MPI as the core numbers, in order to force to use all the cores. Then it takes very long time to enter first iteration, GPUs are fully occupied, but high chance to get stuck. 
![screenshot from 2017-03-08 11-44-41](https://cloud.githubusercontent.com/assets/26193140/23689386/256239da-03f5-11e7-95ca-30c4962134d3.png)
Somehow, on my another 5 years older workstation, the MPI/Thread jobs are distributed evenly and runs much  faster with only Two 1080s than the NEW One with FOUR 1080
![screenshot from 2017-03-08 11-49-30](https://cloud.githubusercontent.com/assets/26193140/23689403/5041409c-03f5-11e7-8a86-70229e6c4bc9.png)

**Comment by bforsbe** [comment]
Were you able to solve it? It would be good to know if the issue was related to core-pinning and what you did to fix it, if that was the case.

**Comment by jianSG** [comment]
I have NOT fix it yet. 
My old system with two GPUs runs fine and actually runs faster. But the new system with 4 GPUs has this threads balancing issue. And I could not identify the differences and what to take to fix it. It seems related to threading, but I don't know why cause the OS and compiling are all same.

**Comment by bforsbe** [comment]
Try adding the flag --no_parallel_disc_io. This will force all slaves to get data through the master, but you will not need to store data "per slave". This should make it smaller, which may make it fit into RAM and get cached by the OS. In that case you should see one moderate or slow iteration and much faster after than ,since the data does not need be red from disc again.

**Comment by jianSG** [comment]
I did have  --no_parallel_disc_io included already, it was same. 

By the way, I tried to build relion in Debug mode, but always get following error. With other tags, compiling finished OK.
------------------------------------------------------------------------------------
Linking CXX executable ../../bin/relion_autopick_mpi
[100%] Built target refine
/usr/bin/ld: CMakeFiles/autopick_mpi.dir/autopick_mpi.cpp.o: undefined reference to symbol 'cudaGetErrorString'
/usr/local/cuda/lib64/libcudart.so.7.5: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [bin/relion_autopick_mpi] Error 1
make[1]: *** [src/apps/CMakeFiles/autopick_mpi.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[100%] Built target particle_sort_mpi

**Comment by bforsbe** [comment]
try adding -DCMAKE_BUILD_SHARED_LIBS=OFF to you debug build cmake-command.

**Comment by bforsbe** [comment]
Any news?

**Comment by jianSG** [comment]
Not exactly. I reinstalled OS of SL7.3 and CUDA8.0 for further testing. It looks that I have same or very similar issue as https://github.com/3dem/relion/issues/222

**Comment by jianSG** [comment]
I am not sure I should open a new issue or not. The scenario is as follows: 
I have two GPU unit: 
( A) is Two Intel(R) Xeon(R) CPU E5-2640 0 @ 2.50GHz, Six Cores each, hyperthread, 256GB, Two  GeForce GTX 1080. OS CentOS7.3 Linux 3.10.0-327.28.3.el7.x86_64 OpenMPI 1.10.3-3.el7  GCC 4.8.5-11.el7 Cuda 7.5
(B) is Two Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz, Fourteen Cores each, hyperthread, 512GB, Four GeForce GTX 1080. OS SL7.3 Linux 3.10.0-514.6.1.el7.x86_64 OpenMPI 1.10.3-3.el7  GCC 4.8.5-11.el7 Cuda 7.5
A was bought FIVE years ago, B is bought this year. GPUs are bought in this year. Somehow, A is running Relion-GPU faster than B, which does not make any sense to me. 

There are two ways to compare Relion-GPU run on a same 2M particle dataset (~240GB) at the same time: 
If running with MPI, the process on B basically stalls at first iteration of expectation step, no timing shows up and no actual job running on GPUs, on the other hand A has no problem to start and occupy GPUs.
If running with pure thread only, both A and B start job well and occupy GPUs OK. But somehow, A is still running faster than B, while with two GTX1080s than four GTX1080s, and five year old CPUs than new generation CPUs. 
I have been struggling with this issue for few months, and could not figure out where is the catch, since I did not do any special on B, my five years old workstation at all.

Here is all the command I did after a fresh installation of SL7.3 live Genorm 
********************************************
set user/ip during the installation
systemctl disable firewalld.service
vi /etc/sysconfig/selinux to disable
systemctl start/enable sshd
systemctl set-default multi-user.target
reboot
yum install epel-release
yum install dkms
yum install  libvdpau
yum install tbb-devel.x86_64
yum clean all
updatedb
reboot
yum install cmake
rpm -i cuda-repo-rhel7-7-5-local-7.5-18.x86_64.rpm
yum clean all
yum install cuda
vi /etc/hosts
mkdir /mnt/cbis_images
mount -t nfs komodo:/mnt/cbis/images        /mnt/cbis_images
copy .tcshrc
reboot 
**yum install openmpi.x86_64 openmpi-devel.x86_64
 wget http://us.download.nvidia.com/XFree86/Linux-x86_64/375.39/NVIDIA-Linux-x86_64-375.39.run
 sh NVIDIA-Linux-x86_64-375.39.run 
 lsmod | grep nvi
 reboot now
 lsmod | grep nvi
git clone https://github.com/3dem/relion.git
cmake  -DCUDA_ARCH=52 ..
make
*********************************************************************

**Comment by bforsbe** [comment]
Sounds like an MPI/hardware mapping issue, but it's hard to say.

1. Is it the same command as above? Could you provide the command again, just to verify it? 
2. What do you get from running   ```nvidia-smi topo -m``` on A and B ?

**Comment by jianSG** [comment]
The command in threads as follows: Somehow A still running faster than B.
A) `which relion_refine` --o Class2D/job037/run --i Sort/job014/particles_sort.star --dont_combine_weights_via_disc --no_parallel_disc_io --preread_images  --pool 500 --ctf  --iter 25 --tau2_fudge 2 --particle_diameter 172 --K 50 --flatten_solvent  --zero_mask  --strict_highres_exp 15 --oversampling 1 --psi_step 20 --offset_range 10 --offset_step 4 --norm --scale  --j 18 --gpu "0,0,0,0,0,0,0,0,0,2,2,2,2,2,2,2,2,2" --dont_check_norm

B) `which relion_refine` --o Class2D/job037/run --i Sort/job014/particles_sort.star --dont_combine_weights_via_disc --no_parallel_disc_io --preread_images  --pool 500 --ctf  --iter 25 --tau2_fudge 2 --particle_diameter 172 --K 50 --flatten_solvent  --zero_mask  --strict_highres_exp 15 --oversampling 1 --psi_step 20 --offset_range 10 --offset_step 4 --norm --scale  --j 28 --gpu "0,0,0,0,0,0,0,1,1,1,1,1,1,1,2,2,2,2,2,2,2,3,3,3,3,3,3,3" --dont_check_norm


Output of nvidia-smi topo -m
A)
	GPU0	GPU1	GPU2	CPU Affinity
GPU0	 X 	PHB	SOC	0-5,12-17
GPU1	PHB	 X 	SOC	                                    (This is a Quadro 2000 for display only)
GPU2	SOC	SOC	 X 	6-11,18-23

B)
	GPU0	GPU1	GPU2	GPU3	mlx4_0	CPU Affinity
GPU0	 X 	PHB	SOC	SOC	PHB	0-13,28-41
GPU1	PHB	 X 	SOC	SOC	PHB	0-13,28-41
GPU2	SOC	SOC	 X 	PHB	SOC	14-27,42-55
GPU3	SOC	SOC	PHB	 X 	SOC	14-27,42-55
mlx4_0	PHB	PHB	SOC	SOC	 X 	

Legend:
  X   = Self
  SOC  = Connection traversing PCIe as well as the SMP link between CPU sockets(e.g. QPI)
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe switches (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing a single PCIe switch
  NV#  = Connection traversing a bonded set of # NVLinks

**Comment by bforsbe** [comment]
What happens if you run 

```
which relion_refine --o Class2D/job037/run --i Sort/job014/particles_sort.star --dont_combine_weights_via_disc --pool 50 --ctf --iter 25 --tau2_fudge 2 --particle_diameter 172 --K 50 --flatten_solvent --zero_mask --strict_highres_exp 15 --oversampling 1 --psi_step 20 --offset_range 10 --offset_step 4 --norm --scale --j 12 --gpu  --dont_check_norm 
```
on B?  I would like to see the terminal output from start until at least the first time estimate of 1st iteration expectation.

**Comment by jianSG** [comment]
This is output of the command you suggested, while on system A (2GPUs), iteration 2 took 12 hours.
************************************************************
gpu-ids not specified, threads will automatically be mapped to devices (incrementally).
 Thread 0 mapped to device 0
 Thread 1 mapped to device 0
 Thread 2 mapped to device 0
 Thread 3 mapped to device 1
 Thread 4 mapped to device 1
 Thread 5 mapped to device 1
 Thread 6 mapped to device 2
 Thread 7 mapped to device 2
 Thread 8 mapped to device 2
 Thread 9 mapped to device 3
 Thread 10 mapped to device 3
 Thread 11 mapped to device 3
 Running CPU instructions in double precision. 
 + WARNING: Changing psi sampling rate (before oversampling) to 11.25 degrees, for more efficient GPU calculations
 Estimating initial noise spectra 
1.29/1.29 hrs ............................................................~~(,_,">
 Estimating accuracies in the orientational assignment ... 
   1/   1 sec ............................................................~~(,_,">
 Auto-refine: Estimated accuracy angles= 30.1 degrees; offsets= 10.1 pixels
 CurrentResolution= 16.564 Angstroms, which requires orientationSampling of at least 10.9091 degrees for a particle of diameter 172 Angstroms
 Oversampling= 0 NrHiddenVariableSamplingPoints= 33600
 OrientationalSampling= 11.25 NrOrientations= 32
 TranslationalSampling= 4 NrTranslations= 21
=============================
 Oversampling= 1 NrHiddenVariableSamplingPoints= 1075200
 OrientationalSampling= 5.625 NrOrientations= 256
 TranslationalSampling= 2 NrTranslations= 84
=============================
 Expectation iteration 1 of 25
2.83/2.83 hrs ............................................................~~(,_,">
 Maximization ...
   1/   1 sec ............................................................~~(,_,">
 Estimating accuracies in the orientational assignment ... 
   1/   1 sec ............................................................~~(,_,">
 Auto-refine: Estimated accuracy angles= 30.1 degrees; offsets= 10.1 pixels
 CurrentResolution= 8.67638 Angstroms, which requires orientationSampling of at least 5.71429 degrees for a particle of diameter 172 Angstroms
 Oversampling= 0 NrHiddenVariableSamplingPoints= 33600
 OrientationalSampling= 11.25 NrOrientations= 32
 TranslationalSampling= 4 NrTranslations= 21
=============================
 Oversampling= 1 NrHiddenVariableSamplingPoints= 1075200
 OrientationalSampling= 5.625 NrOrientations= 256
 TranslationalSampling= 2 NrTranslations= 84
=============================
 Expectation iteration 2 of 25
4.48/22.62 hrs ...........~~(,_,">

**Comment by biochem-fan** [comment]
Too old issue. Class2D will be re-written in the next major update.
