### ISSUE TITLE
Error when setting --sym i

### ISSUE THREAD

**Issue by alexxy** [3dem/relion#211]
When i try to use symmetry i getting error 

`1
KERNEL_ERROR: invalid configuration argument in /run/user/root/relion/src/gpu_utils/cuda_helper_functions.cuh at line 149 (error-code 9)
KERNEL_ERROR: invalid configuration argument in /run/user/root/relion/src/gpu_utils/cuda_helper_functions.cuh at line 149 (error-code 9)
`

however i dont get any error with c1 or i1

**Comment by dkimanius** [comment]
Thanks for reporting this issue. However, the lack of relevant information to begin debugging it is devastating. Could you provide all the relevant logs and output files. 

I don't see this issue when running with --sym I, so it's either data-dependent or something is wrong with your build. Please also let us know how you've built relion, include compiler and FFTW versions.

**Comment by alexxy** [comment]
Relion was built with gcc-5.4.0 cuda-8.0 fftw-3.3.4

I can provide sample input to reproduce this error. It may be data dependent but i'm not sure.

Should reference map has needed symmetry? or its not needed due to lowpass filter?

**Comment by dkimanius** [comment]
Although an asymmetric input model might give you slightly slower refinement it should not cause an error like this. Specially if I1 and C1 works fine. I'm assuming this error occurs at the start of the first iteration.
Just to be super clear, which relion version is this?

**Comment by dkimanius** [comment]
Also if you can provide data that reproduces this I wouldn't mind trying it out here.

**Comment by alexxy** [comment]
Ok. Relion version is 2.0.2-2.0.4 on all of them i can reproduce this bug, it seems to be depend on data.

**Comment by biochem-fan** [comment]
The icosahedral symmetry should be I1, I2, I3 or I4. Closing.
