### ISSUE TITLE
Support Tiff files

### ISSUE THREAD

**Issue by barureddy** [3dem/relion#212]
Wtih motioncor2, tiff movie files are now allowed as inputs. Often tiff movie files (with LZW compression) are just a fraction of the size of mrc movie files and many EM scopes have switched to this format. It would be great if relion supported this.

**Comment by ninthpower** [comment]
+1, barureddy and I have both been reporting issues with this. If I had a few days to spare I could surely write a script to run motioncorr2 on a folder of tiffs and convert them and write the star file, but it seems like a no brainer that this is added as a feature for the next update.

**Comment by alburse** [comment]
+1 please support tiff files with LZW compression.

**Comment by biochem-fan** [comment]
The next version (3.0) will have TIFF support and our own implementation of motion correction.
