### ISSUE TITLE
do_all_reconstruct_ctfs.sh bug with certain small box sizes

### ISSUE THREAD

**Issue by anaphaze** [3dem/relion#215]
In RELION 2, do_all_reconstruct_ctfs.sh crashes when the box size is 22, 24, 26 with this message:
`Segmentation fault (core dumped)`

Strangely, odd size boxes (21, 23, 25, 27) all work. This is probably a fringe case, but I get this problem on both the CPU and GPU versions of RELION 2.0.

If I re-run the script, but generated for RELION 1.x, then I get a correct CTF  #file.

**Comment by biochem-fan** [comment]
This script is deprecated in 3.1.
