### ISSUE TITLE
regression when switching from 2.0.3 to 2.0.4 GPU version

### ISSUE THREAD

**Issue by schloegl** [3dem/relion#221]
After upgrading to relion 2.0.4 (compiled with cuda support) the 3d-classification stalls, no estimate for the runtime is provided, although nvidia-smi shows 100 % utilization. 

We run this on node with 4xGTX 980 cards, one GPU is dedicated to some other project, 3 GPU's are used by relion. Relion has been compiled with the following options 

cmake -DCUDA_ARCH=52 -DFORCE_OWN_FFTW=ON -DFORCE_OWN_FLTK=ON -DCMAKE_INSTALL_PREFIX=/mnt/nfs/clustersw/debian/jessie/cuda7.5/relion-2.0.4c .. && make 

2.0.4 was compiled from commit 9a8dfbae0d78e7ece3847 and d401f241afcb086a5c26, it does not make a difference. The exact same run.job is used with 2.0.3 and 2.0.4 (see attachment)

When running with 2.0.4 the following logs are generated, GPU 1-3 are 100 % utilized, but no runtime estimation is provided and no output is generated.

` === RELION MPI setup ===
 + Number of MPI processes             = 4
 + Number of threads per MPI process  = 2
 + Total number of threads therefore  = 8
 + Master  (0) runs on host            = gpu62
 + Slave     1 runs on host            = gpu62
 + Slave     2 runs on host            = gpu62
 + Slave     3 runs on host            = gpu62
 =================
 uniqueHost gpu62 has 3 ranks.
 Using explicit indexing on slave 1 to assign devices  1 1
 Thread 0 on slave 1 mapped to device 1
 Thread 1 on slave 1 mapped to device 1
 Using explicit indexing on slave 2 to assign devices  2 2
 Thread 0 on slave 2 mapped to device 2
 Thread 1 on slave 2 mapped to device 2
 Using explicit indexing on slave 3 to assign devices  3 3
 Thread 0 on slave 3 mapped to device 3
 Thread 1 on slave 3 mapped to device 3
 Running CPU instructions in double precision. 
 + On host gpu62: free scratch space = 1785 Gb.
 Copying particles to scratch directory: /ssdpool/relion_volatile/
000/??? sec ~~(,_,">                    
 Estimating accuracies in the orientational assignment ... 
000/??? sec ~~(,_,">                    
 Auto-refine: Estimated accuracy angles= 2.027 degrees; offsets= 1.4 pixels
 CurrentResolution= 29.4737 Angstroms, which requires orientationSampling of at least 9.47368 degrees for a particle of diameter 350 Angstroms
 Oversampling= 0 NrHiddenVariableSamplingPoints= 1492992
 OrientationalSampling= 15 NrOrientations= 4608
 TranslationalSampling= 4 NrTranslations= 81
=============================
 Oversampling= 1 NrHiddenVariableSamplingPoints= 47775744
 OrientationalSampling= 7.5 NrOrientations= 36864
 TranslationalSampling= 2 NrTranslations= 324
=============================
 Expectation iteration 2 of 150
000/??? sec ~~(,_,">                    
mpirun noticed that process rank 2 with PID 0 on node gpu62 exited on signal 15 (Terminated).
--------------------------------------------------------------------------
`
Eventually we killed to process and restarted with 2.0.3, which gives the following logs. 

` === RELION MPI setup ===
 + Number of MPI processes             = 4
 + Number of threads per MPI process  = 2
 + Total number of threads therefore  = 8
 + Master  (0) runs on host            = gpu62
 + Slave     1 runs on host            = gpu62
 + Slave     2 runs on host            = gpu62
 + Slave     3 runs on host            = gpu62
 =================
 Running CPU instructions in double precision. 
 + On host gpu62: free scratch space = 1785 Gb.
 Copying particles to scratch directory: /ssdpool/relion_volatile/
000/??? sec ~~(,_,">                    
 uniqueHost gpu62 has 3 ranks.
 Using explicit indexing on slave 1 to assign devices  1 1
 Thread 0 on slave 1 mapped to device 1
 Thread 1 on slave 1 mapped to device 1
 Using explicit indexing on slave 2 to assign devices  2 2
 Thread 0 on slave 2 mapped to device 2
 Thread 1 on slave 2 mapped to device 2
 Using explicit indexing on slave 3 to assign devices  3 3
 Thread 0 on slave 3 mapped to device 3
 Thread 1 on slave 3 mapped to device 3
 Estimating accuracies in the orientational assignment ... 
000/??? sec ~~(,_,">                    
 Auto-refine: Estimated accuracy angles= 2.027 degrees; offsets= 1.4 pixels
 CurrentResolution= 29.4737 Angstroms, which requires orientationSampling of at least 9.47368 degrees for a particle of diameter 350 Angstroms
 Oversampling= 0 NrHiddenVariableSamplingPoints= 1492992
 OrientationalSampling= 15 NrOrientations= 4608
 TranslationalSampling= 4 NrTranslations= 81
=============================
 Oversampling= 1 NrHiddenVariableSamplingPoints= 47775744
 OrientationalSampling= 7.5 NrOrientations= 36864
 TranslationalSampling= 2 NrTranslations= 324
=============================
 Expectation iteration 2 of 150
000/??? sec ~~(,_,">                    
 Maximization ...
000/??? sec ~~(,_,">                    
 Estimating accuracies in the orientational assignment ... 
000/??? sec ~~(,_,">                    
 Auto-refine: Estimated accuracy angles= 3.693 degrees; offsets= 2.601 pixels
 CurrentResolution= 25.4545 Angstroms, which requires orientationSampling of at least 8.18182 degrees for a particle of diameter 350 Angstroms
 Oversampling= 0 NrHiddenVariableSamplingPoints= 1492992
 OrientationalSampling= 15 NrOrientations= 4608
 TranslationalSampling= 4 NrTranslations= 81
=============================
 Oversampling= 1 NrHiddenVariableSamplingPoints= 47775744
 OrientationalSampling= 7.5 NrOrientations= 36864
 TranslationalSampling= 2 NrTranslations= 324
=============================
 Expectation iteration 3 of 150
000/??? sec ~~(,_,">                    
`

We noticed also that with 2.0.3 "Copying particles to scratch ..." comes before "... assign devices...", with 2.0.4 this seems reversed, its not clear whether this is of importance. 

The issue is reproducible. Do you have any ideas/suggestions how to address that issue ? 

[run.job.txt](https://github.com/3dem/relion/files/875629/run.job.txt)

**Comment by bforsbe** [comment]
Thanks for this. I had observations of second iter stalls when compiling for cuda compute 61, but never for 52. In fact, compiling for 52 has been able to solve this issue, so if you are sure you see it with -DCUDA_ARCH=52, then that's a new observation. Just to exclude some possibilities, you called cmake in a clean (empty) build directory, right?

**Comment by schloegl** [comment]
Yes, I compiled compiled from a clean environment. I've set up a separate build directories for each compilation (different commit's and different openmpi versions).

**Comment by bforsbe** [comment]
I just updated the code to include a newer version of the lib-tools ([CUB](https://github.com/NVlabs/cub) 1.6.4) we use for sort/scan/max/etc, which have some updates for both maxwell and pascal. I get rid of some stalls using this, so I'd recommend you pull 2.0.6 and try it out.

**Comment by schloegl** [comment]
First tests indicate that this issue is indeed solved. Thanks.
