### ISSUE TITLE
error when install relion 2.0.4

### ISSUE THREAD

**Issue by YANYANZH** [3dem/relion#223]
I'm installing relion 2.0 on my GPU station desktop. THe system is ubuntu 16.10.
The cmake step was fine. but I got this error in make step. Can you give me some advice on solving this problem? 

[ 50%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/Healpix_2.15a/healpix_base.cc.o
[ 51%] Linking CXX shared library ../../lib/librelion_lib.so
/usr/bin/ld: /home/yanyan/.fltk/lib/libfltk.a(Fl.o): relocation R_X86_64_PC32 against symbol `_ZN2Fl8e_numberE' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
src/apps/CMakeFiles/relion_lib.dir/build.make:1537: recipe for target 'lib/librelion_lib.so' failed
make[2]: *** [lib/librelion_lib.so] Error 1
CMakeFiles/Makefile2:1099: recipe for target 'src/apps/CMakeFiles/relion_lib.dir/all' failed
make[1]: *** [src/apps/CMakeFiles/relion_lib.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by bforsbe** [comment]
Your installation of FLTK is not a shared-enabled library. Either;

1.  Add the flag -DFORCE_OWN_FLTK=ON to the cmake configuration step. If you do, make sure to clean your build-directory completely, or make a new build directory. 
2. Re-compile and install your system FLTK with the --enable-shared flag. 

The easiest is the first. It won't affect performance or functionality, but the installation of relion will take a few minutes longer.

**Comment by YANYANZH** [comment]
I tried the first, and it worked. Thank you so much.
