### ISSUE TITLE
Relion2.0 Compile Error

### ISSUE THREAD

**Issue by 3rdfloorTom** [3dem/relion#224]
I've been running into trouble with corrupted header from 3d classification and refinement using relion2.0 installed via "sudo apt-get install relion" which someone told me isn't an issue if compile from source.

However, I'm running it to some errors upon running "make -j N". The error message states that the OpenMPI wrapper can't find the specified g++ compiler in the current PATH. I ran cmake with gcc-5 and g++-5 which are in my /usr/bin on the PATH. Also tried setting CC and CXX environment variables explicitly.  I've put the output from cmake and make below

Fairly new to linux, so any help appreciated! 
I'm running Ubuntu 16.04.1 LTS.

Thanks!

--------------------------------------------------------------------------------------------
cmake ..
-- The C compiler identification is GNU 5.4.1
-- The CXX compiler identification is GNU 5.4.1
-- Check for working C compiler: /usr/bin/gcc-5
-- Check for working C compiler: /usr/bin/gcc-5 -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/g++-5
-- Check for working CXX compiler: /usr/bin/g++-5 -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- BUILD TYPE set to the default type:  'Release'
-- Setting fallback CUDA_ARCH=35
-- Setting cpu precision to double
-- Setting gpu precision to single
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found CUDA: /usr/local/cuda (found version "8.0") 
-- Using cuda wrapper to compile....
-- Cuda version is >= 7.5 and single-precision build, enable double usage warning.
-- Found MPI_C: /opt/packages/openmpi-2.0.1/lib/libmpi.so  
-- Found MPI_CXX: /opt/packages/openmpi-2.0.1/lib/libmpi.so  
-- MPI_INCLUDE_PATH : /opt/packages/openmpi-2.0.1/include
-- MPI_LIBRARIES : /opt/packages/openmpi-2.0.1/lib/libmpi.so
-- MPI_CXX_INCLUDE_PATH : /opt/packages/openmpi-2.0.1/include
-- MPI_CXX_LIBRARIES : /opt/packages/openmpi-2.0.1/lib/libmpi.so
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Looking for IceConnectionNumber in ICE
-- Looking for IceConnectionNumber in ICE - found
-- Found X11: /usr/lib/x86_64-linux-gnu/libX11.so
-- Could NOT find FLTK (missing:  FLTK_LIBRARIES FLTK_INCLUDE_DIR FLTK_FLUID_EXECUTABLE) 
-- FLTK was NOT found
-- -------------------------------------------------
-- ------- WILL USE LOCALLY BUILT FLTK LIBS --------
-- -------------------------------------------------
-- Found previously built external (non-system) FLTK library
-- FLTK_INCLUDE_DIR: /opt/packages/relion/external/fltk/include
-- FLTK_LIBRARIES:   /opt/packages/relion/external/fltk/lib/libfltk.so
-- Double-precision FFTW was NOT found
-- -------------------------------------------------
-- ------- WILL USE LOCALLY BUILT FFTW LIBS --------
-- -------------------------------------------------
-- Found previously built external (non-system) FFTW library
-- FFTW_INCLUDES:     /opt/packages/relion/external/fftw/include
-- FFTW_LIBRARIES:    /opt/packages/relion/external/fftw/lib/libfftw3.so
-- Looking for sincos
-- Looking for sincos - found
-- Looking for __sincos
-- Looking for __sincos - not found
-- Building shared libs (smaller build size and binaries)
-- CMAKE_BINARY_DIR:/opt/packages/relion/build
-- added run_motioncorr_mpi...
-- added particle_symmetry_expand...
-- added particle_sort_mpi...
-- added particle_sort...
-- added star_compare...
-- added postprocess...
-- added preprocess_mpi...
-- added tiltpair_plot...
-- added display...
-- added mask_create...
-- added find_tiltpairs...
-- added particle_reposition...
-- added preprocess...
-- added run_ctffind_mpi...
-- added autopick_mpi...
-- added helix_toolbox...
-- added refine_mpi...
-- added run_ctffind...
-- added run_motioncorr...
-- added particle_polish...
-- added project...
-- added refine...
-- added image_handler...
-- added particle_polish_mpi...
-- added stack_create...
-- added manualpick...
-- added autopick...
-- added reconstruct...
-- added postprocess_mpi...
-- added pipeliner...
-- added maingui...
-- added star_combine...
-- Configuring done
-- Generating done
-- Build files have been written to: /opt/packages/relion/build
-----------------------------------------------------------------------------------------------------------------------------

make -j 16
Scanning dependencies of target copy_scripts
[  1%] Building NVCC (Device) object src/apps/CMakeFiles/relion_gpu_util.dir/__/gpu_utils/relion_gpu_util_generated_cuda_benchmark_utils.cu.o
[  2%] Building NVCC (Device) object src/apps/CMakeFiles/relion_gpu_util.dir/__/gpu_utils/cuda_kernels/relion_gpu_util_generated_helper.cu.o
[  3%] Building NVCC (Device) object src/apps/CMakeFiles/relion_gpu_util.dir/__/gpu_utils/relion_gpu_util_generated_cuda_projector.cu.o
[  4%] Building NVCC (Device) object src/apps/CMakeFiles/relion_gpu_util.dir/__/gpu_utils/relion_gpu_util_generated_cuda_helper_functions.cu.o
[  4%] Building NVCC (Device) object src/apps/CMakeFiles/relion_gpu_util.dir/__/gpu_utils/relion_gpu_util_generated_cuda_projector_plan.cu.o
[  5%] Building NVCC (Device) object src/apps/CMakeFiles/relion_gpu_util.dir/__/gpu_utils/relion_gpu_util_generated_cuda_backprojector.cu.o
[  6%] Building NVCC (Device) object src/apps/CMakeFiles/relion_gpu_util.dir/__/gpu_utils/relion_gpu_util_generated_cuda_autopicker.cu.o
[  7%] Building NVCC (Device) object src/apps/CMakeFiles/relion_gpu_util.dir/__/gpu_utils/relion_gpu_util_generated_cuda_ml_optimiser.cu.o
[  7%] Built target copy_scripts
Scanning dependencies of target relion_gpu_util
[  7%] Linking CXX shared library ../../lib/librelion_gpu_util.so
--------------------------------------------------------------------------
The Open MPI wrapper compiler was unable to find the specified compiler
g++ in your PATH.

Note that this compiler was either specified at configure time or in
one of several possible environment variables.
--------------------------------------------------------------------------
src/apps/CMakeFiles/relion_gpu_util.dir/build.make:142: recipe for target 'lib/librelion_gpu_util.so' failed
make[2]: *** [lib/librelion_gpu_util.so] Error 1
CMakeFiles/Makefile2:758: recipe for target 'src/apps/CMakeFiles/relion_gpu_util.dir/all' failed
make[1]: *** [src/apps/CMakeFiles/relion_gpu_util.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by SalahBioPhysics** [comment]
@3rdfloorTom did you fix this problem?  I'm running into the same problem

**Comment by 3rdfloorTom** [comment]
I have OpenMPI in the PATH and then switch the gcc/++ to versions 4.8 instead of 5+ and it worked.
Hope that helps.
