### ISSUE TITLE
CudaCustomAlloc out of memory

### ISSUE THREAD

**Issue by achintangal** [3dem/relion#226]
Hello,

I don't know if this issue is an actual bug, if not I'd be happy to move this to another place. 

Back to the problem at hand, researchers in our lab are quite happy with relion2, but they seem to run into this specific error( see below) sporadically. 

**cudaCustomAllocator out of memory
 [requestedSpace:             44135424 B]
 [largestContinuousFreeSpace: 29665280 B]
 [totalFreeSpace:             39136768 B]**

For your reference, I have added information about the datasets and hardware. 

This has been observed with the following datasets:

1. 250k particles, 140x140 box size
2.  240k particles, 256x256 box size 

The relion version on this machine has been built using (commit 195e6f2a06aed4bb2d7758db53ec919876c17a7d - v 2.0.3 - stable) with openmpi/2.0.1 and cuda/8.0 

Here are the specs of the hardware:

Tue Apr 11 14:13:08 2017       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 375.26                 Driver Version: 375.26                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 1080    Off  | 0000:03:00.0      On |                  N/A |
| 55%   82C    P2    87W / 180W |   6946MiB /  8113MiB |     79%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX 1080    Off  | 0000:04:00.0     Off |                  N/A |
| 60%   83C    P2    83W / 180W |   7617MiB /  8113MiB |     96%      Default |
+-------------------------------+----------------------+----------------------+
|   2  GeForce GTX 1080    Off  | 0000:81:00.0     Off |                  N/A |
| 47%   63C    P8    13W / 180W |      3MiB /  8113MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   3  GeForce GTX 1080    Off  | 0000:82:00.0     Off |                  N/A |
| 38%   50C    P8    12W / 180W |      3MiB /  8113MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

cudaCustomAllocator out of memory
 [requestedSpace:             44135424 B]
 [largestContinuousFreeSpace: 29665280 B]
 [totalFreeSpace:             39136768 B]
[512B] (36864B) (165888B) (36864B) (512B) (512B) (2048B) [15872B] (165888B) [55296B] (36864B) (165888B) [18432B] (36864B) (165888B) (73728B) (73728B) [18432B] (82944B) [82944B] (82944B) (84480B) [3096576B] (84480B) (49486336B) (98972160B) (98972160B) (98972160B) (98972160B) (197944320B) [5302272B] (49480704B) (98961408B) (98961408B) (98961408B) (98961408B) (197922816B) (44871168B) (44871168B) (44062720B) [881152B] (44062720B) [29665280B] = 1504869376B

**Comment by bforsbe** [comment]
Hard to say anything without knowing the command being run.

**Comment by achintangal** [comment]
Sorry about the delay. Here are the two batch.run files from the different runs that ran into the same error. 
[run2.job.txt](https://github.com/3dem/relion/files/926864/run2.job.txt)

[run.job.txt](https://github.com/3dem/relion/files/926861/run.job.txt)

Thanks for looking into this.

**Comment by bforsbe** [comment]
This (run2.job.xt);
```
Which GPUs to use: == 0,1,2,3
Number of MPI procs: == 5
Number of threads: == 4
```
is a very bad idea. You are saying "Distribute the first MPI-rank across all GPUs. Then do the same for all other MPI ranks." I'm not surprised that you run out of memory in that case. The better option is to leave it to relion to figure out how to mp to GPUs, especially if you want to use all of them. If you specified 
``` --gpu 0,1,2,3 ```
try simply 
``` --gpu ``` 
instead. I'd be very surprised if that too ran out of memory, in that case it might be your data/run config that needs some tweaking to stabilize. I know how to do that, but let's not revert to it unnecessarily. 

For run.job.txt, it's not obvious to me why it fails. I'd guess that you had some other process competing for GPU memory, but it's hard to be sure. Do you have a log of the terminal output?

**Comment by bforsbe** [comment]
Any news?
