### ISSUE TITLE
RELION 2.0 installation error

### ISSUE THREAD

**Issue by biohydrochen** [3dem/relion#227]
libtool: link: gcc -std=gnu99 -O3 -fomit-frame-pointer -mtune=native -malign-double -fstrict-aliasing -fno-schedule-insns -ffast-math -o .libs/fftw-wisdom fftw_wisdom-fftw-wisdom.o ../tests/bench-bench.o ../tests/bench-fftw-bench.o  ../.libs/libfftw3.so ../libbench2/libbench2.a -lm -Wl,-rpath -Wl,/home/xny/relion/external/fftw/lib
Making all in m4
[ 16%] Performing install step for 'OWN_FFTW'
Making install in support
Making install in kernel
Making install in simd-support
Making install in dft
Making install in scalar
Making install in codelets
Making install in simd
Making install in common
Making install in sse2
Making install in avx
Making install in altivec
Making install in neon
Making install in rdft
Making install in scalar
Making install in r2cf
Making install in r2cb
Making install in r2r
Making install in simd
Making install in common
Making install in sse2
Making install in avx
Making install in altivec
Making install in neon
Making install in reodft
Making install in api
 /bin/mkdir -p '/home/xny/relion/external/fftw/include'
 /bin/mkdir -p '/home/xny/relion/external/fftw/include'
 /usr/bin/install -c -m 644 fftw3.h fftw3.f fftw3l.f03 fftw3q.f03 '/home/xny/relion/external/fftw/include'
 /usr/bin/install -c -m 644 fftw3.f03 '/home/xny/relion/external/fftw/include'
Making install in libbench2
Making install in .
 /bin/mkdir -p '/home/xny/relion/external/fftw/lib'
 /bin/mkdir -p '/home/xny/relion/external/fftw/lib/pkgconfig'
 /bin/bash ./libtool   --mode=install /usr/bin/install -c   libfftw3.la '/home/xny/relion/external/fftw/lib'
 /usr/bin/install -c -m 644 fftw3.pc '/home/xny/relion/external/fftw/lib/pkgconfig'
libtool: install: /usr/bin/install -c .libs/libfftw3.so.3.4.4 /home/xny/relion/external/fftw/lib/libfftw3.so.3.4.4
libtool: install: (cd /home/xny/relion/external/fftw/lib && { ln -s -f libfftw3.so.3.4.4 libfftw3.so.3 || { rm -f libfftw3.so.3 && ln -s libfftw3.so.3.4.4 libfftw3.so.3; }; })
libtool: install: (cd /home/xny/relion/external/fftw/lib && { ln -s -f libfftw3.so.3.4.4 libfftw3.so || { rm -f libfftw3.so && ln -s libfftw3.so.3.4.4 libfftw3.so; }; })
libtool: install: /usr/bin/install -c .libs/libfftw3.lai /home/xny/relion/external/fftw/lib/libfftw3.la
libtool: install: /usr/bin/install -c .libs/libfftw3.a /home/xny/relion/external/fftw/lib/libfftw3.a
libtool: install: chmod 644 /home/xny/relion/external/fftw/lib/libfftw3.a
libtool: install: ranlib /home/xny/relion/external/fftw/lib/libfftw3.a
libtool: finish: PATH="/usr/local/cuda/bin:/usr/local/cuda-8.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/local/openmpi/bin:/sbin" ldconfig -n /home/xny/relion/external/fftw/lib
----------------------------------------------------------------------
Libraries have been installed in:
   /home/xny/relion/external/fftw/lib

If you ever happen to want to link against installed libraries
in a given directory, LIBDIR, you must either use libtool, and
specify the full pathname of the library, or use the `-LLIBDIR'
flag during linking and do at least one of the following:
   - add LIBDIR to the `LD_LIBRARY_PATH' environment variable
     during execution
   - add LIBDIR to the `LD_RUN_PATH' environment variable
     during linking
   - use the `-Wl,-rpath -Wl,LIBDIR' linker flag
   - have your system administrator add LIBDIR to `/etc/ld.so.conf'

See any operating system documentation about shared libraries for
more information, such as the ld(1) and ld.so(8) manual pages.
----------------------------------------------------------------------
Making install in threads
Making install in tests
Making install in mpi
Making install in doc
Making install in FAQ
 /bin/mkdir -p '/home/xny/relion/external/fftw/share/info'
 /usr/bin/install -c -m 644 ./fftw3.info ./fftw3.info-1 ./fftw3.info-2 '/home/xny/relion/external/fftw/share/info'
 install-info --info-dir='/home/xny/relion/external/fftw/share/info' '/home/xny/relion/external/fftw/share/info/fftw3.info'
Making install in tools
 /bin/mkdir -p '/home/xny/relion/external/fftw/bin'
 /bin/mkdir -p '/home/xny/relion/external/fftw/bin'
 /bin/mkdir -p '/home/xny/relion/external/fftw/share/man/man1'
  /bin/bash ../libtool   --mode=install /usr/bin/install -c fftw-wisdom '/home/xny/relion/external/fftw/bin'
 /usr/bin/install -c fftw-wisdom-to-conf '/home/xny/relion/external/fftw/bin'
 /usr/bin/install -c -m 644 fftw-wisdom-to-conf.1 fftw-wisdom.1 '/home/xny/relion/external/fftw/share/man/man1'
libtool: install: /usr/bin/install -c .libs/fftw-wisdom /home/xny/relion/external/fftw/bin/fftw-wisdom
Making install in m4
[ 16%] Completed 'OWN_FFTW'
[ 16%] Built target OWN_FFTW
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by bforsbe** [comment]
Could you show the cmake config cammand and output, and perhaps all of the installation output as well? Please zip them and attach a file.

**Comment by biochem-fan** [comment]
No response for a long time and probably not relevant for 3.0. Closing.
