### ISSUE TITLE
when type command: "make install", errors here

### ISSUE THREAD

**Issue by biohydrochen** [3dem/relion#228]
xny@xny-HP-Z620-Workstation:~/relion/build$ make install
-- BUILD TYPE set to the default type:  'Release'
-- Setting fallback CUDA_ARCH=35
-- Setting cpu precision to double
-- Setting gpu precision to single
-- Using cuda wrapper to compile....
-- Cuda version is >= 7.5 and single-precision build, enable double usage warning.
-- MPI_INCLUDE_PATH : /usr/lib/openmpi/include/openmpi/opal/mca/event/libevent2021/libevent;/usr/lib/openmpi/include/openmpi/opal/mca/event/libevent2021/libevent/include;/usr/lib/openmpi/include;/usr/lib/openmpi/include/openmpi
-- MPI_LIBRARIES : /usr/lib/openmpi/lib/libmpi_cxx.so;/usr/lib/openmpi/lib/libmpi.so
-- MPI_CXX_INCLUDE_PATH : /usr/lib/openmpi/include/openmpi/opal/mca/event/libevent2021/libevent;/usr/lib/openmpi/include/openmpi/opal/mca/event/libevent2021/libevent/include;/usr/lib/openmpi/include;/usr/lib/openmpi/include/openmpi
-- MPI_CXX_LIBRARIES : /usr/lib/openmpi/lib/libmpi_cxx.so;/usr/lib/openmpi/lib/libmpi.so
-- Could NOT find FLTK (missing:  FLTK_LIBRARIES FLTK_INCLUDE_DIR FLTK_FLUID_EXECUTABLE) 
-- FLTK was NOT found
-- -------------------------------------------------
-- ------- WILL USE LOCALLY BUILT FLTK LIBS --------
-- -------------------------------------------------
-- Found previously built external (non-system) FLTK library
-- FLTK_INCLUDE_DIR: /home/xny/relion/external/fltk/include
-- FLTK_LIBRARIES:   /home/xny/relion/external/fltk/lib/libfltk.so
-- Double-precision FFTW was NOT found
-- -------------------------------------------------
-- ------- WILL USE LOCALLY BUILT FFTW LIBS --------
-- -------------------------------------------------
-- Found previously built external (non-system) FFTW library
-- FFTW_INCLUDES:     /home/xny/relion/external/fftw/include
-- FFTW_LIBRARIES:    /home/xny/relion/external/fftw/lib/libfftw3.so
-- Building shared libs (smaller build size and binaries)
-- CMAKE_BINARY_DIR:/home/xny/relion/build
-- added helix_toolbox...
-- added star_compare...
-- added run_motioncorr...
-- added particle_sort...
-- added postprocess...
-- added run_ctffind_mpi...
-- added run_ctffind...
-- added maingui...
-- added stack_create...
-- added refine_mpi...
-- added find_tiltpairs...
-- added pipeliner...
-- added preprocess...
-- added postprocess_mpi...
-- added particle_polish...
-- added particle_symmetry_expand...
-- added run_motioncorr_mpi...
-- added autopick_mpi...
-- added preprocess_mpi...
-- added manualpick...
-- added particle_sort_mpi...
-- added particle_reposition...
-- added reconstruct...
-- added particle_polish_mpi...
-- added display...
-- added star_combine...
-- added tiltpair_plot...
-- added autopick...
-- added mask_create...
-- added refine...
-- added project...
-- added image_handler...
-- Configuring done
-- Generating done
-- Build files have been written to: /home/xny/relion/build
[  0%] Built target copy_scripts
[  1%] Building NVCC (Device) object src/apps/CMakeFiles/relion_gpu_util.dir/__/gpu_utils/relion_gpu_util_generated_cuda_projector_plan.cu.o
[  2%] Building NVCC (Device) object src/apps/CMakeFiles/relion_gpu_util.dir/__/gpu_utils/relion_gpu_util_generated_cuda_ml_optimiser.cu.o
[  2%] Building NVCC (Device) object src/apps/CMakeFiles/relion_gpu_util.dir/__/gpu_utils/relion_gpu_util_generated_cuda_helper_functions.cu.o
[  3%] Building NVCC (Device) object src/apps/CMakeFiles/relion_gpu_util.dir/__/gpu_utils/relion_gpu_util_generated_cuda_autopicker.cu.o
Scanning dependencies of target relion_gpu_util
[  3%] Linking CXX shared library ../../lib/librelion_gpu_util.so
[  7%] Built target relion_gpu_util
Scanning dependencies of target relion_lib
[  8%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/strings.cpp.o
[  9%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/particle_sorter.cpp.o
[ 10%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/euler.cpp.o
[ 10%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/matrix1d.cpp.o
[ 11%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/gui_entries.cpp.o
[ 12%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/metadata_table.cpp.o
[ 13%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/assembly.cpp.o
[ 14%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/preprocessing.cpp.o
[ 14%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/transformations.cpp.o
[ 15%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/args.cpp.o
[ 16%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/particle_sorter_mpi.cpp.o
[ 17%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/filename.cpp.o
[ 17%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/tabfuncs.cpp.o
[ 18%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/memory.cpp.o
[ 19%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/ml_optimiser.cpp.o
[ 20%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/numerical_recipes.cpp.o
[ 20%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/ctf.cpp.o
[ 21%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/autopicker_mpi.cpp.o
[ 22%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/pipeliner.cpp.o
[ 23%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/particle_polisher.cpp.o
[ 24%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/displayer.cpp.o
[ 24%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/metadata_label.cpp.o
[ 25%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/gui_mainwindow.cpp.o
[ 26%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/particle_polisher_mpi.cpp.o
[ 27%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/autopicker.cpp.o
[ 27%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/ctffind_runner_mpi.cpp.o
[ 28%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/preprocessing_mpi.cpp.o
[ 29%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/symmetries.cpp.o
[ 30%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/backprojector.cpp.o
[ 30%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/projector.cpp.o
[ 31%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/postprocessing.cpp.o
[ 32%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/mask.cpp.o
[ 33%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/ml_optimiser_mpi.cpp.o
[ 34%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/healpix_sampling.cpp.o
[ 34%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/ml_model.cpp.o
[ 35%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/fftw.cpp.o
[ 36%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/exp_model.cpp.o
[ 37%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/mpi.cpp.o
[ 37%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/funcs.cpp.o
[ 38%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/ctffind_runner.cpp.o
[ 39%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/CPlot2D.cpp.o
[ 40%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/complex.cpp.o
[ 40%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/multidim_array.cpp.o
[ 41%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/time.cpp.o
[ 42%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/error.cpp.o
[ 43%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/gui_jobwindow.cpp.o
[ 44%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/motioncorr_runner.cpp.o
[ 44%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/helix.cpp.o
[ 45%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/matrix2d.cpp.o
[ 46%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/parallel.cpp.o
[ 47%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/manualpicker.cpp.o
[ 47%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/metadata_container.cpp.o
[ 48%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/motioncorr_runner_mpi.cpp.o
[ 49%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/image.cpp.o
[ 50%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/Healpix_2.15a/healpix_base.cc.o
[ 50%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/Healpix_2.15a/cxxutils.cc.o
[ 51%] Linking CXX shared library ../../lib/librelion_lib.so
[ 51%] Built target relion_lib
Scanning dependencies of target image_handler
[ 52%] Building CXX object src/apps/CMakeFiles/image_handler.dir/image_handler.cpp.o
[ 53%] Linking CXX executable ../../bin/relion_image_handler
../../lib/librelion_gpu_util.so: undefined reference to `FileName::compose(std::string const&, long, std::string const&, int)'
../../lib/librelion_gpu_util.so: undefined reference to `FileName::addExtension(std::string const&) const'
../../lib/librelion_gpu_util.so: undefined reference to `FileName::beforeLastOf(std::string const&) const'
../../lib/librelion_gpu_util.so: undefined reference to `EMDL::label2Str(EMDLabel const&)'
../../lib/librelion_gpu_util.so: undefined reference to `floatToString(float, int, int)'
../../lib/librelion_gpu_util.so: undefined reference to `FileName::decompose(long&, std::string&) const'
../../lib/librelion_gpu_util.so: undefined reference to `FileName::contains(std::string const&) const'
../../lib/librelion_gpu_util.so: undefined reference to `MetaDataContainer::getValue(EMDLabel, std::string&)'
../../lib/librelion_gpu_util.so: undefined reference to `RelionError::RelionError(std::string const&, std::string const&, long)'
collect2: error: ld returned 1 exit status
src/apps/CMakeFiles/image_handler.dir/build.make:103: recipe for target 'bin/relion_image_handler' failed
make[2]: *** [bin/relion_image_handler] Error 1
CMakeFiles/Makefile2:189: recipe for target 'src/apps/CMakeFiles/image_handler.dir/all' failed
make[1]: *** [src/apps/CMakeFiles/image_handler.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by bforsbe** [comment]
Have a look at [this issue](https://github.com/3dem/relion/issues/195) and check your cmake version. Let me know if none of that works.

**Comment by bforsbe** [comment]
Did it work?

**Comment by biochem-fan** [comment]
No response for more than one year. Closing.
