### ISSUE TITLE
No orientation was found as better than any other.

### ISSUE THREAD

**Issue by jianSG** [3dem/relion#231]
I have been running 2D classification, and this error pop up at 
Expectation iteration 11 of 25
1.77/2.14 hrs .................................................~~(,_,">[kuda01:37675] *** Process received signal ***
[kuda01:37675] Signal: Segmentation fault (11)
[kuda01:37675] Signal code: Address not mapped (1)
[kuda01:37675] Failing at address: 0x40c
[kuda01:37675] [ 0] /lib64/libpthread.so.0(+0xf370)[0x7f163b013370]
[kuda01:37675] [ 1] /lib64/libstdc++.so.6(_ZNSsC1ERKSs+0x1b)[0x7f163b7f6f4b]
[kuda01:37675] [ 2] /apps/relion/2.0.6/lib/librelion_lib.so(_ZN11RelionErrorC2ERKS_+0x1f)[0x7f1645d72bff]
[kuda01:37675] [ 3] /apps/relion/2.0.6/lib/librelion_lib.so(_ZN11MlOptimiser24expectationSomeParticlesEll+0x12c0)[0x7f1645d5e9b0]
[kuda01:37675] [ 4] /apps/relion/2.0.6/lib/librelion_lib.so(_ZN14MlOptimiserMpi11expectationEv+0x143a)[0x7f1645d9929a]
[kuda01:37675] [ 5] /apps/relion/2.0.6/lib/librelion_lib.so(_ZN14MlOptimiserMpi7iterateEv+0x5d)[0x7f1645da178d]
[kuda01:37675] [ 6] /apps/relion/2.0.6/bin/relion_refine_mpi(main+0x69)[0x4029f9]
[kuda01:37675] [ 7] /lib64/libc.so.6(__libc_start_main+0xf5)[0x7f163ac64b35]
[kuda01:37675] [ 8] /apps/relion/2.0.6/bin/relion_refine_mpi[0x402b5f]
[kuda01:37675] *** End of error message ***
--------------------------------------------------------------------------
mpirun noticed that process rank 3 with PID 0 on node kuda01 exited on signal 11 (Segmentation fault).
--------------------------------------------------------------------------

*****************************************************
The error message as following
*****************************************************
WARNING: Exception (ERROR: 
No orientation was found as better than any other.

A particle image was compared to the reference and resulted in all-zero
weights (for all orientations). This should not happen, unless your data
has very special characteristics. This has historically happened for some 
lower-precision calculations, but multiple fallbacks have since been 
implemented. Please report this error to the relion developers at 

	         github.com/3dem/relion/issues  
 ) handled by switching to fail-safe mode.

 fn_img= 
 part_id= 414259
 ipart= 0
 op.min_diff2[ipart]= 3427.95
 group_id= 1769
 ml_model.scale_correction[group_id]= 1.11519
 exp_significant_weight[ipart]= 0
 exp_max_weight[ipart]= -1
 ml_model.sigma2_noise[group_id]= 
   0.00031
   0.00024
   0.00017
   0.00018
    0.0002
   0.00024
   0.00027
   0.00025
    0.0002
   0.00013
   7.3e-05
     7e-05
    0.0001
    0.0001
     7e-05
   5.1e-05
   6.3e-05
   6.1e-05
   4.2e-05
   4.5e-05
   4.7e-05
   3.5e-05
   3.8e-05
   3.3e-05
   2.9e-05
   2.9e-05
   2.5e-05
   2.6e-05
   2.2e-05
   2.2e-05
     2e-05
   1.9e-05
   1.8e-05
   1.7e-05
   1.6e-05
   1.5e-05
   1.4e-05
   1.3e-05
   1.2e-05
   1.1e-05
   1.1e-05
     1e-05
   9.5e-06
     9e-06
   8.5e-06
     8e-06
   7.6e-06
   7.2e-06
   6.8e-06
   6.5e-06
   6.1e-06
   5.8e-06
   5.5e-06
   5.2e-06
   4.9e-06
   4.6e-06
   4.4e-06
   4.2e-06
     4e-06
   3.8e-06
   3.6e-06
   3.5e-06
   3.3e-06
   3.2e-06
   3.2e-06
   2.9e-06
   2.6e-06
   2.6e-06
   2.5e-06
   2.4e-06
   2.3e-06
   2.2e-06
   2.1e-06
     2e-06
   1.9e-06
   1.8e-06
   1.7e-06
   1.7e-06
   1.6e-06
   1.5e-06
   1.5e-06
   1.4e-06
   1.4e-06
   1.3e-06
   1.3e-06
   1.2e-06
   1.2e-06
   1.1e-06
   1.1e-06
     1e-06
     1e-06
   9.8e-07
   9.5e-07
   9.3e-07
   8.9e-07
   8.7e-07
   8.5e-07
   8.2e-07
   7.9e-07
   7.8e-07
   7.6e-07
   7.4e-07
   7.2e-07
     7e-07
   6.9e-07
   6.6e-07
   6.6e-07
   6.4e-07
   6.3e-07
   6.1e-07
     6e-07
   5.9e-07
   5.8e-07
   5.7e-07
   5.6e-07
   5.5e-07
   5.4e-07
   5.3e-07
   5.3e-07
   5.2e-07
   5.1e-07
   5.1e-07
     5e-07
     5e-07
   4.9e-07
   4.9e-07
   4.8e-07
   4.8e-07
   4.8e-07

**Comment by dkimanius** [comment]
Please recenter your particles and try rerunning refinement. You can do this in a re-extration.
