### ISSUE TITLE
Relion 2.0.6: linking binaries problem (similar to issue #195)

### ISSUE THREAD

**Issue by chenzhao-CZ** [3dem/relion#237]
I am trying to build Relion 2.0.6 using:

cmake -DCMAKE_INSTALL_PREFIX=/usr/local/relion-2.0 -DCMAKE_C_COMPILER=/usr/bin/gcc-4.8 -DCMAKE_CXX_COMPILER=/usr/bin/g++-4.8 -DCUDA_ARCH=50 ..

And encountered the same error as in #195, which was solved by combining cuda 8.0.44, gcc 5.3.0 and openmpi 1.10.5 (or 1.10.2).

I am wondering if there is any workaround with cuda 7.5? Somehow my OS (Debian Stretch) does not work with NVIDIA drivers that are compatible with cuda 8.0.

My current openmpi version is 2.0.2.

Thank you very much for any suggestions!

**Comment by bforsbe** [comment]
Can you provide the output on the screen when you run the cmake-command?

**Comment by chenzhao-CZ** [comment]
`-- BUILD TYPE set to the default type:  'Release'
-- Using provided CUDA_ARCH=50
-- Setting cpu precision to double
-- Setting gpu precision to single
-- Using cuda wrapper to compile....
-- Cuda version is >= 7.5 and single-precision build, enable double usage warning.
-- MPI_INCLUDE_PATH : /usr/lib/x86_64-linux-gnu/openmpi/include/openmpi;/usr/lib/x86_64-linux-gnu/openmpi/include/openmpi/opal/mca/event/libevent2022/libevent;/usr/lib/x86_64-linux-gnu/openmpi/include/openmpi/opal/mca/event/libevent2022/libevent/include;/usr/lib/x86_64-linux-gnu/openmpi/include
-- MPI_LIBRARIES : /usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi_cxx.so;/usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi.so
-- MPI_CXX_INCLUDE_PATH : /usr/lib/x86_64-linux-gnu/openmpi/include/openmpi;/usr/lib/x86_64-linux-gnu/openmpi/include/openmpi/opal/mca/event/libevent2022/libevent;/usr/lib/x86_64-linux-gnu/openmpi/include/openmpi/opal/mca/event/libevent2022/libevent/include;/usr/lib/x86_64-linux-gnu/openmpi/include
-- MPI_CXX_LIBRARIES : /usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi_cxx.so;/usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi.so
-- Could NOT find FLTK (missing:  FLTK_LIBRARIES FLTK_FLUID_EXECUTABLE) 
-- FLTK was NOT found
-- -------------------------------------------------
-- ------- WILL USE LOCALLY BUILT FLTK LIBS --------
-- -------------------------------------------------
-- Found previously built external (non-system) FLTK library
-- FLTK_INCLUDE_DIR: /usr/local/src/relion/external/fltk/include
-- FLTK_LIBRARIES:   /usr/local/src/relion/external/fltk/lib/libfltk.so
-- Double-precision FFTW was NOT found
-- -------------------------------------------------
-- ------- WILL USE LOCALLY BUILT FFTW LIBS --------
-- -------------------------------------------------
-- Found previously built external (non-system) FFTW library
-- FFTW_INCLUDES:     /usr/local/src/relion/external/fftw/include
-- FFTW_LIBRARIES:    /usr/local/src/relion/external/fftw/lib/libfftw3.so
-- Building shared libs (smaller build size and binaries)
-- CMAKE_BINARY_DIR:/usr/local/src/relion/build
-- added autopick...
-- added autopick_mpi...
-- added display...
-- added find_tiltpairs...
-- added helix_toolbox...
-- added image_handler...
-- added maingui...
-- added manualpick...
-- added mask_create...
-- added particle_polish...
-- added particle_polish_mpi...
-- added particle_reposition...
-- added particle_sort...
-- added particle_sort_mpi...
-- added particle_symmetry_expand...
-- added pipeliner...
-- added postprocess...
-- added postprocess_mpi...
-- added preprocess...
-- added preprocess_mpi...
-- added project...
-- added reconstruct...
-- added refine...
-- added refine_mpi...
-- added run_ctffind...
-- added run_ctffind_mpi...
-- added run_motioncorr...
-- added run_motioncorr_mpi...
-- added stack_create...
-- added star_combine...
-- added star_compare...
-- added tiltpair_plot...
-- Configuring done
-- Generating done
-- Build files have been written to: /usr/local/src/relion/build
`
My gcc version (in PATH) is 6.3.0

**Comment by chenzhao-CZ** [comment]
And when I run make install (sorry I was not being clear before), the following errors occur:
`[  0%] Built target copy_scripts
[  1%] Building NVCC (Device) object src/apps/CMakeFiles/relion_gpu_util.dir/__/gpu_utils/cuda_kernels/relion_gpu_util_generated_helper.cu.o
[  2%] Building NVCC (Device) object src/apps/CMakeFiles/relion_gpu_util.dir/__/gpu_utils/relion_gpu_util_generated_cuda_autopicker.cu.o
[  3%] Building NVCC (Device) object src/apps/CMakeFiles/relion_gpu_util.dir/__/gpu_utils/relion_gpu_util_generated_cuda_backprojector.cu.o
[  4%] Building NVCC (Device) object src/apps/CMakeFiles/relion_gpu_util.dir/__/gpu_utils/relion_gpu_util_generated_cuda_benchmark_utils.cu.o
[  5%] Building NVCC (Device) object src/apps/CMakeFiles/relion_gpu_util.dir/__/gpu_utils/relion_gpu_util_generated_cuda_helper_functions.cu.o
[  5%] Building NVCC (Device) object src/apps/CMakeFiles/relion_gpu_util.dir/__/gpu_utils/relion_gpu_util_generated_cuda_ml_optimiser.cu.o
[  6%] Building NVCC (Device) object src/apps/CMakeFiles/relion_gpu_util.dir/__/gpu_utils/relion_gpu_util_generated_cuda_projector.cu.o
[  7%] Building NVCC (Device) object src/apps/CMakeFiles/relion_gpu_util.dir/__/gpu_utils/relion_gpu_util_generated_cuda_projector_plan.cu.o
[  7%] Linking CXX shared library ../../lib/librelion_gpu_util.so
[  7%] Built target relion_gpu_util
Scanning dependencies of target relion_lib
[  8%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/CPlot2D.cpp.o
[  9%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/args.cpp.o
[ 10%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/assembly.cpp.o
[ 10%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/autopicker.cpp.o
[ 11%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/autopicker_mpi.cpp.o
[ 12%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/backprojector.cpp.o
[ 13%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/complex.cpp.o
[ 14%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/ctf.cpp.o
[ 14%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/ctffind_runner.cpp.o
[ 15%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/ctffind_runner_mpi.cpp.o
[ 16%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/displayer.cpp.o
[ 17%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/error.cpp.o
[ 17%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/euler.cpp.o
[ 18%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/exp_model.cpp.o
[ 19%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/fftw.cpp.o
[ 20%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/filename.cpp.o
[ 20%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/funcs.cpp.o
[ 21%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/gui_entries.cpp.o
[ 22%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/gui_jobwindow.cpp.o
[ 23%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/gui_mainwindow.cpp.o
[ 24%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/healpix_sampling.cpp.o
[ 24%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/helix.cpp.o
[ 25%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/image.cpp.o
[ 26%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/manualpicker.cpp.o
[ 27%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/mask.cpp.o
[ 27%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/matrix1d.cpp.o
[ 28%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/matrix2d.cpp.o
[ 29%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/memory.cpp.o
[ 30%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/metadata_container.cpp.o
[ 30%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/metadata_label.cpp.o
[ 31%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/metadata_table.cpp.o
[ 32%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/ml_model.cpp.o
[ 33%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/ml_optimiser.cpp.o
[ 34%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/ml_optimiser_mpi.cpp.o
[ 34%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/motioncorr_runner.cpp.o
[ 35%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/motioncorr_runner_mpi.cpp.o
[ 36%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/mpi.cpp.o
[ 37%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/multidim_array.cpp.o
[ 37%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/numerical_recipes.cpp.o
[ 38%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/parallel.cpp.o
[ 39%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/particle_polisher.cpp.o
[ 40%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/particle_polisher_mpi.cpp.o
[ 40%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/particle_sorter.cpp.o
[ 41%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/particle_sorter_mpi.cpp.o
[ 42%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/pipeliner.cpp.o
[ 43%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/postprocessing.cpp.o
[ 44%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/preprocessing.cpp.o
[ 44%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/preprocessing_mpi.cpp.o
[ 45%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/projector.cpp.o
[ 46%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/strings.cpp.o
[ 47%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/symmetries.cpp.o
[ 47%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/tabfuncs.cpp.o
[ 48%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/time.cpp.o
[ 49%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/transformations.cpp.o
[ 50%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/Healpix_2.15a/cxxutils.cc.o
[ 50%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/Healpix_2.15a/healpix_base.cc.o
[ 51%] Linking CXX shared library ../../lib/librelion_lib.so
[ 51%] Built target relion_lib
Scanning dependencies of target star_compare
[ 52%] Building CXX object src/apps/CMakeFiles/star_compare.dir/star_compare.cpp.o
[ 53%] Linking CXX executable ../../bin/relion_star_compare
../../lib/librelion_gpu_util.so: undefined reference to `FileName::compose(std::string const&, long, std::string const&, int)'
../../lib/librelion_gpu_util.so: undefined reference to `FileName::addExtension(std::string const&) const'
../../lib/librelion_gpu_util.so: undefined reference to `FileName::beforeLastOf(std::string const&) const'
../../lib/librelion_gpu_util.so: undefined reference to `EMDL::label2Str(EMDLabel const&)'
../../lib/librelion_gpu_util.so: undefined reference to `floatToString(float, int, int)'
../../lib/librelion_gpu_util.so: undefined reference to `FileName::decompose(long&, std::string&) const'
../../lib/librelion_gpu_util.so: undefined reference to `FileName::contains(std::string const&) const'
../../lib/librelion_gpu_util.so: undefined reference to `MetaDataContainer::getValue(EMDLabel, std::string&)'
../../lib/librelion_gpu_util.so: undefined reference to `RelionError::RelionError(std::string const&, std::string const&, long)'
collect2: error: ld returned 1 exit status
src/apps/CMakeFiles/star_compare.dir/build.make:103: recipe for target 'bin/relion_star_compare' failed
make[2]: *** [bin/relion_star_compare] Error 1
CMakeFiles/Makefile2:189: recipe for target 'src/apps/CMakeFiles/star_compare.dir/all' failed
make[1]: *** [src/apps/CMakeFiles/star_compare.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
`

**Comment by david-barker** [comment]
Hi @chenzhao-CZ - I was having similar problem; GCC-4.9.3 worked for me though. CUDA 7.5 was OK for me.

**Comment by chenzhao-CZ** [comment]
Sorry for not responding as I was traveling in the last few weeks.

I spent some time to replace the default compiler to GCC-4.8.5, which is confirmed by "gcc -v". Then when I ran "make -j 8", I saw the following errors:
...
[ 56%] Linking CXX executable ../../bin/relion_run_ctffind_mpi
[ 57%] Linking CXX executable ../../bin/relion_star_compare
/usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi_cxx.so: undefined reference to `operator delete(void*, unsigned long)@CXXABI_1.3.9'
collect2: error: ld returned 1 exit status
src/apps/CMakeFiles/stack_create.dir/build.make:103: recipe for target 'bin/relion_stack_create' failed
make[2]: *** [bin/relion_stack_create] Error 1
CMakeFiles/Makefile2:227: recipe for target 'src/apps/CMakeFiles/stack_create.dir/all' failed
make[1]: *** [src/apps/CMakeFiles/stack_create.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
/usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi_cxx.so: undefined reference to `operator delete(void*, unsigned long)@CXXABI_1.3.9'
collect2: error: ld returned 1 exit status
/usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi_cxx.so: undefined reference to `operator delete(void*, unsigned long)@CXXABI_1.3.9'
collect2: error: ld returned 1 exit status
src/apps/CMakeFiles/run_ctffind.dir/build.make:103: recipe for target 'bin/relion_run_ctffind' failed
make[2]: *** [bin/relion_run_ctffind] Error 1
CMakeFiles/Makefile2:341: recipe for target 'src/apps/CMakeFiles/run_ctffind.dir/all' failed
make[1]: *** [src/apps/CMakeFiles/run_ctffind.dir/all] Error 2
src/apps/CMakeFiles/star_compare.dir/build.make:103: recipe for target 'bin/relion_star_compare' failed
make[2]: *** [bin/relion_star_compare] Error 1
CMakeFiles/Makefile2:189: recipe for target 'src/apps/CMakeFiles/star_compare.dir/all' failed
make[1]: *** [src/apps/CMakeFiles/star_compare.dir/all] Error 2
/usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi_cxx.so: undefined reference to `operator delete(void*, unsigned long)@CXXABI_1.3.9'
collect2: error: ld returned 1 exit status
src/apps/CMakeFiles/refine.dir/build.make:103: recipe for target 'bin/relion_refine' failed
make[2]: *** [bin/relion_refine] Error 1
CMakeFiles/Makefile2:417: recipe for target 'src/apps/CMakeFiles/refine.dir/all' failed
make[1]: *** [src/apps/CMakeFiles/refine.dir/all] Error 2
/usr/lib/x86_64/-linux-usrgnu//libopenmpi//x86_64lib-/linuxlibmpi_cxx.so-:gnu /undefinedopenmpi /referencelib /tolibmpi_cxx.so :` operatorundefined  deletereference( voidto* ,` operatorunsigned  deletelong()void@*CXXABI_1.3.9,' 
unsigned long)@CXXABI_1.3.9'
collect2: error: ld returned 1 exit status
collect2: error: ld returned 1 exit status
/usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi_cxx.so: undefined reference to `operator delete(void*, unsigned long)@CXXABI_1.3.9'
collect2: error: ld returned 1 exit status
src/apps/CMakeFiles/project.dir/build.make:103: recipe for target 'bin/relion_project' failed
make[2]: *** [bin/relion_project] Error 1
CMakeFiles/Makefile2:455: recipe for target 'src/apps/CMakeFiles/project.dir/all' failed
make[1]: *** [src/apps/CMakeFiles/project.dir/all] Error 2
src/apps/CMakeFiles/run_ctffind_mpi.dir/build.make:103: recipe for target 'bin/relion_run_ctffind_mpi' failed
src/apps/CMakeFiles/refine_mpi.dir/build.make:103: recipe for target 'bin/relion_refine_mpi' failed
make[2]: *** [bin/relion_run_ctffind_mpi] Error 1
make[2]: *** [bin/relion_refine_mpi] Error 1
CMakeFiles/Makefile2:379: recipe for target 'src/apps/CMakeFiles/refine_mpi.dir/all' failed
make[1]: *** [src/apps/CMakeFiles/refine_mpi.dir/all] Error 2
CMakeFiles/Makefile2:303: recipe for target 'src/apps/CMakeFiles/run_ctffind_mpi.dir/all' failed
make[1]: *** [src/apps/CMakeFiles/run_ctffind_mpi.dir/all] Error 2
/usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi_cxx.so: undefined reference to `operator delete(void*, unsigned long)@CXXABI_1.3.9'
collect2: error: ld returned 1 exit status
src/apps/CMakeFiles/run_motioncorr.dir/build.make:103: recipe for target 'bin/relion_run_motioncorr' failed
make[2]: *** [bin/relion_run_motioncorr] Error 1
CMakeFiles/Makefile2:265: recipe for target 'src/apps/CMakeFiles/run_motioncorr.dir/all' failed
make[1]: *** [src/apps/CMakeFiles/run_motioncorr.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

Based on google search, I tried to solve this problem by adding '/usr/local/lib64' into LD_LIBRARY_PATH. In /usr/local/lib64, I have linked libstdc++.so.6 to libstdc++.so.6.21, which includes CXXABI_1.3.9. But this did not work. I am not a developer so I do not understand very much how this is supposed to work. Does anyone have any ideas?

**Comment by chenzhao-CZ** [comment]
Update: openmpi-1.10.2 solved the problem above but I have another similar problems with fltk. I am trying things out and hopefully it will work out.

**Comment by chenzhao-CZ** [comment]
Finally I have solved this problem by including -DCMAKE_EXE_LINKER_FLAGS='-static-libstdc++' argument when I ran cmake. The libstdc++.so.6 is pointed to libstdc++.so.6.0.21.

Thank you very much for everyone's help!
