### ISSUE TITLE
--locres saving maps with wrong pixel size

### ISSUE THREAD

**Issue by rdrighetto** [3dem/relion#239]
On version 2.0.6, I noticed that using the --locres option will generate output maps (_locres.mrc and _locres_filtered.mrc) with the same pixel size as in the header of the input half-maps, ignoring what is specified via the --angpix option.

The local-resolution FSCs, however, are evaluated with the correct value from --angpix.

**Comment by biochem-fan** [comment]
The above patch should fix the problem.
