### ISSUE TITLE
2.1-beta-0 fails to process benchmark data: No orientation was found as better than any other

### ISSUE THREAD

**Issue by mokca** [3dem/relion#242]
I've installed 2.1-beta-0 and, as I usually do, was testing it with the benchmark data.  It fails to complete the 2D classification successfully: there are several hundred of the "No orientation was found as better than any other" errors before it finally dies with "terminate called after throwing an instance of 'std::bad_alloc'".

I've attached an abridged file with the errors.

I'm assuming that this is a compilation issue as other people haven't reported problems with 2.1-beta-0.

Compiled on Ubuntu 16.04.2 LTS using gcc 5.4.0, openmpi 2.0.1, CUDA 8.0.  Compiled with CUDA ARCH 52.  Running on i7-6900K, 4 x 1080 Ti.

To compile, I edited src/macros.h to change MY_MPI_COMPLEX to MPI_C_DOUBLE_COMPLEX, as this still gives issues with Ubuntu 16.04.2.

The 2D classification was run using:

`mpirun -n 5 which relion_refine_mpi --j 2 --i Particles/shiny_2sets.star --ctf --iter 25 --tau2_fudge 2 --particle_diameter 360 --K 200 --zero_mask --oversampling 1 --psi_step 6 --offset_range 5 --offset_step 2 --norm --scale --random_seed 0 --o class2d --gpu`

Any idea what is causing this?  Version 2.0.6 compiled in an identical way on this machine runs the benchmarks without issues.

Attached error file: 

[2.1-beta-0-errors.txt](https://github.com/3dem/relion/files/1087905/2.1-beta-0-errors.txt)

**Comment by bforsbe** [comment]
I don't think that is the issue, but to rule it out, could you try downgrading gcc to a version which is [officially supported](http://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html#axzz4kclLu31Z) by cuda 8.0?

**Comment by mokca** [comment]
I've recompiled both openmpi and Relion with gcc-4.9 (which is easier to retrofit to Ubuntu 16.04 than gcc 5.3).  I've tested it a couple of times and I get the similar errors - lots of "No orientation was found..." before crashing.

As other people seem to have 2.1-beta-0 working without problems on Ubuntu 16.04, I'm concerned that some other feature of our build might be breaking things.  I'll try a clean install of Ubuntu with just Relion and no other software and see if that works.

**Comment by jmansour** [comment]
I'm also encountering this issue when running the standard 2d class bench on 2.1beta. Version 2.06 runs without issue. 

Details:
relion 4c37af0cb135286a63f7fe5c4b21f26f5d5277e9
Centos 7
gcc 4.9.3
openmpi 1.10.3
cuda 8.0.61

Command line:
```bash
mpirun elion_refine_mpi --i Particles/shiny_2sets.star --ctf --iter 25 --tau2_fudge 2 --particle_diameter 360 --K 200 --zero_mask --oversampling 1 --psi_step 6 --offset_range 5 --offset_step 2 --norm --scale --random_seed 0 --o class2d --gpu --pool 100 --dont_combine_weights_via_disc --j 1
```

[output.txt](https://github.com/3dem/relion/files/1224067/output.txt)

**Comment by jmansour** [comment]
So running against the latest revision e7607a869687b636d3c39e0d5b6a9cba930fc3b2 I no longer  encounter this message. Were the latest changes expected to resolve this issue?

**Comment by mokca** [comment]
I'm still having this problem.  I've tried on fresh installations of Ubuntu 16.04, Linux Mint 18.1, and CentOS 7.  I've tried the default openmpi (usually 1.10) and separately installed v2.1.2.  I've also tried downgrading to gcc-4.9.

The class2d benchmark gets to around iteration 6 and fails with multiple "No orientation was found as better than any other." errors.

**Comment by jmansour** [comment]
Yep, I'm also still encountering failure at iteration 6. I assume the devs cannot reproduce this at their end? 

relion e7607a8
gcc 5.4
openmpi 1.10.2
cuda V9.0.176

**Comment by bforsbe** [comment]
I will investigate this tomorrow, I suspect its some old/new combinations of software we need to support better. Will report back tomorrow. Thanks guys, for reporting, and apologies for the delays in fixing!

**Comment by jmansour** [comment]
Just backtracking through commits, and the issue first appears at 005eac43a0a12b7e6450fd9acb92292b6a29f12a (ie v.2.1-beta-0).

**Comment by Guilz** [comment]
Hello there,

I just ran into this issue with relion-2.1-beta-1 on one of my datasets. It happened at iteration 11 of a class2D job for all ~300,000 autopicked particles. The job.err file reports 287 occurences of the `No orientation was found as better than any other.` error message.

Now, this message probably makes sense in my case, because examination of the particles revealed that the autopicking job picked up a lot of junk (I had ripples in some micrographs that got autopicked: I suppose they should not align easily to anything and are a possible cause of this error).

I will try to screen out obvious junk particles and rerun this job.

The error message specifically asked to report it here, so I wanted to let you know.

**Comment by jmansour** [comment]
Any further updates on this issue? 

If you need an environment to reproduce it, the Nvidia Relion docker (nvcr.io/hpc/relion:2.1.b1) is an option.

**Comment by mokca** [comment]
I've just tested the recent release of 2.1.0, and this is still happening at iteration 6 with the 2D benchmark data.

This is on Ubuntu 17.0.4 LTS, CUDA 8, OpenMPI 2.0.1, gcc 5.4.0, relion installation builds own FFTW and FLTK.

**Comment by mokca** [comment]
Whoops, I didn't mean to close that issue.  Apologies.

**Comment by biochem-fan** [comment]
Old version.
