### ISSUE TITLE
Very long iteration times for 2D Classification on multiple GPU nodes

### ISSUE THREAD

**Issue by ninthpower** [3dem/relion#243]
We've been struggling to get Relion to work properly on our K80 GPU nodes. Oddly, the same job (~600K particles, 240 GB) runs much faster on a local GPU workstation with older cards (K40s). Our issue may be related to issue [https://github.com/3dem/relion/issues/209](#209) or [https://github.com/3dem/relion/issues/222](#222), but we've still not found a proper solution.

We have run all kinds of commands but most have been similar to (Using 5+ MPI Processes):
`which relion_refine_mpi --o Class2D/job061/run --i ./Extract/job060/particles.star --dont_combine_weights_via_disc  --pool 30 --ctf  --ctf_phase_flipped  --iter 25 --tau2_fudge 2 --particle_diameter -1 --K 100 --flatten_solvent  --zero_mask  --oversampling 1 --psi_step 12 --offset_range 5 --offset_step 2 --norm --scale  --j 1 --gpu ""`

Observations From Different Set-ups:
- A) Running on the local, two-card (K40s) workstation gives iteration times of 1=53 min, 2=15hrs, 3=30hrs.
- B) Running an identical job on a single two-card (K80s) GPU node gives very long iteration times of >100hrs.
- C) Running a job with 1 MPI and 30 threads on a single two-card GPU node (same as B) gives more manageable iteration times, but still longer than we'd expected: 1=1.6hrs, 2=12hrs, 3=12hrs.
- D) (MAIN CONCERN) Running a job with multiple MPIs (9-13) and one thread across multiple K80 GPU nodes causes long iteration times similar to the B) approach.
- E) Running a relion_refine_mpi on 196 CPUs (1 MPI per CPU) over 7 nodes runs faster than them all.

Misc. Observations:
- there is a hours-long pause between noise spectra and 1st iteration on B) and D). I assume this has to do with harddrive/memory allocation, but not sure?
- greater pooling does not significantly improve anything.

The MPI processes in all of the GPU runs appear to be assigned correctly, but the GPUs don't appear to be working very hard on them for B or D:

B) during iteration 1 (D is identical):
```
$ nvidia-smi
Tue Jun 20 11:39:21 2017       
+------------------------------------------------------+                       
| NVIDIA-SMI 352.39     Driver Version: 352.39         |                       
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla K80           On   | 0000:05:00.0     Off |                    0 |
| N/A   50C    P0    55W / 149W |  11365MiB / 11519MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla K80           On   | 0000:06:00.0     Off |                    0 |
| N/A   36C    P0    69W / 149W |  11365MiB / 11519MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  Tesla K80           On   | 0000:84:00.0     Off |                    0 |
| N/A   53C    P0    57W / 149W |  11364MiB / 11519MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   3  Tesla K80           On   | 0000:85:00.0     Off |                    0 |
| N/A   41C    P0    71W / 149W |  11365MiB / 11519MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    0    126762    C   .../relion/2.0.4_cu7.5/bin/relion_refine_mpi 11340MiB |
|    1    126763    C   .../relion/2.0.4_cu7.5/bin/relion_refine_mpi 11340MiB |
|    2    126764    C   .../relion/2.0.4_cu7.5/bin/relion_refine_mpi 11339MiB |
|    3    126765    C   .../relion/2.0.4_cu7.5/bin/relion_refine_mpi 11340MiB |
+-----------------------------------------------------------------------------+
```
We don't have output from any other iterations because we cancel the job long before the first iteration completes.

C) during current iteration (9):
```
$ nvidia-smi
Tue Jun 20 12:01:29 2017       
+------------------------------------------------------+                       
| NVIDIA-SMI 352.39     Driver Version: 352.39         |                       
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla K80           On   | 0000:05:00.0     Off |                    0 |
| N/A   50C    P0    68W / 149W |  10224MiB / 11519MiB |     33%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla K80           On   | 0000:06:00.0     Off |                    0 |
| N/A   38C    P0    76W / 149W |  10224MiB / 11519MiB |     16%      Default |
+-------------------------------+----------------------+----------------------+
|   2  Tesla K80           On   | 0000:84:00.0     Off |                    0 |
| N/A   54C    P0    72W / 149W |  10224MiB / 11519MiB |     36%      Default |
+-------------------------------+----------------------+----------------------+
|   3  Tesla K80           On   | 0000:85:00.0     Off |                    0 |
| N/A   43C    P0    84W / 149W |  10224MiB / 11519MiB |     11%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    0    122677    C   ...inux/relion/2.0.4_cu7.5/bin/relion_refine 10198MiB |
|    1    122677    C   ...inux/relion/2.0.4_cu7.5/bin/relion_refine 10198MiB |
|    2    122677    C   ...inux/relion/2.0.4_cu7.5/bin/relion_refine 10198MiB |
|    3    122677    C   ...inux/relion/2.0.4_cu7.5/bin/relion_refine 10198MiB |
+-----------------------------------------------------------------------------+
```

**Comment by bforsbe** [comment]
What box-size are you using, and at what pixel-size?

**Comment by ninthpower** [comment]
We're using a 250 box-size, 1.3 apix.

**Comment by bforsbe** [comment]
2D classes are useful, but at much lower resolutions than what you have capacity for at such a small pixel size. I would advise that you re-extract your particles with re-scaling to 100 pixels or so, which will give you a maximum resolution of 6.5Å, which is plenty. If you then add the flags;

```
--subset_frac 0.05 --subset_iter 5 --maxsig 20
```   

And things should be flying a bit faster. In general I think you might be having i/o speed limits, and re-scaling will help with that. But in addition, putting 600k particles through the initial phases of 2D classification (especially at 1.3Å/pix) is wasted cycles. Using 2.0.4, these flags will work to make it go through fewer unnecessary cycles.

**Comment by ninthpower** [comment]
Thanks, I figured there are some definite i/o problems with the very long pause before the 1st orientation. I know that I've tried --maxsig before without seeing a significant speed up, but it was something like 500.

We'll try out these ideas and get back to you.

**Comment by ninthpower** [comment]
I know this is an old thread now, but we were able to try these parameters on a similar set of data with >500K particles and there was a considerable speed-up. I don't have actual numbers but I would say at least 2-fold speed-up.

After other testing there is also clear I/O problems. We've attempted to overcome those with reading into memory where we can and using a scratch directory.
