### ISSUE TITLE
relion_mask_create does not give helptext, does not run with parameters from 2.06

### ISSUE THREAD

**Issue by olibclarke** [3dem/relion#244]
Hi,

Running `relion_mask_create` with or without --h or --help parameters fails to give info as to input flags - it just gives an error, "Either provide --i to apply a mask, OR --create_from to create a new mask", which seems a different syntax from relion_mask_create in previous forms of relion.

Running previous successful relion_mask_create commands, replacing --i with --create_from, gives the same error.

Cheers
Oli

**Comment by olibclarke** [comment]
Never mind, I'm an idiot, it is just the errror message which is erroneous - `--i` is still for the input map, and I don't know what `--create_from` is for but it is not present in a command printed from the GUI. Helptext is still missing though.

**Comment by bforsbe** [comment]
When we made -h/--help/<no flags> the systematic way to show all options, there was an additional if()-clause specific to mask_create, which we did not notice. The next version will work as expected. 

Thanks!
