### ISSUE TITLE
Unable to extract particles in 2.1-beta

### ISSUE THREAD

**Issue by rtnolte** [3dem/relion#245]
Since upgrading to the latest beta a few days ago, we are no longer able to extract any particles.  This is true for both new projects and trying to rerun jobs in existing project directories.  The following error occurs

ERROR: 
PipeLine::addNode ERROR: Adding an empty nodename. Did you fill in all Node names correctly?
File: /apps/relion/distfiles/relion/src/pipeliner.cpp line: 30

Has anyone else seen this.

**Comment by biochem-fan** [comment]
Not relevant for 3.0.
