### ISSUE TITLE
WARNING: Exception (ERROR:  No orientation was found as better than any other.

### ISSUE THREAD

**Issue by dieter-erich** [3dem/relion#246]
[run.pdf](https://github.com/3dem/relion/files/1100466/run.pdf)

Hi, 
So far I run Class2D on relion-2.1-beta-0 a number of times without any problem. The issue occurred at iteration 22 on the same data set of raw frame stacks as above but with different frames summed with Shawn Zheng's MOTIONCOR2 (instead of dosefgpu_driftcorr). Otherwise I cannot see any obvious difference except from that other particles might have been picked. The full error message is attached (run.err converted to run.pdf see on top).
First line:
-----------------------------------------------
 WARNING: Exception (ERROR: 
No orientation was found as better than any other.

A particle image was compared to the reference and resulted in all-zero
weights (for all orientations). This should not happen, unless your data
has very special characteristics. This has historically happened for some 
lower-precision calculations, but multiple fallbacks have since been 
implemented. Please report this error to the relion developers at 

	         github.com/3dem/relion/issues  
 ) handled by switching to fail-safe mode.

thanks, regards, Dieter

**Comment by biochem-fan** [comment]
See FAQ.
