### ISSUE TITLE
substandard performance on P100s

### ISSUE THREAD

**Issue by craigyk** [3dem/relion#248]
I've been testing the Relion 2.1 beta on some P100s and am seeing slower than expected performance running the 3D classification benchmark.  For comparison, my quad-1080 workstation finishes the 3D classification benchmark in 1 hr 46 min.  On a quad-P100 machine I'm seeing 3hr 40min.  The power use of the cards stays very low <60W which is consistent with the lower performance (the 1080 machine sees 190W+ per GPU).  I checked to see wether there is a double-precision difference, and the benchmark performance on the P100s stays about the same but the power use does go up to ~85W.  I am using GCC 4.8.5, CUDA 8.0.61, OpenMPI 1.10.3

**Comment by bforsbe** [comment]
Low power consumption means your cards are not clocking up. You can verify this by running

```nvidia-smi dmon```

on the same machine during the run. This will show you both memory- and processing-clock frequencies. Are you using GP100 (Quadro), or P100 (Tesla), and is this a workstation or is the machine in a server-room somewhere?

**Comment by craigyk** [comment]
They are Tesla P100s PCIe.  They are sitting in a dual-socket Xeon server (the 1U supermicro chassis).  They are also hitting their max clocks 1328 GPU, 715 RAM while running, so I am not sure what is going on, the load utilization on them seems to oscillate a lot more 
than I'd expect.

    0    78    38    42     1     0     0   715  1328
    1    35    31     0     0     0     0   715  1328
    2    36    34     0     0     0     0   715  1328
    3    89    35    44     1     0     0   715  1328

**Comment by bforsbe** [comment]
Is there any difference in the available RAM on the separate machines? It's that, or disk i/o, that comes to mind if your cards are behaving, which is what I would expect from Tesla cards.

**Comment by craigyk** [comment]
The machine with the P100s has 512GB of RAM.  The one with the 1080s has 128GB.  I also suspect it might be IO related, the processes under strace seem to call and wait on mmap a lot.  I'd try to load all the data into RAM to account for IO problems, but the 2.1 beta has been crashing on me when using this option.

**Comment by craigyk** [comment]
Hmmm, just tested with the scratch dir, and it did not seem to improve things.  So it is probably not related to weird behavior in Lustre.  Still seems very strange that the GPUs are all in P0 mode, clocks are at or close to max, but there is seldomly more than one with high utilization or using more than 80W out of a power limit of 250W.

**Comment by bforsbe** [comment]
Could you show the complete command you are using? Preferably the one from the original issue, to keep things clear.

**Comment by craigyk** [comment]
time srun --mem 400G -p gpu --gres gpu:4 -u -n 3 -c 4 relion_refine_mpi --i Particles/shiny_2sets.star --ref emd_2660.map:mrc --firstiter_cc --ini_high 60 --ctf --ctf_corrected_ref --iter 25 --tau2_fudge 4 --particle_diameter 360 --K 6 --flatten_solvent --zero_mask --oversampling 1 --healpix_order 2 --offset_range 5 --offset_step 2 --sym C1 --norm --scale --random_seed 0 --o class3d/a --pool 100 --dont_combine_weights_via_disc --j 4 --gpu

**Comment by bforsbe** [comment]
If it's on a single machine, you could try to run the non-MPI version to rule out strange MPI-syncs or so:

```
time srun 
--mem 400G -p gpu --gres gpu:4 -u -n 1 -c 16 
relion_refine 
--i Particles/shiny_2sets.star --ref emd_2660.map:mrc 
--firstiter_cc --ini_high 60 --ctf --ctf_corrected_ref --iter 25 --tau2_fudge 4 
--particle_diameter 360 --K 6 --flatten_solvent --zero_mask --oversampling 1 
--healpix_order 2 --offset_range 5 --offset_step 2 --sym C1 --norm --scale 
--random_seed 0 --o class3d/a --pool 100 --dont_combine_weights_via_disc --j 16 --gpu
```

OpenMPI 1.10.3 if fairly old, in some cases we've needed >2.0 to make everything work.

**Comment by craigyk** [comment]
I'll try that and report back.  I had originally tried compiling Relion 2.1 against my OpenMPI 2.1.2 install, but that was having random crashes that seemed to go away when returning to the system installed 1.10.3 version.

**Comment by craigyk** [comment]
Non-MPI does not seem any faster during the expectation steps.  What I do see now is the GPU utilization for all the GPUs are synchronized and fall and rise together whereas before, as separate processes, they would become unsynchronized.   

It is also easier to observe now that when the GPU utilization falls to 0, the CPU utilization goes to 100% which likely means the blocking code is running in a single thread.  Running an strace while this happening shows a lot of system calls to mmap, munmap, seek, and read. FWIW, mmap and seeks are notorious for sometimes causing lustre to run a lot more slowly.  I can try to test this by trying the preread_images option again.

Strace while the process is above 100% utilization (and the GPUs are busy) shows no system calls, so it is spending all its time in userland code.

Also, even when the GPU utilization is up, the GPUs still report using < 90W of power.

**Comment by craigyk** [comment]
Yes, still getting a segfault when trying to do a preread, so there is probably some kind of out-of-bounds access going on?

**Comment by bforsbe** [comment]
When you run **with** MPI, each MPI is decoupled from the others. When you now run **without** MPI, particles are processed on the GPU in synchronized batches. 

Thus, if you run **without** MPI and then observe that nothing is running on any GPU for some period of time, then you are being held up by the CPU, i/o, or some scheduling lag. My guess is still i/o. If you just cut down the input file to ~1000 particles, and run non-MPI without any preread or scratch, does the 2nd & 3rd iter still move slow? For 1000 particles i would advise --pool 20, to make sure the granularity of batches is not too big, given 4 GPUs.

**Comment by craigyk** [comment]
Sorry I have not responded in a while.  I retried with a smaller subset ~2000 particles without MPI.  Still about the same.

Here is the 4xGTX1080 machine:
`yoshiokc@elblanco $ relion_refine --i small.star --ref emd_2660.map:mrc --firstiter_cc --ini_high 60 --ctf --ctf_corrected_ref --iter 25 --tau2_fudge 4 --particle_diameter 360 --K 6 --flatten_solvent --zero_mask --oversampling 1 --healpix_order 2 --offset_range 5 --offset_step 2 --sym C1 --norm --scale --random_seed 0 --o class3d/a --pool 20 --dont_combine_weights_via_disc --j 12 --gpu
gpu-ids not specified, threads will automatically be mapped to devices (incrementally).
 Thread 0 mapped to device 0
 Thread 1 mapped to device 0
 Thread 2 mapped to device 0
 Thread 3 mapped to device 1
 Thread 4 mapped to device 1
 Thread 5 mapped to device 1
 Thread 6 mapped to device 2
 Thread 7 mapped to device 2
 Thread 8 mapped to device 2
 Thread 9 mapped to device 3
 Thread 10 mapped to device 3
 Thread 11 mapped to device 3
 Running CPU instructions in double precision. 
 Estimating initial noise spectra 
   9/   9 sec ............................................................~~(,_,">
 CurrentResolution= 60.2998 Angstroms, which requires orientationSampling of at least 18.9474 degrees for a particle of diameter 360 Angstroms
 Oversampling= 0 NrHiddenVariableSamplingPoints= 580608
 OrientationalSampling= 15 NrOrientations= 4608
 TranslationalSampling= 2 NrTranslations= 21
=============================
 Oversampling= 1 NrHiddenVariableSamplingPoints= 18579456
 OrientationalSampling= 7.5 NrOrientations= 36864
 TranslationalSampling= 1 NrTranslations= 84
=============================
 Expectation iteration 1 of 25
   6/   6 sec ............................................................~~(,_,">
 Maximization ...
1.33/1.33 min ............................................................~~(,_,">
 Estimating accuracies in the orientational assignment ... 
   3/   3 sec ............................................................~~(,_,">
 Auto-refine: Estimated accuracy angles= 8.62 degrees; offsets= 6.71 pixels
 CurrentResolution= 60.2998 Angstroms, which requires orientationSampling of at least 18.9474 degrees for a particle of diameter 360 Angstroms
 Oversampling= 0 NrHiddenVariableSamplingPoints= 580608
 OrientationalSampling= 15 NrOrientations= 4608
 TranslationalSampling= 2 NrTranslations= 21
=============================
 Oversampling= 1 NrHiddenVariableSamplingPoints= 18579456
 OrientationalSampling= 7.5 NrOrientations= 36864
 TranslationalSampling= 1 NrTranslations= 84
=============================
 Expectation iteration 2 of 25
   3/   3 sec ............................................................~~(,_,">
 Maximization ...
1.23/1.23 min ............................................................~~(,_,">
 Estimating accuracies in the orientational assignment ... 
   3/   3 sec ............................................................~~(,_,">
 Auto-refine: Estimated accuracy angles= 6.3 degrees; offsets= 5.125 pixels
 CurrentResolution= 60.2998 Angstroms, which requires orientationSampling of at least 18.9474 degrees for a particle of diameter 360 Angstroms
 Oversampling= 0 NrHiddenVariableSamplingPoints= 580608
 OrientationalSampling= 15 NrOrientations= 4608
 TranslationalSampling= 2 NrTranslations= 21
=============================
 Oversampling= 1 NrHiddenVariableSamplingPoints= 18579456
 OrientationalSampling= 7.5 NrOrientations= 36864
 TranslationalSampling= 1 NrTranslations= 84
=============================
 Expectation iteration 3 of 25
   3/   3 sec ............................................................~~(,_,">
 Maximization ...
1.18/1.18 min ............................................................~~(,_,">
 Estimating accuracies in the orientational assignment ... 
   3/   3 sec ............................................................~~(,_,">
`

here is the 4xP100 machine:
`yoshiokc@exahead1 /h/e/l/u/y/r/benchmark ❯❯❯ time srun -p gpu --gres gpu:4 --exclusive -n1 -c 12 relion_refine --i small.star --ref emd_2660.map:mrc --firstiter_cc -
-ini_high 60 --ctf --ctf_corrected_ref --iter 25 --tau2_fudge 4 --particle_diameter 360 --K 6 --flatten_solvent --zero_mask --oversampling 1 --healpix_order 2 --offs
et_range 5 --offset_step 2 --sym C1 --norm --scale --random_seed 0 --o class3d/a --pool 20 --dont_combine_weights_via_disc --j 12 --gpu
gpu-ids not specified, threads will automatically be mapped to devices (incrementally).
 Thread 0 mapped to device 0
 Thread 1 mapped to device 0
 Thread 2 mapped to device 0
 Thread 3 mapped to device 1
 Thread 4 mapped to device 1
 Thread 5 mapped to device 1
 Thread 6 mapped to device 2
 Thread 7 mapped to device 2
 Thread 8 mapped to device 2
 Thread 9 mapped to device 3
 Thread 10 mapped to device 3
 Thread 11 mapped to device 3
 Running CPU instructions in double precision. 
 Estimating initial noise spectra 
  13/  13 sec ............................................................~~(,_,">
 CurrentResolution= 60.2998 Angstroms, which requires orientationSampling of at least 18.9474 degrees for a particle of diameter 360 Angstroms
 Oversampling= 0 NrHiddenVariableSamplingPoints= 580608
 OrientationalSampling= 15 NrOrientations= 4608
 TranslationalSampling= 2 NrTranslations= 21
=============================
 Oversampling= 1 NrHiddenVariableSamplingPoints= 18579456
 OrientationalSampling= 7.5 NrOrientations= 36864
 TranslationalSampling= 1 NrTranslations= 84
=============================
 Expectation iteration 1 of 25
  14/  14 sec ............................................................~~(,_,">
 Maximization ...
1.85/1.85 min ............................................................~~(,_,">
 Estimating accuracies in the orientational assignment ... 
   3/   3 sec ............................................................~~(,_,">
 Auto-refine: Estimated accuracy angles= 8.62 degrees; offsets= 6.71 pixels
 CurrentResolution= 60.2998 Angstroms, which requires orientationSampling of at least 18.9474 degrees for a particle of diameter 360 Angstroms
 Oversampling= 0 NrHiddenVariableSamplingPoints= 580608
 OrientationalSampling= 15 NrOrientations= 4608
 TranslationalSampling= 2 NrTranslations= 21
=============================
 Oversampling= 1 NrHiddenVariableSamplingPoints= 18579456
 OrientationalSampling= 7.5 NrOrientations= 36864
 TranslationalSampling= 1 NrTranslations= 84
=============================
 Expectation iteration 2 of 25
   7/   7 sec ............................................................~~(,_,">
 Maximization ...
1.68/1.68 min ............................................................~~(,_,">
 Estimating accuracies in the orientational assignment ... 
   2/   2 sec ............................................................~~(,_,">
 Auto-refine: Estimated accuracy angles= 6.3 degrees; offsets= 5.125 pixels
 CurrentResolution= 60.2998 Angstroms, which requires orientationSampling of at least 18.9474 degrees for a particle of diameter 360 Angstroms
 Oversampling= 0 NrHiddenVariableSamplingPoints= 580608
 OrientationalSampling= 15 NrOrientations= 4608
 TranslationalSampling= 2 NrTranslations= 21
=============================
 Oversampling= 1 NrHiddenVariableSamplingPoints= 18579456
 OrientationalSampling= 7.5 NrOrientations= 36864
 TranslationalSampling= 1 NrTranslations= 84
=============================
 Expectation iteration 3 of 25
   7/   7 sec ............................................................~~(,_,">
 Maximization ...
1.67/1.67 min ............................................................~~(,_,">
 Estimating accuracies in the orientational assignment ... 
   3/   3 sec ............................................................~~(,_,">`

**Comment by bforsbe** [comment]
Next thing to check is probably driver used on each machine. Using the nvidia-smi command the driver version is displayed. 

Also, did you compile the code for the specific gpu-architecture? This shouldn't be necessary, but it'd be good to know.
