### ISSUE TITLE
Regroup from _data.star (feature request).

### ISSUE THREAD

**Issue by olibclarke** [3dem/relion#251]
Currently, regrouping only works for model.star files. Often, e.g. if importing from another program such as cryosparc, I do not have a model.star, and yet I may want to regroup my particles into a more sensible number of groups. It would be useful in this case if regrouping worked with data.star input.

**Comment by olibclarke** [comment]
Or alternatively, an option to automatically regroup as part of auto-refine would also be nice

**Comment by olibclarke** [comment]
Or even better, to set a minimum group size when extracting particles in the first place

**Comment by biochem-fan** [comment]
Outside RELION workflow. Please use an external script.
