### ISSUE TITLE
relion_run_motioncorr_mpi error

### ISSUE THREAD

**Issue by YANYANZH** [3dem/relion#257]
I keep getting this problem when running motioncor2 with MPI from relion 2.1.I don't see a problem when running relion_run_motioncorr, I also tried 3D classification or auto-refinement with GPUs and MPI. There isn't problem either. It seems to me it's the problem with relion_run_motioncorr_mpi  only.

Any advice is appreciated. 
Best,
Yanyan

000/??? sec ~~(,_,">                                                          [oo]--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 1 in communicator MPI_COMM_WORLD
with errorcode 1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.

The error says 
[gpustation:23048] 1 more process has sent help message help-mpi-api.txt / mpi-abort
[gpustation:23048] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages.

**Comment by ashkumatov** [comment]
first make sure that number of MPI matches number of GPU processors, say you want to run 4 GPU processors on your 4 GPU cards: then you specify Number of MPI procs: 4
and which GPUs to use? 0:1:2:3

**Comment by biochem-fan** [comment]
No response for a long time. Closing.
