### ISSUE TITLE
cannot run more than 1 mpi process

### ISSUE THREAD

**Issue by shikhaimt** [3dem/relion#259]
Hi I recently installed Relion2.1 on my new Ubuntu 16.04 ubuntu server (with desktop environment). It has 2 INTEL XEON E5-2620-V4 8 core CPUs, 2 NVIDIA TITAN PCI-E XP 12 GB GDDR5X.
Relion is installed in /home with type=part ; relion: /usr/local/bin/relion /emsoft/relion/build/bin/relion
My dataset is in /data with type=RAID 0, from where I try to run relion

When I try to run a 2D classification with more that 1 MPI processes it terminates with an error message
ERROR:
MlOptimiserMpi::initialiseWorkLoad: at least 2 MPI processes are required, otherwise use the sequential program
File: /emsoft/relion/src/ml_optimiser_mpi.cpp line: 563
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 0
[unset]: write_line error; fd=-1 buf=:cmd=abort exitcode=1
:
system msg for write_line failure : Bad file descriptor

I cannot figure out the actual issue?

**Comment by bforsbe** [comment]
You need to run at least 3 mpi processes, because relion currently uses one mpi process to distribute  tasks to the others. These 'others' need to be at least 2.

**Comment by shikhaimt** [comment]
If I was not clear in my previous post, thats where the problem lies. I cannot run 3 mpi processes, when I try the program exits stating:
Primary job  terminated normally, but 1 process returned
a non-zero exit code.. Per user-direction, the job has been aborted.
-------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[12426,1],1]
  Exit code:    1
with the error message as in my previous post.

**Comment by bforsbe** [comment]
Your original post contains the message relion displays when you run with 2 mpis. 

The message you show in the second post, is saying there was a problem, but not giving any indication of what that problem was. Try checking the log files of the run for more specific info. Without that, I can't start to guess what the issue is.

**Comment by shikhaimt** [comment]
I figured out the problem. It had something to do with the openmpi and associated libraries.

Thanks
SS
