### ISSUE TITLE
relion_mask_create  helptext

### ISSUE THREAD

**Issue by YehudaHalfon** [3dem/relion#260]
Hi, 
I saw that there is a bug that won't let us see the helptext of relion_mask_create when you run it by itself. 

How can I access the helptext? 

Also is there a date for the new version after this been repaired?

Yehuda

**Comment by bforsbe** [comment]
You can just check  the source file src/apps/mask_create,  it should be fairly obvious  what the options are from there. This will be fixed in a future version.

**Comment by YehudaHalfon** [comment]
Cool Thanks,
I copied them to a text file so we can use.
Hope for a new version soon.

Yehuda
