### ISSUE TITLE
Relion and OpenMPI 2.1.1 crashes

### ISSUE THREAD

**Issue by craigyk** [3dem/relion#262]
I recently recompiled (several times, with different configs) both OpenMPI 2.1.1 and Relion and was getting crashes and seg faults in ml_refinement.  Maybe it is a new OpenMPI bug?  In any case, switching to OpenMPI 2.0.3 and recompiled and everything works again.  Just thought you might like to know- I can do further troubleshooting if you want, but my current plan was to just wait for the next OpenMPI 2.1.x release and give it another try.

**Comment by bforsbe** [comment]
Much appreciated observation! I'll check myself next week, I don't think we have run with 2.1.1.

**Comment by hanyunfan** [comment]
it still crashes:

=============================
 Oversampling= 1 NrHiddenVariableSamplingPoints= 18579456
 OrientationalSampling= 7.5 NrOrientations= 36864
 TranslationalSampling= 1 NrTranslations= 84
=============================
 Expectation iteration 1 of 25
000/??? sec ~~(,_,">                                                          [oo]KERNEL_ERROR: no kernel image is available for execution on the device in /cm/shared/scratch/frank/relion/relion/src/gpu_utils/cuda_ml_optimiser.cu at line 292 (error-code 48)
[node002:148942] *** Process received signal ***
[node002:148942] Signal: Segmentation fault (11)
[node002:148942] Signal code: Address not mapped (1)
[node002:148942] Failing at address: 0xfffffffffffffffa
[node002:148942] [ 0] /lib64/libpthread.so.0(+0xf100)[0x2aaab413c100]
[node002:148942] [ 1] /lib64/libstdc++.so.6(_ZNSsC1ERKSs+0x1b)[0x2aaab460ff3b]
[node002:148942] [ 2] /cm/shared/apps/relion-sp/lib/librelion_lib.so(_ZN11RelionErrorC1ERKS_+0x1f)[0x2aaaaae7c31f]
[node002:148942] [ 3] /cm/shared/apps/relion-sp/lib/librelion_lib.so(_ZN11MlOptimiser24expectationSomeParticlesEll+0xeb7)[0x2aaaaae65927]
[node002:148942] [ 4] /cm/shared/apps/relion-sp/lib/librelion_lib.so(_ZN14MlOptimiserMpi11expectationEv+0x12d7)[0x2aaaaae833a7]
[node002:148942] [ 5] /cm/shared/apps/relion-sp/lib/librelion_lib.so(_ZN14MlOptimiserMpi7iterateEv+0x96)[0x2aaaaae8e006]
[node002:148942] [ 6] /cm/shared/apps/relion-sp/bin/relion_refine_mpi(main+0x69)[0x402d29]
[node002:148942] [ 7] /lib64/libc.so.6(__libc_start_main+0xf5)[0x2aaab4d93b15]
[node002:148942] [ 8] /cm/shared/apps/relion-sp/bin/relion_refine_mpi[0x402e91]
[node002:148942] *** End of error message ***
KERNEL_ERROR: no kernel image is available for execution on the device in /cm/shared/scratch/frank/relion/relion/src/gpu_utils/cuda_ml_optimiser.cu at line 292 (error-code 48)
[node002:148944] *** Process received signal ***
[node002:148944] Signal: Segmentation fault (11)
[node002:148944] Signal code: Address not mapped (1)
[node002:148944] Failing at address: 0xfffffffffffffffa
[node002:148944] [ 0] /lib64/libpthread.so.0(+0xf100)[0x2aaab413c100]
[node002:148944] [ 1] /lib64/libstdc++.so.6(_ZNSsC1ERKSs+0x1b)[0x2aaab460ff3b]
[node002:148944] [ 2] /cm/shared/apps/relion-sp/lib/librelion_lib.so(_ZN11RelionErrorC1ERKS_+0x1f)[0x2aaaaae7c31f]
[node002:148944] [ 3] /cm/shared/apps/relion-sp/lib/librelion_lib.so(_ZN11MlOptimiser24expectationSomeParticlesEll+0xeb7)[0x2aaaaae65927]
[node002:148944] [ 4] /cm/shared/apps/relion-sp/lib/librelion_lib.so(_ZN14MlOptimiserMpi11expectationEv+0x12d7)[0x2aaaaae833a7]
[node002:148944] [ 5] /cm/shared/apps/relion-sp/lib/librelion_lib.so(_ZN14MlOptimiserMpi7iterateEv+0x96)[0x2aaaaae8e006]
[node002:148944] [ 6] /cm/shared/apps/relion-sp/bin/relion_refine_mpi(main+0x69)[0x402d29]
[node002:148944] [ 7] /lib64/libc.so.6(__libc_start_main+0xf5)[0x2aaab4d93b15]
[node002:148944] [ 8] /cm/shared/apps/relion-sp/bin/relion_refine_mpi[0x402e91]
[node002:148944] *** End of error message ***
KERNEL_ERROR: no kernel image is available for execution on the device in /cm/shared/scratch/frank/relion/relion/src/gpu_utils/cuda_ml_optimiser.cu at line 292 (error-code 48)
[node002:148943] *** Process received signal ***
[node002:148943] Signal: Segmentation fault (11)
[node002:148943] Signal code: Address not mapped (1)
[node002:148943] Failing at address: 0xfffffffffffffffa
[node002:148943] [ 0] /lib64/libpthread.so.0(+0xf100)[0x2aaab413c100]
[node002:148943] [ 1] /lib64/libstdc++.so.6(_ZNSsC1ERKSs+0x1b)[0x2aaab460ff3b]
[node002:148943] [ 2] /cm/shared/apps/relion-sp/lib/librelion_lib.so(_ZN11RelionErrorC1ERKS_+0x1f)[0x2aaaaae7c31f]
[node002:148943] [ 3] /cm/shared/apps/relion-sp/lib/librelion_lib.so(_ZN11MlOptimiser24expectationSomeParticlesEll+0xeb7)[0x2aaaaae65927]
[node002:148943] [ 4] /cm/shared/apps/relion-sp/lib/librelion_lib.so(_ZN14MlOptimiserMpi11expectationEv+0x12d7)[0x2aaaaae833a7]
[node002:148943] [ 5] /cm/shared/apps/relion-sp/lib/librelion_lib.so(_ZN14MlOptimiserMpi7iterateEv+0x96)[0x2aaaaae8e006]
[node002:148943] [ 6] /cm/shared/apps/relion-sp/bin/relion_refine_mpi(main+0x69)[0x402d29]
[node002:148943] [ 7] /lib64/libc.so.6(__libc_start_main+0xf5)[0x2aaab4d93b15]
[node002:148943] [ 8] /cm/shared/apps/relion-sp/bin/relion_refine_mpi[0x402e91]
[node002:148943] *** End of error message ***
KERNEL_ERROR: no kernel image is available for execution on the device in /cm/shared/scratch/frank/relion/relion/src/gpu_utils/cuda_ml_optimiser.cu at line 292 (error-code 48)
[node002:148945] *** Process received signal ***
[node002:148945] Signal: Segmentation fault (11)
[node002:148945] Signal code: Address not mapped (1)
[node002:148945] Failing at address: 0xfffffffffffffffa
[node002:148945] [ 0] /lib64/libpthread.so.0(+0xf100)[0x2aaab413c100]
[node002:148945] [ 1] /lib64/libstdc++.so.6(_ZNSsC1ERKSs+0x1b)[0x2aaab460ff3b]
[node002:148945] [ 2] /cm/shared/apps/relion-sp/lib/librelion_lib.so(_ZN11RelionErrorC1ERKS_+0x1f)[0x2aaaaae7c31f]
[node002:148945] [ 3] /cm/shared/apps/relion-sp/lib/librelion_lib.so(_ZN11MlOptimiser24expectationSomeParticlesEll+0xeb7)[0x2aaaaae65927]
[node002:148945] [ 4] /cm/shared/apps/relion-sp/lib/librelion_lib.so(_ZN14MlOptimiserMpi11expectationEv+0x12d7)[0x2aaaaae833a7]
[node002:148945] [ 5] /cm/shared/apps/relion-sp/lib/librelion_lib.so(_ZN14MlOptimiserMpi7iterateEv+0x96)[0x2aaaaae8e006]
[node002:148945] [ 6] /cm/shared/apps/relion-sp/bin/relion_refine_mpi(main+0x69)[0x402d29]
[node002:148945] [ 7] /lib64/libc.so.6(__libc_start_main+0xf5)[0x2aaab4d93b15]
[node002:148945] [ 8] /cm/shared/apps/relion-sp/bin/relion_refine_mpi[0x402e91]
[node002:148945] *** End of error message ***
--------------------------------------------------------------------------
mpirun noticed that process rank 1 with PID 0 on node node002 exited on signal 11 (Segmentation fault).
--------------------------------------------------------------------------

**Comment by craigyk** [comment]
I've since noticed that this bug only seems to pop up running the CPU code but not the GPU with OpenMPI 2.1.x

**Comment by biochem-fan** [comment]
Old version.
