### ISSUE TITLE
Please increase fault tolerance

### ISSUE THREAD

**Issue by dtegunov** [3dem/relion#264]
This has probably been suggested before, but I'd like to stress the issue once again:

sumweight = 0 has been around forever and is, in my experience, the most frequent cause of failed refinements. Can this exception be handled in a softer way, i. e. without killing everything? Write a warning, or maintain a file with a list of failed particles for each iteration. Most of the time, a refinement will do just fine without a few particles, and there is a good chance they'll come back to life in the next iteration. In case of catastrophic failure, e. g. >1 % of all particles, the run can still be aborted.

I think this would save many users a lot of time without affecting the results negatively.

**Comment by dkimanius** [comment]
Although I agree that ~1% of particles failing isn't much, it does say something about the state of the whole dataset. The erroneous images fail to generate *any* significant weights, suggesting that there is be a greater number of images generating "bad" weights. This is where you should go back and re-extract the images with re-centering on. 

But if you know what you're doing you can always raise the threshold to permit higher numbers of failures in the GPU code-path with a simple hack. Comment out line 3218-3219 in /src/gpu_utils/cuda_ml_optimiser.cu, in the current commit (2e60eb9).

I'll add an advanced flag for this in the next release. Let's call it --failsafe_threshold

**Comment by olibclarke** [comment]
+1000

**Comment by dtegunov** [comment]
Thanks, I'll modify my local installation. However, the instance of sumweight = 0 that prompted this particular message was in a 2D classification without alignment (taking particles from a 3D refinement that finished without errors), which runs exclusively on the CPU if I'm not mistaken :-)

Sure, there is a chance something is wrong with those particles. The user should definitely be made aware of their presence. On the other hand, the refinement can often be continued without crashes on the CPU if it crashed on the GPU (maybe also vice versa?) – which makes me think there is nothing catastrophically wrong that would justify dismissing hours of calculations, sending users on a hunt for a few rogue particles in a haystack of 500k good ones.

I know this is not an "elegant" solution. As a developer, I'd also rather invest time in fixing the cause, not the symptom. However, as a user, I would very much prefer a quick and dirty fix for the symptom if it lets me arrive at a virtually identical result without hours of troubleshooting.

**Comment by olibclarke** [comment]
I agree with Dmitry - the default is too conservative and also does not point the user towards an easy way to fix the problem. This seems to be something that could be handled by a warning, and/or perhaps by writing out a star file with the offending particles, so at least the user can easily inspect them to see what might be causing the issue.

**Comment by dkimanius** [comment]
Addressed in commit db46c45a802dc112f27b8070782719d28dcefe38.
