### ISSUE TITLE
relion_mask_create makes corrupted file when output does not have mrc extension.

### ISSUE THREAD

**Issue by olibclarke** [3dem/relion#270]
Running relion_mask_create on the command line, I accidentally left off the mrc extension from the output file. When I do so, relion_mask_create consistently creates a file that is *almost* the right size (256001600 vs 256001024 bytes), but with a corrupted header that prevents it from being read - see attached. Also, in general it would be great if relion_refine performed a "sanity check" on all supplied files before beginning. Last night I started a job with a mask that unbeknownst to me was corrupted. Relion happily went through estimating initial noise spectra and the expectation step of the first iteration before crashing sometime during the night when it tried to read the mask. Would seem trivial to test all user supplied files for readability before starting a job. 
<img width="567" alt="image" src="https://user-images.githubusercontent.com/19766818/29071129-4123a9d6-7c10-11e7-94fc-8ea67d0796ae.png">

**Comment by biochem-fan** [comment]
It seems that RELION writes in the SPIDER format https://spider.wadsworth.org/spider_doc/spider/docs/image_doc.html when no file extension is given.
https://github.com/3dem/relion/blob/50505945ec46c25ddebf7292492df7de331a2696/src/image.h#L1376

**Comment by olibclarke** [comment]
Hmmm - if that is the desired behavior, perhaps saying so in the helptext or output would be good? Or adding a .spi extension, if this is the intention?

**Comment by bforsbe** [comment]
This has been fixed on the development branch and will work as expected in the future (2.1b1 an onwards), i.e. " --o fileName" will result in a spider-format file called "fileName.spi", whereas specifying i.e. an mrc file will return an mrc file.
