### ISSUE TITLE
CUDA9 support? (feature request/suggestion)

### ISSUE THREAD

**Issue by olibclarke** [3dem/relion#272]
Looks like CUDA 9 offers pretty substantial performance improvements (2-5X) for Pascal GPUs (https://developer.nvidia.com/cuda-toolkit/whatsnew), and a release candidate is available now - any plans for support in relion, or is the current version compatible with CUDA 9 already?

**Comment by bforsbe** [comment]
Do you have a more specific reference to those numbers? The page you like says Pascal is faster OOTB using cuda 8, as opposed to earlier versions. I can't find any reference to 9 making pascal faster. Most of the updates to cuda 9 concern the volta-gen cards and their tensor cores, so a five-fold speedup would be extraordinary. 

You can run with cuda 9 currently, at least there is nothing we know of to impede it. It's not tested, but supported.

**Comment by olibclarke** [comment]
Sorry I think I was misreading it, my mistake. I'll try with relion at some point anyway and see if it makes a difference.
