### ISSUE TITLE
Problem with Import of 2D micrographs/tomograms from outside of project directory

### ISSUE THREAD

**Issue by robertthomasbyrne** [3dem/relion#274]
We encountered some unexpected behaviour with Relion 2.1-beta-0 when importing aligned micrographs from a directory that is *not* a sub-directory of the Relion project directory.

To import the aligned micrographs, the user selected the Node Type: 2D micrographs/tomograms and then located the aligned micrographs using the Browse button. This resulted in the entry Input Files: ../micrographs/*.mrc. The job completed without any problems.

When the user then runs a subsequent task (e.g. CTF estimation) the programs creates the resulting output files in the incorrect subdirectory. For example:

relion_project_directory/CtfFind/micrographs

instead of within the job directory:

relion_project_directory/CtfFind/job002/micrographs

If the user re-runs the task (e.g. CTF estimation), the files in this directory are overwritten. The user might choose to use the results of the first job, but because they been overwritten, they might unknowingly be using the results of the second job.

In this case, this behaviour caused a problem because the user had extracted particles twice. When they tried to use a particles.star file corresponding to the first particle extraction, this resulted in the error message "Image number xxx exceeds stack size yyy". This was apparently because the second particle extraction job had overwritten the first set of stacks in the directory (e.g. Extract/micrographs) and the references in the first particles.star file were incorrect.

The simplest workaround would be to first copy the aligned micrographs into a subdirectory of the project directory and only then import them.

Best regards,
Rob

**Comment by bforsbe** [comment]
Thanks for reporting it, but this has been noted before (issues #143 and #273 ), and the general advice is to make a shortcut or soft link which makes it appear as though the data is residing inside the relion directory. This avoids making a copy of the data and storing it within the directory.
