### ISSUE TITLE
More sum_weights=0 errors with 2.1beta1?

### ISSUE THREAD

**Issue by olibclarke** [3dem/relion#277]
Hi, I'm rerunning a masked refinement using 2.1beta1 (which completed without error using an earlier build of 2.1). I keep running into the annoying sum_weights=0 error, which neccessitates continuing the refinement every time it crashes (every couple of iterations). 

This is on a clean set of recentered particles.

Firstly, has anything changed in the new build that could be leading to more of these errors? And secondly, How do I disable these error messages? The refinement seems to be proceeding just fine in every other respect.

**Comment by biochem-fan** [comment]
Old version.
