### ISSUE TITLE
Version/Commit from Relion Executable 

### ISSUE THREAD

**Issue by achintangal** [3dem/relion#278]
This is more of a question than an issue. Is there a way to tell which version/commit a build of relion is based from using the relion_* executable?

Correct me if I am wrong, but version info is not present in the about section of the GUI before 2.1. 

Thanks!

**Comment by bforsbe** [comment]
If you compiled with the GUI, the "about" tab should contain version information from 2.0.4 onwards. It's a good point to add though, relion_* --version (or --help or so)  should print the version number. Thanks for pointing it out!

**Comment by achintangal** [comment]
Thanks! A version switch would be a nice addition.
