### ISSUE TITLE
Relion 2.1 beta does not display 3D mrc slices

### ISSUE THREAD

**Issue by didny1** [3dem/relion#279]
Hello,

I have compiled Relion 2.1 beta on CentOS 7.3 with CUDA a few days ago. I have noticed that after Refine3D when I click display and choose: out:*.mrc file, Relion display GUI window appears but as soon as I click there display, the window closes. This only happens to 3D mrc files, for 2D classification files everything works fine. I hope it can be fixed easily.

Best,
Dawid

**Comment by bforsbe** [comment]
Is "Max. nr. images:" set to larger than the number of slices? Try setting it to "-1".

**Comment by didny1** [comment]
@bforsbe you are right! -1 works well (previous default setup was 1000). Thank you very much!
