### ISSUE TITLE
Installation script does not set runtime path for relion

### ISSUE THREAD

**Issue by jdonners** [3dem/relion#280]
Although the installation script sets the right runtime path for all relion_* executables and the libraries, it forgets the relion executable itself.

**Comment by biochem-fan** [comment]
This is still the case.

How to confirm:
https://stackoverflow.com/questions/2836330/is-there-a-way-to-inspect-the-current-rpath-on-linux

**Comment by biochem-fan** [comment]
Fixed in 92353d8.
