### ISSUE TITLE
weird output with ctffind

### ISSUE THREAD

**Issue by ncoudray** [3dem/relion#286]
Hi,

  when running ctffind 4.1 on relion 2.1.0 with the option "Use Micrograph without dose-weighting" set to "No", it works, but when set to "Yes", it gives the following output run.out:
`-catch_rsh /cm/local/apps/sge/var/spool/node035/active_jobs/3484196.1/pe_hostfile
node035
node035
node035
node035
node035
node035
node035
node035
node035
node035
node035
node035
node035
node035
node035
Warning: no access to tty (Bad file descriptor).
Thus no job control in this shell.
 === RELION MPI setup ===
 + Number of MPI processes             = 15
 + Master  (0) runs on host            = node035
 + Slave     1 runs on host            = node035
 + Slave     2 runs on host            = node035
 + Slave     3 runs on host            = node035
 + Slave     4 runs on host            = node035
 + Slave     5 runs on host            = node035
 + Slave     6 runs on host            = node035
 + Slave     7 runs on host            = node035
 + Slave     8 runs on host            = node035
 + Slave     9 runs on host            = node035
 + Slave    10 runs on host            = node035
 + Slave    11 runs on host            = node035
 + Slave    12 runs on host            = node035
 + Slave    13 runs on host            = node035
 + Slave    14 runs on host            = node035
 =================
 Using CTFFIND executable in: /local/apps/ctffind/4.1.8/bin/ctffind
 to estimate CTF parameters for the following micrographs: 
  * 
  * 
  * 
  * 
  * 
  * 
  * 
  * 
  * 
  * 
  * 
  * 
  * 
  * 
  * 
 Estimating CTF parameters using Niko Grigorieff's CTFFIND ...
000/??? sec ~~(,_,">                                                          [oo]y
y
y
y
y
y
y
y
y
y
y
y
y
y
y
`

It then carries on outputting "y" for thousands of lines and the file becomes huge and the GUI get stuck. 

run.err outputs this:
`5: Command not found.
2000: Command not found.
120000: Command not found.
500: Command not found.
no: Command not found.
no: Command not found.`

We tried on the  beta-galactosidase dataset and it behaves the same way. 

I checked but haven't seen any thread on it, so sorry if this subject was published before...

Best,
Nicolas

**Comment by ncoudray** [comment]
Another thing regarding the CTF: in the tutorial, it says that if the parameters are not good for some micrographs, we can delete the log files and "alter the parameters in the
parameter-panel, and then re-run the job by clicking the Continue now button"
However, all the options are greyed out once the job is done and the parameters cannot be adjusted (unless there is a trick to do it?).

Thanks,
Best,
N.

**Comment by biochem-fan** [comment]
Not relevant for the latest version.
