### ISSUE TITLE
3D autorefine crash, regroup issue

### ISSUE THREAD

**Issue by clee02** [3dem/relion#289]
Hi, 
After I selected a subset of particles from classification, I tried to do autorefine but refine keep crashing.

> [CH-Workstation001:02932] Signal: Segmentation fault (11)
[CH-Workstation001:02932] Signal code: Address not mapped (1)
[CH-Workstation001:02932] Failing at address: 0x7f978a0e3296
[CH-Workstation001:02932] [ 0] /lib/x86_64-linux-gnu/libpthread.so.0(+0x11390)[0x7f958a0e7390]
[CH-Workstation001:02932] [ 1] /lib/x86_64-linux-gnu/libc.so.6(+0x14e128)[0x7f95898c2128]
[CH-Workstation001:02932] [ 2] /mnt/SSD/EMsoftwares/relion/build/lib/librelion_lib.so(+0x7d527)[0x7f958a652527]
[CH-Workstation001:02932] [ 3] /mnt/SSD/EMsoftwares/relion/build/lib/librelion_lib.so(_ZN11RelionErrorC1ERKS_+0x47)[0x7f958a669537]
[CH-Workstation001:02932] [ 4] /mnt/SSD/EMsoftwares/relion/build/lib/librelion_lib.so(_ZN11MlOptimiser24expectationSomeParticlesEll+0x1341)[0x7f958a7ecaa1]
[CH-Workstation001:02932] [ 5] /mnt/SSD/EMsoftwares/relion/build/lib/librelion_lib.so(_ZN14MlOptimiserMpi11expectationEv+0x13f1)[0x7f958a655aa1]
[CH-Workstation001:02932] [ 6] /mnt/SSD/EMsoftwares/relion/build/lib/librelion_lib.so(_ZN14MlOptimiserMpi7iterateEv+0x9d)[0x7f958a664ced]
[CH-Workstation001:02932] [ 7] relion_refine_mpi(main+0x7c)[0x402c4c]
[CH-Workstation001:02932] [ 8] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0)[0x7f9589794830]
[CH-Workstation001:02932] [ 9] relion_refine_mpi(_start+0x29)[0x402de9]
[CH-Workstation001:02932] *** End of error message ***
--------------------------------------------------------------------------

Relion also wrote out  "error_dump_pdf_orientation" , "error_dump_pdf_offset", "error_dump_filtered" into the folder.

In the log file, I found that there are multiple warning about too few particles in a group. After regrouping the particles, the error message went away and I could run 3D autorefine.

I did notice that a pattern in the warning

> WARNING: There are only 3 particles in group 122 of half-set 1
WARNING: There are only 3 particles in group 223 of half-set 1
WARNING: There are only 4 particles in group 231 of half-set 1
WARNING: There are only 4 particles in group 311 of half-set 1
WARNING: There are only 4 particles in group 462 of half-set 1
WARNING: There are only 2 particles in group 488 of half-set 1
WARNING: There are only 0 particles in group 646 of half-set 1
WARNING: There are only 0 particles in group 647 of half-set 1
WARNING: There are only 0 particles in group 648 of half-set 1
WARNING: There are only 0 particles in group 649 of half-set 1
WARNING: There are only 0 particles in group 650 of half-set 1
WARNING: There are only 0 particles in group 651 of half-set 1
WARNING: There are only 0 particles in group 652 of half-set 1
WARNING: There are only 0 particles in group 653 of half-set 1
WARNING: There are only 0 particles in group 654 of half-set 1
WARNING: There are only 0 particles in group 655 of half-set 1
....
....
WARNING: There are only 0 particles in group 1339 of half-set 1

Somehow, after image 646, EVERY image now contains 0 particle in half-set 1.
When I looked into run_it000_half2_model.star, I saw group 646 to 1339 of half set 2 usually have ~10-40 particles.
    
This pattern seems odd to me. I am curious to know if I did something wrong. But maybe it is normal. 

Thanks foy any input.

**Comment by bforsbe** [comment]
How many MPIs did you run with?

**Comment by clee02** [comment]
I used 4 MPIs. The workstation has three GPUs.

**Comment by bforsbe** [comment]
IT makes sense to run with 3MPIs from the point of view of having 3GPUs; one slave MPI rank per GPU. However, Autorafine splits the data into halves and I'm not sure what will happen when data is split into "halves" across 3 MPIs. It **should** just work, but I'm not sure it will. I'd recommend trying with 3 MPIs in total and using ``` --gpu 0:1 ``` to keep the two ranks on just two GPUs. If that works, then I can try to make improvementes to the code to better handle odd numbers of MPI-ranks in auto-refine. Alternatively, you van run with 7 MPIS, having 2 on each GPU. Depending on your box-size this will might not make it to the end (it runs out of GPU-memory if the box-size andresolution go to high), but you can always continue from that point with fewer MPIs / without GPUs.

**Comment by clee02** [comment]
Thank you so much. Using odd numbers of MPIs solved the issue without the need of regroup.
