### ISSUE TITLE
Compilation on macOS Sierra

### ISSUE THREAD

**Issue by dtegunov** [3dem/relion#291]
https://github.com/3dem/relion/blob/e7607a869687b636d3c39e0d5b6a9cba930fc3b2/src/image.h#L866

This line causes an error when compiling with clang on macOS Sierra with latest Xcode installed. Please consider changing the comparison to page > nullptr.

**Comment by yoyoq12** [comment]
thanks. that compiled it for me.

although seperate issue : i haven't gotten the GUI working yet

**Comment by dtegunov** [comment]
The user who had this compilation issue definitely had a working GUI afterwards, but I'm not sure what she had installed in addition. For the old 1.4 version, it was just a matter of updating the FLTK library supplied with it.

**Comment by dkimanius** [comment]
This is an old file form the XMIPP library that haven't been updated for quite some time. It's certainly in need of some reviewing. Also perhaps it's time to look into updating the FLTK library for the next release. I'll add it to the todo-list. Thanks!
