### ISSUE TITLE
WARNING: Exception ERROR:  No orientation was found as better than any other.

### ISSUE THREAD

**Issue by wimhagen** [3dem/relion#298]
Relion asked me to report this:

[gpu3.cluster.embl.de:11761] 2 more processes have sent help message help-mpi-btl-openib-cpc-base.txt / no cpcs for port
[gpu3.cluster.embl.de:11761] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages

WARNING: Exception (ERROR: 
No orientation was found as better than any other.

A particle image was compared to the reference and resulted in all-zero
weights (for all orientations). This should not happen, unless your data
has very special characteristics. This has historically happened for some 
lower-precision calculations, but multiple fallbacks have since been 
implemented. Please report this error to the relion developers at 

	         github.com/3dem/relion/issues  
 ) handled by switching to fail-safe mode.

 fn_img= 083758@/tmp/6505784/relion_volatile/particles.mrcs
 part_id= 83757
 ipart= 0
 op.min_diff2[ipart]= 18985.7
 group_id= 44
 ml_model.scale_correction[group_id]= 0.994776
 exp_significant_weight[ipart]= 0
 exp_max_weight[ipart]= -1
 ml_model.sigma2_noise[group_id]= 
 9.949e-06
 5.897e-06
 1.573e-06
 1.199e-06
 1.022e-06
 9.893e-07
 9.801e-07
 1.044e-06
 1.044e-06
 1.095e-06
 1.103e-06
 1.018e-06
 9.747e-07
 9.020e-07
 8.600e-07
 8.025e-07
 7.911e-07
 7.812e-07
 7.712e-07
 7.948e-07
 7.981e-07
 8.296e-07
 8.116e-07
 7.748e-07
 7.567e-07
 7.456e-07
 7.465e-07
 7.191e-07
 6.964e-07
 7.044e-07
 7.168e-07
 7.279e-07
 7.164e-07
 6.895e-07
 6.747e-07
 6.991e-07
 7.224e-07
 7.096e-07
 6.906e-07
 7.011e-07
 7.207e-07
 7.350e-07
 7.409e-07
 7.395e-07
 7.567e-07
 7.841e-07
 8.062e-07
 8.203e-07
 8.246e-07
 8.486e-07
 8.829e-07
 8.763e-07
 8.728e-07
 9.091e-07
 9.253e-07
 9.235e-07
 9.409e-07
 9.561e-07
 9.753e-07
 9.876e-07
 9.994e-07
 1.025e-06
 1.032e-06
 1.044e-06
 1.064e-06
 1.081e-06
 1.103e-06
 1.116e-06
 1.135e-06
 1.144e-06
 1.156e-06
 1.174e-06
 1.190e-06
 1.202e-06
 1.211e-06
 1.229e-06
 1.242e-06
 1.217e-06
 1.280e-06
 1.301e-06
 1.316e-06
 1.339e-06
 1.360e-06
 1.379e-06
 1.395e-06
 1.412e-06
 1.436e-06
 1.456e-06
 1.476e-06
 1.499e-06
 1.523e-06
 1.540e-06
 1.560e-06
 1.592e-06
 1.611e-06
 1.632e-06
 1.651e-06
 1.669e-06
 1.694e-06
 1.720e-06
 1.740e-06
 1.759e-06
 1.784e-06
 1.804e-06
 1.826e-06
 1.842e-06
 1.868e-06
 1.896e-06
 1.918e-06
 1.939e-06
 1.948e-06
 1.968e-06
 1.982e-06
 2.002e-06
 2.033e-06
 2.048e-06
 2.065e-06
 2.077e-06
 2.097e-06
 2.116e-06
 2.129e-06
 2.148e-06
 2.158e-06
 2.177e-06
 2.196e-06
 2.208e-06
 2.231e-06
 2.236e-06
 2.263e-06
 2.279e-06
 2.289e-06
 2.307e-06
 2.310e-06
 2.334e-06
 2.349e-06
 2.361e-06
 2.376e-06
 2.388e-06
 2.414e-06
 2.427e-06
 2.428e-06
 2.447e-06
 2.478e-06
 2.493e-06
 2.478e-06
 2.501e-06
 2.503e-06
 2.518e-06
 2.502e-06
 2.233e-06
 1.373e-06

terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
[gpu3:11765] *** Process received signal ***
[gpu3:11765] Signal: Aborted (6)
[gpu3:11765] Signal code:  (-6)
[gpu3:11765] [ 0] /usr/lib64/libpthread.so.0(+0xf5e0)[0x7f9a0e9a75e0]
[gpu3:11765] [ 1] /usr/lib64/libc.so.6(gsignal+0x37)[0x7f9a0df621f7]
[gpu3:11765] [ 2] /usr/lib64/libc.so.6(abort+0x148)[0x7f9a0df638e8]
[gpu3:11765] [ 3] /g/easybuild/x86_64/CentOS/7/haswell/software/GCCcore/5.4.0/lib64/libstdc++.so.6(_ZN9__gnu_cxx27__verbose_terminate_handlerEv+0x15d)[0x7f9a0e6a17fd]
[gpu3:11765] [ 4] /g/easybuild/x86_64/CentOS/7/haswell/software/GCCcore/5.4.0/lib64/libstdc++.so.6(+0x96876)[0x7f9a0e69f876]
[gpu3:11765] [ 5] /g/easybuild/x86_64/CentOS/7/haswell/software/GCCcore/5.4.0/lib64/libstdc++.so.6(+0x968c1)[0x7f9a0e69f8c1]
[gpu3:11765] [ 6] /g/easybuild/x86_64/CentOS/7/haswell/software/GCCcore/5.4.0/lib64/libstdc++.so.6(+0x96ad8)[0x7f9a0e69fad8]
[gpu3:11765] [ 7] /g/easybuild/x86_64/CentOS/7/haswell/software/GCCcore/5.4.0/lib64/libstdc++.so.6(+0x96fdc)[0x7f9a0e69ffdc]
[gpu3:11765] [ 8] /g/easybuild/x86_64/CentOS/7/haswell/software/RELION/2.1-beta-1_20170817_000_e7607a8-foss-2016b/lib/librelion_lib.so(+0x212fef)[0x7f9a18633fef]
[gpu3:11765] [ 9] /g/easybuild/x86_64/CentOS/7/haswell/software/RELION/2.1-beta-1_20170817_000_e7607a8-foss-2016b/lib/librelion_lib.so(_ZN11RelionErrorC2ERKS_+0x47)[0x7f9a1867b7f7]
[gpu3:11765] [10] /g/easybuild/x86_64/CentOS/7/haswell/software/RELION/2.1-beta-1_20170817_000_e7607a8-foss-2016b/lib/librelion_lib.so(_ZN11MlOptimiser24expectationSomeParticlesEll+0x12b8)[0x7f9a1865bb48]
[gpu3:11765] [11] /g/easybuild/x86_64/CentOS/7/haswell/software/RELION/2.1-beta-1_20170817_000_e7607a8-foss-2016b/lib/librelion_lib.so(_ZN14MlOptimiserMpi11expectationEv+0x13bd)[0x7f9a1868287d]
[gpu3:11765] [12] /g/easybuild/x86_64/CentOS/7/haswell/software/RELION/2.1-beta-1_20170817_000_e7607a8-foss-2016b/lib/librelion_lib.so(_ZN14MlOptimiserMpi7iterateEv+0x8d)[0x7f9a18692a7d]
[gpu3:11765] [13] /g/easybuild/x86_64/CentOS/7/haswell/software/RELION/2.1-beta-1_20170817_000_e7607a8-foss-2016b/bin/relion_refine_mpi(main+0x69)[0x40a8a9]
[gpu3:11765] [14] /usr/lib64/libc.so.6(__libc_start_main+0xf5)[0x7f9a0df4ec05]
[gpu3:11765] [15] /g/easybuild/x86_64/CentOS/7/haswell/software/RELION/2.1-beta-1_20170817_000_e7607a8-foss-2016b/bin/relion_refine_mpi[0x40aa3f]
[gpu3:11765] *** End of error message ***

real	124m24.036s
user	183m0.389s
sys	31m31.924s

Best,

Wim Hagen
EMBL Heidelberg

**Comment by craigyk** [comment]
I'd like to add that I'm seeing a lot more of these errors as well in 2.1.

Not sure if this error is due to a bug in rare corner cases (really bad particles), but I think Relion should print warnings and automatically strip the particles that fail these checks (same for normalization) rather than stopping or crashing.

**Comment by ehanssen** [comment]
Found similar error. 
WARNING: Exception (ERROR: 
No orientation was found as better than any other.

A particle image was compared to the reference and resulted in all-zero
weights (for all orientations). This should not happen, unless your data
has very special characteristics. This has historically happened for some 
lower-precision calculations, but multiple fallbacks have since been 
implemented. Please report this error to the relion developers at 

	         github.com/3dem/relion/issues  
 ) handled by switching to fail-safe mode.

**Comment by biochem-fan** [comment]
Old version.
