### ISSUE TITLE
Relion 2.0.5 update to Relion 2.1

### ISSUE THREAD

**Issue by baibing7713661** [3dem/relion#300]
I have installed the relion on a ubuntu system and a GUI of 2.0.5 pop when hit "relion". Now I would like to update to the latest Relion 2.1 with git clone and there are two version relion and relion2-beta in my home directory. When I hit "relion" still the old version 2.0.5 pop up. Is there a way to activate the new version? Do I need to uninstall the old version? and how to do this since I also try to delete the relion folder and it does not help and still the old version pop up.

Thanks in advance 
Bing

**Comment by biochem-fan** [comment]
Hi, you have to setup your `PATH` environmental variable so that the `bin` directory of 2.1 comes earlier than the old version.

**Comment by baibing7713661** [comment]
Hi,
I have used gedit ~/.profile  to change the PATH environment and save as below. However when hit "relion" still the old version come out. `which relion` points to the new version? where to to setup this?

# ~/.profile: executed by the command interpreter for login shells.
# This file is not read by bash(1), if ~/.bash_profile or ~/.bash_login
# exists.
# see /usr/share/doc/bash/examples/startup-files for examples.
# the files are located in the bash-doc package.

# the default umask is set in /etc/profile; for setting the umask
# for ssh logins, install and configure the libpam-umask package.
#umask 022

# if running bash
if [ -n "$BASH_VERSION" ]; then
    # include .bashrc if it exists
    if [ -f "$HOME/.bashrc" ]; then
	. "$HOME/.bashrc"
    fi
fi

# set PATH so it includes user's private bin directories
PATH="$HOME/bin:$HOME/.local/bin:$PATH:/relion2-beta/bin"

**Comment by biochem-fan** [comment]
(1) edit `~/.bashrc`, not `~/.profile`.
(2) Earlier entries (= those in left) take priority in the `PATH`. Thus, it should be:
```sh
export PATH="/relion2-beta/bin:$HOME/bin:$HOME/.local/bin:$PATH"
```
(3) Did you really install relion2 in `/`? Isn't it `$HOME/relion2-beta/bin`?

**Comment by baibing7713661** [comment]
<img width="1463" alt="qq20171102-163509 2x" src="https://user-images.githubusercontent.com/21249922/32334866-db7dbe76-bfeb-11e7-9431-332c4f725f9a.png">
I tried the `export PATH="/relion2-beta/bin:$HOME/bin:$HOME/.local/bin:$PATH"`and the issue remains as attached.

**Comment by biochem-fan** [comment]
Where did you build relion2 beta? Are you sure it is in /relion2-beta/bin?

**Comment by baibing7713661** [comment]
<img width="1394" alt="qq20171102-164058 2x" src="https://user-images.githubusercontent.com/21249922/32335220-a1c9fcde-bfec-11e7-8cb2-58b4fb6975ab.png">
Here is a screen shot for that. I think the files are there.

**Comment by biochem-fan** [comment]
OK, it is **in your home directory**, not `/`!

`export PATH="$HOME/relion2-beta/build/bin:$HOME/bin:$HOME/.local/bin:$PATH"`
should solve your problem.

**Comment by baibing7713661** [comment]
<img width="1181" alt="qq20171102-164444 2x" src="https://user-images.githubusercontent.com/21249922/32335424-277980fc-bfed-11e7-8eaf-2c4aa68f5262.png">

**Comment by biochem-fan** [comment]
What does the following command show?
`which relion`

Are you sure you re-built RELION by running `cmake` and `make` after downloading files from Git?

**Comment by baibing7713661** [comment]
<img width="1062" alt="qq20171102-164801 2x" src="https://user-images.githubusercontent.com/21249922/32335646-9ca735d6-bfed-11e7-9a56-3987a1c593ca.png">

**Comment by biochem-fan** [comment]
This means your `PATH` is not set up correctly.

**Comment by baibing7713661** [comment]
Shall I try to remove the relion 2.0.5 and re-build for relion 2.1? I did not know how to completely remove the old version. Removing the folder did not help.
so the `export PATH="$HOME/relion2-beta/build/bin:$HOME/bin:$HOME/.local/bin:$PATH"` is also now working.

**Comment by biochem-fan** [comment]
What does `echo $PATH` say?

**Comment by dkimanius** [comment]
Dear Bing,

To clone the latest official release of Relion run:

git clone https://github.com/3dem/relion.git

Then follow the usual compilation procedure.

As it appears you have not made a system-wide installation of 2.1. Do you still plan on using 2.0.5? If not, you can replace the old version by running "sudo make install". Assuming the old Relion was installed in the default installation path, it will be replace with the new one.

If you however would like to temporarily activate the new version and keep the old version available system-wide, you can can modify your environment as suggested. In such case you might need to also set the variable  LD_LIBRARY_PATH. That is if you have compiled shared libraries in BUILD_DIR/lib.

Best,
Dari

**Comment by baibing7713661** [comment]
Dear Dari,
Thanks for the info. I repeat the installation and it confront errors when I start the following step and thus the  system-wide installation is not complete. I attach is error message. Could you let me know I can do with this.
<img width="1179" alt="qq20171102-172248 2x" src="https://user-images.githubusercontent.com/21249922/32337503-7bb7de48-bff2-11e7-8400-9ebdd3c7236e.png">

cmake -DCMAKE_INSTALL_PREFIX=~/relion ..

**Comment by biochem-fan** [comment]
Also you didn't seem to build RELION GUI tools. In `~/relion2-beta/build/bin`, we can see `relion_refine`, `relion_preprocess`, etc but not `relion` and `relion_display`.

Make sure set `GUI` to ON.

**Comment by dkimanius** [comment]
If you want relion to be installed system-wide drop CMAKE_INSTALL_PREFIX. Also you have a bunch of settings you have set previously, e.g. omitting GUI targets. Begin by wiping everything inside your build directory, reconfigure, recompile and install. In your build directory do:

rm -r *
cmake ..
make -j8
sudo make install

**Note** that this is using "rm" with a wildcard, which will remove everything in the current directory.

**Comment by baibing7713661** [comment]
Dear Dari,
Thanks and this time it work out, after changing the $PATH to the new build. 

Cheers, Bing

**Comment by baibing7713661** [comment]
<img width="1165" alt="qq20171102-175450 2x" src="https://user-images.githubusercontent.com/21249922/32339080-f2e0dade-bff6-11e7-8496-b6c80f22abcd.png">
Just one more question, I could open relion on the home directory but not in a deep directory where my data is localized as attached. Is there a issue there?

Bing

**Comment by dkimanius** [comment]
Do you have write-privileges in that directory? Run "touch test.file" and check if the file pops up there.

**Comment by baibing7713661** [comment]
I have the write-previlege and it works now by adding "sudo relion"
