### ISSUE TITLE
Problems running MPI CPU job

### ISSUE THREAD

**Issue by craigyk** [3dem/relion#301]
I've been getting a lot more errors running Relion 2.1b1 with MPI over multiple nodes.  Aside from the zero weights issue others have mentioned, I'm also seeing segmentation faults with the following spit out a lot by Relion prior to the crash:

> halfset= 0 my_halfset= 2 part_id= 2430

Checking the code, I noticed that this should have been accompanied by an exception that print 'BUG!', but I do not see this anywhere in the output.  I can't follow what the code is doing yet, but I do wonder if the call to

>int halfset = DIRECT_A2D_ELEM(exp_metadata, metadata_offset + ipart, METADATA_NR_SIGN);

might be a problem?  The index arithmetic 

> metadata_offset + ipart

 looks suspicious.

Here is the backtrace as spit out by OpenMPI?

> [exanode-4-38:91039] Signal: Segmentation fault (11)
[exanode-4-38:91039] Signal code: Address not mapped (1)
[exanode-4-38:91039] Failing at address: 0x48
[exanode-4-38:91039] [ 0] /usr/lib64/libpthread.so.0(+0xf370)[0x7f619746c370]
[exanode-4-38:91039] [ 1] /usr/lib64/libstdc++.so.6(_ZNSsC1ERKSs+0x1b)[0x7f6197c4ff4b]
[exanode-4-38:91039] [ 2] /home/exacloud/lustre1/users/yoshiokc/sw/relion/0.2.1/lib/librelion_lib.so(_ZN11RelionErrorC1ERKS_+0x1f)[0x7f61a20b6b2f]
[exanode-4-38:91039] [ 3] /home/exacloud/lustre1/users/yoshiokc/sw/relion/0.2.1/lib/librelion_lib.so(_ZN11MlOptimiser24expectationSomeParticlesEll+0x12e0)[0x7f61a209d1f0]
[exanode-4-38:91039] [ 4] /home/exacloud/lustre1/users/yoshiokc/sw/relion/0.2.1/lib/librelion_lib.so(_ZN14MlOptimiserMpi11expectationEv+0x13e4)[0x7f61a216f2c4]
[exanode-4-38:91039] [ 5] /home/exacloud/lustre1/users/yoshiokc/sw/relion/0.2.1/lib/librelion_lib.so(_ZN14MlOptimiserMpi7iterateEv+0x96)[0x7f61a217b6c6]
[exanode-4-38:91039] [ 6] /home/exacloud/lustre1/users/yoshiokc/sw/relion/0.2.1/bin/relion_refine_mpi(main+0x69)[0x402d59]
[exanode-4-38:91039] [ 7] /usr/lib64/libc.so.6(__libc_start_main+0xf5)[0x7f61970bdb35]
[exanode-4-38:91039] [ 8] /home/exacloud/lustre1/users/yoshiokc/sw/relion/0.2.1/bin/relion_refine_mpi[0x402ebf]
[exanode-4-38:91039] *** End of error message ***

**Comment by fangdazhuzhu** [comment]
I have the same question as your, if you have solved this question,please reply to me,thanks
