### ISSUE TITLE
RUNNING CTFFIND in Relion-run as root issue

### ISSUE THREAD

**Issue by baibing7713661** [3dem/relion#302]
<img width="600" alt="qq20171103-105859 2x" src="https://user-images.githubusercontent.com/21249922/32368463-059e03e2-c086-11e7-9e54-fb8573ee164c.png">

I am running CTFFIND in relion for the data stored in a hard disk which I could only access through /media/admin. A note pop up during running indicating that mpirun is attempting to run as root which is discouraged. I am running relion in a separate hard disk as below. So how can I run in this hard disk without go through root? Or adding the --allow-run-as-root to the cmd line as suggested?
cd media/admin/536aeb98-2abe-44d0-a74f-9c758e5423c8/

**Comment by biochem-fan** [comment]
Bad setup.
