### ISSUE TITLE
relion error with GPU acceleration

### ISSUE THREAD

**Issue by munanshaik** [3dem/relion#303]
Hi, 
I am new to relion please help me.
I am tried to run 2D classification with 100k particles. I have 4 GPU which I access through ssh from my linux workstation. While I am tried to run I am getting error.
I am running using GUI but the command is here-
`which relion_refine_mpi` --o Class2D/job111/run --i Select/job107/particles.star --dont_combine_weights_via_disc --pool 30 --ctf  --iter 25 --tau2_fudge 2 --particle_diameter 300 --K 100 --flatten_solvent  --zero_mask  --oversampling 1 --psi_step 12 --offset_range 5 --offset_step 2 --norm --scale  --j 1 --gpu "" 

the error is below. Is anyobne is familiar with this error. I tried to reboot the GPU box and it run one job and again giving the same error.
Thanks in advanced.

Munan

ERROR: unknown error in /programs/x86_64-linux/relion/2.1b1_cu8.0/src/gpu_utils/cuda_projector.cu at line 126 (error-code 30)
[bc-gpu1:01501] *** Process received signal ***
[bc-gpu1:01501] Signal: Segmentation fault (11)
[bc-gpu1:01501] Signal code:  (-6)
[bc-gpu1:01501] Failing at address: 0x82ab000005dd
[bc-gpu1:01501] [ 0] /lib64/libpthread.so.0(+0xf5e0)[0x2b37f434a5e0]
[bc-gpu1:01501] [ 1] /lib64/libpthread.so.0(raise+0x2b)[0x2b37f434a4ab]
[bc-gpu1:01501] [ 2] /programs/x86_64-linux/relion/2.1b1_cu8.0/lib/librelion_gpu_util.so(_ZN13CudaProjector9setMdlDimEiiiiiii+0x5bb)[0x2b37f31f420b]
[bc-gpu1:01501] [ 3] /programs/x86_64-linux/relion/2.1b1_cu8.0/lib/librelion_gpu_util.so(_ZN14MlDeviceBundle22setupFixedSizedObjectsEv+0x252)[0x2b37f31fbc52]
[bc-gpu1:01501] [ 4] /programs/x86_64-linux/relion/2.1b1_cu8.0/lib/librelion_lib.so(_ZN14MlOptimiserMpi11expectationEv+0x118d)[0x2b37e93c944d]
[bc-gpu1:01501] [ 5] /programs/x86_64-linux/relion/2.1b1_cu8.0/lib/librelion_lib.so(_ZN14MlOptimiserMpi7iterateEv+0x96)[0x2b37e93d74f6]
[bc-gpu1:01501] [ 6] /programs/x86_64-linux/relion/2.1b1_cu8.0/bin/relion_refine_mpi(main+0x69)[0x40a3a9]
[bc-gpu1:01501] [ 7] /lib64/libc.so.6(__libc_start_main+0xf5)[0x2b37f4578c05]
[bc-gpu1:01501] [ 8] /programs/x86_64-linux/relion/2.1b1_cu8.0/bin/relion_refine_mpi[0x40a511]
[bc-gpu1:01501] *** End of error message ***
ERROR: unknown error in /programs/x86_64-linux/relion/2.1b1_cu8.0/src/gpu_utils/cuda_projector.cu at line 126 (error-code 30)
[bc-gpu1:01504] *** Process received signal ***
[bc-gpu1:01504] Signal: Segmentation fault (11)
[bc-gpu1:01504] Signal code:  (-6)
[bc-gpu1:01504] Failing at address: 0x82ab000005e0
[bc-gpu1:01504] [ 0] /lib64/libpthread.so.0(+0xf5e0)[0x2ae487ae55e0]
[bc-gpu1:01504] [ 1] /lib64/libpthread.so.0(raise+0x2b)[0x2ae487ae54ab]
[bc-gpu1:01504] [ 2] /programs/x86_64-linux/relion/2.1b1_cu8.0/lib/librelion_gpu_util.so(_ZN13CudaProjector9setMdlDimEiiiiiii+0x5bb)[0x2ae48698f20b]
[bc-gpu1:01504] [ 3] /programs/x86_64-linux/relion/2.1b1_cu8.0/lib/librelion_gpu_util.so(_ZN14MlDeviceBundle22setupFixedSizedObjectsEv+0x252)[0x2ae486996c52]
[bc-gpu1:01504] [ 4] /programs/x86_64-linux/relion/2.1b1_cu8.0/lib/librelion_lib.so(_ZN14MlOptimiserMpi11expectationEv+0x118d)[0x2ae47cb6444d]
[bc-gpu1:01504] [ 5] /programs/x86_64-linux/relion/2.1b1_cu8.0/lib/librelion_lib.so(_ZN14MlOptimiserMpi7iterateEv+0x96)[0x2ae47cb724f6]
[bc-gpu1:01504] [ 6] /programs/x86_64-linux/relion/2.1b1_cu8.0/bin/relion_refine_mpi(main+0x69)[0x40a3a9]
[bc-gpu1:01504] [ 7] /lib64/libc.so.6(__libc_start_main+0xf5)[0x2ae487d13c05]
[bc-gpu1:01504] [ 8] /programs/x86_64-linux/relion/2.1b1_cu8.0/bin/relion_refine_mpi[0x40a511]
[bc-gpu1:01504] *** End of error message ***
ERROR: unknown error in /programs/x86_64-linux/relion/2.1b1_cu8.0/src/gpu_utils/cuda_projector.cu at line 126 (error-code 30)
[bc-gpu1:01503] *** Process received signal ***
[bc-gpu1:01503] Signal: Segmentation fault (11)
[bc-gpu1:01503] Signal code:  (-6)
[bc-gpu1:01503] Failing at address: 0x82ab000005df
[bc-gpu1:01503] [ 0] /lib64/libpthread.so.0(+0xf5e0)[0x2acbefc125e0]
[bc-gpu1:01503] [ 1] /lib64/libpthread.so.0(raise+0x2b)[0x2acbefc124ab]
[bc-gpu1:01503] [ 2] /programs/x86_64-linux/relion/2.1b1_cu8.0/lib/librelion_gpu_util.so(_ZN13CudaProjector9setMdlDimEiiiiiii+0x5bb)[0x2acbeeabc20b]
[bc-gpu1:01503] [ 3] /programs/x86_64-linux/relion/2.1b1_cu8.0/lib/librelion_gpu_util.so(_ZN14MlDeviceBundle22setupFixedSizedObjectsEv+0x252)[0x2acbeeac3c52]
[bc-gpu1:01503] [ 4] /programs/x86_64-linux/relion/2.1b1_cu8.0/lib/librelion_lib.so(_ZN14MlOptimiserMpi11expectationEv+0x118d)[0x2acbe4c9144d]
[bc-gpu1:01503] [ 5] /programs/x86_64-linux/relion/2.1b1_cu8.0/lib/librelion_lib.so(_ZN14MlOptimiserMpi7iterateEv+0x96)[0x2acbe4c9f4f6]
[bc-gpu1:01503] [ 6] /programs/x86_64-linux/relion/2.1b1_cu8.0/bin/relion_refine_mpi(main+0x69)[0x40a3a9]
[bc-gpu1:01503] [ 7] /lib64/libc.so.6(__libc_start_main+0xf5)[0x2acbefe40c05]
[bc-gpu1:01503] [ 8] /programs/x86_64-linux/relion/2.1b1_cu8.0/bin/relion_refine_mpi[0x40a511]
[bc-gpu1:01503] *** End of error message ***
ERROR: unknown error in /programs/x86_64-linux/relion/2.1b1_cu8.0/src/gpu_utils/cuda_projector.cu at line 126 (error-code 30)
[bc-gpu1:01502] *** Process received signal ***
[bc-gpu1:01502] Signal: Segmentation fault (11)
[bc-gpu1:01502] Signal code:  (-6)
[bc-gpu1:01502] Failing at address: 0x82ab000005de
[bc-gpu1:01502] [ 0] /lib64/libpthread.so.0(+0xf5e0)[0x2b8667dd05e0]
[bc-gpu1:01502] [ 1] /lib64/libpthread.so.0(raise+0x2b)[0x2b8667dd04ab]
[bc-gpu1:01502] [ 2] /programs/x86_64-linux/relion/2.1b1_cu8.0/lib/librelion_gpu_util.so(_ZN13CudaProjector9setMdlDimEiiiiiii+0x5bb)[0x2b8666c7a20b]
[bc-gpu1:01502] [ 3] /programs/x86_64-linux/relion/2.1b1_cu8.0/lib/librelion_gpu_util.so(_ZN14MlDeviceBundle22setupFixedSizedObjectsEv+0x252)[0x2b8666c81c52]
[bc-gpu1:01502] [ 4] /programs/x86_64-linux/relion/2.1b1_cu8.0/lib/librelion_lib.so(_ZN14MlOptimiserMpi11expectationEv+0x118d)[0x2b865ce4f44d]
[bc-gpu1:01502] [ 5] /programs/x86_64-linux/relion/2.1b1_cu8.0/lib/librelion_lib.so(_ZN14MlOptimiserMpi7iterateEv+0x96)[0x2b865ce5d4f6]
[bc-gpu1:01502] [ 6] /programs/x86_64-linux/relion/2.1b1_cu8.0/bin/relion_refine_mpi(main+0x69)[0x40a3a9]
[bc-gpu1:01502] [ 7] /lib64/libc.so.6(__libc_start_main+0xf5)[0x2b8667ffec05]
[bc-gpu1:01502] [ 8] /programs/x86_64-linux/relion/2.1b1_cu8.0/bin/relion_refine_mpi[0x40a511]
[bc-gpu1:01502] *** End of error message ***
ERROR: unknown error in /programs/x86_64-linux/relion/2.1b1_cu8.0/src/gpu_utils/cuda_projector.cu at line 127 (error-code 30)
ERROR: unknown error in /programs/x86_64-linux/relion/2.1b1_cu8.0/src/gpu_utils/cuda_projector.cu at line 127 (error-code 30)
ERROR: unknown error in /programs/x86_64-linux/relion/2.1b1_cu8.0/src/gpu_utils/cuda_projector.cu at line 127 (error-code 30)

**Comment by mick-t** [comment]
I've been working with Munan on this, when I run his job on 2-GPU's it doesn't happen. Munan tells me that it also works with 3-GPU's. Looks like there an issue with 4-GPU's.

Thanks
Mick Timony HMS

**Comment by bforsbe** [comment]
Uknown erros tend to be becasue you compiled with a gcc or other compiler that is not compatible with CUDA, or that you are trying to use a GPU which is older than what you specified to compile RELION for. What GPUs are you using?

**Comment by mick-t** [comment]
Hi Björn,

They are NVIDIA GeForce GTX 1080 Ti Founders Edition w/ 11GB GDDR5X. This version was built by the SBGrid and I presume it's built properly. Maybe this is a [red herring](https://www.merriam-webster.com/dictionary/red%20herring) as Munan told me last night that his job appears to be now running on 4-GPU's but using a different input file.  I'll update the ticket or close it next week!
