### ISSUE TITLE
Seg fault in 2.0.3 and 2.1

### ISSUE THREAD

**Issue by max1c** [3dem/relion#304]
Command:
mpirun relion_refine_mpi --o Class3D/job129/run --i Select/job119/particles.star --ref PM_1.26_200.mrc --firstiter_cc --dont_combine_weights_via_disc --ini_high 40 --pool 100 --ctf --iter 25 --tau2_fudge 4 --particle_diameter 180 --K 4 --flatten_solvent --zero_mask --strict_highres_exp 4 --oversampling 1 --healpix_order 3 --offset_range 5 --offset_step 2 --sym D2 --norm --scale  --j 4

Error:
"mpirun noticed that process rank 0 with PID 32434 on node c21a-s5 exited on signal 11 (Segmentation fault)."

Backtrace from the 2.1.0 segfault shows that the issue manifests itself during plot generation:
#0  0x00002aaaaabee74f in CDataSet::GetDataPoint(int) () at /relion/2.1.0/relion/src/CPlot2D.h:160
#1  0x00002aaaaabe7c2c in CPlot2D::DrawDataPostScript() () at /relion/2.1.0/relion/src/CPlot2D.cpp:286
#2  0x00002aaaaabe6dfa in CPlot2D::OutputPostScriptPlot(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) () at /relion/2.1.0/relion/src/CPlot2D.cpp:168
#3  0x00002aaaaaecb5c4 in Postprocessing::writeOutput() () at /distapps/relion/2.1.0/relion/src/postprocessing.cpp:806
#4  0x00002aaaaaecee60 in Postprocessing::run() () at /relion/2.1.0/relion/src/postprocessing.cpp:1179
#5  0x000000000040ade3 in main () at /relion/2.1.0/relion/src/apps/postprocess.cpp:34

**Comment by biochem-fan** [comment]
Refine3D should not generate any PDF files.
