### ISSUE TITLE
linking CXX executable  error

### ISSUE THREAD

**Issue by m3105** [3dem/relion#305]
Hi,

I got this error message when trying to install relion

 56%] Linking CXX executable ../../bin/relion_star_compare
../../lib/librelion_lib.so: undefined reference to `FcPatternAddString'
../../lib/librelion_lib.so: undefined reference to `XcursorImageLoadCursor'
../../lib/librelion_lib.so: undefined reference to `XftFontOpenXlfd'
../../lib/librelion_lib.so: undefined reference to `FcPatternAddMatrix'
../../lib/librelion_lib.so: undefined reference to `FcUtf8ToUcs4'
../../lib/librelion_lib.so: undefined reference to `XftTextExtents32'
../../lib/librelion_lib.so: undefined reference to `XftDrawSetClip'
../../lib/librelion_lib.so: undefined reference. to. /`.FcMatrixRotate.'/
lib./.librelion_lib.so/:. .undefined/ libreference/ librelion_lib.soto:  `undefinedFcPatternAddString 'reference

Anyone else got this?

**Comment by bforsbe** [comment]
What output did you get when running the cmake command?

**Comment by m3105** [comment]
Got this output:

BUILD TYPE set to the default type:  'Release'
-- Setting fallback CUDA_ARCH=35
-- Setting cpu precision to double
-- Setting gpu precision to single
-- Using cuda wrapper to compile....
-- Cuda version is >= 7.5 and single-precision build, enable double usage
warning.
-- MPI_INCLUDE_PATH : /usr/local/include
-- MPI_LIBRARIES : /usr/local/lib/libmpi_cxx.so;/usr/local/lib/libmpi.so
-- MPI_CXX_INCLUDE_PATH : /usr/local/include
-- MPI_CXX_LIBRARIES : /usr/local/lib/libmpi_cxx.so;/usr/local/lib/libmpi.so
-- X11 and FLTK were found
-- FLTK_LIBRARIES: /usr/local/lib64/libfltk_images.a;/usr/local/lib64/
libfltk_forms.a;/usr/local/lib64/libfltk.a;/usr/lib64/
libSM.so;/usr/lib64/libICE.so;/usr/lib64/libX11.so;/usr/
lib64/libXext.so;/usr/lib64/libm.so
-- Found FFTW: fftw3
-- FFTW_LIBRARIES: /usr/local/lib64/libfftw3.so
-- Building shared libs (smaller build size and binaries)
-- CMAKE_BINARY_DIR:/home/emwdl1/relion/build
-- added autopick...
-- added autopick_mpi...
-- added ctf_toolbox...
-- added display...
-- added find_tiltpairs...
-- added helix_toolbox...
-- added image_handler...
-- added localsym...
-- added localsym_mpi...
-- added maingui...
-- added manualpick...
-- added mask_create...
-- added particle_polish...
-- added particle_polish_mpi...
-- added particle_reposition...
-- added particle_sort...
-- added particle_sort_mpi...
-- added particle_symmetry_expand...
-- added pipeliner...
-- added postprocess...
-- added postprocess_mpi...
-- added prepare_subtomo...
-- added preprocess...
-- added preprocess_mpi...
-- added project...
-- added reconstruct...
-- added refine...
-- added refine_mpi...
-- added run_ctffind...
-- added run_ctffind_mpi...
-- added run_motioncorr...
-- added run_motioncorr_mpi...
-- added stack_create...
-- added star_combine...
-- added star_compare...
-- added tiltpair_plot...
-- Configuring done
-- Generating done
-- Build files have been written to: /home/emwdl1/relion/build


Melissa

**Comment by bforsbe** [comment]
Your FLTK-installation is built without shared libraries (some of them end with .a rather than .so). You can ask relion to make it's own FLTK-libs, in which case they will be shared libraries. Simply add the flag 
```
-DFORCE_OWN_FLTK=ON
```
to your cmake-command, than build.
