### ISSUE TITLE
new occurrence of WARNING: Exception (ERROR:  02859:   No orientation was found as better than any other. Class3D

### ISSUE THREAD

**Issue by carmensmp** [3dem/relion#306]
After hundreds of "no orientation found..." messages, relion dies with segmentation fault. This problem appears when classifying ~40000 particles with a 376px box. These particles have undergone relion class2d and one previous round of class3d (10 iterations), so in principle centering should not be an issue.

This is relion2.0.4 run under scipion.

Expectation iteration 13 of 20
00115:   000/??? sec ~~(,_,">                                                          [oo]
00116:   WARNING: Exception (ERROR: 
00117:   No orientation was found as better than any other.
00118:   
00119:   A particle image was compared to the reference and resulted in all-zero
00120:   weights (for all orientations). This should not happen, unless your data
00121:   has very special characteristics. This has historically happened for some 
00122:   lower-precision calculations, but multiple fallbacks have since been 
00123:   implemented. Please report this error to the relion developers at 
00124:   
00125:   	         github.com/3dem/relion/issues  
00126:    ) handled by switching to fail-safe mode.

........etc

Then:
02858:   WARNING: Exception (ERROR: 
02859:   No orientation was found as better than any other.
02860:   
02861:   A particle image was compared to the reference and resulted in all-zero
02862:   weights (for all orientations). This should not happen, unless your data
02863:   has very special characteristics. This has historically happened for some 
02864:   lower-precision calculations, but multiple fallbacks have since been 
02865:   implemented. Please report this error to the relion developers at 
02866:   
02867:   	         github.com/3dem/relion/issues  
02868:    ) handled by switching to fail-safe mode.
02869:   11.05/43.83 min ...............~~(,_,">Segmentation fault

**Comment by carmensmp** [comment]
Update: the same run gave no problems in CPU

**Comment by biochem-fan** [comment]
Old version.
