### ISSUE TITLE
Relion could not be activated with non-root user

### ISSUE THREAD

**Issue by baibing7713661** [3dem/relion#307]
I have installed relion 2.1 in the server and try to setup users to use the software. While when type relion with non-root users,  errors below appear and the GUI does not appear. With root user, it runs properly. Any setting for setup this?

No protocol specified
Can't open display: :0

**Comment by bforsbe** [comment]
I think this is a X11-related configuration error. It's not something that relion sets or modifies, as far as I know.

**Comment by baibing7713661** [comment]
Yes, indeed, xhost +, problem solved thanks
