### ISSUE TITLE
Particles normalisation error in 2D classification

### ISSUE THREAD

**Issue by munanshaik** [3dem/relion#312]
Hi, 
I did say yes for normalisation during particle extraction but still my 2D classification run failed using GUI. Around 500k particle box size 300. Any idea what is going on?

thanks, 
Munan

 fn_img= 000011@Extract/job015/32-g4_01727_ali.mrcs bg_avg= -0.0387734 bg_stddev= 0.491625 bg_radius= 137.615
ERROR: It appears that these images have not been normalised to an average background value of 0 and a stddev value of 1. 
 							Note that the average and stddev values for the background are calculated: 
 							(1) for single particles: outside a circle with the particle diameter 
 							(2) for helical segments: outside a cylinder (tube) with the helical tube diameter 
 							You can use the relion_preprocess program to normalise your images 
 							If you are sure you have normalised the images correctly (also see the RELION Wiki), you can switch off this error message using the --dont_check_norm command line option
File: /programs/x86_64-linux/relion/2.0.3_cu8.0/src/ml_optimiser.cpp line: 1669

**Comment by biochem-fan** [comment]
Did you rescale particles during extraction? If so, this is a known bug in RELION.
It will be fixed in the next release.

**Comment by munanshaik** [comment]
No, I didnt rescale the particles during extraction. Running through command line using dont_check_norm seems running fine.

**Comment by domgutier** [comment]
Hello,

I am reprocessing some data and am having the same issue in relion3. Except that I did rescale the particles. So the bug may not have been fixed. Any suggestions?

Best,
Dominique

**Comment by biochem-fan** [comment]
Are you sure you specified correct `Diameter background circle` in particle extraction and `Mask diameter` in classification & refinement? Note that the first is in pixels while the latter is in Angstrom.

**Comment by biochem-fan** [comment]
No response for a long time. Closing.
