### ISSUE TITLE
"Allocate: no space left" error with high memory estimate

### ISSUE THREAD

**Issue by AndyMender** [3dem/relion#313]
We are trying to create a particle stack from a .star file containing 93384 helical particles of dimensions 512x512x1 with `relion_stack_create` and the command fails with the "Allocate: no space left" error. The full traceback is here:
ERROR:
Allocate: no space left
File: /tmp/build/relion/src/multidim_array.h line: 1141

Before that there is the "This will require 1.71799e+10Gb of memory...", which shows the same value regardless of the number of particles selected (limiting the selection to, for instance 30,000 with `head 30000`).

This is done on Debian 6 x86_64 on an HPC cluster node with dedicated resources. The RELION version is 2.1-beta-e7607a8.

**EDIT:** After some digging in the C++ code, I noticed that different dimension variables are used to calculate the value of `Gb`, which is later printed out via `cout`. One of them being a call to `sizeof(RFLOAT)`. Here: https://github.com/3dem/relion/blob/005eac43a0a12b7e6450fd9acb92292b6a29f12a/src/apps/stack_create.cpp 

These dimension variables are also used in the `coreAllocate` function. Could it be that one of the dimension variables contains an absurdly large value? I could probably try to reproduce the error in a VM, but later.

**Comment by bforsbe** [comment]
Sorry for the very late response. 

A rogue z-dim sounds plausible, but it should have stated just before the memory requirement what the dims were. If you still have the file/problem, could you also try 

```
relion_image_handler --i first_mrc_in_the_original_star_file.mrc --stats
```
to display the dims.

**Comment by AndyMender** [comment]
Thank you for the response. The issue "solved itself" by changing the target directory for the output files. The reading is clearly erroneous of course. I think we can close this issue for now.
