### ISSUE TITLE
Relion 2.1 beat-1, 3D initial model not using GPU acceleration

### ISSUE THREAD

**Issue by munanshaik** [3dem/relion#315]
Hi, 
I am trying to run 3D initial model on Relion 2.1 beta-1 version. Even I put yes for GPU but its not using it. Is it a bug?

`which relion_refine_mpi` --o InitialModel/job055/run --sgd  --subset_size 200 --strict_highres_sgd 20 --write_subsets 10 --denovo_3dref --i Select/job053/particles.star --ctf --ctf_phase_flipped --sym C1 --zero_mask --dont_combine_weights_via_disc --pool 60 --iter 1 --particle_diameter 300 --oversampling 1 --healpix_order 1 --offset_range 6 --offset_step 4 --j 1 --gpu ""

Thanks, 
Munan  

Md Munan Shaik, Ph.D

Research Fellow
Boston Children's Hospital,
Harvard Medical School
Center for Life Science
3 Blackfan Circle, 
Boston, MA 02115

**Comment by dkimanius** [comment]
If you look in the refinement output, you might find the self-explanatory warning:

WARNING : Relion was compiled without CUDA of at least version 7.0 - you do NOT have support for GPUs
