### ISSUE TITLE
Relion/2.1b1 3D classification (no orientation was found as better than any other)

### ISSUE THREAD

**Issue by newyorkcrazyfan** [3dem/relion#317]
I was trying to do a 3D classification on about 16K virus particles by imposing icosahedral symmetry. The box size is 192*192. 

mpirun -np 3 `which relion_refine_mpi` --o Class3D/job001/run --i 1.star --ref 1.mrc --dont_combine_weights_via_disc --pool 3 --ctf --ctf_corrected_ref --iter 25 --tau2_fudge 4 --particle_diameter 370 --K 3 --flatten_solvent --zero_mask --oversampling 1 --healpix_order 4 --offset_range 5 --offset_step 1 --sym i4 --norm --scale --gpu "0,0,0:1,1,1" --angpix 2.6

I had the following error msg. 

WARNING: Exception (ERROR: 
No orientation was found as better than any other.

A particle image was compared to the reference and resulted in all-zero
weights (for all orientations). This should not happen, unless your data
has very special characteristics. 

 fn_img= 4259@start.mrcs
 part_id= 1361
 ipart= 0
 op.min_diff2[ipart]= 14435.4
 group_id= 37
 ml_model.scale_correction[group_id]= 1.0029
 exp_significant_weight[ipart]= 0
 exp_max_weight[ipart]= -1
 ml_model.sigma2_noise[group_id]= 
     3e-05
     1e-05
     8e-06
     8e-06
     7e-06
     7e-06
     7e-06
     7e-06
     7e-06
     8e-06
     9e-06
     1e-05
     1e-05
     1e-05
     1e-05
     1e-05
     1e-05
     2e-05
     2e-05
     2e-05
     2e-05
     2e-05
     2e-05
     2e-05
     2e-05
     1e-05
     1e-05
     1e-05
     1e-05
     9e-06
     8e-06
     7e-06
     6e-06
     6e-06
     6e-06
     6e-06
     6e-06
     7e-06
     8e-06
     8e-06
     9e-06
     9e-06
     9e-06
     9e-06
     8e-06
     7e-06
     6e-06
     6e-06
     6e-06
     6e-06
     7e-06
     7e-06
     7e-06
     7e-06
     7e-06
     7e-06
     7e-06
     6e-06
     6e-06
     6e-06
     6e-06
     6e-06
     6e-06
     6e-06
     6e-06
     6e-06
     6e-06
     6e-06
     6e-06
     6e-06
     6e-06
     6e-06
     6e-06
     6e-06
     6e-06
     6e-06
     6e-06
     6e-06
     6e-06
     6e-06
     6e-06
     6e-06
     6e-06
     6e-06
     6e-06
     6e-06
     6e-06
     6e-06
     6e-06
     6e-06
     6e-06
     6e-06
     6e-06
     6e-06
     6e-06
     6e-06
     6e-06

Thanks in advance for any help.

Yue

**Comment by biochem-fan** [comment]
Old version.
