### ISSUE TITLE
AutoPick Error! Need Help!

### ISSUE THREAD

**Issue by xiaoshagua3** [3dem/relion#319]
I am running the Autopick of relion2.1 beta to pick particles, but there is an error I can not solve.

my command is as follows:

job_type == 4
is_continue == false
Pixel size in micrographs (A) == -1
Pixel size in references (A) == -1
Are References CTF corrected? == Yes
Or use Gaussian blob? == No
Ignore CTFs until first peak? == No
References have inverted contrast? == Yes
Pick 2D helical segments? == No
Submit to queue? == No
Read FOM maps? == Yes
Write FOM maps? == No
Input micrographs for autopick: == Select/job031/micrographs.star
References: == Select/job024/class_averages.star
Gaussian peak value == 0.1
Which GPUs to use: == 2
Number of asymmetrical units: == 1
Helical rise (A): == -1
Maximum curvature (kappa):  == 0.1
Minimum length (A):  == -1
Tube diameter (A):  == 200
Highpass filter (A) == -1
Lowpass filter references (A) == 20
Maximum stddev noise: == 1.5
Minimum dedicated cores per node: == 1
Minimum inter-particle distance (A): == 120
Number of MPI procs: == 1
Additional arguments: == 
Mask diameter (A) == 200
Angular sampling (deg) == 5
Queue submit command: == qsub
Standard submission script: == ž8
Queue name:  == openmpi
Shrink factor: == 0
Picking threshold: == 0.6
Use GPU acceleration? == Yes

+ Using (micrograph) pixel size from input STAR file of 0.92 Angstroms
 + Run autopicking on the following micrographs: 
    * MotionCorr/job002/micrographs/12_01_2017_0106.mrc
    * MotionCorr/job002/micrographs/12_01_2017_0108.mrc
    * MotionCorr/job002/micrographs/12_01_2017_0112.mrc
    * MotionCorr/job002/micrographs/12_01_2017_0113.mrc
    * MotionCorr/job002/micrographs/12_01_2017_0115.mrc
    * MotionCorr/job002/micrographs/12_01_2017_0127.mrc

RROR: 
Cannot read file AutoPick/job032/micrographs/12_01_2017_0106_autopick_stddevNoise.spi It does not exist
File: /usr/local/relion-2-source/src/image.h line: 157

I checked the "relion-2-source/src/image.h line: 157": switch (mode)
		{
		case WRITE_READONLY:
			if (!exist)
				REPORT_ERROR((std::string) "Cannot read file " + fileName + " It does not exist" );
			wmChar = "r";
			break;
 but still do not know what happened? I am sure there is no problem in my micrographs and templates for autopick.

How to solve it? Thank you so much!

**Comment by biochem-fan** [comment]
You set `Read FOM maps?` to `Yes` without setting `Write FOM maps` to `Yes` before.
Try running it with both set to `No`.

**Comment by xiaoshagua3** [comment]
Thank you so much, biochem-fan! I tried to set to both NO, and it works!
