### ISSUE TITLE
Relion 2.1b1 2D classification resulted in all zero weights (for all orientations)

### ISSUE THREAD

**Issue by eariascib** [3dem/relion#320]
Hello,

I am running relion 2.1b1 on linux mint 18.1. The machine has two NVIDIA 1080Ti and CUDA8 installed.

Yesterday I started a 2D classification run (~140,000 144x144 particles):
_`which relion_refine_mpi` --continue Class2D/job043/run_it013_optimiser.star --o Class2D/job043/run_ct13 --dont_combine_weights_via_disc --no_parallel_disc_io --preread_images  --pool 50 --iter 25 --tau2_fudge 2 --particle_diameter 220 --oversampling 1 --psi_step 12 --offset_range 5 --offset_step 2 --j 4 --gpu ""_

and in the iteration 15/25 it gave the following error message:
WARNING: Exception (ERROR: 
No orientation was found as better than any other.

A particle image was compared to the reference and resulted in all-zero
weights (for all orientations). This should not happen, unless your data
has very special characteristics. This has historically happened for some 
lower-precision calculations, but multiple fallbacks have since been 
implemented. Please report this error to the relion developers at 

             github.com/3dem/relion/issues  
 ) handled by switching to fail-safe mode.

The 2D averages from iteration #14 look good, but the program stops there. Do you know what can be causing this issue?

Thank you very much for your help,
Ernesto.

**Comment by bforsbe** [comment]
I'm pretty sure we have the fix in the 2.1 stable candidate. It'll be out after the final testing, which is underway. In other words; the next release should not produce this error. 

But if this is really the command, I'm a bit confused, because you don't specify the number of classes....?

**Comment by craigyk** [comment]
@bforsbe 

Any thoughts on making this release candidate available for testing?  I know this particular problem is vexing a _lot_ of users at the moment even thought it isn't being widely reported.

**Comment by bforsbe** [comment]
We will not release that version for testing. Rather, it will be released as a stable release as soon as we have verified it completely. That will be very soon.

**Comment by eariascib** [comment]
Thank you very much for the information. I will update to the new  
relion version as soon as it is available.

Regarding the command, I launched the job from the GUI and I copied  
the last command from the note.txt file, but I have just realized that  
that's the the command that it ran when I tried to resume the 2D  
classification. This is the whole content of the file:

  ++++ Executing new job on Tue Dec  5 23:05:08 2017
  ++++ with the following command(s):
`which relion_refine_mpi` --o Class2D/job043/run --i  
./Extract/job042/particles.star --dont_combine_weights_via_disc  
--no_parallel_disc_io --preread_images  --pool 50 --ctf  --iter 25  
--tau2_fudge 2 --particle_diameter 220 --K 200 --flatten_solvent   
--zero_mask  --oversampling 1 --psi_step 12 --offset_range 5  
--offset_step 2 --norm --scale  --j 4 --gpu ""
  ++++

  ++++ Executing new job on Wed Dec  6 11:50:07 2017
  ++++ with the following command(s):
`which relion_refine_mpi` --continue  
Class2D/job043/run_it013_optimiser.star --o Class2D/job043/run_ct13  
--dont_combine_weights_via_disc --no_parallel_disc_io --preread_images  
  --pool 50 --iter 25 --tau2_fudge 2 --particle_diameter 220  
--oversampling 1 --psi_step 12 --offset_range 5 --offset_step 2 --j 4  
--gpu ""
  ++++

Thank you again for all your help,
Ernesto.


Quoting Björn Forsberg <notifications@github.com>:

**Comment by biochem-fan** [comment]
Please try 3.0 and report if it persists.
