### ISSUE TITLE
Another "ERROR:  No orientation was found as better than any other" in 3D classification

### ISSUE THREAD

**Issue by alexandredurand** [3dem/relion#322]
Hi,

Another occurrence of the following error:

WARNING: Exception (ERROR: 
No orientation was found as better than any other.

A particle image was compared to the reference and resulted in all-zero
weights (for all orientations). This should not happen, unless your data
has very special characteristics. This has historically happened for some 
lower-precision calculations, but multiple fallbacks have since been 
implemented. Please report this error to the relion developers at 

	         github.com/3dem/relion/issues  
 ) handled by switching to fail-safe mode.

This is obtained using Relion 2.1 beta1 with dual GTX1080Ti running. The command used is the following:

`which relion_refine_mpi` --o Class3D/job209/run --i ./Refine3D/job198/run_data.star --ref ./Refine3D/job195/run_class001.mrc --ini_high 60 --dont_combine_weights_via_disc --scra
tch_dir /tmp --pool 100 --ctf --ctf_corrected_ref --iter 25 --tau2_fudge 4 --particle_diameter 750 --K 10 --flatten_solvent --zero_mask --strict_highres_exp 12 --solvent_mask Sho
rt_mask_Refine1/mask_172.mrc --oversampling 1 --healpix_order 2 --offset_range 5 --offset_step 2 --sym C1 --norm --scale  --j 3 --gpu "0:1"

Any fix for this?
Thanks

Alexandre

**Comment by biochem-fan** [comment]
Old version.
