### ISSUE TITLE
Install errors of 1215 updated version

### ISSUE THREAD

**Issue by cryoem2** [3dem/relion#323]
I met an error while installing the new version of relion. I use the same environment as before. The error as follows:
[ 45%] Linking CXX shared library ../../lib/librelion_lib.so
[ 45%] Built target relion_lib
Scanning dependencies of target stack_create
Scanning dependencies of target star_compare
Scanning dependencies of target run_ctffind_mpi
Scanning dependencies of target run_ctffind
[ 45%] Building CXX object src/apps/CMakeFiles/star_compare.dir/star_compare.cpp.o
[ 46%] Building CXX object src/apps/CMakeFiles/stack_create.dir/stack_create.cpp.o
[ 47%] Building CXX object src/apps/CMakeFiles/run_ctffind.dir/run_ctffind.cpp.o
[ 47%] Building CXX object src/apps/CMakeFiles/run_ctffind_mpi.dir/run_ctffind_mpi.cpp.o
[ 48%] Linking CXX executable ../../bin/relion_run_ctffind
../../lib/librelion_gpu_util.so: undefined reference to `__svml_log2'
../../lib/librelion_gpu_util.so: undefined reference to `_intel_fast_memcpy'
../../lib/librelion_gpu_util.so: undefined reference to `__svml_sincos2'
../../lib/librelion_gpu_util.so: undefined reference to `_intel_fast_memset'
../../lib/librelion_gpu_util.so: undefined reference to `_intel_fast_memmove'
../../lib/librelion_gpu_util.so: undefined reference to `_intel_fast_memcmp'
../../lib/librelion_gpu_util.so: undefined reference to `__intel_sse2_strcat'
../../lib/librelion_gpu_util.so: undefined reference to `__intel_sse2_strlen'
../../lib/librelion_gpu_util.so: undefined reference to `__intel_sse2_strncpy'
../../lib/librelion_gpu_util.so: undefined reference to `__svml_log2_mask'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/relion_run_ctffind] Error 1
make[1]: *** [src/apps/CMakeFiles/run_ctffind.dir/all] Error 2

**Comment by cryoem2** [comment]
I notice that this version seems not support intel icc and GPU at the same time.

**Comment by eriklindahl** [comment]
We might try to fix it, but for now there is no extra benefit whatsoever from using the intel compiler for the GPU version.

**Comment by smsaladi** [comment]
@eriklindahl This is a useful comment. Any chance it could be added to the wiki/other help material? It's pretty hidden down in the issue tracker here.

**Comment by smsaladi** [comment]
Perhaps on this page?

https://www2.mrc-lmb.cam.ac.uk/relion/index.php?title=Benchmarks_%26_computer_hardware

**Comment by ziqin** [comment]
Using `icpc` itself as linker, or adding some flags to link intel's libraries may solve such link errors.

**Comment by biochem-fan** [comment]
Old version.
