### ISSUE TITLE
rpath error in 'relion' after 'make install'

### ISSUE THREAD

**Issue by colinpalmer** [3dem/relion#324]
I've just installed RELION 2.1.0 and noticed a problem with the rpath setup in the main `relion` program.

I followed the [instructions for specifying an installation location](http://www2.mrc-lmb.cam.ac.uk/relion/index.php/Download_%26_install#Specifying_an_installation_location) and used 

    cmake -DCMAKE_INSTALL_PREFIX=/path/to/install/dir/ ..

to set the installation directory. The build and installation both run without errors and everything seems to work initially, but later, after clearing out the contents of the `build` directory, `relion` failed with a library error:

    error while loading shared libraries: librelion_lib.so: cannot open shared object file: No such file or directory

Using `ldd` and `readelf`, I found that the rpath for `relion` was still pointing to the copy of `lib/` in the build directory:

    $ readelf -d relion
    ...
    0x000000000000000f (RPATH)              Library rpath: [<path to build dir>/relion_src/build/lib:...]
    ...

All of the other binaries have the correct rpath, which has been changed to point to `lib/` in the install directory:

    $ readelf -d relion_refine
    ...
    0x000000000000000f (RPATH)              Library rpath: [<path to install dir>/relion/2.1.0/lib:...]
    ...

In the output from `make install`, there's a line like

    -- Set runtime path of ".../relion/2.1.0/bin/relion_image_handler" to ".../relion/2.1.0/lib:..."

for most of the binaries, but not for `relion`, so it looks like `make install` is just missing an instruction to do the same thing for `relion` as it does for all the rest.

I've fixed my build for now by using `patchelf` to correct the rpath, but I hope it might be a simple fix to make this automatic in future versions?

**Comment by bforsbe** [comment]
"relion" is really just a copy of relion_maingui. It might be that we are not setting the rpath of it like we are the original binary. What do you find for the binary "relion_maingui"?

**Comment by colinpalmer** [comment]
`relion_maingui` has the correct rpath:

    $ readelf -d relion_maingui | grep path
    0x000000000000000f (RPATH)              Library rpath: [.../relion/2.1.0/lib:.../cuda/8.0/lib64:.../openmpi/1.6.5/64/lib:.../fltk/1.3.2/lib]

**Comment by bforsbe** [comment]
Ok, then it's clear what needs to change. I can get back to you with a fix if you want it, although you seem to have worked around it already.

**Comment by colinpalmer** [comment]
No, I don't need a fix for now, thanks.
