### ISSUE TITLE
Normalise 3D particles using relion_preprocess

### ISSUE THREAD

**Issue by ruiyanpurdue** [3dem/relion#325]
Hi, 
I have a dataset of 3D particles and I want to do sub-tomogram averaging using Relion 2.1. 
Since those 3D particles may not be normalised in a way Relion prefers, I am trying to normalise them using relion_preprocess.  
When I use a command:
relion_preprocess --operate_on input_3D_subtomo.star  --operate_out output_3D_subtomo --norm --bg_radius 75 --white_dust -1 --black_dust -1 --invert_contrast
An error occurs:
ERROR %% calculateBackgroundRamp is not implemented for 3D data!
File: /apps/relion/relion/src/image.cpp line: 272
I have to add --no_ramp to avoid the error. Is this a correct way to normalise 3D particles?

I am also trying to project sub-tomograms along Z to generate 2D particles using --project3d, but the output makes me confused when I run the following command:
relion_preprocess --operate_on input_3D_subtomo.star  --operate_out output_3D_subtomo --norm --bg_radius 75 --white_dust -1 --black_dust -1 --invert_contrast --no_ramp --project3d
12.38/12.38 min ............................................................~~(,_,">
 Done writing to output_3D_subtomo.mrcs
 Also written a STAR file with the image names as output_3D_subtomo.star
 Done preprocessing!

I can find individal normalised 3D particles in my directory, but I cannot find a star file which corresponds to these normalised 3D particles.
It seems that output_3D_subtomo.mrcs and output_3D_subtomo.star are files for the projected 2D particles, but I cannot find output_3D_subtomo.mrcs when the preprocessing is done. 

Any solution for this?
Thanks.
Rui

**Comment by biochem-fan** [comment]
3D subtomo pipeline is being rewritten.
