### ISSUE TITLE
relion_autopick does not check for existence of all files in input star at beginning of job

### ISSUE THREAD

**Issue by olibclarke** [3dem/relion#326]
Hi,

Relion_autopick should check for the existence of all micrographs referenced in the input star file before starting picking. As it is, it processes the micrographs sequentially, and if run with mpi it dies with an uninformative mpi error, and if run directly with relion_autopick it aborts when it encounters a reference to a micrograph that does not exist. 

I would suggest that the default behavior should be to check for the existence of all referenced micrographs at the start of the job, or to default to skipping those that don't exist (and printing a warning for each). Alternatively, having a --dry_run option that just simulates file i/o and checks that each mrc is readable would be another option.

Cheers
Oli

**Comment by pradeepg15** [comment]
Hi Oli,

I have been getting errors during autopick. Could you please help me with this?

AutoPicker::initialise ERROR: either provide rlnReferenceImage or rlnImageName in the reference STAR file!
File: /home/novakm/relion/src/autopicker.cpp line: 326

Best regards,
Pradeep

**Comment by olibclarke** [comment]
Hi Pradeep

What does the header of your input star file look like - is it lacking the mentioned column names?

Cheers
Oli

**Comment by pradeepg15** [comment]
Hi Oli,

Thanks for the reply, but have it fixed now. Something was wrong with the path!.


Cheers
Pradeep
