### ISSUE TITLE
Error during Refine3D

### ISSUE THREAD

**Issue by munanshaik** [3dem/relion#327]
During refine run with GPU

`which relion_refine_mpi` --o Refine3D/job287/run --auto_refine --split_random_halves --i Refine3D/job281/run_data.star --ref Refine3D/job281/run_class001.mrc --firstiter_cc --dont_combine_weights_via_disc --pool 100 --ctf --ctf_corrected_ref --particle_diameter 275 --flatten_solvent --zero_mask --solvent_mask MaskCreate/job225/mask.mrc --oversampling 1 --healpix_order 3 --auto_local_healpix_order 3 --offset_range 5 --offset_step 2 --sym C1 --low_resol_join_halves 40 --norm --scale  --j 1 --gpu ""
  

1: MPI_ERR_TRUNCATE: message truncated
  1: MPI_ERR_TRUNCATE: message truncated
terminate called after throwing an instance of 'RelionError'
[bc-gpu1:31213] *** Process received signal ***
[bc-gpu1:31213] Signal: Aborted (6)
[bc-gpu1:31213] Signal code:  (-6)
[bc-gpu1:31213] [ 0] /lib64/libpthread.so.0(+0xf5e0)[0x2b088fdb45e0]
[bc-gpu1:31213] [ 1] /lib64/libc.so.6(gsignal+0x37)[0x2b088fff61f7]
[bc-gpu1:31213] [ 2] /lib64/libc.so.6(abort+0x148)[0x2b088fff78e8]
[bc-gpu1:31213] [ 3] /lib64/libstdc++.so.6(_ZN9__gnu_cxx27__verbose_terminate_handlerEv+0x165)[0x2b088f5e5ac5]
[bc-gpu1:31213] [ 4] /lib64/libstdc++.so.6(+0x5ea36)[0x2b088f5e3a36]
[bc-gpu1:31213] [ 5] /lib64/libstdc++.so.6(+0x5ea63)[0x2b088f5e3a63]
[bc-gpu1:31213] [ 6] /lib64/libstdc++.so.6(+0x5ec83)[0x2b088f5e3c83]
[bc-gpu1:31213] [ 7] /programs/x86_64-linux/relion/2.1b1_cu8.0/lib/librelion_lib.so(_ZN7MpiNode16report_MPI_ERROREi+0x119)[0x2b0884f6c0f9]
[bc-gpu1:31213] *** End of error message ***

**Comment by bforsbe** [comment]
how many MPI-ranks ere you using? That is, what was the mpirun-command before the above stated command?

**Comment by munanshaik** [comment]
Hi, 
the mpirun command was "mpirun -n 5"

thanks, 
Munan

**Comment by biochem-fan** [comment]
Old version.
