### ISSUE TITLE
Relion Installation Error During 'make'

### ISSUE THREAD

**Issue by LRiley1** [3dem/relion#329]
I am trying to install relion and keep generating an error during the 'make' step and I'm unsure what the cause of the problem is, after I run 'make -j4' I get this error:

CMake Error at relion_gpu_util_generated_cuda_backprojector.cu.o.cmake:266 (message):
  Error generating file
  /home/relion/build/src/apps/CMakeFiles/relion_gpu_util.dir/__/gpu_utils/./relion_gpu_util_generated_cuda_backprojector.cu.o

src/apps/CMakeFiles/relion_gpu_util.dir/build.make:664: recipe for target 'src/apps/CMakeFiles/relion_gpu_util.dir/__/gpu_utils/relion_gpu_util_generated_cuda_backprojector.cu.o' failed
make[2]: *** [src/apps/CMakeFiles/relion_gpu_util.dir/__/gpu_utils/relion_gpu_util_generated_cuda_backprojector.cu.o] Error 1
make[2]: *** Waiting for unfinished jobs....
/usr/include/string.h: In function ‘void* __mempcpy_inline(void*, const void*, size_t)’:
/usr/include/string.h:652:42: error: ‘memcpy’ was not declared in this scope
   return (char *) memcpy (__dest, __src, __n) + __n;
                                          ^
CMake Error at relion_gpu_util_generated_helper.cu.o.cmake:266 (message):
  Error generating file
  /home/relion/build/src/apps/CMakeFiles/relion_gpu_util.dir/__/gpu_utils/cuda_kernels/./relion_gpu_util_generated_helper.cu.o

src/apps/CMakeFiles/relion_gpu_util.dir/build.make:1392: recipe for target 'src/apps/CMakeFiles/relion_gpu_util.dir/__/gpu_utils/cuda_kernels/relion_gpu_util_generated_helper.cu.o' failed
make[2]: *** [src/apps/CMakeFiles/relion_gpu_util.dir/__/gpu_utils/cuda_kernels/relion_gpu_util_generated_helper.cu.o] Error 1
/usr/include/string.h: In function ‘void* __mempcpy_inline(void*, const void*, size_t)’:
/usr/include/string.h:652:42: error: ‘memcpy’ was not declared in this scope
   return (char *) memcpy (__dest, __src, __n) + __n;
                                          ^
CMake Error at relion_gpu_util_generated_cuda_helper_functions.cu.o.cmake:266 (message):
  Error generating file
  /home/relion/build/src/apps/CMakeFiles/relion_gpu_util.dir/__/gpu_utils/./relion_gpu_util_generated_cuda_helper_functions.cu.o

src/apps/CMakeFiles/relion_gpu_util.dir/build.make:429: recipe for target 'src/apps/CMakeFiles/relion_gpu_util.dir/__/gpu_utils/relion_gpu_util_generated_cuda_helper_functions.cu.o' failed
make[2]: *** [src/apps/CMakeFiles/relion_gpu_util.dir/__/gpu_utils/relion_gpu_util_generated_cuda_helper_functions.cu.o] Error 1
/usr/include/string.h: In function ‘void* __mempcpy_inline(void*, const void*, size_t)’:
/usr/include/string.h:652:42: error: ‘memcpy’ was not declared in this scope
   return (char *) memcpy (__dest, __src, __n) + __n;
                                          ^
CMake Error at relion_gpu_util_generated_cuda_ml_optimiser.cu.o.cmake:266 (message):
  Error generating file
  /home/relion/build/src/apps/CMakeFiles/relion_gpu_util.dir/__/gpu_utils/./relion_gpu_util_generated_cuda_ml_optimiser.cu.o

src/apps/CMakeFiles/relion_gpu_util.dir/build.make:1129: recipe for target 'src/apps/CMakeFiles/relion_gpu_util.dir/__/gpu_utils/relion_gpu_util_generated_cuda_ml_optimiser.cu.o' failed
make[2]: *** [src/apps/CMakeFiles/relion_gpu_util.dir/__/gpu_utils/relion_gpu_util_generated_cuda_ml_optimiser.cu.o] Error 1
CMakeFiles/Makefile2:1037: recipe for target 'src/apps/CMakeFiles/relion_gpu_util.dir/all' failed
make[1]: *** [src/apps/CMakeFiles/relion_gpu_util.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

System information:
Ubuntu 16.04
2x NVIDIA Quadro P5000

**Comment by ejjordan** [comment]
This is not a bug. You should be able to get around this error by ensuring that gcc and cuda versions are compatible. For the latest version of cuda, 9.1 at time of writing, you need at least gcc 5.3, which is the version in the repo. Unfortunately, the repo currently only has cuda 7.5, which is not compatible with GCC > 4.8.

There are a number of possible solutions (not an exhaustive list):
- compile a newer version of cuda (>8)
- get modules working on your system so that you can select from among different gcc versions
- change the header file that causes this collision as done [here](https://www.pugetsystems.com/labs/hpc/NVIDIA-CUDA-with-Ubuntu-16-04-beta-on-a-laptop-if-you-just-cannot-wait-775/)

**Comment by bforsbe** [comment]
Doesn't look like the same message at all. LRiley1 reported

```/usr/include/string.h:652:42: error: ‘memcpy’ was not declared in this scope ``` 

which is **not** the same as your

```No rule to make target '/usr/include/builtin_types.h' ```

I'm guessing your cmake config step will show what the issue is. If you are not able to fix it, just make a new issue or find one which matches your error, and show what the cmake-output is.
