### ISSUE TITLE
Linking CXX executable - make error

### ISSUE THREAD

**Issue by mbenhaim** [3dem/relion#330]
Hi All,

I was hoping to get some help on my current installation of relion, primarily concerning an error during make.  

So far here is what I have:

leelab@leelab:~/relion/build$ cmake -DCUDA_ARCH=52 -DFORCE_OWN_FFTW=ON -DFORCE_OWN_FLTK=ON ..-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- BUILD TYPE set to the default type:  'Release'
-- Using provided CUDA_ARCH=52
-- Setting cpu precision to double
-- Setting gpu precision to single
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found CUDA: /usr/local/cuda-8.0 (found version "8.0") 
-- Using cuda wrapper to compile....
-- Cuda version is >= 7.5 and single-precision build, enable double usage warning.
-- Found MPI_C: /usr/local/lib/libmpi.so  
-- Found MPI_CXX: /usr/local/lib/libmpi.so  
-- MPI_INCLUDE_PATH : /usr/local/include
-- MPI_LIBRARIES : /usr/local/lib/libmpi.so
-- MPI_CXX_INCLUDE_PATH : /usr/local/include
-- MPI_CXX_LIBRARIES : /usr/local/lib/libmpi.so
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Looking for IceConnectionNumber in ICE
-- Looking for IceConnectionNumber in ICE - found
-- Found X11: /usr/lib/x86_64-linux-gnu/libX11.so
-- Found previously built non-system FLTK libraries that will be used.
-- FLTK_INCLUDE_DIR: /home/leelab/relion/external/fltk/include
-- FLTK_LIBRARIES:   /home/leelab/relion/external/fltk/lib/libfltk.so
-- No FFTW installation was found
-- Found previously built non-system FFTW libraries that will be used.
-- FFTW_INCLUDES:     /home/leelab/relion/external/fftw/include
-- FFTW_LIBRARIES:    /home/leelab/relion/external/fftw/lib/libfftw3.so
-- Looking for sincos
-- Looking for sincos - found
-- Looking for __sincos
-- Looking for __sincos - not found
-- Building shared libs (smaller build size and binaries)
-- CMAKE_BINARY_DIR:/home/leelab/relion/build
-- added particle_polish...
-- added particle_sort_mpi...
-- added pipeliner...
-- added localsym...
-- added run_ctffind...
-- added reconstruct...
-- added project...
-- added helix_toolbox...
-- added mask_create...
-- added ctf_toolbox...
-- added postprocess...
-- added star_combine...
-- added maingui...
-- added run_motioncorr...
-- added preprocess...
-- added prepare_subtomo...
-- added stack_create...
-- added particle_polish_mpi...
-- added display...
-- added tiltpair_plot...
-- added star_compare...
-- added autopick_mpi...
-- added autopick...
-- added preprocess_mpi...
-- added image_handler...
-- added particle_sort...
-- added particle_reposition...
-- added run_ctffind_mpi...
-- added find_tiltpairs...
-- added manualpick...
-- added particle_symmetry_expand...
-- added run_motioncorr_mpi...
-- added refine_mpi...
-- added postprocess_mpi...
-- added refine...
-- added localsym_mpi...
-- Configuring done
-- Generating done
-- Build files have been written to: /home/leelab/relion/build

Cmake proceeds with no errors as far as I can tell.  But when I do 'make -j 4' I receive the following errors.

[ 45%] Linking CXX shared library ../../lib/librelion_lib.so
[ 45%] Built target relion_lib
Scanning dependencies of target particle_reposition
Scanning dependencies of target refine
Scanning dependencies of target refine_mpi
Scanning dependencies of target run_ctffind_mpi
[ 46%] Building CXX object src/apps/CMakeFiles/particle_reposition.dir/particle_reposition.cpp.o
[ 46%] Building CXX object src/apps/CMakeFiles/run_ctffind_mpi.dir/run_ctffind_mpi.cpp.o
[ 46%] Building CXX object src/apps/CMakeFiles/refine.dir/refine.cpp.o
[ 47%] Building CXX object src/apps/CMakeFiles/refine_mpi.dir/refine_mpi.cpp.o
[ 48%] Linking CXX executable ../../bin/relion_run_ctffind_mpi
/usr/local/lib/libopen-pal.so.40: undefined reference to `clGetDeviceIDs@OPENCL_1.0'
/usr/local/lib/libopen-pal.so.40: undefined reference to `clGetPlatformIDs@OPENCL_1.0'
/usr/local/lib/libopen-pal.so.40: undefined reference to `clGetPlatformInfo@OPENCL_1.0'
/usr/local/lib/libopen-pal.so.40: undefined reference to `clGetDeviceInfo@OPENCL_1.0'
collect2: error: ld returned 1 exit status
src/apps/CMakeFiles/run_ctffind_mpi.dir/build.make:101: recipe for target 'bin/relion_run_ctffind_mpi' failed
make[2]: *** [bin/relion_run_ctffind_mpi] Error 1
CMakeFiles/Makefile2:275: recipe for target 'src/apps/CMakeFiles/run_ctffind_mpi.dir/all' failed
make[1]: *** [src/apps/CMakeFiles/run_ctffind_mpi.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 48%] Linking CXX executable ../../bin/relion_refine_mpi
/usr/local/lib/libopen-pal.so.40: undefined reference to `clGetDeviceIDs@OPENCL_1.0'
/usr/local/lib/libopen-pal.so.40: undefined reference to `clGetPlatformIDs@OPENCL_1.0'
/usr/local/lib/libopen-pal.so.40: undefined reference to `clGetPlatformInfo@OPENCL_1.0'
/usr/local/lib/libopen-pal.so.40: undefined reference to `clGetDeviceInfo@OPENCL_1.0'
collect2: error: ld returned 1 exit status
src/apps/CMakeFiles/refine_mpi.dir/build.make:101: recipe for target 'bin/relion_refine_mpi' failed
make[2]: *** [bin/relion_refine_mpi] Error 1
CMakeFiles/Makefile2:237: recipe for target 'src/apps/CMakeFiles/refine_mpi.dir/all' failed
make[1]: *** [src/apps/CMakeFiles/refine_mpi.dir/all] Error 2
[ 49%] Linking CXX executable ../../bin/relion_refine
/usr/local/lib/libopen-pal.so.40: undefined reference to `clGetDeviceIDs@OPENCL_1.0'
/usr/local/lib/libopen-pal.so.40: undefined reference to `clGetPlatformIDs@OPENCL_1.0'
/usr/local/lib/libopen-pal.so.40: undefined reference to `clGetPlatformInfo@OPENCL_1.0'
/usr/local/lib/libopen-pal.so.40: undefined reference to `clGetDeviceInfo@OPENCL_1.0'
collect2: error: ld returned 1 exit status
src/apps/CMakeFiles/refine.dir/build.make:101: recipe for target 'bin/relion_refine' failed
make[2]: *** [bin/relion_refine] Error 1
CMakeFiles/Makefile2:199: recipe for target 'src/apps/CMakeFiles/refine.dir/all' failed
make[1]: *** [src/apps/CMakeFiles/refine.dir/all] Error 2
[ 49%] Linking CXX executable ../../bin/relion_particle_reposition
/usr/local/lib/libopen-pal.so.40: undefined reference to `clGetDeviceIDs@OPENCL_1.0'
/usr/local/lib/libopen-pal.so.40: undefined reference to `clGetPlatformIDs@OPENCL_1.0'
/usr/local/lib/libopen-pal.so.40: undefined reference to `clGetPlatformInfo@OPENCL_1.0'
/usr/local/lib/libopen-pal.so.40: undefined reference to `clGetDeviceInfo@OPENCL_1.0'
collect2: error: ld returned 1 exit status
src/apps/CMakeFiles/particle_reposition.dir/build.make:101: recipe for target 'bin/relion_particle_reposition' failed
make[2]: *** [bin/relion_particle_reposition] Error 1
CMakeFiles/Makefile2:313: recipe for target 'src/apps/CMakeFiles/particle_reposition.dir/all' failed
make[1]: *** [src/apps/CMakeFiles/particle_reposition.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
 

For reference I am using Cuda version 8.0, and openMPI version 3.0.0.

Any help would be greatly appreciated,

Mark Benhaim

**Comment by bforsbe** [comment]
You are picking up openCL-libs for some reason. This should not happen, at least RELION does not use them. 

In addition, I'd recommend sticking to compatible gcc/cuda configs (CUDA8 supports at most gcc 5.3),  but you need to fix the openCL-related issue first.
