### ISSUE TITLE
relion installation problem when run "make"

### ISSUE THREAD

**Issue by liz18** [3dem/relion#334]
There's no report when running "cmake .." in the build directory after I solved the problem one by one.
However, when running "make -j 6" in the next step, the message reported following. Is there something wrong with the libfftw library? Could anyone help me to solve it?

Thanks in advance.

......
-- Cuda version is >= 7.5 and single-precision build, enable double usage warning.
-- MPI_INCLUDE_PATH : /usr/local/openmpi-3.0.0/include
-- MPI_LIBRARIES : /usr/local/openmpi-3.0.0/lib/libmpi.so
-- MPI_CXX_INCLUDE_PATH : /usr/local/openmpi-3.0.0/include
-- MPI_CXX_LIBRARIES : /usr/local/openmpi-3.0.0/lib/libmpi.so
-- X11 and FLTK were found
-- FLTK_LIBRARIES: /usr/local/lib/libfltk_images.a;/usr/local/lib/libfltk_forms.a;/usr/local/lib/libfltk.a;/usr/lib64/libX11.so;/usr/lib64/libm.so
-- Found FFTW: fftw3
-- FFTW_LIBRARIES: /usr/local/lib/libfftw3.a
-- Building shared libs (smaller build size and binaries)
-- CMAKE_BINARY_DIR:/usr/local/relion
-- added particle_symmetry_expand...
-- added postprocess...
-- added particle_sort_mpi...
-- added preprocess...
-- added run_motioncorr_mpi...
-- added pipeliner...
-- added image_handler...
-- added prepare_subtomo...
-- added find_tiltpairs...
-- added run_ctffind_mpi...
-- added autopick...
-- added star_combine...
-- added tiltpair_plot...
-- added reconstruct...
-- added particle_polish_mpi...
-- added run_motioncorr...
-- added ctf_toolbox...
-- added mask_create...
-- added stack_create...
-- added localsym...
-- added refine...
-- added particle_reposition...
-- added particle_sort...
-- added postprocess_mpi...
-- added run_ctffind...
-- added localsym_mpi...
-- added star_compare...
-- added preprocess_mpi...
-- added helix_toolbox...
-- added manualpick...
-- added autopick_mpi...
-- added project...
-- added maingui...
-- added particle_polish...
-- added refine_mpi...
-- added display...
-- Configuring done
-- Generating done
-- Build files have been written to: /usr/local/relion
[root@localhost build]# make -j 48
[  0%] Built target copy_scripts
[  8%] Built target relion_gpu_util
Linking CXX shared library ../../lib/librelion_lib.so
/usr/bin/ld: /usr/local/lib/libfftw3.a(apiplan.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/local/lib/libfftw3.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
make[2]: *** [lib/librelion_lib.so] Error 1
make[1]: *** [src/apps/CMakeFiles/relion_lib.dir/all] Error 2
make: *** [all] Error 2

**Comment by bforsbe** [comment]
Your installation of FFTW does not use shared libraries. I can tell, because the library is has the ".a" suffix, rather than ".so". You can either 

1. Recompile your system-installation of FFTW with ``` --enable-shared ```. This has nothing to do with the relion installation. You'll find lots of info online on the specifics, but you probably also need the ``` -fPIC ```flag, as the error also states. 

2. Rerun your cmake command, but add ``` -DFORCE_OWN_FFTW=ON ```. Relion will then download and compile its own fftw.

**Comment by liz18** [comment]
I've solved this problem after I reinstall the FFTW and FLTK.
However, there comes another problem, it seems it can't generate the librelion_gui_lib.so, what should I do?

......
[100%] Building CXX object src/apps/CMakeFiles/display.dir/display.cpp.o
Linking CXX executable ../../bin/relion_pipeliner
Linking CXX executable ../../bin/relion_manualpick
../../lib/librelion_gui_lib.so: undefined reference to `Fl_Menu_Bar::Fl_Menu_Bar(int, int, int, int, char const*)'
../../lib/librelion_gui_lib.so: undefined reference to `Fl_Browser::textsize(int)'
../../lib/librelion_gui_lib.so: undefined reference to `Fl_Select_Browser::Fl_Select_Browser(int, int, int, int, char const*)'
../../lib/librelion_gui_lib.so: undefined reference to `Fl_Hold_Browser::Fl_Hold_Browser(int, int, int, int, char const*)'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/relion_pipeliner] Error 1
make[1]: *** [src/apps/CMakeFiles/pipeliner.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
Linking CXX executable ../../bin/relion_display
../../lib/librelion_gui_lib.so: undefined reference to `Fl_Menu_Bar::Fl_Menu_Bar(int, int, int, int, char const*)'
../../lib/librelion_gui_lib.so: undefined reference to `Fl_Browser::textsize(int)'
../../lib/librelion_gui_lib.so: undefined reference to `Fl_Select_Browser::Fl_Select_Browser(int, int, int, int, char const*)'
../../lib/librelion_gui_lib.so: undefined reference to `Fl_Hold_Browser::Fl_Hold_Browser(int, int, int, int, char const*)'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/relion_manualpick] Error 1
make[1]: *** [src/apps/CMakeFiles/manualpick.dir/all] Error 2
Linking CXX executable ../../bin/relion_maingui
../../lib/librelion_gui_lib.so: undefined reference to `Fl_Menu_Bar::Fl_Menu_Bar(int, int, int, int, char const*)'
../../lib/librelion_gui_lib.so: undefined reference to `Fl_Browser::textsize(int)'
../../lib/librelion_gui_lib.so: undefined reference to `Fl_Select_Browser::Fl_Select_Browser(int, int, int, int, char const*)'
../../lib/librelion_gui_lib.so: undefined reference to `Fl_Hold_Browser::Fl_Hold_Browser(int, int, int, int, char const*)'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/relion_display] Error 1
make[1]: *** [src/apps/CMakeFiles/display.dir/all] Error 2
../../lib/librelion_gui_lib.so: undefined reference to `Fl_Menu_Bar::Fl_Menu_Bar(int, int, int, int, char const*)'
../../lib/librelion_gui_lib.so: undefined reference to `Fl_Browser::textsize(int)'
../../lib/librelion_gui_lib.so: undefined reference to `Fl_Select_Browser::Fl_Select_Browser(int, int, int, int, char const*)'
../../lib/librelion_gui_lib.so: undefined reference to `Fl_Hold_Browser::Fl_Hold_Browser(int, int, int, int, char const*)'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/relion_maingui] Error 1
make[1]: *** [src/apps/CMakeFiles/maingui.dir/all] Error 2
make: *** [all] Error 2

**Comment by liz18** [comment]
If I run "cmake -DGUI=OFF .." addtionally, the installation works smoothly, but I can't use the GUI interface......

**Comment by bforsbe** [comment]
It's not finding the FLTK libs. Try removing everything in the build directory and call cmake with both 

``` -DFORCE_OWN_FFTW=ON -DFORCE_OWN_FLTK=ON ```

I suspect you built some code without proper libs, then installed those libs, then finalized the install. Some references to libs might then be old.

**Comment by robertsjohn** [comment]
FWIW, I had the same issue today. Even with the force option, it was trying to use the system version of the FFTW libraries. I just opened this up with ccmake and removed the entries for the FFTW lines and it built fine the second time around.

**Comment by liz18** [comment]
Thanks for your kindly advice, bforsbe! I've removed all the files in the build folder, and run cmake again with your suggestion, adding -DFORCE_OWN_FFTW=ON -DFORCE_OWN_FLTK=ON, now it has finish installation. 

Thanks!
