### ISSUE TITLE
Relion 2.1 2D Classification failed with exception message

### ISSUE THREAD

**Issue by refolding** [3dem/relion#335]
After Particle extraction job,  the extracted particles (in particles.star) was randomly split into 10 particle star files(1.star, 2.star...) , each has 10% particles. do 2D classification on one of them give error message at the 8th iteration.

WARNING: Exception (ERROR: 
No orientation was found as better than any other.

A particle image was compared to the reference and resulted in all-zero
weights (for all orientations). This should not happen, unless your data
has very special characteristics. This has historically happened for some 
lower-precision calculations, but multiple fallbacks have since been 
implemented. Please report this error to the relion developers at 

	         github.com/3dem/relion/issues  
 ) handled by switching to fail-safe mode.
NOTE: No more fail-safe warnings will be issued.

**Comment by biochem-fan** [comment]
Old version.
