### ISSUE TITLE
Error of  Refine 3D during the last iteration 

### ISSUE THREAD

**Issue by dashuailv** [3dem/relion#336]
The error is 

                         ***WARNING***

With the current settings and hardware, you will be able to 
use an estimated image-size of 516 pixels during the last iteration...

...but your input box-size (image_size) is however 554. This means that 
you will likely run out of memory on the GPU(s), and will have to then re-start 
from the last completed iteration (i.e. continue from it) *without* the use of GPUs.

_**But when I have turn off the GPU acceleration as the above words, it run with the following error**_
             * Running CPU instructions in double precision. 
 Running CPU instructions in double precision. 
 === RELION MPI setup ===
 + Number of MPI processes             = 5
 + Number of threads per MPI process  = 6
 + Total number of threads therefore  = 30
 + Master  (0) runs on host            = localhost.localdomain
 + Slave     1 runs on host            = localhost.localdomain
 + Slave     2 runs on host            = localhost.localdomain
 + Slave     3 runs on host            = localhost.localdomain
 + Slave     4 runs on host            = localhost.localdomain
 =================
 Running CPU instructions in double precision. 
 Auto-refine: Iteration= 24
 Auto-refine: Resolution= 4.46706 (no gain for 6 iter) 
 Auto-refine: Changes in angles= 0.145464 degrees; and in offsets= 0.186541 pixels (no gain for 3 iter) 
 Estimating accuracies in the orientational assignment ... 
  10/  10 sec ............................................................~~(,_,">
 Auto-refine: Estimated accuracy angles= 0.561 degrees; offsets= 0.574 pixels
 Auto-refine: Angular step= 0.234375 degrees; local searches= true
 Auto-refine: Offset search range= 1.296 pixels; offset step= 0.432 pixels
 CurrentResolution= 4.46706 Angstroms, which requires orientationSampling of at least 2.55319 degrees for a particle of diameter 200 Angstroms
 Oversampling= 0 NrHiddenVariableSamplingPoints= 1440
 OrientationalSampling= 0.46875 NrOrientations= 160
 TranslationalSampling= 0.864 NrTranslations= 9
=============================
 Oversampling= 1 NrHiddenVariableSamplingPoints= 46080
 OrientationalSampling= 0.234375 NrOrientations= 1280
 TranslationalSampling= 0.432 NrTranslations= 36
=============================
 Expectation iteration 24
1.06/1.08 hrs ...........................................................~~(,_,"> Averaging half-reconstructions up to 40 Angstrom resolution to prevent diverging orientations ...
 Note that only for higher resolutions the FSC-values are according to the gold-standard!
 Calculating gold-standard FSC ...
 Maximization ...
7.63/7.63 min ............................................................~~(,_,">
 Auto-refine: Iteration= 25
 Auto-refine: Resolution= 4.46706 (no gain for 7 iter) 
 Auto-refine: Changes in angles= 0.123467 degrees; and in offsets= 0.177177 pixels (no gain for 0 iter) 
 Estimating accuracies in the orientational assignment ... 
  10/  10 sec ............................................................~~(,_,">
 Auto-refine: Estimated accuracy angles= 0.561 degrees; offsets= 0.574 pixels
 Auto-refine: Angular step= 0.234375 degrees; local searches= true
 Auto-refine: Offset search range= 1.296 pixels; offset step= 0.432 pixels
 CurrentResolution= 4.46706 Angstroms, which requires orientationSampling of at least 2.55319 degrees for a particle of diameter 200 Angstroms
 Oversampling= 0 NrHiddenVariableSamplingPoints= 1440
 OrientationalSampling= 0.46875 NrOrientations= 160
 TranslationalSampling= 0.864 NrTranslations= 9
=============================
 Oversampling= 1 NrHiddenVariableSamplingPoints= 46080
 OrientationalSampling= 0.234375 NrOrientations= 1280
 TranslationalSampling= 0.432 NrTranslations= 36
=============================
 Expectation iteration 25
1.09/1.10 hrs ...........................................................~~(,_,"> Averaging half-reconstructions up to 40 Angstrom resolution to prevent diverging orientations ...
 Note that only for higher resolutions the FSC-values are according to the gold-standard!
 Calculating gold-standard FSC ...
 Maximization ...
7.68/7.68 min ............................................................~~(,_,">
 Auto-refine: Iteration= 26
 Auto-refine: Resolution= 4.46706 (no gain for 8 iter) 
 Auto-refine: Changes in angles= 0.139742 degrees; and in offsets= 0.207733 pixels (no gain for 1 iter) 
 Auto-refine: Refinement has converged, entering last iteration where two halves will be combined...
 Auto-refine: The last iteration will use data to Nyquist frequency, which may take more CPU and RAM.
 Estimating accuracies in the orientational assignment ... 
1.37/1.37 min ............................................................~~(,_,">
 Auto-refine: Estimated accuracy angles= 0.56 degrees; offsets= 0.574 pixels
 Auto-refine: Angular step= 0.234375 degrees; local searches= true
 Auto-refine: Offset search range= 1.296 pixels; offset step= 0.432 pixels
 CurrentResolution= 4.46706 Angstroms, which requires orientationSampling of at least 2.55319 degrees for a particle of diameter 200 Angstroms
 Oversampling= 0 NrHiddenVariableSamplingPoints= 1440
 OrientationalSampling= 0.46875 NrOrientations= 160
 TranslationalSampling= 0.864 NrTranslations= 9
=============================
 Oversampling= 1 NrHiddenVariableSamplingPoints= 46080
 OrientationalSampling= 0.234375 NrOrientations= 1280
 TranslationalSampling= 0.432 NrTranslations= 36
=============================
 Expectation iteration 26
6.81/6.89 hrs ...........................................................~~(,_,"> Averaging half-reconstructions up to 40 Angstrom resolution to prevent diverging orientations ...
 Note that only for higher resolutions the FSC-values are according to the gold-standard!
 Calculating gold-standard FSC ...
 Maximization ...
000/??? sec ~~(,_,">                                                          [oo]

**A/pix=0.6375 and particle box is  set to  554 pix
My computer have 4 GPU cards and is  NVIDIA  GeForce GTX 1080 Ti.
How could this happen and how to solve these problems ?**

**Comment by biochem-fan** [comment]
Hi, your pixel size is very small! Unless you are expecting 1.3 Angstrom resolution, you can safely downscale your particles.

**Comment by dashuailv** [comment]
Is downscale my particles  means to set the box size smaller ?

**Comment by biochem-fan** [comment]
In the `Particle extraction` job, choose Yes to `OR re-extract refined particles` and specify `Refined particle STAR file`. In the `extract` tab, keep `Particle box size` as before, that is 554 px, to make the field of view the same, but say Yes to `Rescale particles?` and specify `Re-scaled size`.

For example, if you specify 278 px (this **must be an even number**), the new pixel size becomes 0.6375 * 554 / 278 = 1.27 A / pix. If your expected resolution is worse than say 2.6 or 2.7 A, this is enough.

**Comment by dashuailv** [comment]
All the things are ok now , thanks!
