### ISSUE TITLE
Relion 2.1/UnBlur Error in executing csh during Motion Correction

### ISSUE THREAD

**Issue by BrandonS1** [3dem/relion#341]
I am a neophyte in Relion and Linux in general.  I have a dataset of movies (.mrcs) that I have successfully imported and then attempted to perform Motion Correction using the following command:

` which relion_run_motioncorr_mpi --i Import/job001/movies.star --o MotionCorr/job003/ --first_frame_sum 1 --last_frame_sum 0 --use_unblur --j 1 --unblur_exe ../unblur_1.0.2/bin/unblur_openmp_7_17_15.exe --summovie_exe ../summovie_1.0.2/bin/sum_movie_openmp_7_17_15.exe --angpix 1.05 --dose_weighting --voltage 200 --dose_per_frame 0.877 --preexposure 0 --only_do_unfinished`

I then receive an error message, where the run.err reads

`forrtl: severe (24): end-of-file during read, unit 5, file /proc/34236/fd/0
ERROR in executing: csh MotionCorr/job003//home/bds107/Documents/d190-200_HP_nATP/40link/FoilHole_15613578_Data_15571971_15571972_20180116_1345-10361_unblur.com
forrtl: severe (24): end-of-file during read, unit 5, file /proc/34240/fd/0
ERROR in executing: csh MotionCorr/job003//home/bds107/Documents/d190-200_HP_nATP/40link/FoilHole_15613578_Data_15571971_15571972_20180116_1345-10361_unblur.com
forrtl: severe (24): end-of-file during read, unit 5, file /proc/34243/fd/0
ERROR in executing: csh MotionCorr/job003//home/bds107/Documents/d190-200_HP_nATP/40link/FoilHole_15613578_Data_15571971_15571972_20180116_1345-10361_unblur.com
forrtl: severe (24): end-of-file during read, unit 5, file /proc/34308/fd/0
ERROR in executing: csh MotionCorr/job003//home/bds107/Documents/d190-200_HP_nATP/40link/FoilHole_15613578_Data_15571971_15571972_20180116_1345-10361_unblur.com
forrtl: severe (24): end-of-file during read, unit 5, file /proc/34355/fd/0
forrtl: severe (24): end-of-file during read, unit 5, file /proc/34356/fd/0
ERROR in executing: csh MotionCorr/job003//home/bds107/Documents/d190-200_HP_nATP/40link/FoilHole_15613578_Data_15571971_15571972_20180116_1345-10361_unblur.com
ERROR in executing: csh MotionCorr/job003//home/bds107/Documents/d190-200_HP_nATP/40link/FoilHole_15613578_Data_15571971_15571972_20180116_1345-10361_unblur.com
forrtl: severe (24): end-of-file during read, unit 5, file /proc/34352/fd/0
ERROR in executing: csh MotionCorr/job003//home/bds107/Documents/d190-200_HP_nATP/40link/FoilHole_15613578_Data_15571971_15571972_20180116_1345-10361_unblur.com
forrtl: severe (24): end-of-file during read, unit 5, file /proc/34412/fd/0
ERROR in executing: csh MotionCorr/job003//home/bds107/Documents/d190-200_HP_nATP/40link/FoilHole_15613578_Data_15571971_15571972_20180116_1345-10361_unblur.com
forrtl: severe (24): end-of-file during read, unit 5, file /proc/34466/fd/0
ERROR in executing: csh MotionCorr/job003//home/bds107/Documents/d190-200_HP_nATP/40link/FoilHole_15613578_Data_15571971_15571972_20180116_1345-10361_unblur.com
forrtl: severe (24): end-of-file during read, unit 5, file /proc/34517/fd/0
ERROR in executing: csh MotionCorr/job003//home/bds107/Documents/d190-200_HP_nATP/40link/FoilHole_15613578_Data_15571971_15571972_20180116_1345-10361_unblur.com
forrtl: severe (24): end-of-file during read, unit 5, file /proc/34550/fd/0
ERROR in executing: csh MotionCorr/job003//home/bds107/Documents/d190-200_HP_nATP/40link/FoilHole_15613578_Data_15571971_15571972_20180116_1345-10361_unblur.com
forrtl: severe (24): end-of-file during read, unit 5, file /proc/34576/fd/0
ERROR in executing: csh MotionCorr/job003//home/bds107/Documents/d190-200_HP_nATP/40link/FoilHole_15613578_Data_15571971_15571972_20180116_1345-10361_unblur.com
forrtl: severe (24): end-of-file during read, unit 5, file /proc/34587/fd/0
ERROR in executing: csh MotionCorr/job003//home/bds107/Documents/d190-200_HP_nATP/40link/FoilHole_15613578_Data_15571971_15571972_20180116_1345-10361_unblur.com
forrtl: severe (24): end-of-file during read, unit 5, file /proc/34618/fd/0
ERROR in executing: csh MotionCorr/job003//home/bds107/Documents/d190-200_HP_nATP/40link/FoilHole_15613578_Data_15571971_15571972_20180116_1345-10361_unblur.com
forrtl: severe (24): end-of-file during read, unit 5, file /proc/34644/fd/0
ERROR in executing: csh MotionCorr/job003//home/bds107/Documents/d190-200_HP_nATP/40link/FoilHole_15613578_Data_15571971_15571972_20180116_1345-10361_unblur.com
forrtl: severe (24): end-of-file during read, unit 5, file /proc/34670/fd/0
ERROR in executing: csh MotionCorr/job003//home/bds107/Documents/d190-200_HP_nATP/40link/FoilHole_15613578_Data_15571971_15571972_20180116_1345-10361_unblur.com
forrtl: severe (24): end-of-file during read, unit 5, file /proc/34678/fd/0
ERROR in executing: csh MotionCorr/job003//home/bds107/Documents/d190-200_HP_nATP/40link/FoilHole_15613578_Data_15571971_15571972_20180116_1345-10361_unblur.com
forrtl: severe (24): end-of-file during read, unit 5, file /proc/34692/fd/0
ERROR in executing: csh MotionCorr/job003//home/bds107/Documents/d190-200_HP_nATP/40link/FoilHole_15613578_Data_15571971_15571972_20180116_1345-10361_unblur.com
forrtl: severe (24): end-of-file during read, unit 5, file /proc/34703/fd/0
ERROR in executing: csh MotionCorr/job003//home/bds107/Documents/d190-200_HP_nATP/40link/FoilHole_15613578_Data_15571971_15571972_20180116_1345-10361_unblur.com
forrtl: severe (24): end-of-file during read, unit 5, file /proc/34706/fd/0
ERROR in executing: csh MotionCorr/job003//home/bds107/Documents/d190-200_HP_nATP/40link/FoilHole_15613578_Data_15571971_15571972_20180116_1345-10361_unblur.com
forrtl: severe (24): end-of-file during read, unit 5, file /proc/34724/fd/0
ERROR in executing: csh MotionCorr/job003//home/bds107/Documents/d190-200_HP_nATP/40link/FoilHole_15613578_Data_15571971_15571972_20180116_1345-10361_unblur.com
forrtl: severe (24): end-of-file during read, unit 5, file /proc/34756/fd/0
ERROR in executing: csh MotionCorr/job003//home/bds107/Documents/d190-200_HP_nATP/40link/FoilHole_15613578_Data_15571971_15571972_20180116_1345-10361_unblur.com
forrtl: severe (24): end-of-file during read, unit 5, file /proc/34761/fd/0
ERROR in executing: csh MotionCorr/job003//home/bds107/Documents/d190-200_HP_nATP/40link/FoilHole_15613578_Data_15571971_15571972_20180116_1345-10361_unblur.com
forrtl: severe (24): end-of-file during read, unit 5, file /proc/34784/fd/0
ERROR in executing: csh MotionCorr/job003//home/bds107/Documents/d190-200_HP_nATP/40link/FoilHole_15613578_Data_15571971_15571972_20180116_1345-10361_unblur.com
forrtl: severe (24): end-of-file during read, unit 5, file /proc/34786/fd/0
ERROR in executing: csh MotionCorr/job003//home/bds107/Documents/d190-200_HP_nATP/40link/FoilHole_15613578_Data_15571971_15571972_20180116_1345-10361_unblur.com
forrtl: severe (24): end-of-file during read, unit 5, file /proc/34790/fd/0`

(There is more to this run.err, but this was the section that was referring to only one of the .mrcs and the following lines seem to repeat the above, except with the file names changing.  I have a very large data set, and thus don't want to paste the full error message in interest of your time)

In addition, at the end of the run.err, I receive the following:

`GPL Ghostscript 9.18: Unrecoverable error, exit code 1
GPL Ghostscript 9.18: Unrecoverable error, exit code 1`

A corrected_micrographs.star file is generated; however, it is empty.  I have utilized EMAN2 e2display to confirm that the files I am importing have more than one image.

I was able to successfully motion correct the micrographs provided in the Relion 2.1 tutorial, so I imagine this is an issue with my dataset; although, I'm not sure what it would be.

Thank you in advance.

**Comment by biochem-fan** [comment]
Unblur no longer supported.
