### ISSUE TITLE
Compilation issue; CentOS 7.4 + CUDA 9.1 + OpenMPI3.0.0, GCC-7.2.0

### ISSUE THREAD

**Issue by zebrax0r** [3dem/relion#342]
Hi.

I've hit some odd compilation issues with Relion (current pull from default GIT sources).

My build environment is:

* CentOS 7.4 x86
* CUDA 9.1.85
* OpenMPI 3.0.0
* GCC 7.2.0

My target is an openhpc supercomputing platform containing 100's of nVidia V100 Volta GPU's.

So, as a start:

`[meh@headnode build]$ cmake3 ..
-- The C compiler identification is GNU 7.2.0
-- The CXX compiler identification is GNU 7.2.0
-- Check for working C compiler: /opt/ohpc/pub/compiler/gcc/7.2.0/bin/gcc
-- Check for working C compiler: /opt/ohpc/pub/compiler/gcc/7.2.0/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /opt/ohpc/pub/compiler/gcc/7.2.0/bin/c++
-- Check for working CXX compiler: /opt/ohpc/pub/compiler/gcc/7.2.0/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- BUILD TYPE set to the default type:  'Release'
-- Setting fallback CUDA_ARCH=35
-- Setting cpu precision to double
-- Setting gpu precision to single
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Found CUDA: /opt/ohpc/pub/libs/cuda/9.1.85.1 (found version "9.1")
-- Using cuda wrapper to compile....
-- Cuda version is >= 7.5 and single-precision build, enable double usage warning.
-- Found MPI_C: /opt/ohpc/pub/mpi/openmpi3-gnu7/3.0.0/lib/libmpi.so
-- Found MPI_CXX: /opt/ohpc/pub/mpi/openmpi3-gnu7/3.0.0/lib/libmpi_cxx.so;/opt/ohpc/pub/mpi/openmpi3-gnu7/3.0.0/lib/libmpi.so
-- MPI_INCLUDE_PATH : /opt/ohpc/pub/mpi/openmpi3-gnu7/3.0.0/include
-- MPI_LIBRARIES : /opt/ohpc/pub/mpi/openmpi3-gnu7/3.0.0/lib/libmpi_cxx.so;/opt/ohpc/pub/mpi/openmpi3-gnu7/3.0.0/lib/libmpi.so
-- MPI_CXX_INCLUDE_PATH : /opt/ohpc/pub/mpi/openmpi3-gnu7/3.0.0/include
-- MPI_CXX_LIBRARIES : /opt/ohpc/pub/mpi/openmpi3-gnu7/3.0.0/lib/libmpi_cxx.so;/opt/ohpc/pub/mpi/openmpi3-gnu7/3.0.0/lib/libmpi.so
-- Looking for XOpenDisplay in /usr/lib64/libX11.so
-- Looking for XOpenDisplay in /usr/lib64/libX11.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Looking for IceConnectionNumber in ICE
-- Looking for IceConnectionNumber in ICE - found
-- Found X11: /usr/lib64/libX11.so
-- Could NOT find FLTK (missing:  FLTK_FLUID_EXECUTABLE)
-- No FLTK installation was found
-- Found previously built non-system FLTK libraries that will be used.
-- FLTK_INCLUDE_DIR: /usr/include
-- FLTK_LIBRARIES:   /usr/lib64/libfltk_images.so;/usr/lib64/libfltk_forms.so;/usr/lib64/libfltk.so
-- Found FFTW: fftw3
-- FFTW_LIBRARIES: /usr/lib64/libfftw3.so
-- Looking for sincos
-- Looking for sincos - found
-- Looking for __sincos
-- Looking for __sincos - not found
-- Building shared libs (smaller build size and binaries)
-- CMAKE_BINARY_DIR:/afm01/home/meh/relion/build
-- added autopick...
-- added autopick_mpi...
-- added ctf_toolbox...
-- added display...
-- added find_tiltpairs...
-- added helix_toolbox...
-- added image_handler...
-- added localsym...
-- added localsym_mpi...
-- added maingui...
-- added manualpick...
-- added mask_create...
-- added particle_polish...
-- added particle_polish_mpi...
-- added particle_reposition...
-- added particle_sort...
-- added particle_sort_mpi...
-- added particle_symmetry_expand...
-- added pipeliner...
-- added postprocess...
-- added postprocess_mpi...
-- added prepare_subtomo...
-- added preprocess...
-- added preprocess_mpi...
-- added project...
-- added reconstruct...
-- added refine...
-- added refine_mpi...
-- added run_ctffind...
-- added run_ctffind_mpi...
-- added run_motioncorr...
-- added run_motioncorr_mpi...
-- added stack_create...
-- added star_combine...
-- added star_compare...
-- added tiltpair_plot...
-- Configuring done
-- Generating done
-- Build files have been written to: /afm01/home/meh/relion/build
`

And I don't get too far...

```
[meh@headnode build]$ make
Scanning dependencies of target copy_scripts
[  0%] Built target copy_scripts
[  1%] Building NVCC (Device) object src/apps/CMakeFiles/relion_gpu_util.dir/__/gpu_utils/cuda_kernels/relion_gpu_util_generated_helper.cu.o
In file included from /opt/ohpc/pub/libs/cuda/9.1.85.1/include/host_config.h:50:0,
                 from /opt/ohpc/pub/libs/cuda/9.1.85.1/include/cuda_runtime.h:78,
                 from <command-line>:0:
/opt/ohpc/pub/libs/cuda/9.1.85.1/include/crt/host_config.h:121:2: error: #error -- unsupported GNU version! gcc versions later than 6 are not supported!
 #error -- unsupported GNU version! gcc versions later than 6 are not supported!
  ^~~~~
CMake Error at relion_gpu_util_generated_helper.cu.o.Release.cmake:207 (message):
  Error generating
  /afm01/home/meh/relion/build/src/apps/CMakeFiles/relion_gpu_util.dir/__/gpu_utils/cuda_kernels/./relion_gpu_util_generated_helper.cu.o


make[2]: *** [src/apps/CMakeFiles/relion_gpu_util.dir/__/gpu_utils/cuda_kernels/relion_gpu_util_generated_helper.cu.o] Error 1
make[1]: *** [src/apps/CMakeFiles/relion_gpu_util.dir/all] Error 2
make: *** [all] Error 2
```
I'd really _really_ like to compile against current-gen libraries and my MPI stack for a few reasons. Could I possibly have some help, here?

If I try to ratchet things back to a much lower version of GCC, such as:

* GCC 5.4.0
* OpenMPI 1.10.6

....

`
[meh@headnode build]$ cmake3 ..
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /opt/ohpc/pub/compiler/gcc/5.4.0/bin/gcc
-- Check for working C compiler: /opt/ohpc/pub/compiler/gcc/5.4.0/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /opt/ohpc/pub/compiler/gcc/5.4.0/bin/c++
-- Check for working CXX compiler: /opt/ohpc/pub/compiler/gcc/5.4.0/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- BUILD TYPE set to the default type:  'Release'
-- Setting fallback CUDA_ARCH=35
-- Setting cpu precision to double
-- Setting gpu precision to single
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Found CUDA: /opt/ohpc/pub/libs/cuda/9.1.85.1 (found version "9.1")
-- Using cuda wrapper to compile....
-- Cuda version is >= 7.5 and single-precision build, enable double usage warning.
-- Found MPI_C: /opt/ohpc/pub/mpi/openmpi-gnu/1.10.6/lib/libmpi.so
-- Found MPI_CXX: /opt/ohpc/pub/mpi/openmpi-gnu/1.10.6/lib/libmpi_cxx.so;/opt/ohpc/pub/mpi/openmpi-gnu/1.10.6/lib/libmpi.so
-- MPI_INCLUDE_PATH : /opt/ohpc/pub/mpi/openmpi-gnu/1.10.6/include
-- MPI_LIBRARIES : /opt/ohpc/pub/mpi/openmpi-gnu/1.10.6/lib/libmpi_cxx.so;/opt/ohpc/pub/mpi/openmpi-gnu/1.10.6/lib/libmpi.so
-- MPI_CXX_INCLUDE_PATH : /opt/ohpc/pub/mpi/openmpi-gnu/1.10.6/include
-- MPI_CXX_LIBRARIES : /opt/ohpc/pub/mpi/openmpi-gnu/1.10.6/lib/libmpi_cxx.so;/opt/ohpc/pub/mpi/openmpi-gnu/1.10.6/lib/libmpi.so
-- Looking for XOpenDisplay in /usr/lib64/libX11.so
-- Looking for XOpenDisplay in /usr/lib64/libX11.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Looking for IceConnectionNumber in ICE
-- Looking for IceConnectionNumber in ICE - found
-- Found X11: /usr/lib64/libX11.so
-- Could NOT find FLTK (missing:  FLTK_FLUID_EXECUTABLE)
-- No FLTK installation was found
-- Found previously built non-system FLTK libraries that will be used.
-- FLTK_INCLUDE_DIR: /usr/include
-- FLTK_LIBRARIES:   /usr/lib64/libfltk_images.so;/usr/lib64/libfltk_forms.so;/usr/lib64/libfltk.so
-- Found FFTW: fftw3
-- FFTW_LIBRARIES: /usr/lib64/libfftw3.so
-- Looking for sincos
-- Looking for sincos - found
-- Looking for __sincos
-- Looking for __sincos - not found
-- Building shared libs (smaller build size and binaries)
-- CMAKE_BINARY_DIR:/afm01/home/meh/relion/build
-- added autopick...
-- added autopick_mpi...
-- added ctf_toolbox...
-- added display...
-- added find_tiltpairs...
-- added helix_toolbox...
-- added image_handler...
-- added localsym...
-- added localsym_mpi...
-- added maingui...
-- added manualpick...
-- added mask_create...
-- added particle_polish...
-- added particle_polish_mpi...
-- added particle_reposition...
-- added particle_sort...
-- added particle_sort_mpi...
-- added particle_symmetry_expand...
-- added pipeliner...
-- added postprocess...
-- added postprocess_mpi...
-- added prepare_subtomo...
-- added preprocess...
-- added preprocess_mpi...
-- added project...
-- added reconstruct...
-- added refine...
-- added refine_mpi...
-- added run_ctffind...
-- added run_ctffind_mpi...
-- added run_motioncorr...
-- added run_motioncorr_mpi...
-- added stack_create...
-- added star_combine...
-- added star_compare...
-- added tiltpair_plot...
-- Configuring done
-- Generating done
-- Build files have been written to: /afm01/home/meh/relion/build
`

So I make it all the way through compile and make and install and things work - but I can't jump out over multiple nodes as my ORTED capabilities need OpenMPI 3.xx for my Mellanox/IB fabric to function (100G EDR fabrics, mlnx5). 

So - I do need some help making the Relion sources compile up to newer versions, as stated above.

Thank you very much for your time/help.

**Comment by bforsbe** [comment]
I guess your request goes out to CUDA, since it regards the basic [GCC-support](http://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html) of CUDA 9.1 

9.1 supports up to gcc 6.3. You could maybe hack around it, by changing the compatibility checks or by introducing some fake version labels during compilation. But because it may introduce races or other hidden problems in a scientific computing software, I would discourage it STRONGLY. You would have to re-run any result to confirm. Unless you expect massive gains, just stick to the supported combos. 

If you want to run specifically on V100s, why not use ```cmake -DCUDA_ARCH=70 ..``` ? (Disclaimer: you won't be able to run on older cards than you specify the arch for, so on heterogeneous systems it's safer to use an older arch)

**Comment by zebrax0r** [comment]
Thanks for your response. That is helpful.

Actually, the critical factor here isn’t so much CUDA version x or y. It’s the GCC version which will support an appropriate level of MPI. Without GNU7/GCC 7.4.0 I can’t compile OpenMPI3 - and without MPI3, I cannot make my RDMA MPI comms function over Mellanox connect X5 HCA’s.

So, I can happily use my CUDA 9.0 compile with older GCC, but if I ever want to use more than one node in MPI communication - I need OpenMPI3...which requires GCC 7.x

Bit of a puzzle to solve...
