### ISSUE TITLE
No components were able to be opened in the pml framework

### ISSUE THREAD

**Issue by hawuwu163** [3dem/relion#344]
ubuntu 14.4 and openmpi 3.0
 
when set MPI procs>1 the error is :

No components were able to be opened in the pml framework.

This typically means that either no components of this type were
installed, or none of the installed components can be loaded.
Sometimes this means that shared libraries required by these
components are unable to be found/loaded.

  Host:      aimlab-PowerEdge-R730
  Framework: pml
--------------------------------------------------------------------------
[aimlab-PowerEdge-R730:232067] PML ob1 cannot be selected
[aimlab-PowerEdge-R730:232068] PML ob1 cannot be selected
[aimlab-PowerEdge-R730:232056] 1 more process has sent help message help-mca-base.txt / find-available:none found
[aimlab-PowerEdge-R730:232056] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages

but when MPI procs=1 :

ERROR: 
ERROR: Cannot split data into random halves without using MPI!
File: /home/aimlab/software/relion/src/ml_optimiser.cpp line: 2146

**Comment by bforsbe** [comment]
You need to use an odd number of MPIs and the relion_refine_mpi program, like so;

```
mpirun -n 3 relion_refine_mpi <lots of flags>
```

**Comment by softsweetengineer** [comment]
Thank you for your answer!
I tried to use 3 MPIs,and new have a new error like that:


--------------------------------------------------------------------------
No components were able to be opened in the pml framework.

This typically means that either no components of this type were
installed, or none of the installed components can be loaded.
Sometimes this means that shared libraries required by these
components are unable to be found/loaded.

  Host:      aimlab-PowerEdge-R730
  Framework: pml
--------------------------------------------------------------------------
[aimlab-PowerEdge-R730:220729] PML ob1 cannot be selected

**Comment by softsweetengineer** [comment]
I finally found out my mistake.
I made some thing wrong with LD_LIBRARY_PATH.I just add /usr/local/lib intead of /usr/local/bin
it is done . 
thank you for your help!

**Comment by surak** [comment]
What was the missing library which you finally found on usr/local/lib which was missing?
