### ISSUE TITLE
Iterations take much longer after restart

### ISSUE THREAD

**Issue by michlun** [3dem/relion#345]
A 2D classification with relion 2.1.0 have been interrupted during the 15th iteration, which was expected to last about 1.4 hours:
0.86/1.39 hrs .......~~(,_,"> 

After restarting with the same parameters and on the same cluster's nodes, the same iteration took 7.71 hours and also the following iterations lasted much longer than the iterations before the 15th.

The command was the following (for 8 nodes, each one with a Tesla P100 GPU):
mpirun --n 17 relion_refine_mpi --o Class2D/job030/run_ct14  --continue  Class2D/job030/run_it014_optimiser.star --dont_combine_weights_via_disc --pool 3 --ctf  --iter 35 --tau2_fudge 2 --particle_diameter 500 --K 200 --flatten_solvent  --zero_mask  --strict_highres_exp 10 --oversampling 1 --psi_step 10 --offset_range 5 --offset_step 2 --norm --scale  --j 10 --gpu ""

I noticed that the GPU usage was very limited after restarting, nvidia-smi showed GPU-Util most of the time 0%.

**Comment by biochem-fan** [comment]
Old version.
