### ISSUE TITLE
Is there serious problem  using fftw in single precision  

### ISSUE THREAD

**Issue by Gunkkk** [3dem/relion#347]
I compiled ffw with single precision while my cpu is in double precision ，
Will it lead to serious  consequence or just ok？
Will the single particle 2D/3D classification and autofine  achieve the bad result?
Thanks!

**Comment by biochem-fan** [comment]
To compile RELION (CPU code) in double precision, you need double precision FFTW.
The easiest way is to use `-DFORCE_OWN_FFTW=ON` in `cmake`.

**Comment by Gunkkk** [comment]
However ， I'v compiled  it with single precision fftw and run them successfully
It seems that everything is ok but the speed   improved  .
Is the result unsatisfied  or  nothing is wrong?
Thank you very much

**Comment by Gunkkk** [comment]
@biochem-fan  
I found that  if my relion has  not " use -DFORCE_OWN_FFTW=ON in cmake." , sometimes it   can link to my own FFTW(shared library)，and the  speed of the relion can speed up a double,while  sometimes it dont linked to my own fftw and the relion is really slow?
Is there any reason for the performance？
Thanks！
