### ISSUE TITLE
error: all-zero weights (for all orientations)

### ISSUE THREAD

**Issue by ehanssen** [3dem/relion#349]
hi, i have had this error coming up fairly often on several project:

WARNING: Exception (ERROR: 
No orientation was found as better than any other.

A particle image was compared to the reference and resulted in all-zero
weights (for all orientations). This should not happen, unless your data
has very special characteristics. This has historically happened for some 
lower-precision calculations, but multiple fallbacks have since been 
implemented. Please report this error to the relion developers at 

	         github.com/3dem/relion/issues  
 ) handled by switching to fail-safe mode.
[thor:12430] *** Process received signal ***
[thor:12430] Signal: Segmentation fault (11)
[thor:12430] Signal code: Address not mapped (1)
[thor:12430] Failing at address: 0x107e
[thor:12430] [ 0] /lib64/libpthread.so.0[0x375c60f7e0]
[thor:12430] [ 1] /usr/lib64/libstdc++.so.6(_ZNSsC2ERKSs+0xb)[0x3762a9d25b]
[thor:12430] [ 2] /usr/local/lib/librelion_lib.so(_ZN11MlOptimiser24expectationSomeParticlesEll+0x1120)[0x7ff32495d2d0]
[thor:12430] [ 3] /usr/local/lib/librelion_lib.so(_ZN14MlOptimiserMpi11expectationEv+0x15e6)[0x7ff324725fb6]
[thor:12430] [ 4] /usr/local/lib/librelion_lib.so(_ZN14MlOptimiserMpi7iterateEv+0xbd)[0x7ff3247335cd]
[thor:12430] [ 5] /usr/local/bin/relion_refine_mpi(main+0x7a)[0x4030aa]
[thor:12430] [ 6] /lib64/libc.so.6(__libc_start_main+0xfd)[0x375be1ed1d]
[thor:12430] [ 7] /usr/local/bin/relion_refine_mpi[0x402f39]
[thor:12430] *** End of error message ***
[thor:12431] *** Process received signal ***
[thor:12431] Signal: Segmentation fault (11)
[thor:12431] Signal code: Address not mapped (1)
[thor:12431] Failing at address: 0xff8
[thor:12431] [ 0] /lib64/libpthread.so.0[0x375c60f7e0]
[thor:12431] [ 1] /usr/lib64/libstdc++.so.6(_ZNSsC2ERKSs+0xb)[0x3762a9d25b]
[thor:12431] [ 2] /usr/local/lib/librelion_lib.so(_ZN11MlOptimiser24expectationSomeParticlesEll+0x1120)[0x7f0dc5d662d0]
[thor:12431] [ 3] /usr/local/lib/librelion_lib.so(_ZN14MlOptimiserMpi11expectationEv+0x15e6)[0x7f0dc5b2efb6]
[thor:12431] [ 4] /usr/local/lib/librelion_lib.so(_ZN14MlOptimiserMpi7iterateEv+0xbd)[0x7f0dc5b3c5cd]
[thor:12431] [ 5] /usr/local/bin/relion_refine_mpi(main+0x7a)[0x4030aa]
[thor:12431] [ 6] /lib64/libc.so.6(__libc_start_main+0xfd)[0x375be1ed1d]
[thor:12431] [ 7] /usr/local/bin/relion_refine_mpi[0x402f39]
[thor:12431] *** End of error message ***

**Comment by xeniorn** [comment]
Same error.

Happened when I entered large search parameters (30 px range 3 px step), didn't happen with the default settings.

**Comment by xeniorn** [comment]
Also seems to happpen when I try to continue an optimization which contains some empty all-black classes, regardless of parameters.

**Comment by biochem-fan** [comment]
Old version.
