### ISSUE TITLE
Issue installing relion 2.0 on macOS 10.13.3

### ISSUE THREAD

**Issue by jenwlou** [3dem/relion#352]
Hi!

I followed these guides: https://www2.mrc-lmb.cam.ac.uk/relion/index.php?title=Main_Page and https://www.bioch.ox.ac.uk/aspsite/index.asp?pageid=83&dat=yes&action=howto&stepID=104. But I could only install relion when I omit the GUI. 

Here is the output for cmake .. :  
-- The C compiler identification is AppleClang 7.0.2.7000181
-- The CXX compiler identification is AppleClang 7.0.2.7000181
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- BUILD TYPE set to the default type:  'Release'
-- Setting fallback CUDA_ARCH=35
-- Setting cpu precision to double
-- Setting gpu precision to single
CUDA_TOOLKIT_ROOT_DIR not found or specified
-- Could NOT find CUDA (missing:  CUDA_TOOLKIT_ROOT_DIR CUDA_NVCC_EXECUTABLE CUDA_INCLUDE_DIRS CUDA_CUDART_LIBRARY) 
-- Using non-cuda compilation....
-- Found MPI_C: /usr/local/lib/libmpi.dylib  
-- Found MPI_CXX: /usr/local/lib/libmpi.dylib  
-- MPI_INCLUDE_PATH : /usr/local/include
-- MPI_LIBRARIES : /usr/local/lib/libmpi.dylib
-- MPI_CXX_INCLUDE_PATH : /usr/local/include
-- MPI_CXX_LIBRARIES : /usr/local/lib/libmpi.dylib
-- Looking for XOpenDisplay in /opt/X11/lib/libX11.dylib;/opt/X11/lib/libXext.dylib
-- Looking for XOpenDisplay in /opt/X11/lib/libX11.dylib;/opt/X11/lib/libXext.dylib - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Looking for IceConnectionNumber in ICE
-- Looking for IceConnectionNumber in ICE - found
-- Found X11: /opt/X11/lib/libX11.dylib
-- Could NOT find FLTK (missing:  FLTK_LIBRARIES FLTK_FLUID_EXECUTABLE) 
-- No FLTK installation was found
-- --------------------------------------------------------
-- -------- NO EXISTING FLTK LIBRARIES WHERE FOUND. -------
-- -------------- FLTK WILL BE DOWNLOADED AND -------------
-- --------------- BUILT DURING COMPILE-TIME. -------------
-- --------------------------------------------------------
-- ---- A WORKING INTERNET CONNECTION WILL BE REQUIRED. ---
-- --------------------------------------------------------
-- no previous fltk found, the following paths are set for libs/headers TO BE built
-- FLTK_INCLUDE_DIR: /Users/jenlou1/relion/external/fltk/include
-- FLTK_LIBRARIES:   /Users/jenlou1/relion/external/fltk/lib/libfltk.dylib
-- Found FFTW: fftw3
-- FFTW_LIBRARIES: /usr/local/lib/libfftw3.dylib
-- Looking for sincos
-- Looking for sincos - not found
-- Looking for __sincos
-- Looking for __sincos - found
-- Building shared libs (smaller build size and binaries)
-- CMAKE_BINARY_DIR:/Users/jenlou1/relion/build1
-- added autopick...
-- added autopick_mpi...
-- added ctf_toolbox...
-- added display...
-- added find_tiltpairs...
-- added helix_toolbox...
-- added image_handler...
-- added localsym...
-- added localsym_mpi...
-- added maingui...
-- added manualpick...
-- added mask_create...
-- added particle_polish...
-- added particle_polish_mpi...
-- added particle_reposition...
-- added particle_sort...
-- added particle_sort_mpi...
-- added particle_symmetry_expand...
-- added pipeliner...
-- added postprocess...
-- added postprocess_mpi...
-- added prepare_subtomo...
-- added preprocess...
-- added preprocess_mpi...
-- added project...
-- added reconstruct...
-- added refine...
-- added refine_mpi...
-- added run_ctffind...
-- added run_ctffind_mpi...
-- added run_motioncorr...
-- added run_motioncorr_mpi...
-- added stack_create...
-- added star_combine...
-- added star_compare...
-- added tiltpair_plot...
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/jenlou1/relion/build1

Here is the output for make -j : 
Scanning dependencies of target copy_scripts
Scanning dependencies of target OWN_FLTK
Scanning dependencies of target relion_lib
[  1%] Creating directories for 'OWN_FLTK'
[  2%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/assembly.cpp.o
[  2%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/autopicker_mpi.cpp.o
[  3%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/autopicker.cpp.o
[  3%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/backprojector.cpp.o
[  4%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/complex.cpp.o
[  4%] Built target copy_scripts
[  5%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/args.cpp.o
[  6%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/CPlot2D.cpp.o
[  6%] Performing download step (download, verify and extract) for 'OWN_FLTK'
[  6%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/ctf.cpp.o
[  7%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/ctffind_runner.cpp.o
[  8%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/ctffind_runner_mpi.cpp.o
[  9%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/error.cpp.o
-- verifying file...
     file='/Users/jenlou/relion/external/fltk/fltk-1.3.3-source.tar.gz'
[  9%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/euler.cpp.o
-- verifying file... done
-- extracting...
     src='/Users/jenlou/relion/external/fltk/fltk-1.3.3-source.tar.gz'
     dst='/Users/jenlou/relion/external/fltk/fltk'
-- extracting... [tar xfz]
[ 10%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/exp_model.cpp.o
[ 10%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/filename.cpp.o
[ 11%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/fftw.cpp.o
[ 11%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/particle_polisher.cpp.o
[ 12%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/numerical_recipes.cpp.o
[ 13%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/parallel.cpp.o
[ 14%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/funcs.cpp.o
[ 14%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/memory.cpp.o
[ 15%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/ml_optimiser.cpp.o
[ 16%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/image.cpp.o
[ 19%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/local_symmetry_mpi.cpp.o
[ 20%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/matrix2d.cpp.o
[ 17%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/healpix_sampling.cpp.o
[ 20%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/helix.cpp.o
[ 20%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/mask.cpp.o
[ 21%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/ml_optimiser_mpi.cpp.o
[ 22%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/mpi.cpp.o
[ 23%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/metadata_table.cpp.o
[ 24%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/matrix1d.cpp.o
[ 24%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/local_symmetry.cpp.o
[ 25%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/metadata_label.cpp.o
[ 26%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/ml_model.cpp.o
[ 27%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/motioncorr_runner_mpi.cpp.o
[ 27%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/motioncorr_runner.cpp.o
[ 27%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/metadata_container.cpp.o
[ 27%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/multidim_array.cpp.o
[ 28%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/particle_polisher_mpi.cpp.o
[ 29%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/pipeliner.cpp.o
[ 30%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/symmetries.cpp.o
[ 31%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/time.cpp.o
[ 32%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/tabfuncs.cpp.o
[ 33%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/particle_sorter_mpi.cpp.o
[ 33%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/pipeline_jobs.cpp.o
[ 35%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/projector.cpp.o
[ 36%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/postprocessing.cpp.o
[ 36%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/particle_sorter.cpp.o
[ 35%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/preprocessing.cpp.o
[ 37%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/preprocessing_mpi.cpp.o
[ 37%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/strings.cpp.o
[ 37%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/transformations.cpp.o
[ 38%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/Healpix_2.15a/healpix_base.cc.o
[ 39%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/Healpix_2.15a/cxxutils.cc.o
-- extracting... [analysis]
-- extracting... [rename]
-- extracting... [clean up]
-- extracting... done
[ 41%] No update step for 'OWN_FLTK'
[ 41%] Performing patch step for 'OWN_FLTK'
patching file src/fl_line_style.cxx
[ 41%] Performing configure step for 'OWN_FLTK'
[ 42%] Performing build step for 'OWN_FLTK'
=== making jpeg ===
=== making png ===
=== making src ===
In file included from Fl_Quartz_Printer.mm:25:
In file included from /System/Library/Frameworks/Cocoa.framework/Headers/Cocoa.h:13:
In file included from /System/Library/Frameworks/AppKit.framework/Headers/AppKit.h:38:
In file included from /System/Library/Frameworks/AppKit.framework/Headers/NSColor.h:36:
/System/Library/Frameworks/QuartzCore.framework/Headers/CIColor.h:1:10: fatal error: 'QuartzCore/../Frameworks/CoreImage.framework/Headers/CIColor.h'
      file not found
#include <QuartzCore/../Frameworks/CoreImage.framework/Headers/CIColor.h>
         ^
Compiling fl_shortcut.cxx...
Compiling fl_show_colormap.cxx...
Compiling fl_symbols.cxx...
Compiling fl_vertex.cxx...
Compiling screen_xywh.cxx...
Compiling fl_utf8.cxx...
Compiling ps_image.cxx...
Compiling fl_call_main.c...
Fl_Copy_Surface.cxx:191:6: warning: comparison of function 'CGDataConsumerCreateWithCFData' not equal to a null pointer is always true
      [-Wtautological-pointer-compare]
  if(CGDataConsumerCreateWithCFData != NULL) {
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~    ~~~~
Fl_Copy_Surface.cxx:191:6: note: prefix with the address-of operator to silence this warning
  if(CGDataConsumerCreateWithCFData != NULL) {
     ^
     &
In file included from Fl_Sys_Menu_Bar.mm:41:
In file included from /System/Library/Frameworks/Cocoa.framework/Headers/Cocoa.h:13:
In file included from /System/Library/Frameworks/AppKit.framework/Headers/AppKit.h:38:
In file included from /System/Library/Frameworks/AppKit.framework/Headers/NSColor.h:36:
/System/Library/Frameworks/QuartzCore.framework/Headers/CIColor.h:1:10: fatal error: 'QuartzCore/../Frameworks/CoreImage.framework/Headers/CIColor.h'
      file not foundompiling flstring.c...
Compiling scandir.c...
Compiling numericsort.c...
[0m
#include <QuartzCore/../Frameworks/CoreImage.framework/Headers/CIColor.h>
         ^
In file included from Fl_cocoa.mm:56:
In file included from /System/Library/Frameworks/Cocoa.framework/Headers/Cocoa.h:13:
In file included from /System/Library/Frameworks/AppKit.framework/Headers/AppKit.h:38:
In file included from /System/Library/Frameworks/AppKit.framework/Headers/NSColor.h:36:
/System/Library/Frameworks/QuartzCore.framework/Headers/CIColor.h:1:10: fatal error: 'QuartzCore/../Frameworks/CoreImage.framework/Headers/CIColor.h'
      file not found
#include <QuartzCore/../Frameworks/CoreImage.framework/Headers/CIColor.h>
         ^
Compiling vsnprintf.c...
In file included from Fl_Native_File_Chooser_MAC.mm:342:
In file included from /System/Library/Frameworks/Cocoa.framework/Headers/Cocoa.h:13:
In file included from /System/Library/Frameworks/AppKit.framework/Headers/AppKit.h:38:
In file included from /System/Library/Frameworks/AppKit.framework/Headers/NSColor.h:36:
/System/Library/Frameworks/QuartzCore.framework/Headers/CIColor.h:1:10: fatal error: 'QuartzCore/../Frameworks/CoreImage.framework/Headers/CIColor.h'
      file not found
#include <QuartzCore/../Frameworks/CoreImage.framework/Headers/CIColor.h>
         ^
1 error generated.
Compiling fl_utf.c...
Compiling xutf8/case.c...
1 warning generated.
Compiling xutf8/is_right2left.c...
Compiling xutf8/is_spacing.c...
Compiling xutf8/keysym2Ucs.c...
Compiling xutf8/utf8Input.c...
Compiling xutf8/utf8Utils.c...
make[4]: *** [Fl_Quartz_Printer.o] Error 1
make[4]: *** Waiting for unfinished jobs....
1 warning generated.
Fl_Preferences.cxx:959:13: warning: function 'makePath' is not needed and will not be emitted [-Wunneeded-internal-declaration]
static char makePath( const char *path ) {
            ^
1 error generated.
1 error generated.
make[4]: *** [Fl_Native_File_Chooser_MAC.o] Error 1
make[4]: *** [Fl_Sys_Menu_Bar.o] Error 1
1 error generated.
make[4]: *** [Fl_cocoa.o] Error 1
In file included from Fl_Tabs.cxx:28:
../FL/Fl_Tabs.H:202:14: warning: private field 'value_' is not used [-Wunused-private-field]
  Fl_Widget *value_;
             ^
Fl_Tree.cxx:68:12: warning: function 'find_total_children' is not needed and will not be emitted [-Wunneeded-internal-declaration]
static int find_total_children(Fl_Tree_Item *item, int count=0) {
           ^
Fl_Window_shape.cxx:340:31: warning: comparison of function 'CGContextClipToMask' not equal to a null pointer is always true
      [-Wtautological-pointer-compare]
    if (shape_data_->mask && (CGContextClipToMask != NULL)) {
                              ^~~~~~~~~~~~~~~~~~~    ~~~~
Fl_Window_shape.cxx:340:31: note: prefix with the address-of operator to silence this warning
    if (shape_data_->mask && (CGContextClipToMask != NULL)) {
                              ^
                              &
1 warning generated.
1 warning generated.
1 warning generated.
In file included from Fl_get_key.cxx:22:
./Fl_get_key_mac.cxx:247:6: warning: comparison of function 'CGEventSourceKeyState' not equal to a null pointer is always true
      [-Wtautological-pointer-compare]
  if(CGEventSourceKeyState != NULL) {
     ^~~~~~~~~~~~~~~~~~~~~    ~~~~
./Fl_get_key_mac.cxx:247:6: note: prefix with the address-of operator to silence this warning
  if(CGEventSourceKeyState != NULL) {
     ^
     &
1 warning generated.
In file included from fl_font.cxx:51:
./fl_font_mac.cxx:51:8: warning: using integer absolute value function 'abs' when argument is of floating point type [-Wabsolute-value]
  if ( abs(advances[0].width - advances[1].width) < 1E-2 ) {//this is a fixed-width font
       ^
./fl_font_mac.cxx:51:8: note: use function 'std::abs' instead
  if ( abs(advances[0].width - advances[1].width) < 1E-2 ) {//this is a fixed-width font
       ^~~
       std::abs
./fl_font_mac.cxx:51:8: note: include the header <cmath> or explicitly provide a declaration for 'std::abs'
1 warning generated.
screen_xywh.cxx:134:9: warning: comparison of function 'CGDisplayScreenSize' not equal to a null pointer is always true
      [-Wtautological-pointer-compare]
    if (CGDisplayScreenSize != NULL) {
        ^~~~~~~~~~~~~~~~~~~    ~~~~
screen_xywh.cxx:134:9: note: prefix with the address-of operator to silence this warning
    if (CGDisplayScreenSize != NULL) {
        ^
        &
1 warning generated.
1 warning generated.
make[3]: *** [all] Error 1
make[2]: *** [OWN_FLTK-prefix/src/OWN_FLTK-stamp/OWN_FLTK-build] Error 2
make[1]: *** [CMakeFiles/OWN_FLTK.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
1 warning generated.
[ 42%] Linking CXX shared library ../../lib/librelion_lib.dylib
[ 42%] Built target relion_lib
make: *** [all] Error 2

I have tried with -DFORCE_OWN_FLTK=ON and -DFORCE_OWN_FFTW=ON. I have also tried installing fltk from http://fltk.org/pub/fltk/1.3.3/fltk-1.3.3-source.tar.gz and I also get an error from make all:

In file included from /System/Library/Frameworks/AppKit.framework/Headers/NSColor.h:36:
/System/Library/Frameworks/QuartzCore.framework/Headers/CIColor.h:1:10: fatal error: 'QuartzCore/../Frameworks/CoreImage.framework/Headers/CIColor.h'
      file not found
#include <QuartzCore/../Frameworks/CoreImage.framework/Headers/CIColor.h>
         ^
1 error generated.
make[1]: *** [Fl_cocoa.o] Error 1
make: *** [all] Error 1

Thanks!

**Comment by bforsbe** [comment]
Not sure we ever  tried to compile with AppleClang as our c-compiler. Can you try with gcc?

**Comment by jenwlou** [comment]
I've tried with gcc and it did not work.

I am seeing the following error, any ideas on how to fix it? Thanks!!

/System/Library/Frameworks/QuartzCore.framework/Headers/CIColor.h:1:10: fatal error: 
      'QuartzCore/../Frameworks/CoreImage.framework/Headers/CIColor.h' file not
      found
#include <QuartzCore/../Frameworks/CoreImage.framework/Headers/CIColor.h>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make[1]: *** [Fl_cocoa.o] Error 1
make: *** [all] Error 1

**Comment by bforsbe** [comment]
Not sure.... it's finding and using files that I've never seen used before, but then again we don't run relion on apple all that much. It does look like it's realted to FLTK, which you don't have installed, so RELION tries to download and install it for you. Try to install it so that RELION finds it instead. Make sure to purge the build-directory or make a new one before re-building (after having installed FLTK system-wide).

**Comment by jenwlou** [comment]
Thanks for your help! It worked when I installed FLTK first and then building RELION.
