### ISSUE TITLE
CDeviceArray:: Create: invalid device symbol with current Relion + nVidia Volta + CUDA 9.1.85.3

### ISSUE THREAD

**Issue by zebrax0r** [3dem/relion#353]
Hi there.

I *think* we've hit a bug. Everything else seems to be working nicely with our Relion install, but we've hit a couple of odd things around the edges.

I downloaded test dataset from relion21_tutorial.pdf, then started testing. 

- At 'Motion Correction’  step, I entered exactly same parameters which were mentioned in tutorial. 

The output I am getting is completely black (see attached).
[logfile.pdf](https://github.com/3dem/relion/files/1893136/logfile.pdf)
![pastedgraphic-3](https://user-images.githubusercontent.com/15049889/38540060-ed935048-3cdd-11e8-8d21-7c5570e7db00.jpg)
[Falcon_2012_06_12-14_33_35_0.txt](https://github.com/3dem/relion/files/1893142/Falcon_2012_06_12-14_33_35_0.txt)

- Logfile generated (see attached) at this step is completely different than the one provided in ‘precalculatedResults/job002/logfile.pdf’. - When I check ‘Falcon_2012_06_12-14_33_35_0.err, it is showing following error:

`CDeviceArray:: Create: invalid device symbol `

This Relion was git cloned four days ago from this default repository and compiled the following way, on a CentOS 7.4 system:

`cmake3 -DFORCE_OWN_FFTW=ON -DFORCE_OWN_FLTK=ON -DDoublePrec_GPU=ON -DCUDA_ARCH=70 -DCMAKE_INSTALL_PREFIX=/opt/relion2.1.0/ ..`

cmake is version 3.6.3

Any help would be most appreciated, as we just can't see where this is going wrong.

Thank you.

z

**Comment by bforsbe** [comment]
DeviceArray is not a method in the relion source, so this is not a relion issue. I suspect you want to ask the developers of the motioncorrection-program you are using why you appear to not detect any devices (GPUs). I would guess (I don't know the code that's generating this error, so I can only guess), that the error is thrown when the program (motioncor/motioncorr/unblur/whatever you are running) tries to make an array on the memory of a GPU that the CUDA runtime can't detect. 

Unfortunately this is not a RELION bug/issue that we can fix, but I would suggest you try to use a terminal window to manually test-run the motion-correction program you are using to make sure it's working as intended.
