### ISSUE TITLE
Compilation of relion 2.1 using intel 2017 compilers - how?

### ISSUE THREAD

**Issue by CJCShadowsan** [3dem/relion#354]
Just trying to get relion compiled - when I set any CMAKE flags to enable AVX2 for example, I end up with build failures.

Has anyone built this using intel compilers (2017) and can point me in the right direction?

Thanks!

**Comment by Fravadona** [comment]
There's a lot of things that can go wrong and you didn't provide any information ...
Which OS and which version of Linux/macOS/Windows ?
With CUDA support enabled ? If so then which CUDA version ?
Do you have IMPI in your Intel PSXE 2017 installation ?

**Comment by biochem-fan** [comment]
Old version.
