### ISSUE TITLE
--nr_uniform flag in relion_project is broken?

### ISSUE THREAD

**Issue by sjweaver** [3dem/relion#355]
Hi all,

Thanks for your work on Relion!  I'm trying to use relion_project to generate 2D projections of a 3D map, but it no longer seems to recognize the --nr_uniform flag.  The same issue was reported on the list in March (https://www.jiscmail.ac.uk/cgi-bin/webadmin?A2=CCPEM;42c4516a.1803).  I'm running Relion2.1.0 on sbgrid.  

20180425_creatingprojections]$ relion_project
+++ RELION: command line arguments (with defaults for optional ones between parantheses) +++
====== Options ===== 
                                --i : Input map to be projected
                         --o (proj) : Rootname for output projections
                      --ctf (false) : Apply CTF to reference projections
           --ctf_phase_flip (false) : Flip phases of the CTF in the output projections
    --ctf_intact_first_peak (false) : Ignore CTFs until their first peak?
                       --angpix (1) : Pixel size (in Angstroms)
                          --mask () : Mask that will be applied to the input map prior to making projections
                       --ang (None) : STAR file with orientations for multiple projections (if None, assume single projection)
                          --rot (0) : First Euler angle (for a single projection)
                         --tilt (0) : Second Euler angle (for a single projection)
                          --psi (0) : Third Euler angle (for a single projection)
                         --xoff (0) : Origin X-offsets (in pixels) (for a single projection)
                         --yoff (0) : Origin Y-offsets (in pixels) (for a single projection)
                         --zoff (0) : Origin Z-offsets (in pixels) (for a single 3D rotation)
                --add_noise (false) : Add noise to the output projections (only with --ang)
                  --white_noise (0) : Standard deviation of added white Gaussian noise
                   --model_noise () : Model STAR file with power spectra for coloured Gaussian noise
             --subtract_exp (false) : Subtract projections from experimental images (in --ang)
     --ignore_particle_name (false) : Ignore the rlnParticleName column (in --ang)
                   --3d_rot (false) : Perform 3D rotations instead of projection into 2D images
                      --maxres (-1) : Maximum resolution (in Angstrom) to consider in Fourier space (default Nyquist)
                          --pad (2) : Padding factor
                     --ctf2 (false) : Apply CTF*CTF to reference projections
                       --NN (false) : Use nearest-neighbour instead of linear interpolation

20180425_creatingprojections]$ relion_project --i j344_postprocess_masked_D2.mrc --o j344_proj --angpix 0.8315 --nr_uniform 50
The following warnings were encountered upon command-line parsing: 
WARNING: Option --nr_uniform	is not a valid RELION argument
 Reading map: j344_postprocess_masked_D2.mrc
 Done reading map!
 Done writing j344_proj

It looks like the projection images file has 8428099 z slices??

 20180425_creatingprojections]$ header j344_proj

 RO image file on unit   1 : j344_proj     Size=        371 K

                    This is a byte-swapped file.

                    This file has an old-style MRC header.

         This file has invalid axis indices, adjusting them to 1,2,3

 Number of columns, rows, sections .....   32831   39491 8428099
 Map mode ..............................    0   (byte)                     
 Start cols, rows, sects, grid x,y,z ...32831     0     0       1      1      1
 Pixel spacing (Angstroms)..............   1.000      1.000      1.000    
 Cell angles ...........................    0.000    0.000    0.000
 Fast, medium, slow axes ...............    X    Y    Z
 Origin on x,y,z .......................    0.000       0.000       0.000    
 Minimum density .......................   0.0000    
 Maximum density .......................   0.0000    
 Mean density ..........................  0.55340E-40
 tilt angles (original,current) ........   0.0   0.0   0.0   0.0   0.0   0.0
 Space group,# extra bytes,idtype,lens .    39492        0        0        0

     0 Titles :

**Comment by daryna-smyrnova** [comment]
Same problem for me. Relion 2.1.0

As I can see from the code in project.cpp - the option is no longer there. Shall we use --ang option with angle distribution *star file instead?

Maybe something should be changed in the tutorial as well?

**Comment by biochem-fan** [comment]
Thank you very much for reporting this. This is unintentional. The option will be back in RELION 3.0.

**Comment by daryna-smyrnova** [comment]
Ok, thanks! That clarifies things :)

Any sneak peek on when approx RELION 3.0 is coming???
