### ISSUE TITLE
Relion 2.1 3D Autorefine All-zero weights 

### ISSUE THREAD

**Issue by mauwau** [3dem/relion#356]
During 3D autorefine with Standard stettings that I have used many times before, I ran into this error, was running fine until 14th round and had refined the same particles also in a downscaled format already without problems

WARNING: Exception (ERROR: 
No orientation was found as better than any other.

A particle image was compared to the reference and resulted in all-zero
weights (for all orientations). This should not happen, unless your data
has very special characteristics. This has historically happened for some 
lower-precision calculations, but multiple fallbacks have since been 
implemented. Please report this error to the relion developers at 

	         github.com/3dem/relion/issues  
 ) handled by switching to fail-safe mode.

 fn_img= 
 part_id= 139518
 ipart= 0
 op.min_diff2[ipart]= 14824.4
 group_id= 3
 ml_model.scale_correction[group_id]= 1.04985
 exp_significant_weight[ipart]= 0
 exp_max_weight[ipart]= -1
 ml_model.sigma2_noise[group_id]= 
   0.00015
   7.8e-05
   5.1e-05
   4.7e-05
   4.8e-05
   5.2e-05
   5.4e-05
   5.6e-05
   5.7e-05
   5.8e-05
   5.9e-05
   5.8e-05
   5.6e-05
   5.3e-05
   4.7e-05
   4.2e-05
   3.6e-05
   3.1e-05
   2.8e-05
   2.6e-05
   2.5e-05
   2.4e-05
   2.3e-05
   2.1e-05
   2.1e-05
     2e-05
     2e-05
   1.9e-05
   1.8e-05
   1.7e-05
   1.7e-05
   1.6e-05
   1.5e-05
   1.5e-05
   1.4e-05
   1.4e-05
   1.3e-05
   1.3e-05
   1.2e-05
   1.2e-05
   1.1e-05
   1.1e-05
     1e-05
   9.8e-06
   9.5e-06
   9.1e-06
   8.7e-06
   8.3e-06
     8e-06
   7.7e-06
   7.4e-06
   7.1e-06
   6.8e-06
   6.5e-06
   6.3e-06
     6e-06
   5.7e-06
   5.5e-06
   5.3e-06
   5.1e-06
   4.9e-06
   4.7e-06
   4.5e-06
   4.3e-06
   4.1e-06
     4e-06
   3.8e-06
   3.7e-06
   3.5e-06
   3.4e-06
   3.2e-06
   3.1e-06
     3e-06
   2.9e-06
   2.8e-06
   2.7e-06
   2.5e-06
   2.4e-06
   2.4e-06
   2.3e-06
   2.2e-06
   2.1e-06
     2e-06
   1.9e-06
   1.9e-06
   1.8e-06
   1.7e-06
   1.7e-06
   1.6e-06
   1.5e-06
   1.5e-06
   1.4e-06
   1.4e-06
   1.3e-06
   1.3e-06
   1.2e-06
   1.2e-06
   1.1e-06
   1.1e-06
     1e-06
     1e-06
   9.7e-07
   9.4e-07
   9.1e-07
   8.7e-07
   8.4e-07
   8.1e-07
   7.8e-07
   7.6e-07
   7.3e-07
     7e-07
   6.8e-07
   6.5e-07
   6.3e-07
     6e-07
   5.8e-07
   5.6e-07
   5.4e-07
   5.2e-07
     5e-07
   4.9e-07
   4.7e-07
   4.5e-07
   4.4e-07
   4.2e-07
   4.1e-07
     4e-07
   3.8e-07
   3.7e-07
   3.6e-07
   3.5e-07
   3.4e-07
   3.3e-07
   3.2e-07
   3.1e-07
     3e-07
   2.9e-07
   2.8e-07
   2.7e-07
   2.7e-07
   2.6e-07
   2.5e-07
   2.5e-07
   2.4e-07
   2.3e-07
   2.3e-07
   2.2e-07
   2.2e-07
   2.1e-07
   2.1e-07
     2e-07
     2e-07
   1.9e-07
   1.9e-07
   1.8e-07
   1.8e-07
   1.8e-07
   1.7e-07
   1.7e-07
   1.7e-07
   1.6e-07
   1.6e-07
   1.6e-07
   1.5e-07
   1.5e-07
   1.5e-07
   1.5e-07
   1.5e-07
   1.4e-07
   1.4e-07
   1.4e-07
   1.4e-07
   1.4e-07
   1.3e-07
   1.3e-07
   1.3e-07
   1.3e-07
   1.3e-07
   1.3e-07
   1.3e-07
   1.2e-07

slave 1 encountered error: ERROR: 
The sum of weights for all orientations was
found to be zero for an image. This should not happen, unless your data
has very special characteristics. Please report this error to 
the relion developers at 

			 github.com/3dem/relion/issues   
File: /home/schmidtc/Downloads/relion/src/gpu_utils/cuda_ml_optimiser.cu line: 1887

**Comment by pconesa** [comment]
This is also happening to me in r3 when doing 2D classification

**Comment by biochem-fan** [comment]
Old version.
