### ISSUE TITLE
GUI improvement suggestion

### ISSUE THREAD

**Issue by Guilz** [3dem/relion#357]
This applies to RELION 2.1 (might already be fixed in the development version?).

When setting up a 3D classification with no alignment, the job won't even start if GPU acceleration is requested. It will log this message in the run.err file: `ERROR: you cannot use GPUs when skipping alignments`.
This might also happen for a 2D classification job, I haven't tried that.

The error message suggests the correct solution, but why not having the GPU acceleration option automatically set to "No" and greyed out in the GUI when the user turns off image alignment?
This is a trivial improvement, but it would feel much less like the program is trying to trip me up (which I am sure is not intended).

**Comment by biochem-fan** [comment]
Thank you very much for your suggestion. In the new version, the GUI raises an error before the job is actually submitted if GPU is enabled without image alignments.
