### ISSUE TITLE
Error in make

### ISSUE THREAD

**Issue by Zhengyanglee** [3dem/relion#358]
Dear all,
I have the similar error with issue #187 , however, I have no idea how to solve it. 
My system is Ubuntu 16.04 LTS, cuda version is 9.1, g++ version is 5.4.
Here is terminal output when I run cmake and make.
$ cmake -DCMAKE_INSTALL_PREFIX=/usr/local/relion -DCMAKE_C_COMPILER=/usr/bin/gcc-5 -DCMAKE_CXX_COMPILER=/usr/bin/g++-5 -DCUDA_ARCH=52 ..
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/gcc-5
-- Check for working C compiler: /usr/bin/gcc-5 -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/g++-5
-- Check for working CXX compiler: /usr/bin/g++-5 -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- BUILD TYPE set to the default type:  'Release'
-- Using provided CUDA_ARCH=52
-- Setting cpu precision to double
-- Setting gpu precision to single
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found CUDA: /usr (found version "7.5") 
-- Using cuda wrapper to compile....
-- Cuda version is >= 7.5 and single-precision build, enable double usage warning.
-- Found MPI_C: /usr/lib/openmpi/lib/libmpi.so  
-- Found MPI_CXX: /usr/lib/openmpi/lib/libmpi_cxx.so;/usr/lib/openmpi/lib/libmpi.so  
-- MPI_INCLUDE_PATH : /usr/lib/openmpi/include/openmpi/opal/mca/event/libevent2021/libevent;/usr/lib/openmpi/include/openmpi/opal/mca/event/libevent2021/libevent/include;/usr/lib/openmpi/include;/usr/lib/openmpi/include/openmpi
-- MPI_LIBRARIES : /usr/lib/openmpi/lib/libmpi_cxx.so;/usr/lib/openmpi/lib/libmpi.so
-- MPI_CXX_INCLUDE_PATH : /usr/lib/openmpi/include/openmpi/opal/mca/event/libevent2021/libevent;/usr/lib/openmpi/include/openmpi/opal/mca/event/libevent2021/libevent/include;/usr/lib/openmpi/include;/usr/lib/openmpi/include/openmpi
-- MPI_CXX_LIBRARIES : /usr/lib/openmpi/lib/libmpi_cxx.so;/usr/lib/openmpi/lib/libmpi.so
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Looking for IceConnectionNumber in ICE
-- Looking for IceConnectionNumber in ICE - found
-- Found X11: /usr/lib/x86_64-linux-gnu/libX11.so
-- Found FLTK: fltk_images;fltk_forms;fltk  
-- X11 and FLTK were found
-- FLTK_LIBRARIES: fltk_images;fltk_forms;fltk;/usr/lib/x86_64-linux-gnu/libSM.so;/usr/lib/x86_64-linux-gnu/libICE.so;/usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so;/usr/lib/x86_64-linux-gnu/libm.so
-- Found FFTW: fftw3
-- FFTW_LIBRARIES: /usr/lib/x86_64-linux-gnu/libfftw3.so
-- Looking for sincos
-- Looking for sincos - found
-- Looking for __sincos
-- Looking for __sincos - not found
-- Building shared libs (smaller build size and binaries)
-- CMAKE_BINARY_DIR:/home/lilab202/relion/build
-- added particle_reposition...
-- added manualpick...
-- added run_ctffind_mpi...
-- added preprocess...
-- added run_ctffind...
-- added localsym_mpi...
-- added pipeliner...
-- added particle_sort...
-- added mask_create...
-- added particle_symmetry_expand...
-- added particle_sort_mpi...
-- added refine_mpi...
-- added run_motioncorr...
-- added localsym...
-- added prepare_subtomo...
-- added refine...
-- added stack_create...
-- added run_motioncorr_mpi...
-- added display...
-- added reconstruct...
-- added tiltpair_plot...
-- added postprocess_mpi...
-- added maingui...
-- added helix_toolbox...
-- added star_combine...
-- added find_tiltpairs...
-- added ctf_toolbox...
-- added project...
-- added preprocess_mpi...
-- added postprocess...
-- added autopick...
-- added particle_polish_mpi...
-- added star_compare...
-- added particle_polish...
-- added autopick_mpi...
-- added image_handler...
-- Configuring done
-- Generating done
-- Build files have been written to: /home/lilab202/relion/build
---------------------------------------------------------------------------------------------------------------------------------
$ make -j4
Scanning dependencies of target copy_scripts
[  1%] Building NVCC (Device) object src/apps/CMakeFiles/relion_gpu_util.dir/__/gpu_utils/cuda_kernels/relion_gpu_util_generated_helper.cu.o
[  2%] Building NVCC (Device) object src/apps/CMakeFiles/relion_gpu_util.dir/__/gpu_utils/relion_gpu_util_generated_cuda_projector_plan.cu.o
[  3%] Building NVCC (Device) object src/apps/CMakeFiles/relion_gpu_util.dir/__/gpu_utils/relion_gpu_util_generated_cuda_benchmark_utils.cu.o
[  3%] Built target copy_scripts
[  3%] Building NVCC (Device) object src/apps/CMakeFiles/relion_gpu_util.dir/__/gpu_utils/relion_gpu_util_generated_cuda_backprojector.cu.o
/usr/include/string.h: In function ‘void* __mempcpy_inline(void*, const void*, size_t)’:
/usr/include/string.h:652:42: error: ‘memcpy’ was not declared in this scope
   return (char *) memcpy (__dest, __src, __n) + __n;
                                          ^
/usr/include/string.h: In function ‘void* __mempcpy_inline(void*, const void*, size_t)’:
/usr/include/string.h:652:42: error: ‘memcpy’ was not declared in this scope
   return (char *) memcpy (__dest, __src, __n) + __n;
                                          ^
/usr/include/string.h: In function ‘void* __mempcpy_inline(void*, const void*, size_t)’:
/usr/include/string.h:652:42: error: ‘memcpy’ was not declared in this scope
   return (char *) memcpy (__dest, __src, __n) + __n;
                                          ^
CMake Error at relion_gpu_util_generated_cuda_benchmark_utils.cu.o.cmake:266 (message):
  Error generating file
  /home/lilab202/relion/build/src/apps/CMakeFiles/relion_gpu_util.dir/__/gpu_utils/./relion_gpu_util_generated_cuda_benchmark_utils.cu.o

src/apps/CMakeFiles/relion_gpu_util.dir/build.make:70: recipe for target 'src/apps/CMakeFiles/relion_gpu_util.dir/__/gpu_utils/relion_gpu_util_generated_cuda_benchmark_utils.cu.o' failed
make[2]: *** [src/apps/CMakeFiles/relion_gpu_util.dir/__/gpu_utils/relion_gpu_util_generated_cuda_benchmark_utils.cu.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMake Error at relion_gpu_util_generated_cuda_backprojector.cu.o.cmake:266 (message):
  Error generating file
  /home/lilab202/relion/build/src/apps/CMakeFiles/relion_gpu_util.dir/__/gpu_utils/./relion_gpu_util_generated_cuda_backprojector.cu.o

src/apps/CMakeFiles/relion_gpu_util.dir/build.make:77: recipe for target 'src/apps/CMakeFiles/relion_gpu_util.dir/__/gpu_utils/relion_gpu_util_generated_cuda_backprojector.cu.o' failed
make[2]: *** [src/apps/CMakeFiles/relion_gpu_util.dir/__/gpu_utils/relion_gpu_util_generated_cuda_backprojector.cu.o] Error 1
CMake Error at relion_gpu_util_generated_helper.cu.o.cmake:266 (message):
  Error generating file
  /home/lilab202/relion/build/src/apps/CMakeFiles/relion_gpu_util.dir/__/gpu_utils/cuda_kernels/./relion_gpu_util_generated_helper.cu.o

src/apps/CMakeFiles/relion_gpu_util.dir/build.make:112: recipe for target 'src/apps/CMakeFiles/relion_gpu_util.dir/__/gpu_utils/cuda_kernels/relion_gpu_util_generated_helper.cu.o' failed
make[2]: *** [src/apps/CMakeFiles/relion_gpu_util.dir/__/gpu_utils/cuda_kernels/relion_gpu_util_generated_helper.cu.o] Error 1
/usr/include/string.h: In function ‘void* __mempcpy_inline(void*, const void*, size_t)’:
/usr/include/string.h:652:42: error: ‘memcpy’ was not declared in this scope
   return (char *) memcpy (__dest, __src, __n) + __n;
                                          ^
CMake Error at relion_gpu_util_generated_cuda_projector_plan.cu.o.cmake:266 (message):
  Error generating file
  /home/lilab202/relion/build/src/apps/CMakeFiles/relion_gpu_util.dir/__/gpu_utils/./relion_gpu_util_generated_cuda_projector_plan.cu.o

src/apps/CMakeFiles/relion_gpu_util.dir/build.make:63: recipe for target 'src/apps/CMakeFiles/relion_gpu_util.dir/__/gpu_utils/relion_gpu_util_generated_cuda_projector_plan.cu.o' failed
make[2]: *** [src/apps/CMakeFiles/relion_gpu_util.dir/__/gpu_utils/relion_gpu_util_generated_cuda_projector_plan.cu.o] Error 1
CMakeFiles/Makefile2:1151: recipe for target 'src/apps/CMakeFiles/relion_gpu_util.dir/all' failed
make[1]: *** [src/apps/CMakeFiles/relion_gpu_util.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
-------------------------------------------------------------------------------------------------------------------------------
Looking forward to your reply. Thank you very much.
Best wishes!

**Comment by biochem-fan** [comment]
Probably wrong combination of GCC and CUDA?
