### ISSUE TITLE
cmake fails on SGI UV 3000

### ISSUE THREAD

**Issue by Dan-Garrett** [3dem/relion#359]
Has anyone used Relion on an SGI UV or Altix based system?

Get following error when running cmake on command line on SGI UV 3000:
dgarrett@alto% cmake ..
-- BUILD TYPE set to the default type:  'Release'
-- Setting fallback CUDA_ARCH=35
-- Setting cpu precision to double
-- Setting gpu precision to single
CUDA_TOOLKIT_ROOT_DIR not found or specified
-- Could NOT find CUDA (missing: CUDA_TOOLKIT_ROOT_DIR CUDA_NVCC_EXECUTABLE CUDA_INCLUDE_DIRS CUDA_CUDART_LIBRARY) 
-- Using non-cuda compilation....
-- Could NOT find MPI_C (missing: MPI_C_LIB_NAMES MPI_C_WORKS) 
-- Could NOT find MPI_CXX (missing: MPI_CXX_LIB_NAMES MPI_CXX_WORKS) 
CMake Error at /usr/local/share/cmake-3.11/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find MPI (missing: MPI_C_FOUND MPI_CXX_FOUND)
Call Stack (most recent call first):
  /usr/local/share/cmake-3.11/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/share/cmake-3.11/Modules/FindMPI.cmake:1663 (find_package_handle_standard_args)
  CMakeLists.txt:161 (find_package)

-- Configuring incomplete, errors occurred!
See also "/net/dgarrett/Net/CryoEM/Relion/relion/build/CMakeFiles/CMakeOutput.log".
************************************************************************************************************************
************************************************************************************************************************
Attempt to set MPI_C_LIB_NAMES to libmpi results in following error:
dgarrett@alto% vi CMakeCache.txt
dgarrett@alto% cmake ..
-- BUILD TYPE set to the default type:  'Release'
-- Setting fallback CUDA_ARCH=35
-- Setting cpu precision to double
-- Setting gpu precision to single
CUDA_TOOLKIT_ROOT_DIR not found or specified
-- Could NOT find CUDA (missing: CUDA_TOOLKIT_ROOT_DIR CUDA_NVCC_EXECUTABLE CUDA_INCLUDE_DIRS CUDA_CUDART_LIBRARY) 
-- Using non-cuda compilation....
-- Could NOT find MPI_C (missing: MPI_libmpi_LIBRARY MPI_C_WORKS) 
-- Could NOT find MPI_CXX (missing: MPI_CXX_LIB_NAMES MPI_CXX_WORKS) 
CMake Error at /usr/local/share/cmake-3.11/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find MPI (missing: MPI_C_FOUND MPI_CXX_FOUND)
Call Stack (most recent call first):
  /usr/local/share/cmake-3.11/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/share/cmake-3.11/Modules/FindMPI.cmake:1663 (find_package_handle_standard_args)
  CMakeLists.txt:161 (find_package)

-- Configuring incomplete, errors occurred!
See also "/net/dgarrett/Net/CryoEM/Relion/relion/build/CMakeFiles/CMakeOutput.log".

**Comment by Dan-Garrett** [comment]
Problem was version of cmake.  Initially SGI did not have cmake installed.  I installed cmake version 3.11.1 which gave the errors reported above. Then I tried cmake version 2.8.3 which immediately gave an error that it was not supported.  Third time installed 2.8.12.2 which worked.  

The make then failed with: 
> checking whether C compiler accepts -mavx... no
> configure: error: Need a version of gcc with -mavx
> make[2]: *** [OWN_FFTW-prefix/src/OWN_FFTW-stamp/OWN_FFTW-configure] Error 1
> make[1]: *** [CMakeFiles/OWN_FFTW.dir/all] Error 2

**Comment by biochem-fan** [comment]
Not supported.
