### ISSUE TITLE
error in make after successful cmake

### ISSUE THREAD

**Issue by davidh99720** [3dem/relion#360]
Before the error, just a quick tip, if cmake report error and you have installed related packages but the error is still there, just rm -r * in the build folder and cmake again, It will be working.

But, when I go to do make, below is the informaitons:

-- BUILD TYPE set to the default type:  'Release'
-- Setting fallback CUDA_ARCH=35
-- Setting cpu precision to double
-- Setting gpu precision to single
-- Using cuda wrapper to compile....
-- Cuda version is >= 7.5 and single-precision build, enable double usage warning.
-- MPI_INCLUDE_PATH : /usr/include/mpich
-- MPI_LIBRARIES : /usr/lib/x86_64-linux-gnu/libmpichcxx.so;/usr/lib/x86_64-linux-gnu/libmpich.so
-- MPI_CXX_INCLUDE_PATH : /usr/include/mpich
-- MPI_CXX_LIBRARIES : /usr/lib/x86_64-linux-gnu/libmpichcxx.so;/usr/lib/x86_64-linux-gnu/libmpich.so
-- Found previously built non-system FLTK libraries that will be used.
-- FLTK_INCLUDE_DIR: /home/cyhuang/relion/external/fltk/include
-- FLTK_LIBRARIES:   /home/cyhuang/relion/external/fltk/lib/libfltk.so
-- No FFTW installation was found
-- Found previously built non-system FFTW libraries that will be used.
-- FFTW_INCLUDES:     /home/cyhuang/relion/external/fftw/include
-- FFTW_LIBRARIES:    /home/cyhuang/relion/external/fftw/lib/libfftw3.so
-- Building shared libs (smaller build size and binaries)
-- CMAKE_BINARY_DIR:/home/cyhuang/relion/build
-- added display...
-- added particle_symmetry_expand...
-- added helix_toolbox...
-- added project...
-- added find_tiltpairs...
-- added prepare_subtomo...
-- added run_motioncorr...
-- added refine...
-- added tiltpair_plot...
-- added star_compare...
-- added particle_polish...
-- added pipeliner...
-- added refine_mpi...
-- added localsym...
-- added run_motioncorr_mpi...
-- added run_ctffind_mpi...
-- added manualpick...
-- added postprocess...
-- added reconstruct...
-- added mask_create...
-- added star_combine...
-- added preprocess_mpi...
-- added postprocess_mpi...
-- added particle_sort...
-- added particle_sort_mpi...
-- added preprocess...
-- added stack_create...
-- added run_ctffind...
-- added autopick_mpi...
-- added autopick...
-- added particle_polish_mpi...
-- added particle_reposition...
-- added maingui...
-- added ctf_toolbox...
-- added image_handler...
-- added localsym_mpi...
-- Configuring done
-- Generating done
-- Build files have been written to: /home/cyhuang/relion/build
[  0%] Built target copy_scripts
[  1%] Building NVCC (Device) object src/apps/CMakeFiles/relion_gpu_util.dir/__/gpu_utils/cuda_kernels/relion_gpu_util_generated_helper.cu.o
/usr/include/string.h: In function ‘void* __mempcpy_inline(void*, const void*, size_t)’:
/usr/include/string.h:652:42: error: ‘memcpy’ was not declared in this scope
   return (char *) memcpy (__dest, __src, __n) + __n;
                                          ^
CMake Error at relion_gpu_util_generated_helper.cu.o.cmake:266 (message):
  Error generating file
  /home/cyhuang/relion/build/src/apps/CMakeFiles/relion_gpu_util.dir/__/gpu_utils/cuda_kernels/./relion_gpu_util_generated_helper.cu.o

src/apps/CMakeFiles/relion_gpu_util.dir/build.make:2506: recipe for target 'src/apps/CMakeFiles/relion_gpu_util.dir/__/gpu_utils/cuda_kernels/relion_gpu_util_generated_helper.cu.o' failed
make[2]: *** [src/apps/CMakeFiles/relion_gpu_util.dir/__/gpu_utils/cuda_kernels/relion_gpu_util_generated_helper.cu.o] Error 1
CMakeFiles/Makefile2:731: recipe for target 'src/apps/CMakeFiles/relion_gpu_util.dir/all' failed
make[1]: *** [src/apps/CMakeFiles/relion_gpu_util.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by davidh99720** [comment]
After checking other issues, and the instructions, the problem could be my GPU compute capability (version) is sm2.0 (for Quadro 600), which is lower than the lowest supported version of sm3.5.
https://en.wikipedia.org/wiki/CUDA

In that case, I wonder if I could still install and use relion without using GPU?
Or, as far as I know, older version of relion support lower GPU compute capability (version), maybe I could use them?

**Comment by bforsbe** [comment]
CUDA is not your issue in this case. It looks more like your version of gcc and/or glibc. Which version are you using? The gcc-version is listed at the beginning of the cmake-output after a clean config. 

About sm35; older versions of relion do NOT support lower sm. But even if your gpu is older than sm35, you can still build relion with gpu-support. You just can't run it on that gpu.

**Comment by davidh99720** [comment]
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
Is this what you mean?

**Comment by bforsbe** [comment]
Yes. I don't KNOW that this is your issue, but it's clearly related to gcc. I'd suggest installing and then using an earlier version of gcc. Version 4.8.2 is what we used for a long time, but if it's down to your system config and libs, the problem might persist. It's really difficult to say specifically why it's not finding standard library functions; I'm afraid I can't  be more specific without the computer in front of me.

**Comment by radha-chauhan** [comment]
I also have exactly same problem. tried to rerun cmake using GCC vervion 4.8.5 but still not successfull.
 The configuration of my system is GEForce GTX1080 Ti, Ubuntu 16.0.4 and CUDA is 7.5
