### ISSUE TITLE
Bug in 2d classification

### ISSUE THREAD

**Issue by alncat** [3dem/relion#362]
Hi, I found a bug in the function, 

**template<bool failsafe,typename weights_t>
__global__ void cuda_kernel_exponentiate_weights_coarse**

. You haven't loaded the correct prior probabilities of offsets and orientations of each class during the conversion from difference to weight. A correct implementation is shown below, 
<img width="761" alt="image" src="https://user-images.githubusercontent.com/3967300/40281177-7d73d0e8-5c23-11e8-924d-5ff87099f9a0.png">
We should add the classwise shift to the iorient before loading the prior probability of this orient, and the same modification is also applied to the itrans variable in my code above. This bug will result in all zero probabilities in certain circumstances in 2d classification.

**Comment by bforsbe** [comment]
Actually, 0-populated classes shouldn't cause any issues, since they are recognized and avoided. It needs to be a non-zero but low-populated class, which is pretty rare.
