### ISSUE TITLE
problem with ctffind4.1.10 and relion 2.1.0 - "cannot find line with Cs[mm], HT[kV], etc values in mic1_ctffind3.log"

### ISSUE THREAD

**Issue by user34754** [3dem/relion#364]
As the title says, I am having an issue with the ctffind4. I believe it is an issue with relion and not ctffind4, because I can run ctffind4 from terminal and works fine (albeit slowly). Running Ubuntu 16.04 (LTS) and as far as I know I have installed everything I need to for the two programs to work correctly. This is the command:
 *** The command is:
`which relion_run_ctffind` --i Import/job010/my_images.star --o CtfFind/job019/ --CS 2 --HT 200 --AmpCnst 0.1 --XMAG 10000 --DStep 1.4 --Box 512 --ResMin 30 --ResMax 5 --dFMin 5000 --dFMax 50000 --FStep 500 --dAst 100 --ctffind_exe ../ctffind-4.1.10/ctffind --ctfWin -1 --is_ctffind4  

and the error:
 Using CTFFINDs executable in: ../ctffind-4.1.10/ctffind
 to estimate CTF parameters for the following micrographs: 
  * mic1
  * mic2
  * mic3
  * mic4
  * mic5
  * mic6
  * mic7
  * mic8
  * mic9
  * mic10
  * mic11
  * mic12
  * mic13
  * mic14
  * mic15
  * mic16
  * mic17
  * mic18
  * mic19
  * mic20
  * mic21
  * mic22
  * mic23
  * mic24
  * mic25
 Estimating CTF parameters using Niko Grigorieff's CTFFIND ...
   0/   0 sec ............................................................~~(,_,">
ERROR: cannot find line with Cs[mm], HT[kV], etc values in mic1_ctffind3.log
File: src/ctffind_runner.cpp line: 297

**Comment by biochem-fan** [comment]
Sorry for very late reply. Please try RELION 3.0 beta and if it still happens, please let us know.
