### ISSUE TITLE
Error with Rank Distribution on GPU Cluster

### ISSUE THREAD

**Issue by grice12** [3dem/relion#367]
I am processing on a GPU cluster across 6 nodes each equipped with 2 Nvidia V100's and 28 Intel 6132 CPU cores with an allocated RAM limit of 600GB and the latest version of relion. For 2D classes, based on the number of particles I was classifying I calculated I could use 42 MPI processes and made the submission script below and it successfully ran quite quickly. Examining the output file however, it appears that while the resource manager recognised both GPUs on each node every MPI worker was mapped to one GPU rather than properly being distributed between the two available GPUs as is the default behaviour for SLURM. The result of this is 6 nodes each with 7 ranks on the first GPU on each node and 0 ranks on the second GPU on each node as opposed to 4 ranks on the first GPU and 3 ranks on the second GPU. This issue persists when explicitly specifying the distribution type in the submission script (block/cyclic/plane). 

#!/bin/bash
#SBATCH --job-name=Class2D
#SBATCH --nodes=6
#SBATCH --ntasks=42
#SBATCH --mem-per-cpu=14g
#SBATCH --cpus-per-task=1
#SBATCH --ntasks-per-node=7
#SBATCH --partition=gpu
#SBATCH --gres=gpu:tesla:2
#SBATCH --error=/nvmescratch/Gavin/Dataset_1/Class2D/job119/relion_run.err
#SBATCH --output=/nvmescratch/Gavin/Dataset_1/Class2D/job119/relion_run.out
 
module load gnu/5.4.0
module load mvapich2/2.2
module load cuda/9.1.85.3
module load relion
module load pmix

srun -n 42 --mpi=pmi2 `which relion_refine_mpi` --o /nvmescratch/Gavin/Dataset_1/Class2D/job119/run --i /nvmescratch/Gavin/Dataset_1/Select/job119/particles.star --dont_combine_weights_via_disc --preread_images  --pool 3 --ctf  --ctf_intact_first_peak  --iter 25 --tau2_fudge 2 --particle_diameter 200 --K 250 --flatten_solvent  --zero_mask  --strict_highres_exp 10 --oversampling 1 --psi_step 12 --offset_range 5 --offset_step 2 --norm --scale  --j 1 --gpu "0 1"

 === RELION MPI setup ===
 + Number of MPI processes             = 42
 + Master  (0) runs on host            = gpunode-0-4
 + Slave     7 runs on host            = gpunode-0-5
 + Slave    14 runs on host            = gpunode-0-6
 + Slave    21 runs on host            = gpunode-0-7
 + Slave    28 runs on host            = gpunode-0-8
 + Slave    35 runs on host            = gpunode-0-9
 + Slave     1 runs on host            = gpunode-0-4
 + Slave    15 runs on host            = gpunode-0-6
 + Slave     2 runs on host            = gpunode-0-4
 + Slave     8 runs on host            = gpunode-0-5
 + Slave    16 runs on host            = gpunode-0-6
 + Slave     3 runs on host            = gpunode-0-4
 + Slave     9 runs on host            = gpunode-0-5
 + Slave    17 runs on host            = gpunode-0-6
 + Slave     4 runs on host            = gpunode-0-4
 + Slave    10 runs on host            = gpunode-0-5
 + Slave    18 runs on host            = gpunode-0-6
 + Slave    22 runs on host            = gpunode-0-7
 + Slave     5 runs on host            = gpunode-0-4
 + Slave    11 runs on host            = gpunode-0-5
 + Slave    19 runs on host            = gpunode-0-6
 + Slave    23 runs on host            = gpunode-0-7
 + Slave     6 runs on host            = gpunode-0-4
 + Slave    12 runs on host            = gpunode-0-5
 + Slave    20 runs on host            = gpunode-0-6
 + Slave    24 runs on host            = gpunode-0-7
 =================
 + Slave    13 runs on host            = gpunode-0-5
 + Slave    25 runs on host            = gpunode-0-7
 + Slave    26 runs on host            = gpunode-0-7
 + Slave    27 runs on host            = gpunode-0-7
 + Slave    29 runs on host            = gpunode-0-8
 + Slave    36 runs on host            = gpunode-0-9
 + Slave    30 runs on host            = gpunode-0-8
 + Slave    37 runs on host            = gpunode-0-9
 + Slave    31 runs on host            = gpunode-0-8
 + Slave    38 runs on host            = gpunode-0-9
 + Slave    32 runs on host            = gpunode-0-8
 + Slave    39 runs on host            = gpunode-0-9
 + Slave    33 runs on host            = gpunode-0-8
 + Slave    40 runs on host            = gpunode-0-9
 + Slave    34 runs on host            = gpunode-0-8
 + Slave    41 runs on host            = gpunode-0-9
 uniqueHost gpunode-0-4 has 6 ranks.
 uniqueHost gpunode-0-5 has 7 ranks.
 uniqueHost gpunode-0-6 has 7 ranks.
 uniqueHost gpunode-0-7 has 7 ranks.
 uniqueHost gpunode-0-8 has 7 ranks.
 uniqueHost gpunode-0-9 has 7 ranks.
 Using explicit indexing on slave 1 to assign devices  0 1
 Thread 0 on slave 1 mapped to device 0
 Using explicit indexing on slave 2 to assign devices  0 1
 Thread 0 on slave 2 mapped to device 0
 Using explicit indexing on slave 3 to assign devices  0 1
 Thread 0 on slave 3 mapped to device 0
 Using explicit indexing on slave 4 to assign devices  0 1
 Thread 0 on slave 4 mapped to device 0
 Using explicit indexing on slave 5 to assign devices  0 1
 Thread 0 on slave 5 mapped to device 0
 Using explicit indexing on slave 6 to assign devices  0 1
 Thread 0 on slave 6 mapped to device 0
 Using explicit indexing on slave 7 to assign devices  0 1
 Thread 0 on slave 7 mapped to device 0
 Using explicit indexing on slave 8 to assign devices  0 1
 Thread 0 on slave 8 mapped to device 0
 Using explicit indexing on slave 9 to assign devices  0 1
 Thread 0 on slave 9 mapped to device 0
 Using explicit indexing on slave 10 to assign devices  0 1
 Thread 0 on slave 10 mapped to device 0
 Using explicit indexing on slave 11 to assign devices  0 1
 Thread 0 on slave 11 mapped to device 0
 Using explicit indexing on slave 12 to assign devices  0 1
 Thread 0 on slave 12 mapped to device 0
 Using explicit indexing on slave 13 to assign devices  0 1
 Thread 0 on slave 13 mapped to device 0
 Using explicit indexing on slave 14 to assign devices  0 1
 Thread 0 on slave 14 mapped to device 0
 Using explicit indexing on slave 15 to assign devices  0 1
 Thread 0 on slave 15 mapped to device 0
 Using explicit indexing on slave 16 to assign devices  0 1
 Thread 0 on slave 16 mapped to device 0
 Using explicit indexing on slave 17 to assign devices  0 1
 Thread 0 on slave 17 mapped to device 0
 Using explicit indexing on slave 18 to assign devices  0 1
 Thread 0 on slave 18 mapped to device 0
 Using explicit indexing on slave 19 to assign devices  0 1
 Thread 0 on slave 19 mapped to device 0
 Using explicit indexing on slave 20 to assign devices  0 1
 Thread 0 on slave 20 mapped to device 0
 Using explicit indexing on slave 21 to assign devices  0 1
 Thread 0 on slave 21 mapped to device 0
 Using explicit indexing on slave 22 to assign devices  0 1
 Thread 0 on slave 22 mapped to device 0
 Using explicit indexing on slave 23 to assign devices  0 1
 Thread 0 on slave 23 mapped to device 0
 Using explicit indexing on slave 24 to assign devices  0 1
 Thread 0 on slave 24 mapped to device 0
 Using explicit indexing on slave 25 to assign devices  0 1
 Thread 0 on slave 25 mapped to device 0
 Using explicit indexing on slave 26 to assign devices  0 1
 Thread 0 on slave 26 mapped to device 0
 Using explicit indexing on slave 27 to assign devices  0 1
 Thread 0 on slave 27 mapped to device 0
 Using explicit indexing on slave 28 to assign devices  0 1
 Thread 0 on slave 28 mapped to device 0
 Using explicit indexing on slave 29 to assign devices  0 1
 Thread 0 on slave 29 mapped to device 0
 Using explicit indexing on slave 30 to assign devices  0 1
 Thread 0 on slave 30 mapped to device 0
 Using explicit indexing on slave 31 to assign devices  0 1
 Thread 0 on slave 31 mapped to device 0
 Using explicit indexing on slave 32 to assign devices  0 1
 Thread 0 on slave 32 mapped to device 0
 Using explicit indexing on slave 33 to assign devices  0 1
 Thread 0 on slave 33 mapped to device 0
 Using explicit indexing on slave 34 to assign devices  0 1
 Thread 0 on slave 34 mapped to device 0
 Using explicit indexing on slave 35 to assign devices  0 1
 Thread 0 on slave 35 mapped to device 0
 Using explicit indexing on slave 36 to assign devices  0 1
 Thread 0 on slave 36 mapped to device 0
 Using explicit indexing on slave 37 to assign devices  0 1
 Thread 0 on slave 37 mapped to device 0
 Using explicit indexing on slave 38 to assign devices  0 1
 Thread 0 on slave 38 mapped to device 0
 Using explicit indexing on slave 39 to assign devices  0 1
 Thread 0 on slave 39 mapped to device 0
 Using explicit indexing on slave 40 to assign devices  0 1
 Thread 0 on slave 40 mapped to device 0
 Using explicit indexing on slave 41 to assign devices  0 1
 Thread 0 on slave 41 mapped to device 0
Device 0 on gpunode-0-4 is split between 6 slaves
Device 0 on gpunode-0-5 is split between 7 slaves
Device 0 on gpunode-0-6 is split between 7 slaves
Device 0 on gpunode-0-7 is split between 7 slaves
Device 0 on gpunode-0-8 is split between 7 slaves
Device 0 on gpunode-0-9 is split between 7 slaves
 Running CPU instructions in double precision. 

Edit: grammar & solved a secondary issue internally.

**Comment by Fravadona** [comment]
It's quite complicated to debug your problem but here's a trivial error :  
--gpu "0 1" should be --gpu "0:1"
