### ISSUE TITLE
No orientation was found as better than any other (in 2D classification)

### ISSUE THREAD

**Issue by gpya** [3dem/relion#368]
I am processing a data set of a small protein (tetramer ~ 120 kDa) in nanodiscs. we have selected particles and did several rounds of 2D classification to remove bad particles but after 14 irterations it start to show following error.

NOTE: No more fail-safe warnings will be issued.

WARNING: Exception (ERROR:
No orientation was found as better than any other.

A particle image was compared to the reference and resulted in all-zero
weights (for all orientations). This should not happen, unless your data
has very special characteristics. This has historically happened for some
lower-precision calculations, but multiple fallbacks have since been
implemented. Please report this error to the relion developers at

                 github.com/3dem/relion/issues
 ) handled by switching to fail-safe mode.
NOTE: No more fail-safe warnings will be issued.

Here is the script i am using to run the job:

srun --mpi=pmix relion_refine_mpi --o Class2D/2dcls_run10/run --i ./Select/job107/particles.star --dont_combine_weights_via_disc --pool 50 --ctf --iter 50 --tau2_fudge 2 --particle_diameter 170 --K 25 --flatten_solvent --zero_mask --strict_highres_exp 8 --oversampling 1 --psi_step 12 --offset_range 5 --offset_step 2 --norm --scale --j 2 --gpu ""

Could you please help us to resolve the issue? What parameters should we change to address this problem?

Thanks
Gaya

**Comment by gpya** [comment]
Sorry i forgot to mentioned that this happens with current run but previously it went through properly.

**Comment by profilin** [comment]
We are experiencing this same issue on our GPU cluster. Has anyone contacted you with any information as to the root of this error?

**Comment by gpya** [comment]
> We are experiencing this same issue on our GPU cluster. Has anyone contacted you with any information as to the root of this error?

No

**Comment by biochem-fan** [comment]
Please look at this:
https://www3.mrc-lmb.cam.ac.uk/relion/index.php/FAQs#Refinement_or_Classification_crash_saying_.22No_orientation_was_found.22
