### ISSUE TITLE
Build with intel MKL fftw wrapper support

### ISSUE THREAD

**Issue by cron-weasley** [3dem/relion#369]
Dear Developer,
First thanks a lot for writing this powerful software.
I have a question, relion default using opensource fftw-3 with cmake, is there any way to choose the intel fftw wrapper with relion?
Thanks!

**Comment by bforsbe** [comment]
There will be in the upcoming version of RELION, We are actually making sure just now that MKL and is working as well as possible.

**Comment by cron-weasley** [comment]
So cool! Thanks!
And where could I download the beta version of MKL support relion?

**Comment by bforsbe** [comment]
You can't yet. We're busy with in-house beta atm, but hopefully we'll be able to go public-beta in not too long. As a sneak preview I can tell you that MKL will certainly have an impact, especially for larger box-sizes.

**Comment by cron-weasley** [comment]
Thanks a lot bforsbe !
Got it.

**Comment by biochem-fan** [comment]
Now supported.
