### ISSUE TITLE
Parentheses () in alias crashes and prevents reopening of GUI

### ISSUE THREAD

**Issue by rbehrouzi** [3dem/relion#372]
If one picks an alias containing ( or ), GUI will crash immediately upon job completion. User cannot open the GUI again, because the alias with () is now stored in default_pipeline.star and will cause GUI to crash again (due to a touch command). One will have to go manually edit default_pipeline.star.

sh: 1: Syntax error: "(" unexpected
ERROR: 
Filename::touch ERROR: Cannot open file: .Nodes/3/Select/class1-from-1_3D(regroup)/particles.star
File: /relion/src/filename.cpp line: 440

It's a good idea to put a check on alias box to prevent unacceptable characters.

**Comment by biochem-fan** [comment]
Hi, thank you very much for feedback. This makes sense. The fix will be included in RELION 3.0.

**Comment by biochem-fan** [comment]
Fixed in commit 4160e57 on the (internal) development branch.
