### ISSUE TITLE
Request to not have the default --o be the same as --i

### ISSUE THREAD

**Issue by daniel-s-d-larsson** [3dem/relion#374]
It is really annoying to have the --i file to be overwritten if not --o is given in e.g. relion_image_handler and other tools.

**Comment by biochem-fan** [comment]
Hi, the default for `--o` in `relion_image_handler` has been changed in the new version. Please wait for public beta testing. Which other tools do you mean?

**Comment by daniel-s-d-larsson** [comment]
That's great. I think this is the case for several tools that can write micrographs. E.g. relion_display and relion_particle_sort.

**Comment by biochem-fan** [comment]
OK, I changed the default output file name for `relion_particle_sort` to `sorted.star`. I think `relion_display` is fine; it doesn't write anything when `--fn_imgs` or `--fn_parts` are missing.
