### ISSUE TITLE
How does Relion calculate the 2D class averages using the star file

### ISSUE THREAD

**Issue by phonchi** [3dem/relion#375]
Dear developers:

After the 2D classification, there are *_model.star, *_classes.mrcs, *_data.star, *_optimizer.star, *_sampling.star files for each iterations.

I was wondering how does Relion obtain the class averages in *_classes.mrcs files from the *_data.star file. I see that there are _rlnAnglePsi,_rlnOriginX, _rlnOriginY and _rlnGroupNumber, which represents the orientations and class assignment for each raw particle in order to obtain the final 2D averages. My questions are below:

1) How can I get the weight of each raw particles that contribute to the corresponding class average?
2) How does Relion calculate the class averages if I know the class assignment, orientations and weight?

Thanks in advance!!

**Comment by biochem-fan** [comment]
Hi, 

The STAR file contains only the point estimate of orientations and class assignments. In `relion_refine`, however, we marginalise over all possible orientations and classes. Thus, you cannot re-calculate class averages easily. If you don't need marginalisation, you can use `relion_reconstruct` after splitting STAR files into classes.
