### ISSUE TITLE
A zero-size array was attempted to be made, which should not happen.

### ISSUE THREAD

**Issue by marcrm13** [3dem/relion#376]
Dear RELION developers,

I've started getting a lot of the following error:

"slave 13 encountered error: ERROR:
A zero-size array was attempted to be made, which should not happen.
This is a developer error message which you cannot fix
through changing the run config. Either your data is broken or
an unforseen combination of options was encountered. Please report
this error, the command used and a brief description to
the relion developers at

 github.com/3dem/relion/issues"

I could originally use this particle set for 2D classification and 3D classification but recently, keep getting the above error. Any advice?

Thanks,

Marc

**Comment by davboyer** [comment]
Hello,

I also received this error. It seems to happen during Class3D when the healpix number is bumped up to 5. I am using 1080Ti GPUs.

I first received an "out of memory" issue when using j=5 and healpix 5 (ERROR: CudaCustomAllocator out of memory). I tried to solve this by going down to j=3. But then I received the "zero-size array" error as posted above. I then stuck with j=3 and added --free_gpu_memory 125 to test if keeping a bit of free GPU memory might help. This helped me get one more iteration, but then on the next iteration I again got the "zero-size array" error. I have used j=5 and healpix 5 successfully before on a different dataset with the same version of Relion, but it appears this new data has triggered this bug.

Below is my most recent command which brings about the "zero-size array" message:

mpiexec --bind-to none `which relion_refine_mpi`  --o Class3D/tw_fast_384/run_neg2p3 --i Select/tw_fast/BoxSize_384_asym_Round2/particles.star --ref Class3D/tw_fast_384/run_neg2p4_ct100_it150_class001.mrc   --ini_high 30 --dont_combine_weights_via_disc --scratch_dir /scratch --pool 30 --ctf --ctf_corrected_ref --iter 200 --tau2_fudge 64 --particle_diameter 404 --K 1 --flatten_solvent --oversampling 1 --healpix_order 5 --offset_range 6 --offset_step 1 --sym C1 --norm --scale  --helix --helical_outer_diameter 200 --helical_nr_asu 8 --helical_twist_initial -2.307489 --helical_rise_initial 4.8 --helical_z_percentage 0.3  --sigma_psi 5 --j 3 --gpu "" --bimodal_psi --limit_tilt 30  --continue Class3D/tw_fast_384/run_neg2p3_ct87_it150_optimiser.star --free_gpu_memory 125

Any tips/ideas about this issue?

Thanks in advance,

David

**Comment by davboyer** [comment]
To follow-up, currently my problem was solved by running the exact same command as above except bumping down to j 2 and not using --free_gpu_memory.

**Comment by biochem-fan** [comment]
Too old issue.
