### ISSUE TITLE
CTF on RHEL/slurm

### ISSUE THREAD

**Issue by ncoudray** [3dem/relion#377]
Hi,

  I try to run the ctf correction on our new cluster but can't make it work with Relion (neither Ctffind, nor Gctf). This is the situation:
* when tested with the same images from the online command with the same modules loaded, GCTF and CTFFIND are working properly and generating the expected output.
* when run through relion, they fail in a different way:
   - for GCTF: the ###_gctf.log file associated with the images look ok (they end with "Processing done successfully." and the values are the same as those when gctf is ran through the command line). For example:
```
**************************************   LAST CYCLE    *************************************************************

   Defocus_U   Defocus_V       Angle        CCC
    27770.30    26124.32       10.84    0.090360  Final Values

Resolution limit estimated by EPA: RES_LIMIT 3.391 
Estimated Bfactor: B_FACTOR  16.96 
Processing done successfully.
```
However, the micrographs_ctf.star is empty and the run.err file generates: 
```
WARNING: cannot find line with Cs[mm], HT[kV], etc values in CtfFind/job066/movies_tif/nc0014_0099_gctf.log
 WARNING: skipping, since cannot get CTF values for MotionCorr/job033/movies_tif/nc0014_0099.mrc
```
   - for CTFFIND 4.1.10: the error occurs already in the log file of the image. For example for nc0014_0099_ctffind4.log:
```
Input image file name                              : 
Error: File does not exist, please provide an existing file!
 Error: Running as script, and answer is not recognized..
```
Like for GCTF,  this behavior happens only when the job is submitted via Relion. Using ctffind directly from the terminal works fine.

We are using RHEL 7.4 (not sure if that matters).
If someone has an idea or suggestion what could have been wrong, that would be great,

Thanks,
Best,
Nicolas

**Comment by ncoudray** [comment]
Hi -

  OK, I think I partially found the reason (at least why ctffind is not working through relion):
The ".com" files created have the following header:
#!/usr/bin/env csh

but our cluster only works with bash.

Is there a way to have Relion generating scripts compatible with bash instead of csh?

Thanks,
Best,
Nicolas

**Comment by biochem-fan** [comment]
You can hack this line of the source code https://github.com/3dem/relion/blob/master/src/ctffind_runner.cpp#L474.

If you are not very confident about programming, it is probably easier to ask your system administrator to install csh to computing nodes.

**Comment by ncoudray** [comment]
Hi - thanks for the feedback. Our cluster administrator modified the code and now the code starts with "#!/usr/bin/env bash" but Relion is still generating the same error messages. Is there anything else in the code that would prevent it from running on bash, or red hat, or is system specific?

Thanks,
N.

**Comment by biochem-fan** [comment]
Hi, you also need to change https://github.com/3dem/relion/blob/master/src/ctffind_runner.cpp#L504. For Gctf, you need https://github.com/3dem/relion/blob/master/src/ctffind_runner.cpp#L563 and https://github.com/3dem/relion/blob/master/src/ctffind_runner.cpp#L618.

**Comment by ncoudray** [comment]
Great, thanks, will try this!

**Comment by biochem-fan** [comment]
But installing `csh` to the computing nodes might be easier. Otherwise, you have to edit these lines every time you update RELION. You can install `csh` to your home directory by yourself without root privileges.

**Comment by ncoudray** [comment]
Yes, thanks a lot for the advise.

**Comment by ncoudray** [comment]
Hi - 

so we did change the 4 lines suggested above (sorry but for technical reasons, we have to change the code and can't have csh installed yet). It works for ctffind, but doesn't seem to be sufficient to make gctf work:
it's the same status as before: the executable seems to be running and generating the outputs files (...l_EPA.log , ..._gctf.log, etc) but then, it doesn't aggregate the results properly. The "micrographs_ctf.star" file is empty and run.err shows these messages:

"WARNING: cannot find line with Cs[mm], HT[kV], etc values in CtfFind/job074/movies_tif/nc0014_0099_gctf.log
 WARNING: skipping, since cannot get CTF values for MotionCorr/job033/movies_tif/nc0014_0099.mrc"

Is there something else to change to make this part work, please?

**Comment by biochem-fan** [comment]
Sorry, the lines I pointed out above are for CTFFIND4 and CTFFIND3 (not used any more). For Gctf, csh is not explicitly used. What is the content of `CtfFind/job074/movies_tif/nc0014_0099_gctf.log`? Are there any errors? Does it really contain 'Cs[mm], HT[kV]' line?

**Comment by as7a5** [comment]
Hi,

It contans:
CS[mm], HT[kV], ac, XMAG, DStep[um]
  2.7    200.0    0.10  121107.3   14.000

And it does end with:
   Defocus_U   Defocus_V       Angle        CCC
    27768.31    26118.40       11.46    0.034593  Final Values

Resolution limit estimated by EPA: RES_LIMIT 3.296
Estimated Bfactor: B_FACTOR  17.05
Processing done successfully.

and there is no error on Gtcf side.

**Comment by as7a5** [comment]
BTW We are kind of locked in for BASH for our users. (our authentication system that defines default shell environment is managed by IT security. Is it possible to make the application aware of the default shell and install components accordingly for the case of motioncorr and gtcf and...?
Thanks

**Comment by biochem-fan** [comment]
The login shell does not matter. As long as you install csh to your home directory (say /home/as7a5/local/bin/csh) and put that in your PATH, relion should run fine without code modifications.

I don't know why the result from Gctf are not read, though.

**Comment by ncoudray** [comment]
Hi 
actually we do have csh in our path and env recognises it (/usr/bin/):

echo $PATH
**/usr/bin**:/gpfs/share/apps/relion/2.1_test/bin:/cm/shared/apps/cuda80/sdk/8.0.61/bin/x86_64/linux/release:/cm/shared/apps/cuda80/toolkit/8.0.61/bin:/gpfs/share/apps/tiff/3.9.7/bin:/cm/local/apps/cuda/libs/current/bin:/cm/shared/apps/cuda91/sdk/9.1.85/bin/x86_64/linux/release:/cm/shared/apps/cuda91/toolkit/9.1.85/bin:/gpfs/share/apps/openmpi/3.1.0/bin:/gpfs/share/apps/gcc/8.1.0/bin/:/cm/shared/apps/slurm/17.11.7/sbin:/cm/shared/apps/slurm/17.11.7/bin:/cm/local/apps/environment-modules/4.0.0//bin:/usr/local/bin:/usr/local/sbin:/usr/sbin:/sbin:/usr/sbin:/cm/local/apps/environment-modules/4.0.0/bin:/opt/ibutils/bin:/usr/lpp/mmfs/bin:/gpfs/home/coudrn01/.local/bin:/gpfs/home/coudrn01/bin:/usr/lpp/mmfs/bin:/gpfs/share/apps/gctf/1.18/bin/:/gpfs/share/apps/motioncor2/1.1:/gpfs/share/apps/ctffind/4.1.10//bin/

$ which csh
/usr/bin/csh

**Comment by biochem-fan** [comment]
Do you really have csh not only on the log-in node but also on the computing nodes?

This kind of problem is hard to analyse without detailed information about your cluster setup. I recommend you to ask your system admin.

**Comment by as7a5** [comment]
Hi biochem_fun,
Yes it exist on all compute nodes.
I appreciate your help.

**Comment by ncoudray** [comment]
OK, maybe the issue is coming from the compatibility with the latest GCTF version?  
We're using GCTF 1.18 and some parameters have slightly changed, it seems.

For example, in version 1.06, the parameters for Relion in the file named "###_gctf.log" appeared as 

```
********************************  parameter format for RELION: *********************************************

 CS[mm], HT[kV], AmpCnst, XMAG, DStep[um]
```
In version 1.18, it now appears as 

```
********************************  parameter format for RELION: *********************************************

 CS[mm], HT[kV], ac, XMAG, DStep[um]

```

There may be other changes... Have you noticed similar things with v 1.18 or is it working for you, biochem-fan? Would the renaming from "AmpCnst" to "ac" be enough to mess up things?

**Comment by biochem-fan** [comment]
I myself do not use Gctf but this change is enough to kill our wrapper. Could you please try changing the string in https://github.com/3dem/relion/blob/master/src/ctffind_runner.cpp#L677 to "CS[mm], HT[kV]" alone?

**Comment by ncoudray** [comment]
OK, it works now!
Thanks a lot for the help!

Regarding the original issue and as mentioned by our system admin above though, it would be amazing if relion were aware of the default shell and install components accordingly. Do you think that's something which would be possible for next release? 

Best,
Nicolas

**Comment by biochem-fan** [comment]
Thanks for testing. I will include this change to the RELION 3.0.

Regarding the shell, I don't understand why RELION (without code modification) failed to launch CTFFIND even when `/usr/bin/env csh` works. This issue is very system specific and I am afraid that I don't have time to support un-common configurations.

**Comment by ncoudray** [comment]
OK - FYI, I also informed Kai Zhang about it, in case he wants to adjust things on his side to make things more consistent.

**Comment by biochem-fan** [comment]
Are you using the latest Gctf 1.18 from https://www.mrc-lmb.cam.ac.uk/kzhang/Gctf/Gctf_v1.18/? At least cu7.5 and cu8.0 version write `AmpCnst` not `ac`.

**Comment by ncoudray** [comment]
No, those were not working for our cluster and he re-compiled one for us located in a different branch. 
But he just emailed me to confirm that it is a bug and he will be fixing it.

**Comment by biochem-fan** [comment]
I see. Then I will keep RELION unmodified since this is a site-specific issue and Kai's problem.
