### ISSUE TITLE
asymmetric reconstruction

### ISSUE THREAD

**Issue by chunyanyale** [3dem/relion#382]
A particle image was compared to the reference and resulted in all-zero
weights (for all orientations). This should not happen, unless your data
has very special characteristics. This has historically happened for some 
lower-precision calculations, but multiple fallbacks have since been 
implemented. Please report this error to the relion developers at 

	         github.com/3dem/relion/issues  
 ) handled by switching to fail-safe mode.
11.82/22.25 min ...............................~~(,_,">
WARNING: Exception (ERROR: 
No orientation was found as better than any other.

A particle image was compared to the reference and resulted in all-zero
weights (for all orientations). This should not happen, unless your data
has very special characteristics. This has historically happened for some 
lower-precision calculations, but multiple fallbacks have since been 
implemented. Please report this error to the relion developers at 

	         github.com/3dem/relion/issues  
 ) handled by switching to fail-safe mode.
20.13/22.22 min ....................................................~~(,_,">
..............~~(,_,">
WARNING: Exception (ERROR: 
No orientation was found as better than any other.

**Comment by wangnan161** [comment]
I will add a little angle to the tilt and restart the job.

**Comment by biochem-fan** [comment]
Old issue. Closing.
