### ISSUE TITLE
Multibody refinement: 

### ISSUE THREAD

**Issue by ss4858cu** [3dem/relion#385]
@biochem-fan 
[analyse_logfile.pdf](https://github.com/3dem/relion/files/2292063/analyse_logfile.pdf)

I have attached the logfile I get running 3D multi-body after consensus refinement. The point is the amplitude of the first eigen vector, is slightly skewed towards left. Do you think this qualifies for a continuous structural heterogeniety or is better described with discrete?

Thanks,

**Comment by biochem-fan** [comment]
I cannot give a definite answer without looking at your maps, but I would say this is a continuous structural change. With discrete changes, you will see two peaks.

Of course, there is no clear-cut boundary between continuous and discrete. Even when it looks 'discrete', there are always some residual fluctuations around each 'class'.
