### ISSUE TITLE
How to change MAX MPI setting 

### ISSUE THREAD

**Issue by qiaoqii** [3dem/relion#386]
Hi,

This may not be a new issue, but I did not find a solution from search. I have 20 cpu cores, with hyperthread, the max mpi I can set should be 40, but in fact, the max mpi by Relion is 20. More than that will return an error message saying RELION_ERROR_LOCAL_MPI not allowed. I tried "export RELION_MPI_MAX=40", but it did not work, any suggestion in how to change the max mpi limit? Thanks!

Qi

**Comment by biochem-fan** [comment]
Please set `RELION_ERROR_LOCAL_MPI=40` as well.

**Comment by qiaoqii** [comment]
I see, will try it. Thanks!

**Comment by qiaoqii** [comment]
It still does not run, after setting the value, the initial message was
gone, but a new error message showed in run.err.

There are not enough slots available in the system to satisfy the 40 slots
that were requested by the application:
  /usr/local/bin/relion_refine_mpi

Either request fewer slots for your application, or make more slots
available
for use.

Qi

**Comment by biochem-fan** [comment]
This error is not coming from RELION. It is from your MPI runtime.

**Comment by qiaoqii** [comment]
I see, I will ask the administrator to look at the OpenMPI installation.
Thanks!

Qi

**Comment by diffracteD** [comment]
> This error is not coming from RELION. It is from your MPI runtime.

It does not seem like a openmpi issue. Because My relion3.0 runs on 35 cpus, however, my relion3.1 can not go beyond 20 cpus. I have 40 cpus, so I'm making 20 cpus idle that way.
Also Cryosparc could run on 40 cpus when I tried.
So, I'm pretty sure it's not an openmpi or other issue but relion.

**Comment by biochem-fan** [comment]
@diffracteD

Do you mean the "There are not enough slots available in the system to satisfy the 40 slots` message? If so, it **IS** from OpenMPI. OpenMPI gets how many slots are available from the queue system. Probably your RELION job submission template is not configured properly.

**Comment by diffracteD** [comment]
My error says: "You're submitting a local job with 30 parallel processes. That's more than allowed by the RELION_ERROR_LOCAL_MPI environment variable."
It is strange to me because I used the same variables I used to install relion3.0 earlier and it used to run with 30 cpus. But I got this error since last update. The extraction job runs so slow because of this. Please suggest a way out.
Thanks.

**Comment by biochem-fan** [comment]
@diffracteD What is your current `RELION_ERROR_LOCAL_MP`?

**Comment by diffracteD** [comment]
> @diffracteD What is your current `RELION_ERROR_LOCAL_MPI`?

I'm not sure how to check.

**Comment by biochem-fan** [comment]
`echo $RELION_ERROR_LOCAL_MPI`

**Comment by diffracteD** [comment]
I don't get it but this command doesn't give me any output.

**Comment by biochem-fan** [comment]
This means you haven't set the variable. Please set it to the number of available cores. I won't explain how. Please study shell environmental variables.

**Comment by diffracteD** [comment]
> This means you haven't set the variable. Please set it to the number of available cores. I won't explain how. Please study shell environmental variables.

Thanks a lot for the suggestion. It worked to remove the error, however, when I try to run a 40 mpi extraction job I'm stuck with 'not enough slots available'. I'm not sure if that is because I already have something running with 10 cpus.

**Comment by biochem-fan** [comment]
Please read above comments carefully. `You're submitting a local job with X parallel processes. That's more than allowed by the RELION_ERROR_LOCAL_MPI environment variable.` is a check by RELION and can be adjusted by the `RELION_ERROR_LOCAL_MPI` variable . `Not enough slots avaialble` is a check by OpenMPI runtime and `RELION_ERROR_LOCAL_MPI` does not control it. This is managed by the queue system.
