### ISSUE TITLE
Relion 3.0 3D classification issue with fast subset 

### ISSUE THREAD

**Issue by qiaoqii** [3dem/relion#388]
Hi,

I am doing a 3D classification with 450k particles in cisTEM and Relion 3.0. Same particle stack, reference and N were used. cisTEM returned reasonable result, I got 4 classes with 13%, 48%, 16% and 22% distribution, the map also make sense. But Relion with fast subset option returned strange result, one class has 99.5% particles but the map is much worse than cisTEM result. The distribution of Relion was more even in the early iterations, but the major class gain 90% particles gradually before iteration 8.

I am wondering if this is because of the fast subset function or some mishandling when importing the particle stack from cisTEM to Relion. Relion command attached below, particle transfer from cisTEM to relion just followed the cisTEM export procedure and directly use the generated mrcs and star file as input of Relion 3D classification. 

 Please let me know if other information is required, thanks! 

`which relion_refine_mpi` --o Class3D/job140/run --i cisTEM/avb1_mAb42_Fab_Full_Dataset/cisTEM2D_R3_466k.star --ref cisTEM/avb1_mAb42_Fab_Full_Dataset/Assets/Volumes/volume_32_1.mrc --firstiter_cc --ini_high 60 --dont_combine_weights_via_disc --no_parallel_disc_io --pool 100 --pad 2  --ctf --iter 25 --fast_subsets  --tau2_fudge 4 --particle_diameter 200 --K 4 --flatten_solvent --zero_mask --strict_highres_exp 8 --oversampling 1 --healpix_order 2 --offset_range 5 --offset_step 2 --sym C1 --norm --scale  --j 6 --gpu ""

**Comment by biochem-fan** [comment]
Fast subset routine has been improved since then.
