### ISSUE TITLE
multi-body refinement: split dataset

### ISSUE THREAD

**Issue by ss4858cu** [3dem/relion#390]
Hi,

I have finished running one round of multi-body refinement followed by flex-analyze. I now want to split the dataset into 2, based on the amplitudes along first eigen vector. While running the program as a continuation from the last optimiser.star, its taking all the time it would for the last iteration.
Is there a way i could ask the program to just run the analysis to split the particles based on values from the previous run?

Thanks,
Shikha

**Comment by biochem-fan** [comment]
Hi Shikha,

The trick is to leave `Continue from here:` empty and press `Continue`. Then only FlexAnalyser will be executed again. Unfortunately, this overwrites old outputs from your previous FlexAnalyser run, so you have to manually backup them. Indeed this is bit cumbersome, and I will think about GUI improvement (but will not be in 3.0).

**Comment by ss4858cu** [comment]
Wow, that was such a quick fix. Thanks so much, I can live with it until we have it incorporated into relion3+n.

**Comment by ss4858cu** [comment]
Also, there was something related to this that I wanted to ask:
The  amplitudes along different eigen vectors are output as .eps files. Is there a way I could get .dat files for these?

**Comment by biochem-fan** [comment]
Yes, use `--write_pca_projections` in relion_flex_analyser (not available from the GUI).

This feature was implemented just two weeks ago. If your local copy is old, please update and re-compile it.
