### ISSUE TITLE
Motion Correction of Relion 3.0 for Super-resolution Krios data

### ISSUE THREAD

**Issue by PeterXTH** [3dem/relion#392]
When I am using Relion3.0's own motion correction for the Super-resolution data with Binning Factor 2. It is very slow and shows message of "XXX.mrc: too few valid local trajectories to fit local motion model". So I check the corrected image. It is 5x5 pathes of the same image and the log file shows very high error i.e. 50.
Does anyone know how to set the parameters for this super resolution data? Thanks.

**Comment by biochem-fan** [comment]
About performance:
- What is your CPU and how much memory do you have? 
- What is the number of threads and MPI processes?
- How many frames per movie?

About trajectories:
- What is the dose rate?
- "the log file shows very high error i.e. 50": Is this for global fitting or local fitting?

**Comment by PeterXTH** [comment]
I just used one node of GPU cluster (it has 28 cores with 2 thread each) with 385G memory.
So I used 20 cores, total 40 threads for calculation.
The moive has 30 frame with dose rate 1.42 e/A2.
I can run the normal Krios data with 1.074 A/pix, could not run the super-resolution movies with 0.537A/pix. 
I tried motioncorr2. It works fine.

**Comment by biochem-fan** [comment]
> So I used 20 cores, total 40 threads for calculation.
Do you mean 20 MPI processes x 2 threads each?

`--early_binning` will improve the performance but it will not solve the `too few trajectories` issue.
What happens if you try 4 x 4  patches?

For super-resolution movies, UCSF MotionCor2 is usually faster than ours.

See also https://github.com/3dem/relion/issues/383.

**Comment by PeterXTH** [comment]
I tried --early_binning. It showed some error and stopped the program.
"in: /primary/vari/software/relion/relion3_mpich/src/motioncorr_runner.cpp, line 2219
terminate called after throwing an instance of 'RelionError'"
The outcome image is really weird, like this:
![image](https://user-images.githubusercontent.com/20891363/44731331-f66b6700-aab0-11e8-896b-b547023fec01.png)

**Comment by biochem-fan** [comment]
Did you use the latest code from the repository? I fixed a bug with `--early_binning` on August 18th.

**Comment by PeterXTH** [comment]
Our IT department installed the software for all EM users. So, I am not sure what version the code is. Probably not as new as Aug 18.

**Comment by biochem-fan** [comment]
OK, then please try the latest version (ask IT admin to do it or install yourself under your home directory).
