### ISSUE TITLE
Class3D crashes in Relion2.1

### ISSUE THREAD

**Issue by hervecelia** [3dem/relion#393]
I got the following error while performing a 3D classification using Relion2.1.0 on a cluster node.
It eventually worked using Relion3.0

The submitted script that was used with Relion2.1.0 is the following:

______________________________________________________
#!/bin/bash
#SBATCH --ntasks=32
#SBATCH --partition=gpu --constraint=gpuk80
#SBATCH --cpus-per-task=4
#SBATCH --error=Class3D/job087/run.err
#SBATCH --output=Class3D/job087/run.out
#SBATCH --time=1-00:00:00
#SBATCH --mem-per-cpu=24g --mem=240g
#SBATCH --gres=lscratch:200,gpu:k80:4
#SBATCH --nodes=8 --ntasks-per-node=4
#SBATCH 
#SBATCH 
source restrict_tcp_for_mpi.sh
source add_extra_MPI_task.sh
env | sort
srun --mem-per-cpu=24g --mem=240g --mpi=pmi2 `which relion_refine_mpi` --o Class3D/job087/run --i Select/job075/particles.star --ref Import/
job085/ref160_C5.mrc --ini_high 30 --dont_combine_weights_via_disc --scratch_dir /lscratch/$SLURM_JOB_ID --pool 3 --ctf --ctf_corrected_ref 
--iter 25 --write_subsets 1 --subset_size 10000 --max_subsets 3 --tau2_fudge 4 --particle_diameter 120 --K 5 --flatten_solvent --zero_mask -
-strict_highres_exp 9 --oversampling 1 --healpix_order 2 --offset_range 5 --offset_step 2 --sym C1 --norm --scale  --j 4 --gpu "" 
______________________________________________________

slave 29 encountered error: ERROR: 
A zero-size array was attempted to be made, which should not happen.
This is a developer error message which you cannot fix 
through changing the run config. Either your data is broken or
an unforseen combination of options was encountered. Please report
this error, the command used and a brief description to
the relion developers at 

 github.com/3dem/relion/issues 

File: /usr/local/apps/RELION/git/2.1.0/src/gpu_utils/cuda_mem_utils.h line: 1435
slurmstepd: error: *** STEP 8274902.0 ON cn4172 CANCELLED AT 2018-08-26T16:26:25 ***
srun: Job step aborted: Waiting up to 32 seconds for job step to finish.
srun: error: cn4172: task 0: Killed
srun: error: cn4173: task 7: Killed
srun: error: cn4219: task 23: Killed
srun: error: cn4174: task 9: Killed
srun: error: cn4239: task 29: Exited with exit code 1
srun: error: cn4175: task 15: Killed
srun: error: cn4220: task 26: Killed
srun: error: cn4218: task 18: Killed
srun: error: cn4239: task 30: Killed
srun: error: cn4172: task 3: Killed
srun: error: cn4173: task 6: Killed
srun: error: cn4175: task 14: Killed
srun: error: cn4220: task 25: Killed
srun: error: cn4239: task 31: Killed
srun: error: cn4173: task 5: Killed
srun: error: cn4175: task 13: Killed
srun: error: cn4220: task 27: Killed
srun: error: cn4219: tasks 20,22: Killed
srun: error: cn4174: tasks 10-11: Killed
srun: error: cn4218: tasks 17,19: Killed
srun: error: cn4172: task 2: Killed
srun: error: cn4172: task 1: Killed
srun: error: cn4220: task 24: Killed
srun: error: cn4174: task 8: Killed
srun: error: cn4173: task 4: Killed
srun: error: cn4175: task 12: Killed
srun: error: Timed out waiting for job step to complete

**Comment by biochem-fan** [comment]
We will no longer fix bugs in RELION 2.1. Please let us know if the same problem happens in RELION 3.0.
