### ISSUE TITLE
make error on relion3 beta with cuda

### ISSUE THREAD

**Issue by dougbevan** [3dem/relion#394]
I'm getting the following error building relion3 beta with gpu support.  I can compile without cuda support with no problems.

cmake is 3.12.1, cuda 9.1, gcc 6.1

cmake command used: cmake -DFORCE_OWN_FFTW=ON cmake -DFORCE_OWN_FLTK=ON -DCMAKE_INSTALL_PREFIX=/opt/cryoem/relion3b/ ..

then I did:

make -j 14

---------------------------------------------

collect2: error: ld returned 1 exit status
make[2]: *** [bin/relion_autopick] Error 1
make[1]: *** [src/apps/CMakeFiles/autopick.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 78%] Linking CXX executable ../../bin/relion_particle_polish
[ 78%] Built target particle_polish
[ 79%] Linking CXX executable ../../bin/relion_helix_toolbox
[ 79%] Built target helix_toolbox
[ 79%] Linking CXX executable ../../bin/relion_mask_create
[ 79%] Built target mask_create
[ 79%] Linking CXX executable ../../bin/relion_postprocess_mpi
[ 79%] Linking CXX executable ../../bin/relion_localsym_mpi
[ 79%] Built target postprocess_mpi
[ 80%] Linking CXX executable ../../bin/relion_image_handler
[ 80%] Built target localsym_mpi
[ 80%] Built target image_handler
[ 80%] Linking CXX executable ../../bin/relion_ctf_toolbox
[ 80%] Built target ctf_toolbox
[ 80%] Linking CXX static library ../../lib/librelion_gui_lib.a
[ 80%] Built target relion_gui_lib
make: *** [all] Error 2

**Comment by bforsbe** [comment]
Depending on your OS and kernel, gcc 6 may be incompatible, see this list for the current (9.2) cuda version:

https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html

If downgrading gcc does not work, please provide the cmake and make output from a clean build (make a fresh build directory).

**Comment by dougbevan** [comment]
Set gcc to OS native version.  I still get a build error, though it is different...

cmake -DFORCE_OWN_FFTW=ON cmake -DFORCE_OWN_FLTK=ON -DCMAKE_INSTALL_PREFIX=/opt/cryoem/relion3b/ ..
-- The C compiler identification is GNU 4.4.7
-- The CXX compiler identification is GNU 4.4.7
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- BUILD TYPE set to the default type:  'Release'
-- Setting fallback CUDA_ARCH=35
-- CUDA enabled - Building CUDA-accelerated version of RELION
-- Setting cpu precision to double
-- Setting accelerated code precision to single
CMake Warning (dev) at CMakeLists.txt:133 (FIND_PACKAGE):
  Policy CMP0074 is not set: find_package uses <PackageName>_ROOT variables.
  Run "cmake --help-policy CMP0074" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  Environment variable CUDA_ROOT is set to:

    /cm/shared/apps/cuda91/toolkit/9.1.85

  For compatibility, CMake is ignoring the variable.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Found CUDA: /cm/shared/apps/cuda91/toolkit/9.1.85 (found version "9.1")
-- Using cuda wrapper to compile....
-- Cuda version is >= 7.5 and single-precision build, enable double usage warning.
-- CMAKE_C_COMPILER : /usr/bin/cc
-- CMAKE_CXX_COMPILER : /usr/bin/c++
-- MPI_C_COMPILER :
-- MPI_CXX_COMPILER :
-- CMAKE_CXX_COMPILER_ID : GNU
-- Found MPI_C: /cm/shared/apps/openmpi/gcc/64/1.10.1/lib64/libmpi.so (found version "3.0")
-- Found MPI_CXX: /cm/shared/apps/openmpi/gcc/64/1.10.1/lib64/libmpi_cxx.so (found version "3.0")
-- Found MPI: TRUE (found version "3.0")
-- MPI_INCLUDE_PATH : /cm/shared/apps/openmpi/gcc/64/1.10.1/include
-- MPI_LIBRARIES : /cm/shared/apps/openmpi/gcc/64/1.10.1/lib64/libmpi_cxx.so;/cm/shared/apps/openmpi/gcc/64/1.10.1/lib64/libmpi.so
-- MPI_CXX_INCLUDE_PATH : /cm/shared/apps/openmpi/gcc/64/1.10.1/include
-- MPI_CXX_LIBRARIES : /cm/shared/apps/openmpi/gcc/64/1.10.1/lib64/libmpi_cxx.so;/cm/shared/apps/openmpi/gcc/64/1.10.1/lib64/libmpi.so
-- Looking for XOpenDisplay in /usr/lib64/libX11.so;/usr/lib64/libXext.so
-- Looking for XOpenDisplay in /usr/lib64/libX11.so;/usr/lib64/libXext.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Looking for IceConnectionNumber in ICE
-- Looking for IceConnectionNumber in ICE - found
-- Found X11: /usr/lib64/libX11.so
-- Found previously built non-system FLTK libraries that will be used.
-- FLTK_INCLUDE_DIR: /home/linadmin/packages/relion-3.0_beta/external/fltk/include
-- FLTK_LIBRARIES:   /home/linadmin/packages/relion-3.0_beta/external/fltk/lib/libfltk.so
-- Found previously built non-system single precision FFTW libraries that will be used.
-- Found previously built non-system double precision FFTW libraries that will be used.
-- Looking for sincos
-- Looking for sincos - found
-- Looking for __sincos
-- Looking for __sincos - not found
-- Found TIFF: /usr/lib64/libtiff.so (found version "3.9.4")
BUILD_SHARED_LIBS = OFF
-- Building static libs (larger build size and binaries)
Running apps/CMakeLists.txt...
-- CMAKE_BINARY_DIR:/home/linadmin/packages/relion-3.0_beta/build
TIFF FOUND
-- Found OpenMP_C: -fopenmp (found version "3.0")
-- Found OpenMP_CXX: -fopenmp (found version "3.0")
-- Found OpenMP: TRUE (found version "3.0")
OPENMP FOUND
-- Configuring done
-- Generating done
-- Build files have been written to: /home/linadmin/packages/relion-3.0_beta/build

---------------------------------------------------------------------------

make
Scanning dependencies of target copy_scripts
[  0%] Built target copy_scripts
Scanning dependencies of target relion_lib
[  0%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/CPlot2D.cpp.o
[  1%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/args.cpp.o
[  1%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/assembly.cpp.o
[  1%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/autopicker.cpp.o
[  2%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/autopicker_mpi.cpp.o
[  2%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/backprojector.cpp.o
[  3%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/complex.cpp.o
[  3%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/ctf.cpp.o
[  3%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/ctffind_runner.cpp.o
[  4%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/ctffind_runner_mpi.cpp.o
[  4%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/error.cpp.o
[  5%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/euler.cpp.o
[  5%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/exp_model.cpp.o
[  6%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/fftw.cpp.o
[  6%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/filename.cpp.o
[  6%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/flex_analyser.cpp.o
[  7%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/funcs.cpp.o
[  7%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/healpix_sampling.cpp.o
[  8%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/helix.cpp.o
[  8%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/helix_inimodel2d.cpp.o
[  8%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/image.cpp.o
[  9%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/local_symmetry.cpp.o
[  9%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/local_symmetry_mpi.cpp.o
[ 10%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/mask.cpp.o
[ 10%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/matrix1d.cpp.o
[ 11%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/matrix2d.cpp.o
[ 11%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/memory.cpp.o
[ 11%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/metadata_container.cpp.o
[ 12%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/metadata_label.cpp.o
[ 12%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/metadata_table.cpp.o
[ 13%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/micrograph_model.cpp.o
[ 13%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/ml_model.cpp.o
[ 13%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/ml_optimiser.cpp.o
[ 14%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/ml_optimiser_mpi.cpp.o
[ 14%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/motioncorr_runner.cpp.o
[ 15%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/motioncorr_runner_mpi.cpp.o
[ 15%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/mpi.cpp.o
[ 15%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/multidim_array.cpp.o
[ 16%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/numerical_recipes.cpp.o
[ 16%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/parallel.cpp.o
[ 17%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/particle_polisher.cpp.o
[ 17%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/particle_polisher_mpi.cpp.o
[ 18%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/particle_sorter.cpp.o
[ 18%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/particle_sorter_mpi.cpp.o
[ 18%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/pipeline_jobs.cpp.o
[ 19%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/pipeliner.cpp.o
[ 19%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/postprocessing.cpp.o
[ 20%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/preprocessing.cpp.o
[ 20%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/preprocessing_mpi.cpp.o
[ 20%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/projector.cpp.o
[ 21%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/reconstructor.cpp.o
[ 21%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/reconstructor_mpi.cpp.o
[ 22%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/strings.cpp.o
[ 22%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/symmetries.cpp.o
[ 22%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/tabfuncs.cpp.o
[ 23%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/time.cpp.o
[ 23%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/transformations.cpp.o
[ 24%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/Healpix_2.15a/cxxutils.cc.o
[ 24%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/Healpix_2.15a/healpix_base.cc.o
[ 25%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/jaz/Fourier_helper.cpp.o
[ 25%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/jaz/Gaussian_pyramid.cpp.o
[ 25%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/jaz/aberration_fit.cpp.o
[ 26%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/jaz/backprojection_helper.cpp.o
[ 26%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/jaz/complex_io.cpp.o
[ 27%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/jaz/convolution_helper.cpp.o
[ 27%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/jaz/ctf_helper.cpp.o
[ 27%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/jaz/damage_helper.cpp.o
[ 28%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/jaz/distribution_helper.cpp.o
[ 28%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/jaz/fftw_helper.cpp.o
[ 29%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/jaz/filter_helper.cpp.o
[ 29%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/jaz/frame_merge.cpp.o
[ 30%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/jaz/fsc_helper.cpp.o
[ 30%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/jaz/image_log.cpp.o
[ 30%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/jaz/image_op.cpp.o
[ 31%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/jaz/imod_helper.cpp.o
[ 31%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/jaz/interpolation.cpp.o
[ 32%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/jaz/jaz_config.cpp.o
[ 32%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/jaz/local_motion_fit.cpp.o
[ 32%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/jaz/micrograph_handler.cpp.o
[ 33%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/jaz/new_ft.cpp.o
[ 33%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/jaz/noise_helper.cpp.o
[ 34%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/jaz/obs_model.cpp.o
[ 34%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/jaz/parallel_ft.cpp.o
[ 34%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/jaz/projection_helper.cpp.o
[ 35%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/jaz/reference_map.cpp.o
[ 35%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/jaz/refinement_helper.cpp.o
[ 36%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/jaz/refinement_program.cpp.o
[ 36%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/jaz/resampling_helper.cpp.o
[ 37%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/jaz/slice_helper.cpp.o
[ 37%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/jaz/spectral_helper.cpp.o
[ 37%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/jaz/stack_helper.cpp.o
[ 38%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/jaz/structure_tensor.cpp.o
[ 38%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/jaz/svd_helper.cpp.o
[ 39%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/jaz/t_complex.cpp.o
[ 39%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/jaz/tomo_stack.cpp.o
[ 39%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/jaz/volume_converter.cpp.o
[ 40%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/jaz/volume_integration.cpp.o
[ 40%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/jaz/vtk_helper.cpp.o
[ 41%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/jaz/optimization/gradient_descent.cpp.o
[ 41%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/jaz/optimization/lbfgs.cpp.o
[ 41%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/jaz/optimization/nelder_mead.cpp.o
[ 42%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/jaz/optimization/optimization.cpp.o
[ 42%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/jaz/ctf/ctf_refiner.cpp.o
[ 43%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/jaz/ctf/ctf_refiner_mpi.cpp.o
[ 43%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/jaz/ctf/defocus_estimator.cpp.o
[ 44%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/jaz/ctf/defocus_helper.cpp.o
[ 44%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/jaz/ctf/equation2x2.cpp.o
[ 44%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/jaz/ctf/magnification_estimator.cpp.o
[ 45%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/jaz/ctf/magnification_helper.cpp.o
[ 45%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/jaz/ctf/tilt_estimator.cpp.o
[ 46%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/jaz/ctf/tilt_helper.cpp.o
[ 46%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/jaz/motion/alignment_set.cpp.o
[ 46%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/jaz/motion/bfactor_estimator.cpp.o
[ 47%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/jaz/motion/frame_recombiner.cpp.o
[ 47%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/jaz/motion/gp_motion_fit.cpp.o
[ 48%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/jaz/motion/motion_estimator.cpp.o
[ 48%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/jaz/motion/motion_helper.cpp.o
[ 49%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/jaz/motion/motion_param_estimator.cpp.o
[ 49%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/jaz/motion/motion_refiner.cpp.o
[ 49%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/jaz/motion/motion_refiner_mpi.cpp.o
[ 50%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/jaz/motion/three_hyperparameter_fit.cpp.o
[ 50%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/jaz/motion/two_hyperparameter_fit.cpp.o
[ 51%] Building C object src/apps/CMakeFiles/relion_lib.dir/__/jaz/d3x3/dsyev2.c.o
[ 51%] Building C object src/apps/CMakeFiles/relion_lib.dir/__/jaz/d3x3/dsyevc3.c.o
[ 51%] Building C object src/apps/CMakeFiles/relion_lib.dir/__/jaz/d3x3/dsyevd3.c.o
[ 52%] Building C object src/apps/CMakeFiles/relion_lib.dir/__/jaz/d3x3/dsyevh3.c.o
[ 52%] Building C object src/apps/CMakeFiles/relion_lib.dir/__/jaz/d3x3/dsyevj3.c.o
[ 53%] Building C object src/apps/CMakeFiles/relion_lib.dir/__/jaz/d3x3/dsyevq3.c.o
[ 53%] Building C object src/apps/CMakeFiles/relion_lib.dir/__/jaz/d3x3/dsyevv3.c.o
[ 53%] Building C object src/apps/CMakeFiles/relion_lib.dir/__/jaz/d3x3/dsytrd3.c.o
[ 54%] Building C object src/apps/CMakeFiles/relion_lib.dir/__/jaz/d3x3/slvsec3.c.o
[ 54%] Building C object src/apps/CMakeFiles/relion_lib.dir/__/jaz/lbfgs/lbfgs.c.o
[ 55%] Linking CXX static library ../../lib/librelion_lib.a
[ 55%] Built target relion_lib
[ 55%] Building NVCC (Device) object src/apps/CMakeFiles/relion_gpu_util.dir/__/acc/cuda/relion_gpu_util_generated_cuda_projector_plan.cu.o
[ 55%] Building NVCC (Device) object src/apps/CMakeFiles/relion_gpu_util.dir/__/acc/cuda/relion_gpu_util_generated_cuda_autopicker.cu.o
[ 56%] Building NVCC (Device) object src/apps/CMakeFiles/relion_gpu_util.dir/__/acc/cuda/relion_gpu_util_generated_cuda_backprojector.cu.o
[ 56%] Building NVCC (Device) object src/apps/CMakeFiles/relion_gpu_util.dir/__/acc/cuda/relion_gpu_util_generated_cuda_benchmark_utils.cu.o
[ 56%] Building NVCC (Device) object src/apps/CMakeFiles/relion_gpu_util.dir/__/acc/cuda/relion_gpu_util_generated_cuda_helper_functions.cu.o
[ 57%] Building NVCC (Device) object src/apps/CMakeFiles/relion_gpu_util.dir/__/acc/cuda/cuda_kernels/relion_gpu_util_generated_helper.cu.o
[ 57%] Building NVCC (Device) object src/apps/CMakeFiles/relion_gpu_util.dir/__/acc/cuda/relion_gpu_util_generated_cuda_ml_optimiser.cu.o
[ 58%] Building NVCC (Device) object src/apps/CMakeFiles/relion_gpu_util.dir/__/acc/cuda/relion_gpu_util_generated_cuda_projector.cu.o
Scanning dependencies of target relion_gpu_util
[ 58%] Linking CXX static library ../../lib/librelion_gpu_util.a
[ 58%] Built target relion_gpu_util
Scanning dependencies of target tiltpair_plot
[ 58%] Building CXX object src/apps/CMakeFiles/tiltpair_plot.dir/tiltpair_plot.cpp.o
[ 59%] Linking CXX executable ../../bin/relion_tiltpair_plot
[ 59%] Built target tiltpair_plot
Scanning dependencies of target star_handler
[ 59%] Building CXX object src/apps/CMakeFiles/star_handler.dir/star_handler.cpp.o
[ 60%] Linking CXX executable ../../bin/relion_star_handler
[ 60%] Built target star_handler
Scanning dependencies of target stack_create
[ 60%] Building CXX object src/apps/CMakeFiles/stack_create.dir/stack_create.cpp.o
[ 61%] Linking CXX executable ../../bin/relion_stack_create
[ 61%] Built target stack_create
Scanning dependencies of target flex_analyse
[ 62%] Building CXX object src/apps/CMakeFiles/flex_analyse.dir/flex_analyse.cpp.o
[ 62%] Linking CXX executable ../../bin/relion_flex_analyse
[ 62%] Built target flex_analyse
Scanning dependencies of target localsym
[ 63%] Building CXX object src/apps/CMakeFiles/localsym.dir/localsym.cpp.o
[ 63%] Linking CXX executable ../../bin/relion_localsym
[ 63%] Built target localsym
Scanning dependencies of target particle_symmetry_expand
[ 63%] Building CXX object src/apps/CMakeFiles/particle_symmetry_expand.dir/particle_symmetry_expand.cpp.o
[ 64%] Linking CXX executable ../../bin/relion_particle_symmetry_expand
[ 64%] Built target particle_symmetry_expand
Scanning dependencies of target image_handler
[ 64%] Building CXX object src/apps/CMakeFiles/image_handler.dir/image_handler.cpp.o
[ 64%] Linking CXX executable ../../bin/relion_image_handler
[ 64%] Built target image_handler
Scanning dependencies of target relion_gui_lib
[ 65%] Building CXX object src/apps/CMakeFiles/relion_gui_lib.dir/__/displayer.cpp.o
[ 65%] Building CXX object src/apps/CMakeFiles/relion_gui_lib.dir/__/gui_entries.cpp.o
[ 66%] Building CXX object src/apps/CMakeFiles/relion_gui_lib.dir/__/gui_jobwindow.cpp.o
[ 66%] Building CXX object src/apps/CMakeFiles/relion_gui_lib.dir/__/gui_mainwindow.cpp.o
[ 67%] Building CXX object src/apps/CMakeFiles/relion_gui_lib.dir/__/manualpicker.cpp.o
[ 67%] Building CXX object src/apps/CMakeFiles/relion_gui_lib.dir/__/Healpix_2.15a/cxxutils.cc.o
[ 67%] Building CXX object src/apps/CMakeFiles/relion_gui_lib.dir/__/Healpix_2.15a/healpix_base.cc.o
[ 68%] Linking CXX static library ../../lib/librelion_gui_lib.a
[ 68%] Built target relion_gui_lib
Scanning dependencies of target maingui
[ 68%] Building CXX object src/apps/CMakeFiles/maingui.dir/maingui.cpp.o
[ 69%] Linking CXX executable ../../bin/relion_maingui
../../../external/fltk/lib/libfltk.so: undefined reference to `operator delete(void*, unsigned long)@CXXABI_1.3.9'
collect2: ld returned 1 exit status
make[2]: *** [bin/relion_maingui] Error 1
make[1]: *** [src/apps/CMakeFiles/maingui.dir/all] Error 2
make: *** [all] Error 2

**Comment by bforsbe** [comment]
Seems like a [known issue](https://github.com/ContinuumIO/anaconda-issues/issues/5191) related to  some standard libs , which i your case is required by FLTK.

**Comment by dougbevan** [comment]
Would the recommended solution be to compile FLTK separately?

**Comment by Fravadona** [comment]
If your Linux provides development packages for FLTK (at least version 1.3.3) then you can install them and it will work.
