### ISSUE TITLE
Relion GUI font problem

### ISSUE THREAD

**Issue by NFSaga** [3dem/relion#395]
I installed the Relion-2.1.0 stable on Ubuntu 16.04.5 following the instructions. However, the user interface font is weird (small, aliasing and difficult to read. Please see attached). I tried the installation of different versions of Relion (Relion-2.1.0 and Relion-3.0 beta) on different systems (Ubuntu 16.04 and Ubuntu 18.04). They all have the same problem. So what is missing from my systems, or is it a problem in the source code? Any suggestions are appreciated!

![relion-2 1 0_on_ubuntu-18 04_2](https://user-images.githubusercontent.com/42788963/44757134-833b1280-aafb-11e8-83a9-2432b3b255aa.png)

**Comment by biochem-fan** [comment]
This is by design. FLTK is a rather primitive GUI tool kit and uses bitmap fonts.
(But it has benefits of being lightweight even through X11 forwarding)

**Comment by NFSaga** [comment]
But previously when I installed relion-2.0.6, the fonts were much smoother and anti-aliasing. Which is also the case if I install from apt-get (relion-2.0.6). Is it because something changed regarding to the GUI in version 2.1.0?

**Comment by biochem-fan** [comment]
I don't know. Is it on the same system? Isn't it a high-DPI monitor?
Did you use `-DFORCE_OWN_FLTK=ON` for both?

**Comment by NFSaga** [comment]
The initial relion-2.0.6 was installed on Ubuntu 16.04.4, now I have upgraded to 16.04.5. It is not a high-DPI monitor. In the original installation, I did not specify -DFORCE_OWN_FLTK=ON. Now I have tried both ways; neither can give smooth GUI fonts...
I guess it is not that much big deal. Just thought you might have some quick fix. Thanks a lot!

**Comment by KHerb** [comment]
Hi, I am having the same exact issue that NFSaga had. I have identical machines and both have the same RELION version, except one has the font in the image posted while the other has a more refined/desired font. I have tried re-installing by specifying  -DFORCE_OWN_FLTK=ON and  -DFORCE_OWN_FLTK=OFF but did not have any luck. Is there a way to change fonts?

**Comment by biochem-fan** [comment]
As I wrote above, this is happening in FLTK, outside RELION. We cannot help.

How about comparing packages installed in your two computers? I guess one has more fonts than the other.

**Comment by KHerb** [comment]
It looks like FLTK versions are different. I will try reverting to the older version - 1.3.4 to see if that fixes the issue. Otherwise, I will look into FLTK documentation to potentially find an answer. Thanks!

**Comment by biochem-fan** [comment]
It is also worth checking which FLTK RELION is actually using by:
```
ldd `which relion`
```

**Comment by KHerb** [comment]
ldd for relion shows that both systems are using the same FLTK, even though fltk-config version for them are 1.3.4 and 1.3.5, respectively. When I compile, I notice that it doesn't recognize the existing FLTK library so instead it downloads it and tries to build from scratch. How can I point relion to the newer version?

**Comment by biochem-fan** [comment]
Please delete `external` folder before running `cmake`.

**Comment by KHerb** [comment]
Hmm, I have done that and I still get the following message:
-- -------- NO EXISTING FLTK LIBRARIES WHERE FOUND. -------
-- -------------- FLTK WILL BE DOWNLOADED AND -------------
-- --------------- BUILT DURING COMPILE-TIME. -------------
The commands I am running after deleting external are 

cd /usr/local/relion-3-source
rm -rf build
git clean -f -d -x
#git pull
git checkout ca101fab137eba76ae7f29071265cac7a929a936
mkdir build
cd build
cmake -DCUDA=ON -DCudaTexture=ON -DCUDA_ARCH=61 -DFORCE_OWN_FLTK=ON -DCMAKE_INSTALL_PREFIX=/usr/local/relion-3 ..
make -j8
make install
rm -rf *

**Comment by biochem-fan** [comment]
Because you are requesting`-DFORCE_OWN_FLTK=ON`, this is the right behavior.

I don't think the difference of FLTK 1.3.4 or 1.3.5 matters. Whatever version the system has, as long as you compile RELION with `-DFORCE_OWN_FLTK=ON` with fresh `external` directory and `ldd relion` points to RELION's own FLTK, it should be the same version, because `cmake` always download the same version. My concern was that if you had an old `external` folder from an old version of RELION, it might contain a different version.

> even though fltk-config version for them are 1.3.4 and 1.3.5

`which fltk-config`?

As I wrote above, did you confirm both systems have the same set of fonts? Are you sure both have the same font configuration? There are many font setting files which might be modified by other applications (there are so many that I cannot point).

**Comment by KHerb** [comment]
Thanks for your help biochem-fan, I figured it out. I had to issue yum remove fltk.x86_64 on the one computer which happened to be version 1.3.4 and not the version that was downloaded form the relion compiler. I then deleted the external folder and re-ran cmake which seemed to fix the problem. 

Thanks again :+1:

**Comment by biochem-fan** [comment]
Although I don't know why it solved the problem (because `ldd` pointed to the RELION's own FLTK, not system-wide FLTK), I'm glad to hear it. Thanks for reporting.
