### ISSUE TITLE
Make issue with Relion 3.0 beta

### ISSUE THREAD

**Issue by mspilman** [3dem/relion#396]
I've run into an issue when running make after a successful cmake. Initially I had issues with gcc version (7+) and  CUDA 8.0 (solved after reading previous issues) as well as cmake 3.9 causing problems. 

Any help would be appreciated.

System:
ubuntu 17.10
gcc 5.4.1
cmake 3.5.2

---- Command line output ----
CC=gcc-5 CXX=g++-5 /home/mspilman/Downloads/cmake-3.5.2-Linux-x86_64/bin/cmake -DCMAKE_INSTALL_PREFIX=/opt/Relion3_beta -DCUDA_ARCH=61 -DFORCE_OWN_FFTW=ON -DFORCE_OWN_FLTK=ON -DMPI_C_COMPILER=/usr/bin/mpicc -DMPI_CXX_COMPILER=/usr/bin/mpicxx -DTIFF_LIBRARY_RELEASE=/usr/lib/x86_64-linux-gnu/libtiff.so -DTIFF_INCLUDE_DIR=/usr/lib/x86_64-linux-gnu ..
-- The C compiler identification is GNU 5.4.1
-- The CXX compiler identification is GNU 5.4.1
-- Check for working C compiler: /usr/bin/gcc-5
-- Check for working C compiler: /usr/bin/gcc-5 -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/g++-5
-- Check for working CXX compiler: /usr/bin/g++-5 -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- BUILD TYPE set to the default type:  'Release'
-- Using provided CUDA_ARCH=61
-- CUDA enabled - Building CUDA-accelerated version of RELION
-- Setting cpu precision to double
-- Setting accelerated code precision to single
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found CUDA: /usr (found version "8.0") 
-- Using cuda wrapper to compile....
-- Cuda version is >= 7.5 and single-precision build, enable double usage warning.
-- CMAKE_C_COMPILER : /usr/bin/gcc-5
-- CMAKE_CXX_COMPILER : /usr/bin/g++-5
-- MPI_C_COMPILER : /usr/bin/mpicc
-- MPI_CXX_COMPILER : /usr/bin/mpicxx
-- CMAKE_CXX_COMPILER_ID : GNU
-- Found MPI_C: /usr/lib/x86_64-linux-gnu/libmpich.so  
-- Found MPI_CXX: /usr/lib/x86_64-linux-gnu/libmpichcxx.so;/usr/lib/x86_64-linux-gnu/libmpich.so  
-- MPI_INCLUDE_PATH : /usr/include/mpich
-- MPI_LIBRARIES : /usr/lib/x86_64-linux-gnu/libmpichcxx.so;/usr/lib/x86_64-linux-gnu/libmpich.so
-- MPI_CXX_INCLUDE_PATH : /usr/include/mpich
-- MPI_CXX_LIBRARIES : /usr/lib/x86_64-linux-gnu/libmpichcxx.so;/usr/lib/x86_64-linux-gnu/libmpich.so
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Looking for IceConnectionNumber in ICE
-- Looking for IceConnectionNumber in ICE - found
-- Found X11: /usr/lib/x86_64-linux-gnu/libX11.so
-- Found previously built non-system FLTK libraries that will be used.
-- FLTK_INCLUDE_DIR: /home/mspilman/Downloads/relion-3.0_beta/external/fltk/include
-- FLTK_LIBRARIES:   /home/mspilman/Downloads/relion-3.0_beta/external/fltk/lib/libfltk.so
-- Found previously built non-system single precision FFTW libraries that will be used.
-- Found previously built non-system double precision FFTW libraries that will be used.
-- Looking for sincos
-- Looking for sincos - found
-- Looking for __sincos
-- Looking for __sincos - not found
-- Found TIFF: /usr/lib/x86_64-linux-gnu/libtiff.so  
BUILD_SHARED_LIBS = OFF
-- Building static libs (larger build size and binaries)
Running apps/CMakeLists.txt...
-- CMAKE_BINARY_DIR:/home/mspilman/Downloads/relion-3.0_beta/build
TIFF FOUND
-- Try OpenMP C flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Try OpenMP CXX flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Found OpenMP: -fopenmp  
OPENMP FOUND
-- Configuring done
-- Generating done
-- Build files have been written to: /home/mspilman/Downloads/relion-3.0_beta/build
mspilman@DE-CryoEMProcessor:~/Downloads/relion-3.0_beta/build$ make
Scanning dependencies of target copy_scripts
[  0%] Built target copy_scripts
[  0%] Building NVCC (Device) object src/apps/CMakeFiles/relion_gpu_util.dir/__/acc/cuda/cuda_kernels/relion_gpu_util_generated_helper.cu.o
[  0%] Building NVCC (Device) object src/apps/CMakeFiles/relion_gpu_util.dir/__/acc/cuda/relion_gpu_util_generated_cuda_autopicker.cu.o
/home/mspilman/Downloads/relion-3.0_beta/src/rwMRC.h(371): error: namespace "std" has no member "isfinite"
          detected during:
            instantiation of "void Image<T>::_write(const FileName &, fImageHandler &, long, __nv_bool, int) [with T=double]" 
/home/mspilman/Downloads/relion-3.0_beta/src/image.h(450): here
            instantiation of "void Image<T>::write(FileName, long, __nv_bool, int) [with T=double]" 
/home/mspilman/Downloads/relion-3.0_beta/src/acc/cuda/cuda_autopicker.cu(659): here

/home/mspilman/Downloads/relion-3.0_beta/src/rwMRC.h(375): error: namespace "std" has no member "isfinite"
          detected during:
            instantiation of "void Image<T>::_write(const FileName &, fImageHandler &, long, __nv_bool, int) [with T=double]" 
/home/mspilman/Downloads/relion-3.0_beta/src/image.h(450): here
            instantiation of "void Image<T>::write(FileName, long, __nv_bool, int) [with T=double]" 
/home/mspilman/Downloads/relion-3.0_beta/src/acc/cuda/cuda_autopicker.cu(659): here

/home/mspilman/Downloads/relion-3.0_beta/src/rwMRC.h(376): error: namespace "std" has no member "isfinite"
          detected during:
            instantiation of "void Image<T>::_write(const FileName &, fImageHandler &, long, __nv_bool, int) [with T=double]" 
/home/mspilman/Downloads/relion-3.0_beta/src/image.h(450): here
            instantiation of "void Image<T>::write(FileName, long, __nv_bool, int) [with T=double]" 
/home/mspilman/Downloads/relion-3.0_beta/src/acc/cuda/cuda_autopicker.cu(659): here

/home/mspilman/Downloads/relion-3.0_beta/src/rwMRC.h(380): error: namespace "std" has no member "isfinite"
          detected during:
            instantiation of "void Image<T>::_write(const FileName &, fImageHandler &, long, __nv_bool, int) [with T=double]" 
/home/mspilman/Downloads/relion-3.0_beta/src/image.h(450): here
            instantiation of "void Image<T>::write(FileName, long, __nv_bool, int) [with T=double]" 
/home/mspilman/Downloads/relion-3.0_beta/src/acc/cuda/cuda_autopicker.cu(659): here

/home/mspilman/Downloads/relion-3.0_beta/src/rwMRC.h(384): error: namespace "std" has no member "isfinite"
          detected during:
            instantiation of "void Image<T>::_write(const FileName &, fImageHandler &, long, __nv_bool, int) [with T=double]" 
/home/mspilman/Downloads/relion-3.0_beta/src/image.h(450): here
            instantiation of "void Image<T>::write(FileName, long, __nv_bool, int) [with T=double]" 
/home/mspilman/Downloads/relion-3.0_beta/src/acc/cuda/cuda_autopicker.cu(659): here

/home/mspilman/Downloads/relion-3.0_beta/src/rwMRC.h(385): error: namespace "std" has no member "isfinite"
          detected during:
            instantiation of "void Image<T>::_write(const FileName &, fImageHandler &, long, __nv_bool, int) [with T=double]" 
/home/mspilman/Downloads/relion-3.0_beta/src/image.h(450): here
            instantiation of "void Image<T>::write(FileName, long, __nv_bool, int) [with T=double]" 
/home/mspilman/Downloads/relion-3.0_beta/src/acc/cuda/cuda_autopicker.cu(659): here

/home/mspilman/Downloads/relion-3.0_beta/src/rwMRC.h(389): error: namespace "std" has no member "isfinite"
          detected during:
            instantiation of "void Image<T>::_write(const FileName &, fImageHandler &, long, __nv_bool, int) [with T=double]" 
/home/mspilman/Downloads/relion-3.0_beta/src/image.h(450): here
            instantiation of "void Image<T>::write(FileName, long, __nv_bool, int) [with T=double]" 
/home/mspilman/Downloads/relion-3.0_beta/src/acc/cuda/cuda_autopicker.cu(659): here

/home/mspilman/Downloads/relion-3.0_beta/src/rwMRC.h(393): error: namespace "std" has no member "isfinite"
          detected during:
            instantiation of "void Image<T>::_write(const FileName &, fImageHandler &, long, __nv_bool, int) [with T=double]" 
/home/mspilman/Downloads/relion-3.0_beta/src/image.h(450): here
            instantiation of "void Image<T>::write(FileName, long, __nv_bool, int) [with T=double]" 
/home/mspilman/Downloads/relion-3.0_beta/src/acc/cuda/cuda_autopicker.cu(659): here

/home/mspilman/Downloads/relion-3.0_beta/src/rwMRC.h(394): error: namespace "std" has no member "isfinite"
          detected during:
            instantiation of "void Image<T>::_write(const FileName &, fImageHandler &, long, __nv_bool, int) [with T=double]" 
/home/mspilman/Downloads/relion-3.0_beta/src/image.h(450): here
            instantiation of "void Image<T>::write(FileName, long, __nv_bool, int) [with T=double]" 
/home/mspilman/Downloads/relion-3.0_beta/src/acc/cuda/cuda_autopicker.cu(659): here

9 errors detected in the compilation of "/tmp/tmpxft_000036b9_00000000-7_cuda_autopicker.cpp1.ii".
CMake Error at relion_gpu_util_generated_cuda_autopicker.cu.o.cmake:266 (message):
  Error generating file
  /home/mspilman/Downloads/relion-3.0_beta/build/src/apps/CMakeFiles/relion_gpu_util.dir/__/acc/cuda/./relion_gpu_util_generated_cuda_autopicker.cu.o

src/apps/CMakeFiles/relion_gpu_util.dir/build.make:63: recipe for target 'src/apps/CMakeFiles/relion_gpu_util.dir/__/acc/cuda/relion_gpu_util_generated_cuda_autopicker.cu.o' failed
make[2]: *** [src/apps/CMakeFiles/relion_gpu_util.dir/__/acc/cuda/relion_gpu_util_generated_cuda_autopicker.cu.o] Error 1
CMakeFiles/Makefile2:850: recipe for target 'src/apps/CMakeFiles/relion_gpu_util.dir/all' failed
make[1]: *** [src/apps/CMakeFiles/relion_gpu_util.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by mdppdm** [comment]
In case you or others are having problems with recent Ubuntu distros, here is what worked for me.
Ubuntu 18.04
cuda 9.1
gcc 6.4 (selected with update-alternatives)
cmake 3.9.0 (https://cmake.org/files/v3.9/)

**Comment by biochem-fan** [comment]
Probably no longer relevant.
