### ISSUE TITLE
autopicking option ignored when using Laplacian

### ISSUE THREAD

**Issue by ncoudray** [3dem/relion#397]
Hi -
  I am testing relion 3 on the tutorial's dataset and was using the LoG auto-picking method. It looks like none of the options from the autopicking tab have any effect:
* I modified stdev noise to 1.0, 1.2 and even 3.0 
* Minimum Avg noise to -0.5, and 0 

I know the images do not have carbon or much contamination but I would have expected some change. Are these options ignored? 
Also, it looks like the minimum inter-particles distance is ignored as well (I think this one is mentioned in the tutorial), but it would be useful to be able to set it, though

Thanks,
Nicolas

**Comment by ncoudray** [comment]
Ah, ok, thanks for the feedback. The manual only says "Ignore the References tab, and on the autopicking tab, the first two options will be ignored." so I thought that the noise thresholds would be taken into account.

Best
N.

**Comment by delarosatrevin** [comment]
So, none of the parameters in the "Autopicking tab" are used?
Personally, I find a bit misleading that when clicking "Print command" the
autopicking arguments are still shown in the command line.

Best,
Jose Miguel

**Comment by biochem-fan** [comment]
Thank you very much for pointing out the inconsistency. I will double-check this tomorrow and update the command line & tutorial accordingly.

**Comment by delarosatrevin** [comment]
Thanks a lot for the responsiveness! It is very much appreciated.
I double checked the command line and it seems that only '--write_fom_maps'
is printed from the "Autopicking tab" in the case of Laplacian.
There is also the "--shrink 0" always and the "--lowpass 20" (although it
is possible to change the Lowpass value in the "References" tab in
the Laplacian case).

I think it would be great for consistency that non-relevant options in
other tabs were greyed-out as it is the case with other parameters.

**Comment by biochem-fan** [comment]
Unfortunately, 'greying-out' does not work over multiple tabs (this is legacy of bad code design). I will update the help strings, though.

`shrink` and `lowpass` are indeed respected.

**Comment by delarosatrevin** [comment]
Ok, thanks for looking at this.

**Comment by bforsbe** [comment]
I noticed some inconsistencies in LoG-picking today as well - the inter-particle distance does not seem to be respected. I'll verify tomorrow or later this week unless someone can get to it before me.

**Comment by biochem-fan** [comment]
Minimum inter-particle distance in LoG picker is calculated from particle diameters, not the value in the `Autopicking` tab.

**Comment by bforsbe** [comment]
I just noticed that the picking was very overlapping and there was no way to make it change. I think that the minimum distance is a much easier way to "fix" such a situation than trying to tweak the LoG parameters. But I don't have a strong case here - I didn't try to optimize the LoG. The gaussian blob was easy for me to use, the LoG picker less so, so I ended up doing it the old way, quick 2D and use ref-based picking ; )

**Comment by scheres** [comment]
What was your minimum diameter for the log-picker?
S

> I just noticed that the picking was very overlapping and there was no way
> to make it change. I think that the minimum distance is a much easier way
> to "fix" such a situation than trying to tweak the LoG parameters. But I
> don't have a strong case here - I didn't try to optimize the LoG. The
> gaussian blob was easy for me to use, the LoG picker less so, so I ended
> up doing it the old way, quick 2D and use ref-based picking ; )
>
> --
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/3dem/relion/issues/397#issuecomment-420166789


-- 
Sjors Scheres
MRC Laboratory of Molecular Biology
Francis Crick Avenue, Cambridge Biomedical Campus
Cambridge CB2 0QH, U.K.
tel: +44 (0)1223 267061
http://www2.mrc-lmb.cam.ac.uk/groups/scheres

**Comment by bforsbe** [comment]
My particles are ~300Å, so I set the log-picking to min=250, max=350, based on the ?-boxes. I deleted the jobs since, but the pickings were severely clustered and overlapping in my case. Let me know if you want a repro-case or so.

**Comment by biochem-fan** [comment]
We updated the tutorial and clarified the help messages.

> `shrink` and `lowpass` are indeed respected.

This was my mistake. `shink` always becomes 0.

**Comment by ncoudray** [comment]
Thanks for updating the tutorial.

**Comment by biochem-fan** [comment]
The bug in LoG picker's inter-particle distance was fixed.
