### ISSUE TITLE
GPU Double precision on 3.0 Beta2?

### ISSUE THREAD

**Issue by miesav** [3dem/relion#399]
Hello,

I had a look at compiling Relion v3.0 beta 2 with double precision. I see the option -DoublePrec_GPU=ON is no longer available. Instead I notice this option has been added:

DoublePrec_ACC=ON 

However, Relion fails to compile with the option turned on with the following error:

[  0%] Building NVCC (Device) object src/apps/CMakeFiles/relion_gpu_util.dir/__/acc/cuda/cuda_kernels/relion_gpu_util_generated_helper.cu.o
[  0%] Built target copy_scripts
/software/relion-3.0_beta/src/acc/cuda/cuda_kernels/helper.cu(124): error: no operator "=" matches these operands
            operand types are: double2 = float2

/software/relion-3.0_beta/src/acc/cuda/cuda_kernels/helper.cu(165): error: no operator "=" matches these operands
            operand types are: double2 = float2

2 errors detected in the compilation of "/tmp/tmpxft_00004a2c_00000000-7_helper.cpp1.ii".
CMake Error at relion_gpu_util_generated_helper.cu.o.Release.cmake:267 (message):
  Error generating file
  /software/build/src/apps/CMakeFiles/relion_gpu_util.dir/__/acc/cuda/cuda_kernels/./relion_gpu_util_generated_helper.cu.o

make[2]: *** [src/apps/CMakeFiles/relion_gpu_util.dir/__/acc/cuda/cuda_kernels/relion_gpu_util_generated_helper.cu.o] Error 1
make[1]: *** [src/apps/CMakeFiles/relion_gpu_util.dir/all] Error 2
make: *** [all] Error 2

**Comment by bforsbe** [comment]
Will fix. Thanks!

**Comment by miesav** [comment]
Added the following to fix it:

./src/acc/cuda/cuda_kernels/cuda_device_utils.cuh

inline __device__ double2 operator*(double2 a, double b)
{
    return make_double2(a.x * b, a.y * b);
}

src/acc/cuda/cuda_kernels/helper.cu at lines 122 and 163

                       #if defined(ACC_DOUBLE_PRECISION) 
                           XFLOAT scale = 0;
                           if(ires<xdim)
                                   scale =  spectra[ires];

                           Image[pixel] = (curand_normal2_double(&States[id]))*scale;
                       #else
                           XFLOAT scale = 0.f;
                           if(ires<xdim)
                                   scale =  spectra[ires];

                           Image[pixel] = (curand_normal2(&States[id]))*scale;
                      #endif

It compiles after that.

**Comment by biochem-fan** [comment]
Fixed in f73ec6e. Thank you very much for your report and patch.
