### ISSUE TITLE
Last frame parameter inconsistency between Motioncorrection and Polishing

### ISSUE THREAD

**Issue by delarosatrevin** [3dem/relion#400]
For the sake of consistency, could both programs have same convention for last frame value?

Last frame value:
In Motioncorrection, 0 means take all frames.
In Bayesian polishing, Negative values means take all frames. Could this be changed to 0?
In that way both program will be more consistent and also with other movie correction programs.

**Comment by biochem-fan** [comment]
Hi, I asked this to Jasenko, the developer of the program. He said '0' is also treated as 'take all frames'. So the program is fine. I will update the default value and the help message in the GUI.
