### ISSUE TITLE
Segmentation fault and data dumped

### ISSUE THREAD

**Issue by BuddySphinx** [3dem/relion#401]
**Dear Relion Developers.
I am running 3D Refine with my particles and I have encountered the following issues:**
 fn_img= 000018@Extract/job005/./DW_micrographs/TRP_1610_DW.mrcs
 ipart= 0 adaptive_fraction= 0.999
 min_diff2= 3.40282e+38

 fn_img= 000015@Extract/job005/./DW_micrographs/TRP_1610_DW.mrcs
 ipart= 0 adaptive_fraction= 0.999
 min_diff2= 3.40282e+38
Dumped data: error_dump_pdf_orientation, error_dump_pdf_orientation and error_dump_unsorted.
Dumped data: error_dump_pdf_orientation, error_dump_pdf_orientation and error_dump_unsorted.
[c21n10:13494] *** Process received signal ***
[c21n10:13494] Signal: Segmentation fault (11)
[c21n10:13494] Signal code: Address not mapped (1)
[c21n10:13494] Failing at address: 0x21dc3928
[c21n10:13494] [ 0] /lib64/libpthread.so.0(+0xf5e0)[0x2ae6793695e0]
[c21n10:13494] [ 1] /lib64/libc.so.6(+0x142e40)[0x2ae679bc2e40]
[c21n10:13494] [ 2] /ysm-gpfs/apps/software/RELION/2.1.b1-gcccuda-2016.10-cc37/lib/librelion_lib.so(+0x2382ba)[0x2ae66e8e22ba]
[c21n10:13494] [ 3] /ysm-gpfs/apps/software/RELION/2.1.b1-gcccuda-2016.10-cc37/lib/librelion_lib.so(_ZN11RelionErrorC2ERKS_+0x47)[0x2ae66e929aa7]
[c21n10:13494] [ 4] /ysm-gpfs/apps/software/RELION/2.1.b1-gcccuda-2016.10-cc37/lib/librelion_lib.so(_ZN11MlOptimiser24expectationSomeParticlesEll+0x12b8)[0x2ae66e909df8]
[c21n10:13494] [ 5] /ysm-gpfs/apps/software/RELION/2.1.b1-gcccuda-2016.10-cc37/lib/librelion_lib.so(_ZN14MlOptimiserMpi11expectationEv+0x13bd)[0x2ae66e930b2d]
[c21n10:13494] [ 6] /ysm-gpfs/apps/software/RELION/2.1.b1-gcccuda-2016.10-cc37/lib/librelion_lib.so(_ZN14MlOptimiserMpi7iterateEv+0x8d)[0x2ae66e940d2d]
[c21n10:13494] [ 7] /ysm-gpfs/apps/software/RELION/2.1.b1-gcccuda-2016.10-cc37/bin/relion_refine_mpi(main+0x69)[0x40a859]
[c21n10:13494] [ 8] /lib64/libc.so.6(__libc_start_main+0xf5)[0x2ae679aa1c05]
[c21n10:13494] [ 9] /ysm-gpfs/apps/software/RELION/2.1.b1-gcccuda-2016.10-cc37/bin/relion_refine_mpi[0x40a9ef]
[c21n10:13494] *** End of error message ***
srun: error: c21n10: task 3: Segmentation fault (core dumped)
**Initially, I thought it was a memory issue. So I split my data into half by running a 3D classfication. Then I ran 3D Refine separately. One half of data converged without any problem, but another half raised the same issue. Now I am thinking there might be something suspicious about "TRP_1610_DW.mrcs", but not knowing how it caused the error. Could you help me understand what does that min_diff2 stand for? And how does it cause such issue? Thank you.
Best,
Yangqi**

**Comment by biochem-fan** [comment]
FAQ.
