### ISSUE TITLE
Relion 3.0 install issue - CMAKE failing on missing OpenMP_C

### ISSUE THREAD

**Issue by ewoods2** [3dem/relion#402]
Hello.  I'm trying to get a local install for Relion 3.0 beta on Mac OSX (High Sierra, all updates) and I've installed all the recommended supporting libraries, but CMAKE Is failing.  I've looked through support emails and they said to install CMake 3.5.2 and it might solve the OpenMPI missing flags otherwise, I've also installed the most recent version of CMake. 

Any advice would be appreciated. 

Specifically, this is the error where it happens:
Could NOT find OpenMP_C (missing: OpenMP_C_FLAGS OpenMP_C_LIB_NAMES)

I have tried the following CMAKE strings from command line: 

cmake ..

cmake -DMPI_C_COMPILER=$(which mpicc)       -DMPI_CXX_COMPILER=$(which mpic++)       -DCMAKE_INSTALL_PREFIX=/usr/local/ericwoods/relion-3.0b ..

cmake -DCMAKE_INSTALL_PREFIX=/where/to/install/ .. 

The full error string is:
make ..
-- The C compiler identification is AppleClang 10.0.0.10001145
-- The CXX compiler identification is AppleClang 10.0.0.10001145
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- BUILD TYPE set to the default type:  'Release'
-- Setting fallback CUDA_ARCH=35
-- CUDA enabled - Building CUDA-accelerated version of RELION
-- Setting cpu precision to double
-- Setting accelerated code precision to single
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - found
-- Found Threads: TRUE  
-- Found CUDA: /usr/local/cuda (found version "10.0") 
-- Using cuda wrapper to compile....
-- Cuda version is >= 7.5 and single-precision build, enable double usage warning.
-- CMAKE_C_COMPILER : /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- CMAKE_CXX_COMPILER : /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
-- MPI_C_COMPILER : 
-- MPI_CXX_COMPILER : 
-- CMAKE_CXX_COMPILER_ID : Clang
-- Found MPI_C: /usr/local/Cellar/open-mpi/3.1.2/lib/libmpi.dylib (found version "3.1") 
-- Found MPI_CXX: /usr/local/Cellar/open-mpi/3.1.2/lib/libmpi.dylib (found version "3.1") 
-- Found MPI: TRUE (found version "3.1")  
-- MPI_INCLUDE_PATH : /usr/local/Cellar/open-mpi/3.1.2/include
-- MPI_LIBRARIES : /usr/local/Cellar/open-mpi/3.1.2/lib/libmpi.dylib
-- MPI_CXX_INCLUDE_PATH : /usr/local/Cellar/open-mpi/3.1.2/include
-- MPI_CXX_LIBRARIES : /usr/local/Cellar/open-mpi/3.1.2/lib/libmpi.dylib
-- Looking for XOpenDisplay in /usr/X11R6/lib/libX11.dylib;/usr/X11R6/lib/libXext.dylib
-- Looking for XOpenDisplay in /usr/X11R6/lib/libX11.dylib;/usr/X11R6/lib/libXext.dylib - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Looking for IceConnectionNumber in ICE
-- Looking for IceConnectionNumber in ICE - found
-- Found X11: /usr/X11R6/lib/libX11.dylib
-- Found FLTK: /usr/local/lib/libfltk_images.dylib;/usr/local/lib/libfltk_forms.dylib;/usr/local/lib/libfltk.dylib  
-- X11 and FLTK were found
-- FLTK_LIBRARIES: -framework Carbon -framework Cocoa -framework ApplicationServices -lz;/usr/local/lib/libfltk_images.dylib;/usr/local/lib/libfltk_forms.dylib;/usr/local/lib/libfltk.dylib
-- Found FFTW
-- FFTW_PATH: /usr/local/include
-- FFTW_INCLUDES: /usr/local/include
-- FFTW_LIBRARIES: /usr/local/lib/libfftw3f.dylib;/usr/local/lib/libfftw3.dylib
-- Looking for sincos
-- Looking for sincos - not found
-- Looking for __sincos
-- Looking for __sincos - found
-- Found TIFF: /usr/local/lib/libtiff.dylib (found version "4.0.9") 
BUILD_SHARED_LIBS = OFF
-- Building static libs (larger build size and binaries)
Running apps/CMakeLists.txt...
-- CMAKE_BINARY_DIR:/Users/ericwoods/relion-3.0_beta/build
TIFF FOUND
CMake Error at /usr/local/Cellar/cmake/3.12.2/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find OpenMP_C (missing: OpenMP_C_FLAGS OpenMP_C_LIB_NAMES)
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.12.2/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/Cellar/cmake/3.12.2/share/cmake/Modules/FindOpenMP.cmake:466 (find_package_handle_standard_args)
  src/apps/CMakeLists.txt:219 (FIND_PACKAGE)

-- Configuring incomplete, errors occurred!
See also "/Users/[name]/relion-3.0_beta/build/CMakeFiles/CMakeOutput.log".
See also "/Users/[name]/relion-3.0_beta/build/CMakeFiles/CMakeError.log"

**Comment by ewoods2** [comment]
Update:  CMake 3.5.2 and the latest version of CMake both do not work.  Any help would be greatly appreciated.  I have tried using the install instructions from different threads that were closed, as well as setting CPU only and I am not succeeding.  Still getting the same errors with the OpenMP flags.  I tried manually setting them using the command syntax from the thread closed on Aug 30), but that didn't work either.

Do I need to try an older GCC version as well?

**Comment by mjskier** [comment]
For an unrelated project, I ran into the same issue.
I can use the native C and C++ compilers (LLVM based clang) if I use this line in my CMakeLists.txt

find_package ( OPENMP REQUIRED )  

Case is important. find_package ( OpenMP REQUIRED ) didn't work.

**Comment by biochem-fan** [comment]
Hmm, the capital `OPENMP` does not work on older CMake on Linux. Of course I can add `if`s but I will not do it for the version 3.0 as it might de-stabilize the build script and we do not officially support Mac OS X.

**Comment by mjskier** [comment]
Last time I tried to reinstall a package, homebrew updated a lot of packages (including cmake), and my OPENMP "solution" didn't work anymore.

What did work was going back to 'find_package ( OpenMP REQUIRED), making sure libomp was installed (brew install libomp), and add this to the CMakLists.txt

PROPERTIES COMPILE_FLAGS "-Xclang -fopenmp"

**Comment by ewoods2** [comment]
Where did you add that in the CMakeLists.txt?  I'm trying to find that line
and I'm not finding the OpenMP reference when searching it.

**Comment by mjskier** [comment]
In my case it is for a different package. I just found this thread while trying to make OpenMP work and thought I'd mention what worked for me.
It looks something like this (only one of the source files uses OpenMP, so the property is only applied to it.

```
if (${CMAKE_SYSTEM_NAME} MATCHES "Darwin")
        find_package ( OpenMP REQUIRED ) # needs brew install libomp
	if(${CMAKE_GENERATOR} MATCHES "Makefile")
		set ( OPENMP_FLAG "-Xclang -fopenmp" )
		set ( OPENMP_LINK "-lgomp" )
		#set ( APP_TYPE MACOSX_BUNDLE )
	else()
		set ( OPENMP_FLAG "-fopenmp" )
	        set ( OPENMP_LINK "" )
        endif
endif
...
set_source_files_properties ( src/CostFunction3D.cpp src/VarDriver3D.cpp src/BkgdObsLoaders.cpp
	PROPERTIES COMPILE_FLAGS ${OPENMP_FLAG}
	)
```

**Comment by biochem-fan** [comment]
Mac OS X not supported.
