### ISSUE TITLE
relion gui can't execute mpi versions of programs 

### ISSUE THREAD

**Issue by haraQQiri** [3dem/relion#403]
currently trying to use sbgrid version of either relion 2.1 or 3.0beta cu8.0 with openmpi 2.1.2, if i run mpirun -n (#) (command) on the terminal the job will execute normally but not when i try to use the run button to start the job locally, the run button will execute single process non mpi jobs. this is only happening on one of three machines that as far as i know have the same programs installed and updates on ubuntu 16.04.3. is there some kind of configuration file that is referenced when this run function on the gui is used? i don't use qsub or a scheduler

thanks for your time!
eric

**Comment by biochem-fan** [comment]
Not locally reproducible. No response for many months.
