### ISSUE TITLE
probelem in this step: [ 45%] Linking CXX shared library ../../lib/librelion_lib.so

### ISSUE THREAD

**Issue by davidh99720** [3dem/relion#404]
Problem encountered when install relion 2.0.0:
[ 45%] Linking CXX shared library ../../lib/librelion_lib.so
/usr/bin/ld: /usr/local/lib/libfftw3.a(apiplan.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/local/lib/libfftw3.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
src/apps/CMakeFiles/relion_lib.dir/build.make:1477: recipe for target 'lib/librelion_lib.so' failed
make[2]: *** [lib/librelion_lib.so] Error 1
CMakeFiles/Makefile2:1416: recipe for target 'src/apps/CMakeFiles/relion_lib.dir/all' failed
make[1]: *** [src/apps/CMakeFiles/relion_lib.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

Any idea about how to fix it?

Here is the configure log:
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- BUILD TYPE set to the default type:  'Release'
-- Setting fallback CUDA_ARCH=35
-- Setting cpu precision to double
-- Setting gpu precision to single
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found CUDA: /usr/local/cuda (found version "8.0") 
-- Using cuda wrapper to compile....
-- Cuda version is >= 7.5 and single-precision build, enable double usage warning.
-- Found MPI_C: /usr/lib/x86_64-linux-gnu/libmpich.so  
-- Found MPI_CXX: /usr/lib/x86_64-linux-gnu/libmpichcxx.so;/usr/lib/x86_64-linux-gnu/libmpich.so  
-- MPI_INCLUDE_PATH : /usr/include/mpich
-- MPI_LIBRARIES : /usr/lib/x86_64-linux-gnu/libmpichcxx.so;/usr/lib/x86_64-linux-gnu/libmpich.so
-- MPI_CXX_INCLUDE_PATH : /usr/include/mpich
-- MPI_CXX_LIBRARIES : /usr/lib/x86_64-linux-gnu/libmpichcxx.so;/usr/lib/x86_64-linux-gnu/libmpich.so
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Looking for IceConnectionNumber in ICE
-- Looking for IceConnectionNumber in ICE - found
-- Found X11: /usr/lib/x86_64-linux-gnu/libX11.so
-- Found FLTK: fltk_images;fltk_forms;fltk  
-- X11 and FLTK were found
-- FLTK_LIBRARIES: fltk_images;fltk_forms;fltk;/usr/lib/x86_64-linux-gnu/libSM.so;/usr/lib/x86_64-linux-gnu/libICE.so;/usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so;/usr/lib/x86_64-linux-gnu/libm.so
-- Found FFTW: fftw3
-- FFTW_LIBRARIES: /usr/local/lib/libfftw3.a
-- Looking for sincos
-- Looking for sincos - found
-- Looking for __sincos
-- Looking for __sincos - not found
-- Building shared libs (smaller build size and binaries)
-- CMAKE_BINARY_DIR:/home/cyhuang/Software/relions/relion/build
-- added display...
-- added particle_symmetry_expand...
-- added helix_toolbox...
-- added project...
-- added find_tiltpairs...
-- added prepare_subtomo...
-- added run_motioncorr...
-- added refine...
-- added tiltpair_plot...
-- added star_compare...
-- added particle_polish...
-- added pipeliner...
-- added refine_mpi...
-- added localsym...
-- added run_motioncorr_mpi...
-- added run_ctffind_mpi...
-- added manualpick...
-- added postprocess...
-- added reconstruct...
-- added mask_create...
-- added star_combine...
-- added preprocess_mpi...
-- added postprocess_mpi...
-- added particle_sort...
-- added particle_sort_mpi...
-- added preprocess...
-- added stack_create...
-- added run_ctffind...
-- added autopick_mpi...
-- added autopick...
-- added particle_polish_mpi...
-- added particle_reposition...
-- added maingui...
-- added ctf_toolbox...
-- added image_handler...
-- added localsym_mpi...
-- Configuring done
-- Generating done
-- Build files have been written to: /home/cyhuang/Software/relions/relion/build

here is the the respond of make -j4:
[  1%] Building NVCC (Device) object src/apps/CMakeFiles/relion_gpu_util.dir/__/gpu_utils/relion_gpu_util_generated_cuda_benchmark_utils.cu.o
[  2%] Building NVCC (Device) object src/apps/CMakeFiles/relion_gpu_util.dir/__/gpu_utils/cuda_kernels/relion_gpu_util_generated_helper.cu.o
Scanning dependencies of target copy_scripts
[  3%] Building NVCC (Device) object src/apps/CMakeFiles/relion_gpu_util.dir/__/gpu_utils/relion_gpu_util_generated_cuda_helper_functions.cu.o
[  3%] Built target copy_scripts
[  3%] Building NVCC (Device) object src/apps/CMakeFiles/relion_gpu_util.dir/__/gpu_utils/relion_gpu_util_generated_cuda_backprojector.cu.o
[  4%] Building NVCC (Device) object src/apps/CMakeFiles/relion_gpu_util.dir/__/gpu_utils/relion_gpu_util_generated_cuda_projector.cu.o
[  5%] Building NVCC (Device) object src/apps/CMakeFiles/relion_gpu_util.dir/__/gpu_utils/relion_gpu_util_generated_cuda_autopicker.cu.o
[  6%] Building NVCC (Device) object src/apps/CMakeFiles/relion_gpu_util.dir/__/gpu_utils/relion_gpu_util_generated_cuda_projector_plan.cu.o
[  6%] Building NVCC (Device) object src/apps/CMakeFiles/relion_gpu_util.dir/__/gpu_utils/relion_gpu_util_generated_cuda_ml_optimiser.cu.o
Scanning dependencies of target relion_gpu_util
[  7%] Linking CXX shared library ../../lib/librelion_gpu_util.so
[  7%] Built target relion_gpu_util
Scanning dependencies of target relion_lib
[  8%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/metadata_label.cpp.o
[  8%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/healpix_sampling.cpp.o
[  9%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/preprocessing_mpi.cpp.o
[ 10%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/transformations.cpp.o
[ 11%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/motioncorr_runner_mpi.cpp.o
[ 11%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/ml_optimiser_mpi.cpp.o
[ 12%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/mask.cpp.o
[ 13%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/backprojector.cpp.o
[ 13%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/strings.cpp.o
[ 14%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/complex.cpp.o
[ 15%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/postprocessing.cpp.o
[ 16%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/motioncorr_runner.cpp.o
[ 16%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/ctffind_runner.cpp.o
[ 17%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/args.cpp.o
[ 18%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/euler.cpp.o
[ 18%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/ctf.cpp.o
[ 19%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/time.cpp.o
[ 20%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/ml_optimiser.cpp.o
[ 20%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/matrix2d.cpp.o
[ 21%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/pipeliner.cpp.o
[ 22%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/autopicker.cpp.o
[ 22%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/autopicker_mpi.cpp.o
[ 23%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/mpi.cpp.o
[ 24%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/helix.cpp.o
[ 25%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/pipeline_jobs.cpp.o
[ 25%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/projector.cpp.o
[ 26%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/assembly.cpp.o
[ 27%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/filename.cpp.o
[ 27%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/tabfuncs.cpp.o
[ 28%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/multidim_array.cpp.o
[ 29%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/error.cpp.o
[ 29%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/CPlot2D.cpp.o
[ 30%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/metadata_container.cpp.o
[ 31%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/exp_model.cpp.o
[ 32%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/local_symmetry_mpi.cpp.o
[ 32%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/fftw.cpp.o
[ 33%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/particle_sorter.cpp.o
[ 34%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/memory.cpp.o
[ 34%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/numerical_recipes.cpp.o
[ 35%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/local_symmetry.cpp.o
[ 36%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/particle_polisher_mpi.cpp.o
[ 36%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/preprocessing.cpp.o
[ 37%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/particle_polisher.cpp.o
[ 38%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/funcs.cpp.o
[ 38%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/ctffind_runner_mpi.cpp.o
[ 39%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/ml_model.cpp.o
[ 40%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/symmetries.cpp.o
[ 41%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/parallel.cpp.o
[ 41%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/matrix1d.cpp.o
[ 42%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/particle_sorter_mpi.cpp.o
[ 43%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/image.cpp.o
[ 43%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/metadata_table.cpp.o
[ 44%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/Healpix_2.15a/healpix_base.cc.o
[ 45%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/Healpix_2.15a/cxxutils.cc.o
[ 45%] Linking CXX shared library ../../lib/librelion_lib.so
/usr/bin/ld: /usr/local/lib/libfftw3.a(apiplan.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/local/lib/libfftw3.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
src/apps/CMakeFiles/relion_lib.dir/build.make:1477: recipe for target 'lib/librelion_lib.so' failed
make[2]: *** [lib/librelion_lib.so] Error 1
CMakeFiles/Makefile2:1416: recipe for target 'src/apps/CMakeFiles/relion_lib.dir/all' failed
make[1]: *** [src/apps/CMakeFiles/relion_lib.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by davidh99720** [comment]
Problem fixed by Adding
-DFORCE_OWN_FFTW=ON
to the cmake configuration command.

**Comment by davidh99720** [comment]
Just an add-up.
Similar problems may happen if my gcc version is not 4.8. 
So, you may what to install gcc 4.8 which is mostly test by RELION2 and replace your current gcc link to the 4.8 version.
You can use 
"which gcc" and "gcc --version" to find the information you need.

**Comment by biochem-fan** [comment]
@gauravsahooo

What are you compiling? This does not look like RELION.
If you are building ORB_SLAM3, ask its developers.
