### ISSUE TITLE
Makefile:138: recipe for target 'all' failed

### ISSUE THREAD

**Issue by brukmensa** [3dem/relion#405]
I get the following error while trying to build on ubuntu:

Scanning dependencies of target OWN_FLTK
Scanning dependencies of target copy_scripts
[  1%] Building NVCC (Device) object src/apps/CMakeFiles/relion_gpu_util.dir/__/gpu_utils/cuda_kernels/relion_gpu_util_generated_helper.cu.o
[  1%] Building NVCC (Device) object src/apps/CMakeFiles/relion_gpu_util.dir/__/gpu_utils/relion_gpu_util_generated_cuda_benchmark_utils.cu.o
[  1%] Creating directories for 'OWN_FLTK'
[  1%] Built target copy_scripts
[  2%] Building NVCC (Device) object src/apps/CMakeFiles/relion_gpu_util.dir/__/gpu_utils/relion_gpu_util_generated_cuda_projector_plan.cu.o
[  3%] Performing download step (download, verify and extract) for 'OWN_FLTK'
-- downloading...
     src='https://drive.google.com/uc?export=download&id=0B942d76zVnSeazZWcExRaXIyVDg'
     dst='/home/dgl/relion/external/fltk/fltk-1.3.3-source.tar.gz'
     timeout='none'
/usr/include/string.h: In function ‘void* __mempcpy_inline(void*, const void*, size_t)’:
/usr/include/string.h:652:42: error: ‘memcpy’ was not declared in this scope
   return (char *) memcpy (__dest, __src, __n) + __n;
                                          ^
CMake Error at relion_gpu_util_generated_cuda_benchmark_utils.cu.o.cmake:266 (message):
  Error generating file
  /home/dgl/relion/build/src/apps/CMakeFiles/relion_gpu_util.dir/__/gpu_utils/./relion_gpu_util_generated_cuda_benchmark_utils.cu.o

src/apps/CMakeFiles/relion_gpu_util.dir/build.make:63: recipe for target 'src/apps/CMakeFiles/relion_gpu_util.dir/__/gpu_utils/relion_gpu_util_generated_cuda_benchmark_utils.cu.o' failed
make[2]: *** [src/apps/CMakeFiles/relion_gpu_util.dir/__/gpu_utils/relion_gpu_util_generated_cuda_benchmark_utils.cu.o] Error 1
make[2]: *** Waiting for unfinished jobs....
/usr/include/string.h: In function ‘void* __mempcpy_inline(void*, const void*, size_t)’:
/usr/include/string.h:652:42: error: ‘memcpy’ was not declared in this scope
   return (char *) memcpy (__dest, __src, __n) + __n;
                                          ^
CMake Error at relion_gpu_util_generated_helper.cu.o.cmake:266 (message):
  Error generating file
  /home/dgl/relion/build/src/apps/CMakeFiles/relion_gpu_util.dir/__/gpu_utils/cuda_kernels/./relion_gpu_util_generated_helper.cu.o

src/apps/CMakeFiles/relion_gpu_util.dir/build.make:112: recipe for target 'src/apps/CMakeFiles/relion_gpu_util.dir/__/gpu_utils/cuda_kernels/relion_gpu_util_generated_helper.cu.o' failed
make[2]: *** [src/apps/CMakeFiles/relion_gpu_util.dir/__/gpu_utils/cuda_kernels/relion_gpu_util_generated_helper.cu.o] Error 1
/usr/include/string.h: In function ‘void* __mempcpy_inline(void*, const void*, size_t)’:
/usr/include/string.h:652:42: error: ‘memcpy’ was not declared in this scope
   return (char *) memcpy (__dest, __src, __n) + __n;
                                          ^
CMake Error at relion_gpu_util_generated_cuda_projector_plan.cu.o.cmake:266 (message):
  Error generating file
  /home/dgl/relion/build/src/apps/CMakeFiles/relion_gpu_util.dir/__/gpu_utils/./relion_gpu_util_generated_cuda_projector_plan.cu.o

src/apps/CMakeFiles/relion_gpu_util.dir/build.make:70: recipe for target 'src/apps/CMakeFiles/relion_gpu_util.dir/__/gpu_utils/relion_gpu_util_generated_cuda_projector_plan.cu.o' failed
make[2]: *** [src/apps/CMakeFiles/relion_gpu_util.dir/__/gpu_utils/relion_gpu_util_generated_cuda_projector_plan.cu.o] Error 1
CMakeFiles/Makefile2:808: recipe for target 'src/apps/CMakeFiles/relion_gpu_util.dir/all' failed
make[1]: *** [src/apps/CMakeFiles/relion_gpu_util.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
-- downloading... done
-- verifying file...
     file='/home/dgl/relion/external/fltk/fltk-1.3.3-source.tar.gz'
-- verifying file... done
-- extracting...
     src='/home/dgl/relion/external/fltk/fltk-1.3.3-source.tar.gz'
     dst='/home/dgl/relion/external/fltk/fltk'
-- extracting... [tar xfz]
-- extracting... [analysis]
-- extracting... [rename]
-- extracting... [clean up]
-- extracting... done
[  3%] Performing patch step for 'OWN_FLTK'
[  4%] No update step for 'OWN_FLTK'
patching file src/fl_line_style.cxx
[  5%] Performing configure step for 'OWN_FLTK'
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking if the compiler supports -fvisibility... yes
checking if the compiler supports -fvisibility-inlines-hidden... yes
checking for a BSD-compatible install... /usr/bin/install -c
checking for nroff... /usr/bin/nroff
checking for doxygen... no
checking for ranlib... ranlib
checking for ar... /usr/bin/ar
checking for windres... no
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking size of short... 2
checking size of int... 4
checking size of long... 8
checking whether byte ordering is bigendian... no
checking whether the compiler recognizes bool as a built-in type... yes
checking for dirent.h that defines DIR... yes
checking for library containing opendir... none required
checking sys/select.h usability... yes
checking sys/select.h presence... yes
checking for sys/select.h... yes
checking sys/stdtypes.h usability... no
checking sys/stdtypes.h presence... no
checking for sys/stdtypes.h... no
checking whether we have the POSIX compatible scandir() prototype... yes
checking for vsnprintf... yes
checking for snprintf... yes
checking for strings.h... (cached) yes
checking for strcasecmp... yes
checking for strlcat... no
checking for strlcpy... no
checking locale.h usability... yes
checking locale.h presence... yes
checking for locale.h... yes
checking for localeconv... yes
checking for library containing pow... -lm
checking for special C compiler options needed for large files... no
checking for _FILE_OFFSET_BITS value needed for large files... no
checking for long long int... yes
checking for library containing dlsym... -ldl
checking dlfcn.h usability... yes
checking dlfcn.h presence... yes
checking for dlfcn.h... yes
checking alsa/asoundlib.h usability... no
checking alsa/asoundlib.h presence... no
checking for alsa/asoundlib.h... no
checking for jpeg_CreateCompress in -ljpeg... no
checking for gzgets in -lz... yes
checking zlib.h usability... yes
checking zlib.h presence... yes
checking for zlib.h... yes
checking for png_read_info in -lpng... yes
checking png.h usability... yes
checking png.h presence... yes
checking for png.h... yes
checking libpng/png.h usability... yes
checking libpng/png.h presence... yes
checking for libpng/png.h... yes
checking for png_get_valid in -lpng... yes
checking for png_set_tRNS_to_alpha in -lpng... yes
checking pthread.h usability... yes
checking pthread.h presence... yes
checking for pthread.h... yes
checking for pthread_create using -lpthreads... no
checking for pthread_create using -lpthread... yes
checking for X... libraries , headers 
checking for gethostbyname... yes
checking for connect... yes
checking for remove... yes
checking for shmat... yes
checking for IceConnectionNumber in -lICE... yes
configure: WARNING: Ignoring libraries " -lSM -lICE" requested by configure.
checking for library containing dlopen... none required
checking GL/gl.h usability... yes
checking GL/gl.h presence... yes
checking for GL/gl.h... yes
checking for glXMakeCurrent in -lGL... yes
checking for glXGetProcAddressARB in -lGL... yes
checking GL/glu.h usability... yes
checking GL/glu.h presence... yes
checking for GL/glu.h... yes
checking for XineramaIsActive in -lXinerama... no
checking for freetype-config... /home/dgl/cryosparc2_master/deps/anaconda/bin/freetype-config
checking for FcPatternCreate in -lfontconfig... no
checking X11/Xft/Xft.h usability... no
checking X11/Xft/Xft.h presence... no
checking for X11/Xft/Xft.h... no
checking for X11/extensions/Xdbe.h... yes
checking for XdbeQueryExtension in -lXext... yes
checking for X11/extensions/Xfixes.h... yes
checking for XFixesQueryExtension in -lXfixes... yes
checking for X11/Xcursor/Xcursor.h... no
checking for XcursorImageCreate in -lXcursor... no
checking for xprop... /usr/bin/xprop
checking for X overlay visuals... no
checking if GCC supports -fno-exceptions... yes
checking if GCC supports -fno-strict-aliasing... yes
checking if ld supports -Bsymbolic-functions... yes
checking if toolchain supports sections... yes

Configuration Summary
-------------------------------------------------------------------------
    Directories: prefix=/home/dgl/relion/external/fltk
                 bindir=${exec_prefix}/bin
                 datadir=${datarootdir}
                 datarootdir=${prefix}/share
                 exec_prefix=${prefix}
                 includedir=${prefix}/include
                 libdir=${exec_prefix}/lib
                 mandir=${datarootdir}/man
       Graphics: X11+Xft+Xdbe+Xinerama
Image Libraries: JPEG=Builtin
                 PNG=System
                 ZLIB=System
    Large Files: YES
         OpenGL: YES
        Threads: YES
configure: creating ./config.status
config.status: creating makeinclude
config.status: creating fltk.list
config.status: creating fltk-config
config.status: creating fltk.spec
config.status: creating FL/Makefile
config.status: creating config.h
[  6%] Performing build step for 'OWN_FLTK'
=== making jpeg ===
Compiling jaricom.c...
Compiling jcapimin.c...
Compiling jcapistd.c...
Compiling jcarith.c...
Compiling jccoefct.c...
Compiling jccolor.c...
Compiling jcdctmgr.c...
Compiling jchuff.c...
Compiling jcinit.c...
Compiling jcmainct.c...
Compiling jcmarker.c...
Compiling jcmaster.c...
Compiling jcomapi.c...
Compiling jcparam.c...
Compiling jcprepct.c...
Compiling jcsample.c...
Compiling jctrans.c...
Compiling jdapimin.c...
Compiling jdapistd.c...
Compiling jdarith.c...
Compiling jdatadst.c...
Compiling jdatasrc.c...
Compiling jdcoefct.c...
Compiling jdcolor.c...
Compiling jddctmgr.c...
Compiling jdhuff.c...
Compiling jdinput.c...
Compiling jdmainct.c...
Compiling jdmarker.c...
Compiling jdmaster.c...
Compiling jdmerge.c...
Compiling jdpostct.c...
Compiling jdsample.c...
Compiling jdtrans.c...
Compiling jerror.c...
Compiling jfdctflt.c...
Compiling jfdctfst.c...
Compiling jfdctint.c...
Compiling jidctflt.c...
Compiling jidctfst.c...
Compiling jidctint.c...
Compiling jmemmgr.c...
Compiling jmemnobs.c...
Compiling jquant1.c...
Compiling jquant2.c...
Compiling jutils.c...
Archiving ../lib/libfltk_jpeg.a...
=== making src ===
Compiling Fl.cxx...
Compiling Fl_Adjuster.cxx...
Compiling Fl_Bitmap.cxx...
Compiling Fl_Browser.cxx...
Compiling Fl_Browser_.cxx...
Compiling Fl_Browser_load.cxx...
Compiling Fl_Box.cxx...
Compiling Fl_Button.cxx...
Compiling Fl_Chart.cxx...
Compiling Fl_Check_Browser.cxx...
Compiling Fl_Check_Button.cxx...
Compiling Fl_Choice.cxx...
Compiling Fl_Clock.cxx...
Compiling Fl_Color_Chooser.cxx...
Compiling Fl_Copy_Surface.cxx...
Compiling Fl_Counter.cxx...
Compiling Fl_Dial.cxx...
Compiling Fl_Device.cxx...
Compiling Fl_Double_Window.cxx...
Compiling Fl_File_Browser.cxx...
Compiling Fl_File_Chooser.cxx...
Compiling Fl_File_Chooser2.cxx...
Compiling Fl_File_Icon.cxx...
Compiling Fl_File_Input.cxx...
Compiling Fl_Group.cxx...
Compiling Fl_Help_View.cxx...
Compiling Fl_Image.cxx...
Compiling Fl_Image_Surface.cxx...
Compiling Fl_Input.cxx...
Compiling Fl_Input_.cxx...
Compiling Fl_Light_Button.cxx...
Compiling Fl_Menu.cxx...
Compiling Fl_Menu_.cxx...
Compiling Fl_Menu_Bar.cxx...
Compiling Fl_Menu_Button.cxx...
Compiling Fl_Menu_Window.cxx...
Compiling Fl_Menu_add.cxx...
Compiling Fl_Menu_global.cxx...
Compiling Fl_Multi_Label.cxx...
Compiling Fl_Native_File_Chooser.cxx...
Compiling Fl_Overlay_Window.cxx...
Compiling Fl_Pack.cxx...
Compiling Fl_Paged_Device.cxx...
Compiling Fl_Pixmap.cxx...
Compiling Fl_PostScript.cxx...
Compiling Fl_Positioner.cxx...
Compiling Fl_Preferences.cxx...
Compiling Fl_Printer.cxx...
Compiling Fl_Progress.cxx...
Compiling Fl_Repeat_Button.cxx...
Compiling Fl_Return_Button.cxx...
Compiling Fl_Roller.cxx...
Compiling Fl_Round_Button.cxx...
Compiling Fl_Scroll.cxx...
Compiling Fl_Scrollbar.cxx...
Compiling Fl_Shared_Image.cxx...
Compiling Fl_Single_Window.cxx...
Compiling Fl_Slider.cxx...
Compiling Fl_Table.cxx...
Compiling Fl_Table_Row.cxx...
Compiling Fl_Tabs.cxx...
Fl_Table.cxx: In member function ‘void Fl_Table::recalc_dimensions()’:
Fl_Table.cxx:494:11: warning: suggest parentheses around operand of ‘!’ or change ‘&’ to ‘&&’ or ‘!’ to ‘~’ [-Wparentheses]
     if ( !hideh & hidev ) { hidev = (( table_h - tih + scrollsize ) <= 0 ); } 
           ^
Fl_Table.cxx:495:11: warning: suggest parentheses around operand of ‘!’ or change ‘&’ to ‘&&’ or ‘!’ to ‘~’ [-Wparentheses]
     if ( !hidev & hideh ) { hideh = (( table_w - tiw + scrollsize ) <= 0 ); } 
           ^
Compiling Fl_Text_Buffer.cxx...
Compiling Fl_Text_Display.cxx...
Compiling Fl_Text_Editor.cxx...
Compiling Fl_Tile.cxx...
Compiling Fl_Tiled_Image.cxx...
Compiling Fl_Tree.cxx...
Compiling Fl_Tree_Item.cxx...
Compiling Fl_Tree_Item_Array.cxx...
Compiling Fl_Tree_Prefs.cxx...
Compiling Fl_Tooltip.cxx...
Compiling Fl_Valuator.cxx...
Compiling Fl_Value_Input.cxx...
Compiling Fl_Value_Output.cxx...
Compiling Fl_Value_Slider.cxx...
Compiling Fl_Widget.cxx...
Compiling Fl_Window.cxx...
Compiling Fl_Window_fullscreen.cxx...
Compiling Fl_Window_hotspot.cxx...
Compiling Fl_Window_iconize.cxx...
Compiling Fl_Window_shape.cxx...
Compiling Fl_Wizard.cxx...
Compiling Fl_XBM_Image.cxx...
Compiling Fl_XPM_Image.cxx...
Compiling Fl_abort.cxx...
Compiling Fl_add_idle.cxx...
Compiling Fl_arg.cxx...
Compiling Fl_compose.cxx...
Compiling Fl_display.cxx...
Compiling Fl_get_key.cxx...
Compiling Fl_get_system_colors.cxx...
Compiling Fl_grab.cxx...
Compiling Fl_lock.cxx...
Compiling Fl_own_colormap.cxx...
Compiling Fl_visual.cxx...
Compiling Fl_x.cxx...
Compiling filename_absolute.cxx...
Compiling filename_expand.cxx...
Fl_x.cxx: In function ‘KeySym fl_KeycodeToKeysym(Display*, KeyCode, unsigned int)’:
Fl_x.cxx:1313:10: warning: ‘KeySym XKeycodeToKeysym(Display*, KeyCode, int)’ is deprecated [-Wdeprecated-declarations]
   return XKeycodeToKeysym(d, k, i);
          ^
In file included from ../FL/fl_utf8.h:63:0,
                 from ../FL/Fl.H:30,
                 from Fl_x.cxx:30:
/usr/include/X11/Xlib.h:1687:15: note: declared here
 extern KeySym XKeycodeToKeysym(
               ^
Fl_x.cxx:1313:10: warning: ‘KeySym XKeycodeToKeysym(Display*, KeyCode, int)’ is deprecated [-Wdeprecated-declarations]
   return XKeycodeToKeysym(d, k, i);
          ^
In file included from ../FL/fl_utf8.h:63:0,
                 from ../FL/Fl.H:30,
                 from Fl_x.cxx:30:
/usr/include/X11/Xlib.h:1687:15: note: declared here
 extern KeySym XKeycodeToKeysym(
               ^
Fl_x.cxx:1313:34: warning: ‘KeySym XKeycodeToKeysym(Display*, KeyCode, int)’ is deprecated [-Wdeprecated-declarations]
   return XKeycodeToKeysym(d, k, i);
                                  ^
In file included from ../FL/fl_utf8.h:63:0,
                 from ../FL/Fl.H:30,
                 from Fl_x.cxx:30:
/usr/include/X11/Xlib.h:1687:15: note: declared here
 extern KeySym XKeycodeToKeysym(
               ^
Compiling filename_ext.cxx...
Compiling filename_isdir.cxx...
Compiling filename_list.cxx...
Compiling filename_match.cxx...
Compiling filename_setext.cxx...
Compiling fl_arc.cxx...
Compiling fl_arci.cxx...
Compiling fl_ask.cxx...
Compiling fl_boxtype.cxx...
Compiling fl_color.cxx...
Compiling fl_cursor.cxx...
Compiling fl_curve.cxx...
Compiling fl_diamond_box.cxx...
Compiling fl_dnd.cxx...
Compiling fl_draw.cxx...
Compiling fl_draw_image.cxx...
Compiling fl_draw_pixmap.cxx...
Compiling fl_encoding_latin1.cxx...
Compiling fl_encoding_mac_roman.cxx...
Compiling fl_engraved_label.cxx...
Compiling fl_file_dir.cxx...
Compiling fl_font.cxx...
Compiling fl_gleam.cxx...
Compiling fl_gtk.cxx...
Compiling fl_labeltype.cxx...
Compiling fl_line_style.cxx...
Compiling fl_open_uri.cxx...
Compiling fl_oval_box.cxx...
Compiling fl_overlay.cxx...
Compiling fl_overlay_visual.cxx...
Compiling fl_plastic.cxx...
Compiling fl_read_image.cxx...
Compiling fl_rect.cxx...
Compiling fl_round_box.cxx...
Compiling fl_rounded_box.cxx...
Compiling fl_set_font.cxx...
Compiling fl_set_fonts.cxx...
Compiling fl_scroll_area.cxx...
Compiling fl_shadow_box.cxx...
Compiling fl_shortcut.cxx...
Compiling fl_show_colormap.cxx...
Compiling fl_symbols.cxx...
Compiling fl_vertex.cxx...
Compiling screen_xywh.cxx...
Compiling fl_utf8.cxx...
Compiling ps_image.cxx...
Compiling fl_call_main.c...
Compiling flstring.c...
Compiling scandir.c...
Compiling numericsort.c...
Compiling vsnprintf.c...
Compiling fl_utf.c...
Compiling xutf8/case.c...
Compiling xutf8/is_right2left.c...
Compiling xutf8/is_spacing.c...
Compiling xutf8/keysym2Ucs.c...
Compiling xutf8/utf8Input.c...
Compiling xutf8/utf8Utils.c...
Compiling xutf8/utf8Wrap.c...
Compiling forms_compatability.cxx...
Compiling forms_bitmap.cxx...
Compiling forms_free.cxx...
Compiling forms_fselect.cxx...
Compiling forms_pixmap.cxx...
Compiling forms_timer.cxx...
Compiling Fl_Gl_Choice.cxx...
Compiling Fl_Gl_Overlay.cxx...
Compiling Fl_Gl_Device_Plugin.cxx...
Compiling Fl_Gl_Window.cxx...
Compiling freeglut_geometry.cxx...
Compiling freeglut_stroke_mono_roman.cxx...
Compiling freeglut_stroke_roman.cxx...
Compiling freeglut_teapot.cxx...
Compiling gl_draw.cxx...
Compiling gl_start.cxx...
Compiling glut_compatability.cxx...
Compiling glut_font.cxx...
Compiling fl_images_core.cxx...
Compiling Fl_BMP_Image.cxx...
Compiling Fl_File_Icon2.cxx...
Compiling Fl_GIF_Image.cxx...
Compiling Fl_Help_Dialog.cxx...
Compiling Fl_JPEG_Image.cxx...
Compiling Fl_PNG_Image.cxx...
Compiling Fl_PNM_Image.cxx...
/usr/bin/ar cr ../lib/libfltk.a ...
g++ -L. -Wl,-Bsymbolic-functions -Wl,-gc-sections -Wl,-soname,libfltk.so.1.3 -lXfixes -lXext -lpthread -ldl -lm -lX11 -shared -fPIC -o libfltk.so.1.3 ...
/usr/bin/ar cr ../lib/libfltk_forms.a ...
/usr/bin/ar cr ../lib/libfltk_gl.a ...
/usr/bin/ar cr ../lib/libfltk_images.a ...
g++ -L. -Wl,-Bsymbolic-functions -Wl,-gc-sections -Wl,-soname,libfltk_forms.so.1.3 -lXfixes -lXext -lpthread -ldl -lm -lX11 -shared -fPIC -o libfltk_forms.so.1.3 ...
g++ -L. -Wl,-Bsymbolic-functions -Wl,-gc-sections -Wl,-soname,libfltk_gl.so.1.3 -lXfixes -lXext -lpthread -ldl -lm -lX11 -shared -fPIC -o libfltk_gl.so.1.3 ...
g++ -L. -Wl,-Bsymbolic-functions -Wl,-gc-sections -Wl,-soname,libfltk_images.so.1.3 -lXfixes -lXext -lpthread -ldl -lm -lX11 -shared -fPIC -o libfltk_images.so.1.3 ...
=== making fluid ===
Compiling CodeEditor.cxx...
Compiling Fl_Function_Type.cxx...
Compiling Fl_Group_Type.cxx...
Compiling Fl_Menu_Type.cxx...
Compiling Fl_Type.cxx...
Compiling Fl_Widget_Type.cxx...
Compiling Fl_Window_Type.cxx...
Compiling Fluid_Image.cxx...
Compiling about_panel.cxx...
Compiling align_widget.cxx...
Compiling alignment_panel.cxx...
Compiling code.cxx...
Compiling factory.cxx...
Compiling file.cxx...
Compiling fluid.cxx...
Compiling function_panel.cxx...
Compiling template_panel.cxx...
Compiling undo.cxx...
Compiling widget_panel.cxx...
Linking fluid-shared...
Linking fluid...
=== making test ===
Compiling unittests.cxx...
Compiling arc.cxx...
Compiling adjuster.cxx...
Compiling ask.cxx...
Compiling bitmap.cxx...
Compiling blocks.cxx...
Compiling boxtype.cxx...
Compiling browser.cxx...
Compiling button.cxx...
Compiling buttons.cxx...
Compiling cairo_test.cxx...
Compiling checkers.cxx...
Compiling clock.cxx...
Compiling colbrowser.cxx...
Compiling color_chooser.cxx...
Compiling cursor.cxx...
Compiling curve.cxx...
Compiling demo.cxx...
Compiling device.cxx...
Compiling doublebuffer.cxx...
Compiling editor.cxx...
Generating fast_slow.cxx and header from fast_slow.fl...
Generating fast_slow.h and header from fast_slow.fl...
Compiling file_chooser.cxx...
Compiling fonts.cxx...
Compiling forms.cxx...
Compiling hello.cxx...
Compiling help.cxx...
Compiling icon.cxx...
Compiling iconize.cxx...
Compiling image.cxx...
Generating inactive.cxx and header from inactive.fl...
Generating inactive.h and header from inactive.fl...
Compiling input.cxx...
Compiling input_choice.cxx...
Generating keyboard_ui.cxx and header from keyboard_ui.fl...
Generating keyboard_ui.h and header from keyboard_ui.fl...
Compiling label.cxx...
Compiling line_style.cxx...
Compiling list_visuals.cxx...
Generating mandelbrot_ui.cxx and header from mandelbrot_ui.fl...
Generating mandelbrot_ui.h and header from mandelbrot_ui.fl...
Compiling menubar.cxx...
Compiling message.cxx...
Compiling minimum.cxx...
Compiling native-filechooser.cxx...
Compiling navigation.cxx...
Compiling output.cxx...
Compiling overlay.cxx...
Compiling pack.cxx...
Compiling pixmap.cxx...
Compiling pixmap_browser.cxx...
Generating preferences.cxx and header from preferences.fl...
Generating preferences.h and header from preferences.fl...
Generating radio.cxx and header from radio.fl...
Generating radio.h and header from radio.fl...
Generating resize.cxx and header from resize.fl...
Generating resize.h and header from resize.fl...
Compiling resizebox.cxx...
Compiling rotated_text.cxx...
Compiling scroll.cxx...
Compiling subwindow.cxx...
Compiling sudoku.cxx...
Compiling symbols.cxx...
Compiling table.cxx...
Generating tabs.cxx and header from tabs.fl...
Generating tabs.h and header from tabs.fl...
Compiling threads.cxx...
Compiling tile.cxx...
Compiling tiled_image.cxx...
Generating tree.cxx and header from tree.fl...
Generating tree.h and header from tree.fl...
Compiling twowin.cxx...
Generating valuators.cxx and header from valuators.fl...
Generating valuators.h and header from valuators.fl...
Compiling utf8.cxx...
Compiling windowfocus.cxx...
Compiling cube.cxx...
Generating CubeViewUI.h and header from CubeViewUI.fl...
Generating CubeViewUI.cxx and header from CubeViewUI.fl...
Compiling CubeView.cxx...
Compiling CubeViewUI.cxx...
Compiling fractals.cxx...
Compiling fracviewer.cxx...
Compiling fullscreen.cxx...
Compiling gl_overlay.cxx...
Compiling glpuzzle.cxx...
Compiling shape.cxx...
Linking adjuster...
Linking unittests...
Linking arc...
Linking ask...
Linking bitmap...
Linking blocks...
Linking boxtype...
Linking browser...
Linking button...
Linking buttons...
Linking cairo_test...
Linking checkers...
Linking clock...
Linking colbrowser...
Linking color_chooser...
Linking cursor...
Linking curve...
Linking demo...
Linking device...
Linking doublebuffer...
Linking editor...
Compiling fast_slow.cxx...
Linking file_chooser...
Linking fonts...
Linking forms...
Linking hello...
Linking help...
Linking icon...
Linking iconize...
Linking image...
Compiling inactive.cxx...
Linking input...
Linking input_choice...
Compiling keyboard_ui.cxx...
Compiling keyboard.cxx...
Linking label...
Linking line_style...
Linking list_visuals...
Compiling mandelbrot_ui.cxx...
Compiling mandelbrot.cxx...
Linking menubar...
Linking message...
Linking minimum...
Linking native-filechooser...
Linking navigation...
Linking output...
Linking overlay...
Linking pack...
Linking pixmap...
Linking pixmap_browser...
Compiling preferences.cxx...
Compiling radio.cxx...
Compiling resize.cxx...
Linking resizebox...
Linking rotated_text...
Linking scroll...
Linking subwindow...
Linking sudoku...
Linking symbols...
Linking table...
Compiling tabs.cxx...
Linking threads...
Linking tile...
Linking tiled_image...
Compiling tree.cxx...
Linking twowin...
Compiling valuators.cxx...
Linking utf8...
Linking windowfocus...
Linking cube...
Compiling CubeMain.cxx...
Linking fractals...
Linking fullscreen...
Linking gl_overlay...
Linking glpuzzle...
Linking shape...
Linking fast_slow...
Linking inactive...
Linking keyboard...
Linking mandelbrot...
Linking preferences...
Linking radio...
Linking resize...
Linking tabs...
Linking tree...
Linking valuators...
Linking CubeView...
=== making documentation ===
Formatting src/fltk.man...
Formatting src/fltk-config.man...
Formatting src/fluid.man...
Formatting src/blocks.man...
Formatting src/checkers.man...
Formatting src/sudoku.man...
[  7%] Performing install step for 'OWN_FLTK'
=== installing FL ===
Installing include files in /home/dgl/relion/external/fltk/include...
=== installing jpeg ===
Installing ../lib/libfltk_jpeg.a in /home/dgl/relion/external/fltk/lib...
Installing jpeg headers in /home/dgl/relion/external/fltk/include/FL/images...
=== installing src ===
Installing libraries in /home/dgl/relion/external/fltk/lib...
=== installing fluid ===
Installing FLUID in /home/dgl/relion/external/fltk/bin...
=== installing test ===
Installing example programs to /home/dgl/relion/external/fltk/share/doc/fltk/examples...
=== installing documentation ===
Installing documentation files in /home/dgl/relion/external/fltk/share/doc/fltk ...
Installing man pages in /home/dgl/relion/external/fltk/share/man ...
[  7%] Completed 'OWN_FLTK'
[  7%] Built target OWN_FLTK
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by biochem-fan** [comment]
No longer relevant.
