### ISSUE TITLE
SLURM job submission script

### ISSUE THREAD

**Issue by dougbevan** [3dem/relion#408]
Hello.

We are trying to get relion3 beta working for job submission via the gui using the job script template.  Here is the template we are using for CPU jobs, which is working so far.  We would also like for GPUs to be selectable, but these would need to be reserved by slurm as well.  Is there something we can add to the job template that will allow this to be passed from the gui?

------------------------------------------

#!/bin/bash

### Job name
#SBATCH --job-name="XXXnameXXX"

### Queue name
#SBATCH --partition=XXXqueueXXX

### Specify the number of nodes and thread (ppn) for your job.
#SBATCH --nodes=XXXthreadsXXX
#SBATCH --ntasks=XXXmpinodesXXX

### Different units can be specified using the suffix [K|M|G|T]
##SBATCH --mem 1G

### The anticipated run-time for your job, where walltime=HH:MM:SS
##SBATCH --time==XXXextra1XXX

#################################
### Switch to the working directory;
cd $SLURM_SUBMIT_DIR

module load cryoem/relion/3.0beta
module load local/openmpi/3.1.2
#module load CUDA (no CUDA on Executor)

### Run:
mpirun --map-by node -np XXXmpinodesXXX XXXcommandXXX
echo "done"

**Comment by dougbevan** [comment]
Well, in the interface you can select a number of GPUs, but I don't see how this gets passed to SLURM.

You mean like:

#SBATCH --gres=XXXextra2XXX

?

**Comment by biochem-fan** [comment]
You can add new input fields in the `Running` tab of the GUI by `RELION_QSUB_EXTRA1`, `RELION_QSUB_EXTRA2`, etc, which will replace `XXXextra1XXX`, `XXXextra2XXX`, etc in the template. So users can specify the number of GPU there. There is no easy way to pass the value in `Which GPUs to use` to the script header. Well, you can write a `bsub` wrapper which parses the `--gpu` argument and appends correct options to (real) `bsub`.

**Comment by dougbevan** [comment]
I see.  So the job script would be like:

#SBATCH --gres=gpu:XXXextra1XXX

Where XXXextra1XXX is the value of the field added to the running tab of relion.

What I'm not clear on, is h ow to add the fields.  Where does one put a statement like "RELION_QSUB_EXTRA1 and how do you define the options for the field?

**Comment by biochem-fan** [comment]
You use environmental variables. For example, in bash,
```
export RELION_QSUB_EXTRA1='Number of GPUs'
export RELION_QSUB_EXTRA1_DEFAULT='0'
```
will give the following entry in the `Running` tab.
![image](https://user-images.githubusercontent.com/1611483/47442899-1d8d9e80-d7ab-11e8-838e-7245bc210bb5.png)

**Comment by dougbevan** [comment]
This is a great solution, biochem-fan.  Do you use this as well?

Testing now....

**Comment by dougbevan** [comment]
Works brilliantly.
