### ISSUE TITLE
Installation of Relion in GPU cluster

### ISSUE THREAD

**Issue by sayanbhakta** [3dem/relion#409]
I have a GPU cluster with a master node with no graphics card and three slave nodes with GeForce GTX 1080 Ti graphics card. CUDA 7.5 is installed in all the four nodes. Three slave nodes have appropriate NVIDIA graphics card installed.
I have compiled Relion 2.1 in the master node successfully.
Now I am stuck how to specify which graphics and which node to use during processing. How to setup the environment so that I can submit the job simultaneously with three slave nodes.
Please help.

**Comment by biochem-fan** [comment]
Not a RELION issue.
