### ISSUE TITLE
built to /opt/cryoem/relion3.0b_new, but errors reference /opt/local/temp

### ISSUE THREAD

**Issue by dougbevan** [3dem/relion#410]
Hello.

Downloaded source to a temp directory, then installed using the cmake prefix flag.  The bin and lib folders get built properly at the prefix location, but I'm getting error messages that reference the temp location when trying to run a job.  

Also can't figure out why GPUs aren't working, but it may be related to this other issue.

ERROR: no CUDA-capable device is detected in /opt/local/temp/relion-3.0_beta/src/ml_optimiser_mpi.cpp at line 128 (error-code 38)
ERROR: no CUDA-capable device is detected in /opt/local/temp/relion-3.0_beta/src/ml_optimiser_mpi.cpp at line 128 (error-code 38)
in: /opt/local/temp/relion-3.0_beta/src/acc/cuda/cuda_settings.h, line 67
=== Backtrace  ===
/opt/cryoem/relion3.0b_new/bin/relion_refine_mpi(_ZN11RelionErrorC1ERKSsS1_l+0x61) [0x435501]
/opt/cryoem/relion3.0b_new/bin/relion_refine_mpi() [0x44b889]
/opt/cryoem/relion3.0b_new/bin/relion_refine_mpi(_ZN14MlOptimiserMpi10initialiseEv+0x22a4) [0x45ccf4]
/opt/cryoem/relion3.0b_new/bin/relion_refine_mpi(main+0x72) [0x42a2c2]
/lib64/libc.so.6(__libc_start_main+0xfd) [0x3d3da1ed1d]
/opt/cryoem/relion3.0b_new/bin/relion_refine_mpi() [0x42a159]
==================
in: /opt/local/temp/relion-3.0_beta/src/acc/cuda/cuda_settings.h, line 67
=== Backtrace  ===
/opt/cryoem/relion3.0b_new/bin/relion_refine_mpi(_ZN11RelionErrorC1ERKSsS1_l+0x61) [0x435501]
/opt/cryoem/relion3.0b_new/bin/relion_refine_mpi() [0x44b889]
/opt/cryoem/relion3.0b_new/bin/relion_refine_mpi(_ZN14MlOptimiserMpi10initialiseEv+0x22a4) [0x45ccf4]
/opt/cryoem/relion3.0b_new/bin/relion_refine_mpi(main+0x72) [0x42a2c2]
/lib64/libc.so.6(__libc_start_main+0xfd) [0x3d3da1ed1d]
/opt/cryoem/relion3.0b_new/bin/relion_refine_mpi() [0x42a159]
==================
ERROR: 

A GPU-function failed to execute.

**Comment by biochem-fan** [comment]
The path refers to the path of the source codes when the binary was compiled, not the installed location. You don't have to worry about it. The real problem is your GPU.

**Comment by dougbevan** [comment]
Interesting, so ignore those.  

How to best track down the GPU issue?  It's a single-node compute system, GPU local, defined in the scheduler.  Latest driver, CUDA toolkit available in the path.
