### ISSUE TITLE
Relion3: Autopick

### ISSUE THREAD

**Issue by ss4858cu** [3dem/relion#411]
Hi,

I am trying to run autopick on a server. While the entire process finishes with:
 Autopicking ...
 Generating logfile.pdf ... 
   9/   9 sec ............................................................~~(,_,">
 Total number of particles from 5536 micrographs is 1.51119e+06
 i.e. on average there were 273 particles per micrograph

It gets stuck at the last step, without creating any coords_suffix.star file with the error message:
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted (core dumped)

The server is running low on RAM, as another user is running Motion correction. Is there any way I can get past this error under current circumstances?

Thanks,
Shikha

**Comment by biochem-fan** [comment]
You can split your input STAR files into several files, so that each contains fewer micrographs. Run AutoPick and Extraction separately and join the resulting STAR files.
