### ISSUE TITLE
Relion3 Motion correction erorrs

### ISSUE THREAD

**Issue by Itaisrn** [3dem/relion#412]
Hi,
I'm trying to run a motion correction job in the relion3-beta GUI but keep getting various errors.
The first one makes it impossible to run relion's own implementation:

The following warnings were encountered upon command-line parsing: 
WARNING: Option --use_own	is not a valid RELION argument
WARNING: Option --gain_rot	is not a valid RELION argument
WARNING: Option --gain_flip	is not a valid RELION argument
ERROR: 
 ERROR: You have to specify which programme to use through either --use_motioncor2 or --use_unblur
File: /prog/relion/src/motioncorr_runner.cpp line: 119

I do, of course, specify which program to use, but because of the parsing error relion doesn't get the command.
If I try to use MotionCorr2 it starts the run but then immediately crashes:

The following warnings were encountered upon command-line parsing: 
WARNING: Option --gain_rot	is not a valid RELION argument
WARNING: Option --gain_flip	is not a valid RELION argument
 WARNING: there was an error executing: /prog/MotionCor2  -InMrc Micrographs/18may22b/18may22b_IS7_00042gr_00005sq_v02_00002hl_00001en.frames.mrcs -OutMrc MotionCorr/job011/Micrographs/18may22b/18may22b_IS7_00042gr_00005sq_v02_00002hl_00001en_frames.mrc -LogFile MotionCorr/job011/Micrographs/18may22b/18may22b_IS7_00042gr_00005sq_v02_00002hl_00001en_frames -Bft 150 -PixSize 1.16 -Patch 5 5 -Gain Micrographs/references_18may2018/18may22b_22132933_05_3838x3710_norm_0.mrc -Throw 3 -FtBin 2 -Kv 200 -FmDose 0.9 -InitDose 0  -- FlipGain 1  -Gpu 0 >> MotionCorr/job011/Micrographs/18may22b/18may22b_IS7_00042gr_00005sq_v02_00002hl_00001en_frames.out 2>> MotionCorr/job011/Micrographs/18may22b/18may22b_IS7_00042gr_00005sq_v02_00002hl_00001en_frames.err
GPL Ghostscript 9.18: Unrecoverable error, exit code 1

Did I make a mistake during installation or something like that?

**Comment by Itaisrn** [comment]
Forgot to mention it, but the exact same things happen with the tutorial dataset using the recommended parameters.

**Comment by biochem-fan** [comment]
It seems that you are running version 3.0 of the GUI but `relion_run_motioncorr` from version 2.1. Please verify your `PATH` environmental variable. Note that starting the GUI with full path like  `/path/to/relion_3.0/bin/relion` without updating your `PATH` is **NOT** enough.

**Comment by Itaisrn** [comment]
You are right, thanks!
