### ISSUE TITLE
Problems to run refine2D for input mrcs generated from EMAN hed(img) file

### ISSUE THREAD

**Issue by davidh99720** [3dem/relion#413]
I am trying to do a simulation to test the power of RELION2.1 refine2D algorithm.
The input is a EMAN hed(img) file and I convert it to mrcs file using e2proc2d.py
Then, I import it as mrcs file and write bash to generate a particles.star file for it. The head of it is attached in the appendix in the end.

However, when I try refine2D, I encounter the following error:
ERROR: 
image.cpp::calculateBackgroundAvgStddev(): No pixels in background are found. Radius of circular mask is too large.
File: /home/xxx/Software/relions/relion/src/image.cpp line: 246

Any idea of how to fix it will greatly appreciated!

-----------------------
Appendix:
data_

loop_ 
_rlnCoordinateX #1 
_rlnCoordinateY #2 
_rlnClassNumber #3 
_rlnAnglePsi #4 
_rlnAutopickFigureOfMerit #5 
_rlnImageName #6 
_rlnMicrographName #7 
_rlnMagnification #8 
_rlnDetectorPixelSize #9 
0 0 -999 -999 -999 000001@Import/job001/GroEL-proj-shft10-addnoise150.mrcs null 100000 1
0 0 -999 -999 -999 000002@Import/job001/GroEL-proj-shft10-addnoise150.mrcs null 100000 1
0 0 -999 -999 -999 000003@Import/job001/GroEL-proj-shft10-addnoise150.mrcs null 100000 1
0 0 -999 -999 -999 000004@Import/job001/GroEL-proj-shft10-addnoise150.mrcs null 100000 1
0 0 -999 -999 -999 000005@Import/job001/GroEL-proj-shft10-addnoise150.mrcs null 100000 1
0 0 -999 -999 -999 000006@Import/job001/GroEL-proj-shft10-addnoise150.mrcs null 100000 1
0 0 -999 -999 -999 000007@Import/job001/GroEL-proj-shft10-addnoise150.mrcs null 100000 1
0 0 -999 -999 -999 000008@Import/job001/GroEL-proj-shft10-addnoise150.mrcs null 100000 1
0 0 -999 -999 -999 000009@Import/job001/GroEL-proj-shft10-addnoise150.mrcs null 100000 1
0 0 -999 -999 -999 000010@Import/job001/GroEL-proj-shft10-addnoise150.mrcs null 100000 1
0 0 -999 -999 -999 000011@Import/job001/GroEL-proj-shft10-addnoise150.mrcs null 100000 1
0 0 -999 -999 -999 000012@Import/job001/GroEL-proj-shft10-addnoise150.mrcs null 100000 1
0 0 -999 -999 -999 000013@Import/job001/GroEL-proj-shft10-addnoise150.mrcs null 100000 1
0 0 -999 -999 -999 000014@Import/job001/GroEL-proj-shft10-addnoise150.mrcs null 100000 1
0 0 -999 -999 -999 000015@Import/job001/GroEL-proj-shft10-addnoise150.mrcs null 100000 1
0 0 -999 -999 -999 000016@Import/job001/GroEL-proj-shft10-addnoise150.mrcs null 100000 1
0 0 -999 -999 -999 000017@Import/job001/GroEL-proj-shft10-addnoise150.mrcs null 100000 1
0 0 -999 -999 -999 000018@Import/job001/GroEL-proj-shft10-addnoise150.mrcs null 100000 1
0 0 -999 -999 -999 000019@Import/job001/GroEL-proj-shft10-addnoise150.mrcs null 100000 1
0 0 -999 -999 -999 000020@Import/job001/GroEL-proj-shft10-addnoise150.mrcs null 100000 1
0 0 -999 -999 -999 000021@Import/job001/GroEL-proj-shft10-addnoise150.mrcs null 100000 1
0 0 -999 -999 -999 000022@Import/job001/GroEL-proj-shft10-addnoise150.mrcs null 100000 1
0 0 -999 -999 -999 000023@Import/job001/GroEL-proj-shft10-addnoise150.mrcs null 100000 1
0 0 -999 -999 -999 000024@Import/job001/GroEL-proj-shft10-addnoise150.mrcs null 100000 1
0 0 -999 -999 -999 000025@Import/job001/GroEL-proj-shft10-addnoise150.mrcs null 100000 1
0 0 -999 -999 -999 000026@Import/job001/GroEL-proj-shft10-addnoise150.mrcs null 100000 1
0 0 -999 -999 -999 000027@Import/job001/GroEL-proj-shft10-addnoise150.mrcs null 100000 1
0 0 -999 -999 -999 000028@Import/job001/GroEL-proj-shft10-addnoise150.mrcs null 100000 1
0 0 -999 -999 -999 000029@Import/job001/GroEL-proj-shft10-addnoise150.mrcs null 100000 1

**Comment by biochem-fan** [comment]
Is your pixel size correct? If not, specify in  `--angpix`. Also note that the particle mask diameter is in angstrom.

**Comment by davidh99720** [comment]
> Is your pixel size correct? If not, specify in `--angpix`. Also note that the particle mask diameter is in angstrom.

Yes, it is correct. I figure it out after thinking it over. I change the star file to the following and it works.
Basically I set the coordinates to -999 -999 following RELION conventions for other invalid parameters and set the micrograph to None as RELION did for other cases.

Thank you!
--------------------------------
data_

loop_ 
_rlnCoordinateX #1 
_rlnCoordinateY #2 
_rlnClassNumber #3 
_rlnAnglePsi #4 
_rlnAutopickFigureOfMerit #5 
_rlnImageName #6 
_rlnMicrographName #7 
_rlnMagnification #8 
_rlnDetectorPixelSize #9 
 -999 -999 -999 -999 -999 000001@Import/job001/GroEL-proj-shft10-addnoise150.mrcs None 10000 1
 -999 -999 -999 -999 -999 000002@Import/job001/GroEL-proj-shft10-addnoise150.mrcs None 10000 1
 -999 -999 -999 -999 -999 000003@Import/job001/GroEL-proj-shft10-addnoise150.mrcs None 10000 1
 -999 -999 -999 -999 -999 000004@Import/job001/GroEL-proj-shft10-addnoise150.mrcs None 10000 1
 -999 -999 -999 -999 -999 000005@Import/job001/GroEL-proj-shft10-addnoise150.mrcs None 10000 1
 -999 -999 -999 -999 -999 000006@Import/job001/GroEL-proj-shft10-addnoise150.mrcs None 10000 1
 -999 -999 -999 -999 -999 000007@Import/job001/GroEL-proj-shft10-addnoise150.mrcs None 10000 1
 -999 -999 -999 -999 -999 000008@Import/job001/GroEL-proj-shft10-addnoise150.mrcs None 10000 1
 -999 -999 -999 -999 -999 000009@Import/job001/GroEL-proj-shft10-addnoise150.mrcs None 10000 1
 -999 -999 -999 -999 -999 000010@Import/job001/GroEL-proj-shft10-addnoise150.mrcs None 10000 1
 -999 -999 -999 -999 -999 000011@Import/job001/GroEL-proj-shft10-addnoise150.mrcs None 10000 1
 -999 -999 -999 -999 -999 000012@Import/job001/GroEL-proj-shft10-addnoise150.mrcs None 10000 1
 -999 -999 -999 -999 -999 000013@Import/job001/GroEL-proj-shft10-addnoise150.mrcs None 10000 1
 -999 -999 -999 -999 -999 000014@Import/job001/GroEL-proj-shft10-addnoise150.mrcs None 10000 1
 -999 -999 -999 -999 -999 000015@Import/job001/GroEL-proj-shft10-addnoise150.mrcs None 10000 1
 -999 -999 -999 -999 -999 000016@Import/job001/GroEL-proj-shft10-addnoise150.mrcs None 10000 1
 -999 -999 -999 -999 -999 000017@Import/job001/GroEL-proj-shft10-addnoise150.mrcs None 10000 1
 -999 -999 -999 -999 -999 000018@Import/job001/GroEL-proj-shft10-addnoise150.mrcs None 10000 1
 -999 -999 -999 -999 -999 000019@Import/job001/GroEL-proj-shft10-addnoise150.mrcs None 10000 1
 -999 -999 -999 -999 -999 000020@Import/job001/GroEL-proj-shft10-addnoise150.mrcs None 10000 1
 -999 -999 -999 -999 -999 000021@Import/job001/GroEL-proj-shft10-addnoise150.mrcs None 10000 1
 -999 -999 -999 -999 -999 000022@Import/job001/GroEL-proj-shft10-addnoise150.mrcs None 10000 1
 -999 -999 -999 -999 -999 000023@Import/job001/GroEL-proj-shft10-addnoise150.mrcs None 10000 1
 -999 -999 -999 -999 -999 000024@Import/job001/GroEL-proj-shft10-addnoise150.mrcs None 10000 1
 -999 -999 -999 -999 -999 000025@Import/job001/GroEL-proj-shft10-addnoise150.mrcs None 10000 1
 -999 -999 -999 -999 -999 000026@Import/job001/GroEL-proj-shft10-addnoise150.mrcs None 10000 1
 -999 -999 -999 -999 -999 000027@Import/job001/GroEL-proj-shft10-addnoise150.mrcs None 10000 1
 -999 -999 -999 -999 -999 000028@Import/job001/GroEL-proj-shft10-addnoise150.mrcs None 10000 1
 -999 -999 -999 -999 -999 000029@Import/job001/GroEL-proj-shft10-addnoise150.mrcs None 10000 1
