### ISSUE TITLE
GPU acceleration not working with two NVIDIA GPUs with one's sm<3.5 and one's sm=6.1

### ISSUE THREAD

**Issue by davidh99720** [3dem/relion#414]
My situation of GPU is:
![image](https://user-images.githubusercontent.com/32203454/47686561-109cf080-db99-11e8-8547-92171843b95e.png)

When I run class-average, the error below stops my from using it. 

WARNING : at least one of your GPUs is not compatible with RELION (CUDA-capable and compute-capability >= 3.5)
ERROR: unknown error in /home/cyhuang/Software/relions/relion/src/gpu_utils/cuda_projector.cu at line 154 (error-code 30)

I do have specified which GPU to use as '1', which should referring to the QUDRO P2000 card that has sm=6.1 
In the installation, the -DCUDA_ARCH I use is 61

I wonder if there is a way to solve it?

**Comment by biochem-fan** [comment]
Probably "hiding" the old GPU completely by `CUDA_VISIBLE_DEVICES=1` might help. (Now P6000 will be GPU 0 for RELION).
