### ISSUE TITLE
relion3 make issue

### ISSUE THREAD

**Issue by GeemG** [3dem/relion#415]
Hi i am getting an error after > make -j - . I am wondering how to solve it. Relion2 works fine. Thanks

------------
sudo make -j4
-- BUILD TYPE set to the default type:  'Release'
-- Setting fallback CUDA_ARCH=35
-- CUDA enabled - Building CUDA-accelerated version of RELION
-- Setting cpu precision to double
-- Setting accelerated code precision to single
-- Using cuda wrapper to compile....
-- Cuda version is >= 7.5 and single-precision build, enable double usage warning.
-- CMAKE_C_COMPILER : /usr/bin/cc
-- CMAKE_CXX_COMPILER : /usr/bin/c++
-- MPI_C_COMPILER : /usr/bin/mpicc
-- MPI_CXX_COMPILER : /usr/bin/mpicxx
-- CMAKE_CXX_COMPILER_ID : GNU
-- MPI_INCLUDE_PATH : /usr/lib/openmpi/include/openmpi/opal/mca/event/libevent2021/libevent;/usr/lib/openmpi/include/openmpi/opal/mca/event/libevent2021/libevent/include;/usr/lib/openmpi/include;/usr/lib/openmpi/include/openmpi
-- MPI_LIBRARIES : /usr/lib/openmpi/lib/libmpi_cxx.so;/usr/lib/openmpi/lib/libmpi.so
-- MPI_CXX_INCLUDE_PATH : /usr/lib/openmpi/include/openmpi/opal/mca/event/libevent2021/libevent;/usr/lib/openmpi/include/openmpi/opal/mca/event/libevent2021/libevent/include;/usr/lib/openmpi/include;/usr/lib/openmpi/include/openmpi
-- MPI_CXX_LIBRARIES : /usr/lib/openmpi/lib/libmpi_cxx.so;/usr/lib/openmpi/lib/libmpi.so
-- Could NOT find FLTK (missing:  FLTK_LIBRARIES FLTK_FLUID_EXECUTABLE) 
-- No FLTK installation was found
-- Found previously built non-system FLTK libraries that will be used.
-- FLTK_INCLUDE_DIR: /mnt/data1/App/relion3-git/relion-3.0_beta/external/fltk/include
-- FLTK_LIBRARIES:   /mnt/data1/App/relion3-git/relion-3.0_beta/external/fltk/lib/libfltk.so
-- Found FFTW
-- FFTW_PATH: /usr/include
-- FFTW_INCLUDES: /usr/include
-- FFTW_LIBRARIES: /usr/lib/x86_64-linux-gnu/libfftw3f.so;/usr/lib/x86_64-linux-gnu/libfftw3.so
BUILD_SHARED_LIBS = OFF
-- Building static libs (larger build size and binaries)
Running apps/CMakeLists.txt...
-- CMAKE_BINARY_DIR:/mnt/data1/App/relion3-git/relion-3.0_beta/build
TIFF FOUND
OPENMP FOUND
-- Configuring done
-- Generating done
-- Build files have been written to: /mnt/data1/App/relion3-git/relion-3.0_beta/build
[  0%] Built target copy_scripts
[ 55%] Built target relion_lib
[ 55%] Building NVCC (Device) object src/apps/CMakeFiles/relion_gpu_util.dir/__/acc/cuda/cuda_kernels/relion_gpu_util_generated_helper.cu.o
[ 55%] Building NVCC (Device) object src/apps/CMakeFiles/relion_gpu_util.dir/__/acc/cuda/relion_gpu_util_generated_cuda_projector.cu.o
[ 56%] Building NVCC (Device) object src/apps/CMakeFiles/relion_gpu_util.dir/__/acc/cuda/relion_gpu_util_generated_cuda_backprojector.cu.o
[ 56%] Building NVCC (Device) object src/apps/CMakeFiles/relion_gpu_util.dir/__/acc/cuda/relion_gpu_util_generated_cuda_projector_plan.cu.o
/usr/include/string.h: In function ‘void* __mempcpy_inline(void*, const void*, size_t)’:
/usr/include/string.h:652:42: error: ‘memcpy’ was not declared in this scope
   return (char *) memcpy (__dest, __src, __n) + __n;
                                          ^
/usr/include/string.h: In function ‘void* __mempcpy_inline(void*, const void*, size_t)’:
/usr/include/string.h:652:42: error: ‘memcpy’ was not declared in this scope
   return (char *) memcpy (__dest, __src, __n) + __n;
                                          ^
CMake Error at relion_gpu_util_generated_cuda_projector.cu.o.cmake:266 (message):
  Error generating file
  /mnt/data1/App/relion3-git/relion-3.0_beta/build/src/apps/CMakeFiles/relion_gpu_util.dir/__/acc/cuda/./relion_gpu_util_generated_cuda_projector.cu.o

src/apps/CMakeFiles/relion_gpu_util.dir/build.make:977: recipe for target 'src/apps/CMakeFiles/relion_gpu_util.dir/__/acc/cuda/relion_gpu_util_generated_cuda_projector.cu.o' failed
make[2]: *** [src/apps/CMakeFiles/relion_gpu_util.dir/__/acc/cuda/relion_gpu_util_generated_cuda_projector.cu.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMake Error at relion_gpu_util_generated_cuda_backprojector.cu.o.cmake:266 (message):
  Error generating file
  /mnt/data1/App/relion3-git/relion-3.0_beta/build/src/apps/CMakeFiles/relion_gpu_util.dir/__/acc/cuda/./relion_gpu_util_generated_cuda_backprojector.cu.o

src/apps/CMakeFiles/relion_gpu_util.dir/build.make:737: recipe for target 'src/apps/CMakeFiles/relion_gpu_util.dir/__/acc/cuda/relion_gpu_util_generated_cuda_backprojector.cu.o' failed
make[2]: *** [src/apps/CMakeFiles/relion_gpu_util.dir/__/acc/cuda/relion_gpu_util_generated_cuda_backprojector.cu.o] Error 1
/usr/include/string.h: In function ‘void* __mempcpy_inline(void*, const void*, size_t)’:
/usr/include/string.h:652:42: error: ‘memcpy’ was not declared in this scope
   return (char *) memcpy (__dest, __src, __n) + __n;
                                          ^
/usr/include/string.h: In function ‘void* __mempcpy_inline(void*, const void*, size_t)’:
/usr/include/string.h:652:42: error: ‘memcpy’ was not declared in this scope
   return (char *) memcpy (__dest, __src, __n) + __n;
                                          ^
CMake Error at relion_gpu_util_generated_helper.cu.o.cmake:266 (message):
  Error generating file
  /mnt/data1/App/relion3-git/relion-3.0_beta/build/src/apps/CMakeFiles/relion_gpu_util.dir/__/acc/cuda/cuda_kernels/./relion_gpu_util_generated_helper.cu.o

src/apps/CMakeFiles/relion_gpu_util.dir/build.make:1263: recipe for target 'src/apps/CMakeFiles/relion_gpu_util.dir/__/acc/cuda/cuda_kernels/relion_gpu_util_generated_helper.cu.o' failed
make[2]: *** [src/apps/CMakeFiles/relion_gpu_util.dir/__/acc/cuda/cuda_kernels/relion_gpu_util_generated_helper.cu.o] Error 1
CMake Error at relion_gpu_util_generated_cuda_projector_plan.cu.o.cmake:266 (message):
  Error generating file
  /mnt/data1/App/relion3-git/relion-3.0_beta/build/src/apps/CMakeFiles/relion_gpu_util.dir/__/acc/cuda/./relion_gpu_util_generated_cuda_projector_plan.cu.o

src/apps/CMakeFiles/relion_gpu_util.dir/build.make:496: recipe for target 'src/apps/CMakeFiles/relion_gpu_util.dir/__/acc/cuda/relion_gpu_util_generated_cuda_projector_plan.cu.o' failed
make[2]: *** [src/apps/CMakeFiles/relion_gpu_util.dir/__/acc/cuda/relion_gpu_util_generated_cuda_projector_plan.cu.o] Error 1
CMakeFiles/Makefile2:923: recipe for target 'src/apps/CMakeFiles/relion_gpu_util.dir/all' failed
make[1]: *** [src/apps/CMakeFiles/relion_gpu_util.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by biochem-fan** [comment]
Likely an incompatible combination of GCC and CUDA versions. Anyway, too old issue.
