### ISSUE TITLE
2D classification error

### ISSUE THREAD

**Issue by RubenHM80** [3dem/relion#416]
Hi all,

I have 2 set of extracted particles that finally I join into one single data file using the join star files function. When I try to run the 2D classification, systematically appears this error during the noise spectra estimation: 

Estimating initial noise spectra 
0.68/8.20 min ....~~(,_,">--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 1 in communicator MPI_COMM_WORLD 
with errorcode 1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
-----------------------------------------

In the run.err file appears the following error:
ERROR: 
Backprojector::set2DSlice%%ERROR: Dimension of the data array should be 2 or 3
File: /usr/local/src/relion-2.1.b1/src/backprojector.h line: 201

This is the print command of the 2D job:
`which relion_refine_mpi` --continue Class2D/job078/run_it010_optimiser.star --o Class2D/job170/run_ct10 --dont_combine_weights_via_disc --scratch_dir /scratch --pool 3 --iter 30 --tau2_fudge 2 --particle_diameter 205 --oversampling 1 --psi_step 12 --offset_range 5 --offset_step 2 --helical_outer_diameter 160 --bimodal_psi --sigma_psi 2 --j 1 --gpu ""

If I try to do the 2D classification with every set of data independently it works perfectly, but not the the joint file.

Any idea?
Thanks,
Ruben

**Comment by bforsbe** [comment]
This has been occurring quite frequently of late, and the solution is pushed to the [relion3-beta repo](https://bitbucket.org/scheres/relion-3.0_beta/src/master). To clone from that repo, you can use the command

```
git clone https://bforsbe@bitbucket.org/scheres/relion-3.0_beta.git
```

**Comment by RubenHM80** [comment]
It worked, thanks!
