### ISSUE TITLE
Slow running jobs on dual socket 4GPU servers

### ISSUE THREAD

**Issue by donaldbenton** [3dem/relion#419]
We have been experiencing slow running of Relion jobs on some new dual-socket quad GPU nodes. 

Specifically it is a server with dual Xeon 4116 silver CPUs, 384GB RAM, 4x GTX1080Ti (2 attached to each socket).

We are running the current build of Relion 3. The jobs appear to start off at a comparable speed to another 4 GPU server, however as the iteration progresses the estimated time increases greatly to around 3x the initial estimate and also the GPU usage reduces. By another iteration or two in the GPU usage is very low with 0% showing on nvidia-smi with very occasional peaks on single GPUs and absurdly long predicted iteration times. The identical Class3D job with the dataset read from the same location completes at high speed on another 4 GPU node or on a 2 GPU desktop workstation using an identically compiled version of Relion.

We have isolated the slowness to be coming from the particular kernel version that the server was running on. The server is running CentOS v.7.5 . The offending kernel update appears to be between 3.10.0-514 and 3.10.0-862. We can regain full performance by downgrading to the 514 version.

Updating to this newer kernel also gives openmpi errors not seen before (openmpi version is 1.10.7):

In run.out:
[[20083,1],2]: A high-performance Open MPI point-to-point messaging module
was unable to find any relevant network interfaces:

Module: OpenFabrics (openib)
  Host: sbserver6

Another transport will be used instead, although this may result in
lower performance.

In run.err:
[sbserver6:445355] 2 more processes have sent help message help-mpi-btl-base.txt / btl:no-nics
[sbserver6:445355] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages

This error can be removed and the speed increased by setting the variable:

setenv OMPI_MCA_btl ^openib

Between these two kernel versions the Spectre/Meltdown patches were applied in the kernel. We turned off these with the commands, which did not speed up the job:

echo 0 > /sys/kernel/debug/x86/pti_enabled
echo 0 > /sys/kernel/debug/x86/retp_enabled
echo 0 > /sys/kernel/debug/x86/ibrs_enabled

Do you have any idea what may be going on here? We can get full performance with the old kernel but it is not particularly sustainable for us to be operating with a kernel that is already ~2 years old.

**Comment by tbugfinder** [comment]
Hi @donaldbenton ,
did you find a solution or a way to improve the initial mentioned issue?

**Comment by biochem-fan** [comment]
If `setenv OMPI_MCA_btl ^openib` solves the speed issue and crash, please use the flag. This is a problem with OpenMPI (and InfiniBand kernel driver?), not RELION.
