### ISSUE TITLE
Bayesian Polishing error: "terminate called after throwing an instance of 'RelionError'"

### ISSUE THREAD

**Issue by rudaluna** [3dem/relion#421]
Hi,

I'm trying to run Bayesian Polishing after getting my optimized parameters and I get this error:

in: /primary/vari/software/relion/relion3.0-112618/src/image.h, line 248
terminate called after throwing an instance of 'RelionError'

I first tried first with 30 MPI processes, then with 1 MPI process and 30 threads, now it seems to be running with 1 MPI/thread. The files for the run are attached. Also the original movie files are in super resolution, whereas the motion corrected micrographs are binned by 2x.
[Archive.zip](https://github.com/3dem/relion/files/2649426/Archive.zip)

**Comment by rudaluna** [comment]
Sorry the Archive.zip contains the job from the training run, my mistake. I'm attaching the files from the actual polishing run. 

Unrelated question: is there a way to speed up the training? This one took almost a week (~10000 movies).
[Archive-job23.zip](https://github.com/3dem/relion/files/2649436/Archive-job23.zip)

**Comment by biochem-fan** [comment]
Does this problem happen with our tutorial dataset as well?
Are your movies from EPU or SerialEM? Are they in 4 bit?
4-bit MRC support was implemented just last week.

> is there a way to speed up the training?
Don't train but use the default parameters. In almost all cases, the resolution does not change.

**Comment by rudaluna** [comment]
> Does this problem happen with our tutorial dataset as well?

Didn't try the tutorial dataset. But I think it's specific for this dataset, I've done polishing with other datasets and it worked fine.

> Are your movies from EPU or SerialEM? Are they in 4 bit?

SerialEM, a byte (map mode 0)

> 4-bit MRC support was implemented just last week.
> 
> > is there a way to speed up the training?
> 
> Don't train but use the default parameters. In almost all cases, the resolution does not change.

Good to know!

**Comment by rudaluna** [comment]
Also the movies are in tif!

**Comment by biochem-fan** [comment]
> But I think it's specific for this dataset, I've done polishing with other datasets and it worked fine.

Are other successful datasets also 8-bit TIFF from SerialEM?
Are you sure none of your movies are corrupted? Doesn't your STAR file contain non-movie files?
Is the gain reference readable?

**Comment by biochem-fan** [comment]
> This is the first one.

I think RELION's implementation of 8-bit MRC is stable (4-bit MRC is very new and I am not confident).
If you have multiple machines, please confirm the problem happens in them as well.
From your another issue on Refine3D, I have an impression that something is unstable with your file system.

> I'm getting the headers of them all to confirm but I think if it was an error with a specific movie wouldn't it be caught by MotionCor earlier?

If you can run RELION's motion correction, it proves RELION can read the movies.

**Comment by rudaluna** [comment]
> > This is the first one.
> 
> I think RELION's implementation of 8-bit MRC is stable (4-bit MRC is very new and I am not confident).
> If you have multiple machines, please confirm the problem happens in them as well.
> From your another issue on Refine3D, I have an impression that something is unstable with your file system.
> 
> > I'm getting the headers of them all to confirm but I think if it was an error with a specific movie wouldn't it be caught by MotionCor earlier?
> 
> If you can run RELION's motion correction, it proves RELION can read the movies.

Maybe it's better if I describe my setup. We have an HPC room with many nodes that is ran by our IT department. 

Regarding the machines, I tried to run this job on many different nodes.

Regarding the filesystem, they have a specific network file system that syncs the backups and everything, I can get more details to you but if there was a system-wide filesystem error I think other users would have reported. I can put you in contact with you if you want.

**Comment by biochem-fan** [comment]
Hmm, I don't know.

What does `relion_image_handler --stats --i 1@movie.tiff` say? (Change 1 to 2, 3, 4, ... for every frame)

**Comment by rudaluna** [comment]
> Hmm, I don't know.
> 
> What does `relion_image_handler --stats --i 1@movie.tiff` say? (Change 1 to 2, 3, 4, ... for every frame)

This is the output for the loop "for i in {1..40}; do relion_image_handler --stats --i "$i"@stack_0001.tif; done"

1@stack_0001.tif : (x,y,z,n)= 7676 x 7420 x 1 x 1 ; avg= 0.185585 stddev= 0.431759 minval= 0 maxval= 15
2@stack_0001.tif : (x,y,z,n)= 7676 x 7420 x 1 x 1 ; avg= 0.186066 stddev= 0.432337 minval= 0 maxval= 15
3@stack_0001.tif : (x,y,z,n)= 7676 x 7420 x 1 x 1 ; avg= 0.185506 stddev= 0.431915 minval= 0 maxval= 15
4@stack_0001.tif : (x,y,z,n)= 7676 x 7420 x 1 x 1 ; avg= 0.185405 stddev= 0.431987 minval= 0 maxval= 15
5@stack_0001.tif : (x,y,z,n)= 7676 x 7420 x 1 x 1 ; avg= 0.185842 stddev= 0.432423 minval= 0 maxval= 15
6@stack_0001.tif : (x,y,z,n)= 7676 x 7420 x 1 x 1 ; avg= 0.185674 stddev= 0.432369 minval= 0 maxval= 15
7@stack_0001.tif : (x,y,z,n)= 7676 x 7420 x 1 x 1 ; avg= 0.185437 stddev= 0.432062 minval= 0 maxval= 15
8@stack_0001.tif : (x,y,z,n)= 7676 x 7420 x 1 x 1 ; avg= 0.185792 stddev= 0.432443 minval= 0 maxval= 15
9@stack_0001.tif : (x,y,z,n)= 7676 x 7420 x 1 x 1 ; avg= 0.185706 stddev= 0.432287 minval= 0 maxval= 15
10@stack_0001.tif : (x,y,z,n)= 7676 x 7420 x 1 x 1 ; avg= 0.185609 stddev= 0.432251 minval= 0 maxval= 15
11@stack_0001.tif : (x,y,z,n)= 7676 x 7420 x 1 x 1 ; avg= 0.185526 stddev= 0.432159 minval= 0 maxval= 15
12@stack_0001.tif : (x,y,z,n)= 7676 x 7420 x 1 x 1 ; avg= 0.185693 stddev= 0.432298 minval= 0 maxval= 15
13@stack_0001.tif : (x,y,z,n)= 7676 x 7420 x 1 x 1 ; avg= 0.185746 stddev= 0.432408 minval= 0 maxval= 15
14@stack_0001.tif : (x,y,z,n)= 7676 x 7420 x 1 x 1 ; avg= 0.18559 stddev= 0.43211 minval= 0 maxval= 15
15@stack_0001.tif : (x,y,z,n)= 7676 x 7420 x 1 x 1 ; avg= 0.185381 stddev= 0.431928 minval= 0 maxval= 15
16@stack_0001.tif : (x,y,z,n)= 7676 x 7420 x 1 x 1 ; avg= 0.185675 stddev= 0.432271 minval= 0 maxval= 15
17@stack_0001.tif : (x,y,z,n)= 7676 x 7420 x 1 x 1 ; avg= 0.185388 stddev= 0.431956 minval= 0 maxval= 15
18@stack_0001.tif : (x,y,z,n)= 7676 x 7420 x 1 x 1 ; avg= 0.185467 stddev= 0.432036 minval= 0 maxval= 15
19@stack_0001.tif : (x,y,z,n)= 7676 x 7420 x 1 x 1 ; avg= 0.185494 stddev= 0.432055 minval= 0 maxval= 15
20@stack_0001.tif : (x,y,z,n)= 7676 x 7420 x 1 x 1 ; avg= 0.185466 stddev= 0.432047 minval= 0 maxval= 15
21@stack_0001.tif : (x,y,z,n)= 7676 x 7420 x 1 x 1 ; avg= 0.185304 stddev= 0.431699 minval= 0 maxval= 15
22@stack_0001.tif : (x,y,z,n)= 7676 x 7420 x 1 x 1 ; avg= 0.185267 stddev= 0.431836 minval= 0 maxval= 15
23@stack_0001.tif : (x,y,z,n)= 7676 x 7420 x 1 x 1 ; avg= 0.185112 stddev= 0.431627 minval= 0 maxval= 15
24@stack_0001.tif : (x,y,z,n)= 7676 x 7420 x 1 x 1 ; avg= 0.185408 stddev= 0.431842 minval= 0 maxval= 15
25@stack_0001.tif : (x,y,z,n)= 7676 x 7420 x 1 x 1 ; avg= 0.185326 stddev= 0.43188 minval= 0 maxval= 12
26@stack_0001.tif : (x,y,z,n)= 7676 x 7420 x 1 x 1 ; avg= 0.185159 stddev= 0.431569 minval= 0 maxval= 15
27@stack_0001.tif : (x,y,z,n)= 7676 x 7420 x 1 x 1 ; avg= 0.1851 stddev= 0.431578 minval= 0 maxval= 13
28@stack_0001.tif : (x,y,z,n)= 7676 x 7420 x 1 x 1 ; avg= 0.185539 stddev= 0.431904 minval= 0 maxval= 15
29@stack_0001.tif : (x,y,z,n)= 7676 x 7420 x 1 x 1 ; avg= 0.185436 stddev= 0.432006 minval= 0 maxval= 15
30@stack_0001.tif : (x,y,z,n)= 7676 x 7420 x 1 x 1 ; avg= 0.185363 stddev= 0.431919 minval= 0 maxval= 15
31@stack_0001.tif : (x,y,z,n)= 7676 x 7420 x 1 x 1 ; avg= 0.185211 stddev= 0.431762 minval= 0 maxval= 15
32@stack_0001.tif : (x,y,z,n)= 7676 x 7420 x 1 x 1 ; avg= 0.185429 stddev= 0.431915 minval= 0 maxval= 15
33@stack_0001.tif : (x,y,z,n)= 7676 x 7420 x 1 x 1 ; avg= 0.185439 stddev= 0.432038 minval= 0 maxval= 15
34@stack_0001.tif : (x,y,z,n)= 7676 x 7420 x 1 x 1 ; avg= 0.185575 stddev= 0.43198 minval= 0 maxval= 14
35@stack_0001.tif : (x,y,z,n)= 7676 x 7420 x 1 x 1 ; avg= 0.185636 stddev= 0.43224 minval= 0 maxval= 14
36@stack_0001.tif : (x,y,z,n)= 7676 x 7420 x 1 x 1 ; avg= 0.185582 stddev= 0.431812 minval= 0 maxval= 15
37@stack_0001.tif : (x,y,z,n)= 7676 x 7420 x 1 x 1 ; avg= 0.185291 stddev= 0.431779 minval= 0 maxval= 14
38@stack_0001.tif : (x,y,z,n)= 7676 x 7420 x 1 x 1 ; avg= 0.185704 stddev= 0.432222 minval= 0 maxval= 11
39@stack_0001.tif : (x,y,z,n)= 7676 x 7420 x 1 x 1 ; avg= 0.185529 stddev= 0.431867 minval= 0 maxval= 11
40@stack_0001.tif : (x,y,z,n)= 7676 x 7420 x 1 x 1 ; avg= 0.185633 stddev= 0.432043 minval= 0 maxval= 15

On a side note I'm rerunning the job but instead of giving the opt_parm file I manually put the values. It seems to be working but others also crashed in the middle. I'll let you know what happens.

**Comment by biochem-fan** [comment]
Thanks. This looks the movie is read correctly.

**Comment by rudaluna** [comment]
> Does it contain particles from a same micrograph but extracted in multiple jobs? This might be related to https://bitbucket.org/scheres/relion-3.0_beta/issues/49/ctf-refinement-from-a-star-file-containing.

It doesn't, it was all from a single job. It actually finished last night and I'm running Refinement with it and no errors so far. The only change I made was instead of giving the opt_parm.txt file I manually gave the values on the command line.
