### ISSUE TITLE
Crash while performing particle extraction

### ISSUE THREAD

**Issue by kehrnal** [3dem/relion#423]
I just attempted to run a particle extraction and received the following error in the terminal and a GUI crash:
PipeLine::addNode ERROR: Adding an empty nodename. Did you fill in all Node names correctly?

After going back through, I realized I had neglected to include "input coordinates".  A fix so the GUI doesn't crash would be appreciated.
Thanks!

**Comment by biochem-fan** [comment]
Thank you very much for the report. I fixed this in commit 656344e on BitBucket.
