### ISSUE TITLE
Relion prematurely exit during 2D classification

### ISSUE THREAD

**Issue by Sunyp-IM** [3dem/relion#424]
Hi,
I am running 2D classification with Relion. I use 6 cpu and without GPU and after a while Relion automatically exit before the step is finished. I get a message from the terminal which reads:
"The relion GUI has been idle for more than 3600 seconds, exiting now..."
Could you tell me how to avoid this?
Thank you in advance.

Yeping Sun

**Comment by biochem-fan** [comment]
Only the GUI quits. The Class2D itself is still running.

If you don't want GUI to automatically close, start GUI with `--idle 9999999` (in seconds).
