### ISSUE TITLE
An error occured in MPI_Init in autopick

### ISSUE THREAD

**Issue by xmq234** [3dem/relion#425]
Hi, when I run the Autopick ,there is an warning as follows, How to resovle it ?

![img_20181228_200834](https://user-images.githubusercontent.com/30149174/50515419-a8f31b00-0adf-11e9-9f10-bbf8c3e9c791.jpg)

**Comment by Fravadona** [comment]
I see PMIX in the error log so the problem is related to your cluster manager AND MPI implementation. You should ask for help to your cluster admin.
