### ISSUE TITLE
3D auto-refine error segment

### ISSUE THREAD

**Issue by Jocoz** [3dem/relion#429]
Hi,
I am trying to run 3D auto-refine using a 3D class that I generated with relion and I keep getting an error. I am just trying to refine a small 120 A protein with C2 symmetry. Changing the number of MPI from 3 to 5 and GPUs from 0 or 2 or 4 does't work so the problem comes from somewhere else. Here the launch command for the job and the error I get:
```
*** The command is:
`which relion_refine_mpi` --o Refine3D/job079/run --auto_refine --split_random_halves --i Select/job076/particles.star --ref Class3D/job055/run_it025_class003.mrc --ini_high 50 --dont_combine_weights_via_disc --pool 16 --pad 2  --ctf --ctf_corrected_ref --particle_diameter 120 --flatten_solvent --zero_mask --oversampling 1 --healpix_order 2 --auto_local_healpix_order 4 --offset_range 5 --offset_step 2 --sym C2 --low_resol_join_halves 40 --norm --scale  --j 1 --gpu "" 
```
```
ERROR: one of your half sets has no segments. Helical half-sets are always per-filament. Provide at least 2 filaments.
File: /usr/local/apps/RELION/git/2.1.0/src/exp_model.cpp line: 414
ERROR:
ERROR: one of your half sets has no segments. Helical half-sets are always per-filament. Provide at least 2 filaments.
File: /usr/local/apps/RELION/git/2.1.0/src/exp_model.cpp line: 414
ERROR:
ERROR: one of your half sets has no segments. Helical half-sets are always per-filament. Provide at least 2 filaments.
File: /usr/local/apps/RELION/git/2.1.0/src/exp_model.cpp line: 414
[cli_1]: aborting job:
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 1
[cli_2]: aborting job:
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 2
[cli_3]: aborting job:
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 3
```

**Comment by biochem-fan** [comment]
This isn't a filament, is it?

Does your `particles.star` contain the `rlnRandomSubset` column?

**Comment by Jocoz** [comment]
My protein is not a filament and the values of the `rlnRandomSubset` is `1` on every line

**Comment by Jocoz** [comment]
I ran a select job without any of the subset options to generate the particle.star.
I ran the `relion_star_handler --remove_column rlnRandomSubset` and it solved my issue.
Thanks!

**Comment by biochem-fan** [comment]
If your reference model comes from your previous refinement, don't forget to apply strong low pass filtering to avoid overfitting, now that you reset the gold-standard half set assignment.

**Comment by Jocoz** [comment]
It came from a 3D classification but i'll make note of that tip for the next round.
