### ISSUE TITLE
Issue in final steps of compiling

### ISSUE THREAD

**Issue by asgodoy** [3dem/relion#430]
Scanning dependencies of target star_compare
[ 90%] Building CXX object src/apps/CMakeFiles/star_compare.dir/star_compare.cpp.o
[ 91%] Linking CXX executable ../../bin/relion_run_motioncorr_mpi
[ 92%] Linking CXX executable ../../bin/relion_star_combine
[ 92%] Built target run_motioncorr_mpi
Scanning dependencies of target tiltpair_plot
[ 93%] Building CXX object src/apps/CMakeFiles/tiltpair_plot.dir/tiltpair_plot.cpp.o
[ 93%] Built target star_combine
Scanning dependencies of target display
[ 93%] Building CXX object src/apps/CMakeFiles/display.dir/display.cpp.o
[ 94%] Linking CXX executable ../../bin/relion_star_compare
[ 94%] Built target star_compare
Scanning dependencies of target maingui
[ 95%] Building CXX object src/apps/CMakeFiles/maingui.dir/maingui.cpp.o
[ 96%] Linking CXX executable ../../bin/relion_display
../../lib/librelion_gui_lib.so: undefined reference to `Fl_Browser::textsize(int)'
collect2: error: ld returned 1 exit status
src/apps/CMakeFiles/display.dir/build.make:114: recipe for target 'bin/relion_display' failed
make[2]: *** [bin/relion_display] Error 1
CMakeFiles/Makefile2:314: recipe for target 'src/apps/CMakeFiles/display.dir/all' failed
make[1]: *** [src/apps/CMakeFiles/display.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 96%] Linking CXX executable ../../bin/relion_maingui
../../lib/librelion_gui_lib.so: undefined reference to `Fl_Browser::textsize(int)'
collect2: error: ld returned 1 exit status
src/apps/CMakeFiles/maingui.dir/build.make:114: recipe for target 'bin/relion_maingui' failed
make[2]: *** [bin/relion_maingui] Error 1
CMakeFiles/Makefile2:543: recipe for target 'src/apps/CMakeFiles/maingui.dir/all' failed
make[1]: *** [src/apps/CMakeFiles/maingui.dir/all] Error 2
[ 97%] Linking CXX executable ../../bin/relion_tiltpair_plot
[ 97%] Built target tiltpair_plot
[ 97%] Linking CXX executable ../../bin/relion_stack_create
[ 97%] Built target stack_create
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

any guess?

**Comment by biochem-fan** [comment]
Please delete your `build` directory and retry from `cmake` with `-DFORCE_OWN_FLTK=ON`.

**Comment by asgodoy** [comment]
Hi, still the same error.
What is the FLTK i should use for Ubuntu 1604 ? 

Im using this:

BUILD_SHARED_LIBS                ON
 CMAKE_BUILD_TYPE
 CMAKE_CXX_FLAGS_BENCHMARKING     -O3 -DNDEBUG
 CMAKE_CXX_FLAGS_PROFILING        -O3 -DNDEBUG
 CMAKE_C_FLAGS_BENCHMARKING       -O3 -DNDEBUG
 CMAKE_C_FLAGS_PROFILING          -O3 -DNDEBUG
 CMAKE_EXE_LINKER_FLAGS_BENCHMA
 CMAKE_EXE_LINKER_FLAGS_PROFILI
 CMAKE_INSTALL_PREFIX             /usr/local/relion-3.0b
 CUDA                             ON
 CUDA_HOST_COMPILER               /usr/bin/cc
 CUDA_NVCC_FLAGS_BENCHMARKING     -arch=sm_35  -D__INTEL_COMPILER --default-stream per-thread
 CUDA_NVCC_FLAGS_PROFILING        -arch=sm_35  -D__INTEL_COMPILER --default-stream per-thread -lineinfo
 CUDA_SDK_ROOT_DIR                CUDA_SDK_ROOT_DIR-NOTFOUND
 CUDA_TOOLKIT_ROOT_DIR            /usr/local/cuda
 CUDA_USE_STATIC_CUDA_RUNTIME     ON
 CUDA_dl_LIBRARY                  /usr/lib/x86_64-linux-gnu/libdl.so
 CUDA_rt_LIBRARY                  /usr/lib/x86_64-linux-gnu/librt.so
 CachedAlloc                      ON
 CudaForceSTL                     OFF
 CudaTexture                      ON
 CustomAllocMemGuards             OFF
 DoublePrec_CPU                   ON
 DoublePrec_GPU                   OFF
 FFTW_INCLUDES                    /usr/include
 FFTW_LIBRARIES                   /usr/lib/x86_64-linux-gnu/libfftw3.so
 FFTW_PATH                        /usr/include
 FLTK_DIR                         /usr/lib/fltk
 FLTK_MATH_LIBRARY                /usr/lib/x86_64-linux-gnu/libm.so
 FORCE_OWN_FFTW                   OFF
 FORCE_OWN_FLTK                   OFF
 GUI                              ON
 MPI_EXTRA_LIBRARY                /usr/lib/openmpi/lib/libmpi.so
 MPI_LIBRARY                      /usr/lib/openmpi/lib/libmpi_cxx.so
 RELION_FLAGS_BENCHMARKING
 RELION_FLAGS_DEBUG               -O0
 RELION_FLAGS_PROFILING
 RELION_FLAGS_RELEASE
 RELION_NVCC_FLAGS                -arch=sm_35  -D__INTEL_COMPILER --default-stream per-thread
 RELION_NVCC_FLAGS_BENCHMARKING   -arch=sm_35  -D__INTEL_COMPILER --default-stream per-thread
 RELION_NVCC_FLAGS_DEBUG          -arch=sm_35  -D__INTEL_COMPILER --default-stream per-thread
 RELION_NVCC_FLAGS_PROFILING      -arch=sm_35  -D__INTEL_COMPILER --default-stream per-thread -lineinfo
 RELION_NVCC_FLAGS_RELEASE        -arch=sm_35  -D__INTEL_COMPILER --default-stream per-thread --disable-warnings
 RELION_NVCC_FLAGS_RELWITHDEBIN   -arch=sm_35  -D__INTEL_COMPILER --default-stream per-thread
 X11_INCLUDES                     X11_INCLUDES-NOTFOUND

**Comment by biochem-fan** [comment]
Hi,

Did you really specify `-DFORCE_OWN_FLTK=ON` to `cmake`?
Your log says no.

> FORCE_OWN_FLTK OFF

**Comment by asgodoy** [comment]
Sorry,

now I changed and the following error hapens:

-- downloading...
     src='https://drive.google.com/uc?export=download&id=0B942d76zVnSeazZWcExRaXIyVDg'
     dst='/home/davinci/Cryoem/relion3.0/relion/external/fltk/fltk-1.3.3-source.tar.gz'
     timeout='none'
CMake Error at /home/davinci/Cryoem/relion3.0/relion/build/OWN_FLTK-prefix/src/OWN_FLTK-stamp/download-OWN_FLTK.cmake:27 (message):
  error: downloading
  'https://drive.google.com/uc?export=download&id=0B942d76zVnSeazZWcExRaXIyVDg'
  failed

    status_code: 1
    status_string: "Unsupported protocol"
    log: Protocol "https" not supported or disabled in libcurl

  Closing connection -1





CMakeFiles/OWN_FLTK.dir/build.make:89: recipe for target 'OWN_FLTK-prefix/src/OWN_FLTK-stamp/OWN_FLTK-download' failed
make[2]: *** [OWN_FLTK-prefix/src/OWN_FLTK-stamp/OWN_FLTK-download] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/OWN_FLTK.dir/all' failed
make[1]: *** [CMakeFiles/OWN_FLTK.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[  7%] Built target copy_scripts
[  7%] Built target relion_gpu_util
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by biochem-fan** [comment]
Probably your `curl` is too old or compiled wrongly.

Do you have administrator privilege to your machine? If so, do `sudo apt-get install curl` and make sure `PATH` points to that curl. Otherwise, compile `curl` yourself with OpenSSL support under your home directory and set `PATH` to it.
