### ISSUE TITLE
Issue with focused refine

### ISSUE THREAD

**Issue by whiteqiu82** [3dem/relion#432]
Here is what I did:
Take data.star file from the end of the refinement with C3, run relion_particle_symmetry_expand, and then run a 3D auto-refine in C1 with local angular searches using the symmetry expanded set of particles, with a mask around the asymmetric region.

Here is the error:
[usnee1-lph001-g005:35956] 2 more processes have sent help message help-mpi-btl-base.txt / btl:no-nics
[usnee1-lph001-g005:35956] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages
 WARNING: FSC curve between unmasked maps never drops below 0.8. Using unmasked FSC as FSC_true... 
 WARNING: This message should go away during the later stages of refinement!

 fn_img= 
 ipart= 0 adaptive_fraction= 0.999
 min_diff2= 3.40282e+38

 fn_img= 
 ipart= 0 adaptive_fraction= 0.999
 min_diff2= 3.40282e+38

 fn_img= 
 ipart= 0 adaptive_fraction= 0.999
 min_diff2= 3.40282e+38

 fn_img= 
 ipart= 0 adaptive_fraction= 0.999
 min_diff2= 3.40282e+38

 fn_img= 
 ipart= 0 adaptive_fraction= 0.999
 min_diff2= 3.40282e+38

 fn_img= 
 ipart= 0 adaptive_fraction= 0.999
 min_diff2= 3.40282e+38

 fn_img= 
 ipart= 0 adaptive_fraction= 0.999
 min_diff2= 3.40282e+38

 fn_img= 
 ipart= 0 adaptive_fraction= 0.999
 min_diff2= 3.40282e+38

 fn_img= 
 ipart= 0 adaptive_fraction= 0.999
 min_diff2= 3.40282e+38

 fn_img= 
 ipart= 0 adaptive_fraction= 0.999
 min_diff2= 3.40282e+38

 fn_img= 
 ipart= 0 adaptive_fraction= 0.999
 min_diff2= 3.40282e+38

 fn_img= 
 ipart= 0 adaptive_fraction= 0.999
 min_diff2= 3.40282e+38

 fn_img= 
 ipart= 0 adaptive_fraction= 0.999
 min_diff2= 3.40282e+38

 fn_img= 
 ipart= 0 adaptive_fraction= 0.999
 min_diff2= 3.40282e+38

 fn_img= 
 ipart= 0 adaptive_fraction= 0.999
 min_diff2= 3.40282e+38

 fn_img= 
 ipart= 0 adaptive_fraction= 0.999
 min_diff2= 3.40282e+38
Dumped data: error_dump_pdf_orientation, error_dump_pdf_orientation and error_dump_unsorted.
in: /programs/x86_64-linux/relion/3.0_beta_cu8.0/src/acc/acc_ml_optimiser_impl.h, line 1793
in: /programs/x86_64-linux/relion/3.0_beta_cu8.0/src/acc/acc_ml_optimiser_impl.h, line 1793
Dumped data: error_dump_pdf_orientation, error_dump_pdf_orientation and error_dump_unsorted.
in: /programs/x86_64-linux/relion/3.0_beta_cu8.0/src/acc/acc_ml_optimiser_impl.h, line 1793
in: /programs/x86_64-linux/relion/3.0_beta_cu8.0/src/acc/acc_ml_optimiser_impl.h, line 1793
Dumped data: error_dump_pdf_orientation, error_dump_pdf_orientation and error_dump_unsorted.
in: /programs/x86_64-linux/relion/3.0_beta_cu8.0/src/acc/acc_ml_optimiser_impl.h, line 1793
in: /programs/x86_64-linux/relion/3.0_beta_cu8.0/src/acc/acc_ml_optimiser_impl.h, line 1793
Dumped data: error_dump_pdf_orientation, error_dump_pdf_orientation and error_dump_unsorted.
in: /programs/x86_64-linux/relion/3.0_beta_cu8.0/src/acc/acc_ml_optimiser_impl.h, line 1793
in: /programs/x86_64-linux/relion/3.0_beta_cu8.0/src/acc/acc_ml_optimiser_impl.h, line 1793
Dumped data: error_dump_pdf_orientation, error_dump_pdf_orientation and error_dump_unsorted.
in: /programs/x86_64-linux/relion/3.0_beta_cu8.0/src/acc/acc_ml_optimiser_impl.h, line 1793
in: /programs/x86_64-linux/relion/3.0_beta_cu8.0/src/acc/acc_ml_optimiser_impl.h, line 1793
Dumped data: error_dump_pdf_orientation, error_dump_pdf_orientation and error_dump_unsorted.
in: /programs/x86_64-linux/relion/3.0_beta_cu8.0/src/acc/acc_ml_optimiser_impl.h, line 1793
in: /programs/x86_64-linux/relion/3.0_beta_cu8.0/src/acc/acc_ml_optimiser_impl.h, line 1793
Dumped data: error_dump_pdf_orientation, error_dump_pdf_orientation and error_dump_unsorted.
in: /programs/x86_64-linux/relion/3.0_beta_cu8.0/src/acc/acc_ml_optimiser_impl.h, line 1793
in: /programs/x86_64-linux/relion/3.0_beta_cu8.0/src/acc/acc_ml_optimiser_impl.h, line 1793
Dumped data: error_dump_pdf_orientation, error_dump_pdf_orientation and error_dump_unsorted.
in: /programs/x86_64-linux/relion/3.0_beta_cu8.0/src/acc/acc_ml_optimiser_impl.h, line 1793
in: /programs/x86_64-linux/relion/3.0_beta_cu8.0/src/acc/acc_ml_optimiser_impl.h, line 1793
slave 2 encountered error: === Backtrace  ===
/site/ne/app/x86_64/relion/v3.0/bin/relion_refine_mpi(_ZN11RelionErrorC1ERKSsS1_l+0x41) [0x449271]
/site/ne/app/x86_64/relion/v3.0/bin/relion_refine_mpi(_Z36globalThreadExpectationSomeParticlesR14ThreadArgument+0xed) [0x5f437d]
/site/ne/app/x86_64/relion/v3.0/bin/relion_refine_mpi(_Z11_threadMainPv+0x3e) [0x49539e]
/lib64/libpthread.so.0(+0x7dc5) [0x2aaab8babdc5]
/lib64/libc.so.6(clone+0x6d) [0x2aaab9b0673d]
==================
ERROR: 
No orientation was found as better than any other.

A particle image was compared to the reference and resulted in all-zero
weights (for all orientations). This should not happen, unless your data
has very special characteristics. This has historically happened for some 
lower-precision calculations, but multiple fallbacks have since been 
implemented. Please report this error to the relion developers at 

	         github.com/3dem/relion/issues  
 
Dumped data: error_dump_pdf_orientation, error_dump_pdf_orientation and error_dump_unsorted.
in: /programs/x86_64-linux/relion/3.0_beta_cu8.0/src/acc/acc_ml_optimiser_impl.h, line 1793
in: /programs/x86_64-linux/relion/3.0_beta_cu8.0/src/acc/acc_ml_optimiser_impl.h, line 1793

**Comment by biochem-fan** [comment]
https://www3.mrc-lmb.cam.ac.uk/relion/index.php/FAQs#Refinement_or_Classification_crash_saying_.22No_orientation_was_found.22
