### ISSUE TITLE
Relion make error during re-compiling

### ISSUE THREAD

**Issue by mingyue80** [3dem/relion#434]
While trying to re-compile to the latest version of Relion, I did the following:

- removed build/ in relion/ and re-made build/
- successful cmake, no errors
- upon running make, encountered the following error. Any help would be much appreciated!

Scanning dependencies of target copy_scripts
Scanning dependencies of target relion_lib
[  0%] Built target copy_scripts
[  1%] [  1%] [  2%] [  2%] [  3%] [  3%] [  3%] [  4%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/assembly.cpp.o
Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/error.cpp.o
Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/ctffind_runner.cpp.o
Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/ctf.cpp.o
Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/ctffind_runner_mpi.cpp.o
Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/exp_model.cpp.o
Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/ml_model.cpp.o
Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/image.cpp.o
[  5%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/euler.cpp.o
[  5%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/mpi.cpp.o
[  6%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/fftw.cpp.o
[  6%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/filename.cpp.o
[  7%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/funcs.cpp.o
[  7%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/helix.cpp.o
[  8%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/mask.cpp.o
[  8%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/healpix_sampling.cpp.o
[  9%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/helix_inimodel2d.cpp.o
[  9%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/local_symmetry.cpp.o
[ 10%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/local_symmetry_mpi.cpp.o
[ 10%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/matrix1d.cpp.o
[ 11%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/matrix2d.cpp.o
[ 11%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/memory.cpp.o
[ 12%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/metadata_container.cpp.o
[ 12%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/metadata_label.cpp.o
[ 13%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/metadata_table.cpp.o
[ 13%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/ml_optimiser.cpp.o
[ 14%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/ml_optimiser_mpi.cpp.o
[ 14%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/motioncorr_runner.cpp.o
[ 15%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/motioncorr_runner_mpi.cpp.o
[ 15%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/multidim_array.cpp.o
[ 16%] [ 16%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/numerical_recipes.cpp.o
Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/parallel.cpp.o
[ 17%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/particle_polisher.cpp.o
[ 17%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/particle_polisher_mpi.cpp.o
[ 18%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/particle_sorter.cpp.o
[ 18%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/particle_sorter_mpi.cpp.o
[ 19%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/pipeline_jobs.cpp.o
[ 19%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/pipeliner.cpp.o
[ 20%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/postprocessing.cpp.o
[ 20%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/preprocessing.cpp.o
[ 21%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/preprocessing_mpi.cpp.o
[ 21%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/projector.cpp.o
[ 22%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/strings.cpp.o
[ 23%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/symmetries.cpp.o
[ 23%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/tabfuncs.cpp.o
[ 24%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/time.cpp.o
[ 24%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/transformations.cpp.o
[ 25%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/pipeliner-orig.cpp.o
[ 25%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/CPlot2D.cpp.o
[ 26%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/args.cpp.o
/usr/local/relion/src/pipeliner-orig.cpp:566:6: error: prototype for ‘void PipeLine::runScheduledJobs(FileName, FileName, int, long int)’ does not match any in class ‘PipeLine’
 void PipeLine::runScheduledJobs(FileName fn_sched, FileName fn_jobids, int nr_repeat, long int minutes_wait)
      ^
In file included from /usr/local/relion/src/pipeliner-orig.cpp:21:0:
/usr/local/relion/src/pipeliner.h:161:7: error: candidate is: void PipeLine::runScheduledJobs(FileName, FileName, int, long int, long int, long int)
  void runScheduledJobs(FileName fn_sched, FileName fn_jobids, int nr_repeat, long int minutes_wait, long int minutes_wait_before = 0, long int seconds_wait_after = 10);
       ^
/usr/local/relion/src/pipeliner-orig.cpp:1562:6: error: prototype for ‘void PipeLine::read(bool)’ does not match any in class ‘PipeLine’
 void PipeLine::read(bool do_lock)
      ^
In file included from /usr/local/relion/src/pipeliner-orig.cpp:21:0:
/usr/local/relion/src/pipeliner.h:204:7: error: candidate is: void PipeLine::read(bool, std::string)
  void read(bool do_lock = false, std::string lock_message = "Undefined lock message");
       ^
[ 26%] make[2]: *** [src/apps/CMakeFiles/relion_lib.dir/__/pipeliner-orig.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/autopicker.cpp.o
make[1]: *** [src/apps/CMakeFiles/relion_lib.dir/all] Error 2
make: *** [all] Error 2

**Comment by biochem-fan** [comment]
Where did `pipeliner-orig.cpp` come from? It is not part of our repository.

**Comment by mingyue80** [comment]
Great question, I don't know. Would it be best to just remove everything entirely, do a git clone, and re-compile?

**Comment by biochem-fan** [comment]
Yes. Just remove everything and start from scratch.

**Comment by mingyue80** [comment]
OK, so I did that and no errors from CMake nor installation steps. But invoking relion I got the following error:
relion: error while loading shared libraries: librelion_lib.so: cannot open shared object file: No such file or directory

Can't seem to locate this file anywhere. Suggestions?

**Comment by mingyue80** [comment]
nevermind issue solved. Thanks!
