### ISSUE TITLE
Take CTF parameters from micrographs in Extract job [feature request]

### ISSUE THREAD

**Issue by olibclarke** [3dem/relion#439]
Hi,

Congrats on the release of v3.0, it is an amazing piece of work!

Would it be possible to add an option in the Extract job to use CTF parameters from micrographs, rather than particles, when re-extracting refined particles? 

I believe right now Relion defaults to using the values from the particles when re-extracting, which is the sensible thing to do under most circumstances, but it would be useful to have the option to use the micrograph values when one is comparing the use of different packages or settings for CTF estimation.

Cheers
Oli

**Comment by biochem-fan** [comment]
It is not in the GUI but `--use_ctf_in_mic` do what you want.

> one is comparing the use of different packages or settings for CTF estimation

As long as you run CtfRefine, it does not really matter.

**Comment by olibclarke** [comment]
Thanks!

**Comment by olibclarke** [comment]
Re it not mattering, I imagine that is true in most cases, but I sometimes see quite different astigmatism estimations between Gctf and CTFFIND (which are not typically refined by CTFrefine), so I want to test. Also both programs will sometimes fail for particular micrographs, and in that case Ctfrefine won't help (because particles are discarded before they make it to CTFrefine).
