### ISSUE TITLE
relion_display: symbol lookup error: relion_display: undefined symbol: fftw_plan_dft_r2c

### ISSUE THREAD

**Issue by apachipa** [3dem/relion#440]
Hi All, 

We are trying relion3 beta. 

Ubuntu 16.04
P40's NVIDIA GPU cards
CUDA 8.0
Relion 3 build and installation was successful with CUDA. No errors.

When user/s try to do Manuel Picking and then Click on Pick button on .mrc it is not displaying the Image. CTF button next to it works fine. 

Error: "relion_display: symbol lookup error: relion_display: undefined symbol: fftw_plan_dft_r2c"

Any thoughts or suggestions on how to fix this error. 

Cheers,
Ash

**Comment by biochem-fan** [comment]
Your FFTW is not in `LD_LIBRARY_PATH`. Try using `-DFORCE_OWN_FFTW=ON` in `cmake`.

**Comment by apachipa** [comment]
Awesome! That fixed the issue. Thank you.
