### ISSUE TITLE
MKLFFT=ON compilation error

### ISSUE THREAD

**Issue by DBrusson** [3dem/relion#441]
Dear all,
I'm trying to compile Relion 3.0 with Intel 18 compilers and MKL on a Scientific Linux 7 distribution. Here is the cmake command :

`cmake -DCMAKE_INSTALL_PREFIX=/usr/local/relion/CPUVERSION -DMKLFFT=ON -DCMAKE_BUILD_TYPE=Release ..`

The configure doesn't complain but there are no mentions of MKL or FFT anywhere, I don't know if it's normal (cmake.log attached to this message)

Then I have this error, shortly after the beginning of the compilation :
```
$ make
Scanning dependencies of target copy_scripts
[  0%] Built target copy_scripts
Scanning dependencies of target relion_lib
[  0%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/CPlot2D.cpp.o
[  1%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/args.cpp.o
[  1%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/assembly.cpp.o
[  1%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/autopicker.cpp.o
In file included from /usr/local/relion/relion-3.0/src/image.h(66),
                 from /usr/local/relion/relion-3.0/src/autopicker.h(10),
                 from /usr/local/relion/relion-3.0/src/autopicker.cpp(20):
/usr/local/relion/relion-3.0/src/fftw.h(49): catastrophic error: cannot open source file "fftw3.h"
  #include <fftw3.h>
                    ^

compilation aborted for /usr/local/relion/relion-3.0/src/autopicker.cpp (code 4)
make[2]: *** [src/apps/CMakeFiles/relion_lib.dir/__/autopicker.cpp.o] Error 4
make[1]: *** [src/apps/CMakeFiles/relion_lib.dir/all] Error 2
make: *** [all] Error 2

```
compilervars.sh and mklvars.sh are already sourced and I have already compiled other codes with MKL without any problem. And Relion compiles well without MKL.

Thanks in advance !

[cmake.log](https://github.com/3dem/relion/files/2876151/cmake.log)

**Comment by Fravadona** [comment]
You can add the MKL's FFTW include dir to your CPATH:
# After sourcing mklvars.sh
export CPATH="${CPATH:+$CPATH:}${MKLROOT}/include/fftw"

**Comment by DBrusson** [comment]
"fun" story : I thought  MKL's FFTW was in my CPATH, but I made a small typo in my .bashrc :
export CPATH=$MKLROOT/include/**ffttw** 
So now that it is fixed, everything works fine. Thank you very much !
