### ISSUE TITLE
OpenMPI

### ISSUE THREAD

**Issue by apachipa** [3dem/relion#442]
Hi All, 

We are testing relion 3 beta. 
We are using OpenMPI version 4.0. It seems when we run autopick with multiple MPI's/CPU's, it comes with below error. However when we run with single MPI/CPU, it works fine.

CUDA: 8
GPU's: P40
------------------------------
 ORTE_ERROR_LOG: Not found in file runtime/orte_init.c at line 129
*** An error occurred in MPI_Init
*** on a NULL communicator
*** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
***    and potentially your MPI job)
[reliontest:9208] Local abort before MPI_INIT completed successfully; not able to aggregate error messages, and not able to guarantee that all other processes were killed!
[reliontest:09209] [[INVALID],INVALID] ORTE_ERROR_LOG: Not found in file runtime/orte_init.c at line 129
*** An error occurred in MPI_Init
*** on a NULL communicator
*** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
***    and potentially your MPI job)
[reliontest:9209] Local abort before MPI_INIT completed successfully; not able to aggregate error messages, and not able to guarantee that all other processes were killed!
-------------------------------------------
Any help fixing this issue would be much appreciated. 

Cheers,
Ash

**Comment by biochem-fan** [comment]
Are you sure you are using the same OpenMPI for compilation (`mpic` etc) and execution (`mpirun`)?

**Comment by apachipa** [comment]
Below are the steps i used to compile it:

Extracted: Openmpi 4.0 (Current):
cd into openmpi 4.0 folder

  - ./configure --prefix="/opt/openmpi"
  - make all
  - make install

Then build relion3 beta using below commands:

  - cmake -DFORCE_OWN_FFTW=ON ..
  - make -j4 all
  - make install

Then set Environmental path to relion and openmpi under /etc/profile.d/as two separate shell scripts:

relion3.sh : This is to load relion3 to users profile.

- export PATH=$PATH:/usr/local/bin

openmpi4.sh, This is to set Just the openmpi environmental path to user profiles when they login, as per relion wiki page

#!/bin/bash

if ("" == "`echo $path | grep /opt/openmpi/bin`") then
        set path=(/opt/openmpi/bin $path)
endif
if ("1" == "$?LD_LIBRARY_PATH") then
        if ("$LD_LIBRARY_PATH" !~ */opt/openmpi/lib*) then
                export LD_LIBRARY_PATH /opt/openmpi/lib:$LD_LIBRARY_PATH
        endif
else
        export LD_LIBRARY_PATH /opt/openmpi/lib
endif

I might be doing something wrong here. 

Is there anywhere to validate we are using openmpi for compilation and execution ?

Cheers,
Ash

**Comment by biochem-fan** [comment]
Look at logs from `cmake`. It prints out which MPIC it is using.

**Comment by apachipa** [comment]
relion cmake is showing openmpi is using is under /usr/lib/openmpi.
Don i need to set this to load into my bashprofile to run autopick,  2 CPU or mpi jobs ?
Apologies, i am new to this and thank you for the help in advance. 

Cheers,
Ash

**Comment by biochem-fan** [comment]
> /usr/lib/openmpi

This is the problem. If you want to use OpenMPI you installed in `/opt/openmpi`for RELION, you have to use it also for compilation. If you used the one in `/usr/lib/openmpi` for compilation, you have to use `mpirun` there for execution. No mixing.

**Comment by apachipa** [comment]
If i would like to use /opt/openmpi, is there a switch i can use in relion3 to set openmpi path while i cmake ?

**Comment by biochem-fan** [comment]
Set PATH to it before running `cmake`.  Also note that `cmake` caches previous results. You should delete your `build` directory and run `cmake` from scratch.

**Comment by apachipa** [comment]
Thank you. I will give it a try and let you know the result. 

Cheers,
Ash

**Comment by apachipa** [comment]
Apologies for the delayed response. 

Problem: I have anaconda3 installed under /usr/local/anaconda3/ which had mpirun and mpicc in it. I set anaconda to be loaded into users profiles to use conda tools. 

I uninstalled or removed anaconda3 and re-building relion3 from scratch including dependencies etc.. Will post the result tomorrow. 

Cheers,
Ash

**Comment by apachipa** [comment]
i can confirm setting path for anaconda3 was the problem. 
Removed anaconda3 path. 

Re-make and installed openmpi. 
Set path to bin and lib for openmpi. 
In relion3 delete build folder, recreate build folder and re-build/recompile relion3. 
Autopicking with Multi-MPI started working. 

Thank you very much for all the help. 

Cheers,
Ash
