### ISSUE TITLE
Relion 2.1: specifying CUDA

### ISSUE THREAD

**Issue by pconesa** [3dem/relion#443]
Hi! Is there any chance specify which CUDA to be used when compiling relion 2.1?

My default /usr/local/cuda points to CUDA 8
But I've got 7.5 too at /usr/local/cuda-7.5.

Is there a way to specify the CUDA paths?

**Comment by delarosatrevin** [comment]
Hi Pablo,

Maybe you could try something like this:
https://stackoverflow.com/questions/19980412/how-to-let-cmake-find-cuda

Hope this helps,
Best,
Jose Miguel

**Comment by pconesa** [comment]
you are everywhere!! @delarosatrevin .heheheh.

That worked. actually, just in case some else get problems instllaling relion in ubuntu 18 with CUDA 8...this worked for me:

# Change to an earlier version of GCC and GXX (<= 5)
export CXX=/usr/bin/g++-5
export CC=/usr/bin/gcc-5

and in the cmake added this: -D CMAKE_C_COMPILER=gcc-5 -D CMAKE_CXX_COMPILER=g++-5

the error was that CUDA needed lower compilers versions and were using version 7 or 8.

@delarosatrevin , It is going to be true that you are like Sauron, the all-seeing eye! (hey! with all my respect and admiration!). hehehe

All the best, Pablo.
