### ISSUE TITLE
Setting RELION_QUEUE_USE=Yes forces import, manual pick and subset selection to queue

### ISSUE THREAD

**Issue by andschenk** [3dem/relion#445]
If RELION_QUEUE_USE is set to "Yes" in the environment all jobs are submitted to queue by default, even the ones (manualpick,import,subset selection) where the queue option is disabled. As the queuing is disabled in the GUI the user then has no way of running these jobs interactively in that case.

The attached patch sets submit to queue to no for all job types where queuing is disabled. 
[queue.patch.gz](https://github.com/3dem/relion/files/2900518/queue.patch.gz)

**Comment by biochem-fan** [comment]
Fixed in 87d87fd. Thank you very much for your report and patch.
