### ISSUE TITLE
crashing when selecting path for import from a nested softlink

### ISSUE THREAD

**Issue by xeniorn** [3dem/relion#448]
Hi,

I'm getting an odd crash while importing a 3D model (though it doesn't depend on which import type I select). After clicking "browse", selecting the item, and pressing ok, the gui crashes with

```
terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::substr: __pos (which is 18446744073709551615) > this->size() (which is 53)
```

the file is located in a soft-linked directory reference_models in relion project folder that points to ../../../reference_models/

if I then create a soft link to the file itself reference_models/[filename].mrc, the import works.

if I create a soft link directly to the actual non-soft link source file, it also works.

The original file in "../../../reference_models/" is also a soft-link, which points to ../project/folder/relion/Refine3D/jobAlias/run_class001.mrc"

I guess it has something to do with the file being imported being a soft link to a soft link, both of which contain ".." - since adding more soft link layer fixes the issue.

Best,

J

**Comment by biochem-fan** [comment]
There are many tricky cases about soft links in RELION. Our recommendation is to use an absolute path in a link.

**Comment by biochem-fan** [comment]
https://www3.mrc-lmb.cam.ac.uk/relion/index.php/FAQs#What_is_the_right_way_to_import_files_outside_the_project_directory.3F
