### ISSUE TITLE
Class3d stuck

### ISSUE THREAD

**Issue by wangnan161** [3dem/relion#450]
Hello,
I am doing 3d Classification without alignment. The program stuck after Estimating initial noise spectra. No error or waring information is reported and all my processes are running. 
Pixel size is 3.45 and box is 400 pix

Here is my command.
mpirun -n 4 relion_refine_mpi --o mk_process/ball_class3d/run1 --i mk_process/ori-i3ex.star --ref mk_process/temp3.45.mrc --firstiter_cc --ini_high 10 --dont_combine_weights_via_disc --pool 3 --pad 2  --ctf --ctf_corrected_ref --iter 1 --tau2_fudge 4 --particle_diameter 1360 --K 1 --flatten_solvent --solvent_mask mk_process/mask/vertex_ball_mask.mrc --skip_align  --sym C1 --norm --scale  --j 20 > mk_process/ball_class3d/run.log

Here is the log.
RELION version: 3.0-beta-2 
Precision: BASE=double, CUDA-ACC=single 

 === RELION MPI setup ===
 + Number of MPI processes             = 4
 + Number of threads per MPI process  = 20
 + Total number of threads therefore  = 80
 + Master  (0) runs on host            = amax
 + Slave     1 runs on host            = amax
 + Slave     2 runs on host            = amax
 =================
 + Slave     3 runs on host            = amax
 Running CPU instructions in double precision. 
 Estimating initial noise spectra 
47.22/47.22 min ............................................................~~(,_,">

**Comment by Fravadona** [comment]
Does that computer have at least 61 cores ? What's the size of the stack ?

**Comment by wangnan161** [comment]
My computer work with 2x E5-2640V4 10 COREs 20 THREADS
The size of the stack is about 31Gib

> Does that computer have at least 61 cores ? What's the size of the stack ?

**Comment by biochem-fan** [comment]
Aren't you running out of (CPU) memory?

First try it on a small subset of your dataset with fewer MPI and threads.

**Comment by Fravadona** [comment]
OK, so you have 20 cores on that computer but you're asking for 61 cores in your "Running" parameters ...
I would recommend to try:
- 3 MPI processes, 8 (or 9) threads each, which will use 17 (or 19) cores
- 5 MPI processes, 4 threads each (if you have enough RAM), which will use 17 cores

**Comment by wangnan161** [comment]
> OK, so you have 20 cores on that computer but you're asking for 61 cores in your "Running" parameters ...
> I would recommend to try:
> 
>     * 3 MPI processes, 8 (or 9) threads each, which will use 17 (or 19) cores
> 
>     * 5 MPI processes, 4 threads each (if you have enough RAM), which will use 17 cores

I changed my command to this
mpirun -n 3 relion_refine_mpi --o Class3D/job017/run --i Extract/job014/particles_i3_ex.star --ref mk_process/temp4.3125.mrc --firstiter_cc --ini_high 10 --dont_combine_weights_via_disc --pool 3 --pad 2  --ctf --ctf_corrected_ref --iter 1 --tau2_fudge 4 --particle_diameter 1360 --K 1 --flatten_solvent --zero_mask --solvent_mask mk_process/mask/temp4.3125_mask.mrc --skip_align  --sym C1 --norm --scale  --j 9 

And the job stop again.
RELION version: 3.0-beta-2 
Precision: BASE=double, CUDA-ACC=single 

 === RELION MPI setup ===
 + Number of MPI processes             = 3
 + Number of threads per MPI process  = 9
 + Total number of threads therefore  = 27
 + Master  (0) runs on host            = amax
 + Slave     2 runs on host            = amax
 =================
 + Slave     1 runs on host            = amax
 Running CPU instructions in double precision. 
 Estimating initial noise spectra 
1.43/1.43 hrs ............................................................~~(,_,">

**Comment by wangnan161** [comment]
> Aren't you running out of (CPU) memory?
> 
> First try it on a small subset of your dataset with fewer MPI and threads. In addition, you should upgrade to the stable version of RELION 3.0.
I check the status of my memory. My computer has a RAM of 256Gib and the memory the job take is 50Gib.
The number of particle is reduced to 10,000. The job stopped again.

COMMAND:
mpirun -n 10 `which relion_refine_mpi` --o Class3D/job017/run --i test.star --ref mk_process/temp4.3125.mrc --firstiter_cc --ini_high 10 --dont_combine_weights_via_disc --pool 3 --pad 2  --ctf --ctf_corrected_ref --iter 1 --tau2_fudge 4 --particle_diameter 1360 --K 1 --flatten_solvent --zero_mask --solvent_mask mk_process/mask/temp4.3125_mask.mrc --skip_align  --sym C1 --norm --scale  --j 4

OUTPUT:
RELION version: 3.0-beta-2 
Precision: BASE=double, CUDA-ACC=single 

 === RELION MPI setup ===
 + Number of MPI processes             = 10
 + Number of threads per MPI process  = 4
 + Total number of threads therefore  = 40
 + Master  (0) runs on host            = amax
 + Slave     1 runs on host            = amax
 + Slave     2 runs on host            = amax
 + Slave     3 runs on host            = amax
 + Slave     4 runs on host            = amax
 + Slave     5 runs on host            = amax
 + Slave     6 runs on host            = amax
 + Slave     7 runs on host            = amax
 + Slave     8 runs on host            = amax
 + Slave     9 runs on host            = amax
 =================
 Running CPU instructions in double precision. 
 Estimating initial noise spectra 
   5/   5 sec ............................................................~~(,_,">

**Comment by bforsbe** [comment]
I have seen a similar behaviour when trying to get openmpi-3 to work. Could you try not using MPI at all? Just call relion_refine instead of relion_refine_mpi, and use one or a few threads to exclude further complications.

**Comment by wangnan161** [comment]
> I have seen a similar behaviour when trying to get openmpi-3 to work. Could you try not using MPI at all? Just call relion_refine instead of relion_refine_mpi, and use one or a few threads to exclude further complications.
I am very excited to tell relion_refine works well and fast. 
Thank you very much.

Here is my openmpi version
$ mpirun -V
mpirun (Open MPI) 1.10.2
Report bugs to http://www.open-mpi.org/community/help/

Maybe we need the higher version of OPENMPI
Here is the command.
relion_refine --o Class3D/job017/run --i test.star --ref mk_process/temp4.3125.mrc --firstiter_cc --ini_high 10 --dont_combine_weights_via_disc --pool 3 --pad 2  --ctf --ctf_corrected_ref --iter 1 --tau2_fudge 4 --particle_diameter 1360 --K 1 --flatten_solvent --zero_mask --solvent_mask mk_process/mask/temp4.3125_mask.mrc --skip_align  --sym C1 --norm --scale  --j 10
 Running CPU instructions in double precision. 
 Estimating initial noise spectra 
  40/  40 sec ............................................................~~(,_,">
 CurrentResolution= 10 Angstroms, which requires orientationSampling of at least 0.841121 degrees for a particle of diameter 1360 Angstroms
 Oversampling= 0 NrHiddenVariableSamplingPoints= 1
 OrientationalSampling= 15 NrOrientations= 1

Thanks!

**Comment by bforsbe** [comment]
openmpi 2.0.2  is my go-to version, for future reference.
