### ISSUE TITLE
make error with own_fltk: error downloading 'https://drive.google.com/ with curl

### ISSUE THREAD

**Issue by clemensgrimm** [3dem/relion#451]
Building with-DFORCE_OWN_FLTK=ON gives me:

  error: downloading 'https://drive.google.com/uc?export=download&id=0B942d76zVnSeazZWcExRaXIyVDg' failed
         status_code: 1
         status_string: "Unsupported protocol"
         log:
         --- LOG BEGIN ---
         Protocol "https" not supported or disabled in libcurl

  Closing connection -1

However $ curl -V yields:
curl 7.58.0 (x86_64-pc-linux-gnu) libcurl/7.58.0 OpenSSL/1.1.0g zlib/1.2.11 libidn2/2.0.4 libpsl/0.19.1 (+libidn2/2.0.4) nghttp2/1.30.0 librtmp/2.3
Release-Date: 2018-01-24
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL 

with https in the list!

**Comment by biochem-fan** [comment]
Does `curl -O https://drive.google.com/uc?export=download&id=0B942d76zVnSeazZWcExRaXIyVDg` work? If it doesn't, you can download the file by an Web browser to `external/fltk/fltk-1.3.3-source.tar.gz`. Then `make` will use it.

If downloading from an Web browser also fails, just wait for a while. Sometimes Google Drive becomes inaccessible when too many people request the same file.

**Comment by clemensgrimm** [comment]
Hi biochem-fan,

both of the suggested options work. I just couldn't find out where to place the manually downloaded sources. Will try this, thanks.

BTW, this issue seems to be related to #430. I am using Ubuntu. Curl 7.58.0 is up to date for my installation (7.63 seems to be latest stable version currently).

**Comment by clemensgrimm** [comment]
Could successfully build with the manual FLTK download. Suspect that there is a (Ubuntu-related?) issue with curl and the cmake script.
