### ISSUE TITLE
Relion 3d refine run-time not scaling with number of threads

### ISSUE THREAD

**Issue by yazzmanian** [3dem/relion#454]
Hi,

I am running a Relion 3D refine job on a cluster but the job run-time does not appear to scale with number of processors when compared to a similar job run on my own linux workstation. The two jobs are similar except the job on the cluster is running on 3.0 beta with ~80000 ptcl images, whereas the one on my workstation is running on the latest stable version of relion and with 68000 ptcl images. Both jobs are still in progress, but based on the times for the expectation step of corresponding early iterations (1 through 5), the job on my workstation is running faster, presumably because of less particles. For instance, iteration 3 expectation step  took 9.4 hours on my workstation while it took 10.5 hours on the cluster. More details on the systems used and the jobs run are below.

I would appreciate some feedback on whether this is expected. Will I see a difference only at later iterations when memory becomes an issue?

Thanks, 

Yazan

**Cluster information**

3.0_beta_gpu installed on
Sany Bridge Dual sockets Intel Xeon CPU E5-2670 0 @ 2.60GHz
32 threads per node
120GB RAM
Operating system Centos 6.4

_The job (focused refinement) was executed using a script containing the following command:_

mpirun -mca btl tcp,sm,self -np 8 `which relion_refine_mpi` --o outputmap.mrc --auto_refine --split_random_halves --i particles.star --particle_diameter 340 --angpix 1.06 --ref inputmap.mrc --firstiter_cc --ini_high 15 --ctf --flatten_solvent --solvent_mask mask.mrc --zero_mask --oversampling 1 --healpix_order 4 --auto_local_healpix_order 4 --offset_range 5 --offset_step 2 --sym C1 --low_resol_join_halves 40 --norm --scale --j 4

_I have also tried the same but with --pool 64 --preread_images --dont_combine_weights_via_disc --no_parallel_disc_io added, which improved speed slightly_

**Personal Workstation**

Relion 3.0 stable
Intel Core i7-7700 Kaby Lake quad-core 3.6 GHz
16GB DDR4 RAM
Ubuntu 16.04

_Command used:_

mpirun -n 3 relion_refine_mpi --o outputmap.mrc --auto_refine --split_random_halves --i particles.star --particle_diameter 340 --angpix 1.06 --ref inputmap.mrc --firstiter_cc --ini_high 15 --ctf --flatten_solvent --solvent_mask mask.mrc --zero_mask --oversampling 1 --healpix_order 4 --auto_local_healpix_order 4 --offset_range 5 --offset_step 2 --sym C1 --low_resol_join_halves 40 --norm --scale

**Comment by biochem-fan** [comment]
This depends on many things, e.g., NUMA architecture of the machine, memory speed, particle box size, etc. You have to find the best combination of the MPI and threads.
