### ISSUE TITLE
Scratch problems with symmetry expanded particle sets

### ISSUE THREAD

**Issue by olibclarke** [3dem/relion#455]
Hi,

This has only occurred recently (since the release of 3.0-stable), and only so far when using symmetry-expanded particle sets (though I haven't tested systematically).

When I am running a refinement job, for which the particles have been copied to scratch (/scratch/relion_volatile/particles.mrcs), and then I start another refinement or classification job from the same dataset (also copying particles to scratch), it seems to try to clobber the original particles.mrcs on scratch and both jobs die as a result with the attached error. 

If I specify a unique path in scratch for the second job (e.g. /scratch/relion_volatile2), then both jobs trundle along happily.

Cheers,
Oli.

<img width="812" alt="image" src="https://user-images.githubusercontent.com/19766818/54316470-3dd1c480-45b7-11e9-8f62-2903a78f8558.png">

**Comment by biochem-fan** [comment]
Did you use `--keep_scratch` or `--reuse_scratch`?

**Comment by olibclarke** [comment]
Neither. Should I have? I thought the default would be to treat the new job as though it was an independent dataset?

Oli

**Comment by olibclarke** [comment]
Hi Takanori - to be clear, I did not use --keep_scratch or --reuse_scratch in either run, but is this mandatory? Is it necessary to manually assign where on the scratch disk each run puts the particle stack? I don't recall having to do this before, though I mostly read the whole particle set into RAM when I can

**Comment by biochem-fan** [comment]
Hi, if you use the same scratch directory for two jobs, you have to use these options. Otherwise, the second job will delete the scratch at the beginning, killing the first job. `--reuse_scratch` prevents this. When one job finishes, it clears the scratch, killing the other. `--keep_scratch` prevents that.

**Comment by olibclarke** [comment]
Ah got it - I did not realize that, I expected the default would be to create a uniquely named stack on scratch for each job. Sorry for the bother

Cheers
Oli
