### ISSUE TITLE
Acknowledgement of code borrowed from other sources

### ISSUE THREAD

**Issue by amzs** [3dem/relion#460]
Hi,

I am glad to see that there is a project that uses code originally written by me (CPlot2D.h, CPlot2D.cpp), which is the true spirit of opensource codes. However, what I am not happy about is that the original source is not acknowledged. There a file in your project where you acknowledge other codes used and I do not see my project in there. So please give credit where credit is due or remove my code from your project.

Thank you,
A.M. Zsaki

**Comment by scheres** [comment]
Dear amzs,
Thank you for pointing this out. This was an oversight, and we will correct this today. Please accept our sincere apologies for this.
Best,
Sjors

**Comment by scheres** [comment]
I've also tweeted about this: https://twitter.com/SjorsScheres/status/1115989103051407360
Hope it helps.
best,
Sjors
