### ISSUE TITLE
Can't find g++ in PATH

### ISSUE THREAD

**Issue by SalahBioPhysics** [3dem/relion#461]
I'm trying to install relion following this repo.  I get the following error when running 
`make -j4` inside build.

`The Open MPI wrapper compiler was unable to find the specified compiler /opt/rh/devtoolset-3/root/usr/bin/g++ in your PATH`

Can I set an environment variable for the g++ compiler?  Any help?
The above path is empty, but g++ is in my `/usr/bin`

**Comment by biochem-fan** [comment]
Please install `devtoolset-3`.

**Comment by SalahBioPhysics** [comment]
That works.  Thanks 👍
