### ISSUE TITLE
Symmetry expansion takes up n-fold more space on scratch

### ISSUE THREAD

**Issue by olibclarke** [3dem/relion#462]
Hi,

When one uses a dataset created with `relion_particle_symmetry_expand` in conjunction with a scratch disk, Relion currently treats each symmetry expanded *copy* of a particle as a completely separate particle, and concatenates them all into a single particles.mrcs file on scratch. 

This means the dataset takes up n-fold more space on scratch for a Cn symmetric particle, which is a problem with large particles or high symmetry (as it exceeds the amount of room on the SSD). 

In the particle.star file, these symmetry expanded particles refer to the same particle, just with different Euler angles - is there a reason why the same particle must be copied to scratch separately for each symmetry operation?

Cheers
Oli

**Comment by bforsbe** [comment]
Symmetry expand creates a new .star, but no new .mrcs. If you run 
subtraction or re-extraction, you create new images, which are all 
unique if you base it on a symmetry-expanded thing, so a new, bigger 
mrcs is produced. RELION doesn't know that they are related or identical.

/Björn

**Comment by biochem-fan** [comment]
Hi Oli,

As we discussed before https://bitbucket.org/scheres/relion-3.0_beta/issues/58/copying-symmetry-expanded-particle-sets-to, this is on own TODO list.

**Comment by olibclarke** [comment]
Hi Björn

I'm not talking about running symmetry expand itself, or subtraction or re-extraction. I am specifically talking about running relion_refine with a scratch disk, when the dataset is copied to an SSD. In this case, the symmetry expanded particle copies are treated as unique, even though they are identical, and this causes problems because the new dataset doesn't fit on the scratch disk. Given that the particle name is the same, surely when just copying the files (not subtracting or re-extracting) relion should be able to detect that these are not unique entities?

**Comment by olibclarke** [comment]
Ah - sorry Takanori - I thought I had brought it up before, but I couldn't find it when I googled after running up against it again - my apologies.

**Comment by biochem-fan** [comment]
Meanwhile, you can copy particles manually to your SSD and replace `Extract/jobXXX` with a symbolic link.

**Comment by bforsbe** [comment]
Ah I see what you mean. So you'd want RELION to copy only the set of unique mrcs-frames in the .star into a new .mrcs. Makes sense.

**Comment by olibclarke** [comment]
> Meanwhile, you can copy particles manually to your SSD and replace `Extract/jobXXX` with a symbolic link.

Ah - I didn't quite understand that work around - now I see! I will try that for my current refinement, it is currently taking 7hrs per iteration so hopefully that will speed things up substantially - thank you @biochem-fan!

**Comment by biochem-fan** [comment]
@olibclarke, I implemented this on RELION 3.1 but do not have a good test case at hand. When we start beta testing (I don't know when yet), please don't forget to test it.
