### ISSUE TITLE
Pixel and box size aware references (quality of life/feature request)

### ISSUE THREAD

**Issue by daniel-s-d-larsson** [3dem/relion#465]
Early on in my workflow, I use small boxes and rescale during extraction. Later on, I will re-extract with unscaled data and perhaps increase the box size. It would be nice if the Class3D and Refine3D job types would rescale the pixel size and crop or zero pad the box of the reference on the fly. Now I have to use the relion_image_handler tool with the flags --angpix --rescale_angpix and --new_box.

**Comment by biochem-fan** [comment]
In RELION 3.1, you can merge particles of different box sizes and pixel sizes. All particles will be refined against the reference box size and pixel size. In other words, the reference has higher priority than particles.
