### ISSUE TITLE
Subset selection output (quality of life/feature request)

### ISSUE THREAD

**Issue by daniel-s-d-larsson** [3dem/relion#466]
The output from a selection job with subset selection (e.g. rlnCtfMaxResolution) currently does not print how many micrographs/particles were selected.

**Comment by biochem-fan** [comment]
Do you mean outputs from `relion_star_handler` with `--select`? If so, this is trivial. I will add the message in 3.1.

**Comment by daniel-s-d-larsson** [comment]
My use case was the Subset selection job type from the GUI with "Select based on metadata values" set to "Yes". And yes, this is trivial.

**Comment by biochem-fan** [comment]
Done. This feature will be included in 3.1. Thanks for your feedback.
