### ISSUE TITLE
Argument list too long, scratch, chmod 777

### ISSUE THREAD

**Issue by EMBL-Structures** [3dem/relion#467]
Hi all,

https://github.com/3dem/relion/blob/c3b33646ae0e8a8c9a19bc44dceb4cd8092699a5/src/exp_model.cpp#L786

"ERROR in executing chmod 777 /tmp/33776414/relion_volatile/particle*" occured for a data set with 58000 particles.
We fixed the issue in our installation by using chmod -R instead:
	std::string command = " chmod -R 777 " + fn_scratch + "/";

Cheers,
Thomas

**Comment by biochem-fan** [comment]
Thanks for your report. Is this for 3D particles (i.e. subtomogram averaging)?

**Comment by EMBL-Structures** [comment]
yes

**Comment by biochem-fan** [comment]
Thanks. This will be fixed in the next release.
