### ISSUE TITLE
GPU issue

### ISSUE THREAD

**Issue by 4esoLATE** [3dem/relion#468]
Dear All,

GPU is not really used when using GPU acceleration.

When I start a 3D auto refine job. It shows its working properly.

RELION version: 3.0.5 
Precision: BASE=double, CUDA-ACC=single 

 === RELION MPI setup ===
 + Number of MPI processes             = 5
 + Number of threads per MPI process  = 4
 + Total number of threads therefore  = 20
 + Master  (0) runs on host            = dalian
 + Slave     1 runs on host            = dalian
 + Slave     2 runs on host            = dalian
 + Slave     3 runs on host            = dalian
 + Slave     4 runs on host            = dalian
 =================
 uniqueHost dalian has 4 ranks.
GPU-ids not specified for this rank, threads will automatically be mapped to available devices.
 Thread 0 on slave 1 mapped to device 0
 Thread 1 on slave 1 mapped to device 0
 Thread 2 on slave 1 mapped to device 0
 Thread 3 on slave 1 mapped to device 0
GPU-ids not specified for this rank, threads will automatically be mapped to available devices.
 Thread 0 on slave 2 mapped to device 1
 Thread 1 on slave 2 mapped to device 1
 Thread 2 on slave 2 mapped to device 1
 Thread 3 on slave 2 mapped to device 1
GPU-ids not specified for this rank, threads will automatically be mapped to available devices.
 Thread 0 on slave 3 mapped to device 2
 Thread 1 on slave 3 mapped to device 2
 Thread 2 on slave 3 mapped to device 2
 Thread 3 on slave 3 mapped to device 2
GPU-ids not specified for this rank, threads will automatically be mapped to available devices.
 Thread 0 on slave 4 mapped to device 3
But I check GPU usage with command nvidia-smi, GPU is not really used.

Tue May 14 11:58:53 2019       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 390.116                Driver Version: 390.116                   |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  TITAN X (Pascal)    On   | 00000000:02:00.0  On |                  N/A |
| 24%   37C    P8    18W / 250W |   1239MiB / 12195MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  TITAN X (Pascal)    On   | 00000000:03:00.0 Off |                  N/A |
| 23%   36C    P8    10W / 250W |     12MiB / 12196MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  TITAN X (Pascal)    On   | 00000000:83:00.0 Off |                  N/A |
| 24%   36C    P8     9W / 250W |     12MiB / 12196MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   3  TITAN X (Pascal)    On   | 00000000:84:00.0 Off |                  N/A |
| 23%   34C    P8    10W / 250W |     12MiB / 12196MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0     19206      G   /usr/lib/xorg/Xorg                           183MiB |
|    0     20347      G   ...-token=8E3CBF09C5286ADB1601C8052C62F7AB     2MiB |
|    0     20560      G   ...-token=26BC6492602AC9317C1E609CC49E460F     2MiB |
|    0     20846      G   ...-token=205DBEBDEB394F1AFA80ECAD9B638083     2MiB |
|    0     20901      G   ...-token=C6BAE40C221BE68FB2B4F43FEF7F20B7     2MiB |
|    0     20965      G   ...-token=76F8F127C24652F99B45C7D8619E0E36     2MiB |
|    0     20996      C   /usr/lib/libreoffice/program/soffice.bin     145MiB |
|    0     23609      G   /usr/lib/xorg/Xorg                           166MiB |
|    0     47202      G   /usr/lib/xorg/Xorg                           461MiB |
|    0     47777      G   compiz                                        16MiB |

 Thread 1 on slave 4 mapped to device 3
 Thread 2 on slave 4 mapped to device 3
 Thread 3 on slave 4 mapped to device 3
 Running CPU instructions in double precision. 

Do you have any ideas to fix this problem?

Sincerely yours,

Ke Chen

**Comment by biochem-fan** [comment]
GPU is used only in the E step. You should check `nvidia-smi` when the program says something like:
```
Expectation iteration X
0.18/8.05 min ....~~(,_,">
```

**Comment by 4esoLATE** [comment]
Thank you!
Expectation iteration X only takes 9 second so we did not catch it using nvdia-smi.

Ke
