### ISSUE TITLE
Option to run the last auto-refine iteration w/o GPU

### ISSUE THREAD

**Issue by daniel-s-d-larsson** [3dem/relion#471]
Upon convergence of a Refine3D job, the final iteration will use data to Nyquist frequency. It would be nice to have a "power user" flag to force the last iteration to be done on the CPUs only, in those cases that you know that the GPU memory is not enough.

**Comment by biochem-fan** [comment]
Why don't you use `Skip padding: Yes`? Is your box larger than 1000 px?

**Comment by daniel-s-d-larsson** [comment]
It should be reasonably easy to implement skipping GPUs in the final iteration and it would improve my workflow substantially. As it is now, the job will crash and I have to manually restart. Then it usually takes a few iterations before the reconstruction is considered to have converged before entering the final iteration. (There are of course ways around this, such as queuing up a continuation job and using the --force_converge flag, but those workarounds are a bit messy.)

I know of the --pad 1 or "skip padding" option, but I'm a bit weary of the artifacts in the corners. I think the box size should be a bit larger when doing --pad 1, right? Perhaps I should start using that option...

**Comment by biochem-fan** [comment]
> Then it usually takes a few iterations before the reconstruction is considered to have converged

What is wrong with `--force_converge`? This is what we recommend.

> I know of the --pad 1 or "skip padding" option, but I'm a bit weary of the artifacts in the corners.
> I think the box size should be a bit larger when doing --pad 1, right?

As long as it is outside your protein mask, it does not matter. You can also try `--pad 1.2` (you have to remove `--pad X` from the command line generated by the GUI).

The last iteration on CPU takes significant time; it should be run on multiple CPU nodes. The optimal MPI-to-thread ratio is also different. Wasting GPU nodes on a long non-GPU task is not a good idea. Although this might be useful on some computing environments, I am not convinced this is generally useful. Such hack should be done locally.
