### ISSUE TITLE
How does Relion 2D classification calculate the initial 2D reference averages

### ISSUE THREAD

**Issue by phonchi** [3dem/relion#475]
Dear developers:

I am tracing the code and found that in _ml_model.cpp_ file there is [a comment](https://github.com/3dem/relion/blob/master/src/ml_model.cpp#L766) says that "If no -ref is given, calculate average of all unaligned images later on.". But I can not find the corresponding code that calculates the average.

I am curious about how does Relion 2D classification form the initial 2D reference averages?
Does it randomly choose images from dataset or randomly group images as initial references?

Thanks in advance!!

**Comment by biochem-fan** [comment]
Relevant codes are here: https://github.com/3dem/relion/blob/master/src/ml_optimiser.cpp#L2180

Basically, each image is assigned to a random class with a random orientation.

**Comment by phonchi** [comment]
Thanks!!
