### ISSUE TITLE
Segfault on relion_refine_mpi with Relion 3.0-stable

### ISSUE THREAD

**Issue by rudaluna** [3dem/relion#476]
Hi,

I had a job running on our HPC and it just stopped running without any error on the error logs. Our system administrator pulled this from the system logs:

May 25 05:44:15 node062 kernel: relion_refine_m[4651]: segfault at 28 ip 000000000060d150 sp 00002aaac97fe980 error 4 in relion_refine_mpi[400000+477000]
May 25 06:07:54 node062 kernel: relion_refine_m[4629]: segfault at 28 ip 000000000060d9ed sp 00002aaac97fe9f0 error 4 in relion_refine_mpi[400000+477000]

It's the second time this happens. Please let me know what additional information files/information would be necessary to sort this issue out.

**Comment by biochem-fan** [comment]
- Full command you run
- box size and pixel size
- CPU or GPU
- Number of MPI processes and threads
- When did this happen? In the first iteration? During the E-step or M step?
- Does this always happen for this particular job?

**Comment by biochem-fan** [comment]
No response for one month. Closing.

**Comment by mcahn** [comment]
I'm not sure if this is the same issue, but perhaps it's a compiler problem. I built 3.0 with the Intel compiler version 18.  RELION would consistently give "segmentation violation" after a few seconds when running a 3D refinement.  I built 3.0.6 with gcc 7.3.1 and it works fine.

-- Matthew Cahn

**Comment by biochem-fan** [comment]
This could be related to this: https://github.com/3dem/relion/issues/453
