### ISSUE TITLE
relion3 crashed when running 2D classification

### ISSUE THREAD

**Issue by HICRYOEM** [3dem/relion#481]
Hi,

Any comment or provide advice on the issue will be greatly appreciated:

RELION version: 3.0.3 
Precision: BASE=double, CUDA-ACC=single 

 === RELION MPI setup ===
 + Number of MPI processes             = 5
 + Master  (0) runs on host            = teras.xxx.edu
 + Slave     1 runs on host            = teras.xxx.edu
 + Slave     2 runs on host            = teras.xxx.edu
 + Slave     3 runs on host            = teras.xxx.edu
 + Slave     4 runs on host            = teras.xxx.edu
 =================
 uniqueHost teras.xxx.edu has 4 ranks.
 Using explicit indexing on slave 1 to assign devices  0
 Thread 0 on slave 1 mapped to device 0
 Using explicit indexing on slave 2 to assign devices  1
 Thread 0 on slave 2 mapped to device 1
 Using explicit indexing on slave 3 to assign devices  2
 Thread 0 on slave 3 mapped to device 2
 Using explicit indexing on slave 4 to assign devices  3
 Thread 0 on slave 4 mapped to device 3
 Running CPU instructions in double precision. 

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   PID 160529 RUNNING AT teras.xxx.edu
=   EXIT CODE: 9
=   CLEANING UP REMAINING PROCESSES
=   YOU CAN IGNORE THE BELOW CLEANUP MESSAGES
===================================================================================
YOUR APPLICATION TERMINATED WITH THE EXIT STRING: Killed (signal 9)
This typically refers to a problem with your application.
Please see the FAQ page for debugging suggestions

Thanks so much in advance!

HICRYOEM

**Comment by biochem-fan** [comment]
We need more information!
The box size, number of particles, number of classes, command line options, etc.

DId you try to pre-read all images into RAM? If so, it might have ran out of memory.

**Comment by HICRYOEM** [comment]
Thanks so much for the quick response! Box size: 648 , 100,000 particles and 100 classes. I guess 'pre-read all images into RAM" may cause the problem. I have then tried to set "NO pre-read", but still got error" Kernel error out of memory in usr/local/relion-3-source/src/acc/utilities_impl.h at line 253 (error-code 2). Any additional suggestions? My workstation's memory is 16x12 GB . Thanks again!

**Comment by biochem-fan** [comment]
What GPU are you using? Aren't you running other programs that use GPU simultaneously? Usually Class2D does not use much GPU memory.

By the way, why your box so large? Class2D can be performed on down-sampled particles, say at 3 or 4 A/px.

**Comment by HICRYOEM** [comment]
4x RTX 2080 Ti 11GB GPU, No, I'm only running relion. I'm picking up the particles that are dimer and have around 620 A diameter. Probably I can try down-sampled. Now the pixel size is 0.9A. Thanks

**Comment by biochem-fan** [comment]
Did you increase the number of pooled particles? If so, revert to the default value (3).

**Comment by HICRYOEM** [comment]
yes, I have increased it to 20 as suggested. I may try a small value just like 3. Thanks for the advice. I will try it.

**Comment by HICRYOEM** [comment]
I have tried all, but still got " Kernel error out of memory in usr/local/relion-3-source/src/acc/utilities_impl.h at line 253 (error-code 2)"

........................................
 Auto-refine: Estimated accuracy angles= 30.1 degrees; offsets= 10.1 pixels
 CurrentResolution= 145.8 Angstroms, which requires orientationSampling of at least 25.7143 degrees for a particle of diameter 648 Angstroms
 Oversampling= 0 NrHiddenVariableSamplingPoints= 67200
 OrientationalSampling= 11.25 NrOrientations= 32
 TranslationalSampling= 2 NrTranslations= 21
=============================
 Oversampling= 1 NrHiddenVariableSamplingPoints= 2150400
 OrientationalSampling= 5.625 NrOrientations= 256
 TranslationalSampling= 1 NrTranslations= 84
=============================
 Expectation iteration 1 of 25 (with 10000 particles)
000/??? sec ~~(,_,">                                                          [oo]KERNEL_ERROR: out of memory in /usr/local/relion-3-source/src/acc/utilities_impl.h at line 253 (error-code 2)
............................................

Any suggestions? Thanks so much again!

**Comment by biochem-fan** [comment]
Which CUDA version did you use to compile and run the program?
Does the program work fine on other datasets?

**Comment by HICRYOEM** [comment]
Should be cuda_10.0.130_410.48_linux
I have no chance to try other datasets since this is a new workstation. Will try different datasets. Probably caused by too large box size?
or hardware errors in memory chips?
