### ISSUE TITLE
compiling in centos GPU

### ISSUE THREAD

**Issue by srvryt** [3dem/relion#482]
Hi 
I am trying to compile and install Relion 3 in a CentOS  linux (GPU) and following the recommended set of instructions for installation lands me up with following errors. I have an installation of FFTW and FLTK latest version through standard yum install .... This is how the error looks, any help is appreciated 
*************************************************************************************************************************cmake -DCMAKE_INSTALL_PREFIX=/usr/local/relion/ ..
-- The C compiler identification is GNU 5.3.1
-- The CXX compiler identification is GNU 5.3.1
-- Check for working C compiler: /opt/rh/devtoolset-4/root/usr/bin/cc
-- Check for working C compiler: /opt/rh/devtoolset-4/root/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /opt/rh/devtoolset-4/root/usr/bin/c++
-- Check for working CXX compiler: /opt/rh/devtoolset-4/root/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- BUILD TYPE set to the default type:  'Release'
-- Setting fallback CUDA_ARCH=35
-- CUDA enabled - Building CUDA-accelerated version of RELION
-- Setting cpu precision to double
-- Setting accelerated code precision to single
-- Found CUDA: /usr/local/cuda (found version "8.0") 
-- Using cuda wrapper to compile....
-- Cuda version is >= 7.5 and single-precision build, enable double usage warning.
-- Found MPI_C: /usr/local/mpich-3.1.4/lib/libmpi.so  
-- Found MPI_CXX: /usr/local/mpich-3.1.4/lib/libmpicxx.so;/usr/local/mpich-3.1.4/lib/libmpi.so  
-- MPI_INCLUDE_PATH : /usr/local/mpich-3.1.4/include
-- MPI_LIBRARIES : /usr/local/mpich-3.1.4/lib/libmpicxx.so;/usr/local/mpich-3.1.4/lib/libmpi.so
-- MPI_CXX_INCLUDE_PATH : /usr/local/mpich-3.1.4/include
-- MPI_CXX_LIBRARIES : /usr/local/mpich-3.1.4/lib/libmpicxx.so;/usr/local/mpich-3.1.4/lib/libmpi.so
-- CMAKE_C_COMPILER : /opt/rh/devtoolset-4/root/usr/bin/cc
-- CMAKE_CXX_COMPILER : /opt/rh/devtoolset-4/root/usr/bin/c++
-- MPI_C_COMPILER : /usr/local/mpich-3.1.4/bin/mpicc
-- MPI_CXX_COMPILER : /usr/local/mpich-3.1.4/bin/mpicxx
-- CMAKE_CXX_COMPILER_ID : GNU
-- CMAKE_C_COMPILER : /usr/local/mpich-3.1.4/bin/mpicc
-- CMAKE_CXX_COMPILER : /usr/local/mpich-3.1.4/bin/mpicxx
-- MPI_C_COMPILER : /usr/local/mpich-3.1.4/bin/mpicc
-- MPI_CXX_COMPILER : /usr/local/mpich-3.1.4/bin/mpicxx
-- Looking for XOpenDisplay in /usr/lib64/libX11.so;/usr/lib64/libXext.so
-- Looking for XOpenDisplay in /usr/lib64/libX11.so;/usr/lib64/libXext.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Looking for IceConnectionNumber in ICE
-- Looking for IceConnectionNumber in ICE - found
-- Found X11: /usr/lib64/libX11.so
-- Could NOT find FLTK (missing:  FLTK_LIBRARIES FLTK_INCLUDE_DIR FLTK_FLUID_EXECUTABLE) 
-- No FLTK installation was found
-- --------------------------------------------------------
-- -------- NO EXISTING FLTK LIBRARIES WHERE FOUND. -------
-- -------------- FLTK WILL BE DOWNLOADED AND -------------
-- --------------- BUILT DURING COMPILE-TIME. -------------
-- --------------------------------------------------------
-- ---- A WORKING INTERNET CONNECTION WILL BE REQUIRED. ---
-- --------------------------------------------------------
-- no previous fltk found, the following paths are set for libs/headers TO BE built
-- FLTK_INCLUDE_DIR: /root/relion/external/fltk/include
-- FLTK_LIBRARIES:   /root/relion/external/fltk/lib/libfltk.so
-- Single-precision FFTW was required but NOT found
-- Double-precision FFTW was required but NOT found
-- --------------------------------------------------------
-- ------ REQUIRED FFTW LIBRARIES WHERE NOT FOUND. --------
-- -------------- FFTW WILL BE DOWNLOADED AND -------------
-- --------------- BUILT DURING COMPILE-TIME. -------------
-- --------------------------------------------------------
-- ---- A WORKING INTERNET CONNECTION WILL BE REQUIRED. ---
-- --------------------------------------------------------
-- Looking for sincos
-- Looking for sincos - found
-- Looking for __sincos
-- Looking for __sincos - not found
-- Could NOT find TIFF (missing:  TIFF_LIBRARY TIFF_INCLUDE_DIR) 
BUILD_SHARED_LIBS = OFF
-- Building static libs (larger build size and binaries)
Running apps/CMakeLists.txt...
-- CMAKE_BINARY_DIR:/root/relion/build
TIFF NOT FOUND
-- Try OpenMP C flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Try OpenMP CXX flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Found OpenMP: -fopenmp  
OPENMP FOUND
-- Configuring done
-- Generating done
-- Build files have been written to: /root/relion/build

**Comment by biochem-fan** [comment]
I don't see any problem. Just type `make`.

**Comment by srvryt** [comment]
After typing make it doesn't proceed and stops at about 4% of the run

**Comment by biochem-fan** [comment]
Is your machine connected to the internet? As the `cmake` message suggests, RELION wants to build its own version of FFTW and FLTK by downloading them. It is possible to use the system wide installation you installed via `yum` but it is highly recommended to let RELION build its own, because the version you installed might not be compatible with RELION and/or compiled with wrong compiler flags.

**Comment by srvryt** [comment]
It apparently seems to be connected to the internet because as I type in firefox the system does connect to the internet

**Comment by biochem-fan** [comment]
> stops at about 4% of the run

What is printed so far?

**Comment by srvryt** [comment]
[  3%] Creating directories for 'own_fftw_lib'
[  4%] Performing download step (download, verify and extract) for 'own_fftw_lib'
-- downloading...
     src='ftp://ftp.fftw.org/pub/fftw/fftw-3.3.4.tar.gz'
     dst='/root/relion/external/fftw/fftw-3.3.4.tar.gz'
     timeout='none'
CMake Error at /root/relion/own_fftw_lib-prefix/src/own_fftw_lib-stamp/download-own_fftw_lib.cmake:9 (file):
  file DOWNLOAD HASH mismatch

    for file: [/root/relion/external/fftw/fftw-3.3.4.tar.gz]
      expected hash: [2edab8c06b24feeb3b82bbb3ebf3e7b3]
        actual hash: [d41d8cd98f00b204e9800998ecf8427e]

I guess there is a mismatch in the fftw version and it is exiting, It could downlaod and build fltk

**Comment by biochem-fan** [comment]
Please delete `/root/relion/external/fftw/fftw-3.3.4.tar.gz` and try again. Sometimes downloaded files are broken.

**Comment by srvryt** [comment]
OK

**Comment by srvryt** [comment]
unfortunately it shows me the same error 

Creating directories for 'own_fftw_lib'
[  4%] Performing download step (download, verify and extract) for 'own_fftw_lib'
-- downloading...
     src='ftp://ftp.fftw.org/pub/fftw/fftw-3.3.4.tar.gz'
     dst='/root/relion/external/fftw/fftw-3.3.4.tar.gz'
     timeout='none'
CMake Error at /root/relion/build/own_fftw_lib-prefix/src/own_fftw_lib-stamp/download-own_fftw_lib.cmake:9 (file):
  file DOWNLOAD HASH mismatch

    for file: [/root/relion/external/fftw/fftw-3.3.4.tar.gz]
      expected hash: [2edab8c06b24feeb3b82bbb3ebf3e7b3]
        actual hash: [d41d8cd98f00b204e9800998ecf8427e]



make[2]: *** [own_fftw_lib-prefix/src/own_fftw_lib-stamp/own_fftw_lib-download] Error 1
make[1]: *** [CMakeFiles/own_fftw_lib.dir/all] Error 2
make: *** [all] Error 2

**Comment by biochem-fan** [comment]
Probably the broken file has been cached somewhere in your network. Please try again later.

**Comment by srvryt** [comment]
Is there a way to manually remove it

**Comment by biochem-fan** [comment]
No, it depends on your network. Indeed, something seems wrong with their FTP server. I myself cannot download ftp://ftp.fftw.org/pub/fftw/fftw-3.3.4.tar.gz right now.

**Comment by srvryt** [comment]
Yes my network seems to just seems to time out

**Comment by srvryt** [comment]
For the cpu version with Ubuntu as an OS I didn't face such problems

**Comment by biochem-fan** [comment]
If download was successful at that time, you might be able to copy `relion/external/fftw/fftw-3.3.4.tar.gz` from your Ubuntu.

**Comment by srvryt** [comment]
I remember compiling fftw-3.3.8 and fltk from source for ubuntu, and probably that's the reason that it doesn't contain an "external" folder. since I don't have a problem with Fltk would compiling and installing fftw-3.3.8 from source be a good idea?

**Comment by biochem-fan** [comment]
Yes, you can try. You need both double and single precision builds.

**Comment by srvryt** [comment]
So, to install both the single- and double-precision libraries on the same machine, you would do:

./configure --enable-type-prefix [ other options ]
make
make install
make clean
./configure --enable-float --enable-type-prefix [ other options ]
make
make install


I would have to do this correct? But I am a bit confused about what [ other options ] are referring to

**Comment by biochem-fan** [comment]
You don't need to specify anything for `[ other options ]`. You might want to install FFTW to somewhere else by `--prefix` option and specify it in `cmake`. That being said, this is rather advanced way of installation. If you are not sure, just wait until the FFTW server comes up.

**Comment by srvryt** [comment]
I wrote to FFTW they said that their servers were running and possibly my institution could be blocking it....

**Comment by alburse** [comment]
I have seen the same problem before for fltk, I think this has to do with cmake somehow cannot download those links. You can download the fftw and fltk libraries manually, extract and put it under relion-source/external/fltk and relion-source/external/fftw. Then run your cmake command again.

**Comment by srvryt** [comment]
Hi Guys
Sorry for the late post, I could resolve the issue, yes I manually extracted and installed the fftw version relion was looking for and then ran cmake it worked, thanks
