### ISSUE TITLE
Subset selection for Micrographs on version 3.06 does not finish 

### ISSUE THREAD

**Issue by alburse** [3dem/relion#486]
Dear Relion developers

I tried to do subset selection for ctf corrected micrographs using split into subsets. However the job is hanging as not finished even though output states it is "done". This happens for both options of "subset size" and "number of subsets". I tried the same subset selection with 3.04 and it finishes without a problem.

**Comment by biochem-fan** [comment]
Thanks for reporting. Meanwhile you can `mark the job as finished`. The output is there.

**Comment by biochem-fan** [comment]
This will be fixed in 3.1.
