### ISSUE TITLE
problems on installing relion

### ISSUE THREAD

**Issue by Gwynase** [3dem/relion#487]
i'm doing the last step of installing relion but i think some thing is wrong.
here i attached the code.

chu@chu:~/disk1/relion/relion/build$ cmake ..
-- BUILD TYPE set to the default type:  'Release'
-- Using provided CUDA_ARCH=52
-- CUDA enabled - Building CUDA-accelerated version of RELION
-- Setting cpu precision to double
-- Setting accelerated code precision to single
CUDA_TOOLKIT_ROOT_DIR not found or specified
-- Could NOT find CUDA (missing: CUDA_TOOLKIT_ROOT_DIR CUDA_NVCC_EXECUTABLE CUDA_INCLUDE_DIRS CUDA_CUDART_LIBRARY) 
-- Using non-cuda compilation....
-- Omitting GUI targets as per your request
-- MPI_INCLUDE_PATH : /usr/lib/x86_64-linux-gnu/openmpi/include/openmpi;/usr/lib/x86_64-linux-gnu/openmpi/include
-- MPI_LIBRARIES : /usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi_cxx.so;/usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi.so
-- MPI_CXX_INCLUDE_PATH : /usr/lib/x86_64-linux-gnu/openmpi/include/openmpi;/usr/lib/x86_64-linux-gnu/openmpi/include
-- MPI_CXX_LIBRARIES : /usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi_cxx.so;/usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi.so
-- CMAKE_C_COMPILER : /usr/bin/cc
-- CMAKE_CXX_COMPILER : /usr/bin/c++
-- MPI_C_COMPILER : /usr/bin/mpicc
-- MPI_CXX_COMPILER : /usr/bin/mpicxx
-- CMAKE_CXX_COMPILER_ID : GNU
-- CMAKE_C_COMPILER : /usr/bin/mpicc
-- CMAKE_CXX_COMPILER : /usr/bin/mpicxx
-- MPI_C_COMPILER : /usr/bin/mpicc
-- MPI_CXX_COMPILER : /usr/bin/mpicxx
-- Found previously built non-system single precision FFTW libraries that will be used.
-- Found previously built non-system double precision FFTW libraries that will be used.
-- Could NOT find TIFF (missing: TIFF_LIBRARY TIFF_INCLUDE_DIR) 
BUILD_SHARED_LIBS = OFF
-- Building static libs (larger build size and binaries)
Running apps/CMakeLists.txt...
-- CMAKE_BINARY_DIR:/home/chu/disk1/relion/relion
TIFF NOT FOUND
OPENMP FOUND
-- Configuring done
-- Generating done
-- Build files have been written to: /home/chu/disk1/relion/relion

I think one of the reason is 'TIFF NOT FOUND', but I do install libTIFF by 'sudo apt-get install libTIFF'. Can someone tell me how to move forward or where i can find help of setting up these scripts.
Thank you very very much.
Best regards!

**Comment by biochem-fan** [comment]
You need `libtiff-dev` package.

**Comment by Felix931** [comment]
Try this:
```
cd build
cmake \
    -DCMAKE_C_FLAGS:STRING="$SLKCFLAGS" \
    -DCMAKE_CXX_FLAGS:STRING="$SLKCFLAGS" \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DMANUAL_DIRECTORY=man \
    -DLIB_SUFFIX=${LIBDIRSUFFIX} \
    -DGNASH_EXE_PATH=/usr/bin/gtk-gnash \
    -DCMAKE_BUILD_TYPE=Release ..
  make
  sudo make install
```
