### ISSUE TITLE
relion_refine --continue sampling exorbitant for helical refinement

### ISSUE THREAD

**Issue by superdex75** [3dem/relion#490]
Hi, with 
RELION version: 3.0.6 
Precision: BASE=double, CUDA-ACC=single
I am running 3D auto refinement with helical symmetry. The last iteration when convergence is reached and FFT is done to Nyquist cannot be done with the gpus (normal behavior) and I would like to finish with cpus only using the --continue option. However, with --continue the angular sampling goes to exorbitant numbers, e.g. from 11080 to 25529616. I suspect that helical symmetry is not taken into account in case of --continue and normal C1 sampling is applied? The box is 1024 and particle diameter is 850, with an angular sampling of 25529616 and cpu, calculating the expectation step will never finish.
Thanks, Simon

#####################################
INITIAL gpu run:

 Auto-refine: Iteration= 24
 Auto-refine: Resolution= 5.68889 (no gain for 1 iter) 
 Auto-refine: Changes in angles= 0.0310901 degrees; and in offsets= 0.0975769 pixels (no gain for 3 iter) 
 Auto-refine: Refinement has converged, entering last iteration where two halves will be combined...
 Auto-refine: The last iteration will use data to Nyquist frequency, which may take more CPU and RAM.
 Estimating accuracies in the orientational assignment ... 
  41/  41 sec ............................................................~~(,_,">
 Auto-refine: Estimated accuracy angles= 0.11 degrees; offsets= 0.395 pixels
 Auto-refine: Angular step= 0.0585938 degrees; local searches= true
 Auto-refine: Helical refinement... Local translational searches along helical axis= true
 Auto-refine: Offset search range= 0.88875 pixels; offset step= 0.29625 pixels; offset step along helical axis= 0.269894 pixels
 CurrentResolution= 5.68889 Angstroms, which requires orientationSampling of at least 0.765957 degrees for a particle of diameter 850 Angstroms
 Oversampling= 0 NrHiddenVariableSamplingPoints= 12465
 OrientationalSampling= 0.117188 NrOrientations= 1385
 TranslationalSamplingAlongHelicalAxis= 0.539788 TranslationalSampling= 0.5925 NrTranslations= 9
=============================
 Oversampling= 1 NrHiddenVariableSamplingPoints= 398880
 OrientationalSampling= 0.0585938 NrOrientations= 11080
 TranslationalSamplingAlongHelicalAxis= 0.269894 TranslationalSampling= 0.29625 NrTranslations= 36
=============================
WARNING: Ignoring required free GPU memory amount of 1200 MB, due to space insufficiency.
WARNING: Ignoring required free GPU memory amount of 1200 MB, due to space insufficiency.
WARNING: Ignoring required free GPU memory amount of 1200 MB, due to space insufficiency.
WARNING: Ignoring required free GPU memory amount of 1200 MB, due to space insufficiency.
WARNING: Ignoring required free GPU memory amount of 1200 MB, due to space insufficiency.
WARNING: Ignoring required free GPU memory amount of 1200 MB, due to space insufficiency.
WARNING: Ignoring required free GPU memory amount of 1200 MB, due to space insufficiency.
 Expectation iteration 24
000/??? sec ~~(,_,">

#####################################
WITH --continue

 Auto-refine: Iteration= 24
 Auto-refine: Resolution= 5.68889 (no gain for 2 iter) 
 Auto-refine: Changes in angles= 0.03109 degrees; and in offsets= 0.097577 pixels (no gain for 3 iter) 
 Estimating accuracies in the orientational assignment ... 
   9/   9 sec ............................................................~~(,_,">
 Auto-refine: Estimated accuracy angles= 0.1075 degrees; offsets= 0.391 pixels
 Auto-refine: Angular step= 0.0585938 degrees; local searches= true
 Auto-refine: Helical refinement... Local translational searches along helical axis= true
 Auto-refine: Offset search range= 0.88875 pixels; offset step= 0.29625 pixels; offset step along helical axis= 0.269894 pixels
 CurrentResolution= 5.68889 Angstroms, which requires orientationSampling of at least 0.765957 degrees for a particle of diameter 850 Angstroms
 Oversampling= 0 NrHiddenVariableSamplingPoints= 28720818
 OrientationalSampling= 0.117188 NrOrientations= 3191202
 TranslationalSamplingAlongHelicalAxis= 0.539788 TranslationalSampling= 0.5925 NrTranslations= 9
=============================
 Oversampling= 1 NrHiddenVariableSamplingPoints= 919066176
 OrientationalSampling= 0.0585938 NrOrientations= 25529616
 TranslationalSamplingAlongHelicalAxis= 0.269894 TranslationalSampling= 0.29625 NrTranslations= 36
=============================
 Expectation iteration 24
000/??? sec ~~(,_,">

**Comment by scheres** [comment]
Hi Superdex75, 
This may be a harmless error in the reporting of the number. Could you try editing the optimiser.star from which you continue and change the rlnRandomSeed to a different number? The estimated value will then change. We will change this behaviour for relion-3.1. Meanwhile, are you sure you don't want to downsize your data a bit? 
hth,
Sjors
