### ISSUE TITLE
issue with motioncorr_runner.cpp

### ISSUE THREAD

**Issue by flipkenduiker** [3dem/relion#491]
Dear Relion users,
I'm using an Nvidia RTX2080 card and installed cuda10.1. I specified -DCUDA_ARCH=75 during the installation of Relion3.0.7.
When testing out the tutorial files, I run into the error below at the motion correction step.
Any clues would be appreciated!

best,

Filip

ERROR: unknown error in /usr/local/SOFTWARE/relion/src/motioncorr_runner.cpp at line 227 (error-code 999)
in: /usr/local/SOFTWARE/relion/src/acc/cuda/cuda_settings.h, line 67
=== Backtrace  ===
/usr/local/SOFTWARE/relion/build/bin/relion_run_motioncorr(_ZN11RelionErrorC1ERKSsS1_l+0x41) [0x41b681]
/usr/local/SOFTWARE/relion/build/bin/relion_run_motioncorr(_ZN16MotioncorrRunner10initialiseEv+0x15bd) [0x43b76d]
/usr/local/SOFTWARE/relion/build/bin/relion_run_motioncorr(main+0x33) [0x4157b3]
/lib64/libc.so.6(__libc_start_main+0xf5) [0x7f8d28d3f495]
/usr/local/SOFTWARE/relion/build/bin/relion_run_motioncorr() [0x415d9f]
==================
ERROR: 

A GPU-function failed to execute.

**Comment by biochem-fan** [comment]
Your driver or CUDA runtime is probably inconsistent.
