### ISSUE TITLE
The OpenMP installation issue again

### ISSUE THREAD

**Issue by jacknicoludis** [3dem/relion#493]
I'm having trouble with Relion installation on my Mac Book Pro running High Sierra 10.13

I downloaded relion using: 

`git clone https://github.com/3dem/relion.git`

Then I followed the next commands: 
`cd relion`
`mkdir build`
`cd build`
`cmake ..`

and I get the error:
`Could NOT find OpenMP_C (missing: OpenMP_C_FLAGS OpenMP_C_LIB_NAMES)`

I've tried the following to overcome the lack of OpenMP:
1) Installation of llvm and libomp via brew
2) Inclusion of following in `CMakeLists.txt`:
```
# Find OpenMP
if(APPLE AND USE_OpenMP)
    if(CMAKE_C_COMPILER_ID MATCHES "Clang")
        set(OpenMP_C "${CMAKE_C_COMPILER}")
        set(OpenMP_C_FLAGS "-fopenmp=libomp -Wno-unused-command-line-argument")
        set(OpenMP_C_LIB_NAMES "libomp" "libgomp" "libiomp5")
        set(OpenMP_libomp_LIBRARY ${OpenMP_C_LIB_NAMES})
        set(OpenMP_libgomp_LIBRARY ${OpenMP_C_LIB_NAMES})
        set(OpenMP_libiomp5_LIBRARY ${OpenMP_C_LIB_NAMES})
    endif()
    if(CMAKE_CXX_COMPILER_ID MATCHES "Clang")
      set(OpenMP_CXX "${CMAKE_CXX_COMPILER}")
      set(OpenMP_CXX_FLAGS "-fopenmp=libomp -Wno-unused-command-line-argument")
      set(OpenMP_CXX_LIB_NAMES "libomp" "libgomp" "libiomp5")
      set(OpenMP_libomp_LIBRARY ${OpenMP_CXX_LIB_NAMES})
      set(OpenMP_libgomp_LIBRARY ${OpenMP_CXX_LIB_NAMES})
      set(OpenMP_libiomp5_LIBRARY ${OpenMP_CXX_LIB_NAMES})
    endif()
endif()
 ```
3) Specifying the GCC path with:
```
cmake -D CMAKE_C_COMPILER=/usr/local/bin/gcc-9 -D CMAKE_CXX_COMPILER=/usr/local/bin/g++-9 ..
```

None of this has worked. What am I missing?

**Comment by jacknicoludis** [comment]
After a few hours and reading lots of issues here, I installed Relion 3. Here are some things I did:

- I made sure that I had all the proper modules installed:

`conda install -c conda-forge openmpi`
`brew install cuda`
`brew install fftw`
`brew install fltk`

- In the CMakeLists.txt file, I added the following to the top of the file:

```
# ----------------------------------------------------------------------------OpenMP--
# Find OpenMP

set(CMAKE_C_COMPILER "/usr/local/Cellar/llvm@5/5.0.2_1/bin/clang")
set(CMAKE_CXX_COMPILER "/usr/local/Cellar/llvm@5/5.0.2_1/bin/clang++")
set(OPENMP_LIBRARIES "/usr/local/Cellar/llvm@5/5.0.2_1/lib")
set(OPENMP_INCLUDES "/usr/local/Cellar/llvm@5/5.0.2_1/include")

OPTION (USE_OpenMP "Use OpenMP to enamble <omp.h>" ON)

# Find OpenMP
if(APPLE AND USE_OpenMP)
    if(CMAKE_C_COMPILER_ID MATCHES "Clang")
        set(OpenMP_C "${CMAKE_C_COMPILER}")
        set(OpenMP_C_FLAGS "-fopenmp=libomp -Wno-unused-command-line-argument")
        set(OpenMP_C_LIB_NAMES "libomp" "libgomp" "libiomp5")
        set(OpenMP_libomp_LIBRARY ${OpenMP_C_LIB_NAMES})
        set(OpenMP_libgomp_LIBRARY ${OpenMP_C_LIB_NAMES})
        set(OpenMP_libiomp5_LIBRARY ${OpenMP_C_LIB_NAMES})
    endif()
    if(CMAKE_CXX_COMPILER_ID MATCHES "Clang")
        set(OpenMP_CXX "${CMAKE_CXX_COMPILER}")
        set(OpenMP_CXX_FLAGS "-fopenmp=libomp -Wno-unused-command-line-argument")
        set(OpenMP_CXX_LIB_NAMES "libomp" "libgomp" "libiomp5")
        set(OpenMP_libomp_LIBRARY ${OpenMP_CXX_LIB_NAMES})
        set(OpenMP_libgomp_LIBRARY ${OpenMP_CXX_LIB_NAMES})
        set(OpenMP_libiomp5_LIBRARY ${OpenMP_CXX_LIB_NAMES})
    endif()
endif()
```

- I used LLVM version 5 (since current versions of LLVM are not compatible), which I downloaded though homebrew:
`brew install llvm@5`

- I cmake-d relion to /usr/local/relion:
`cmake -DCMAKE_INSTALL_PREFIX=/usr/local/relion ..`

- Then I `make -j4` and `make install`

- I think these were the most important things I did to get it to work, but there were other things I tried along the way. Best of luck to others trying to download this software!

**Comment by rubyFeedback** [comment]
I run into the same issue on linux.

I compiled openmpi into /usr hierarchy.

https://download.open-mpi.org/release/open-mpi/v4.0/openmpi-4.0.0.tar.bz2

Perhaps it is a version problem?

If possible, perhaps the cmake check could report which version of openmpi should be used.

I will try with an older openmpi next.

**Comment by arohou** [comment]
[Homebrew installation](https://github.com/3dem/relion/issues/913#issuecomment-1331554056)
