### ISSUE TITLE
Question about code reading

### ISSUE THREAD

**Issue by AmazonRF** [3dem/relion#496]
Hi,

Excellent work. I try to read the code and want to know how this nice project works. Could you please recommend me some points to get start?  If possible, I am eager to know the structure of the coding.

Thanks a lot. 

Sincerely,
AmazonRF

**Comment by biochem-fan** [comment]
What exactly do you want to learn? Please ask more specific questions.

Have you already studied the theories described in the JMB papers?

**Comment by AmazonRF** [comment]
Thanks your answer and telling me what to do for first step!
I just start reading the 'Optimal Determination of Particle Orientation,...'. So much I have to learn, I just understand what the Guinier is. Could you please recommend me some book about the theory in paper ? I read some material about X-ray but the knowledge I got is in pieces.
I want to learn how the RELION work, I am using RELION3 to deal with some subtomo data. I feel nervous when I use a software which is a black box to me. I have enough time and enjoy learning more about RELION so that I try to read RELION from step to step. I am a undergraduate student major in condensed matter physics.

Sincerely,
AmazonRF

At 2019-08-10 16:02:28, "biochem_fan" <notifications@github.com> wrote:


What exactly do you want to learn? Please ask more specific questions.

Have you already studied the theories described in the JMB papers?

**Comment by biochem-fan** [comment]
If you are new to electron microscopy, I recommend you to first learn physical basis of imaging.

http://cryo-em-course.caltech.edu/videos provides nice introductory lecture videos.
https://em-learning.com/ has more.
https://www2.mrc-lmb.cam.ac.uk/research/scientific-training/electron-microscopy/ is also good.

Then study the algorithms implemented in RELION:
 -  Scheres (2012) J. Mol. Biol. (PMID: 22100448)	 
 -  Scheres (2012) J. Struct. Biol. (PMID: 23000701)	 

Relevant codes are `ml_optimier.cpp` and `ml_model.cpp` under `src` directory. But they are extremely complicated.

Better place to start would be `src/app/project.cpp` and `src/app/reconstruct.cpp`. Here you can learn how 2D images can be generated by projecting a 3D reference volumes and vice versa.

> I feel nervous when I use a software which is a black box to me

This is a very good attitude :)

**Comment by AmazonRF** [comment]
Thanks so much for the information!

**Comment by AmazonRF** [comment]
Hi,
   I am the undergraduate student who are interested in how RELION work and wrote a issure to ask for help in the summer. I keep learning the algorithm behind the CryoEM and find that I love it!
   From the paper, I notice that you use the semi-automatic picking particles which based on template matching. From my learning I know that cross-correlation couldn't work will on rotated template. I try to use polar coordinates to transform the rotate issure to the translation one. But because of the center, the angle shows huge difference between template and image. Then I try to use "template bank" which including series of angle of template to find the nearest one and then create another bank with precise angle. But in some case, it can show mistakes in the first generation( I think the reason is the step is big). May I ask for the detail of the template matching in RELION ?
   Thanks a lot! 
   (All the video you recommend I have already finished watching.) If possible, can I ask for further learning materials? I am a Junior student major in condensed matter physics.


Best wishes,
Yifei
*************************************

Yifei Chen

Xi'an Jiaotong University
Tel: (+86) 13629295515
pro2biophy@gmail.com
yifeichen_arf@163.com
amazonrf@163.com



At 2019-08-10 16:02:28, "biochem_fan" <notifications@github.com> wrote:


What exactly do you want to learn? Please ask more specific questions.

Have you already studied the theories described in the JMB papers?

**Comment by biochem-fan** [comment]
RELION's template-based autopicker generates many rotated copies of a template (by default every 5 degrees) and match them against a micrograph. We don't need `another bank with precise angle` because in-plane rotation is refined later in the Class2D/3D or Refine3D step.

See https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4318617/ for the details.

**Comment by AmazonRF** [comment]
Thanks a lot for your quick reply! :) I am going to read it!

At 2019-12-16 22:56:38, "biochem_fan" <notifications@github.com> wrote:


RELION's template-based autopicker generates many rotated copies of a template (by default every 5 degrees) and match them against a micrograph. We don't need another bank with precise angle because in-plane rotation is refined later in the Class2D/3D or Refine3D step.

See https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4318617/ for the details.

**Comment by AmazonRF** [comment]
Hi,


    I am that undergraduate student who is interested in how RELION works. I feel confused about the .mrc file's header. When I find its meaning from the tutorial, I failed to figure out what the formation of the files and what these headers exactly means. May I ask for the information about the meaning of those headers? Thanks a lot.


    Wish you a happy new year!


bests,
Yifei
******************************************************************
Yifei Chen

Xi'an Jiaotong University
Tel: (+86) 13629295515
pro2biophy@gmail.com
yifeichen_arf@163.com
amazonrf@163.com









At 2019-12-16 22:49:37, "AmazonRF" <amazonrf@163.com> wrote:




Hi,
   I am the undergraduate student who are interested in how RELION work and wrote a issure to ask for help in the summer. I keep learning the algorithm behind the CryoEM and find that I love it!
   From the paper, I notice that you use the semi-automatic picking particles which based on template matching. From my learning I know that cross-correlation couldn't work will on rotated template. I try to use polar coordinates to transform the rotate issure to the translation one. But because of the center, the angle shows huge difference between template and image. Then I try to use "template bank" which including series of angle of template to find the nearest one and then create another bank with precise angle. But in some case, it can show mistakes in the first generation( I think the reason is the step is big). May I ask for the detail of the template matching in RELION ?
   Thanks a lot! 
   (All the video you recommend I have already finished watching.) If possible, can I ask for further learning materials? I am a Junior student major in condensed matter physics.


Best wishes,
Yifei
*************************************

Yifei Chen

Xi'an Jiaotong University
Tel: (+86) 13629295515
pro2biophy@gmail.com
yifeichen_arf@163.com
amazonrf@163.com



At 2019-08-10 16:02:28, "biochem_fan" <notifications@github.com> wrote:


What exactly do you want to learn? Please ask more specific questions.

Have you already studied the theories described in the JMB papers?

**Comment by biochem-fan** [comment]
Did you look at https://www.ccpem.ac.uk/mrc_format/mrc2000.php?

There are many fields but most important for RELION are the image size (NX, NY, NZ) and MODE (8 bit integer? 32 bit float? etc). The data follows the header as a 3D array.
