### ISSUE TITLE
Help needed for Gctf issue

### ISSUE THREAD

**Issue by Felix931** [3dem/relion#498]
Hi, I am new to Linux and Relion, and currently going through the Relion 3 tutorial by Dr. Scheres. When running the CTF estimation, I received the following error: 

**Did not find any of the expected EPS files to generate a PDF file + Will make an empty PDF-file in CtfFind/job003/logfile.pdf**

This is likely due to Gctf is not present in my system as the default path in the 'Gctf executable:' (in the 'Gctf' tab of Relion) **/public/EM/Gctf/bin/Gctf** is non-existent and no Gctf or Ctf files are present in my system. 

In an attempt to address this, I obtained the Gctf v1.06 tar file from Kai Zhang's repository, extracted them and used the directory for the 'Gctf executable:' but the same error occurred. Also did the same using Ctffind-4.1 downloaded from repository but didn't solve the problem. Extra info: Cuda v10; gs (but not Gctf) is present in /usr/bin

Please advise what can be done here with terminal scripts (if any) to resolve the issue? Thanks.

**Comment by biochem-fan** [comment]
> used the directory for the 'Gctf executable:'

You have to specify the path to the GCTF or CTFFIND executables, not the path to the directory.

**Comment by Felix931** [comment]
Thanks for the reply. Yes, I have specified the path to GCTF or CTFFIND executables e.g. **../Public/EM/Gctf/bin/Gctf-v1.06_sm_20_cu8.0_x86_64** or **../Public/EM/ctffind/ctffind-4.1.13-linux64** but the same error occurred. 

I noticed that the available GCTF executables from Kai Zhang's repository support up to Cuda v8 such as: 
**Gctf-v1.06_sm_30_cu8.0_x86_64
Gctf-v1.06_sm_20_cu8.0_x86_64
Gctf-v1.06_sm_20_cu7.5_x86_64
Gctf-v1.06_sm_20_cu7.0_x86_64**

I've tried all the above but the same error. My Cuda is v10, is that causing the issue and should I downgrade Cuda to v8? I'm not sure if downgrading Cuda would mess up subsequent Relion analyses. 

Finally, after successfully installing Relion, my system did not have any GCTF (or CTFFIND) executables until I downloaded them manually online; is that normal?

**Comment by biochem-fan** [comment]
I cannot support GCTF specific issues. Did you try CTFFIND 4.1.x?

> my system did not have any GCTF (or CTFFIND) executables until I downloaded them manually online; is that normal?

Yes, these programs must be obtained separately.

**Comment by m-shred** [comment]
Hi, I've been experiencing the same problem where no EPS files are found and no output is created in my star files after using either gctf or ctffind. I also have cuda v10 installed and wonder if it possible to use either CTFFind4 or Gctf with cuda v10? Or do I need to somehow install cuda v8 as well? 
Thanks

**Comment by biochem-fan** [comment]
Please use CTFFIND 4.1.x. It does not use CUDA.

**Comment by m-shred** [comment]
Hi, this problem is persisting despite using CTFFIND 4.1.13 (after compiling and installing it without any error messages). Do you know what else could be the cause?

**Comment by biochem-fan** [comment]
Does your system have `csh`?

**Comment by m-shred** [comment]
yes, it does
`$ csh --version
tcsh 6.20.00 (Astron) 2016-11-24 (x86_64-unknown-linux) options wide,nls,dl,al,kan,sm,rh,color,filec
$ which csh
/usr/bin/csh`

**Comment by cuncunqiao** [comment]
I met the same problem. using GCTF always triggers the error, but CTFFIND4 works well. Could CTFFind4.1 support tilting the grid? I want to process the data which was collected from the tilted grid (30 degrees).

**Comment by biochem-fan** [comment]
You need GOCTF, a derivative from CTFFIND4.

Unfortunately, CTF estimation of tilted images is not supported from RELION GUI (even with Gctf or GOCTF). For 30 deg of tilt, you can simply estimate defocus globally and then repeat CtfRefine. See the hemagglutinin example in our eLife paper.
