### ISSUE TITLE
CtfFind bug

### ISSUE THREAD

**Issue by wimhagen** [3dem/relion#508]
Relion 3.07:
CtfFind job using CTFFIND 4.1.
Job starts but gives no time left and takes forever:

 Estimating CTF parameters using Niko Grigorieff's CTFFIND ...
000/??? sec ~~(,_,">                                                          [oo]

Turns out I accidentally set a pixel size of 0,=.52015. This did not trigger any error.

Best,

Wim

**Comment by biochem-fan** [comment]
We cannot add checks for all sort of user mistakes but a01ec78 ensures the pixel size and the voltage are positive during Import.
