### ISSUE TITLE
MPI_C error with install

### ISSUE THREAD

**Issue by evanseitz** [3dem/relion#509]
I'm following the guide at `https://www3.mrc-lmb.cam.ac.uk/relion//index.php?title=Download_%26_install` and am currently at the step `cmake ..`

However, I'm getting this error:

```
cmake ..
-- BUILD TYPE set to the default type:  'Release'
-- Setting fallback CUDA_ARCH=35
-- CUDA enabled - Building CUDA-accelerated version of RELION
-- Setting cpu precision to double
-- Setting accelerated code precision to single
CUDA_TOOLKIT_ROOT_DIR not found or specified
-- Could NOT find CUDA (missing: CUDA_TOOLKIT_ROOT_DIR CUDA_NVCC_EXECUTABLE CUDA_INCLUDE_DIRS CUDA_CUDART_LIBRARY) 
-- Using non-cuda compilation....
-- Found MPI_C: /home/user/anaconda3/envs/ManifoldEM/lib/libmpi.so (found version "3.1") 
-- Could NOT find MPI_CXX (missing: MPI_CXX_WORKS) 
CMake Error at /usr/local/share/cmake-3.12/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find MPI (missing: MPI_CXX_FOUND) (found version "3.1")
Call Stack (most recent call first):
  /usr/local/share/cmake-3.12/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/share/cmake-3.12/Modules/FindMPI.cmake:1666 (find_package_handle_standard_args)
  CMakeLists.txt:204 (find_package)

-- Configuring incomplete, errors occurred!
```

Using `cmake --version`, I'm using 3.12.3. Any help would be greatly appreciated.

**Comment by biochem-fan** [comment]
Your `cmake` is picking up MPI that comes with ManifoldEM. Does it contain compilers or only runtime? I recommend you to use OpenMPI provided by the system (or cluster administrator), or one installed by yourself. To do this, you typically need to avoid enabling ManifoldEM's conda environment when compiling and using RELION.

**Comment by evanseitz** [comment]
Okay, thank you. I've deactivated all conda environments, but a similar error persists:

```
cmake ..
-- BUILD TYPE set to the default type:  'Release'
-- Setting fallback CUDA_ARCH=35
-- CUDA enabled - Building CUDA-accelerated version of RELION
-- Setting cpu precision to double
-- Setting accelerated code precision to single
CUDA_TOOLKIT_ROOT_DIR not found or specified
-- Could NOT find CUDA (missing: CUDA_TOOLKIT_ROOT_DIR CUDA_NVCC_EXECUTABLE CUDA_INCLUDE_DIRS CUDA_CUDART_LIBRARY) 
-- Using non-cuda compilation....
-- Could NOT find MPI_C (missing: MPI_C_LIB_NAMES MPI_C_HEADER_DIR MPI_C_WORKS) 
-- Could NOT find MPI_CXX (missing: MPI_CXX_LIB_NAMES MPI_CXX_HEADER_DIR MPI_CXX_WORKS) 
CMake Error at /usr/local/share/cmake-3.12/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find MPI (missing: MPI_C_FOUND MPI_CXX_FOUND)
Call Stack (most recent call first):
  /usr/local/share/cmake-3.12/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/share/cmake-3.12/Modules/FindMPI.cmake:1666 (find_package_handle_standard_args)
  CMakeLists.txt:204 (find_package)

-- Configuring incomplete, errors occurred!
```

**Comment by biochem-fan** [comment]
What does `which mpic` say?

If this is your own computer, you can install OpenMPI from the OS's package manager. Otherwise, install it under your home directory and set `PATH` and `LD_LIBRARY_PATH` accordingly.

**Comment by evanseitz** [comment]
Okay, I've installed via `yum install openmpi` without error, but `which mpic` gives:
`/usr/bin/which: no mpic in (/home/ees2192/anaconda3/condabin:/usr/lib64/qt-3.3/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin:/var/lib/snapd/snap/bin:/home/ees2192/.local/bin:/home/ees2192/bin)`
even though I'm not running in anaconda 3 base or any environment.

I'm researching paths now via `https://stackoverflow.com/questions/36091579/cmake-set-path-to-mpi-headers-and-binaries-manually`

**Comment by evanseitz** [comment]
Okay, so I've installed MPI via `yum install openmpi` and `yum install openmpi-devel` and added the path (via `which mpicc`; note: not `which mpic`) to both `PATH` and `LD_LIBRARY_PATH` in `.bashrc`:
```
export PATH=$PATH:/usr/lib/openmpi/bin
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib/openmpi/bin
```
Following this, I read that cmake needs to be downgraded to 3.9.6 to avoid this error (https://gitlab.kitware.com/cmake/cmake/issues/18570) which then requires the `tar.gz` here (for linux): https://cmake.org/files/v3.9/ ...with instructions on how to install in the readme

Then I found out that this version of cmake actually requires `gcc` to be upgraded for it to function (https://gitlab.kitware.com/cmake/cmake/issues/18570)... and this can be done via https://stackoverflow.com/questions/47175706/how-to-install-gcc-4-9-2-on-rhel-7-4:
```
yum install centos-release-scl-rh
yum install devtoolset-3-gcc devtoolset-3-gcc-c++
update-alternatives --install /usr/bin/gcc-4.9 gcc-4.9 /opt/rh/devtoolset-3/root/usr/bin/gcc 10
update-alternatives --install /usr/bin/g++-4.9 g++-4.9 /opt/rh/devtoolset-3/root/usr/bin/g++ 10
source scl_source enable devtoolset-3
```
and possible ccache needs to be explicitly installed as well: `sudo yum install ccache -y`, but I'm not sure but did so any way.

So finally, I run `cmake ..` specifically using cmake 3.9.6 and get the following error:
```
-- BUILD TYPE set to the default type:  'Release'
-- Setting fallback CUDA_ARCH=35
-- CUDA enabled - Building CUDA-accelerated version of RELION
-- Setting cpu precision to double
-- Setting accelerated code precision to single
CUDA_TOOLKIT_ROOT_DIR not found or specified
-- Could NOT find CUDA (missing: CUDA_TOOLKIT_ROOT_DIR CUDA_NVCC_EXECUTABLE CUDA_INCLUDE_DIRS CUDA_CUDART_LIBRARY) 
-- Using non-cuda compilation....
-- Unable to determine MPI from MPI driver /usr/lib64/openmpi/bin/mpirun
CMake Error at /home/ees2192/share/cmake-3.9/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find MPI_C (missing: MPI_C_LIBRARIES MPI_C_INCLUDE_PATH)
Call Stack (most recent call first):
  /home/ees2192/share/cmake-3.9/Modules/FindPackageHandleStandardArgs.cmake:377 (_FPHSA_FAILURE_MESSAGE)
  /home/ees2192/share/cmake-3.9/Modules/FindMPI.cmake:640 (find_package_handle_standard_args)
  CMakeLists.txt:204 (find_package)
```

...which is incredibly similar to the RELION topic here (centOS and all):
https://github.com/3dem/relion/issues/55

However this is for relion2 - I need to know which lines correspond to "lines 169 and 171" in the latest release. Do you have any idea?

**Comment by bforsbe** [comment]
I don't want to be this default, but did you try rebooting your computer after all these changes?

**Comment by evanseitz** [comment]
@bforsbe just rebooted to make sure; still getting that same error.

**Comment by evanseitz** [comment]
@bforsbe if it helps, when I run `module avail`, I see:
```
mpi/openmpi-i386
mpi/openmpi-x86_64
```
I've tried running with each independently (via `module load ...`), but neither work.

**Comment by evanseitz** [comment]
Sadly still haven't been able to resolve this; @biochem-fan, do you have any leads?

**Comment by biochem-fan** [comment]
No. This is your environment specific issue and I cannot help any more.

**Comment by biochem-fan** [comment]
By the way, you can get pre-compiled RELION binary from CCPEM.

**Comment by evanseitz** [comment]
Okay, thank you. I'll look into that.

**Comment by evanseitz** [comment]
Thank you, that worked!

**Comment by Teige** [comment]
I solved a very similar problem with same errors failing to find an openmpi installation on CentOS 7 in the following way, in case it helps anyone. If you get to the point where you have the cmake error message 
"Could NOT find MPI_C (missing: MPI_C_LIBRARIES MPI_C_INCLUDE_PATH)" then you can give cmake the paths to the MPI compiler wrappers and include path as flags when you run cmake, my example below.

module load mpi (check with module list, module avail)
cd build
cmake -DMPI_C_COMPILER=/usr/lib64/openmpi/bin/mpicc  -DMPI_CXX_COMPILER=/usr/lib64/openmpi/bin/mpicxx  -DMPI_C_INCLUDE_PATH=/usr/include/openmpi-x86_64/ ..

N.B. the install guide at https://www3.mrc-lmb.cam.ac.uk/relion//index.php/Download_&_install explains that the MPI version used here should be the same version that you use when running things in relion (with mpirun). So, make sure that /usr/lib64/openmpi/bin/ and /usr/lib64/openmpi/lib (in my case) are in the path, or, the matching mpi module is loaded with module load.

**Comment by lyjzsyzlt** [comment]
> I solved a very similar problem with same errors failing to find an openmpi installation on CentOS 7 in the following way, in case it helps anyone. If you get to the point where you have the cmake error message
> "Could NOT find MPI_C (missing: MPI_C_LIBRARIES MPI_C_INCLUDE_PATH)" then you can give cmake the paths to the MPI compiler wrappers and include path as flags when you run cmake, my example below.
> 
> module load mpi (check with module list, module avail)
> cd build
> cmake -DMPI_C_COMPILER=/usr/lib64/openmpi/bin/mpicc -DMPI_CXX_COMPILER=/usr/lib64/openmpi/bin/mpicxx -DMPI_C_INCLUDE_PATH=/usr/include/openmpi-x86_64/ ..
> 
> N.B. the install guide at https://www3.mrc-lmb.cam.ac.uk/relion//index.php/Download_&_install explains that the MPI version used here should be the same version that you use when running things in relion (with mpirun). So, make sure that /usr/lib64/openmpi/bin/ and /usr/lib64/openmpi/lib (in my case) are in the path, or, the matching mpi module is loaded with module load.

thanks!!! This works for me!

**Comment by GTGJi** [comment]
After I ran the following codes on the https://sites.google.com/site/rangsiman1993/comp-env/program-install/install-openmpi, the it works. Although it took a long time to compile.

Installation on Local (in home) directory for user
Procedure is quite similar to installation with root/sudo.

1. Change directory to OpenMPI

cd openmpi-3.1.3

2. Set up configuration.

./configure --prefix="/$HOME/openmpi-3.1.3-local"

3. Compile OpenMPI

make

make install

4. Put the following commands into $HOME/.bashrc

export PATH="$PATH:/$HOME/openmpi-3.1.3-local/bin"

export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/$HOME/openmpi-3.1.3-local/lib/" 

5. Activate .bashrc file.

source /$HOME/.bashrc
