### ISSUE TITLE
relion_project --nr_uniform is not "uniform" (bug?)

### ISSUE THREAD

**Issue by evanseitz** [3dem/relion#510]
Hi, I've tried using the `relion_project --nr_uniform 800` command to get 800 angle-combinations from a "uniform angular distribution", but upon plotting these values, they don't appear uniform at all:
<img width="612" alt="RELION_UNIFORM" src="https://user-images.githubusercontent.com/35609503/65696138-bc1f2100-e046-11e9-9e32-9bcc97624e38.png">

As a counter-example, I then generated 812 points via the vertices of a tessellated sphere (icosahedron w/ 54 segments):
<img width="628" alt="TESS_UNIFORM" src="https://user-images.githubusercontent.com/35609503/65696115-b6c1d680-e046-11e9-9ad5-12a00e1fbec6.png">

[_proj812.txt](https://github.com/3dem/relion/files/3658188/_proj812.txt)

**Comment by bforsbe** [comment]
Uniform and regular is not the same thing. Orientations are generated by drawing a random tilt and rotation, each from a flat distribution. These values are random, and not evenly spaced. 

If you are referring to a non-uniform coverage of the random points across the surface of the sphere, you are correct; independent uniform distributions of the rot and tilt will not produce a completely uniform coverage.

**Comment by evanseitz** [comment]
Okay, thank you very much for clarifying. May I suggest a rewording in the `--help` argument: 
`--nr_uniform (-1) : OR get this many **random** samples from a uniform angular distribution

I'd also like to suggest a function that actually creates a "regular" distribution, but realize this is much for involved.

**Comment by biochem-fan** [comment]
Thanks for suggestion. I updated the message in RELION 3.1.
