### ISSUE TITLE
problem with relion_run_motioncorr

### ISSUE THREAD

**Issue by electronimus** [3dem/relion#512]
Hi... I apologize if someone has already posted about this... anyway, I am having the problem that relion_run_motioncorr is adding an underscore in the filenames, and then it cannot read its own output. The error message is

ERROR: 
Image::openFile cannot open: MotionCorr/job028/_/Micrographs/proteasome_100_Aug14_23_40_49.mrc

If the "/_" did not exist, everything would be fine. Does anyone know how to fix this problem? It sounds trivial, but relion_run_motioncorr is a binary file.

**Comment by biochem-fan** [comment]
This problem is fixed in 3.1 (we will start beta testing in few days).

When importing movies, please avoid `./` at the beginning of the path. If you use symbolic links to files outside the project directory, please use absolute paths.
