### ISSUE TITLE
--class flag for relion_reconstruct? [Feature request]

### ISSUE THREAD

**Issue by olibclarke** [3dem/relion#513]
Hi,

When performing a masked classification, I often want to reconstruct volumes of each class without masking in order to inspect correlated changes elsewhere in the molecule. Currently, this is a little tedious to do for many classes, as one needs to create a subset selection for each class of interest and perform reconstruction for each.

`relion_reconstruct` currently has an option to reconstruct a half-set, based on the `rln_RandomSubset` column. Would it be possible to add a similar flag, but which looks at the class number, to allow easy reconstruction of an individual class from a data.star that has multiple classes present?

Cheers
Oli

**Comment by biochem-fan** [comment]
Done in 3.1.
