### ISSUE TITLE
Minor UI bugs in CTFrefine [3.1]

### ISSUE THREAD

**Issue by olibclarke** [3dem/relion#517]
Hi,

Loving the 3.1 beta so far, great work!! Couple of minor UI bugs in Ctfrefine (I think):

If the user selects in to refine anisotropic magnification, all the CTF fitting options are then grayed out (as expected). However, if "fit CTF parameters" was already set to Yes, relion gives an error that refining anisotropic magnification cannot be performed in conjunction with fitting other CTF params (even though these options are grayed out and presumably ignored). 

Also, when opening a relion 3.0 project, if I select a previously run CTFrefine job, it now does not show the correct, original parameters in the GUI. It shows anisotropic magnification refinement "Yes", and everything else "No", no matter what parameters the job was originally run with (beam tilt, defocus, etc).

Cheers
Oli

**Comment by biochem-fan** [comment]
Thanks for feedback. I will try to fix the first issue. The second issue will not fixed (there are many cases like this in the GUI and repair is not easy).

**Comment by biochem-fan** [comment]
Fixed the first issue.
