### ISSUE TITLE
Minor issue with --random_seed warning

### ISSUE THREAD

**Issue by rdrighetto** [3dem/relion#518]
Hi,

In 3.1-beta, commit b86482c458d88425594a7b1eab0709ca21f487c1, I am getting the following message in `stderr`:

```
The following warnings were encountered upon command-line parsing:
WARNING: Option --random_seed   is not a valid RELION argument
```

even though the option still shows up when calling `relion_refine` with no arguments and the job is indeed using the `--random_seed` that I specified, as verified from the `_optimiser.star` file.

Hopefully harmless but you may want to look into it.

Thanks!

**Comment by biochem-fan** [comment]
Aren't you continuing a job? The option is not valid when continuing.

**Comment by rdrighetto** [comment]
Right, I am continuing a job. Thanks for the heads up. I understand why the option is invalid in this case, but the current warning message is misleading.
