### ISSUE TITLE
Switch to on-the-fly shifts for particle movie alignment

### ISSUE THREAD

**Issue by bforsbe** [3dem/relion#52]
Originally reported by: **Dimitry Tegunov (Bitbucket: [DTegunov](https://bitbucket.org/DTegunov), GitHub: [DTegunov](https://github.com/DTegunov))**

----------------------------------------

When doing particle movie alignment without rotational searches, turning on --onthefly_shifts will make things a lot faster, unless IO is the performance bottleneck. It will also lower the memory requirements dramatically. Could it be turned on automatically in case of --realign_movie_frames and --skip_rotate?

----------------------------------------
- Bitbucket: https://bitbucket.org/tcblab/relion2-beta/issue/52

**Comment by biochem-fan** [comment]
Old movie refinement is no longer relevant.
