### ISSUE TITLE
relion_display --lowpass fails for non STAR input

### ISSUE THREAD

**Issue by biochem-fan** [3dem/relion#523]
Reported in CCPEM by @olibclarke: https://www.jiscmail.ac.uk/cgi-bin/webadmin?A2=ind1910&L=CCPEM&O=D&P=107614

This happens in `basisViewerCanvas::fill` because obsModel is empty.

**Comment by biochem-fan** [comment]
Fixed by the above commit.

**Comment by olibclarke** [comment]
Great, thanks for the quick fix Takanori!
