### ISSUE TITLE
RELION 3.1 dies when not all particles can be copied to scratch

### ISSUE THREAD

**Issue by biochem-fan** [3dem/relion#529]
See https://www.jiscmail.ac.uk/cgi-bin/webadmin?A2=ind1910&L=CCPEM&O=D&P=167855

**Comment by h-ehara** [comment]
I hope this would be helpful, but similar problems repeatedly occur with relion-3.0.X in our environment.

Example:
Warning: scratch space full on g03.em.local. Remaining 1727622 particles will be read from where they were.
 Warning: scratch space full on g03.em.local. Remaining 1727622 particles will be read from where they were.
 Warning: scratch space full on g03.em.local. Remaining 1727622 particles will be read from where they were.
 Warning: scratch space full on g03.em.local. Remaining 1727622 particles will be read from where they were.
in: /Appl/src/relion/src/rwMRC.h, line 191
slave 4 encountered error: === Backtrace  ===
/Appl/relion-3.0.4/bin/relion_refine_mpi(_ZN11RelionErrorC1ERKSsS1_l+0x41) [0x447251]
/Appl/relion-3.0.4/bin/relion_refine_mpi(_ZN5ImageIdE7readMRCElbRK8FileName+0xaaa) [0x48915a]
/Appl/relion-3.0.4/bin/relion_refine_mpi(_ZN5ImageIdE5_readERK8FileNameR13fImageHandlerblbb+0x2bb) [0x48a19b]
/Appl/relion-3.0.4/bin/relion_refine_mpi(_ZN11MlOptimiser24expectationSomeParticlesEll+0x772) [0x5ddec2]
/Appl/relion-3.0.4/bin/relion_refine_mpi(_ZN14MlOptimiserMpi11expectationEv+0x230e) [0x469b3e]
/Appl/relion-3.0.4/bin/relion_refine_mpi(_ZN14MlOptimiserMpi7iterateEv+0xaa) [0x47742a]
/Appl/relion-3.0.4/bin/relion_refine_mpi(main+0x69) [0x432349]
/lib64/libc.so.6(__libc_start_main+0xf5) [0x7f1a049a43d5]
/Appl/relion-3.0.4/bin/relion_refine_mpi() [0x43475f]
==================
ERROR:
readMRC: Image number 1551956 exceeds stack size 492131 of image 1551956@/scratch/katsurak/relion_volatile/particles.mrcs
in: /Appl/src/relion/src/rwMRC.h, line 191
slave 1 encountered error: === Backtrace  ===
/Appl/relion-3.0.4/bin/relion_refine_mpi(_ZN11RelionErrorC1ERKSsS1_l+0x41) [0x447251]
/Appl/relion-3.0.4/bin/relion_refine_mpi(_ZN5ImageIdE7readMRCElbRK8FileName+0xaaa) [0x48915a]
/Appl/relion-3.0.4/bin/relion_refine_mpi(_ZN5ImageIdE5_readERK8FileNameR13fImageHandlerblbb+0x2bb) [0x48a19b]
/Appl/relion-3.0.4/bin/relion_refine_mpi(_ZN11MlOptimiser24expectationSomeParticlesEll+0x772) [0x5ddec2]
/Appl/relion-3.0.4/bin/relion_refine_mpi(_ZN14MlOptimiserMpi11expectationEv+0x230e) [0x469b3e]
/Appl/relion-3.0.4/bin/relion_refine_mpi(_ZN14MlOptimiserMpi7iterateEv+0xaa) [0x47742a]
/Appl/relion-3.0.4/bin/relion_refine_mpi(main+0x69) [0x432349]
/lib64/libc.so.6(__libc_start_main+0xf5) [0x7fde74fc33d5]
/Appl/relion-3.0.4/bin/relion_refine_mpi() [0x43475f]
==================
ERROR:
readMRC: Image number 667115 exceeds stack size 492131 of image 667115@/scratch/katsurak/relion_volatile/particles.mrcs
in: /Appl/src/relion/src/rwMRC.h, line 191
slave 3 encountered error: === Backtrace  ===
/Appl/relion-3.0.4/bin/relion_refine_mpi(_ZN11RelionErrorC1ERKSsS1_l+0x41) [0x447251]
/Appl/relion-3.0.4/bin/relion_refine_mpi(_ZN5ImageIdE7readMRCElbRK8FileName+0xaaa) [0x48915a]
/Appl/relion-3.0.4/bin/relion_refine_mpi(_ZN5ImageIdE5_readERK8FileNameR13fImageHandlerblbb+0x2bb) [0x48a19b]
/Appl/relion-3.0.4/bin/relion_refine_mpi(_ZN11MlOptimiser24expectationSomeParticlesEll+0x772) [0x5ddec2]
/Appl/relion-3.0.4/bin/relion_refine_mpi(_ZN14MlOptimiserMpi11expectationEv+0x230e) [0x469b3e]
/Appl/relion-3.0.4/bin/relion_refine_mpi(_ZN14MlOptimiserMpi7iterateEv+0xaa) [0x47742a]
/Appl/relion-3.0.4/bin/relion_refine_mpi(main+0x69) [0x432349]
/lib64/libc.so.6(__libc_start_main+0xf5) [0x7f9490c3a3d5]
/Appl/relion-3.0.4/bin/relion_refine_mpi() [0x43475f]
==================
ERROR:
readMRC: Image number 1549735 exceeds stack size 492131 of image 1549735@/scratch/katsurak/relion_volatile/particles.mrcs
in: /Appl/src/relion/src/rwMRC.h, line 191
slave 2 encountered error: === Backtrace  ===
/Appl/relion-3.0.4/bin/relion_refine_mpi(_ZN11RelionErrorC1ERKSsS1_l+0x41) [0x447251]
/Appl/relion-3.0.4/bin/relion_refine_mpi(_ZN5ImageIdE7readMRCElbRK8FileName+0xaaa) [0x48915a]
/Appl/relion-3.0.4/bin/relion_refine_mpi(_ZN5ImageIdE5_readERK8FileNameR13fImageHandlerblbb+0x2bb) [0x48a19b]
/Appl/relion-3.0.4/bin/relion_refine_mpi(_ZN11MlOptimiser24expectationSomeParticlesEll+0x772) [0x5ddec2]
/Appl/relion-3.0.4/bin/relion_refine_mpi(_ZN14MlOptimiserMpi11expectationEv+0x230e) [0x469b3e]
/Appl/relion-3.0.4/bin/relion_refine_mpi(_ZN14MlOptimiserMpi7iterateEv+0xaa) [0x47742a]
/Appl/relion-3.0.4/bin/relion_refine_mpi(main+0x69) [0x432349]
/lib64/libc.so.6(__libc_start_main+0xf5) [0x7f9d1c5e63d5]
/Appl/relion-3.0.4/bin/relion_refine_mpi() [0x43475f]
==================
ERROR:
readMRC: Image number 1528821 exceeds stack size 492131 of image 1528821@/scratch/katsurak/relion_volatile/particles.mrcs
[g03.em.local:32307] 3 more processes have sent help message help-mpi-api.txt / mpi-abort
[g03.em.local:32307] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages

**Comment by biochem-fan** [comment]
It seems this happens in the MPI version only. Debuggging...

**Comment by biochem-fan** [comment]
Fixed. Internally testing within LMB; after making sure this is OK, I will push it here.

**Comment by biochem-fan** [comment]
FYI: @olibclarke

**Comment by biochem-fan** [comment]
Fixed in f8a215d.
