### ISSUE TITLE
(3.1-beta) Reverting from subtracted particles with re-windowing

### ISSUE THREAD

**Issue by h-ehara** [3dem/relion#531]
Issue:
2D/3D classifications produce very strange results (with many ripples) when using star files created with the "revert to original particles" function, which were done after particle subtraction with re-windowing.

Possible causes:
I just thought it might be helpful to revert _rlnImageSize values in the optics section, when using the "revert to original particles" function.
(Is it enough to manually edit the _rlnImageSize column for solving the problem?)

3.1-780dd7

Thank you always for your kind support.

**Comment by biochem-fan** [comment]
> Is it enough to manually edit the _rlnImageSize column for solving the problem?

Yes. I will implement this.

**Comment by biochem-fan** [comment]
Fixed by commit 95dfc62c. I will push this soon.
