### ISSUE TITLE
Particle subtraction not working properly with sub-tomograms

### ISSUE THREAD

**Issue by xueliang4906** [3dem/relion#532]
This is a template for asking questions and reporting bugs. Please fill in as much information as you can.

**Describe your problem**

I am a PhD student at EMBL and doing sub-tomogram averaging with the new Relion 3.1.0. Refine3D worked well and I plan to do particle subtraction after that. I select the .optimizer file of the refine3d job, give it a mask and leave everything else as default setting. The Subtraction job run through without showing any error but when I checked the "particles", there are only 4433 particles exist, instead of 8290 particles in the input star file. When I checked the star file writtenafter subtraction, there are 8290 particles but some are duplicates.  

Thanks, Liang

**Environment:**
 - RELION version [e.g. /g/easybuild/x86_64/CentOS/7/haswell/software/RELION_core/3.1.0-beta-20191025_02_13869ee_a-foss-2018b-cu100/bin/relion] 
 - Memory: [e.g. 128 GB]
 

**Dataset:**
 - Box size: [e.g. 120 px]
 - Pixel size: [e.g. 1.7005 Å/px]
 - Number of particles: [e.g. 8290]
 - Description: [e.g. ribosomal sub-volumes]

**Job options:**
 - Type of job: [e.g. Subtract]
 - Number of MPI processes: [e.g. 3]
 - Number of threads: [e.g. 7]
 - Full command (see `note.txt` in the job directory):
   ```
`which relion_particle_subtract_mpi` --i Refine3D/job004_puppy/run_it025_optimiser.star --mask ../mask.mrc --o Subtract/job014/ --recenter_on_mask --pipeline_control Subtract/job014/
   ```
The snapshot is from the particle_subtracted star file. After 4433, the naming sequence went back back to 1. 
![image](https://user-images.githubusercontent.com/32864028/67713253-c32eab80-f9c5-11e9-8e01-a6894168264a.png)

**Comment by biochem-fan** [comment]
I found what is wrong. Trying to fix now.

**Comment by biochem-fan** [comment]
Meanwhile, you should be able to run this by not using MPI.

**Comment by biochem-fan** [comment]
Fixed.
