### ISSUE TITLE
Help with upgrade from 3.0.5 to 3.1

### ISSUE THREAD

**Issue by krutru** [3dem/relion#539]
Hello,

I am running centos 7 with relion 3.0.5 and facing some issues installing relion 3.1.

I have used the following commands:
`sudo su
cd /usr/local/bin
git clone https://github.com/3dem/relion.git
cd relion
git checkout ver3.1
git pull
mkdir build
cd build
cmake -DCMAKE_INSTALL_PREFIX=/usr/local/bin/relion/3.1 -DCUDA=ON -DCudaTexture=ON ..
make -j4
sudo make install`

I have used the same steps previously and installs fine for 3.0.8. However for 3.1 I am getting the following error:

`Package xft was not found in the pkg-config search path
No package 'xft' found
package freetype2 was not found in the pkg-config path
No package 'freetype2' found`

Can anyone assist on how to install these to complete the relion 3.1 installation.

**Comment by biochem-fan** [comment]
I don't know why RELION is asking for `xft` and `freetype2`, but you might try installing `libxft-devel` and ` freetype2-devel` packages.

**Comment by krutru** [comment]
Thanks for your help. I installed libXft-devel and there is no freetype2-devel so i tried:

`yum install freetype`

which actually upgraded to `Package freetype-2.8-14.el7.x86_64`

I also had to install libjpeg-devel and then finally make -j4 and make install worked.

I am now seeing this error when I run relion command:

`[relion@host-1~]$ relion
in: /usr/local/bin/relion/src/filename.cpp, line 477
ERROR:
Filename::touch ERROR: Cannot open file: .pipeline_has_changed
=== Backtrace  ===
relion(_ZN11RelionErrorC1ERKSsS1_l+0x41) [0x47e4d1]
relion(_Z5touchRK8FileName+0x251) [0x55be91]
relion(_ZN8PipeLine5writeEb8FileNameSt6vectorIbSaIbEES3_+0xee4) [0x502104]
relion(_ZN13GuiMainWindowC2EiiPKc8FileNameS2_iib+0x53c) [0x59a85c]
relion(main+0x67f) [0x4256af]
/lib64/libc.so.6(__libc_start_main+0xf5) [0x7feddfa7b445]
relion() [0x42915e]
==================
ERROR:
Filename::touch ERROR: Cannot open file: .pipeline_has_changed
`
