### ISSUE TITLE
Relion 3.1b installation problem

### ISSUE THREAD

**Issue by zruan** [3dem/relion#540]
Hi Relion developers,

I'm trying to install relion3.1b in CentOS 7, but I'm running into a problem when "Linking CXX executable ../../bin/relion_refine_mpi".

Here is the system configuration during cmake:

/primary/vari/software/cmake/cmake-3.8.0-Linux-x86_64/bin/cmake ../ -DCMAKE_INSTALL_PREFIX=/home/zheng.ruan/lu-secondary/software/relion-3.1b 
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- BUILD TYPE set to the default type:  'Release'
-- Setting fallback CUDA_ARCH=35
-- CUDA enabled - Building CUDA-accelerated version of RELION
-- Setting cpu precision to double
-- Setting accelerated code precision to single
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found CUDA: /cm/shared/apps/cuda80/toolkit/8.0.44 (found version "8.0") 
-- Using cuda wrapper to compile....
-- Cuda version is >= 7.5 and single-precision build, enable double usage warning.
-- Found MPI_C: /cm/shared/apps/mpich/ge/gcc/64/3.1.4/lib/libmpi.so  
-- Found MPI_CXX: /cm/shared/apps/mpich/ge/gcc/64/3.1.4/lib/libmpicxx.so;/cm/shared/apps/mpich/ge/gcc/64/3.1.4/lib/libmpi.so  
-- MPI_INCLUDE_PATH : /cm/shared/apps/gcc/current/include/c++/4.8.2/backward/backward_old;/cm/shared/apps/mpich/ge/gcc/64/3.1.4/include
-- MPI_LIBRARIES : /cm/shared/apps/mpich/ge/gcc/64/3.1.4/lib/libmpicxx.so;/cm/shared/apps/mpich/ge/gcc/64/3.1.4/lib/libmpi.so
-- MPI_CXX_INCLUDE_PATH : /cm/shared/apps/gcc/current/include/c++/4.8.2/backward/backward_old;/cm/shared/apps/mpich/ge/gcc/64/3.1.4/include
-- MPI_CXX_LIBRARIES : /cm/shared/apps/mpich/ge/gcc/64/3.1.4/lib/libmpicxx.so;/cm/shared/apps/mpich/ge/gcc/64/3.1.4/lib/libmpi.so
-- CMAKE_C_COMPILER : /usr/bin/cc
-- CMAKE_CXX_COMPILER : /usr/bin/c++
-- MPI_C_COMPILER : /cm/shared/apps/mpich/ge/gcc/64/3.1.4/bin/mpicc
-- MPI_CXX_COMPILER : /cm/shared/apps/mpich/ge/gcc/64/3.1.4/bin/mpicxx
-- CMAKE_CXX_COMPILER_ID : GNU
-- CMAKE_C_COMPILER : /cm/shared/apps/mpich/ge/gcc/64/3.1.4/bin/mpicc
-- CMAKE_CXX_COMPILER : /cm/shared/apps/mpich/ge/gcc/64/3.1.4/bin/mpicxx
-- MPI_C_COMPILER : /cm/shared/apps/mpich/ge/gcc/64/3.1.4/bin/mpicc
-- MPI_CXX_COMPILER : /cm/shared/apps/mpich/ge/gcc/64/3.1.4/bin/mpicxx
-- Looking for XOpenDisplay in /usr/lib64/libX11.so;/usr/lib64/libXext.so
-- Looking for XOpenDisplay in /usr/lib64/libX11.so;/usr/lib64/libXext.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Looking for IceConnectionNumber in ICE
-- Looking for IceConnectionNumber in ICE - found
-- Found X11: /usr/lib64/libX11.so
-- Could NOT find FLTK (missing:  FLTK_FLUID_EXECUTABLE) 
-- No FLTK installation was found
-- Found previously built non-system FLTK libraries that will be used.
-- FLTK_INCLUDE_DIR: /usr/include
-- FLTK_LIBRARIES:   /usr/lib64/libfltk_images.so;/usr/lib64/libfltk_forms.so;/usr/lib64/libfltk.so
-- Single-precision FFTW was required but NOT found
-- Double-precision FFTW was required but NOT found
-- Found previously built non-system single precision FFTW libraries that will be used.
-- Found previously built non-system double precision FFTW libraries that will be used.
-- Looking for sincos
-- Looking for sincos - found
-- Looking for __sincos
-- Looking for __sincos - not found
-- Found TIFF: /usr/lib64/libtiff.so (found version "4.0.3") 
-- Found ZLIB: /usr/lib64/libz.so (found version "1.2.7") 
-- Found PNG: /usr/lib64/libpng.so (found version "1.5.13") 
BUILD_SHARED_LIBS = OFF
-- Building static libs (larger build size and binaries)
Running apps/CMakeLists.txt...
-- CMAKE_BINARY_DIR:/home/zheng.ruan/lu-secondary/Zheng/software/relion-3.1b/relion/build_cuda80
-- Git commit ID: 9d75256d6f053b408a0c060dabb49ddbca631e89
TIFF FOUND
PNG FOUND
-- Try OpenMP C flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Try OpenMP CXX flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Found OpenMP: -fopenmp  
OPENMP FOUND
-- Configuring done
-- Generating done

Here is the error message when I type make:

[ 59%] Linking CXX executable ../../bin/relion_refine_mpi
../../lib/librelion_gpu_util.a(relion_gpu_util_generated_cuda_ml_optimiser.cu.o): In function `HandleError(cudaError, char const*, int)':
tmpxft_0000d2a3_00000000-4_cuda_ml_optimiser.cudafe1.cpp:(.text+0x9f): undefined reference to `RelionError::RelionError(std::string const&, std::string const&, long)'
../../lib/librelion_gpu_util.a(relion_gpu_util_generated_cuda_ml_optimiser.cu.o): In function `LaunchHandleError(cudaError, char const*, int)':
tmpxft_0000d2a3_00000000-4_cuda_ml_optimiser.cudafe1.cpp:(.text+0x1c7): undefined reference to `RelionError::RelionError(std::string const&, std::string const&, long)'
../../lib/librelion_gpu_util.a(relion_gpu_util_generated_cuda_ml_optimiser.cu.o): In function `LaunchHandleError(cudaError, char const*, int) [clone .constprop.526]':
tmpxft_0000d2a3_00000000-4_cuda_ml_optimiser.cudafe1.cpp:(.text+0x97d): undefined reference to `RelionError::RelionError(std::string const&, std::string const&, long)'
../../lib/librelion_gpu_util.a(relion_gpu_util_generated_cuda_ml_optimiser.cu.o): In function `Matrix1D<double>::resize(int) [clone .constprop.525]':
tmpxft_0000d2a3_00000000-4_cuda_ml_optimiser.cudafe1.cpp:(.text+0xb08): undefined reference to `RelionError::RelionError(std::string const&, std::string const&, long)'
../../lib/librelion_gpu_util.a(relion_gpu_util_generated_cuda_ml_optimiser.cu.o): In function `Matrix2D<double>::operator=(Matrix2D<double> const&) [clone .constprop.514]':
tmpxft_0000d2a3_00000000-4_cuda_ml_optimiser.cudafe1.cpp:(.text+0x12a0): undefined reference to `RelionError::RelionError(std::string const&, std::string const&, long)'
../../lib/librelion_gpu_util.a(relion_gpu_util_generated_cuda_ml_optimiser.cu.o):tmpxft_0000d2a3_00000000-4_cuda_ml_optimiser.cudafe1.cpp:(.text+0x2662): more undefined references to `RelionError::RelionError(std::string const&, std::string const&, long)' follow
../../lib/librelion_gpu_util.a(relion_gpu_util_generated_cuda_ml_optimiser.cu.o): In function `MultidimArray<double>::resize(long, long, long, long) [clone .constprop.524]':
tmpxft_0000d2a3_00000000-4_cuda_ml_optimiser.cudafe1.cpp:(.text+0x3332): undefined reference to `FileName::addExtension(std::string const&) const'
tmpxft_0000d2a3_00000000-4_cuda_ml_optimiser.cudafe1.cpp:(.text+0x345d): undefined reference to `RelionError::RelionError(std::string const&, std::string const&, long)'
tmpxft_0000d2a3_00000000-4_cuda_ml_optimiser.cudafe1.cpp:(.text+0x3529): undefined reference to `RelionError::RelionError(std::string const&, std::string const&, long)'
tmpxft_0000d2a3_00000000-4_cuda_ml_optimiser.cudafe1.cpp:(.text+0x35c1): undefined reference to `RelionError::RelionError(std::string const&, std::string const&, long)'
../../lib/librelion_gpu_util.a(relion_gpu_util_generated_cuda_ml_optimiser.cu.o): In function `MlDeviceBundle::setupFixedSizedObjects()':
tmpxft_0000d2a3_00000000-4_cuda_ml_optimiser.cudafe1.cpp:(.text+0x4273): undefined reference to `RelionError::RelionError(std::string const&, std::string const&, long)'
tmpxft_0000d2a3_00000000-4_cuda_ml_optimiser.cudafe1.cpp:(.text+0x430c): undefined reference to `RelionError::RelionError(std::string const&, std::string const&, long)'
../../lib/librelion_gpu_util.a(relion_gpu_util_generated_cuda_ml_optimiser.cu.o):tmpxft_0000d2a3_00000000-4_cuda_ml_optimiser.cudafe1.cpp:(.text+0x4d68): more undefined references to `RelionError::RelionError(std::string const&, std::string const&, long)' follow
../../lib/librelion_gpu_util.a(relion_gpu_util_generated_cuda_ml_optimiser.cu.o): In function `MultidimArray<float>::resizeNoCp(long, long, long, long)':
tmpxft_0000d2a3_00000000-4_cuda_ml_optimiser.cudafe1.cpp:(.text._ZN13MultidimArrayIfE10resizeNoCpEllll[_ZN13MultidimArrayIfE10resizeNoCpEllll]+0x256): undefined reference to `FileName::addExtension(std::string const&) const'
tmpxft_0000d2a3_00000000-4_cuda_ml_optimiser.cudafe1.cpp:(.text._ZN13MultidimArrayIfE10resizeNoCpEllll[_ZN13MultidimArrayIfE10resizeNoCpEllll]+0x370): undefined reference to `RelionError::RelionError(std::string const&, std::string const&, long)'
tmpxft_0000d2a3_00000000-4_cuda_ml_optimiser.cudafe1.cpp:(.text._ZN13MultidimArrayIfE10resizeNoCpEllll[_ZN13MultidimArrayIfE10resizeNoCpEllll]+0x440): undefined reference to `RelionError::RelionError(std::string const&, std::string const&, long)'
tmpxft_0000d2a3_00000000-4_cuda_ml_optimiser.cudafe1.cpp:(.text._ZN13MultidimArrayIfE10resizeNoCpEllll[_ZN13MultidimArrayIfE10resizeNoCpEllll]+0x534): undefined reference to `RelionError::RelionError(std::string const&, std::string const&, long)'
tmpxft_0000d2a3_00000000-4_cuda_ml_optimiser.cudafe1.cpp:(.text._ZN13MultidimArrayIfE10resizeNoCpEllll[_ZN13MultidimArrayIfE10resizeNoCpEllll]+0x683): undefined reference to `RelionError::RelionError(std::string const&, std::string const&, long)'
../../lib/librelion_gpu_util.a(relion_gpu_util_generated_cuda_ml_optimiser.cu.o): In function `unsigned long findThresholdIdxInCumulativeSum<float>(AccPtr<float>&, float)':
tmpxft_0000d2a3_00000000-4_cuda_ml_optimiser.cudafe1.cpp:(.text._Z31findThresholdIdxInCumulativeSumIfEmR6AccPtrIT_ES1_[_Z31findThresholdIdxInCumulativeSumIfEmR6AccPtrIT_ES1_]+0x408): undefined reference to `RelionError::RelionError(std::string const&, std::string const&, long)'
../../lib/librelion_gpu_util.a(relion_gpu_util_generated_cuda_ml_optimiser.cu.o):tmpxft_0000d2a3_00000000-4_cuda_ml_optimiser.cudafe1.cpp:(.text._ZNSt20__uninitialized_copyILb0EE13__uninit_copyIP8Matrix1DIdES4_EET0_T_S6_S5_[_ZNSt20__uninitialized_copyILb0EE13__uninit_copyIP8Matrix1DIdES4_EET0_T_S6_S5_]+0x17e): more undefined references to `RelionError::RelionError(std::string const&, std::string const&, long)' follow
../../lib/librelion_gpu_util.a(relion_gpu_util_generated_cuda_ml_optimiser.cu.o): In function `MultidimArray<bool>::resizeNoCp(long, long, long, long)':
tmpxft_0000d2a3_00000000-4_cuda_ml_optimiser.cudafe1.cpp:(.text._ZN13MultidimArrayIbE10resizeNoCpEllll[_ZN13MultidimArrayIbE10resizeNoCpEllll]+0x180): undefined reference to `FileName::addExtension(std::string const&) const'
tmpxft_0000d2a3_00000000-4_cuda_ml_optimiser.cudafe1.cpp:(.text._ZN13MultidimArrayIbE10resizeNoCpEllll[_ZN13MultidimArrayIbE10resizeNoCpEllll]+0x296): undefined reference to `RelionError::RelionError(std::string const&, std::string const&, long)'
tmpxft_0000d2a3_00000000-4_cuda_ml_optimiser.cudafe1.cpp:(.text._ZN13MultidimArrayIbE10resizeNoCpEllll[_ZN13MultidimArrayIbE10resizeNoCpEllll]+0x3f0): undefined reference to `RelionError::RelionError(std::string const&, std::string const&, long)'
tmpxft_0000d2a3_00000000-4_cuda_ml_optimiser.cudafe1.cpp:(.text._ZN13MultidimArrayIbE10resizeNoCpEllll[_ZN13MultidimArrayIbE10resizeNoCpEllll]+0x4c2): undefined reference to `RelionError::RelionError(std::string const&, std::string const&, long)'
tmpxft_0000d2a3_00000000-4_cuda_ml_optimiser.cudafe1.cpp:(.text._ZN13MultidimArrayIbE10resizeNoCpEllll[_ZN13MultidimArrayIbE10resizeNoCpEllll]+0x588): undefined reference to `RelionError::RelionError(std::string const&, std::string const&, long)'
../../lib/librelion_gpu_util.a(relion_gpu_util_generated_cuda_ml_optimiser.cu.o): In function `void getAllSquaredDifferencesCoarse<MlOptimiserCuda>(unsigned int, OptimisationParamters&, SamplingParameters&, MlOptimiser*, MlOptimiserCuda*, AccPtr<float>&, AccPtrFactory, int)':
tmpxft_0000d2a3_00000000-4_cuda_ml_optimiser.cudafe1.cpp:(.text._Z30getAllSquaredDifferencesCoarseI15MlOptimiserCudaEvjR21OptimisationParamtersR18SamplingParametersP11MlOptimiserPT_R6AccPtrIfE13AccPtrFactoryi[_Z30getAllSquaredDifferencesCoarseI15MlOptimiserCudaEvjR21OptimisationParamtersR18SamplingParametersP11MlOptimiserPT_R6AccPtrIfE13AccPtrFactoryi]+0x28a7): undefined reference to `RelionError::RelionError(std::string const&, std::string const&, long)'
../../lib/librelion_gpu_util.a(relion_gpu_util_generated_cuda_ml_optimiser.cu.o):tmpxft_0000d2a3_00000000-4_cuda_ml_optimiser.cudafe1.cpp:(.text._Z28getAllSquaredDifferencesFineI15MlOptimiserCudaEvjR21OptimisationParamtersR18SamplingParametersP11MlOptimiserPT_RSt6vectorI16IndexedDataArraySaISA_EERS9_IS9_I20IndexedDataArrayMaskSaISE_EESaISG_EERS9_I16ProjectionParamsSaISK_EE13AccPtrFactoryiRS9_I12AccPtrBundleSaISP_EE[_Z28getAllSquaredDifferencesFineI15MlOptimiserCudaEvjR21OptimisationParamtersR18SamplingParametersP11MlOptimiserPT_RSt6vectorI16IndexedDataArraySaISA_EERS9_IS9_I20IndexedDataArrayMaskSaISE_EESaISG_EERS9_I16ProjectionParamsSaISK_EE13AccPtrFactoryiRS9_I12AccPtrBundleSaISP_EE]+0x2f50): more undefined references to `RelionError::RelionError(std::string const&, std::string const&, long)' follow
collect2: error: ld returned 1 exit status
make[2]: *** [bin/relion_refine_mpi] Error 1
make[1]: *** [src/apps/CMakeFiles/refine_mpi.dir/all] Error 2
make: *** [all] Error 2

Any hint about where is the problem?

Thank you!
Zheng

**Comment by biochem-fan** [comment]
> The C compiler identification is GNU 4.8.5
> -- Found CUDA: /cm/shared/apps/cuda80/toolkit/8.0.44 (found version "8.0")
> -- Found MPI_C: /cm/shared/apps/mpich/ge/gcc/64/3.1.4/lib/libmpi.so

Please make sure all of them use the same GCC version. (MPIC and nvcc internally uses GCC).
