### ISSUE TITLE
Take anisotropic mag info to motioncorr2 ?

### ISSUE THREAD

**Issue by FFTMing** [3dem/relion#549]
The higher order anisotropic mag and aberration correction are amazing! 

As the  anisotropic mag is pretty consistent under similar data collection conditions, I'm wondering if we could take the info from RELION 3.1 to UCSF MotionCorr2. Where can I find the angle def etc? Does it use the same angle etc convention as it's in Niko's mag_distortion_estimate? MotionCorr2 follows mag_distortion_estimate conventions. 

Thanks,

**Comment by biochem-fan** [comment]
No. RELION's preferred way is to apply correction during reconstruction (Refine3D), not during initial motion correction. This way, you can reduce the number of interpolations. If you apply `-Mag` flag in UCSF MotionCor2, you cannot run Polishing.

The information is in `rlnMagMatrix_00` to `rlnMagMatrix_11`, which corresponds to the Matrix `M` in our aberration preprint.
