### ISSUE TITLE
Problem installing: Could NOT find MPI_C

### ISSUE THREAD

**Issue by bforsbe** [3dem/relion#55]
Originally reported by: **Alberto Riera (Bitbucket: [iiciieii](https://bitbucket.org/iiciieii), GitHub: Unknown)**

----------------------------------------

Hello!

I am currently having a problem when installing the beta in this computer with Scientific Linux 7.2. I initially found that with this version of Linux only CMAKE 2.8.11 is in the repositories but that is OK because I already downloaded 2.8.12. However, now I am finding the following error message: 

**CMake Error at /home/iiciieii/bin/cmake-3.6.0-Linux-x86_64/share/cmake-3.6/Modules/FindPackageHandleStandardArgs.cmake:148 (message):**

**  Could NOT find MPI_C (missing: MPI_C_LIBRARIES MPI_C_INCLUDE_PATH)**

Below is the full log:

-- BUILD TYPE set to the default type:  'Release'

-- Setting fallback CUDA_ARCH=35

-- Setting cpu precision to double

-- Setting gpu precision to single

-- Using cuda wrapper to compile....

-- Cuda version is >= 7.5 and single-precision build, enable double usage warning.
CMake Error at /home/iiciieii/bin/cmake-3.6.0-Linux-x86_64/share/cmake-3.6/Modules/FindPackageHandleStandardArgs.cmake:148 (message):

  Could NOT find MPI_C (missing: MPI_C_LIBRARIES MPI_C_INCLUDE_PATH)
Call Stack (most recent call first):

  /home/iiciieii/bin/cmake-3.6.0-Linux-x86_64/share/cmake-3.6/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)

  /home/iiciieii/bin/cmake-3.6.0-Linux-x86_64/share/cmake-3.6/Modules/FindMPI.cmake:628 (find_package_handle_standard_args)

  CMakeLists.txt:168 (find_package)

-- Configuring incomplete, errors occurred!

See also "/home/iiciieii/bin/cmake-3.6.0-Linux-x86_64/bin/CMakeFiles/CMakeOutput.log".

See also "/home/iiciieii/bin/cmake-3.6.0-Linux-x86_64/bin/CMakeFiles/CMakeError.log".

It seems that there is a problem detecting MPI. In my case, I installed the default Open MPI that comes with this distribution of Linux. 

Any help would be very welcome!

Thank you! :)

----------------------------------------
- Bitbucket: https://bitbucket.org/tcblab/relion2-beta/issue/55

**Comment by evanseitz** [comment]
@bforsbe I'm running into this same problem on the latest RELION release. In your solution for Relion 2, you recommended the removal of lines 169 and 171. Do you know which lines this now corresponds to in the Relion 3 beta file?

**Comment by bforsbe** [comment]
It's really about making sure that cmake can find your MPI flavour, as you are already dealing with through issue #509. I'll make further comments there rather than to reopen this issue.
