### ISSUE TITLE
Can't open coords_suffix_autopick.star with "Error in textToFloat of undefined"

### ISSUE THREAD

**Issue by tjragan** [3dem/relion#554]
After commit 8af52e3, trying to open a coords_suffix_autopick.star file results in "Error in textToFloat of undefined" in the gui.  The problem can be reproduced by checking out aab1197 and adding:
```
		FileName fn_star = myfilename;
		if (fn_star.back() == '/')
			fn_star += "job.star";
		if (!exists(fn_star))
			return false;
```
at line 358 (where it would get added in 8af52e3).  Commenting out the second if statement then removes the error and allows one to load the file for display.

**Comment by biochem-fan** [comment]
Fixed in 2085051. Thank you very much for reporting.
