### ISSUE TITLE
GUI shows parameters of last job of type not selected job

### ISSUE THREAD

**Issue by tjragan** [3dem/relion#555]
While 2085051 fixed the micrograph display issue (thanks for the rapid response!), it seems to have introduced a new issue where the job parameters displayed in the GUI are for the last job of that type, not the one selected.
To reproduce:
1. Run two jobs of the same type with different settings (I've checked Extract, Class2D, Refine3D), we'll call them Extract/job1 and Extract/job2
2. Select Extract/job1 in the 'Finished jobs' box
The parameters displayed on the right-hand side match those for Extract/job2.  This works as expected in 9c2ab92.

**Comment by biochem-fan** [comment]
Thanks for feedback. I fixed this in 6c49f84.
