### ISSUE TITLE
Relion_project variations in background

### ISSUE THREAD

**Issue by evanseitz** [3dem/relion#557]
Hi - I'm using `relion_project` on a series of synthetically-generated Coulomb potential maps (with defocus=0), and am seeing a "flickering" between output images in the background that I'm not sure how to explain. Is this an intentional quality that relion imposes based on the signal intensity or something unexpected?

I'm attaching a GIF showcasing the first 20 images (each taken from a constant angle on 20 unique volume conformations). The histograms for these images show sharp peaks around ~0 intensity that fall off rapidly (also attached for one image; plotted with 100 bins), whereby the actual variability in the backgrounds (while visually noticeable) is quantitatively rather constrained. However, I'm also running distance metrics on these images, so trying to be as precise as possible.

Ideally, the background between all 20 images would be perfectly uniform.

![movie_temp](https://user-images.githubusercontent.com/35609503/70948337-3e592900-2029-11ea-9347-947b93648bab.gif)

**Image 1/20:**
mean: 0.14507712324255545
std: 1.4753487027079073
![figure_7](https://user-images.githubusercontent.com/35609503/70948818-49608900-202a-11ea-8fca-a4b1e9c4aefe.png)

**Image 2/20:**
mean: 0.14510022447309212
std: 1.4705644046106425
![figure_8](https://user-images.githubusercontent.com/35609503/70949350-92650d00-202b-11ea-81ff-d6aaa8d1263d.png)

**Comment by biochem-fan** [comment]
Can you write the full command of `relion_proejct`? Are you plotting the projections by `relion_display` or your custom code?

**Comment by evanseitz** [comment]
`relion_project --i "${i}" --o $outFile --ang $angFile --ctf true`, where angFile is an alignment file with the single Euler angle combination of interest, and defocus 0.

I'm handling these images in Python, but here's a screenshot from `relion_display`, where the same background differences can be seen:
![figure_9](https://user-images.githubusercontent.com/35609503/70949532-030c2980-202c-11ea-9c1b-d5c2b5847e77.png)

**Comment by biochem-fan** [comment]
What is amplitude contrast and Cs?

If your Python code maps floating point numbers into the gray scale by normalizing mean and standard deviation (as in `relion_display`), tiny difference in them will be exaggerated.

**Comment by evanseitz** [comment]
Thank you so much for your time and help.

For all images:
`rlnVoltage = 300.`
`rlnSphericalAberration = 2.7`
`rlnAmplitudeContrast = .1`

So if I understand correctly, this is mainly a visual illusion that should have basically no affect on performing distance calculations between images?

If I did still want to create a movie (like the above) without flickering, do you have a reference for the correct gray scale conversion procedure? I was unaware there were competing methods.

**Comment by biochem-fan** [comment]
I would use a fixed threshold (e.g. black =-1, white=+1) for all frames in a movie.

**Comment by evanseitz** [comment]
Great feedback, thank you very much for all your help!
