### ISSUE TITLE
error message in Ctffind4.1

### ISSUE THREAD

**Issue by ananyachatterjeeiiserkolkata** [3dem/relion#559]
While performing CTF correction with Ctffind4.1, I am getting this error message:

/public/EM/ctffind/ctffind.exe: Command not found.
 WARNING: skipping, since cannot get CTF values for MotionCorr/job002/135.mrc
 Did not find any of the expected EPS files to generate a PDF file
 + Will make an empty PDF-file in CtfFind/job004/logfile.pdf

Please help

**Comment by biochem-fan** [comment]
Look at the error message. You didn't specify the right path to CTFFIND.

`/public/EM/ctffind/ctffind.exe: Command not found.`
