### ISSUE TITLE
Error converting optics groups from 3.0.2 to 3.1-beta-commit-a451e8 

### ISSUE THREAD

**Issue by mcianfrocco** [3dem/relion#560]
**Describe your problem**

Hello - I have a test dataset of aldolase that contains 386 beam tilt groups. When converting this from 3.0.2 to 3.1, the optics groups only go up to 219 instead of 386. I just confirmed this with the latest commit. I can write my own conversion but I wanted to point out this bug.

**Environment:**
 - OS: Red Hat Enterprise Linux 7
 - MPI runtime: OpenMPI 3.1.0
 - RELION version3.1-beta-commit-a451e8 

**Dataset:**
 - Box size: 300
 - Pixel size: 0.91 Å/px]
 - Number of particles: 186,841
 - Description: Aldolase

**Job options:**
 - Type of job: relion_convert_star
 - Full command (see `note.txt` in the job directory):
   ```
   relion_convert_star --i Refine3D/job174/run_data.star --o Refine3D/job174/run_data_3.1.star --Cs 2.7 --Q0 0.1

**Error message:**
No error message. Conversion completes but only writes out 219 optics groups instead of 386.

Thank you,
Mike

**Comment by biochem-fan** [comment]
Can you share us your `run_data.star`?

**Comment by mcianfrocco** [comment]
Yes - here it is attached. 

[run_data.star.zip](https://github.com/3dem/relion/files/4031641/run_data.star.zip)

**Comment by biochem-fan** [comment]
Thanks, but you have only 219 optics groups.

```bash
$ awk 'NF>25 {print $31}' run_data.star  | sort | uniq | wc -l
219
```

**Comment by mcianfrocco** [comment]
Oh - I see. Thank you for catching that and sorry for troubling you.

Mike
