### ISSUE TITLE
relion_align_symmetry files missing in release 3.0.8.tar.gz

### ISSUE THREAD

**Issue by ponomarevsy** [3dem/relion#562]
Y'all,

Just wanted to share my relion compiling experience here and, hopefully, save some time for other users, trying to compile relion from this source code:

https://github.com/3dem/relion/archive/3.0.8.tar.gz

The above distro does NOT have the relion_align_symmetry files, thus, when doing "make install" you will produce an error like this:

```
Install the project...
-- Install configuration: "Release"
CMake Error at src/apps/cmake_install.cmake:42 (file):
  file INSTALL cannot find
  "path-to-relion/relion-3.0.8/build/bin/relion_align_symmetry".
Call Stack (most recent call first):
  cmake_install.cmake:49 (include)


make: *** [install] Error 1
``` 

**Solution: use "git clone https://github.com/3dem/relion.git" instead. That one has the missing relion_align_symmetry source files and will compile the executable successfully.**

**Comment by biochem-fan** [comment]
The file you mentioned does contain `src/app/align_symmetry.cpp`.

**Comment by ponomarevsy** [comment]
Yes, I did:

cd /path-to-relion/relion-3.0.8/build
rm -r *
cmake -DDoublePrec_GPU=ON -DCUDA=ON -DCudaTexture=ON -DCMAKE_INSTALL_PREFIX=/path-to-relion/relion-3.0.8/build ..
make -j 12
make install

And that produces:

```
Install the project...
-- Install configuration: "Release"
CMake Error at src/apps/cmake_install.cmake:42 (file):
  file INSTALL cannot find
  "path-to-relion/relion-3.0.8/build/bin/relion_align_symmetry".
Call Stack (most recent call first):
  cmake_install.cmake:49 (include)


make: *** [install] Error 1
```

**Comment by biochem-fan** [comment]
I cannot reproduce your problem. What happens if you run `make` twice?

**Comment by ponomarevsy** [comment]
Did you start from the source file above? It never worked for me until I switched to the github repo.

**Comment by biochem-fan** [comment]
Yes. I used your link to tar.gz.

**Comment by ponomarevsy** [comment]
And you see the **relion_align_symmetry** executable in the build folder as a result of "make install"? If so, I'd wait to close this discussion, since there could be more users with the same issue. I don't have the time to test it again from scratch right now, - I've spent a day compiling Relion from source.

**Comment by biochem-fan** [comment]
> `-DCMAKE_INSTALL_PREFIX=/path-to-relion/relion-3.0.8/build`

This is the destination of `make install`. The `make` step creates binaries under the `bin` of the current build directory and `make install` copies them to the destination specified here.

Thus, the destination must be different from your `build` directory (e.g. `/usr/local`). Or, you can completely omit the `make install` step and just set `PATH` to `/path-to-relion/relion-3.0.8/build/bin`.

By specifying the build path as the destination, `make install` is overwriting the binaries created in the `make` step and causing the error.

**Comment by ponomarevsy** [comment]
Thank you, @biochem-fan ! That, indeed, seems to be the case.
