### ISSUE TITLE
Particle number after symmetry expansion

### ISSUE THREAD

**Issue by QB5678** [3dem/relion#563]
Hi, I am using relion 3.1. After I did symmetry expansion, I imported the particles to do refinement. Relion reported that " For optics_group 1, there are XXXXX particles on the scratch disk."
Strangely, XXXXX is the same number before the symmetry expansion. But I did see from the star file that my particle numbers increased. Is there a problem?

Thanks

**Comment by biochem-fan** [comment]
This is normal. In RELION 3.1, the caching was improved to avoid copying the same particle image many times.
