### ISSUE TITLE
Cannot compile Relion 3.1

### ISSUE THREAD

**Issue by ryanlindsay** [3dem/relion#569]
**Describe your problem**
Trying to compile Relion 3.1 on a RHEL7 / Cuda 10 environment
It keeps failing at the linking stage on trying to link relion_autopick_mpi and relion_autopick

**Environment:**
 - OS: Rhel 7
 - MPI runtime: OpenMPI3 / MPICH
 - RELION version [e.g. RELION-3.1-devel-commit-6ba935 (please see the title bar of the GUI)] 
 - Memory: 256GB
 - GPU: Nvidia Tesla P100

**Error message:**
cmake completes ok

Please cite the *full* error message as the example below.
cmake -DFORCE_OWN_FFTW=ON -DFORCE_OWN_FLTK=ON -DCUDA_ARCH=60 ..
-- BUILD TYPE set to the default type:  'Release'
-- Using provided CUDA_ARCH=60
-- ALLOW_CTF_IN_SAGD enabled - This build of RELION allows modulation of particle images by a contrast transfer function inside stochastic average gradient descent, as specified in Claim 1 of patent US10,282,513B2
-- CUDA enabled - Building CUDA-accelerated version of RELION
-- Setting cpu precision to double
-- Setting accelerated code precision to single
-- Found CUDA: /cm/shared/apps/cuda10.1/toolkit/10.1.168 (found version "10.1")
-- Using cuda wrapper to compile....
-- Cuda version is >= 7.5 and single-precision build, enable double usage warning.
-- Found MPI_C: /cm/shared/apps/openmpi3/gcc/64/3.0.0/lib64/libmpi.so
-- Found MPI_CXX: /cm/shared/apps/openmpi3/gcc/64/3.0.0/lib64/libmpi.so
-- MPI_INCLUDE_PATH : /cm/shared/apps/openmpi3/gcc/64/3.0.0/include
-- MPI_LIBRARIES : /cm/shared/apps/openmpi3/gcc/64/3.0.0/lib64/libmpi.so
-- MPI_CXX_INCLUDE_PATH : /cm/shared/apps/openmpi3/gcc/64/3.0.0/include
-- MPI_CXX_LIBRARIES : /cm/shared/apps/openmpi3/gcc/64/3.0.0/lib64/libmpi.so
-- CMAKE_C_COMPILER : /usr/bin/cc
-- CMAKE_CXX_COMPILER : /usr/bin/c++
-- MPI_C_COMPILER : /cm/shared/apps/openmpi3/gcc/64/3.0.0/bin/mpicc
-- MPI_CXX_COMPILER : /cm/shared/apps/openmpi3/gcc/64/3.0.0/bin/mpicxx
-- CMAKE_CXX_COMPILER_ID : GNU
-- CMAKE_C_COMPILER : /cm/shared/apps/openmpi3/gcc/64/3.0.0/bin/mpicc
-- CMAKE_CXX_COMPILER : /cm/shared/apps/openmpi3/gcc/64/3.0.0/bin/mpicxx
-- MPI_C_COMPILER : /cm/shared/apps/openmpi3/gcc/64/3.0.0/bin/mpicc
-- MPI_CXX_COMPILER : /cm/shared/apps/openmpi3/gcc/64/3.0.0/bin/mpicxx
-- Looking for XOpenDisplay in /usr/lib64/libX11.so;/usr/lib64/libXext.so
-- Looking for XOpenDisplay in /usr/lib64/libX11.so;/usr/lib64/libXext.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Looking for IceConnectionNumber in ICE
-- Looking for IceConnectionNumber in ICE - found
-- Found X11: /usr/lib64/libX11.so
-- Found previously built non-system FLTK libraries that will be used.
-- FLTK_INCLUDE_DIR: /home/ryan.a.lindsay/relion/external/fltk/include
-- FLTK_LIBRARIES:   /home/ryan.a.lindsay/relion/external/fltk/lib/libfltk.so
-- Found previously built non-system single precision FFTW libraries that will be used.
-- Found previously built non-system double precision FFTW libraries that will be used.
-- Looking for sincos
-- Looking for sincos - found
-- Looking for __sincos
-- Looking for __sincos - not found
-- Found TIFF: /usr/lib64/libtiff.so (found version "4.0.3")
-- Found ZLIB: /usr/lib64/libz.so (found version "1.2.7")
-- Found PNG: /usr/lib64/libpng.so (found version "1.5.13")
BUILD_SHARED_LIBS = OFF
-- Building static libs (larger build size and binaries)
Running apps/CMakeLists.txt...
-- CMAKE_BINARY_DIR:/home/ryan.a.lindsay/relion/build
-- Git commit ID: 06afb9fe634d32265ce9e305e655e30812057683
TIFF FOUND
PNG FOUND
-- Try OpenMP C flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Try OpenMP CXX flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Found OpenMP: -fopenmp
OPENMP FOUND
-- Configuring done
-- Generating done
-- Build files have been written to: /home/ryan.a.lindsay/relion/build

Scanning dependencies of target autopick
[ 70%] Building CXX object src/apps/CMakeFiles/autopick.dir/autopick.cpp.o
Linking CXX executable ../../bin/relion_autopick
../../lib/librelion_gpu_util.a(relion_gpu_util_generated_cuda_autopicker.cu.o): In function `LaunchHandleError(cudaError, char const*, int)':
tmpxft_0002653c_00000000-5_cuda_autopicker.cudafe1.cpp:(.text+0x97): undefined reference to `RelionError::RelionError(std::string const&, std::string const&, long)'
../../lib/librelion_gpu_util.a(relion_gpu_util_generated_cuda_autopicker.cu.o): In function `HandleError(cudaError, char const*, int)':
tmpxft_0002653c_00000000-5_cuda_autopicker.cudafe1.cpp:(.text+0x1bf): undefined reference to `RelionError::RelionError(std::string const&, std::string const&, long)'
../../lib/librelion_gpu_util.a(relion_gpu_util_generated_cuda_autopicker.cu.o): In function `LaunchHandleError(cudaError, char const*, int) [clone .constprop.186]':
tmpxft_0002653c_00000000-5_cuda_autopicker.cudafe1.cpp:(.text+0x4fd): undefined reference to `RelionError::RelionError(std::string const&, std::string const&, long)'
../../lib/librelion_gpu_util.a(relion_gpu_util_generated_cuda_autopicker.cu.o): In function `HandleError(cudaError, char const*, int) [clone .constprop.187]':
tmpxft_0002653c_00000000-5_cuda_autopicker.cudafe1.cpp:(.text+0x615): undefined reference to `RelionError::RelionError(std::string const&, std::string const&, long)'
../../lib/librelion_gpu_util.a(relion_gpu_util_generated_cuda_autopicker.cu.o): In function `void runCenterFFT<float>(AccPtr<float>&, int, int, bool, int) [clone .constprop.175]':
tmpxft_0002653c_00000000-5_cuda_autopicker.cudafe1.cpp:(.text+0x7b9): undefined reference to `RelionError::RelionError(std::string const&, std::string const&, long)'
../../lib/librelion_gpu_util.a(relion_gpu_util_generated_cuda_autopicker.cu.o):tmpxft_0002653c_00000000-5_cuda_autopicker.cudafe1.cpp:(.text+0xba4): more undefined references to `RelionError::RelionError(std::string const&, std::string const&, long)' follow
../../lib/librelion_gpu_util.a(relion_gpu_util_generated_cuda_autopicker.cu.o): In function `MultidimArray<double>::resize(long, long, long, long) [clone .constprop.176]':
tmpxft_0002653c_00000000-5_cuda_autopicker.cudafe1.cpp:(.text+0xc4c): undefined reference to `FileName::addExtension(std::string const&) const'
tmpxft_0002653c_00000000-5_cuda_autopicker.cudafe1.cpp:(.text+0xd75): undefined reference to `RelionError::RelionError(std::string const&, std::string const&, long)'
tmpxft_0002653c_00000000-5_cuda_autopicker.cudafe1.cpp:(.text+0xe40): undefined reference to `RelionError::RelionError(std::string const&, std::string const&, long)'
tmpxft_0002653c_00000000-5_cuda_autopicker.cudafe1.cpp:(.text+0xed8): undefined reference to `RelionError::RelionError(std::string const&, std::string const&, long)'
../../lib/librelion_gpu_util.a(relion_gpu_util_generated_cuda_autopicker.cu.o): In function `AutoPickerCuda::calculateStddevAndMeanUnderMask(AccPtr<float2>&, AccPtr<float2>&, AccPtr<float2>&, int, AccPtr<float>&, AccPtr<float>&, unsigned long, unsigned long, unsigned long, unsigned long)':
tmpxft_0002653c_00000000-5_cuda_autopicker.cudafe1.cpp:(.text+0x1c64): undefined reference to `RelionError::RelionError(std::string const&, std::string const&, long)'
tmpxft_0002653c_00000000-5_cuda_autopicker.cudafe1.cpp:(.text+0x1d30): undefined reference to `RelionError::RelionError(std::string const&, std::string const&, long)'
../../lib/librelion_gpu_util.a(relion_gpu_util_generated_cuda_autopicker.cu.o):tmpxft_0002653c_00000000-5_cuda_autopicker.cudafe1.cpp:(.text+0x2637): more undefined references to `RelionError::RelionError(std::string const&, std::string const&, long)' follow
../../lib/librelion_gpu_util.a(relion_gpu_util_generated_cuda_autopicker.cu.o): In function `AutoPickerCuda::autoPickOneMicrograph(FileName&, long)':
tmpxft_0002653c_00000000-5_cuda_autopicker.cudafe1.cpp:(.text+0x3c85): undefined reference to `MetaDataContainer::getValue(long, std::string&) const'
tmpxft_0002653c_00000000-5_cuda_autopicker.cudafe1.cpp:(.text+0x689e): undefined reference to `FileName::compose(std::string const&, long, std::string const&, int)'
tmpxft_0002653c_00000000-5_cuda_autopicker.cudafe1.cpp:(.text+0x6a7e): undefined reference to `FileName::compose(std::string const&, long, std::string const&, int)'
tmpxft_0002653c_00000000-5_cuda_autopicker.cudafe1.cpp:(.text+0x6da6): undefined reference to `FileName::compose(std::string const&, long, std::string const&, int)'
tmpxft_0002653c_00000000-5_cuda_autopicker.cudafe1.cpp:(.text+0x6f49): undefined reference to `FileName::compose(std::string const&, long, std::string const&, int)'
tmpxft_0002653c_00000000-5_cuda_autopicker.cudafe1.cpp:(.text+0x9c2f): undefined reference to `RelionError::RelionError(std::string const&, std::string const&, long)'
tmpxft_0002653c_00000000-5_cuda_autopicker.cudafe1.cpp:(.text+0xa636): undefined reference to `RelionError::RelionError(std::string const&, std::string const&, long)'
../../lib/librelion_gpu_util.a(relion_gpu_util_generated_cuda_autopicker.cu.o): In function `AutoPickerCuda::run()':
tmpxft_0002653c_00000000-5_cuda_autopicker.cudafe1.cpp:(.text+0xaa8b): undefined reference to `FileName::beforeLastOf(std::string const&) const'
../../lib/librelion_gpu_util.a(relion_gpu_util_generated_cuda_autopicker.cu.o): In function `CudaCustomAllocator::alloc(unsigned long)':
tmpxft_0002653c_00000000-5_cuda_autopicker.cudafe1.cpp:(.text._ZN19CudaCustomAllocator5allocEm[_ZN19CudaCustomAllocator5allocEm]+0x2f9): undefined reference to `RelionError::RelionError(std::string const&, std::string const&, long)'
../../lib/librelion_gpu_util.a(relion_gpu_util_generated_cuda_autopicker.cu.o): In function `CudaFFT::forward()':
tmpxft_0002653c_00000000-5_cuda_autopicker.cudafe1.cpp:(.text._ZN7CudaFFT7forwardEv[_ZN7CudaFFT7forwardEv]+0x9e): undefined reference to `RelionError::RelionError(std::string const&, std::string const&, long)'
../../lib/librelion_gpu_util.a(relion_gpu_util_generated_cuda_autopicker.cu.o): In function `CudaFFT::backward()':
tmpxft_0002653c_00000000-5_cuda_autopicker.cudafe1.cpp:(.text._ZN7CudaFFT8backwardEv[_ZN7CudaFFT8backwardEv]+0x9e): undefined reference to `RelionError::RelionError(std::string const&, std::string const&, long)'
../../lib/librelion_gpu_util.a(relion_gpu_util_generated_cuda_autopicker.cu.o): In function `AccPtr<float>::hostAlloc()':
tmpxft_0002653c_00000000-5_cuda_autopicker.cudafe1.cpp:(.text._ZN6AccPtrIfE9hostAllocEv[_ZN6AccPtrIfE9hostAllocEv]+0x7b): undefined reference to `RelionError::RelionError(std::string const&, std::string const&, long)'
../../lib/librelion_gpu_util.a(relion_gpu_util_generated_cuda_autopicker.cu.o): In function `AccPtr<float>::AccPtr(unsigned long, CudaCustomAllocator*)':
tmpxft_0002653c_00000000-5_cuda_autopicker.cudafe1.cpp:(.text._ZN6AccPtrIfEC2EmP19CudaCustomAllocator[_ZN6AccPtrIfEC5EmP19CudaCustomAllocator]+0xa2): undefined reference to `RelionError::RelionError(std::string const&, std::string const&, long)'
../../lib/librelion_gpu_util.a(relion_gpu_util_generated_cuda_autopicker.cu.o):tmpxft_0002653c_00000000-5_cuda_autopicker.cudafe1.cpp:(.text._ZN6AccPtrI6float2EC2EmP19CudaCustomAllocator[_ZN6AccPtrI6float2EC5EmP19CudaCustomAllocator]+0xa2): more undefined references to `RelionError::RelionError(std::string const&, std::string const&, long)' follow
../../lib/librelion_gpu_util.a(relion_gpu_util_generated_cuda_autopicker.cu.o): In function `MultidimArray<double>::resizeNoCp(long, long, long, long)':
tmpxft_0002653c_00000000-5_cuda_autopicker.cudafe1.cpp:(.text._ZN13MultidimArrayIdE10resizeNoCpEllll[_ZN13MultidimArrayIdE10resizeNoCpEllll]+0x256): undefined reference to `FileName::addExtension(std::string const&) const'
tmpxft_0002653c_00000000-5_cuda_autopicker.cudafe1.cpp:(.text._ZN13MultidimArrayIdE10resizeNoCpEllll[_ZN13MultidimArrayIdE10resizeNoCpEllll]+0x370): undefined reference to `RelionError::RelionError(std::string const&, std::string const&, long)'
tmpxft_0002653c_00000000-5_cuda_autopicker.cudafe1.cpp:(.text._ZN13MultidimArrayIdE10resizeNoCpEllll[_ZN13MultidimArrayIdE10resizeNoCpEllll]+0x440): undefined reference to `RelionError::RelionError(std::string const&, std::string const&, long)'
tmpxft_0002653c_00000000-5_cuda_autopicker.cudafe1.cpp:(.text._ZN13MultidimArrayIdE10resizeNoCpEllll[_ZN13MultidimArrayIdE10resizeNoCpEllll]+0x534): undefined reference to `RelionError::RelionError(std::string const&, std::string const&, long)'
tmpxft_0002653c_00000000-5_cuda_autopicker.cudafe1.cpp:(.text._ZN13MultidimArrayIdE10resizeNoCpEllll[_ZN13MultidimArrayIdE10resizeNoCpEllll]+0x683): undefined reference to `RelionError::RelionError(std::string const&, std::string const&, long)'
../../lib/librelion_gpu_util.a(relion_gpu_util_generated_cuda_autopicker.cu.o): In function `CudaFFT::setSize(unsigned long, unsigned long, unsigned long, int, int)':
tmpxft_0002653c_00000000-5_cuda_autopicker.cudafe1.cpp:(.text._ZN7CudaFFT7setSizeEmmmii[_ZN7CudaFFT7setSizeEmmmii]+0x747): undefined reference to `RelionError::RelionError(std::string const&, std::string const&, long)'
../../lib/librelion_gpu_util.a(relion_gpu_util_generated_cuda_autopicker.cu.o):tmpxft_0002653c_00000000-5_cuda_autopicker.cudafe1.cpp:(.text._ZN7CudaFFT7setSizeEmmmii[_ZN7CudaFFT7setSizeEmmmii]+0xc4c): more undefined references to `RelionError::RelionError(std::string const&, std::string const&, long)' follow
../../lib/librelion_gpu_util.a(relion_gpu_util_generated_cuda_autopicker.cu.o): In function `Image<int>::_write(FileName const&, fImageHandler&, long, bool, int)':
tmpxft_0002653c_00000000-5_cuda_autopicker.cudafe1.cpp:(.text._ZN5ImageIiE6_writeERK8FileNameR13fImageHandlerlbi[_ZN5ImageIiE6_writeERK8FileNameR13fImageHandlerlbi]+0x86): undefined reference to `FileName::decompose(long&, std::string&) const'
tmpxft_0002653c_00000000-5_cuda_autopicker.cudafe1.cpp:(.text._ZN5ImageIiE6_writeERK8FileNameR13fImageHandlerlbi[_ZN5ImageIiE6_writeERK8FileNameR13fImageHandlerlbi]+0x56d): undefined reference to `FileName::contains(std::string const&) const'
tmpxft_0002653c_00000000-5_cuda_autopicker.cudafe1.cpp:(.text._ZN5ImageIiE6_writeERK8FileNameR13fImageHandlerlbi[_ZN5ImageIiE6_writeERK8FileNameR13fImageHandlerlbi]+0x5c4): undefined reference to `FileName::contains(std::string const&) const'
tmpxft_0002653c_00000000-5_cuda_autopicker.cudafe1.cpp:(.text._ZN5ImageIiE6_writeERK8FileNameR13fImageHandlerlbi[_ZN5ImageIiE6_writeERK8FileNameR13fImageHandlerlbi]+0x7dd): undefined reference to `FileName::contains(std::string const&) const'
tmpxft_0002653c_00000000-5_cuda_autopicker.cudafe1.cpp:(.text._ZN5ImageIiE6_writeERK8FileNameR13fImageHandlerlbi[_ZN5ImageIiE6_writeERK8FileNameR13fImageHandlerlbi]+0x92a): undefined reference to `RelionError::RelionError(std::string const&, std::string const&, long)'
tmpxft_0002653c_00000000-5_cuda_autopicker.cudafe1.cpp:(.text._ZN5ImageIiE6_writeERK8FileNameR13fImageHandlerlbi[_ZN5ImageIiE6_writeERK8FileNameR13fImageHandlerlbi]+0xa98): undefined reference to `RelionError::RelionError(std::string const&, std::string const&, long)'
tmpxft_0002653c_00000000-5_cuda_autopicker.cudafe1.cpp:(.text._ZN5ImageIiE6_writeERK8FileNameR13fImageHandlerlbi[_ZN5ImageIiE6_writeERK8FileNameR13fImageHandlerlbi]+0xbe5): undefined reference to `FileName::contains(std::string const&) const'
tmpxft_0002653c_00000000-5_cuda_autopicker.cudafe1.cpp:(.text._ZN5ImageIiE6_writeERK8FileNameR13fImageHandlerlbi[_ZN5ImageIiE6_writeERK8FileNameR13fImageHandlerlbi]+0xc38): undefined reference to `FileName::contains(std::string const&) const'
tmpxft_0002653c_00000000-5_cuda_autopicker.cudafe1.cpp:(.text._ZN5ImageIiE6_writeERK8FileNameR13fImageHandlerlbi[_ZN5ImageIiE6_writeERK8FileNameR13fImageHandlerlbi]+0xc80): undefined reference to `FileName::contains(std::string const&) const'
tmpxft_0002653c_00000000-5_cuda_autopicker.cudafe1.cpp:(.text._ZN5ImageIiE6_writeERK8FileNameR13fImageHandlerlbi[_ZN5ImageIiE6_writeERK8FileNameR13fImageHandlerlbi]+0xd2d): undefined reference to `FileName::contains(std::string const&) const'
tmpxft_0002653c_00000000-5_cuda_autopicker.cudafe1.cpp:(.text._ZN5ImageIiE6_writeERK8FileNameR13fImageHandlerlbi[_ZN5ImageIiE6_writeERK8FileNameR13fImageHandlerlbi]+0xe3b): undefined reference to `RelionError::RelionError(std::string const&, std::string const&, long)'
tmpxft_0002653c_00000000-5_cuda_autopicker.cudafe1.cpp:(.text._ZN5ImageIiE6_writeERK8FileNameR13fImageHandlerlbi[_ZN5ImageIiE6_writeERK8FileNameR13fImageHandlerlbi]+0xef5): undefined reference to `FileName::contains(std::string const&) const'
tmpxft_0002653c_00000000-5_cuda_autopicker.cudafe1.cpp:(.text._ZN5ImageIiE6_writeERK8FileNameR13fImageHandlerlbi[_ZN5ImageIiE6_writeERK8FileNameR13fImageHandlerlbi]+0xf79): undefined reference to `RelionError::RelionError(std::string const&, std::string const&, long)'
tmpxft_0002653c_00000000-5_cuda_autopicker.cudafe1.cpp:(.text._ZN5ImageIiE6_writeERK8FileNameR13fImageHandlerlbi[_ZN5ImageIiE6_writeERK8FileNameR13fImageHandlerlbi]+0x1011): undefined reference to `RelionError::RelionError(std::string const&, std::string const&, long)'
tmpxft_0002653c_00000000-5_cuda_autopicker.cudafe1.cpp:(.text._ZN5ImageIiE6_writeERK8FileNameR13fImageHandlerlbi[_ZN5ImageIiE6_writeERK8FileNameR13fImageHandlerlbi]+0x10ed): undefined reference to `RelionError::RelionError(std::string const&, std::string const&, long)'
tmpxft_0002653c_00000000-5_cuda_autopicker.cudafe1.cpp:(.text._ZN5ImageIiE6_writeERK8FileNameR13fImageHandlerlbi[_ZN5ImageIiE6_writeERK8FileNameR13fImageHandlerlbi]+0x124c): undefined reference to `RelionError::RelionError(std::string const&, std::string const&, long)'
tmpxft_0002653c_00000000-5_cuda_autopicker.cudafe1.cpp:(.text._ZN5ImageIiE6_writeERK8FileNameR13fImageHandlerlbi[_ZN5ImageIiE6_writeERK8FileNameR13fImageHandlerlbi]+0x137b): undefined reference to `RelionError::RelionError(std::string const&, std::string const&, long)'
../../lib/librelion_gpu_util.a(relion_gpu_util_generated_cuda_autopicker.cu.o):tmpxft_0002653c_00000000-5_cuda_autopicker.cudafe1.cpp:(.text._ZN5ImageIiE5writeE8FileNamelbi[_ZN5ImageIiE5writeE8FileNamelbi]+0x1d5): more undefined references to `RelionError::RelionError(std::string const&, std::string const&, long)' follow
../../lib/librelion_gpu_util.a(relion_gpu_util_generated_cuda_ml_optimiser.cu.o): In function `MultidimArray<double>::resize(long, long, long, long) [clone .constprop.520]':
tmpxft_000265d0_00000000-5_cuda_ml_optimiser.cudafe1.cpp:(.text+0x3352): undefined reference to `FileName::addExtension(std::string const&) const'
tmpxft_000265d0_00000000-5_cuda_ml_optimiser.cudafe1.cpp:(.text+0x347d): undefined reference to `RelionError::RelionError(std::string const&, std::string const&, long)'
tmpxft_000265d0_00000000-5_cuda_ml_optimiser.cudafe1.cpp:(.text+0x3549): undefined reference to `RelionError::RelionError(std::string const&, std::string const&, long)'
tmpxft_000265d0_00000000-5_cuda_ml_optimiser.cudafe1.cpp:(.text+0x35e1): undefined reference to `RelionError::RelionError(std::string const&, std::string const&, long)'
../../lib/librelion_gpu_util.a(relion_gpu_util_generated_cuda_ml_optimiser.cu.o): In function `MlDeviceBundle::setupFixedSizedObjects()':
tmpxft_000265d0_00000000-5_cuda_ml_optimiser.cudafe1.cpp:(.text+0x42e3): undefined reference to `RelionError::RelionError(std::string const&, std::string const&, long)'
tmpxft_000265d0_00000000-5_cuda_ml_optimiser.cudafe1.cpp:(.text+0x437c): undefined reference to `RelionError::RelionError(std::string const&, std::string const&, long)'
../../lib/librelion_gpu_util.a(relion_gpu_util_generated_cuda_ml_optimiser.cu.o):tmpxft_000265d0_00000000-5_cuda_ml_optimiser.cudafe1.cpp:(.text+0x4dd8): more undefined references to `RelionError::RelionError(std::string const&, std::string const&, long)' follow
../../lib/librelion_gpu_util.a(relion_gpu_util_generated_cuda_ml_optimiser.cu.o): In function `MultidimArray<float>::resizeNoCp(long, long, long, long)':
tmpxft_000265d0_00000000-5_cuda_ml_optimiser.cudafe1.cpp:(.text._ZN13MultidimArrayIfE10resizeNoCpEllll[_ZN13MultidimArrayIfE10resizeNoCpEllll]+0x256): undefined reference to `FileName::addExtension(std::string const&) const'
tmpxft_000265d0_00000000-5_cuda_ml_optimiser.cudafe1.cpp:(.text._ZN13MultidimArrayIfE10resizeNoCpEllll[_ZN13MultidimArrayIfE10resizeNoCpEllll]+0x370): undefined reference to `RelionError::RelionError(std::string const&, std::string const&, long)'
tmpxft_000265d0_00000000-5_cuda_ml_optimiser.cudafe1.cpp:(.text._ZN13MultidimArrayIfE10resizeNoCpEllll[_ZN13MultidimArrayIfE10resizeNoCpEllll]+0x440): undefined reference to `RelionError::RelionError(std::string const&, std::string const&, long)'
tmpxft_000265d0_00000000-5_cuda_ml_optimiser.cudafe1.cpp:(.text._ZN13MultidimArrayIfE10resizeNoCpEllll[_ZN13MultidimArrayIfE10resizeNoCpEllll]+0x534): undefined reference to `RelionError::RelionError(std::string const&, std::string const&, long)'
tmpxft_000265d0_00000000-5_cuda_ml_optimiser.cudafe1.cpp:(.text._ZN13MultidimArrayIfE10resizeNoCpEllll[_ZN13MultidimArrayIfE10resizeNoCpEllll]+0x683): undefined reference to `RelionError::RelionError(std::string const&, std::string const&, long)'
../../lib/librelion_gpu_util.a(relion_gpu_util_generated_cuda_ml_optimiser.cu.o): In function `unsigned long findThresholdIdxInCumulativeSum<float>(AccPtr<float>&, float)':
tmpxft_000265d0_00000000-5_cuda_ml_optimiser.cudafe1.cpp:(.text._Z31findThresholdIdxInCumulativeSumIfEmR6AccPtrIT_ES1_[_Z31findThresholdIdxInCumulativeSumIfEmR6AccPtrIT_ES1_]+0x4ba): undefined reference to `RelionError::RelionError(std::string const&, std::string const&, long)'
../../lib/librelion_gpu_util.a(relion_gpu_util_generated_cuda_ml_optimiser.cu.o): In function `std::ostream& operator<< <double>(std::ostream&, MultidimArray<double> const&)':
tmpxft_000265d0_00000000-5_cuda_ml_optimiser.cudafe1.cpp:(.text._ZlsIdERSoS0_RK13MultidimArrayIT_E[_ZlsIdERSoS0_RK13MultidimArrayIT_E]+0x1b0): undefined reference to `floatToString(float, int, int)'
tmpxft_000265d0_00000000-5_cuda_ml_optimiser.cudafe1.cpp:(.text._ZlsIdERSoS0_RK13MultidimArrayIT_E[_ZlsIdERSoS0_RK13MultidimArrayIT_E]+0x378): undefined reference to `floatToString(float, int, int)'
../../lib/librelion_gpu_util.a(relion_gpu_util_generated_cuda_ml_optimiser.cu.o): In function `Matrix1D<double>* std::__uninitialized_copy<false>::__uninit_copy<Matrix1D<double>*, Matrix1D<double>*>(Matrix1D<double>*, Matrix1D<double>*, Matrix1D<double>*)':
tmpxft_000265d0_00000000-5_cuda_ml_optimiser.cudafe1.cpp:(.text._ZNSt20__uninitialized_copyILb0EE13__uninit_copyIP8Matrix1DIdES4_EET0_T_S6_S5_[_ZNSt20__uninitialized_copyILb0EE13__uninit_copyIP8Matrix1DIdES4_EET0_T_S6_S5_]+0x149): undefined reference to `RelionError::RelionError(std::string const&, std::string const&, long)'
../../lib/librelion_gpu_util.a(relion_gpu_util_generated_cuda_ml_optimiser.cu.o): In function `MultidimArray<bool>::coreAllocate()':
tmpxft_000265d0_00000000-5_cuda_ml_optimiser.cudafe1.cpp:(.text._ZN13MultidimArrayIbE12coreAllocateEv[_ZN13MultidimArrayIbE12coreAllocateEv]+0x65): undefined reference to `FileName::addExtension(std::string const&) const'
tmpxft_000265d0_00000000-5_cuda_ml_optimiser.cudafe1.cpp:(.text._ZN13MultidimArrayIbE12coreAllocateEv[_ZN13MultidimArrayIbE12coreAllocateEv]+0x154): undefined reference to `RelionError::RelionError(std::string const&, std::string const&, long)'
tmpxft_000265d0_00000000-5_cuda_ml_optimiser.cudafe1.cpp:(.text._ZN13MultidimArrayIbE12coreAllocateEv[_ZN13MultidimArrayIbE12coreAllocateEv]+0x1d0): undefined reference to `RelionError::RelionError(std::string const&, std::string const&, long)'
tmpxft_000265d0_00000000-5_cuda_ml_optimiser.cudafe1.cpp:(.text._ZN13MultidimArrayIbE12coreAllocateEv[_ZN13MultidimArrayIbE12coreAllocateEv]+0x252): undefined reference to `RelionError::RelionError(std::string const&, std::string const&, long)'
tmpxft_000265d0_00000000-5_cuda_ml_optimiser.cudafe1.cpp:(.text._ZN13MultidimArrayIbE12coreAllocateEv[_ZN13MultidimArrayIbE12coreAllocateEv]+0x2b3): undefined reference to `RelionError::RelionError(std::string const&, std::string const&, long)'
tmpxft_000265d0_00000000-5_cuda_ml_optimiser.cudafe1.cpp:(.text._ZN13MultidimArrayIbE12coreAllocateEv[_ZN13MultidimArrayIbE12coreAllocateEv]+0x2f9): undefined reference to `RelionError::RelionError(std::string const&, std::string const&, long)'
../../lib/librelion_gpu_util.a(relion_gpu_util_generated_cuda_ml_optimiser.cu.o):tmpxft_000265d0_00000000-5_cuda_ml_optimiser.cudafe1.cpp:(.text._ZN13MultidimArrayIbE12coreAllocateEv[_ZN13MultidimArrayIbE12coreAllocateEv]+0x34c): more undefined references to `RelionError::RelionError(std::string const&, std::string const&, long)' follow
../../lib/librelion_gpu_util.a(relion_gpu_util_generated_cuda_ml_optimiser.cu.o): In function `MultidimArray<bool>::resizeNoCp(long, long, long, long)':
tmpxft_000265d0_00000000-5_cuda_ml_optimiser.cudafe1.cpp:(.text._ZN13MultidimArrayIbE10resizeNoCpEllll[_ZN13MultidimArrayIbE10resizeNoCpEllll]+0x180): undefined reference to `FileName::addExtension(std::string const&) const'
tmpxft_000265d0_00000000-5_cuda_ml_optimiser.cudafe1.cpp:(.text._ZN13MultidimArrayIbE10resizeNoCpEllll[_ZN13MultidimArrayIbE10resizeNoCpEllll]+0x296): undefined reference to `RelionError::RelionError(std::string const&, std::string const&, long)'
tmpxft_000265d0_00000000-5_cuda_ml_optimiser.cudafe1.cpp:(.text._ZN13MultidimArrayIbE10resizeNoCpEllll[_ZN13MultidimArrayIbE10resizeNoCpEllll]+0x3f0): undefined reference to `RelionError::RelionError(std::string const&, std::string const&, long)'
tmpxft_000265d0_00000000-5_cuda_ml_optimiser.cudafe1.cpp:(.text._ZN13MultidimArrayIbE10resizeNoCpEllll[_ZN13MultidimArrayIbE10resizeNoCpEllll]+0x4c2): undefined reference to `RelionError::RelionError(std::string const&, std::string const&, long)'
tmpxft_000265d0_00000000-5_cuda_ml_optimiser.cudafe1.cpp:(.text._ZN13MultidimArrayIbE10resizeNoCpEllll[_ZN13MultidimArrayIbE10resizeNoCpEllll]+0x588): undefined reference to `RelionError::RelionError(std::string const&, std::string const&, long)'
../../lib/librelion_gpu_util.a(relion_gpu_util_generated_cuda_ml_optimiser.cu.o): In function `arrayByArray(MultidimArray<double> const&, MultidimArray<double> const&, MultidimArray<double>&, char)':
tmpxft_000265d0_00000000-5_cuda_ml_optimiser.cudafe1.cpp:(.text._Z12arrayByArrayRK13MultidimArrayIdES2_RS0_c[_Z12arrayByArrayRK13MultidimArrayIdES2_RS0_c]+0xc7): undefined reference to `RelionError::RelionError(std::string const&, std::string const&, long)'
../../lib/librelion_gpu_util.a(relion_gpu_util_generated_cuda_ml_optimiser.cu.o):tmpxft_000265d0_00000000-5_cuda_ml_optimiser.cudafe1.cpp:(.text._Z12arrayByArrayRK13MultidimArrayI8tComplexIdEES4_RS2_c[_Z12arrayByArrayRK13MultidimArrayI8tComplexIdEES4_RS2_c]+0xc4): more undefined references to `RelionError::RelionError(std::string const&, std::string const&, long)' follow
collect2: error: ld returned 1 exit status
make[2]: *** [bin/relion_autopick] Error 1
make[1]: *** [src/apps/CMakeFiles/autopick.dir/all] Error 2
make: *** [all] Error 2

**Comment by biochem-fan** [comment]
This is caused when your compilers are messed up. Your CUDA SDK (`nvcc`) and OpenMPI (`mpicc`) must use the same version of GCC as CMake.

**Comment by ryanlindsay** [comment]
Actually it was resolved by compiling it with the Intel Compiler.
