### ISSUE TITLE
optics groups

### ISSUE THREAD

**Issue by jhansen6** [3dem/relion#571]
relion/3.1b0-gnu 

see attached image.

step 1:  import movies of optics group 1.
step 2: import movies of optics group 2.  change "optics group name" to "opticsGroup2"
step 3: join micrograph star files.    FAIL.

![Screen Shot 2020-01-28 at 10 49 39 AM](https://user-images.githubusercontent.com/22459413/73295500-a66c6480-41bc-11ea-8613-abb1c72125fe.png)

**Comment by biochem-fan** [comment]
You want to join movie STAR files but you specified `Combined micrograph STAR files: Yes`.

**Comment by jhansen6** [comment]
well I'm an idiot.  thanks.  thought it was a bug.
