### ISSUE TITLE
Manual pick fail in 3.1

### ISSUE THREAD

**Issue by jhansen6** [3dem/relion#583]
relion-3.1b10gnu

step 1) open relion >> import >> raw micrographs >> (input all metadata) >> run.   Successfully imported (see attached).

step 2) Manual pick tab >> (select input from previous step) >> run.  Error (see attached screenshot) "throwing an instance of std::out_of_range".

can't do manual picking in 3.1.  My workaround used to be to do it in 3.0.7 but that recently got uninstalled on our cluster. 

![Screen Shot 2020-02-26 at 1 03 19 PM](https://user-images.githubusercontent.com/22459413/75387561-61f5e680-5898-11ea-8a3a-dc98fac4eb30.png)
![Screen Shot 2020-02-26 at 1 01 46 PM](https://user-images.githubusercontent.com/22459413/75387567-63271380-5898-11ea-9116-5e8d42203576.png)

**Comment by biochem-fan** [comment]
Please avoid screenshot and paste as a text. We need full error message.

**Comment by jhansen6** [comment]
hi thanks.

my command, and the output:

[jhansen6@sculpin URA7_H360R_4]$ `which relion_manualpick` --i Import/job010/micrographs.star --odir ManualPick/job012/ --pickname manualpick --allow_save   --fast_save --selection ManualPick/job012/micrographs_selected.star --scale 0.2 --sigma_contrast 3 --black 0 --white 0 --lowpass 20 --ctf_scale 1 --particle_diameter 100  --pipeline_control ManualPick/job012/ && echo Import/job010/micrographs.star > ManualPick/job012/coords_suffix_manualpick.star

 Setting angpix to 1.16 based on the input STAR file... 
 Set low-pass filter to 20 due to downscaling of 0.2
 Saved ManualPick/job012/micrographs_selected.star
terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::substr: __pos (which is 18446744073709551615) > this->size() (which is 72)
Aborted

**Comment by biochem-fan** [comment]
Is your micrograph/20feb13a_XXXXXX_frames.mrc a symbolic link to somewhere else? If so, please use a link by an absolute path. Please avoid `ln -s ../../somewhere/20feb13a*.mrc .`.

**Comment by jhansen6** [comment]
thank you that works.  I will make my symbolic links to absolute paths from now on.  Had no idea.   Appreciated.
