### ISSUE TITLE
Having a job number on all files generated by relion?

### ISSUE THREAD

**Issue by heejongkim** [3dem/relion#590]
Hi,
It's a super naive question but i noticed that it would be very useful if all files comes with job number as prefix to organize and quickly distinguish when files got accidentally mixed up when I transfer them to my computer for the inspection. (Also, it would be useful for sorting and visualizing them as well)
Will it be possible already in Relion or any other suggestions how you keep track of all files besides putting them in a separate folder for each job?

Thank you.

**Comment by biochem-fan** [comment]
Most (but not all) RELION programs take the output file prefix in `--o`. For example, `--o Class3D/job025/run`. If you change this to `--o Class3D/job025/j025`, the file name will change. But this is not possible from the GUI and the job history (Input/Ouput) will be messed up.

We don't support this request. Sorry.
