### ISSUE TITLE
unbinning and sharpening

### ISSUE THREAD

**Issue by ejmontemayor** [3dem/relion#592]
Not totally sure if this is a legitimate bug, or just a property of my dataset.  I am working on a helical reconstruction in Relion 3.1.  Two-fold binned data gives a reasonable helical reconstruction that appears to be Nyquist limited, and automated map sharpening appears to “improve” the map with an estimated B factor of ~ -80 Å2.  Example images are attached

If I re-extract to the native pixel size of 0.87 Å during polishing, I get a map that looks a little noisier after auto refinement with a nominally better FSC cutoff, and running postprocessing in Relion now estimates a very different B factor of ~ -20 Å2, which makes the map look horrible.  Manually applying a B factor of +20 Å2 makes it look a little better.

Is this the expected behavior?  Why are the B value behaviors so different before and after unbinning?

[unbinning.pdf](https://github.com/3dem/relion/files/4383299/unbinning.pdf)

**Comment by biochem-fan** [comment]
Are you using MTF correction? Did you specify the correct detector pixel size?

**Comment by ejmontemayor** [comment]
I provided the .mtf file during initial import of the movies, before running motioncor2 (not relioncor).

Before and after unbinning I had calibrated pixel size as “-1” and perform MTF correction as “No” in the Postprocessing GUI.

-Eric

**Comment by biochem-fan** [comment]
Please attach PostProcess's logfile (logfile.pdf) for bin1 and bin2.

**Comment by ejmontemayor** [comment]
Here they are, is this happening because I’m already maxed out on usable SNR range when binned?

**Comment by biochem-fan** [comment]
? I don't see your attachment.

**Comment by ejmontemayor** [comment]
how about this way? (attaching on website instead of email)

[binned-2x.pdf](https://github.com/3dem/relion/files/4383404/binned-2x.pdf)
[unbinned.pdf](https://github.com/3dem/relion/files/4383405/unbinned.pdf)

**Comment by biochem-fan** [comment]
Yes, I see attachments now. I think you don't have to worry.

In the log file, you should see lines like
```
== Fitting straight line through Guinier plot to find B-factor ...
  + fit from resolution:           10
  + fit until resolution:          0
```

Now that you have higher resolution shells in the unbinned reconstruction, the fit included too much noise and became unreliable. If you put `--fit_maxres 3.4`, you should get a similar result as bin2 reconstruction.

**Comment by ejmontemayor** [comment]
I'm using 3.1-beta-commit-a6aaa5 (from SBGrid).  I don't see the --fit_maxres option, but is that functionally equivalent to --autob_highres?

I tried this a few different ways and a summary is attached.  Combining --autob_highres 3.3  --low_pass 3.3 seems to give the best map here and a plausible B factor.

Thanks!

[2020-03-26_unbinning.pdf](https://github.com/3dem/relion/files/4390359/2020-03-26_unbinning.pdf)

**Comment by biochem-fan** [comment]
You are right. `--autob_highres` is correct. `fit_maxres` is an internal variable name.
