### ISSUE TITLE
Polishing not writing "cella" header

### ISSUE THREAD

**Issue by cdienem** [3dem/relion#597]
**Description**

When I compare particles extracted normally (relion extract) versus shiny particles from polishing, I noticed that the shiny particles do not contain a correct header entry for "cella". Instead they contain 0. Of course this is not a critical bug, but quite annoying if one wants to use the header information.

**Environment:**
 - OS: Ubuntu 18.04.2 LTS
 - MPI runtime: OpenMPI 4.0.1
 - RELION version 3.0.7
 - Memory: 128 GB
 - GPU: GTX 1080Ti

**Dataset:**
 - any

**Job options:**
 - any Polish
   
**Error message:**

When reading the header from a shiny MRCS stack, bytes 41-44 read value 0 in contrast to MRCS stacks originating from Extract jobs.

**Comment by biochem-fan** [comment]
Thanks for feedback. Fixed.
