### ISSUE TITLE
Cl2d and cl3d runs stall in Relion 3.1

### ISSUE THREAD

**Issue by eariascib** [3dem/relion#601]
Good afternoon,

We've recently installed relion 3.1 (beta-commit-164b0f) and the cl2D and cl3D procedures sometimes stall. They don't give any error. They sometimes simply stop running at random points  of the process and we have to relaunch them continuing from the las iteration.  We never observed that behavior with relion 3.07.

We are using:
- Linux Mint 18.1 Serena
- mpich-3.1.4
- relion 3.1 (beta-commit-164b0f) 
- Intel7 12 cores
- memory 64 GB
- GPU 2X GTX 1080Ti
- Scratch disk: 512 GB SDD

Dataset:
- Box size: 96
- Pixel size: 3 A/px (binned from the original 1 A/px for initial processing)
 - Number of particles: 11,000,000 in the case of cl2D. 4,500,000 in the case of cl3D
 - Description: 

**Job options:**
 - Type of job: CL2D and CL3D
 - Number of MPI processes: 3
 - Number of threads: 4
 - Full command (see `note.txt` in the job directory):
   ```
`which relion_refine_mpi` --continue Class2D/job037/run_it008_optimiser.star --o Class2D/job037/run_ct8 --dont_combine_weights_via_disc --no_parallel_disc_io --scratch_dir /scratch/Mer/relion --pool 12 --pad 2  --iter 20 --tau2_fudge 2 --particle_diameter 260 --oversampling 1 --psi_step 12 --offset_range 5 --offset_step 2 --j 4 --gpu ""  --pipeline_control Class2D/job037/

**Comment by biochem-fan** [comment]
> stop running at random points

Does this happens in the E step, M step or in between iterations?

**Comment by biochem-fan** [comment]
No response. Closing.
