### ISSUE TITLE
 A small question about reconstruction code

### ISSUE THREAD

**Issue by holyprince** [3dem/relion#602]
Sorry to bother you. Recently, I read backprojector.cpp and learns reconstruction. But I have a question  that I find in function : BackProjector::reconstruct, the weight or the data access all use this restriction:
```
k * k + i * i + j * j < max_r2
```
but in backproject2Dto3D.cpp, the interpolated data not only in this range(a little more than or equal max_r2).
I want to ask the restriction of the range why using less than.
If I use <=, the result of reconstruction how to be affected?
Thank you very much!

**Comment by biochem-fan** [comment]
It affects only a few voxels exactly at the resolution limit. In practice, `max_r2` is much larger than the dataset's resolution, so I don't think it really matters.

**Comment by holyprince** [comment]
OK, I got it. Thank you very much!
