### ISSUE TITLE
Slow "reading in optimiser.star" when continuing jobs

### ISSUE THREAD

**Issue by heejongkim** [3dem/relion#603]
Hi,

I have been noticing that the amount of time it takes to continue jobs in 3.1 is substantially longer than 3.0. (3.0 is almost instantaneous while 3.1 may take 30min to several hours depending on the datasets) 
I checked the I/O and it's actually not reading or writing but relion_refine_mpi are doing some cpu jobs. (<- i'm curious about what they are doing actually)

I wonder it's due to a new star file format or new implementation of algorithm OR I did something wrong with compiling.

Thank you.

best,
heejong kim

**Comment by biochem-fan** [comment]
First, are you using the latest version? It fixed several issues.

If you have thousands of groups (not optics groups but noise estimation group), it may take time. But on our system, continuing from 5000 groups takes less than 10 min, not 30 min or hours.

> i'm curious about what they are doing actually
You can use GDB to find out what is happening inside the program. See https://github.com/3dem/relion/issues/514.

**Comment by heejongkim** [comment]
Yes. Indeed, there were 22k noise estimation groups.
I followed the tutorial to lower the number of groups and now it's blazing fast.
Thank you for the suggestion and "GDB".
I started enjoying it.

Thanks.
