### ISSUE TITLE
Relion 3.1 3D refine error: one of your half sets has no segments.  

### ISSUE THREAD

**Issue by Jake4484** [3dem/relion#605]
I imported particles from a select 2D class in Cryosparc. I then ran multiple 2D/3D classifications with no with no issues. I get an error with 3D auto refine that states one of your half sets has no segments and asks if rlnRandomSubset is set to 1 or 2 in your particles Star file .The data is for a 100 angstrom diameter particle with a 200 box size. Here is part of the Star file being used for Refinement: 
# version 30001

data_optics

loop_ 
_rlnVoltage #1 
_rlnSphericalAberration #2 
_rlnAmplitudeContrast #3 
_rlnOpticsGroup #4 
_rlnImagePixelSize #5 
_rlnImageDimensionality #6 
_rlnImageSize #7 
  300.000000     2.700000     0.070000            1     1.060000            2          200 
 

# version 30001

data_particles

loop_ 
_rlnImageName #1 
_rlnMicrographName #2 
_rlnCoordinateX #3 
_rlnCoordinateY #4 
_rlnAnglePsi #5 
_rlnOriginXAngst #6 
_rlnOriginYAngst #7 
_rlnDefocusU #8 
_rlnDefocusV #9 
_rlnDefocusAngle #10 
_rlnPhaseShift #11 
_rlnCtfBfactor #12 
_rlnRandomSubset #13 
_rlnClassNumber #14 
_rlnOpticsGroup #15 
_rlnGroupNumber #16 
_rlnAngleRot #17 
_rlnAngleTilt #18 
_rlnNormCorrection #19 
_rlnLogLikeliContribution #20 
_rlnMaxValueProbDistribution #21 
_rlnNrOfSignificantSamples #22 
000116@J774/extract/FoilHole_1159715_Data_31204767_31204768_20190201_1934_aligned_DW_particles.mrcs J764/imported/FoilHole_1159715_Data_31204767_31204768_20190201_1934_aligned_DW.mrc  2156.000000  3060.000000    60.615960     3.974408     0.794408 29223.787109 28601.591797    25.456038     0.000000     0.000000            1            1            1            1    28.244671    85.321598     0.671937 17981.327251     0.657452           16 

Is there something I should change on this to get it work?

**Comment by biochem-fan** [comment]
Look at the 13th column (_rlnRandomSubset). The values there should be either 1 or 2. If not, delete this column.

**Comment by Jake4484** [comment]
Isnt the 13th column a one for rlnRandomeSubset?

**Comment by biochem-fan** [comment]
Yes

**Comment by Jake4484** [comment]
Yeah, sorry the e was a typo on my part. I mean it looks like a one is in the correct spot though right?

**Comment by biochem-fan** [comment]
You showed me only one row, so I don't know if it really contains only 1 and 2. Did you check?

**Comment by Jake4484** [comment]
Yeah I checked and it looks fine from what I can tell. Here is more of it: 
000027@J774/extract/FoilHole_1159715_Data_31204773_31204774_20190201_1935_aligned_DW_particles.mrcs J764/imported/FoilHole_1159715_Data_31204773_31204774_20190201_1935_aligned_DW.mrc  1074.000000  1828.000000    15.645364     -1.32559     1.854407 29848.451172 29340.681641    14.153535     0.000000     0.000000            1            1            1            2    -56.76078    81.666363     0.668370 17504.979429     0.086946           38 
000161@J774/extract/FoilHole_1159715_Data_31204773_31204774_20190201_1935_aligned_DW_particles.mrcs J764/imported/FoilHole_1159715_Data_31204773_31204774_20190201_1935_aligned_DW.mrc  1090.000000  2175.000000    22.746588     -0.26559     -3.44559 29848.451172 29340.681641    14.153535     0.000000     0.000000            1            1            1            2    -50.10469    95.593959     0.685574 17726.083163     0.261871           34 
000024@J774/extract/FoilHole_1159715_Data_31204773_31204774_20190201_1935_aligned_DW_particles.mrcs J764/imported/FoilHole_1159715_Data_31204773_31204774_20190201_1935_aligned_DW.mrc  3200.000000  2399.000000   143.099817     -3.44559     3.974407 29848.451172 29340.681641    14.153535     0.000000     0.000000            1            1            1            2    -56.03130    91.199049     0.721454 17825.602786     0.218381          113 
000059@J774/extract/FoilHole_1159715_Data_31204773_31204774_20190201_1935_aligned_DW_particles.mrcs J764/imported/FoilHole_1159715_Data_31204773_31204774_20190201_1935_aligned_DW.mrc   858.000000  1745.000000   -172.63626     -3.44559     2.914408 29848.451172 29340.681641    14.153535     0.000000     0.000000            1            1            1            2    -45.44609    80.880869     0.660900 17698.170603     0.177964           17 
000046@J774/extract/FoilHole_1159715_Data_31204773_31204774_20190201_1935_aligned_DW_particles.mrcs J764/imported/FoilHole_1159715_Data_31204773_31204774_20190201_1935_aligned_DW.mrc  1414.000000   248.000000    46.288876     3.974408     9.274408 29848.451172 29340.681641    14.153535     0.000000     0.000000            1            1             1            2    61.502677   175.094153     0.648444 17199.075695     0.511167           25 
000033@J774/extract/FoilHole_1159715_Data_31204773_31204774_20190201_1935_aligned_DW_particles.mrcs J764/imported/FoilHole_1159715_Data_31204773_31204774_20190201_1935_aligned_DW.mrc  1252.000000   844.000000    -23.57131     -0.26559     2.914408 29848.451172 29340.681641    14.153535     0.000000     0.000000            1            1             1            2   -164.82812    53.422966     0.754781 17909.753263     0.297193           31 
000264@J774/extract/FoilHole_1159715_Data_31204773_31204774_20190201_1935_aligned_DW_particles.mrcs J764/imported/FoilHole_1159715_Data_31204773_31204774_20190201_1935_aligned_DW.mrc  1152.000000  1853.000000    91.524650     -3.44559     9.274408 29848.451172 29340.681641    14.153535     0.000000     0.000000            1            1            1            2   151.396176   104.786385     0.660234 17485.838194     0.430846          132 
000040@J774/extract/FoilHole_1159715_Data_31204773_31204774_20190201_1935_aligned_DW_particles.mrcs J764/imported/FoilHole_1159715_Data_31204773_31204774_20190201_1935_aligned_DW.mrc  3362.000000  2151.000000   151.669963     -1.32559     6.094408 29848.451172 29340.681641    14.153535     0.000000     0.000000            1            1            1            2    -79.28633    83.609763     0.668099 17754.115808     0.406712           22

**Comment by biochem-fan** [comment]
Did you check the number of 1s and 2s? Is it more-or-less balanced?

**Comment by Jake4484** [comment]
All of them are ones at the 13th column

**Comment by biochem-fan** [comment]
OK, that is the problem. Please report this bug to whoever wrote this CryoSPARC-to-RELION converter.

Meanwhile, you should remove the column to let RELION reassign half sets.

**Comment by Jake4484** [comment]
Okay sounds good I will give that a try. I really appreciate the help with it. I'll let you know what I come up with

**Comment by Jake4484** [comment]
It seems to run to just fine by deleting the column. I will add this issue to pyem, so that it can get fixed. Is there a setting I should change to start refinement by global search at the start of the refinement?

**Comment by biochem-fan** [comment]
> I will add this issue to pyem
Thanks!

> Is there a setting I should change to start refinement by global search at the start of the refinement?
The default is global search.

**Comment by Jake4484** [comment]
Not a problem, thanks for your help! I really appreciate it!
