### ISSUE TITLE
Relion 3.1 builds, but get "symbol lookup" error

### ISSUE THREAD

**Issue by dougbevan** [3dem/relion#606]
This is a template for asking questions and reporting bugs. Please fill in as much information as you can.

**Describe your problem**

Relion 3.1 builds with:

cmake -DCMAKE_INSTALL_PREFIX=/opt/cryoem/relion3.1-041620 -DFORCE_OWN_FFTW=ON -DFORCE_OWN_FLTK=ON ..

Please write a clear description of what the problem is.

**Environment:**
 - OS: CentOS 7.7
 - MPI runtime: 1.10.7
 - RELION version 3.1 (latest)
 - Memory: 512GB
 - GPU: 2080Ti

**Error message:**
Trying to run, we get:

>relion
relion: symbol lookup error: relion: undefined symbol: _ZN8Fl_ImageC2Eiii

**Comment by biochem-fan** [comment]
You should have `libfltk.so.1.3` in `external/fltk/lib/` of the package. Put this folder in your `LD_LIBRARY_PATH`.

**Comment by dougbevan** [comment]
I deleted the local relion repo, did a new git, checked out 3.1, re-built, and it seems to be running now.  Strange.

Will move on now to test the functionality!  Thanks for your support...
