### ISSUE TITLE
CTF refinement in v3.1-beta does not process all micrographs

### ISSUE THREAD

**Issue by krogala** [3dem/relion#607]
Hello developers!

I noticed that in the Relion 3.1-beta version not all of the micrographs get processed during per-particle defocus refinement. I cannot figure out why that would be, and thought that perhaps you might be able to help. The only warnings that I'm getting are about a missing pixel size value, which get pulled from input files anyway.

`WARNING: You did not specify --angpix_ref. The pixel size in the image header of Refine3D/job027/run_half1_class001_unfil.mrc, 0.83 A/px, is used.`

Please see below screenshots of two adjacent micrographs from the logfile.pdf. The number of micrographs that were not processed is much higher than those that were. I'd say 90% of micrographs do not get processed. There is no warning, or message that fitting for those particular micrographs failed for any reason.

My job is as follows:
`relion_ctf_refine_mpi --i Refine3D/job027/run_data.star --f PostProcess/job043/postprocess.star --o CtfRefine/job044/ --fit_defocus --kmin_defocus 30 --fit_mode fpmff --only_do_unfinished  --j 2  --pipeline_control CtfRefine/job044/`

Any help would be greatly appreciated!

Cheers,

Kacper

![image](https://user-images.githubusercontent.com/37286209/79524473-a139eb80-802e-11ea-9f3d-0aa9001588f4.png)
![image](https://user-images.githubusercontent.com/37286209/79524496-ac8d1700-802e-11ea-9c94-bf9ab50c7f14.png)

**Comment by biochem-fan** [comment]
I have never seen this. Does this happen only for defocus refinement? Only for this dataset? What if you don't use MPI?

**Comment by krogala** [comment]
Hi Takanori,

I did a number of troubleshooting runs, and it looks like either with or without MPI, the result is the same. Also, it's happening for multiple datasets, with variable results (different proportion of failed micrographs).

I also tested running the same job with one of the following extra parameters (one at a time):
```
--bf0
--bf1
--bf_only
```

All three of them produce perfect refinement for all micrographs.

Any clues why that might be the case?

Cheers,

Kacper

**Comment by biochem-fan** [comment]
This means the gradient based refinement introduced in RELION 3.1 is not working properly on your system. But I don't know why.

Did you build RELION in single precision for CPU? (If you didn't explicitly specify in `cmake`, the default is double precision and safer)

**Comment by krogala** [comment]
Right, that would make sense.

Here's my cmake command:

`cmake -DFORCE_OWN_FLTK=ON -DCUDA=ON -DCudaTexture=ON -DCMAKE_INSTALL_PREFIX=/VR_3.1/relion/build/ ..`

The build completed perfectly.

I guess I will stick to using the Relion 3.0-style --bf0 refinements for now.

Would the 3.1 implementation give better results in terms of defocus estimation, or perhaps the update was purely speed-based?

**Comment by biochem-fan** [comment]
Can you try our tutorial dataset? If it also fails, something is wrong with your binary. What compiler did you use?

> Would the 3.1 implementation give better results in terms of defocus estimation, or perhaps the update was purely speed-based?
The new method is more robust, especially for astigmatism refinement.

**Comment by krogala** [comment]
Hiya,

I'm using GNU 5.4.0, MPICH 3.2.1 and cmake 3.5.1. All my builds have been working perfectly until now.

Actually, I always get one errors during building, but that never stopped the software from doing the jobs that I normally run (without symmetry operators):
```
CMake Error at src/apps/cmake_install.cmake:42 (file):
  file INSTALL cannot find
  "/VR_3.1/relion/build/bin/relion_align_symmetry".
Call Stack (most recent call first):
  cmake_install.cmake:53 (include)
```

I will take a look at the tutorial dataset.

Kacper

**Comment by biochem-fan** [comment]
No response. Closing...
