### ISSUE TITLE
Libtiff and other issues

### ISSUE THREAD

**Issue by iamabhik** [3dem/relion#608]
Hi all, 

I am new in running Relion so please be gentle with me :-) I have compiled Relion version 3.0 on macOS Mojave Version 10.14.6, 16 GB. Started doing the tutorial dataset and in the Motion correction step I see this error message,

**Command** 
++++ with the following command(s): 
`which relion_run_motioncorr` --i Import/job001/movies.star --o MotionCorr/job007/ --first_frame_sum 1 --last_frame_sum 0 --use_own  --j 12 --bin_factor 1 --bfactor 150 --angpix 0.885 --voltage 200 --dose_per_frame 1.277 --preexposure 0 --patch_x 5 --patch_y 5 --gainref Movies/gain.mrc --gain_rot 0 --gain_flip 0 --dose_weighting  
 ++++ 

**Error message** 
in: /Users/abhi/relion/src/image.h, line 206
=== Backtrace  ===
0   relion_run_motioncorr               0x000000010d50aa76 _ZN11RelionErrorC1ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES7_l + 102
1   ???                                 0x000000000000002f 0x0 + 47
==================
ERROR: 
TIFF support was not enabled during compilation

After trying several things, now I can’t figure out how to proceed.

First, I found that installing libtiff-devel and reinstalling Relion should solve the problem. So I installed libtiff-devel, here is the last few lines I got in the terminal, 

==> Downloading https://homebrew.bintray.com/bottles/libtiff-4.1.0.mojave.bottle
==> Downloading from https://akamai.bintray.com/dd/dd060521aa30fb2f4678c9ebab636
######################################################################## 100.0%
==> Pouring libtiff-4.1.0.mojave.bottle.tar.gz
🍺  /usr/local/Cellar/libtiff/4.1.0: 247 files, 3.6MB
W

At this stage, I tested Motion correction Job again just to check but it returned the same error. 

Next, I tried installing Relion again and there was a new error message in the terminal
“No Java runtime present, requesting install” so I installed Java 

Once again started installation, and now it is this error message, 
**Command**
build abhi$ sudo apt install cmake build-essential mpi-default-bin mpi-default-dev libfftw3-dev
Password:
**Error**
Unable to locate an executable at "/Library/Java/JavaVirtualMachines/jdk-14.0.1.jdk/Contents/Home/bin/apt" (-1)

Please let me know if there is something fundamentally wrong here, how do I specify the location of libtiff and java executable? 

Thank you for your time and help, 
Abhinav

**Comment by biochem-fan** [comment]
We don't officially support Mac OS X. CCPEM distributes pre-compiled binaries.
