### ISSUE TITLE
motion correction issue with TIFF support 

### ISSUE THREAD

**Issue by martiansmay** [3dem/relion#609]
Here is the thing. I compiled relion3.0.8 on ubuntu18 and try to process the test data set.
When I tried to run the motion correction job, an error saying "TIFF support was not enabled during compilation" occurred. 
I referred to the solution of adding libtiff-dev by ### `$sudo apt-get install libtiff-dev` . And it shows that it has been the latest version of `4.0.9-5ubuntu0.3`.
Then I recompiled relion and the cmake was like:
```
yuew@yuew-Blade:~/relion-3.0_beta/build$ cmake ..
-- BUILD TYPE set to the default type:  'Release'
-- Setting fallback CUDA_ARCH=35
-- CUDA enabled - Building CUDA-accelerated version of RELION
-- Setting cpu precision to double
-- Setting accelerated code precision to single
-- Using cuda wrapper to compile....
-- Cuda version is >= 7.5 and single-precision build, enable double usage warning.
-- Omitting GUI targets as per your request
-- MPI_INCLUDE_PATH : /usr/local/openmpi-4.0.3/include
-- MPI_LIBRARIES : /usr/local/openmpi-4.0.3/lib/libmpi.so
-- MPI_CXX_INCLUDE_PATH : /usr/local/openmpi-4.0.3/include
-- MPI_CXX_LIBRARIES : /usr/local/openmpi-4.0.3/lib/libmpi.so
-- CMAKE_C_COMPILER : /usr/bin/cc
-- CMAKE_CXX_COMPILER : /usr/bin/c++
-- MPI_C_COMPILER : /usr/local/openmpi-4.0.3/bin/mpicc
-- MPI_CXX_COMPILER : /usr/local/openmpi-4.0.3/bin/mpicxx
-- CMAKE_CXX_COMPILER_ID : GNU
-- Single-precision FFTW was required but NOT found
-- Double-precision FFTW was required but NOT found
-- Found previously built non-system single precision FFTW libraries that will be used.
-- Found previously built non-system double precision FFTW libraries that will be used.
BUILD_SHARED_LIBS = OFF
-- Building static libs (larger build size and binaries)
Running apps/CMakeLists.txt...
-- CMAKE_BINARY_DIR:/home/yuew/relion-3.0_beta
TIFF FOUND
OPENMP FOUND
-- Configuring done
-- Generating done
-- Build files have been written to: /home/yuew/relion-3.0_beta
```
Then I move back to motion correction and the same error of lacking TIFF support showed up again.
Is there anything I can do to get things correct?

**Comment by biochem-fan** [comment]
>  I recompiled relion

Please delete the build directory and start from scratch.

Please also stop using "RELION 3.0 beta". That is more than one year old. Please use 3.0 latest OR 3.1 beta.

**Comment by martiansmay** [comment]
> Please delete the build directory and start from scratch.
> Please also stop using "RELION 3.0 beta". That is more than one year old. Please use 3.0 latest OR 3.1 beta.
It worked. Thank you sooo much.
