### ISSUE TITLE
Issues with LoG particle picking during tutorial

### ISSUE THREAD

**Issue by girodat** [3dem/relion#618]
I am trying to go through the relion tutorial, however, when I tried to run an auto-picking job with Laplacian-of-Gaussian I receive the error:

in: /Users/dylangirodat/relion/src/metadata_table.cpp, line 1254
=== Backtrace  ===
0   relion_autopick                     0x000000010af37b86 _ZN11RelionErrorC1ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES7_l + 102
1   ???                                 0x000000000000003b 0x0 + 59
==================
ERROR: 
MetaDataTable::addToCPlot2D ERROR: cannot find x-axis label

Any ideas of what is going on?

I am running the relion tutorial on a Macbook pro.

Thanks.

**Comment by biochem-fan** [comment]
Are you using exactly the same option as tutorial?
Check "note.txt" in your job and that in pre-calculated results of the tutorial.

> I am running the relion tutorial on a Macbook pro.
I am afraid to say that we don't officially support Mac OS X.

**Comment by girodat** [comment]
Thanks for the information. It appeared that everything between my input and the tutorial was the same. However, since you said that you don't support Mac OS X I switched to a Linux machine and everything is working fine for the particle picker. 

Thank you.
