### ISSUE TITLE
Using 2D class from one project as template for another

### ISSUE THREAD

**Issue by Leotrosa** [3dem/relion#623]
**Hi I'm trying to use the result of a 2D classification from project1 as a template for autopicking in project2. I tried importing only the .mrcs from proect1-2Dselect file in project 2, but although the job run with no errors this leads to picking of random blobs and edges even though particles are easily recognizable in the images.
Manually picking 2k particles, classifying in project2 and using as template works well with the same autopicking parameters
 Do I have to import something else in project2 for this to work properly?

I really apologise if this is not the right space for these questions, I'm new to relion and did not find another space for questions. Thank you**

**Dataset:**
 - Box size: 220 pixels in both projects
 - Pixel size: 0.93 in both projects
 - Number of particles: 750 000 used to generate classes in project1
 - Description: hexameric ring 300kDa total
-autopicking log minimum 75A maximum 150A
-threshold 0.05

**Job options:**
 - Type of job: Importing/ Autopicking

**Comment by biochem-fan** [comment]
I guess the absolute contrast of two datasets is not common. In this case, you cannot re-use templates.
