### ISSUE TITLE
The optimal conditions for running Class2D

### ISSUE THREAD

**Issue by jianhaoc** [3dem/relion#625]
Hi, I have ~100k particles (box size: 72) for running Class2D on a 4* RTX2080Ti GPUs and 2* 10cores CPUs workstation. I'm looking for the optimal setting to submit a job. If I do Class2D for ~1 million particles, should I have a bit change on the setting? Thank you!

**Comment by biochem-fan** [comment]
For Class2D, you should put 2 MPI / GPU. Thus, I would run 9 MPI (remember rank 0 does not do anything), 3 threads. This is bit over-commiting (8 * 3 = 24 > 20) but should be fine. If you have not enabled HyperThreading in CPU, you should enable it and put 5 threads per MPI.
