### ISSUE TITLE
mpi jobs that run out of memory don't get killed

### ISSUE THREAD

**Issue by xeniorn** [3dem/relion#626]
If an MPI rank dies due to an out of memory error, only that MPI rank dies, but the whole process continues to run in zombie mode, not generating any outputs, but not terminating the scheduled job on the cluster. 

Asked our cluster management, they said this needs to be handled on the level of the MPI program and it's not an issue of our slurm scheduler. I don't know personally if this is true and it happens to other people.

observed with Class2D Class3D, probably happens with other things as well.

**Environment:**
 - OS: CentOS 7
 - MPI runtime: openmpi/3.1.1-gcccuda-2018b
 - RELION version 3.1-da823c1fa87839d84bad3edf348b391bdf54223b
- scheduler: slurm 18.08.8

**Comment by biochem-fan** [comment]
This is interesting. At LMB (OpenMPI 2.0.x), all MPI ranks are killed when one of them die.

Can you try adding `-mca orte_abort_on_non_zero_status 1` to `mpiexec` as explained in https://stackoverflow.com/questions/50273012/openmpi-doesnt-kill-other-rank-when-one-rank-crashes?

**Comment by xeniorn** [comment]
Didn't help unfortunately.

output:

`20200525_203830
Submission script version:  ja_clip_200128
Submitted from clip-login-1.cbe.vbc.ac.at using template script at
[REDACTED]
Module environment:
########################################
This job is being run through slurm on cluster clip (clip-login-1.cbe.vbc.ac.at / clip-g2-1.cbe.vbc.ac.at)
Job id: 4730177
MPI tasks: 5    ::    Cpus per task: 1
Memory per CPU: 13312    ::    Per node: unavailable
Partition: g
QOS: g_medium
Running user: juraj.ahel (Slurm user: cla)
Parent working folder: [REDACTED]

available GPUs (on master node - clip-g2-1.cbe.vbc.ac.at):
GPU 0: Tesla V100-PCIE-32GB (UUID: GPU-df0b3f3f-883d-383f-9bbc-eb882fafc9ba)
GPU 1: Tesla V100-PCIE-32GB (UUID: GPU-93822be3-a928-2973-c287-14ad8df1f941)
GPU 2: Tesla V100-PCIE-32GB (UUID: GPU-71b8fd5f-a126-66ec-91df-829fbaee919f)
GPU 3: Tesla V100-PCIE-32GB (UUID: GPU-48073c12-4bea-8159-5641-b1223f35fb71)
########################################

Successfully loaded EM framework by JA
RELION version: 3.1-beta-commit-GITDIR
Precision: BASE=double, CUDA-ACC=single

 === RELION MPI setup ===
 + Number of MPI processes             = 5
 + Master  (0) runs on host            = clip-g2-1.cbe.vbc.ac.at
 + Slave     1 runs on host            = clip-g2-1.cbe.vbc.ac.at
 + Slave     2 runs on host            = clip-g2-1.cbe.vbc.ac.at
 + Slave     3 runs on host            = clip-g2-1.cbe.vbc.ac.at
 =================
 + Slave     4 runs on host            = clip-g2-1.cbe.vbc.ac.at
 uniqueHost clip-g2-1.cbe.vbc.ac.at has 4 ranks.
GPU-ids not specified for this rank, threads will automatically be mapped to available devices.
 Thread 0 on slave 1 mapped to device 0
GPU-ids not specified for this rank, threads will automatically be mapped to available devices.
 Thread 0 on slave 2 mapped to device 1
GPU-ids not specified for this rank, threads will automatically be mapped to available devices.
 Thread 0 on slave 3 mapped to device 2
GPU-ids not specified for this rank, threads will automatically be mapped to available devices.
 Thread 0 on slave 4 mapped to device 3
 Running CPU instructions in double precision.
 + WARNING: Changing psi sampling rate (before oversampling) to 11.25 degrees, for more efficient GPU calculations
`

error:

`slurmstepd: error: Detected 1 oom-kill event(s) in step 4730177.0 cgroup. Some of your processes may have been killed by the cgroup out-of-memory handler.
srun: error: clip-g2-1: task 2: Out Of Memory`

Input file has 11 million particles, 64 px size. 

Best

J

**Comment by xeniorn** [comment]
Don't have the info at hand but indeed I think our jobs die normally out of memory when they die later (e.g. in Refine3D when reaching final iteration and there is insufficient memory for it), but not when it's this early

**Comment by biochem-fan** [comment]
Hmm, this is difficult.

This is a highly technical issue that needs coordination between the job manager, Linux cgroup and client processes. I think your IT people can solve it by tweaking settings, but if they don't want to invest time on this, there is not much RELION alone can do.

**Comment by xeniorn** [comment]
Ok, thanks Takanori. I can't assess myself what the root cause is, but at this point it's you telling me it's about the system settings, and the IT folks telling me it's on the software side, will see if I can goad in some further investigation.

**Comment by xeniorn** [comment]
Just to note, possibly will help other people with a similar problem. We use the slurm submission system. With using srun, the problem persisted, but if using "mpirun" directly, it behaved as it should with the flag biochem-fan noted.
