### ISSUE TITLE
Relion GUI closes after 3600s even when the idle option has set to longer time 

### ISSUE THREAD

**Issue by JuhaHuiskonen** [3dem/relion#636]
I start the RELION GUI with the command
> relion --idle=10000000

I would not expect RELION GUI to close automatically, however I get this after 3600s:

The relion GUI has been idle for more than 3600 seconds, exiting now... 
[4]   Done                    relion --idle=10000000

**Comment by biochem-fan** [comment]
You shouldn't put `=`. Just say `--idle 1000000`.

**Comment by JuhaHuiskonen** [comment]
OK, perhaps the usage needs to be updated, currently it says:

 [--idle=3600]  : quit GUI after this many second

**Comment by biochem-fan** [comment]
Oops, I will fix it. Thanks for pointing this out.
