### ISSUE TITLE
Possible confusion of fftw.h bitwise operation

### ISSUE THREAD

**Issue by do-jason** [3dem/relion#637]
There is one line of code which may cause confusion to compiler and/or user in bitwise operation in fftw.h file

Line #392 in 3.1 branch is:

        if ((k ^ i ^ j) & 1 != 0) // if ODD

Since logical "!=" has higher precedence than bitwise operation compiler will treat this as below and (1 != 0) is always true.

        if ((k ^ i ^ j) & (1 != 0)) // if ODD

So I think the below is what is meant.

        if (((k ^ i ^ j) & 1) != 0) // if ODD

**Comment by biochem-fan** [comment]
Thanks for pointing out!

Fortunately, `if ((k ^ i ^ j) & (1 != 0))` is the same as `if ((k ^ i ^ j) & true)`, so the behavior is the same (i.e. checking if the last bit is 1 or not). Nonetheless I will fix the code.
