### ISSUE TITLE
Error with Relion 3.1.0 install

### ISSUE THREAD

**Issue by Rick-Baker** [3dem/relion#642]
Hi,

I am having issues with the new Relion 3.1.0 release.

I can install 3.1.0 with the following cmake command and it finishes with no errors. 
`cmake -DFORCE_OWN_FLTK=ON -DFORCE_OWN_FFTW=ON ..`

However, when I try to open the Relion GUI I get this error:
relion: symbol lookup error: relion: undefined symbol: _ZN8Fl_ImageC2Eiii

This issue has been raised for users on 3.0.X, and seems to be related to FLTK libraries. However, I included the required flag to get around this. Also, the correct path is in $LD_LIBRARY_PATH and libfltk.so.1.3 is also in the right directory.

I can install Relion 3.0.8 with the exact same command and have no issues.

Any insight would be great! thanks! 

Thanks!
Rick

**Comment by biochem-fan** [comment]
What does `ldd /path/to/bin/relion` say?

**Comment by Rick-Baker** [comment]
`ldd /data/software/repo/relion/3.1.0/bin/relion
	linux-vdso.so.1 =>  (0x00007ffc445c5000)
	libcufft.so.10 => /usr/local/cuda-10.1/lib64/libcufft.so.10 (0x00007f867b815000)
	libmpi_cxx.so.1 => /usr/lib64/openmpi/lib/libmpi_cxx.so.1 (0x00007f867b5fa000)
	libmpi.so.12 => /usr/lib64/openmpi/lib/libmpi.so.12 (0x00007f867b316000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f867b112000)
	libfltk.so.1.3 => /usr/local/lib/libfltk.so.1.3 (0x00007f867ae3a000)
	libtiff.so.5 => /lib64/libtiff.so.5 (0x00007f867abc6000)
	libfftw3f.so.3 => /data/software/repo/relion/3.1.0/lib/libfftw3f.so.3 (0x00007f867a7b8000)
	libfftw3.so.3 => /data/software/repo/relion/3.1.0/lib/libfftw3.so.3 (0x00007f867a437000)
	libcurand.so.10 => /usr/local/cuda-10.1/lib64/libcurand.so.10 (0x00007f86763d6000)
	libpng15.so.15 => /lib64/libpng15.so.15 (0x00007f86761ab000)
	libcudart.so.10.1 => /usr/local/cuda-10.1/lib64/libcudart.so.10.1 (0x00007f8675f2f000)
	libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007f8675c28000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f8675926000)
	libgomp.so.1 => /lib64/libgomp.so.1 (0x00007f8675700000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f86754ea000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f86752ce000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f8674f00000)
	librt.so.1 => /lib64/librt.so.1 (0x00007f8674cf8000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f8683e57000)
	libopen-rte.so.12 => /usr/lib64/openmpi/lib/libopen-rte.so.12 (0x00007f8674a7c000)
	libopen-pal.so.13 => /usr/lib64/openmpi/lib/libopen-pal.so.13 (0x00007f86747d8000)
	libutil.so.1 => /lib64/libutil.so.1 (0x00007f86745d5000)
	libhwloc.so.5 => /lib64/libhwloc.so.5 (0x00007f8674398000)
	libXcursor.so.1 => /lib64/libXcursor.so.1 (0x00007f867418d000)
	libXfixes.so.3 => /lib64/libXfixes.so.3 (0x00007f8673f87000)
	libXext.so.6 => /lib64/libXext.so.6 (0x00007f8673d75000)
	libXft.so.2 => /lib64/libXft.so.2 (0x00007f8673b5f000)
	libfontconfig.so.1 => /lib64/libfontconfig.so.1 (0x00007f867391d000)
	libXinerama.so.1 => /lib64/libXinerama.so.1 (0x00007f867371a000)
	libX11.so.6 => /lib64/libX11.so.6 (0x00007f86733dc000)
	libjbig.so.2.0 => /lib64/libjbig.so.2.0 (0x00007f86731d0000)
	libjpeg.so.62 => /lib64/libjpeg.so.62 (0x00007f8672f7b000)
	libz.so.1 => /lib64/libz.so.1 (0x00007f8672d65000)
	libnuma.so.1 => /lib64/libnuma.so.1 (0x00007f8672b5a000)
	libltdl.so.7 => /lib64/libltdl.so.7 (0x00007f8672950000)
	libXrender.so.1 => /lib64/libXrender.so.1 (0x00007f8672745000)
	libfreetype.so.6 => /lib64/libfreetype.so.6 (0x00007f8672486000)
	libexpat.so.1 => /lib64/libexpat.so.1 (0x00007f867225c000)
	libuuid.so.1 => /lib64/libuuid.so.1 (0x00007f8672057000)
	libxcb.so.1 => /lib64/libxcb.so.1 (0x00007f8671e2f000)
	libbz2.so.1 => /lib64/libbz2.so.1 (0x00007f8671c1f000)
	libXau.so.6 => /lib64/libXau.so.6 (0x00007f8671a1b000)`

**Comment by Rick-Baker** [comment]
ldd /data/software/repo/relion/3.1.0/bin/relion
	linux-vdso.so.1 =>  (0x00007ffc445c5000)
	libcufft.so.10 => /usr/local/cuda-10.1/lib64/libcufft.so.10 (0x00007f867b815000)
	libmpi_cxx.so.1 => /usr/lib64/openmpi/lib/libmpi_cxx.so.1 (0x00007f867b5fa000)
	libmpi.so.12 => /usr/lib64/openmpi/lib/libmpi.so.12 (0x00007f867b316000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f867b112000)
	libfltk.so.1.3 => /usr/local/lib/libfltk.so.1.3 (0x00007f867ae3a000)
	libtiff.so.5 => /lib64/libtiff.so.5 (0x00007f867abc6000)
	libfftw3f.so.3 => /data/software/repo/relion/3.1.0/lib/libfftw3f.so.3 (0x00007f867a7b8000)
	libfftw3.so.3 => /data/software/repo/relion/3.1.0/lib/libfftw3.so.3 (0x00007f867a437000)
	libcurand.so.10 => /usr/local/cuda-10.1/lib64/libcurand.so.10 (0x00007f86763d6000)
	libpng15.so.15 => /lib64/libpng15.so.15 (0x00007f86761ab000)
	libcudart.so.10.1 => /usr/local/cuda-10.1/lib64/libcudart.so.10.1 (0x00007f8675f2f000)
	libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007f8675c28000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f8675926000)
	libgomp.so.1 => /lib64/libgomp.so.1 (0x00007f8675700000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f86754ea000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f86752ce000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f8674f00000)
	librt.so.1 => /lib64/librt.so.1 (0x00007f8674cf8000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f8683e57000)
	libopen-rte.so.12 => /usr/lib64/openmpi/lib/libopen-rte.so.12 (0x00007f8674a7c000)
	libopen-pal.so.13 => /usr/lib64/openmpi/lib/libopen-pal.so.13 (0x00007f86747d8000)
	libutil.so.1 => /lib64/libutil.so.1 (0x00007f86745d5000)
	libhwloc.so.5 => /lib64/libhwloc.so.5 (0x00007f8674398000)
	libXcursor.so.1 => /lib64/libXcursor.so.1 (0x00007f867418d000)
	libXfixes.so.3 => /lib64/libXfixes.so.3 (0x00007f8673f87000)
	libXext.so.6 => /lib64/libXext.so.6 (0x00007f8673d75000)
	libXft.so.2 => /lib64/libXft.so.2 (0x00007f8673b5f000)
	libfontconfig.so.1 => /lib64/libfontconfig.so.1 (0x00007f867391d000)
	libXinerama.so.1 => /lib64/libXinerama.so.1 (0x00007f867371a000)
	libX11.so.6 => /lib64/libX11.so.6 (0x00007f86733dc000)
	libjbig.so.2.0 => /lib64/libjbig.so.2.0 (0x00007f86731d0000)
	libjpeg.so.62 => /lib64/libjpeg.so.62 (0x00007f8672f7b000)
	libz.so.1 => /lib64/libz.so.1 (0x00007f8672d65000)
	libnuma.so.1 => /lib64/libnuma.so.1 (0x00007f8672b5a000)
	libltdl.so.7 => /lib64/libltdl.so.7 (0x00007f8672950000)
	libXrender.so.1 => /lib64/libXrender.so.1 (0x00007f8672745000)
	libfreetype.so.6 => /lib64/libfreetype.so.6 (0x00007f8672486000)
	libexpat.so.1 => /lib64/libexpat.so.1 (0x00007f867225c000)
	libuuid.so.1 => /lib64/libuuid.so.1 (0x00007f8672057000)
	libxcb.so.1 => /lib64/libxcb.so.1 (0x00007f8671e2f000)
	libbz2.so.1 => /lib64/libbz2.so.1 (0x00007f8671c1f000)
	libXau.so.6 => /lib64/libXau.so.6 (0x00007f8671a1b000)

**Comment by biochem-fan** [comment]
> libfltk.so.1.3 => /usr/local/lib/libfltk.so.1.3 (0x00007f867ae3a000)

This is the problem. You are using a wrong FLTK library. Is the order of paths in your `LD_LIBRARY_PATH` correct?

**Comment by Rick-Baker** [comment]
echo $LD_LIBRARY_PATH
/usr/local/lib:/usr/local/cuda-10.1/lib64:/data/software/repo/relion/3.1.0/lib:/usr/lib64/openmpi/lib:/usr/local/cuda-8.0/lib64:/usr/local/lib:/usr/local/cuda-10.1/lib64:/usr/local/IMOD/lib:/usr/local/bsoft/lib

ok, that seems like the likely problem.

**Comment by biochem-fan** [comment]
The first one has the highest priority. Thus, it should be ordered from something specific to something more general.

I would set:

`/usr/local/IMOD/lib:/usr/local/bsoft/lib:/data/software/repo/relion/3.1.0/lib:/usr/lib64/openmpi/lib:/usr/local/cuda-10.1/lib64:/usr/local/cuda-8.0/lib64:/usr/local/lib`
