### ISSUE TITLE
corrected_micrographs.star file entry 4, 5 and 6.

### ISSUE THREAD

**Issue by fbonnet08** [3dem/relion#644]
Hi,

I have a question about the following relion keys:

_rlnAccumMotionTotal #4 
_rlnAccumMotionEarly #5 
_rlnAccumMotionLate #6 

After the motion corr has been calculated using MotionCor2_v1.3.1-Cuda102 within Relion-3.1.0, in the corrected_micrographs.star star file we get entries such as:

MotionCorr/job016/Micrographs/FoilHole_18180471_Data_18181927_18181929_20200618_233150_fractions.mrc MotionCorr/job016/Micrographs/FoilHole_18180471_Data_18181927_18181929_20200618_233150_fractions.star            1    36.612271     8.74079
8    27.871472

for example.

which corresponds to 
_rlnMicrographName #1 
_rlnMicrographMetadata #2 
_rlnOpticsGroup #3 
_rlnAccumMotionTotal #4 
_rlnAccumMotionEarly #5 
_rlnAccumMotionLate #6 

About #4, 5 and 6. Are these calculated inside relion following a parsing of the MotionCor2_v1.3.1-Cuda102 or a straight parsing?

If a straight parsing which file is being parsed?

If calculated within relion how are these calculated and from which input data log file coming from MotionCor2_v1.3.1-Cuda102?

Frederic.

**Comment by biochem-fan** [comment]
The trajectory is read from the standard output of UCSF MotionCor2, which is redirected to `*.out`.
The values are under `Full-frame alignment shift`.

Then shifts are integrated before/after 4e/A2 (or the value specified in `--dose_motionstats_cutoff`).

**Comment by fbonnet08** [comment]
Ok Thanks,
I see the values under Full-frame alignment shift

for the
_rlnAccumMotionTotal #4 
_rlnAccumMotionEarly #5 
_rlnAccumMotionLate #6
I get  36.612271     8.740798    27.871472 in the 

In the .out for the Full-frame alignment shift I get the following

Full-frame alignment shift
...... Frame (  1) shift:     0.000      0.000
...... Frame (  2) shift:     2.660     -4.750
...... Frame (  3) shift:     2.820     -6.760
...... Frame (  4) shift:     3.340     -7.930
...... Frame (  5) shift:     1.950     -8.090
...... Frame (  6) shift:     1.980     -7.810
...... Frame (  7) shift:     1.350     -8.110
...... Frame (  8) shift:     0.810     -8.580
...... Frame (  9) shift:     0.620     -8.280
...... Frame ( 10) shift:    -0.020     -7.540
...... Frame ( 11) shift:    -0.390     -7.470
...... Frame ( 12) shift:     0.330     -7.000
...... Frame ( 13) shift:    -0.390     -7.550
...... Frame ( 14) shift:     0.000     -7.160
...... Frame ( 15) shift:    -0.350     -7.120
...... Frame ( 16) shift:    -0.590     -7.250
...... Frame ( 17) shift:    -0.750     -7.430
...... Frame ( 18) shift:    -0.390     -6.960
...... Frame ( 19) shift:    -0.780     -6.350
...... Frame ( 20) shift:     0.000     -7.440
...... Frame ( 21) shift:    -0.520     -7.410
...... Frame ( 22) shift:    -0.070     -6.880
...... Frame ( 23) shift:    -0.210     -6.920
...... Frame ( 24) shift:     0.610     -6.200
...... Frame ( 25) shift:    -0.330     -6.700
...... Frame ( 26) shift:    -0.280     -6.830
...... Frame ( 27) shift:    -0.390     -6.480
...... Frame ( 28) shift:    -0.460     -6.970
...... Frame ( 29) shift:    -0.040     -6.750
...... Frame ( 30) shift:     0.140     -6.690
...... Frame ( 31) shift:    -0.120     -6.800
...... Frame ( 32) shift:    -0.090     -6.330
...... Frame ( 33) shift:    -0.140     -6.300
...... Frame ( 34) shift:    -0.270     -6.450
...... Frame ( 35) shift:     0.230     -5.590
...... Frame ( 36) shift:     0.230     -6.360
...... Frame ( 37) shift:     0.230     -6.590
...... Frame ( 38) shift:    -0.170     -5.490
...... Frame ( 39) shift:     0.100     -5.740
...... Frame ( 40) shift:    -0.430     -6.240
...... Frame ( 41) shift:    -0.370     -6.000
...... Frame ( 42) shift:    -0.790     -5.880
...... Frame ( 43) shift:    -0.550     -5.370
...... Frame ( 44) shift:    -0.860     -5.820
...... Frame ( 45) shift:    -0.320     -5.680
...... Frame ( 46) shift:     0.180     -5.370
...... Frame ( 47) shift:    -0.340     -5.260
...... Frame ( 48) shift:     0.290     -4.530
...... Frame ( 49) shift:    -0.080     -5.340
...... Frame ( 50) shift:    -0.470     -4.700
...... Frame ( 51) shift:    -1.150     -4.850


Sorry, but how do you get 36.612271     8.740798    27.871472 ?

Frederic.

**Comment by biochem-fan** [comment]
Shift from frame 1 to 0 is sqrt((2.660 - 0.000)^ 2 + (-4.750 - 0.000)^2),
Shift from frame 2 to 1 is sqrt((2.820 - 2.660)^ 2 + (-6.760 + 4.750)^2)
and so on.

Add these shifts until 4 e/A2. That is Early. Add the others to get Late. Add both to get Total.

**Comment by fbonnet08** [comment]
I can see how the file:
Micrographs/FoilHole_18180471_Data_18181927_18181929_20200618_233150_fractions.star

is constructed. 

If I understand this correctly:

shift 0 [1--->0]=  sqrt((2.660 - 0.000)^ 2 + (-4.750 - 0.000)^2) = 5,444088537
shift 1 [2--->1]=  sqrt((2.820 - 2.660)^ 2 + (-6.760 + 4.750)^2) = 2,016358103
....
shift i [i+1--->i]=  sqrt((x_i - x_(i-1))^ 2 + (y_i - y_(i-1))^2) = s_i
....
shift 50 [51--->50]=  sqrt((-1.150 - -0.470)^ 2 + (-4.850 - -4.700)^2) = 0,696347614

Sum_{i=0}^{50} (s_i) = Total

But I do not understand exactly what you mean numerically but understand what you roughly mean. 
Add these shifts until **4 e/A2**. That is Early.
Add the others to get Late. 
Add both to get Total.

**Comment by biochem-fan** [comment]
If this is 1e/A2/frame, shift 0 to 4 becomes early motion. Shift 4 to the end becomes late motion.
