### ISSUE TITLE
Is xend_z assignment of wavg.h bug or not?

### ISSUE THREAD

**Issue by do-jason** [3dem/relion#646]
"else" statement starting from line 227of src/acc/cpu/cpu_kernels/wavg.h file is not enclosed with bracket.
"if (z>projector.maxR)" condition is met, xend_z is always xstart_z+1 regardless of "if (z >= zSize - projector.maxR)".
Is it intended or bug?

		int xstart_z = 0, xend_z = xSize;
		int z = iz;
		if (z > projector.maxR)
		{
			if (z >= zSize - projector.maxR)
				z = z - projector.imgZ;
			else
				xstart_z = projector.maxR;
				xend_z   = xstart_z + 1;
		}

**Comment by do-jason** [comment]
The same patter appears in src/acc/cpu/cpu_kernels/diff2.h file as well.
Line 688, 987, and 1310 belongs to this.

**Comment by biochem-fan** [comment]
I _guess_ this is a bug but I am not confident. This is a tomography code I don't use.

Can @dkimanius, @joton or @scheres confirm? Did @CharlesCongdon write this?

**Comment by biochem-fan** [comment]
@joton is looking at this.

**Comment by CharlesCongdon** [comment]
Yes, looks like an error on my part.   You are right, there should be braces there.

**Comment by CharlesCongdon** [comment]
I've created a pull request for this issue.   If it checks out and can be merged, please close this issue.  Thanks!

**Comment by joton** [comment]
Thank you @CharlesCongdon.
