### ISSUE TITLE
Failure to compile with MKLFFT

### ISSUE THREAD

**Issue by biochem-fan** [3dem/relion#648]
RELION fails to compile with `-DMKLFFT=ON` if you don't have `fftw3.h` in a standard location (e.g. `/usr/include`).

This is because our `CMakeList.txt` does not look at MKL-provided header files, although it can nonetheless link against MKL if `mklvars.sh` was sourced.

**Comment by do-jason** [comment]
I would like to suggest the below change to include MKL header file in CMakeList.txt.

    if(MKLFFT)
        if (NOT "$ENV{MKLROOT}" STREQUAL "")
            include_directories("$ENV{MKLROOT}/include/fftw")
            message(STATUS "Using MKL FFTW wrapper include directory : $ENV{MKLROOT}/include/fftw")
        else()
            message("COMPILATION MAY FAIL since no MKL FFTW wrapper include directory found")
        endif()
        add_definitions(-DMKLFFT)
    endif(MKLFFT)

**Comment by biochem-fan** [comment]
Thanks! I will incorporate this.
