### ISSUE TITLE
Question about relion_star_handler expected output

### ISSUE THREAD

**Issue by frozenfas** [3dem/relion#651]
I am using relion_star_handler to compare 2 files based on the rlnImageName such that I would like to keep the entries in the input file (--i) that are also shared in the --compare file.  The command runs fine but in the output files I get the data_optics table from the --compare files but the data_particles tables from the --i file.  As you can see below in this case it seems to output a file with the _rlnCtfDataAreCtfPremultiplied = 0 (last column) even though in my input the _rlnCtfDataAreCtfPremultiplied = 1. Is this expected and I am misusing the command? 

### Info:
CentOS
RELION version: 3.1.0-commit-902010 
Precision: BASE=double, CUDA-ACC=single 

### Command:

`relion_star_handler --i shiny.star --o shiny_ctfmult-refine135 --compare ../../Refine3D/job135/run_data.star --label1 rlnImageName`

### Output ( A line from the optics group table for the --i, --o, and --compare files)

data_optics = shiny.star (--i) 
```
opticsGroup-1621            2 mtf_k2_300kV.star     1.086000   300.000000     2.700000     0.100000     1.086000          300            2     3.801000     2.143022  
   2.918687     1.000958     0.001087     0.001367     1.004498            1
```

data_optics = shiny_ctfmult-refine135 (--o; output here has same data as the --compare file)
```
opticsGroup-1621            2 mtf_k2_300kV.star     1.086000   300.000000     2.700000     0.100000     1.520400          320            2     3.801000     2.143022  
   2.918687     1.000958     0.001087     0.001367     1.004498            0 
```

data_optics = Refine3D/job135/run_data.star (--compare)
```
opticsGroup-1621            2 mtf_k2_300kV.star     1.086000   300.000000     2.700000     0.100000     1.520400          320            2     3.801000     2.143022  
   2.918687     1.000958     0.001087     0.001367     1.004498            0 
```

### Out ( A line from the particle data table for the --i, --o, and --compare files)

data_particles = shiny.star (--i) 
` 2103.000000   669.500000            1    77.055275   -999.00000 2@Polish/job115/Movies/FoilHole_4203508_Data_4204001_4204002_20170105_1636-40615-Fractions_shiny.mrcs MotionCorr/job003/Movies/FoilHole_4203508_Data_4204001_4204002_20170105_1636-40615-Fractions.mrc            1     3.566042     0.269703 12003.109518 10517.083436    93.804376     0.000000     1.000000     0.000000   170.878781    78.623445     -0.11810     -0.60843     0.474446 4.317258e+05     0.238208           10 group_0037            1            1 000001@Subtract/job089/Particles/subtracted_rank2_opticsgroup1.mrcs` 

data_particles = shiny_ctfmult-refine135 (--o; output here has same data as the --i file))
 `2103.000000   669.500000            1    77.055275   -999.00000 2@Polish/job115/Movies/FoilHole_4203508_Data_4204001_4204002_20170105_1636-40615-Fractions_shiny.mrcs MotionCorr/job003/Movies/FoilHole_4203508_Data_4204001_4204002_20170105_1636-40615-Fractions.mrc            1     3.566042     0.269703 12003.109518 10517.083436    93.804376     0.000000     1.000000     0.000000   170.878781    78.623445     -0.11810     -0.60843     0.474446 4.317258e+05     0.238208           10 group_0037            1            1 000001@Subtract/job089/Particles/subtracted_rank2_opticsgroup1.mrcs`

data_particles = Refine3D/job135/run_data.star (--compare)
`2103.000000   669.500000            1    77.164934   -999.00000 2@Polish/job115/Movies/FoilHole_4203508_Data_4204001_4204002_20170105_1636-40615-Fractions_shiny.mrcs MotionCorr/job003/Movies/FoilHole_4203508_Data_4204001_4204002_20170105_1636-40615-Fractions.mrc            1     3.566042     0.269703 12003.109518 10517.083436    93.804376     0.000000     1.000000     0.000000   170.435220    80.695760     0.080103     -0.36005     0.615676 4.124805e+05     0.529129            2 group_0037            1            1 000001@Subtract/job089/Particles/subtracted_rank2_opticsgroup1.mrcs`

**Comment by biochem-fan** [comment]
This sounds like a bug. For the time being, you might be able to achieve this by https://github.com/cdienem/StarTool.

**Comment by frozenfas** [comment]
Thanks.  That looks really interesting.  I guess just swapping the data_optics by hand is also ok?

**Comment by biochem-fan** [comment]
Yes, you should use the optics table from `shiny.star`.

**Comment by biochem-fan** [comment]
Can you test the above commit (05beaae) in the `ver3.1` branch?

**Comment by frozenfas** [comment]
Yes, it it giving the expected output now.

Thanks
