### ISSUE TITLE
CTFrefine error with tutorial data set

### ISSUE THREAD

**Issue by Hyunmisong** [3dem/relion#652]
This is a template for asking questions and reporting bugs. Please fill in as much information as you can.

During the exercise with tutorial data set, I did every thing same as the Tutorial PDF. 
But the CTF refinement and Bayesian Polishing is not working. 
They just show infinite left time.
So I tried with command line, and it showed error message "Segmentation fault (core dumped)"

And I tried to do that job with Precalculated data, and It worked. 
I don't know why this happend.

Please write a clear description of what the problem is.

**Environment:**
 - OS: CentOS 7 
 - MPI runtime: OpenMPI 4.0.2
 - RELION version RELION-3.1.0-commit-902010
 - Memory: 256 GB
 - GPU: [e.g. GTX 1080Ti]

**Dataset:**
 -Tutorial dataset

**Job options:**
 - Type of job: CTF refinement & Bayesian Polishing
 - Number of MPI processes: 1
 - Number of threads: 12
 - Full command (see `note.txt` in the job directory):
   ```
`which relion_ctf_refine` --i Refine3D/job029/run_data.star --f PostProcess/job038/postprocess.star --o CtfRefine/job046/ --fit_beamtilt --kmin_tilt 30 --odd_aberr_max_n 3 --fit_aberr --j 12 --angpix_ref 1.244 --pipeline_control CtfRefine/job046/
   ```

**Error message:**
 + Reading Refine3D/job029/run_data.star...
 + Reading references ...
 + The names of the reference half maps and the mask were taken from the PostProcess STAR file.
   - Half map 1: Refine3D/job029/run_half1_class001_unfil.mrc
   - Half map 2: Refine3D/job029/run_half2_class001_unfil.mrc
   - Mask: MaskCreate/job037/mask.mrc
 + Masking references ...
 + Transforming references ...
 + Performing loop over all micrographs ... 
000/??? sec ~~(,_,">                                                          [oo]Segmentation fault (core dumped)

```

**Comment by biochem-fan** [comment]
Is postprocess job038 based on Refine job029?
Does the FSC look OK?

Why did you add `--angpix_ref 1.244`? This should not be necessary.

**Comment by Hyunmisong** [comment]
when I use CTF refine, relion show warning that --angpix_ref is not designated so I added it.

**Comment by Hyunmisong** [comment]
> Is postprocess job038 based on Refine job029?
> Does the FSC look OK?
> 
> Why did you add `--angpix_ref 1.244`? This should not be necessary.
I put the right Input file in the process...

I think my FSC graph is okay because the red line at the resolution is around 0.
What else can I do??

**Comment by biochem-fan** [comment]
> relion show warning that --angpix_ref is not designated so I added it.
It shows the warning but you don't have to add it.

**Comment by Hyunmisong** [comment]
> > relion show warning that --angpix_ref is not designated so I added it.
> 
> It shows the warning but you don't have to add it.

Thanks.
Even though I removed it, it still not working.
And I'm wondering why relion GUI didn't show the message segmentation fault. 
It only showed the message when I run it with command

**Comment by Hyunmisong** [comment]
> > relion show warning that --angpix_ref is not designated so I added it.
> 
> It shows the warning but you don't have to add it.
> 
> I don't know what is wrong. The fact that pre-calculated results worked means that you did something wrong during processing, but I cannot tell without looking at your directory.

Also, I used 3 MPI during some former processes, but in the CTF refinement step, MPIRUN error is made, so I only can use 1 MPI

**Comment by biochem-fan** [comment]
> MPIRUN error is made

What did it say?

What happens if you run only defocus fitting? What about beam tilt only?

**Comment by Hyunmisong** [comment]
> > MPIRUN error is made
> 
> What did it say?
> 
> What happens if you run only defocus fitting? What about beam tilt only?


This it the error message when I used 3 MPI
mpirun noticed that process rank 1 with PID 0 on node cryo-work02 exited on signal 11 (Segmentation fault).

And it doesn't work when I run only defocus or beam tilt.

**Comment by biochem-fan** [comment]
Make sure your half maps and the mask have the same box size and does not contain NaNs.
(use `relion_image_handler --stats`)

**Comment by biochem-fan** [comment]
I cannot reproduce locally.
