### ISSUE TITLE
Schedules do not abort

### ISSUE THREAD

**Issue by azazellochg** [3dem/relion#655]
I have 3 schedules running in parallel. I open relion GUI and for each of them press Abort. It creates abort files for the current job and the schedule. However nothing stops. The schedules keep running and the abort files inside job folders disappear. The only abort files left are in schedule folders but this doesn't make it stop.

**Environment:**
 - OS: Linux em-pc-5 5.7.0-1-amd64 #1 SMP Debian 5.7.6-1 (2020-06-24) x86_64 GNU/Linux
 - RELION version RELION version: 3.1.0-commit-a96ba9 
Precision: BASE=double, CUDA-ACC=single

**Comment by biochem-fan** [comment]
(For records)

I got a test case in private but could not reproduce the issue.

**Comment by biochem-fan** [comment]
It turned out that one needs `--pipeline_control Schedules/schedule_name/` in addition to `relion_scheduler --schedule schedule_name --run`.
