### ISSUE TITLE
change FORCE_OWN_FFTW url?

### ISSUE THREAD

**Issue by craigyk** [3dem/relion#659]
Can the URL used by the build system (cmake/BuildFFTW.cmake) be switched to http://fftw.org/fftw-3.3.4.tar.gz instead of the FTP address?  For reasons unknown, I've seen the FTP link fail to download in the past, breaking new builds.  The http url has been a lot more reliable in my experience.

**Comment by biochem-fan** [comment]
Sure. This will be changed in 3.1.1.
