### ISSUE TITLE
Subtraction with re-centering and/or re-sizing should provide new reference

### ISSUE THREAD

**Issue by bforsbe** [3dem/relion#664]
A subtraction with re-centering on the mask, and/or change in box-size of subtracted particles need a new 3D reference as input. It would be nice if RELION also output the re-centered/re-sized reference that was used for subtraction, so that there is a good starting  model for subsequent steps. 

I can make suggested code changes, but don't have the time at the moment. Also wanted to float the idea first.

**Comment by bforsbe** [comment]
For documentation one could of course just run 

```relion_reconstruct --i Subtract/jobXXX/particles_subtracted.star --o new_reference.mrc```

**Comment by biochem-fan** [comment]
Or you can improve the message in https://github.com/3dem/relion/blob/ver3.1/src/particle_subtractor.cpp#L154 to suggest the actual command line ("relion_image_handler ..."). I don't think it is a good idea to actually perform such shifts on the reference and the mask in particle subtractor itself. It is duplication of functionality.
