### ISSUE TITLE
How to generate the ctf-corrected image with RELION?

### ISSUE THREAD

**Issue by FrankZhang0309** [3dem/relion#665]
When I followed the full tutorial to process the data, and finally get the 3D volume of the particle. I believe that RELION must do the CTF correction to all the images with optical parameters and estimated defocus value.

So my question is: When I finished estimating the CTF parameters for the micrographs and the images(particles), **How can I directly get the ctf-corrected images?** I want to do some analysis with images.

If I have to write the code, can you notify me of the part of the code I need to write?

Sincerely,
Jiakai

**Comment by biochem-fan** [comment]
You cannot "get the ctf-corrected images". Traditionally this has been approximated by CTF phase flipping, but this is not ideal. It only corrects for sign changes. Because of CTF zeros, you cannot "correct" individual images.

**Comment by FrankZhang0309** [comment]
@biochem-fan Thanks for your kind reply. With my understanding of CTF, maybe we can correct the images in Fourier domain, as we know defocus value per image and other CTF parameters per micrograph? I wonder if RELION divide CTF in Fourier domain(back focal plane image), in other words, how RELION do ctf-correction in 3D refine procedure? Can I just do a simple inverse Fourier transform to get a less frequency lossed micrograph or image? If yes, what should I do? If no, where is the misunderstanding in my intuition?

Looking forward to your reply~

Best,
Jiakai

**Comment by biochem-fan** [comment]
>  divide CTF in Fourier domain

The basic idea is this, but you cannot apply this to individual micrographs, because you cannot divide by zero where CTF crosses 0. CTF close to 0 (say 0.0001) is also problematic, because tiny errors will be amplified significantly.

When you have multiple images, you don't have this problem, because we divide after summing all particles and all CTFs. See eq. 3 of https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3690530/.

**Comment by FrankZhang0309** [comment]
@biochem-fan Thanks for your answer. I think I know your meaning, I would like to close this issue, and if I have some further confusion, I may re-open this issue XD. Thanks a lot.
