### ISSUE TITLE
UI failure

### ISSUE THREAD

**Issue by Zouxxyy** [3dem/relion#666]
I tried to install relion, After the installation is complete, and start to use theUI interface,  is a bit strange, as shown in the figure. 
Is this common, or am I missing something? 

![zzzz](https://user-images.githubusercontent.com/37108074/91515270-62406e80-e91b-11ea-9881-296aceb29ada.jpg)

Here are my steps，my linux version is CentOS Linux release 7.7.1908

```bash
wget https://download.open-mpi.org/release/open-mpi/v4.0/openmpi-4.0.4.tar.gz
tar -zxvf openmpi-4.0.4.tar.gz
cd openmpi-4.0.4
./configure
sudo make && sudo make install

sudo yum install cmake fftw-devel fltk-devel libtiff-devel

git clone https://github.com/3dem/relion.git
git checkout ver3.1
mkdir build
cd build
cmake -DGUI=ON -DCUDA_ARCH=60 -DFORCE_OWN_FFTW=ON -DFORCE_OWN_FLTK=ON -DCMAKE_INSTALL_PREFIX=/usr/local/relion ..
make -j
sudo make install
```

Thank you!
Sincerely,
Zouxxyy

**Comment by biochem-fan** [comment]
Please set `LD_LIBRARY_PATH` to RELION's own FLTK. OR, remove fltk packages from the system (if other programs don't need it), delete `build` and `external` folders in RELION and re-comple.

**Comment by Zouxxyy** [comment]
Thank you for your reply, I chose the second method you provided, and got the same result. 
Then I found out that my problem is caused by the transparent interface. Since the GUI is transparent, it will be affected by the color of the background behind it. Is this common？Or can it be changed to opaque?

Thank you!
Sincerely,
Zouxxyy

**Comment by biochem-fan** [comment]
It is not really RELION's problem. It is your window manager that controls how to composite windows. Please consult documentation or the support forum of your window manager.
