### ISSUE TITLE
[Not really a "bug" but possibly a tiny peculiar assumption in commandline use]

### ISSUE THREAD

**Issue by rubyFeedback** [3dem/relion#667]
Hey there biochem-fan,

I am not sure if this is worth to bother you with. At any rate, allow me to first get to the gist, and reproduce this tiny issue:

Updoing doing:

    relion_project --version

The result is:

    RELION version: 3.1.0-commit-GITDIR

I believe the first part is ok; but the "-commit-GITDIR" confuses me. Should that really be as part of the version
itself?

To clarify, I use this URL:

    https://github.com/3dem/relion/archive/3.1.0.tar.gz

And compiled from source, it is all working fine.

The reason I even mention this is because I have some ruby scripts that query installed versions on
a computer system, and I personally prefer to use the same version as the tarball (in this case 3.1.0),
but the relion version query returns that odd "-commit-GITDIR" suffix. If this is intended please ignore
this issue, but perhaps it was not intended. (Not sure how this gets into the version output but it seems
to me as if there is some git-related action that may have appended it perhaps).

**Comment by biochem-fan** [comment]
OK, I will change this as follows:

- When built from the Git source tree: "relion-3.1.0-commit-123abcd", where commit 123abcd is the commit ID. 
- When built from a tar ball (without git): "relion-3.1.0"

**Comment by biochem-fan** [comment]
(The tar ball is not updated; this will be part of 3.1.1)
