### ISSUE TITLE
Relion crashes on multiple nodes at the same time with an MPI nemesis error

### ISSUE THREAD

**Issue by rudaluna** [3dem/relion#672]
Hi,

Multiple jobs on different datasets and different nodes are crashing where this problem is reported:

Assertion failed in file src/mpid/ch3/channels/nemesis/netmod/tcp/socksm.c at line 596: hdr.pkt_type == MPIDI_NEM_TCP_SOCKSM_PKT_ID_INFO || hdr.pkt_type == MPIDI_NEM_TCP_SOCKSM_PKT_TMPVC_INFO
internal ABORT - process 4

I asked IT and they report that it should be a software issue. For simplicity I'll report the most recent error, but it happened ~10 times. Also they seem to crash at the same time, which is very weird because it's different datasets, different jobs on different nodes. To add to that I have two polish training jobs that are running without MPI and they do not crash, even though they are running on the same node that other jobs crashed.

**Environment:**
 - OS: Bright Cluster Manager 7.3 based on CentOS Linux 7
 - MPI runtime: Mpich 3.1.4 
 - RELION version RELION-3.1.0-commit-GITDIR
 - Memory: 264 GB
 - GPU: 4x GTX 1080

**Dataset:**
 - Box size: 64 pix (bin 4)
 - Pixel size: 4.116 Å/px
 - Number of particles: 340339
 - Description: proteasome of about 750 kDa

**Job options:**
 - Type of job: [ Class3D]
 - Number of MPI processes: [e.g. 4]
 - Number of threads: [e.g. 6]
 - Full command (see `note.txt` in the job directory):
 ++++ Executing new job on Thu Sep 10 12:16:14 2020
 ++++ with the following command(s):
`which relion_refine_mpi` --o Class3D/job010/run --i Select/job007/particles.star --ref map_64.mrc --firstiter_cc --ini_high 60 --dont_combine_weights_via_disc --pool 1 --pad 2  --skip_gridding  --ctf --iter 25 --tau2_fudge 4 --particle_diameter 220 --K 4 --flatten_solvent --zero_mask --oversampling 1 --healpix_order 4 --offset_range 5 --offset_step 2 --sym C1 --norm --scale  --j 2 --gpu "0:1:2:3" --maxsig 10000 --pipeline_control Class3D/job010/
 ++++

**Error message:**

Please cite the *full* error message as the example below.

```
Assertion failed in file src/mpid/ch3/channels/nemesis/netmod/tcp/socksm.c at line 596: hdr.pkt_type == MPIDI_NEM_TCP_SOCKSM_PKT_ID_INFO || hdr.pkt_type == MPIDI_NEM_TCP_SOCKSM_PKT_TMPVC_INFO
internal ABORT - process 4

```

**Comment by biochem-fan** [comment]
Hmm, it is difficult to tell if this is a problem in RELION or in your MPI runtime (Mpich2).

Can you try using OpenMPI? RELION is mostly tested with it.

**Comment by rudaluna** [comment]
Sure! I will switch to OpenMPI and let you know if it continues to crash.

**Comment by rudaluna** [comment]
Now I'm getting this error:

ERROR: CUDA driver version is insufficient for CUDA runtime version in /primary/vari/software/relion/relion-3.1.0/src/ml_optimiser_mpi.cpp at line 126 (error-code 35)
ERROR: CUDA driver version is insufficient for CUDA runtime version in /primary/vari/software/relion/relion-3.1.0/src/ml_optimiser_mpi.cpp at line 126 (error-code 35)
in: /primary/vari/software/relion/relion-3.1.0/src/acc/cuda/cuda_settings.h, line 67
ERROR: 

A GPU-function failed to execute.

 If this occured at the start of a run, you might have GPUs which
are incompatible with either the data or your installation of relion.
If you 

	-> INSTALLED RELION YOURSELF: if you e.g. specified -DCUDA_ARCH=50
	   and are trying ot run on a compute 3.5 GPU (-DCUDA_ARCH=3.5), 
	   this may happen.

	-> HAVE MULTIPLE GPUS OF DIFFERNT VERSIONS: relion needs GPUS with
	   at least compute 3.5. You may be trying to use a GPU older than
	   this. If you have multiple generations, try specifying --gpu <X>
	   with X=0. Then try X=1 in a new run, and so on. The numbering of
	   GPUs may not be obvious from the driver or intuition. For a list
	   of GPU compute generations, see 

	   en.wikipedia.org/wiki/CUDA#Version_features_and_specifications

	-> ARE USING DOUBLE-PRECISION GPU CODE: relion was been written so
	   as to not require this, and may thus have unforeseen requirements
	   when run in this mode. If you think it is nonetheless necessary,
	   please consult the developers with this error.

If this occurred at the middle or end of a run, it might be that

	-> YOUR DATA OR PARAMETERS WERE UNEXPECTED: execution on GPUs is 
	   subject to many restrictions, and relion is written to work within
	   common restraints. If you have exotic data or settings, unexpected
	   configurations may occur. See also above point regarding 
	   double precision.
If none of the above applies, please report the error to the relion
developers at    github.com/3dem/relion/issues


in: /primary/vari/software/relion/relion-3.1.0/src/acc/cuda/cuda_settings.h, line 67
ERROR: 

A GPU-function failed to execute.

 If this occured at the start of a run, you might have GPUs which
are incompatible with either the data or your installation of relion.
If you 

	-> INSTALLED RELION YOURSELF: if you e.g. specified -DCUDA_ARCH=50
	   and are trying ot run on a compute 3.5 GPU (-DCUDA_ARCH=3.5), 
	   this may happen.

	-> HAVE MULTIPLE GPUS OF DIFFERNT VERSIONS: relion needs GPUS with
	   at least compute 3.5. You may be trying to use a GPU older than
	   this. If you have multiple generations, try specifying --gpu <X>
	   with X=0. Then try X=1 in a new run, and so on. The numbering of
	   GPUs may not be obvious from the driver or intuition. For a list
	   of GPU compute generations, see 

	   en.wikipedia.org/wiki/CUDA#Version_features_and_specifications

	-> ARE USING DOUBLE-PRECISION GPU CODE: relion was been written so
	   as to not require this, and may thus have unforeseen requirements
	   when run in this mode. If you think it is nonetheless necessary,
	   please consult the developers with this error.

If this occurred at the middle or end of a run, it might be that

	-> YOUR DATA OR PARAMETERS WERE UNEXPECTED: execution on GPUs is 
	   subject to many restrictions, and relion is written to work within
	   common restraints. If you have exotic data or settings, unexpected
	   configurations may occur. See also above point regarding 
	   double precision.
If none of the above applies, please report the error to the relion
developers at    github.com/3dem/relion/issues


=== Backtrace  ===
/primary/vari/software/relion/default3.1.0/relion_refine_mpi(_ZN11RelionErrorC2ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES7_l+0x66) [0x443786]
/primary/vari/software/relion/default3.1.0/relion_refine_mpi() [0x45d2a0]
/primary/vari/software/relion/default3.1.0/relion_refine_mpi(_ZN14MlOptimiserMpi10initialiseEv+0x271b) [0x46c00b]
/primary/vari/software/relion/default3.1.0/relion_refine_mpi(main+0x55) [0x4325a5]
/lib64/libc.so.6(__libc_start_main+0xf5) [0x2aaab750fb35]
/primary/vari/software/relion/default3.1.0/relion_refine_mpi() [0x434d4f]
==================
ERROR: 

A GPU-function failed to execute.

 If this occured at the start of a run, you might have GPUs which
are incompatible with either the data or your installation of relion.
If you 

	-> INSTALLED RELION YOURSELF: if you e.g. specified -DCUDA_ARCH=50
	   and are trying ot run on a compute 3.5 GPU (-DCUDA_ARCH=3.5), 
	   this may happen.

	-> HAVE MULTIPLE GPUS OF DIFFERNT VERSIONS: relion needs GPUS with
	   at least compute 3.5. You may be trying to use a GPU older than
	   this. If you have multiple generations, try specifying --gpu <X>
	   with X=0. Then try X=1 in a new run, and so on. The numbering of
	   GPUs may not be obvious from the driver or intuition. For a list
	   of GPU compute generations, see 

	   en.wikipedia.org/wiki/CUDA#Version_features_and_specifications

	-> ARE USING DOUBLE-PRECISION GPU CODE: relion was been written so
	   as to not require this, and may thus have unforeseen requirements
	   when run in this mode. If you think it is nonetheless necessary,
	   please consult the developers with this error.

If this occurred at the middle or end of a run, it might be that

	-> YOUR DATA OR PARAMETERS WERE UNEXPECTED: execution on GPUs is 
	   subject to many restrictions, and relion is written to work within
	   common restraints. If you have exotic data or settings, unexpected
	   configurations may occur. See also above point regarding 
	   double precision.
If none of the above applies, please report the error to the relion
developers at    github.com/3dem/relion/issues


=== Backtrace  ===
/primary/vari/software/relion/default3.1.0/relion_refine_mpi(_ZN11RelionErrorC2ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES7_l+0x66) [0x443786]
/primary/vari/software/relion/default3.1.0/relion_refine_mpi() [0x45d2a0]
/primary/vari/software/relion/default3.1.0/relion_refine_mpi(_ZN14MlOptimiserMpi10initialiseEv+0x271b) [0x46c00b]
/primary/vari/software/relion/default3.1.0/relion_refine_mpi(main+0x55) [0x4325a5]
/lib64/libc.so.6(__libc_start_main+0xf5) [0x2aaab750fb35]
/primary/vari/software/relion/default3.1.0/relion_refine_mpi() [0x434d4f]
==================
ERROR: 

A GPU-function failed to execute.

 If this occured at the start of a run, you might have GPUs which
are incompatible with either the data or your installation of relion.
If you 

	-> INSTALLED RELION YOURSELF: if you e.g. specified -DCUDA_ARCH=50
	   and are trying ot run on a compute 3.5 GPU (-DCUDA_ARCH=3.5), 
	   this may happen.

	-> HAVE MULTIPLE GPUS OF DIFFERNT VERSIONS: relion needs GPUS with
	   at least compute 3.5. You may be trying to use a GPU older than
	   this. If you have multiple generations, try specifying --gpu <X>
	   with X=0. Then try X=1 in a new run, and so on. The numbering of
	   GPUs may not be obvious from the driver or intuition. For a list
	   of GPU compute generations, see 

	   en.wikipedia.org/wiki/CUDA#Version_features_and_specifications

	-> ARE USING DOUBLE-PRECISION GPU CODE: relion was been written so
	   as to not require this, and may thus have unforeseen requirements
	   when run in this mode. If you think it is nonetheless necessary,
	   please consult the developers with this error.

If this occurred at the middle or end of a run, it might be that

	-> YOUR DATA OR PARAMETERS WERE UNEXPECTED: execution on GPUs is 
	   subject to many restrictions, and relion is written to work within
	   common restraints. If you have exotic data or settings, unexpected
	   configurations may occur. See also above point regarding 
	   double precision.
If none of the above applies, please report the error to the relion
developers at    github.com/3dem/relion/issues


ERROR: CUDA driver version is insufficient for CUDA runtime version in /primary/vari/software/relion/relion-3.1.0/src/ml_optimiser_mpi.cpp at line 126 (error-code 35)
in: /primary/vari/software/relion/relion-3.1.0/src/acc/cuda/cuda_settings.h, line 67
ERROR: 

A GPU-function failed to execute.

 If this occured at the start of a run, you might have GPUs which
are incompatible with either the data or your installation of relion.
If you 

	-> INSTALLED RELION YOURSELF: if you e.g. specified -DCUDA_ARCH=50
	   and are trying ot run on a compute 3.5 GPU (-DCUDA_ARCH=3.5), 
	   this may happen.

	-> HAVE MULTIPLE GPUS OF DIFFERNT VERSIONS: relion needs GPUS with
	   at least compute 3.5. You may be trying to use a GPU older than
	   this. If you have multiple generations, try specifying --gpu <X>
	   with X=0. Then try X=1 in a new run, and so on. The numbering of
	   GPUs may not be obvious from the driver or intuition. For a list
	   of GPU compute generations, see 

	   en.wikipedia.org/wiki/CUDA#Version_features_and_specifications

	-> ARE USING DOUBLE-PRECISION GPU CODE: relion was been written so
	   as to not require this, and may thus have unforeseen requirements
	   when run in this mode. If you think it is nonetheless necessary,
	   please consult the developers with this error.

If this occurred at the middle or end of a run, it might be that

	-> YOUR DATA OR PARAMETERS WERE UNEXPECTED: execution on GPUs is 
	   subject to many restrictions, and relion is written to work within
	   common restraints. If you have exotic data or settings, unexpected
	   configurations may occur. See also above point regarding 
	   double precision.
If none of the above applies, please report the error to the relion
developers at    github.com/3dem/relion/issues


=== Backtrace  ===
/primary/vari/software/relion/default3.1.0/relion_refine_mpi(_ZN11RelionErrorC2ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES7_l+0x66) [0x443786]
/primary/vari/software/relion/default3.1.0/relion_refine_mpi() [0x45d2a0]
/primary/vari/software/relion/default3.1.0/relion_refine_mpi(_ZN14MlOptimiserMpi10initialiseEv+0x271b) [0x46c00b]
/primary/vari/software/relion/default3.1.0/relion_refine_mpi(main+0x55) [0x4325a5]
/lib64/libc.so.6(__libc_start_main+0xf5) [0x2aaab750fb35]
/primary/vari/software/relion/default3.1.0/relion_refine_mpi() [0x434d4f]
==================
ERROR: 

A GPU-function failed to execute.

 If this occured at the start of a run, you might have GPUs which
are incompatible with either the data or your installation of relion.
If you 

	-> INSTALLED RELION YOURSELF: if you e.g. specified -DCUDA_ARCH=50
	   and are trying ot run on a compute 3.5 GPU (-DCUDA_ARCH=3.5), 
	   this may happen.

	-> HAVE MULTIPLE GPUS OF DIFFERNT VERSIONS: relion needs GPUS with
	   at least compute 3.5. You may be trying to use a GPU older than
	   this. If you have multiple generations, try specifying --gpu <X>
	   with X=0. Then try X=1 in a new run, and so on. The numbering of
	   GPUs may not be obvious from the driver or intuition. For a list
	   of GPU compute generations, see 

	   en.wikipedia.org/wiki/CUDA#Version_features_and_specifications

	-> ARE USING DOUBLE-PRECISION GPU CODE: relion was been written so
	   as to not require this, and may thus have unforeseen requirements
	   when run in this mode. If you think it is nonetheless necessary,
	   please consult the developers with this error.

If this occurred at the middle or end of a run, it might be that

	-> YOUR DATA OR PARAMETERS WERE UNEXPECTED: execution on GPUs is 
	   subject to many restrictions, and relion is written to work within
	   common restraints. If you have exotic data or settings, unexpected
	   configurations may occur. See also above point regarding 
	   double precision.
If none of the above applies, please report the error to the relion
developers at    github.com/3dem/relion/issues


application called MPI_Abort(MPI_COMM_WORLD, 1) - process 2
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 4
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 1
ERROR: CUDA driver version is insufficient for CUDA runtime version in /primary/vari/software/relion/relion-3.1.0/src/ml_optimiser_mpi.cpp at line 126 (error-code 35)
in: /primary/vari/software/relion/relion-3.1.0/src/acc/cuda/cuda_settings.h, line ERROR: CUDA driver version is insufficient for CUDA runtime version in /primary/vari/software/relion/relion-3.1.0/src/ml_optimiser_mpi.cpp at line 126 (error-code 35)
67
ERROR: 

A GPU-function failed to execute.

 If this occured at the start of a run, you might have GPUs which
are incompatible with either the data or your installation of relion.
If you 

	-> INSTALLED RELION YOURSELF: if you e.g. specified -DCUDA_ARCH=50
	   and are trying ot run on a compute 3.5 GPU (-DCUDA_ARCH=3.5), 
	   this may happen.

	-> HAVE MULTIPLE GPUS OF DIFFERNT VERSIONS: relion needs GPUS with
	   at least compute 3.5. You may be trying to use a GPU older than
	   this. If you have multiple generations, try specifying --gpu <X>
	   with X=0. Then try X=1 in a new run, and so on. The numbering of
	   GPUs may not be obvious from the driver or intuition. For a list
	   of GPU compute generations, see 

	   en.wikipedia.org/wiki/CUDA#Version_features_and_specifications

	-> ARE USING DOUBLE-PRECISION GPU CODE: relion was been written so
	   as to not require this, and may thus have unforeseen requirements
	   when run in this mode. If you think it is nonetheless necessary,
	   please consult the developers with this error.

If this occurred at the middle or end of a run, it might be that

	-> YOUR DATA OR PARAMETERS WERE UNEXPECTED: execution on GPUs is 
	   subject to many restrictions, and relion is written to work within
	   common restraints. If you have exotic data or settings, unexpected
	   configurations may occur. See also above point regarding 
	   double precision.
If none of the above applies, please report the error to the relion
developers at    github.com/3dem/relion/issues


=== Backtrace  ===in: 
/primary/vari/software/relion/relion-3.1.0/src/acc/cuda/cuda_settings.h, line 67
ERROR: 

A GPU-function failed to execute.

 If this occured at the start of a run, you might have GPUs which
are incompatible with either the data or your installation of relion.
If you 

	-> INSTALLED RELION YOURSELF: if you e.g. specified -DCUDA_ARCH=50
	   and are trying ot run on a compute 3.5 GPU (-DCUDA_ARCH=3.5), 
	   this may happen.

	-> HAVE MULTIPLE GPUS OF DIFFERNT VERSIONS: relion needs GPUS with
	   at least compute 3.5. You may be trying to use a GPU older than
	   this. If you have multiple generations, try specifying --gpu <X>
	   with X=0. Then try X=1 in a new run, and so on. The numbering of
	   GPUs may not be obvious from the driver or intuition. For a list
	   of GPU compute generations, see 

	   en.wikipedia.org/wiki/CUDA#Version_features_and_specifications

	-> ARE USING DOUBLE-PRECISION GPU CODE: relion was been written so
	   as to not require this, and may thus have unforeseen requirements
	   when run in this mode. If you think it is nonetheless necessary,
	   please consult the developers with this error.

If this occurred at the middle or end of a run, it might be that

	-> YOUR DATA OR PARAMETERS WERE UNEXPECTED: execution on GPUs is 
	   subject to many restrictions, and relion is written to work within
	   common restraints. If you have exotic data or settings, unexpected
	   configurations may occur. See also above point regarding 
	   double precision.
If none of the above applies, please report the error to the relion
developers at    github.com/3dem/relion/issues


=== Backtrace  ===
/primary/vari/software/relion/default3.1.0/relion_refine_mpi(_ZN11RelionErrorC2ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES7_l+0x66) [0x443786]
/primary/vari/software/relion/default3.1.0/relion_refine_mpi() [0x45d2a0]
/primary/vari/software/relion/default3.1.0/relion_refine_mpi(_ZN14MlOptimiserMpi10initialiseEv+0x271b) [0x46c00b]
/primary/vari/software/relion/default3.1.0/relion_refine_mpi(main+0x55) [0x4325a5]
/lib64/libc.so.6(__libc_start_main+0xf5) [0x2aaab750fb35]
/primary/vari/software/relion/default3.1.0/relion_refine_mpi() [0x434d4f]
==================
ERROR: 

A GPU-function failed to execute.

 If this occured at the start of a run, you might have GPUs which
are incompatible with either the data or your installation of relion.
If you 

	-> INSTALLED RELION YOURSELF: if you e.g. specified -DCUDA_ARCH=50
	   and are trying ot run on a compute 3.5 GPU (-DCUDA_ARCH=3.5), 
	   this may happen.

	-> HAVE MULTIPLE GPUS OF DIFFERNT VERSIONS: relion needs GPUS with
	   at least compute 3.5. You may be trying to use a GPU older than
	   this. If you have multiple generations, try specifying --gpu <X>
	   with X=0. Then try X=1 in a new run, and so on. The numbering of
	   GPUs may not be obvious from the driver or intuition. For a list
	   of GPU compute generations, see 

	   en.wikipedia.org/wiki/CUDA#Version_features_and_specifications

	-> ARE USING DOUBLE-PRECISION GPU CODE: relion was been written so
	   as to not require this, and may thus have unforeseen requirements
	   when run in this mode. If you think it is nonetheless necessary,
	   please consult the developers with this error.

If this occurred at the middle or end of a run, it might be that

	-> YOUR DATA OR PARAMETERS WERE UNEXPECTED: execution on GPUs is 
	   subject to many restrictions, and relion is written to work within
	   common restraints. If you have exotic data or settings, unexpected
	   configurations may occur. See also above point regarding 
	   double precision.
If none of the above applies, please report the error to the relion
developers at    github.com/3dem/relion/issues


/primary/vari/software/relion/default3.1.0/relion_refine_mpi(_ZN11RelionErrorC2ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES7_l+0x66) [0x443786]
/primary/vari/software/relion/default3.1.0/relion_refine_mpi() [0x45d2a0]
/primary/vari/software/relion/default3.1.0/relion_refine_mpi(_ZN14MlOptimiserMpi10initialiseEv+0x271b) [0x46c00b]
/primary/vari/software/relion/default3.1.0/relion_refine_mpi(main+0x55) [0x4325a5]
/lib64/libc.so.6(__libc_start_main+0xf5) [0x2aaab750fb35]
/primary/vari/software/relion/default3.1.0/relion_refine_mpi() [0x434d4f]
==================
ERROR: 

A GPU-function failed to execute.

 If this occured at the start of a run, you might have GPUs which
are incompatible with either the data or your installation of relion.
If you 

	-> INSTALLED RELION YOURSELF: if you e.g. specified -DCUDA_ARCH=50
	   and are trying ot run on a compute 3.5 GPU (-DCUDA_ARCH=3.5), 
	   this may happen.

	-> HAVE MULTIPLE GPUS OF DIFFERNT VERSIONS: relion needs GPUS with
	   at least compute 3.5. You may be trying to use a GPU older than
	   this. If you have multiple generations, try specifying --gpu <X>
	   with X=0. Then try X=1 in a new run, and so on. The numbering of
	   GPUs may not be obvious from the driver or intuition. For a list
	   of GPU compute generations, see 

	   en.wikipedia.org/wiki/CUDA#Version_features_and_specifications

	-> ARE USING DOUBLE-PRECISION GPU CODE: relion was been written so
	   as to not require this, and may thus have unforeseen requirements
	   when run in this mode. If you think it is nonetheless necessary,
	   please consult the developers with this error.

If this occurred at the middle or end of a run, it might be that

	-> YOUR DATA OR PARAMETERS WERE UNEXPECTED: execution on GPUs is 
	   subject to many restrictions, and relion is written to work within
	   common restraints. If you have exotic data or settings, unexpected
	   configurations may occur. See also above point regarding 
	   double precision.
If none of the above applies, please report the error to the relion
developers at    github.com/3dem/relion/issues


ERROR: CUDA driver version is insufficient for CUDA runtime version in /primary/vari/software/relion/relion-3.1.0/src/ml_optimiser_mpi.cpp at line 126 (error-code 35)
in: /primary/vari/software/relion/relion-3.1.0/src/acc/cuda/cuda_settings.h, line 67
ERROR: 

A GPU-function failed to execute.

 If this occured at the start of a run, you might have GPUs which
are incompatible with either the data or your installation of relion.
If you 

	-> INSTALLED RELION YOURSELF: if you e.g. specified -DCUDA_ARCH=50
	   and are trying ot run on a compute 3.5 GPU (-DCUDA_ARCH=3.5), 
	   this may happen.

	-> HAVE MULTIPLE GPUS OF DIFFERNT VERSIONS: relion needs GPUS with
	   at least compute 3.5. You may be trying to use a GPU older than
	   this. If you have multiple generations, try specifying --gpu <X>
	   with X=0. Then try X=1 in a new run, and so on. The numbering of
	   GPUs may not be obvious from the driver or intuition. For a list
	   of GPU compute generations, see 

	   en.wikipedia.org/wiki/CUDA#Version_features_and_specifications

	-> ARE USING DOUBLE-PRECISION GPU CODE: relion was been written so
	   as to not require this, and may thus have unforeseen requirements
	   when run in this mode. If you think it is nonetheless necessary,
	   please consult the developers with this error.

If this occurred at the middle or end of a run, it might be that

	-> YOUR DATA OR PARAMETERS WERE UNEXPECTED: execution on GPUs is 
	   subject to many restrictions, and relion is written to work within
	   common restraints. If you have exotic data or settings, unexpected
	   configurations may occur. See also above point regarding 
	   double precision.
If none of the above applies, please report the error to the relion
developers at    github.com/3dem/relion/issues


ERROR: CUDA driver version is insufficient for CUDA runtime version in /primary/vari/software/relion/relion-3.1.0/src/ml_optimiser_mpi.cpp at line 126 (error-code 35)
ERROR: CUDA driver version is insufficient for CUDA runtime version in /primary/vari/software/relion/relion-3.1.0/src/ml_optimiser_mpi.cpp at line 126 (error-code 35)
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 7

**Comment by biochem-fan** [comment]
Do you have proper GPU drivers in the computing node? Did you compile RELION with the right version of CUDA?

**Comment by rudaluna** [comment]
Sorry, this specific node had an issue with the GPU driver. I submitted a new job with OpenMPI to another node and it seems to be running smoothly. I'll let you know if there are further errors.
