### ISSUE TITLE
You do NOT have support for GPUs

### ISSUE THREAD

**Issue by CFDavidHou** [3dem/relion#675]
Hi! Thank you for helping previously. When I do 2D classification and would like to use GPU acceleration. I got:
```
WARNING: Relion was compiled without CUDA of at least verson 7.0.
```
I have two RTX2080 ti on board. And the environment seems okay. I do not know what caused the issue. Please see my settings below.
```
user@xxx:~$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Sun_Jul_28_19:07:16_PDT_2019
Cuda compilation tools, release 10.1, V10.1.243
```
```
user@xxx:~/relion/build$ cmake ..
-- BUILD TYPE set to the default type:  'Release'
-- Setting fallback CUDA_ARCH=35
-- ALLOW_CTF_IN_SAGD enabled - This build of RELION allows modulation of particle images by a contrast transfer function inside stochastic average gradient descent, as specified in Claim 1 of patent US10,282,513B2
-- CUDA enabled - Building CUDA-accelerated version of RELION
-- Setting cpu precision to double
-- Setting accelerated code precision to single
-- Using cuda wrapper to compile....
-- Cuda version is >= 7.5 and single-precision build, enable double usage warning.
```

Thank you!

David

**Comment by biochem-fan** [comment]
Are you sure you are not running the RELION from CCPEM?

What does `which relion` say?

**Comment by CFDavidHou** [comment]
Well, I download 10204 tutorial dataset to /home/user/project and 
```
user@xxx:~/project/tutorial/10204$ relion
```
And the GUI pop put as RELION-3.1.0-commit-5bc851

I have removed all CCPEM folder. I should not be running RELION from CCPEM

hmm...

**Comment by biochem-fan** [comment]
Please run `which relion_refine` and cite what it says.

**Comment by CFDavidHou** [comment]
It says:
```
user@xxx:~/project/tutorial/10204$ which relion_refine
/usr/local/bin/relion_refine
```

**Comment by biochem-fan** [comment]
Is this where you installed RELION? Did you specify it in cmake?

**Comment by CFDavidHou** [comment]
It seems that which relion and whcih relion_refine gave me different directory.
one is 
```
user@xxx:~/project/tutorial/10204$ which relion
/home/user/relion/build/bin/relion
``
one is
```
user@xxx:~/project/tutorial/10204$ which relion_refine
/usr/local/bin/relion_refine
```
I tired to do gedit ~/.bashrc
```
set path="/home/user/relion/build/bin:$PATH"
```
But still the same.

I did cmake as instructed
```
git clone https://github.com/3dem/relion.git
cd relion
git checkout ver3.1
mkdir build
cd build
cmake ..
make
```
hmm...

**Comment by biochem-fan** [comment]
In BASH, case matters. Use capital PATH.

Also note that you have to use `export` not `set`. (`set` is for csh)

**Comment by CFDavidHou** [comment]
```
export PATH="/home/user/relion/build/bin:$PATH"
```
Thank you! That did the trick.

Then,

I close and re-open RELION and run Class2D. It still gives me the same warnings. 

I will need some time to investigate the issue.

**Comment by CFDavidHou** [comment]
Hi,

I made sure the PATH is correct directed to CUDA and I found out a thread mentioned to reboot system after installing CUDA. So I did and it worked.

Thank you!
