### ISSUE TITLE
Cmake installation issues _relion

### ISSUE THREAD

**Issue by Raj-dei** [3dem/relion#676]
Hi there, 

Hope someone could help me with this. I have no prior knowledge in programming and had issues when i tried to install relion from the instructions here and provided by https://blogs.urz.uni-halle.de/kastritislab/2019/06/installation-of-relion-3-on-our-macos/ link. 

I am trying to install relion in mac book MacOS Catalina (version 10.15.6) and ended up with the similar problem many users mentioned . Pasting the log below. Tried with different CMake version etc. but nothing changed. Any help on this is highly appreciated.

zsh: command not found: ###How
zsh: command not found: ###Kastritis
zsh: command not found: ###Install
zsh: command not found: ###for
Updating Homebrew…
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> Updated Formulae
Updated 4 formulae.

Warning: cmake 3.18.2 is already installed and up-to-date
To reinstall 3.18.2, run `brew reinstall cmake`
Warning: gcc 10.2.0 is already installed and up-to-date
To reinstall 10.2.0, run `brew reinstall gcc`
Updating Homebrew…
Warning: open-mpi 4.0.5 is already installed and up-to-date
To reinstall 4.0.5, run `brew reinstall open-mpi`
Updating Homebrew…
Warning: fltk 1.3.5 is already installed and up-to-date
To reinstall 1.3.5, run `brew reinstall fltk`
Updating Homebrew…
Warning: fftw 3.3.8_2 is already installed and up-to-date
To reinstall 3.3.8_2, run `brew reinstall fftw`
zsh: command not found: ###Set
zsh: command not found: ###Now
Cloning into ‘relion’…
remote: Enumerating objects: 159, done.
remote: Counting objects: 100% (159/159), done.
remote: Compressing objects: 100% (108/108), done.
remote: Total 26811 (delta 87), reused 85 (delta 51), pack-reused 26652
Receiving objects: 100% (26811/26811), 51.75 MiB | 2.55 MiB/s, done.
Resolving deltas: 100% (21056/21056), done.
Note: switching to ‘3.0.6’.

You are in ‘detached HEAD’ state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

git switch -c

Or undo this operation with:

git switch –

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at 8a677f29 This is 3.0.6.
CMake Error at /usr/local/Cellar/cmake/3.18.2/share/cmake/Modules/CMakeDetermineCCompiler.cmake:49 (message):
Could not find compiler set in environment variable CC:

gcc-9.
Call Stack (most recent call first):
CMakeLists.txt:7 (project)

CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
— Configuring incomplete, errors occurred!
See also “/Users/u/Applications/relion/relion/build/CMakeFiles/CMakeOutput.log”.
make: *** No targets specified and no makefile found. Stop.
make: *** No rule to make target `install’. Stop.

**Comment by Raj-dei** [comment]
u1@MAC23297 build % echo $CXX $CC $OMPI_CXX $OMPI_CC $CXXFLAGS $LDFLAGS
../cc_args.py ../bin/g++ ../cc_args.py ../bin/gcc g++-9 gcc-9 -I/usr/local/opt/openmpi/include -L/usr/local/opt/openmpi/lib
u1@MAC23297 build %

**Comment by biochem-fan** [comment]
RELION does not officially support Mac OS X. CCPEM provides pre-compiled binaries of RELION for Mac OS X if you really need. It does not GPU, though, so it is not very practical.
