### ISSUE TITLE
Trouble with large particles

### ISSUE THREAD

**Issue by CFDavidHou** [3dem/relion#679]
Hi everyone,

I do not know if this is a proper question/issue to ask here but I really do not have a close expert who knows how to deal with large datasets. My issue is that I am solving a cryoEM phage structure and the capsid of this virus is huge, up to 850 A diameters with possible I1 or I7 symmetry. I have the datasets collected from NCEF, taken with K3 camera. The image pixel size is 1.42A.

So here is my question. My workstation's settings and hardware can handle up to 516 pixels in 3D auto-refinement as told by RELION, but my box-size is at least 640 pixels (700 pixels will be nicer). I can never finish the last few iterations and the best resolution I can have is about 4.7A. I down grade the pixel size to 2.84 A in order to finish 3D auto-refine but the final resolution is caped to 5.7A. Do I have a better method to improve my structure resolution to about 3 A?

I am sorry if this question is too novice but I really need some help and enlightenment.

Thank you!

David

**Comment by biochem-fan** [comment]
Please use "Skip padding: Yes". CCPEM mailing list is more adequate for these questions. You should also search its archive. https://www.jiscmail.ac.uk/cgi-bin/wa-jisc.exe?A0=CCPEM

**Comment by CFDavidHou** [comment]
Thank you biochem-fan!
