### ISSUE TITLE
MetaDataTable::read: File mtf does not exist

### ISSUE THREAD

**Issue by mengxin-mx-cpu** [3dem/relion#681]
Hi,when i run CTF refinement,it had an ERROR.

[root@node00 data]# `which relion_ctf_refine` --i Refine3D/job142/run_data.star --f PostProcess/job144/postprocess.star --o CtfRefine/job145/ --fit_beamtilt --kmin_tilt 30 --odd_aberr_max_n 3 --fit_aberr --only_do_unfinished   --pipeline_control CtfRefine/job145/
 + Reading Refine3D/job142/run_data.star...
 + Reading references ...
 + The names of the reference half maps and the mask were taken from the PostProcess STAR file.
   - Half map 1: Refine3D/job142/run_half1_class001_unfil.mrc
   - Half map 2: Refine3D/job142/run_half2_class001_unfil.mrc
   - Mask: MaskCreate/job143/mask.mrc
WARNING: You did not specify --angpix_ref. The pixel size in the image header of Refine3D/job142/run_half1_class001_unfil.mrc, 1.24484 A/px, is used.
 + Masking references ...
 + Transforming references ...
   - Will process all 24 micrographs
 + Performing loop over all micrographs ... 
000/??? sec ~~(,_,">                                                          [oo]in: /home/relion/relion/src/metadata_table.cpp, line 1114
ERROR: 
MetaDataTable::read: File mtf does not exist
terminate called after throwing an instance of 'RelionError'
Aborted

[root@node00 data]# cat mtf_k2_200kV.star 
data_mtf_k2_200kv
loop_
_rlnResolutionInversePixel
_rlnMtfValue
0.000000000	0.999999885
0.015873016	0.996121942
0.031746032	0.991044063
0.047619047	0.98482507
0.063492064	0.977522754
0.07936508	0.969193876
0.095238095	0.959894164
0.111111111	0.949678317
0.126984127	0.938599999
0.142857143	0.926711847
0.158730159	0.914065464
0.174603175	0.900711423
0.190476191	0.886699265
0.206349207	0.8720775
0.222222222	0.856893608
0.238095238	0.841194035
0.253968254	0.825024198
0.26984127	0.808428481
0.285714286	0.79145024
0.301587302	0.774131795
0.317460318	0.75651444
0.333333334	0.738638433
0.349206349	0.720543003
0.365079365	0.702266348
0.380952381	0.683845634
0.396825397	0.665316996
0.412698413	0.646715539
0.428571429	0.628075333
0.444444445	0.609429422
0.460317461	0.590809813
0.476190476	0.572247488
0.492063492	0.553772392
0.507936508	0.535413442
[root@node00 data]#

**Comment by biochem-fan** [comment]
Please paste the optics group table of `Refine3D/job142/run_data.star`.

**Comment by mengxin-mx-cpu** [comment]
Do you mean this

[root@node00 job142]# head -n 100 run_data.star 

# version 30001

data_optics

loop_ 
_rlnOpticsGroupName #1 
_rlnOpticsGroup #2 
_rlnMtfFileName #3 
_rlnMicrographOriginalPixelSize #4 
_rlnVoltage #5 
_rlnSphericalAberration #6 
_rlnAmplitudeContrast #7 
_rlnImagePixelSize #8 
_rlnImageSize #9 
_rlnImageDimensionality #10 
opticsGroup1            1        mtf     0.885000   200.000000     1.400000     0.100000     1.244531          256            2 
 

# version 30001

data_particles

loop_ 
_rlnCoordinateX #1 
_rlnCoordinateY #2 
_rlnClassNumber #3 
_rlnAutopickFigureOfMerit #4 
_rlnAnglePsi #5 
_rlnImageName #6 
_rlnMicrographName #7 
_rlnOpticsGroup #8 
_rlnCtfMaxResolution #9 
_rlnCtfFigureOfMerit #10 
_rlnDefocusU #11 
_rlnDefocusV #12 
_rlnDefocusAngle #13 
_rlnCtfBfactor #14 
_rlnCtfScalefactor #15 
_rlnPhaseShift #16 
_rlnGroupNumber #17 
_rlnAngleRot #18 
_rlnAngleTilt #19 
_rlnOriginXAngst #20 
_rlnOriginYAngst #21 
_rlnNormCorrection #22 
_rlnLogLikeliContribution #23 
_rlnMaxValueProbDistribution #24 
_rlnNrOfSignificantSamples #25 
_rlnRandomSubset #26 
 1424.605891  2805.770605            1     0.010954    53.948517 000001@Extract/job126/relion30_tutorial/Movies/20170629_00021_frameImage.mrcs MotionCorr/job109/relion30_tutorial/Movies/20170629_00021_frameImage.mrc            1     4.797000     0.092779 10864.480469 10
588.639648    87.809998     0.000000     1.000000     0.000000            1   111.159379    66.015595     5.382937    10.861673     0.472844 2.670910e+05     0.309059            3            2  1532.200009  3342.317667            1     0.342763     6.124097 000002@Extract/job126/relion30_tutorial/Movies/20170629_00021_frameImage.mrcs MotionCorr/job109/relion30_tutorial/Movies/20170629_00021_frameImage.mrc            1     4.797000     0.092779 10864.480469 10
588.639648    87.809998     0.000000     1.000000     0.000000            1   154.745643    35.621651     1.649344    11.605592     0.469169 2.668922e+05     0.350929            6            1  2010.017659  3567.082374            1     0.254472     8.013986 000003@Extract/job126/relion30_tutorial/Movies/20170629_00021_frameImage.mrcs MotionCorr/job109/relion30_tutorial/Movies/20170629_00021_frameImage.mrc            1     4.797000     0.092779 10864.480469 10
588.639648    87.809998     0.000000     1.000000     0.000000            1   147.418452    29.530683     9.116530     6.627468     0.468888 2.666856e+05     0.357474           11            2  2486.988250  3687.541198            1     0.039758    42.704302 000004@Extract/job126/relion30_tutorial/Movies/20170629_00021_frameImage.mrcs MotionCorr/job109/relion30_tutorial/Movies/20170629_00021_frameImage.mrc            1     4.797000     0.092779 10864.480469 10
588.639648    87.809998     0.000000     1.000000     0.000000            1   148.789814    26.516313     -6.56176     9.617142     0.427392 2.667258e+05     0.319758            1            1  2611.294133  2607.294133            1     0.053660    -79.17280 000005@Extract/job126/relion30_tutorial/Movies/20170629_00021_frameImage.mrcs MotionCorr/job109/relion30_tutorial/Movies/20170629_00021_frameImage.mrc            1     4.797000     0.092779 10864.480469 10
588.639648    87.809998     0.000000     1.000000     0.000000            1    40.357977    35.690648     -0.33911     2.893875     0.469824 2.668392e+05     0.507255            2            2  2734.752957  2498.411779            1     0.012313    -65.14299 000006@Extract/job126/relion30_tutorial/Movies/20170629_00021_frameImage.mrcs MotionCorr/job109/relion30_tutorial/Movies/20170629_00021_frameImage.mrc            1     4.797000     0.092779 10864.480469 10
588.639648    87.809998     0.000000     1.000000     0.000000            1   163.202136    64.677769     6.627468     -5.81784     0.469300 2.667625e+05     0.382399            4            2  3500.776491   944.923535            1     0.081907   -147.65553 000007@Extract/job126/relion30_tutorial/Movies/20170629_00021_frameImage.mrcs MotionCorr/job109/relion30_tutorial/Movies/20170629_00021_frameImage.mrc            1     4.797000     0.092779 10864.480469 10
588.639648    87.809998     0.000000     1.000000     0.000000            1     0.785449    48.231084     -2.82817     0.905425     0.468302 2.667196e+05     0.548184            3            1  1751.676481  1135.535301            1     0.085774   124.254221 000008@Extract/job126/relion30_tutorial/Movies/20170629_00021_frameImage.mrcs MotionCorr/job109/relion30_tutorial/Movies/20170629_00021_frameImage.mrc            1     4.797000     0.092779 10864.480469 10
588.639648    87.809998     0.000000     1.000000     0.000000            1    56.324314    76.161030     -3.32878     -3.82939     0.470491 2.666142e+05     0.298150            4            1  2529.276485  1381.164714            1     0.254600   118.606280 000009@Extract/job126/relion30_tutorial/Movies/20170629_00021_frameImage.mrcs MotionCorr/job109/relion30_tutorial/Movies/20170629_00021_frameImage.mrc            1     4.797000     0.092779 10864.480469 10
588.639648    87.809998     0.000000     1.000000     0.000000            1   163.905967    66.642271     -5.81784     6.627468     0.475431 2.667807e+05     0.502785            2            2  3441.335314  3279.300019            1     0.112328    97.111815 000010@Extract/job126/relion30_tutorial/Movies/20170629_00021_frameImage.mrcs MotionCorr/job109/relion30_tutorial/Movies/20170629_00021_frameImage.mrc            1     4.797000     0.092779 10864.480469 10
588.639648    87.809998     0.000000     1.000000     0.000000            1   126.827555    24.278850     -2.08425     -5.81784     0.469703 2.669256e+05     0.996847            4            1   405.664708  3269.588255            1     0.101357   151.451145 000011@Extract/job126/relion30_tutorial/Movies/20170629_00021_frameImage.mrcs MotionCorr/job109/relion30_tutorial/Movies/20170629_00021_frameImage.mrc            1     4.797000     0.092779 10864.480469 10
588.639648    87.809998     0.000000     1.000000     0.000000            1    64.745525    56.507627     2.893875     2.650569     0.464073 2.668626e+05     0.221596            4            1  3124.552959  3505.776491            1     0.417054   101.746637 000012@Extract/job126/relion30_tutorial/Movies/20170629_00021_frameImage.mrcs MotionCorr/job109/relion30_tutorial/Movies/20170629_00021_frameImage.mrc            1     4.797000     0.092779 10864.480469 10
588.639648    87.809998     0.000000     1.000000     0.000000            1    40.152804    73.073899     -5.31723    17.584941     0.465683 2.668552e+05     0.117156           12            1  1000.652947  1900.423541            1     0.053025    41.762707 000013@Extract/job126/relion30_tutorial/Movies/20170629_00021_frameImage.mrcs MotionCorr/job109/relion30_tutorial/Movies/20170629_00021_frameImage.mrc            1     4.797000     0.092779 10864.480469 10
588.639648    87.809998     0.000000     1.000000     0.000000            1    54.195048    49.796053     -0.33911     6.126855     0.468788 2.666442e+05     0.372147            6            2  3075.111783  1024.652947            1     0.002556   166.451706 000014@Extract/job126/relion30_tutorial/Movies/20170629_00021_frameImage.mrcs MotionCorr/job109/relion30_tutorial/Movies/20170629_00021_frameImage.mrc            1     4.797000     0.092779 10864.480469 10
588.639648    87.809998     0.000000     1.000000     0.000000            1   110.449750    58.597388     -2.82817     1.649344     0.469366 2.668732e+05     0.724717            1            1  2221.205895   518.547062            1     0.421852   163.646370 000015@Extract/job126/relion30_tutorial/Movies/20170629_00021_frameImage.mrcs MotionCorr/job109/relion30_tutorial/Movies/20170629_00021_frameImage.mrc            1     4.797000     0.092779 10864.480469 10
588.639648    87.809998     0.000000     1.000000     0.000000            1    65.701863    45.815522     -2.82817     -6.56176     0.466727 2.668356e+05     0.374426            8            2  2551.852956  2168.052954            1     0.004582     -6.95771 000016@Extract/job126/relion30_tutorial/Movies/20170629_00021_frameImage.mrcs MotionCorr/job109/relion30_tutorial/Movies/20170629_00021_frameImage.mrc            1     4.797000     0.092779 10864.480469 10
588.639648    87.809998     0.000000     1.000000     0.000000            1   121.172206    28.788799     0.404813     -1.58364     0.466833 2.665091e+05     0.378560            8            2   641.429416  2628.870604            1     0.338767   -126.98669 000017@Extract/job126/relion30_tutorial/Movies/20170629_00021_frameImage.mrcs MotionCorr/job109/relion30_tutorial/Movies/20170629_00021_frameImage.mrc            1     4.797000     0.092779 10864.480469 10
588.639648    87.809998     0.000000     1.000000     0.000000            1    78.111116    65.384234     -2.82817     -4.07270     0.465440 2.669648e+05     0.496014            4            1   398.800002  2683.735310            1     0.097749    11.718247 000018@Extract/job126/relion30_tutorial/Movies/20170629_00021_frameImage.mrcs MotionCorr/job109/relion30_tutorial/Movies/20170629_00021_frameImage.mrc            1     4.797000     0.092779 10864.480469 10
588.639648    87.809998     0.000000     1.000000     0.000000            1     -0.62016    71.831443     7.871999     7.871999     0.461931 2.667132e+05     0.247645           10            2  3269.588255  2049.747071            1     0.403165   -137.31165 000019@Extract/job126/relion30_tutorial/Movies/20170629_00021_frameImage.mrcs MotionCorr/job109/relion30_tutorial/Movies/20170629_00021_frameImage.mrc            1     4.797000     0.092779 10864.480469 10
588.639648    87.809998     0.000000     1.000000     0.000000            1   142.797111    51.284849    -17.76254     8.615917     0.470439 2.667557e+05     0.287366            2            2  1191.264713   332.647061            1     0.031080    -17.34156 000020@Extract/job126/relion30_tutorial/Movies/20170629_00021_frameImage.mrcs MotionCorr/job109/relion30_tutorial/Movies/20170629_00021_frameImage.mrc            1     4.797000     0.092779 10864.480469 10
588.639648    87.809998     0.000000     1.000000     0.000000            1   177.868163    45.757097     0.404813     -5.31723     0.462810 2.666510e+05     0.610076            4            2   426.376473   237.052943            1     0.147705   140.162004 000021@Extract/job126/relion30_tutorial/Movies/20170629_00021_frameImage.mrcs MotionCorr/job109/relion30_tutorial/Movies/20170629_00021_frameImage.mrc            1     4.797000     0.092779 10864.480469 10
588.639648    87.809998     0.000000     1.000000     0.000000            1     7.815864    76.793007     -2.82817     -4.81662     0.476643 2.669016e+05     0.310421            6            1  3158.417666  3052.111783            1     0.010846   -164.51852 000022@Extract/job126/relion30_tutorial/Movies/20170629_00021_frameImage.mrcs MotionCorr/job109/relion30_tutorial/Movies/20170629_00021_frameImage.mrc            1     4.797000     0.092779 10864.480469 10
588.639648    87.809998     0.000000     1.000000     0.000000            1   165.310014    55.731091     -2.08425    -10.29535     0.465985 2.666181e+05     0.722959            2            2  3069.400018   589.276474            1     0.001209   152.387899 000023@Extract/job126/relion30_tutorial/Movies/20170629_00021_frameImage.mrcs MotionCorr/job109/relion30_tutorial/Movies/20170629_00021_frameImage.mrc            1     4.797000     0.092779 10864.480469 10
588.639648    87.809998     0.000000     1.000000     0.000000            1   132.000308    44.188343     -0.33911     4.639018     0.473536 2.669930e+05     0.375344            3            2  1711.100010  2430.970602            1     0.279779   -172.93546 000024@Extract/job126/relion30_tutorial/Movies/20170629_00021_frameImage.mrcs MotionCorr/job109/relion30_tutorial/Movies/20170629_00021_frameImage.mrc            1     4.797000     0.092779 10864.480469 10
588.639648    87.809998     0.000000     1.000000     0.000000            1   148.148612    41.042048     2.893875     -4.07270     0.472399 2.668023e+05     0.400098            2            2  1491.623538   524.835297            1     0.006648    -92.32393 000025@Extract/job126/relion30_tutorial/Movies/20170629_00021_frameImage.mrcs MotionCorr/job109/relion30_tutorial/Movies/20170629_00021_frameImage.mrc            1     4.797000     0.092779 10864.480469 10
588.639648    87.809998     0.000000     1.000000     0.000000            1    25.386432    63.427318     -4.07270     6.627468     0.475586 2.671642e+05     0.194245           11            1  2131.900012  1848.982364            1     0.087635    72.678848 000026@Extract/job126/relion30_tutorial/Movies/20170629_00021_frameImage.mrcs MotionCorr/job109/relion30_tutorial/Movies/20170629_00021_frameImage.mrc            1     4.797000     0.092779 10864.480469 10
588.639648    87.809998     0.000000     1.000000     0.000000            1   147.034511    86.381958     0.404813     5.883549     0.472951 2.669250e+05     0.338524            6            2  3056.247077   473.105885            1     0.027799    -49.16814 000027@Extract/job126/relion30_tutorial/Movies/20170629_00021_frameImage.mrcs MotionCorr/job109/relion30_tutorial/Movies/20170629_00021_frameImage.mrc            1     4.797000     0.092779 10864.480469 10
588.639648    87.809998     0.000000     1.000000     0.000000            1   147.894372    25.766190     -5.81784     2.149956     0.463381 2.665663e+05     0.813670            3            2   204.764707  1605.217657            1     0.037997    -44.51874 000028@Extract/job126/relion30_tutorial/Movies/20170629_00021_frameImage.mrcs MotionCorr/job109/relion30_tutorial/Movies/20170629_00021_frameImage.mrc            1     4.797000     0.092779 10864.480469 10
588.639648    87.809998     0.000000     1.000000     0.000000            1   167.533098    45.758050     7.871999    -10.79597     0.462381 2.665684e+05     0.344493            6            2  2710.176486  1222.705890            1     0.165990    91.451377 000029@Extract/job126/relion30_tutorial/Movies/20170629_00021_frameImage.mrcs MotionCorr/job109/relion30_tutorial/Movies/20170629_00021_frameImage.mrc            1     4.797000     0.092779 10864.480469 10
588.639648    87.809998     0.000000     1.000000     0.000000            1    63.338207    55.064731     -8.30690     -4.07270     0.470328 2.666057e+05     0.441646            5            2  1530.488244  2498.700015            1     0.044843     -3.26359 000030@Extract/job126/relion30_tutorial/Movies/20170629_00021_frameImage.mrcs MotionCorr/job109/relion30_tutorial/Movies/20170629_00021_frameImage.mrc            1     4.797000     0.092779 10864.480469 10
588.639648    87.809998     0.000000     1.000000     0.000000            1   160.384450    52.039358     -2.08425     -7.80629     0.467160 2.667941e+05     0.353093            2            1  1610.641186   119.170589            1     0.414405    84.906623 000031@Extract/job126/relion30_tutorial/Movies/20170629_00021_frameImage.mrcs MotionCorr/job109/relion30_tutorial/Movies/20170629_00021_frameImage.mrc            1     4.797000     0.092779 10864.480469 10
588.639648    87.809998     0.000000     1.000000     0.000000            1    79.201521    40.305379    -12.04050     0.905425     0.395072 2.671139e+05     0.726871            3            2  2340.088249  1322.011773            1     0.479201   -119.46705 000032@Extract/job126/relion30_tutorial/Movies/20170629_00021_frameImage.mrcs MotionCorr/job109/relion30_tutorial/Movies/20170629_00021_frameImage.mrc            1     4.797000     0.092779 10864.480469 10
588.639648    87.809998     0.000000     1.000000     0.000000            1   137.596429    25.770688    -10.29535     6.627468     0.468597 2.668428e+05     0.335904            2            1   602.141180  1686.523539            1     0.100737   -157.89504 000033@Extract/job126/relion30_tutorial/Movies/20170629_00021_frameImage.mrcs MotionCorr/job109/relion30_tutorial/Movies/20170629_00021_frameImage.mrc            1     4.797000     0.092779 10864.480469 10
588.639648    87.809998     0.000000     1.000000     0.000000            1   125.287567    27.279428     0.404813     6.627468     0.466291 2.664758e+05     0.724193            4            2  2918.941194  3480.776491            1     0.245507   -124.17795 000034@Extract/job126/relion30_tutorial/Movies/20170629_00021_frameImage.mrcs MotionCorr/job109/relion30_tutorial/Movies/20170629_00021_frameImage.mrc            1     4.797000     0.092779 10864.480469 10
588.639648    87.809998     0.000000     1.000000     0.000000            1   104.138077    79.789995    17.828247     7.628693     0.467163 2.666480e+05     0.287132            4            1  2137.188248  3674.252963            1     0.570488    -65.14068 000035@Extract/job126/relion30_tutorial/Movies/20170629_00021_frameImage.mrcs MotionCorr/job109/relion30_tutorial/Movies/20170629_00021_frameImage.mrc            1     4.797000     0.092779 10864.480469 10
588.639648    87.809998     0.000000     1.000000     0.000000            1   160.388324    63.350911     6.627468     2.893875     0.450811 2.669224e+05     0.326934            5            2  3452.911785  2087.035306            1     0.006914   129.851938 000036@Extract/job126/relion30_tutorial/Movies/20170629_00021_frameImage.mrcs MotionCorr/job109/relion30_tutorial/Movies/20170629_00021_frameImage.mrc            1     4.797000     0.092779 10864.480469 10
588.639648    87.809998     0.000000     1.000000     0.000000            1     8.191853    45.839454     5.382937     0.404813     0.465482 2.664051e+05     0.341141            6            1  1171.688242  2770.617663            1     0.006026    34.225686 000037@Extract/job126/relion30_tutorial/Movies/20170629_00021_frameImage.mrcs MotionCorr/job109/relion30_tutorial/Movies/20170629_00021_frameImage.mrc            1     4.797000     0.092779 10864.480469 10
588.639648    87.809998     0.000000     1.000000     0.000000            1   171.641907    60.645842     -3.32878     5.382937     0.463405 2.668076e+05     0.189073            4            2  3032.958841  2612.717662            1     0.064813   165.514761 000038@Extract/job126/relion30_tutorial/Movies/20170629_00021_frameImage.mrcs MotionCorr/job109/relion30_tutorial/Movies/20170629_00021_frameImage.mrc            1     4.797000     0.092779 10864.480469 10
588.639648    87.809998     0.000000     1.000000     0.000000            1    45.047319    39.549220     -6.56176     7.128080     0.470515 2.668204e+05     0.397761            4            2  3469.200020  3722.252963            1     0.013144    -55.64804 000039@Extract/job126/relion30_tutorial/Movies/20170629_00021_frameImage.mrcs MotionCorr/job109/relion30_tutorial/Movies/20170629_00021_frameImage.mrc            1     4.797000     0.092779 10864.480469 10
588.639648    87.809998     0.000000     1.000000     0.000000            1    76.830840    17.621856     -5.31723     -8.30690     0.413059 2.662063e+05     0.456109            7            1  2479.700015  3248.723548            1     0.220665     1.424284 000040@Extract/job126/relion30_tutorial/Movies/20170629_00021_frameImage.mrcs MotionCorr/job109/relion30_tutorial/Movies/20170629_00021_frameImage.mrc            1     4.797000     0.092779 10864.480469 10
588.639648    87.809998     0.000000     1.000000     0.000000            1    21.870293    58.650266     1.649344     2.149956     0.467584 2.666447e+05     0.234816           11            1  2731.752957  1494.047068            1     0.256311    64.246115 000041@Extract/job126/relion30_tutorial/Movies/20170629_00021_frameImage.mrcs MotionCorr/job109/relion30_tutorial/Movies/20170629_00021_frameImage.mrc            1     4.797000     0.092779 10864.480469 10
588.639648    87.809998     0.000000     1.000000     0.000000            1   139.998402    76.720287     4.138406     -5.31723     0.470302 2.665909e+05     0.159187            3            2  2451.547073  1766.252952            1     0.163453     -5.10404 000042@Extract/job126/relion30_tutorial/Movies/20170629_00021_frameImage.mrcs MotionCorr/job109/relion30_tutorial/Movies/20170629_00021_frameImage.mrc            1     4.797000     0.092779 10864.480469 10
588.639648    87.809998     0.000000     1.000000     0.000000            1    23.433260    18.390492     -4.57331     -4.07270     0.462451 2.667357e+05     0.539987            6            1  2886.923546   878.770593            1     0.095776   -160.73984 000043@Extract/job126/relion30_tutorial/Movies/20170629_00021_frameImage.mrcs MotionCorr/job109/relion30_tutorial/Movies/20170629_00021_frameImage.mrc            1     4.797000     0.092779 10864.480469 10
588.639648    87.809998     0.000000     1.000000     0.000000            1    91.487761    88.208170     4.138406     -2.82817     0.464369 2.663907e+05     0.281618            1            2  3362.894137   502.258827            1     0.240200   -126.04910 000044@Extract/job126/relion30_tutorial/Movies/20170629_00021_frameImage.mrcs MotionCorr/job109/relion30_tutorial/Movies/20170629_00021_frameImage.mrc            1     4.797000     0.092779 10864.480469 10
588.639648    87.809998     0.000000     1.000000     0.000000            1    95.690594    67.326308     3.394487    24.050902     0.476006 2.668963e+05     0.265213            4            1  2390.105896  1449.894126            1     0.222768    -91.35973 000045@Extract/job126/relion30_tutorial/Movies/20170629_00021_frameImage.mrcs MotionCorr/job109/relion30_tutorial/Movies/20170629_00021_frameImage.mrc            1     4.797000     0.092779 10864.480469 10
588.639648    87.809998     0.000000     1.000000     0.000000            1    83.029751    62.051859     3.394487     3.394487     0.468985 2.668364e+05     0.605187            2            2  3019.958841  2241.070601            1     0.014525     2.359960 000046@Extract/job126/relion30_tutorial/Movies/20170629_00021_frameImage.mrcs MotionCorr/job109/relion30_tutorial/Movies/20170629_00021_frameImage.mrc            1     4.797000     0.092779 10864.480469 10
588.639648    87.809998     0.000000     1.000000     0.000000            1    21.874620    71.828475     -4.57331     4.138406     0.466954 2.666932e+05     0.185063            7            1   591.700003   999.229418            1     0.330014     1.987615 000047@Extract/job126/relion30_tutorial/Movies/20170629_00021_frameImage.mrcs MotionCorr/job109/relion30_tutorial/Movies/20170629_00021_frameImage.mrc            1     4.797000     0.092779 10864.480469 10
588.639648    87.809998     0.000000     1.000000     0.000000            1   116.502617     3.636812     6.384162     -4.57331     0.478187 2.669278e+05     0.874410            3            2   779.888240  1867.558834            1     0.032094   151.461460 000048@Extract/job126/relion30_tutorial/Movies/20170629_00021_frameImage.mrcs MotionCorr/job109/relion30_tutorial/Movies/20170629_00021_frameImage.mrc            1     4.797000     0.092779 10864.480469 10
588.639648    87.809998     0.000000     1.000000     0.000000            1   142.331036    27.270575     7.871999    10.361061     0.469151 2.667858e+05     0.643510           14            2  1162.264713  2559.429427            1     0.021629    -26.69159 000049@Extract/job126/relion30_tutorial/Movies/20170629_00021_frameImage.mrcs MotionCorr/job109/relion30_tutorial/Movies/20170629_00021_frameImage.mrc            1     4.797000     0.092779 10864.480469 10
588.639648    87.809998     0.000000     1.000000     0.000000            1   156.237859    37.932389     -2.08425     0.404813     0.464369 2.666664e+05     0.882495            4            2  1088.382359  1670.658833            1     0.191494    -47.27647 000050@Extract/job126/relion30_tutorial/Movies/20170629_00021_frameImage.mrcs MotionCorr/job109/relion30_tutorial/Movies/20170629_00021_frameImage.mrc            1     4.797000     0.092779 10864.480469 10
588.639648    87.809998     0.000000     1.000000     0.000000            1   135.022220    25.771972     -9.05082     3.895100     0.469806 2.666267e+05     0.515073            5            2 [root@node00 job142]#

**Comment by processEM** [comment]
Hi,
I am using Relion 3.1.2 to run CTF refinement for Relion tutorial data. The error message came out "MetaDataTable::read: file dat_mtf_k2_200kv does not exist." Should I paste below table into my run_data.star that you previously posted in this site? If I need to paste this table, where should it be located in the run_data.star? Thanks in advance.

data_mtf_k2_200kv
loop_
_rlnResolutionInversePixel
_rlnMtfValue
0.000000000 0.999999885
0.015873016 0.996121942
0.031746032 0.991044063
0.047619047 0.98482507
0.063492064 0.977522754
0.07936508 0.969193876
0.095238095 0.959894164
0.111111111 0.949678317
0.126984127 0.938599999
0.142857143 0.926711847
0.158730159 0.914065464
0.174603175 0.900711423
0.190476191 0.886699265
0.206349207 0.8720775
0.222222222 0.856893608
0.238095238 0.841194035
0.253968254 0.825024198
0.26984127 0.808428481
0.285714286 0.79145024
0.301587302 0.774131795
0.317460318 0.75651444
0.333333334 0.738638433
0.349206349 0.720543003
0.365079365 0.702266348
0.380952381 0.683845634
0.396825397 0.665316996
0.412698413 0.646715539
0.428571429 0.628075333
0.444444445 0.609429422
0.460317461 0.590809813
0.476190476 0.572247488
0.492063492 0.553772392
0.507936508 0.535413442

**Comment by biochem-fan** [comment]
Probably you put a wrong MTF file name during Import. Check the value of the `rlnMtfFileName` column in the optics group table of `run_data.star`. If the file name is wrong, fix it. **Don't** paste the content of the MTF file into the `run_data.star`.

**Comment by processEM** [comment]
Thanks for your quick response. Indeed the rlnMtfFileName column #3 does not match data optical table. It was mtf_k2_200kV.star but after I changed mtf_k2_200kV.star to mtf and re-ran CTF refinement, still get error.



ERROR:

MetaDataTable::read: File mtf does not exist

terminate called after throwing an instance of 'RelionError'





Here is the data_optical table in my run_data.star before and after change:



Before change:

# version 30001



data_optics



loop_

_rlnOpticsGroupName #1

_rlnOpticsGroup #2

_rlnMtfFileName #3

_rlnMicrographOriginalPixelSize #4

_rlnVoltage #5

_rlnSphericalAberration #6

_rlnAmplitudeContrast #7

_rlnImagePixelSize #8

_rlnImageSize #9

_rlnImageDimensionality #10

opticsGroup1     1 mtf_k2_200kV.star     0.885000   200.000000     1.400000     0.100000     1.244531          256            2





After change:

# version 30001



data_optics



loop_

_rlnOpticsGroupName #1

_rlnOpticsGroup #2

_rlnMtfFileName #3

_rlnMicrographOriginalPixelSize #4

_rlnVoltage #5

_rlnSphericalAberration #6

_rlnAmplitudeContrast #7

_rlnImagePixelSize #8

_rlnImageSize #9

_rlnImageDimensionality #10

opticsGroup1            1 mtf    0.885000   200.000000     1.400000     0.100000     1.244531          256            2



run.err:



WARNING: You did not specify --angpix_ref. The pixel size in the image header of Refine3D/job041/run_half1_class001_unfil.mrc, 1.24484 A/px, is used.

WARNING: You did not specify --angpix_ref. The pixel size in the image header of Refine3D/job041/run_half1_class001_unfil.mrc, 1.24484 A/px, is used.

WARNING: You did not specify --angpix_ref. The pixel size in the image header of Refine3D/job041/run_half1_class001_unfil.mrc, 1.24484 A/px, is used.

in: /usr/local/relion/tmp/relion-3.1.2/src/metadata_table.cpp, line 1143

ERROR:

MetaDataTable::read: File mtf does not exist

terminate called after throwing an instance of 'RelionError'

**Comment by biochem-fan** [comment]
No, the other way round!

Make sure you have `mtf_k2_200kV.star` in the project directory.

**Comment by processEM** [comment]
For some reason in my project directory, I do not have mtf_k2_200kv.star. I have no idea why the mtf_k2_200kv.star is missing and how can I get mtf_k2_200kv.star?

By the way, I copied data_mtf_k2_200kv table that you had posted in GitHub which I used for my mtf_k2_200kV.star in the project directory and I re-ran CTF refinement. It works.
