### ISSUE TITLE
GPU node crashed when running RELION

### ISSUE THREAD

**Issue by PeterXTH** [3dem/relion#682]
GPU node crashed when running RELION

I have a node with 4 GPUs, 28 CPUs, 384 GB RAM. I tried RELION 3D classification with about 500k particles with a boxsize of 320, and using 4 GPUs with 13 MPI. Usually, it works fine. But the node crashed. After restart everything. I also used RELION's own implementation for motion correction. I tested 16 micrographs with 4 MPI. It worked. However, when I increased the MPI to 8, it crashed. I checked the same data and same job on another CPU node. It worked. The IT help me with tress test running at near 100% utilization for around 24 hours now without issue. This seems to indicate that the issue is not with the hardware of the node but with the software or software parameters.
Right now I can hardly use the GPU node. Does anyone have suggestions? 
Thank you so much.

**Environment:**
 - OS: CentOS Linux, VERSION="7 (Core)"
 - MPI runtime: mpich
 - RELION version: RELION3.0 
 - Memory: 384 GB
 - GPU: 4x GTX 1080Ti

**Dataset:**
 - Pixel size: 1.16 Å/px

**Job options:**
 - Type of job: RELION Motion correction
 - Number of MPI processes: 8
 - Number of threads: 1
 - Full command:
  `which relion_run_motioncorr_mpi` --i Import/job001/movies.star --o MotionCorr/job002/ --first_frame_sum 1 --last_frame_sum -1 --use_own  --j 1 --bin_factor 2 --bfactor 150 --angpix 0.58 --voltage 200 --dose_per_frame 1.78 --preexposure 0 --patch_x 5 --patch_y 5 --gainref SuperRef_stack_00001.mrc --gain_rot 0 --gain_flip 0 --dose_weighting

**Error message:**
Node crashed. No error message.

**Comment by biochem-fan** [comment]
What do you mean by "crashed"? The node got rebooted?

> The IT help me with tress test running at near 100% utilization for around 24 hours now without issue. This seems to indicate that the issue is not with the hardware of the node but with the software or software parameters.

Not necessarily. Continuous load and intermittent load give different kind of stress to the mother board or power unit. This is clearly a hardware issue and we cannot help.

**Comment by PeterXTH** [comment]
The node is frozen and showed offline. Then it will reboot.

**Comment by biochem-fan** [comment]
This is a hardware (or kernel driver) issue.
