### ISSUE TITLE
2D classification issue on GPU TitanX2

### ISSUE THREAD

**Issue by adil-20** [3dem/relion#684]
Hi guys, I hope you doing well all, I new on using RELION 3.1, I'm facing some issues on using 2D classification on RELION 3.1 I did follow the installation and try to run the GUI it did work but when I tried to run the 2D classification it did not work, 
![Screenshot from 2020-09-26 15-44-40](https://user-images.githubusercontent.com/71946383/94349963-39d98c00-000f-11eb-903e-1b281bfc6322.png)

I wen back to the comment line approach and download the benchmark dataset with the STAR file and when I tried to run the following comment:

mpirun -n XXX which relion_refine_mpi --i Particles/shiny_2sets.star --ctf --iter 25 --tau2_fudge 2 --particle_diameter 360 --K 200 --zero_mask --oversampling 1 --psi_step 6 --offset_range 5 --offset_step 2 --norm --scale --random_seed 0 --o class2d

I got the following error:

![Screenshot from 2020-09-26 15-38-19](https://user-images.githubusercontent.com/71946383/94349950-0c8cde00-000f-11eb-87bc-3df86daee6ea.png

I just need to do the correct 2D classification on the RELION benchmark please, appreciate your help

**Comment by biochem-fan** [comment]
First of all:

- Please don't post the same question to many issues.
- Don't use use screenshots when you can copy-and-paste error messages. (images are not searchable)

> mpirun -n XXX 

XXX must be replaced with the number of MPI processes you want to use.

**Comment by adil-20** [comment]
Thanks I did and I got this error

mpirun: Error: unknown option "--i"

**Comment by biochem-fan** [comment]
Is `relion_refine_mpi` in your PATH?

**Comment by adil-20** [comment]
Yes, this a screenshot to what I did and the error 
![Screenshot from 2020-09-27 11-31-03](https://user-images.githubusercontent.com/71946383/94370342-0cdfb480-00b5-11eb-8aaf-049598d3ee4f.png)

**Comment by biochem-fan** [comment]
> Yes, this a screenshot

**Don't use use screenshots when you can copy-and-paste error messages.**

What you showed is that your folder contains `relion_refine_mpi` but you didn't show the PATH (i.e. environmental variable) contains the folder.

**Comment by adil-20** [comment]
How can I show that?

**Comment by biochem-fan** [comment]
Please study http://www.linfo.org/path_env_var.html.

**Comment by adil-20** [comment]
Thanks for your replay I did and I got this 
![Uploading Screenshot from 2020-09-27 21-48-24.png…]()

Does that seems correct?

**Comment by biochem-fan** [comment]
Not at all. Please read the page correctly. And I told you twice "*Don't use use screenshots*" and you are still using screenshots.

**Comment by adil-20** [comment]
I did use the copy-paste the message 'path' and it did not show it correctly, for this reason I used the screenshot, could you please be more flexible? anyway thanks for your time
