### ISSUE TITLE
Postprocess Failed - GPL Ghostscript 9.25

### ISSUE THREAD

**Issue by CFDavidHou** [3dem/relion#686]
Hi there,

When I doing postprocess on my 640 box, pixel size 1.42 particles I encountered the following errors:

```
GPL Ghostscript 9.25: Unrecoverable error, exit code 1
 ERROR in executing: gs -sDEVICE=pdfwrite -dNOPAUSE -dBATCH -dSAFER -dDEVICEWIDTHPOINTS=800 -dDEVICEHEIGHTPOINTS=800 -sOutputFile=PostProcess/job127/logfile.pdf @PostProcess/job127/logfile.pdf.lst > /dev/null
 + Will make an empty PDF-file in PostProcess/job127/logfile.pdf
```

I can see a 800 value in the error code but there is nowhere I can set the parameter. In tab Sharpen and Filter I use tutorial 3.1 default  settings. The model has been 3D auto-refined and mask-created.

Thank you!

David

**Comment by biochem-fan** [comment]
Do you have Ghostscript?

800 has nothing to do with your processing; it is a parameter for making a PDF file.

**Comment by CFDavidHou** [comment]
Hmm I don't know what happened. But I re-made a mask with different initial binarisation threshold and do the post-processing. There was no more errors. I still don't know the reason.

Best,
