### ISSUE TITLE
Error during 3D classification: No orientation was found as better than any other

### ISSUE THREAD

**Issue by mecyshi** [3dem/relion#693]
Hi,

When I performed 3D classification in Relion-3.1.0-commit-618a63, an error happens. The command line is: 

`which relion_refine_mpi` --o Class3D/job092/run --i Extract/job090/particles.star --ref run_it139_class003_250_2.8.mrc --firstiter_cc --ini_high 60 --dont_combine_weights_via_disc --pool 50 --pad 2  --ctf --iter 200 --tau2_fudge 3 --particle_diameter 420 --fast_subsets  --K 3 --flatten_solvent --zero_mask --oversampling 1 --healpix_order 2 --offset_range 5 --offset_step 2 --sym C1 --norm --scale  --j 6 --gpu "0:1:2:3:4:5:6:7"  --pipeline_control Class3D/job092/

ERROR is:
No orientation was found as better than any other.

A particle image was compared to the reference and resulted in all-zero
weights (for all orientations). This should not happen, unless your data
has very special characteristics. This has historically happened for some 
lower-precision calculations, but multiple fallbacks have since been 
implemented. Please report this error to the relion developers at 

	         github.com/3dem/relion/issues  
 
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 4

Could you help with this? Thanks.
Zhubing

**Comment by biochem-fan** [comment]
https://www3.mrc-lmb.cam.ac.uk/relion/index.php/FAQs#Refinement_or_Classification_crash_saying_.22No_orientation_was_found.22

**Comment by mecyshi** [comment]
Thanks. I have solved this issue. The error occurs because the original images are not in the Relion folder.
