### ISSUE TITLE
Using relion30_tutorial data -

### ISSUE THREAD

**Issue by Furciferi** [3dem/relion#701]
Hi,
Im hoping you can help with testing relion-3.1.0 on our cluster.

I've installed relion 3.1.0 for our HPC users, and would like to test to see if i've set the cluster environment correctly by following the tutorial pdf.

However Im using the tar ball with example movies from 3.0 and run into:

`ERROR:
StarConverter::convert_3p0_particlesTo_3p1: Star file is already at version 3.0001`

When trying to test MotionCorr

Any tips or advice on what I need to do to use the 3.0 tar ball data with 3.1 - or if theres some testing data for 3.1.0 i've missed?

**Comment by biochem-fan** [comment]
The data (movies) themselves are common but you have to process everything using 3.1 from scratch. Also note that:

> Wherever you install RELION, make sure your PATH environmental variable points to the directory containing relion binaries. Launching RELION with a path like /path/to/relion is not a right way; this starts the right GUI, but the GUI might invoke other versions of RELION in the PATH.

https://www3.mrc-lmb.cam.ac.uk/relion/index.php/Download_%26_install#Specifying_an_installation_location

**Comment by Furciferi** [comment]
Thanks for the quick reply.
I've built everything as a Lmod module, and it has no information on other RELION builds we have.

I was being a complete novice and our user has correctly pointed out I should be running motioncorr on movies.star not default_pipeline.

Sorrry! Will close - thank you!
