### ISSUE TITLE
MPI error installation

### ISSUE THREAD

**Issue by rshek351** [3dem/relion#702]
**running just sudo cmake ..**
`-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc - works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ - works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- BUILD TYPE set to the default type:  'Release'
-- Setting fallback CUDA_ARCH=35
-- ALLOW_CTF_IN_SAGD enabled - This build of RELION allows modulation of particle images by a contrast transfer function inside stochastic average gradient descent, as specified in Claim 1 of patent US10,282,513B2
-- CUDA enabled - Building CUDA-accelerated version of RELION
-- Setting cpu precision to double
-- Setting accelerated code precision to single
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found CUDA: /usr/local/cuda (found version "11.1") 
-- Using cuda wrapper to compile....
-- Cuda version is >= 7.5 and single-precision build, enable double usage warning.
-- Could NOT find MPI_C (missing: MPI_mpi_LIBRARY MPI_C_HEADER_DIR MPI_C_WORKS) 
-- Could NOT find MPI_CXX (missing: MPI_mpicxx_LIBRARY MPI_mpi_LIBRARY MPI_CXX_HEADER_DIR MPI_CXX_WORKS) 
CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:164 (message):
  Could NOT find MPI (missing: MPI_C_FOUND MPI_CXX_FOUND)

      Reason given by package: MPI component 'Fortran' was requested, but language Fortran is not enabled.  

Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:445 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake/Modules/FindMPI.cmake:1717 (find_package_handle_standard_args)
  CMakeLists.txt:216 (find_package)

-- Configuring incomplete, errors occurred!
See also "/usr/local/bin/relion/build/CMakeFiles/CMakeOutput.log".
See also "/usr/local/bin/relion/build/CMakeFiles/CMakeError.log".
`
**so then i ran sudo cmake -DCMAKE_C_COMPILER=/usr/lib64/mpi/gcc/openmpi3/bin/mpicc -DCMAKE_CXX_COMPILER=/usr/lib64/mpi/gcc/openmpi3/bin/mpicxx -DCMAKE_Fortran_COMPILER=/usr/lib64/mpi/gcc/openmpi3/bin/mpif90 ..**

`-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Check for working C compiler: /usr/lib64/mpi/gcc/openmpi3/bin/mpicc
-- Check for working C compiler: /usr/lib64/mpi/gcc/openmpi3/bin/mpicc - works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/lib64/mpi/gcc/openmpi3/bin/mpicxx
-- Check for working CXX compiler: /usr/lib64/mpi/gcc/openmpi3/bin/mpicxx - works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- BUILD TYPE set to the default type:  'Release'
-- Setting fallback CUDA_ARCH=35
-- ALLOW_CTF_IN_SAGD enabled - This build of RELION allows modulation of particle images by a contrast transfer function inside stochastic average gradient descent, as specified in Claim 1 of patent US10,282,513B2
-- CUDA enabled - Building CUDA-accelerated version of RELION
-- Setting cpu precision to double
-- Setting accelerated code precision to single
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Found CUDA: /usr/local/cuda (found version "11.1") 
-- Using cuda wrapper to compile....
-- Cuda version is >= 7.5 and single-precision build, enable double usage warning.
-- Found MPI_C: /usr/lib64/mpi/gcc/openmpi3/bin/mpicc (found version "3.1") 
-- Found MPI_CXX: /usr/lib64/mpi/gcc/openmpi3/bin/mpicxx (found version "3.1") 
-- Found MPI: TRUE (found version "3.1")  
CMake Error at CMakeLists.txt:219 (include_directories):
  include_directories given empty-string as include directory.

-- MPI_INCLUDE_PATH : 
-- MPI_LIBRARIES : 
-- MPI_CXX_INCLUDE_PATH : 
-- MPI_CXX_LIBRARIES : 
-- CMAKE_C_COMPILER : /usr/lib64/mpi/gcc/openmpi3/bin/mpicc
-- CMAKE_CXX_COMPILER : /usr/lib64/mpi/gcc/openmpi3/bin/mpicxx
-- MPI_C_COMPILER : /usr/lib64/mpi/gcc/openmpi3/bin/mpicc
-- MPI_CXX_COMPILER : /usr/lib64/mpi/gcc/openmpi3/bin/mpicxx
-- CMAKE_CXX_COMPILER_ID : GNU
-- CMAKE_C_COMPILER : /usr/lib64/mpi/gcc/openmpi3/bin/mpicc
-- CMAKE_CXX_COMPILER : /usr/lib64/mpi/gcc/openmpi3/bin/mpicxx
-- MPI_C_COMPILER : /usr/lib64/mpi/gcc/openmpi3/bin/mpicc
-- MPI_CXX_COMPILER : /usr/lib64/mpi/gcc/openmpi3/bin/mpicxx
-- Found X11: /usr/include   
-- Looking for XOpenDisplay in /usr/lib64/libX11.so;/usr/lib64/libXext.so
-- Looking for XOpenDisplay in /usr/lib64/libX11.so;/usr/lib64/libXext.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
CMake Warning (dev) at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:272 (message):
  The package name passed to `find_package_handle_standard_args` (X11) does
  not match the name of the calling package (FLTK).  This can lead to
  problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindX11.cmake:366 (find_package_handle_standard_args)
  /usr/share/cmake/Modules/FindFLTK.cmake:98 (include)
  CMakeLists.txt:302 (FIND_PACKAGE)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found FLTK: /usr/lib64/libfltk_images.so;/usr/lib64/libfltk_forms.so;/usr/lib64/libfltk.so  
-- X11 and FLTK were found
-- FLTK_LIBRARIES: /usr/lib64/libfltk_images.so;/usr/lib64/libfltk_forms.so;/usr/lib64/libfltk.so;/usr/lib64/libX11.so;/usr/lib64/libXext.so;/usr/lib64/libm.so
-- Found FFTW
-- FFTW_PATH: /usr/include
-- FFTW_INCLUDES: /usr/include
-- FFTW_LIBRARIES: /usr/lib64/libfftw3f.so;/usr/lib64/libfftw3.so
-- Looking for sincos
-- Looking for sincos - found
-- Looking for __sincos
-- Looking for __sincos - not found
-- Found TIFF: /usr/lib64/libtiff.so (found version "4.0.9") 
-- Found ZLIB: /usr/lib64/libz.so (found version "1.2.11") 
-- Found PNG: /usr/lib64/libpng.so (found version "1.6.34") 
BUILD_SHARED_LIBS = OFF
-- Building static libs (larger build size and binaries)
Running apps/CMakeLists.txt...
-- CMAKE_BINARY_DIR:/usr/local/bin/relion/build
-- Git commit ID: 618a366dcf346ce9e5bfa57988351b4f700f79dc
-- Found OpenMP_C: -fopenmp (found version "4.5") 
-- Found OpenMP_CXX: -fopenmp (found version "4.5") 
-- Found OpenMP: TRUE (found version "4.5")  
-- Configuring incomplete, errors occurred!
See also "/usr/local/bin/relion/build/CMakeFiles/CMakeOutput.log".
See also "/usr/local/bin/relion/build/CMakeFiles/CMakeError.log".
`

**any suggestions on what to try next?**

**Comment by biochem-fan** [comment]
What happens if you put `/usr/lib64/mpi/gcc/openmpi3/bin` into your `PATH` environmental variable and `/usr/lib64/mpi/gcc/openmpi3/lib` into your `LD_LIBARY_PATH` environmental variable, instead of using -DCMAKE... options? Also note that cmake sometimes caches previous configurations. Delete everything in your build directory before you try something next.

**Comment by rshek351** [comment]
I had tried adding openmpi to my path by appending the following to my bashrc
#MPI
export PATH="/usr/lib64/mpi/gcc/openmpi3/bin:"$PATH
export LD_LIBRARY_PATH=/usr/lib64/mpi/gcc/openmpi3/lib64:$LD_LIBRARY_PATH

source ~/.bashrc
sudo rm -r build (in relion directory)
sudo mkdir build
and reran sudo cmake .. 

to get the first error where MPI is not found?

**Comment by biochem-fan** [comment]
Is your OpenMPI built against GNU 7.5.0, the system compiler?

You also don't need `sudo` for `cmake`. It is only necessary for the last `make install` step.

**Comment by rshek351** [comment]
OKAY, so I got it to work by commenting out lines 216-222 in the cmakelists.txt and re-running cmake with all the -DCMAKE options. Not sure why openmpi doesnt play nice with cmake in OpenSUSE LEAP, all packages were downloaded from the main repos and this was on a fresh install...Relion launches now, so I will call it a success.  Thank you for all your help! Looking forward to using Relion 👍
