### ISSUE TITLE
Control the iteration of refine3D

### ISSUE THREAD

**Issue by ghl1995** [3dem/relion#711]
Hi, how could I choose iteration numbers in refine3D? --sgd_ini_iter  --sgd_inbetween_iter  --sgd_fin_iter  is not useful

**Comment by biochem-fan** [comment]
Why do you want to do so? This is not recommended.

**Comment by ghl1995** [comment]
The default is 25? I want to know how I set the iteration number or it is fixed?

**Comment by biochem-fan** [comment]
In classification, you can set the number of iterations. In Refine3D and MultiBody, the process is automatic; it continues until convergence. You should NOT tweak the number unless there is some special reason to justify it.

> In my task, the first 9 iterations only last about a half-hour but the 10th iteration consumes 3hour, why?

Probably the angular sampling increased from the iteration.

**Comment by ghl1995** [comment]
Hello, the refine 3D reconstruction values beyond (0,1),   Does this influence the multibody-refinement process? because mask file need be 0,1 value
