### ISSUE TITLE
Refine 3D reconstruction Values beyond (0,1)

### ISSUE THREAD

**Issue by ghl1995** [3dem/relion#712]
Hello, the refine 3D reconstruction values beyond (0,1) because I use --no_norm, Does this influence the multibody-refinement process? because mask file need be 0,1 value.  Or just the mask within (0,1) is enough?

**Comment by biochem-fan** [comment]
The map value can be anything. The map value is multiplied by the mask. Thus, the mask must be within [0, 1] (0 = totally suppress, 1 = keep as is).
