### ISSUE TITLE
--always_cc is checked twice: as expert and as hidden/debugging option

### ISSUE THREAD

**Issue by joton** [3dem/relion#714]
I guess it should be visible as expert option but I report in case the purpose is the other.

**Comment by biochem-fan** [comment]
Where? It is an expert option for new jobs (line 464 in the ver3.1 branch) and hidden for continuation (line 737), because it does not really make sense to switch from squared diff into CC in later iterations.

**Comment by joton** [comment]
OK, I wasn't aware that it was checked as hidden option for continuation. I understand now. Thanks.
I close it.
