### ISSUE TITLE
RELION's "Start project" query

### ISSUE THREAD

**Issue by mcahn** [3dem/relion#716]
When you start RELION in a new directory, it asks "Only run the relion GUI from your ProjectDirectory. Do you want to start a new project here [y/n]?".  This presents a stumbling block for users who are new to Linux.  If you run RELION in the foreground, then your shell is not available for other commands.  If you run RELION in the background, you can't answer the question.  I usually tell users to start two terminals, one for starting RELION in the foreground, and another for other commands.  Alternatively, one can start RELION in the foreground, answer the question, and then interrupt it with control-z and put it in the background with "bg", but that's a lot to explain to a new user.

I'd like to suggest a different interface for starting a project.  "Start project" could be the first item in the menu on the left, before "Import".  Or perhaps there could be a "Start project" button in the "Import" UI.

Matthew Cahn

**Comment by biochem-fan** [comment]
How about asking the question `Only run the relion GUI from your ProjectDirectory. Do you want to start a new project here?` in a dialog box with Yes and No buttons?

> Alternatively, one can start RELION in the foreground, answer the question, and then interrupt it with control-z and put it in the background with "bg", but that's a lot to explain to a new user.

That being said, users have to learn these UNIX basics sooner or later.

**Comment by mcahn** [comment]
A dialog would get around the problem of having to run the program in the
foreground.  However, I believe it would be the only thing in RELION that
cares what the current directory was when you launched the program.  It
would be more consistent if one could navigate in the GUI to some
directory, and possibly create a project directory there from the GUI.
That navigation would be analogous to how one imports movies, for example.

People do have to learn about the command line.  I teach one lecture in a
class on cryoem, and also spend a lot of one-on-one time with grad students
and postdocs, to help people use our HPC cluster and submit RELION jobs.
Rarely are any of the students familiar with Linux or the command line.
They need to install XQuartz or MobaXterm, learn to log in, navigate (pwd,
cd), learn about SLURM, learn what a GPU is, and learn an editor. So I
don't like to add shell job control to all that. I'd rather let them get
back to actual science.

Matthew

**Comment by biochem-fan** [comment]
I might use the dialog box in future but I don't agree with your "consistency" logic.
