### ISSUE TITLE
Missing library and conflicts when installing

### ISSUE THREAD

**Issue by wjnicol** [3dem/relion#718]
Hello,

I am trying to install Relion and the $cmake .. command gives out a bunch of warnings of two sorts:

1- It tells me it cannot find  TIFF nor PNG (missing TIFF_LIBRARY, PNG_LIBRARY, TIFF_INCLUDE_DIR and PNG_PNG_INCLUDE_DIR)

![requirements_relion](https://user-images.githubusercontent.com/75800946/101799954-8f2b2280-3ac1-11eb-8b00-2ece46ab9864.png)

I tried installing libtiff-dev and libpng using a package manager called synaptic but the same warnings persist. I wonder if cmake is not looking in the right places for these libraries.

2- I get loads of warnings mentioning the following: 

![lib_errors](https://user-images.githubusercontent.com/75800946/101800030-a79b3d00-3ac1-11eb-9c3f-978d9aaf61b4.png)

I got these errors after installing the latest libtiff5 and there seems to be some conflict with EMAN2 maybe?
I also read on the wiki that I should beware of which MPI version is being compiled. I don't understand what to do here.

I have several other softwares like EMAN2, IMOD and Amira on my ubuntu machine and did not start trying to replace libraries with others by fear of breaking everything.

Thanks for the help.

William J Nicolas

**Comment by biochem-fan** [comment]
Please stop sourcing EMAN2, IMOD etc in your `~/.bashrc` so that you have clean `PATH` and `LD_LIBRARY_PATH`.

**Comment by wjnicol** [comment]
Hello,

Thanks for the response. Apologies for the screenshots, first-timer on Github.

How should I source Eman2 and IMOD then for them to work?

**Comment by biochem-fan** [comment]
Source RELION or EMAN2 only when you used it. This is a basic Linux question. Please look around.
