### ISSUE TITLE
relion_import ignores --ofile

### ISSUE THREAD

**Issue by lkater** [3dem/relion#720]
Hi!
I possibly found a minor bug running relion_import from terminal:

relion_import ignores --ofile flag and uses default name

test command:
`which relion_import`  --do_movies  --optics_group_name "oG1" --angpix 1.1 --kV 300 --Cs 2.7 --Q0 0.1 --beamtilt_x 0 --beamtilt_y 0 --i "raw/*.tif" --ofile movies_test.star --odir ./

expected behaviour: create movies_test.star
experienced behaviour:  creates movies.star 

**Environment:**
 - OS: CentOS7
 - MPI runtime: 1.10.7
 - RELION version: 3.1.1-commit-fd1bb7

**Comment by biochem-fan** [comment]
You are right. Thanks for reporting.

**Comment by lkater** [comment]
Sorry  for posting here again. It worked for a while, but since I rebuilt relion today it is broken again?
git pull
Already up-to-date.

relion --version
RELION version: 3.1.1-commit-9f3bf1 
Precision: BASE=double, VECTOR-ACC=single

**Comment by biochem-fan** [comment]
Commit 9f3bf1 is much older than the above commit to fix it (d51f8af). Probably you are not in the `ver3.1` branch, but in `master`.
