### ISSUE TITLE
[Motion Correction] could not generate EPS file

### ISSUE THREAD

**Issue by alexnovaris** [3dem/relion#723]
Hello everyone, 

I tried to use Motion correction on the GUI of relion after importation of my micrographs. 

As input for the job I used the micrographs.star and when I filled all of the fields from my data (used own Relion's implementation) and clicked on run. I tried on multiply  occasions to make sure it wasn't a "one time problem".
Then an error appeared : 
"Did not find any of the expected EPS files to generate PDF file
+ Will make an empty PDF-file in MotionCorr/job005/logfile.pdf"

I know that GhostScript is used for converting EPS to PDF and the package is up to date. In addition, motion correction works with the tutorial data (the difference is that I am currently working with tif micrographs and not tiff movies).
I searched what the cause of this issue could be and I don't know where this could come from except from my tif images.
The thing is I tried also to remove tag from tif file without successful result. I used other micrographs and I have the same problem.

**Environment:**
 - OS: Ubuntu 20.04.01 LTS
 - MPI runtime: Debian MPI v.4.0.3
 - RELION version [e.g. RELION-3.1.1.commit-9f3bf1
 - Memory: 16 GB
 - GPU: GTX 1660 Ti

**Dataset:**
 Helix of peptide
Pixel size =460 pm

**Job options:**
 - Type of job: Motion Correction
 - Number of MPI processes: 1
 - Number of threads: 6
 - Full command (see `note.txt` in the job directory):
 

 ++++ Executing new job on Fri Jan 15 11:05:38 2021
 ++++ with the following command(s): 
`which relion_run_motioncorr` --i Import/job004/micrographs.star --o MotionCorr/job005/ --first_frame_sum 1 --last_frame_sum 0 --use_own  --j 6 --bin_factor 1 --bfactor 150 --dose_per_frame 1.277 --preexposure 0 --patch_x 5 --patch_y 5 --eer_grouping 32 --dose_weighting  --save_noDW  --grouping_for_ps 3   --pipeline_control MotionCorr/job005/
 ++++ 

**Error message:**

 Did not find any of the expected EPS files to generate a PDF file
+ Will make an empty PDF-file in MotionCorr/job005/logfile.pdf

If I did something wrong do not hesitate to point me the mistake.

**Comment by biochem-fan** [comment]
> micrographs.star

Usually this is `movies.star`. Did you import movies as such, not as micrographs?

**Comment by alexnovaris** [comment]
I did not try that one because each tif file is only one image as they are not multi-frame movies. 
I just tested your method and the error says that I have less than 3 frames per file but for me this is normal because I have only one image per tif file.

Maybe I can only use multiframe movies ?

**Comment by biochem-fan** [comment]
If the input is not multi-frame movie, why do you want to run motion correction? It does not make sense.

**Comment by alexnovaris** [comment]
Yes you are right I have mistaken everything in my dataset
Thank you very much for your replies
