### ISSUE TITLE
relion_flex_analyse command options not valid

### ISSUE THREAD

**Issue by bingwang14** [3dem/relion#724]
**Describe your problem**
I recently run multi-body refinement tutorial (ftp://ftp.mrc-lmb.cam.ac.uk/pub/scheres/multibody_protocol.pdf), but came across a problem when performing partial signal subtraction after multi-body refinement with the command relion_flex_analyse. The warning says options --subtract, --keep_inside, and --ctf are all not valid. I checked this command with the option --help and indeed no such options available. I was using relion 3.1.1. Is there an alternative job option for achieving that goal? I did see an job option "Particle subtraction" on relion GUI. Is that the replacement? Thanks.

**Environment:**
 - OS: Ubuntu 16.04.4 LTS
 - RELION version 3.1.1-commit-9f3bf1  
 - Memory: [e.g. 128 GB]
 - GPU: [e.g. GTX 1080Ti]

**Dataset:**
 the tutorial test dataset

**Job options:**
 
relion_flex_analyse --data MultiBody/job002/run_ct5_data.star --model MultiBody/job002/run_ct5_model.star --bodies Example/4-bodies-tight-mask.star --o Substract/sf3b --subtract --keep_inside Mask-and-Ref/SF3b_mask.mrc --ctf  

**Error message:**
The following warnings were encountered upon command-line parsing: 
WARNING: Option --subtract	is not a valid RELION argument
WARNING: Option --keep_inside	is not a valid RELION argument
WARNING: Option --ctf	is not a valid RELION argument

**Comment by biochem-fan** [comment]
The tutorial is based on RELION 3.0. In RELION 3.1, the functionality is in the Particle Subtraction GUI.
