### ISSUE TITLE
ctffind_runner fails with tiff images

### ISSUE THREAD

**Issue by gruchalla** [3dem/relion#728]
CTFFIND can process tiff images. Relion launches CTFFIND and executes correctly, but the ctffind_runner fails with warning messages:

> WARNING: skipping, since cannot get CTF values for images/4_bl.000.tif

The issue is cttfind_runner is hard-coded to strip ".mrc" off the image filenames when looking for ctf files, so it cannot find them. For the above example, instead of looking for the _4_bl.000.ctf_ that ctffind created, it is looking for _4_bl.000.tif.ctf_ which doesn’t exist. See ctffind_runner.cpp line 252:
`FileName fn_microot = fn_mic_ctf_given_all[imic].without(".mrc");`
and line 431:
`FileName fn_microot = fn_micrographs_ctf_all[imic].without(".mrc")`

replacing these lines with 
`FileName fn_microot = fn_mic_ctf_given_all[imic].withoutExtension();`
and
`FileName fn_microot = fn_micrographs_ctf_all[imic].withoutExtension();`

respectively, appears to resolve the problem with tiff images.

**Comment by biochem-fan** [comment]
This makes sense. I applied your suggestion in commit 319cd1b. Thank you very much for feedback.
