### ISSUE TITLE
symbol lookup error after default installation

### ISSUE THREAD

**Issue by koschie** [3dem/relion#729]
I ran the default installation with no errors or warnings given. The only specified parameter was number of processes in 'make'

when i run relion in a project folder i get this error

`relion: symbol lookup error: relion: undefined symbol: _ZN6Fl_BoxC1EiiiiPKc`

any help would be appreciated.

System info:
`System:    Kernel: 5.9.16-1-MANJARO x86_64 bits: 64 compiler: gcc v: 10.2.1 Desktop: Xfce 4.16.0 Distro: Manjaro Linux 
Machine:   Type: Desktop System: Gigabyte product: X570 AORUS PRO WIFI v: -CF serial: <filter> 
           Mobo: Gigabyte model: X570 AORUS PRO WIFI v: x.x serial: <filter> UEFI: American Megatrends v: F12e 
           date: 03/06/2020 
CPU:       Info: 12-Core model: AMD Ryzen 9 3900X bits: 64 type: MT MCP arch: Zen 2 rev: 0 L2 cache: 6 MiB 
           flags: avx avx2 lm nx pae sse sse2 sse3 sse4_1 sse4_2 sse4a ssse3 svm bogomips: 182129 
           Speed: 2194 MHz min/max: 2200/3800 MHz boost: enabled Core speeds (MHz): 1: 2194 2: 2191 3: 2791 4: 1862 5: 2189 
           6: 2188 7: 2196 8: 2186 9: 2196 10: 2195 11: 2186 12: 2186 13: 2198 14: 2194 15: 1858 16: 2790 17: 1855 18: 2193 
           19: 2195 20: 2196 21: 2194 22: 2194 23: 2191 24: 1862 
Graphics:  Device-1: NVIDIA TU104 [GeForce RTX 2080 SUPER] vendor: eVga.com. driver: nvidia v: 460.32.03 bus ID: 09:00.0 
           Display: x11 server: X.Org 1.20.10 driver: loaded: nvidia resolution: 1: 1080x1920 2: 2560x1440~75Hz 3: 2560x1440 
           OpenGL: renderer: GeForce RTX 2080 SUPER/PCIe/SSE2 v: 4.6.0 NVIDIA 460.32.03 direct render: Yes`

**Comment by biochem-fan** [comment]
Explained in README.

> If FLTK related errors are reported, please add -DFORCE_OWN_FLTK=ON to cmake. For FFTW related errors, try -DFORCE_OWN_FFTW=ON.

**Comment by biochem-fan** [comment]
Also see issue #606.

**Comment by koschie** [comment]
worked perfectly thanks
