### ISSUE TITLE
Relion 3.1.1 install problem

### ISSUE THREAD

**Issue by chempia** [3dem/relion#730]
I have been trying to install RELION 3.1.1 on my computer as a superuser. Basic information about my hardware is as follows:

CentOS 7.9.2009
CUDA 11.2
Four NVIDIA GTX1080 cards

When I tried to install RELION 3.1.1 using options -DCUDA_ARCH=61 -DCMAKE_INSTALL_PREFIX={my own choice of directory} failed at the stage of "build". 

==== (Last part of screen output) ====
CMake Error at relion_gpu_util_generated_cuda_ml_optimiser.cu.o.Release.cmake:280 (message):
  Error generating file
  
(...)/relion/relion/build/src/apps/CMakeFiles/relion_gpu_util.dir/__/acc/cuda/./relion_gpu_util_generated_cuda_ml_optimiser.cu.o

gmake[2]: *** [src/apps/CMakeFiles/relion_gpu_util.dir/__/acc/cuda/relion_gpu_util_generated_cuda_ml_optimiser.cu.o] Error 1
gmake[1]: *** [src/apps/CMakeFiles/relion_gpu_util.dir/all] Error 2
gmake: *** [all] Error 2
==== (End of screen output) ====

When I tried to install RELION 3.1.1 with -DCUDA=OFF option, everything went okay. 

Can somebody help me resolve this issue?

Thank you.

Sangho

**Comment by biochem-fan** [comment]
Please re-run `make` without `-j` option and cite the FULL error message.

**Comment by chempia** [comment]
Thanks @biochem-fan for a quick suggestion. I ran <make> without <-j> option and am posting the full error message below:


[error.txt](https://github.com/3dem/relion/files/5943545/error.txt)

**Comment by biochem-fan** [comment]
This is a very strange problem.

https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html says CUDA 11.2 requires GCC 4.8.5. Which version of GCC are you using? How about `mpic` wrapper?

**Comment by chempia** [comment]
GCC version is 4.8.5; MPI version 3; OpenMPI version 3.1.

**Comment by biochem-fan** [comment]
CUDA (`nvcc`) and OpenMPI (`mpic`) internally use GCC. Make sure they use the same version of GCC (4.8.5 in this case). Your `error.txt` mentions files from 4.8.2; there are some mixing ups.

**Comment by chempia** [comment]
Since I am not an experienced user in linux, I am lost in how to synchronize the versions of CUDA nvcc and OpenMPI mpic. Can you give some advice?

**Comment by chempia** [comment]
I found that in the directory '/usr/include/c++' there was a symbolic link named '4.8.5' actually connected to '4.8.2' directory. I could not find any real directory for '4.8.5'. Can you tell me how to fix this issue?

**Comment by biochem-fan** [comment]
I am afraid to say your system is in a weird, messy state. Since this is not a RELION problem but a Linux problem, we cannot help.

**Comment by biochem-fan** [comment]
@chempia See issue #736. Updating glibc might help.

**Comment by chempia** [comment]
Finally I managed to install Relion 3.1.1 on my two linux computers. Both have CentOS 7.9.2009 installed and NVIDIA graphic cards (one computer with GTX 1080 and the other with GTX 1050). Trick was to use CUDA 8.0: other CUDA versions such as 9.2 and 10.2 did not work for me.

To summarize my basic configuration for installing RELION 3.1.1:
CentOS 7.9.2009 (GNU gcc version 4.8.5)
CUDA 8.0 (although the systems also have CUDA 11.2 installed as well)
MPICH 3.2
