### ISSUE TITLE
Compile problem on CentOS 7

### ISSUE THREAD

**Issue by dmccully** [3dem/relion#736]
When compiling Relion, I'm getting a error at the  library build phase.   Any assistance would be appreciated.  :) 
Version 3.0 or 3.1 gives me the same issues.  See attached. 

Dwayne
[Relion-errors.txt](https://github.com/3dem/relion/files/5976252/Relion-errors.txt)

**Comment by biochem-fan** [comment]
Potentially related to #730?

Can you try with earlier CUDA SDK (10.x)?

**Comment by biochem-fan** [comment]
I tested compilation with CUDA 11.2 + GCC 4.8.5 on Scientific Linux 7.9. It worked fine.

**Comment by biochem-fan** [comment]
Also related to this? https://github.com/BVLC/caffe/issues/6011

Can you make sure your `nvcc` is really using gcc 4.8.5, not earlier versions?

**Comment by truatpasteurdotfr** [comment]
maybe related to the bad glibc-2.17-322 release, fixed now with glibc-2.17-323.el7_9.x86_64.

**Comment by dmccully** [comment]
Hi Huynh,

Updating the glibc fixed the issue. 😊

Thank you for the tip!

Dwayne

**Comment by ahm9th** [comment]
I have struggled much to compile Relion. It took more than a month for me... 

However, I can confirm that, I finally managed to compile it on CentOS cluster, using the native gcc (4.8.5) of the OS, CUDA 11.2 (11.2.1_460.32.03) and openmpi 4.1.0.
