### ISSUE TITLE
4K rendering EER creates line artifacts on Relion-3.1.2

### ISSUE THREAD

**Issue by CFDavidHou** [3dem/relion#742]
Hi there,

This my first time using EER format movies on Relion. I have read the instruction on https://www3.mrc-lmb.cam.ac.uk/relion/index.php/Image_compression#Falcon4_EER

I am running Relion-3.1.2 on Ubuntu 20.04 and the movies are 4K resolution. I do not know if I have done it wrong.

Please see my micrographs properties and Relion settings below.

![image](https://user-images.githubusercontent.com/71337645/109996049-d8fc6100-7cdc-11eb-8ae2-c357fe60dc18.png)

![image](https://user-images.githubusercontent.com/71337645/109996105-e74a7d00-7cdc-11eb-952c-6c83686f1fd3.png)

![image](https://user-images.githubusercontent.com/71337645/109996118-eade0400-7cdc-11eb-8fe9-b64cc8f5861a.png)

![image](https://user-images.githubusercontent.com/71337645/109996132-ef0a2180-7cdc-11eb-9623-505f9ba72ace.png)

![image](https://user-images.githubusercontent.com/71337645/109996155-f5000280-7cdc-11eb-9c51-2ebe1797bb19.png)

Thank you!

David

**Comment by biochem-fan** [comment]
These are defective lines. Please use the gain reference written by the detector software or make your own defect file.

**Comment by CFDavidHou** [comment]
Thank you @biochem-fan. But why does my regular mrc or tiff movies do not have the defected lines on my Falcon4? I am confused.

**Comment by biochem-fan** [comment]
If you use MRC for Falcon3/4, the defect lines are patches by the detector software. EER outputs are closer to "raw" data so defect correction is user's responsibility.

**Comment by CFDavidHou** [comment]
Thank you so much! Now I get it!

**Comment by biochem-fan** [comment]
P.S.

If you have problems making a defect file, share one movie on DropBox; I will investigate the file.

**Comment by CFDavidHou** [comment]
Will the gain-ref work as a defect  file?

**Comment by biochem-fan** [comment]
This depends. If the detector software knows the location, it sets the gain value to 0 for such pixels and RELION respects it. Otherwise, you should make your own defect file by checking the coordinates (click the "?" button for "Defect file" field).

**Comment by CFDavidHou** [comment]
> P.S.
> 
> If you have problems making a defect file, share one movie on DropBox; I will investigate the file.

https://www.dropbox.com/s/hceohlkys2i73ss/FoilHole_2341597_Data_2336741_2336743_20210303_152530_EER.mrc?dl=0

Thank you @biochem-fan ! I really have no idea how to make a defected file for Relion even I have read the description. If you are able to help me out here I am so much appreciated! 

David

**Comment by biochem-fan** [comment]
Did you try the gain reference from the camera?

> I really have no idea how to make a defected file for Relion even I have read the description.

1. Convert an EER file to an MRC or TIFF by summing all frames **without** alignment.
  (`relion_convert_to_tiff` with `--eer_grouping` set to the total number of frames)
2. Open it in some image viewer (relion_display, 3dmod or whatever)
3. Find the coordinates of the defective lines
4. Make the defect file. As the help message says, each line should contain `x y w h`.
   For example, if there is a vertical line at X=100, this becomes `100 0 1 4096`, i.e., starting from 
   X=100, Y = 0, width = 1 px, height = 4096 px. (coordinates count from 0)

If you still need my help, I need the original EER file, not the motion corrected one, to find the raw coordinates of the lines before alignment.

**Comment by CFDavidHou** [comment]
Thank you @biochem-fan !

Just found out that our scope software generate a .gain file for EER.
![image](https://user-images.githubusercontent.com/71337645/110047818-8cd11100-7d1c-11eb-929a-3d5619320c55.png)
I input this reference to Relion on Gain-reference image that fix the defect lines.
![image](https://user-images.githubusercontent.com/71337645/110048659-441a5780-7d1e-11eb-994e-4c696e4be8c2.png)

**Comment by biochem-fan** [comment]
No correction algorithms can "recover" lost information; at most they "conceal" the defects. There remain some systematic bias on defects and we can sometimes see it.
