### ISSUE TITLE
Memory limit for Particle Subtraction?

### ISSUE THREAD

**Issue by rui--zhang** [3dem/relion#743]
Hi,

I need to do particle signal subtraction for a big particle stack (~590GB), but I only have 512 GB memory.

As a result, the Relion job will fail and freeze the GPU workstation when all the memory and swap are taken.

I wonder is there a work-around or I have to break my particle list into 2 parts?

Thanks!

Rui

**Comment by biochem-fan** [comment]
Reboxing in a subtract job consumes a huge amount of RAM. This is actually a GLIBC, not RELION, issue. A workaround is described in #673.

**Comment by rui--zhang** [comment]
Thank you for your fast response as always! :)

**Comment by rui--zhang** [comment]
This may be a silly question, but how can I set GLIBC_TUNABLES=glibc.malloc.mmap_threshold=1048576 ?

**Comment by biochem-fan** [comment]
It is just an environmental variable. Use `export` (bash) or `setenv` (csh).

(Note: this might affect other programs; do this only in the job script for your Subtract job)

**Comment by rui--zhang** [comment]
Thanks for the tips! It works now!
The memory consumption is kept under 340 GB.
