### ISSUE TITLE
relion_particle_symmetry_expand core dumped

### ISSUE THREAD

**Issue by GuShaocheng** [3dem/relion#744]
Hi,
I would like to report an error.
when running relion_particle_symmetry_expand with a star file containing an unknown label, it warns me, "will ignore (but maintain) values for the unknown label". However, it fails to output the completed star file and there is a XXX.star.tmp which only contains data_optics and terminals shows "Segmentation fault (core dumped)".
Is it possible to keep the unknown column and output a full file? 
Thank you!

**Comment by biochem-fan** [comment]
Are you using the latest version (3.1.2)? Can you confirm that it works fine if you delete the columns with unknown labels?

If both are true, I will investigate. Please share your STAR file and the full command line. Please make the STAR file tiny by truncating it after several particles. I don't need images.

If you are in hurry, you can temporarily rename the unknown labels into something RELION knows.

**Comment by GuShaocheng** [comment]
> Are you using the latest version (3.1.2)? Can you confirm that it works fine if you delete the columns with unknown labels?
> 
> If both are true, I will investigate. Please share your STAR file and the full command line. Please make the STAR file tiny by truncating it after several particles. I don't need images.
> 
> If you are in hurry, you can temporarily rename the unknown labels into something RELION knows.

Thanks for your prompt reply.
I confirm that it works fine if I delete the column with unknown labels. But I run with Relion 3.1.1. I will give you more information after I test it on the Relion 3.1.2.

**Comment by GuShaocheng** [comment]
> Are you using the latest version (3.1.2)? Can you confirm that it works fine if you delete the columns with unknown labels?
> 
> If both are true, I will investigate. Please share your STAR file and the full command line. Please make the STAR file tiny by truncating it after several particles. I don't need images.
> 
> If you are in hurry, you can temporarily rename the unknown labels into something RELION knows.

Hi,
I am glad to reply to you that it works fine using Relion 3.1.2. This problem should be solved in this new version. 
Many thanks!
