### ISSUE TITLE
errors when run relion_prepare_subtomograms.py

### ISSUE THREAD

**Issue by yuanhaowang1213** [3dem/relion#748]
I was following the procedure exactly on the 2016 nature protocol paper, and got error on the procedure 9. Here is the output:

 WARNING: skipping, since cannot get CTF values for ./Tomograms/tomogram1/ctffind/tomogram1_image59.44_0.mrc

I fixed this by change to ctffind3. The python file read it support ctffind4, but which version? 
But got other issues,

1. Traceback (most recent call last):
  File "relion_prepare_subtomograms.py", line 448, in <module>
    micnames, avgdefoci, defocusv = read_relion_star(outputstarname_read)
  File "relion_prepare_subtomograms.py", line 137, in read_relion_star
    micnames.append(fields[imgnamecolumn])
UnboundLocalError: local variable 'imgnamecolumn' referenced before assignment

I checked the file ./Tomograms/tomogram1/ctffind/results/micrographs_ctf.star
It only gave 
"# RELION; version 3.0.8# RELION; version 3.0.8

data_

loop_ 
_rlnMicrographName #1 
_rlnCtfImage #2 
_rlnDefocusU #3 
_rlnDefocusV #4 
_rlnCtfAstigmatism #5 
_rlnDefocusAngle #6 
_rlnVoltage #7 
_rlnSphericalAberration #8 
_rlnAmplitudeContrast #9 
_rlnMagnification #10 
_rlnDetectorPixelSize #11 
_rlnCtfFigureOfMerit #12 
./Tomograms/test1/ctffind/test1_image59.44_0.mrc /home/wangy0k/Desktop/recomcomp/warped3_frommylab/nowarp/reliontest/./Tomograms/test1/ctffind/results/./Tomograms/test1/ctffind/test1_image59.44_0.ctf:mrc 32975.910156 38577.839844  5601.929688    77.410004   300.000000     2.700000     0.070000 10000.000000     1.000000     0.104640 
...

2. What should be set for SkipCTFCorrection and Relion2 in the relion_prepare_subtomograms.py?

The default setting is  Relion2 = True, SkipCTFCorrection = False, but there will be no ctffind.star generated.

**Environment:**
 - OS:  Ubuntu 18.04 LTS
 - MPI runtime: OpenMPI 4.5
 - RELION version RELION-3.0.8
 - Memory: 256
 - GPU:  RTX Titan

**Dataset:** EMPIAR 10045

**Comment by biochem-fan** [comment]
Unfortunately this protocol no longer works in the latest version of RELION. RELION 4.0, which we hope to start public beta testing in a few months, will implement a much better tomography pipeline.

Meanwhile, if you really need to reproduce the paper's work, please use the old version of RELION.
