### ISSUE TITLE
Relion_refine got mpi error

### ISSUE THREAD

**Issue by yuanhaowang1213** [3dem/relion#749]
After doing ctf correction and particle extraction, I tried with relion_refine (not relion_refine_mpi:

relion_refine --o Refine3D/job005/run --auto_refine --split_random_halves --i particles_subtomo.star --ref riboReScale200.mrc --firstiter_cc --ini_high 60 --dont_combine_weights_via_disc --pool 3 --ctf --particle_diameter 200 --flatten_solvent --zero_mask --oversampling 1 --healpix_order 2 --auto_local_healpix_order 4 --offset_range 5 --offset_step 2 --sym C1 --low_resol_join_halves 40 --norm --scale  --j 64

, but got this error:

in: /home/****/Downloads/software/relion/src/ml_optimiser.cpp, line 2417
Backtrace  
relion_refine(_ZN11RelionErrorC2ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES7_l+0x77) [0x562c0c446757]
relion_refine(_ZN11MlOptimiser7iterateEv+0x6cb) [0x562c0c4a318b]
relion_refine(main+0x51) [0x562c0c434de1]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xe7) [0x150e0ddffbf7]
relion_refine(_start+0x2a) [0x562c0c43740a]

ERROR: 
ERROR: Cannot split data into random halves without using MPI!

So my question is that whether I could remove --split_random_halves, will this cause artifects or? I only have a workstation with two xeon processor, so probably I cannot use mpi here or the mpi board number is 1 for me.

**Environment:**
 - OS: Ubuntu 18.04 LTS
 - MPI runtime: OpenMPI 4.0
 - RELION version RELION-2.1
 - Memory: 256 GB
 - GPU: RTX Titan
 

**Dataset:** EMPIAR 10045

**Comment by biochem-fan** [comment]
Refine3D need two half sets for FSC calculation. Thus you MUST use MPI.
