### ISSUE TITLE
subset selection issue

### ISSUE THREAD

**Issue by jhansen6** [3dem/relion#751]
image is easier here.  Sorry for not following format.  Trying to select particles based on a defocus cutoff.   Everything is running in relion 3.1.   Initially I got the error that the metadata table does not contain the label rlnDefocusU.   Okay, so as with many Relion 3.1-specific issues I simply removed the optics table and tried again.  This time I got the error below.  Baffled.   Thanks in advance. 

![image](https://user-images.githubusercontent.com/22459413/111180429-46748100-856a-11eb-85cc-d16e0e5b83bd.png)

**Comment by biochem-fan** [comment]
You shouldn't include `_`. Just say `rlnDefocusU`. You don't have to remove the optics group table.
