### ISSUE TITLE
Failure to link TBB

### ISSUE THREAD

**Issue by biochem-fan** [3dem/relion#753]
Reported in CCPEM.
https://www.jiscmail.ac.uk/cgi-bin/wa-jisc.exe?A2=ind2103&L=CCPEM&O=D&P=67262

```
[ 8%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/healpix_sampling.cpp.o
 /home/heumannj/BUILDS/relion/src/ml_optimiser.cpp:55:33: fatal error: tbb/global_control.h: No such file or directory
 #include <tbb/global_control.h>
```

d0581b4 by @CharlesCongdon is the cause.

CMake: 2.8.12.2

Waiting for more information on:

- GCC version
- MPI runtime versino
- full cmake command and outputs from cmake and make

**Comment by jmheumann** [comment]
As of 16-March-2021, I get the same error when trying to build an AVX version on RHEL7 with commit d0581b4 and later. The gpu version builds with no problem. Gcc is vesion 4.8.5 and openMPI version is 1.10.7. The cmake command I'm running is:

rm CMakeCache.txt
cmake -DCMAKE_INSTALL_PREFIX=/usr/local/relion3.1AVX \
      -DALTCPU=ON -DFORCE_OWN_FLTK=ON -DFORCE_OWN_FFTW=OFF \
      -DCMAKE_BUILD_TYPE=Release ..

At Takanori's request, I'm attaching the output from running cmake and make.

Regards,
-jh-

[cmakeOutput.txt](https://github.com/3dem/relion/files/6150413/cmakeOutput.txt)
[makeOutput.txt](https://github.com/3dem/relion/files/6150416/makeOutput.txt)

**Comment by biochem-fan** [comment]
Thank you very much for details.

Can you try 4be19e1? What if you add `-DFORCE_OWN_TBB=ON`?

**Comment by biochem-fan** [comment]
`-DFORCE_OWN_TBB=ON` solved the issue.
