### ISSUE TITLE
Little detail: code duplication in pipliner.cpp

### ISSUE THREAD

**Issue by cdienem** [3dem/relion#754]
While checking the procedures for gentle cleaning in pipeliner.cpp, I came across a small code duplication in https://github.com/3dem/relion/blob/44d57634c042d240c9449227ca3bc5e3481d8b14/src/pipeliner.cpp#L1603. Seems like it tries to mark "*_aberr_Axx_optics-group_*.mrc" files twice for deletion.

**Comment by biochem-fan** [comment]
Thanks for reporting this. I fixed it.
