### ISSUE TITLE
Autopicking template greyscale uncorrected lead to bad results

### ISSUE THREAD

**Issue by Maoqiyu1** [3dem/relion#757]
**Describe your problem**

Dear all,
I was doing templated auto-picking using a map downloaded from PDB. I use relion_project --i xxx.mrc --o xxx_2d5 --nr_uniform 5 to generate 5 2d projections : xxx_2d5.mrcs , xxx_2d5.star . I lowpassed the map to 20A before reprojection.

Then I put xxx_2d5.mrcs into Auto-picking 's 2D reference column as a 2D-template.
The output result is that on average zero particles is picked from my micrographs. I think it result from unnormalized .mrc map from PDB and subsequently incorrect greyscale in my picking template. Is there a way to normalize the map or to correct the greyscale ? 
[https://github.com/Maoqiyu1/images/blob/2ccba9aba645bfafcf5608555654a14e97fd95ae/QQ%E6%88%AA%E5%9B%BE20210328170126.png](url)
[https://github.com/Maoqiyu1/images/blob/2ccba9aba645bfafcf5608555654a14e97fd95ae/QQ%E6%88%AA%E5%9B%BE20210328170207.png](url)
[https://github.com/Maoqiyu1/images/blob/2ccba9aba645bfafcf5608555654a14e97fd95ae/QQ%E6%88%AA%E5%9B%BE20210328170348.png](url)

I have checked that I corrected the pixel size(==2.088) and box size(216*216) of my map and I have input the relavant parameters correctly (Pixel size in reference = 2.088)

I also used another  .mrc map that I calculated previously using Relion. I lowpassed and reprojected it , and it turns out right , on average 200 particles are picked from each micrograph. 

I would be grateful for any ideas/hints about how to solve this issue of incorrect grayscale

**DO NOT** cross post a same question to multiple issues and/or many mailing lists (CCPEM, 3DEM, etc).

**Environment:**
 - OS: [3.10.0-957.el7.x86_64]
 - MPI runtime: [openmpi/4.0.2_cuda10.1]
 - RELION version [RELION-3.0.8] 
 - Memory: [251 GB]
 - GPU: [GeForce RTX 2080]

**Dataset:**
 - Box size: [216 px]
 - Pixel size: [2.088 Å/px]
 
 - Description: [A protein of about 500 kDa in total]

**Job options:**
 - Type of job: [Autopicking]
 - Number of MPI processes: [4]
 - Number of threads: [1]
 - Full command :
   ```
   `which relion_autopick_mpi` --i Select/job006/micrographs_split002.star --odir AutoPick/job075/ --pickname autopick --ref Models/TCRI_CSN/lp50_TCR_CSN_2d5.mrcs --invert  --ctf  --ang 5 --shrink 1 --angpix_ref 2.088 --threshold 0.1 --min_distance 150 --max_stddev_noise 1.1
echo Select/job006/micrographs_split002.star > AutoPick/job075/coords_suffix_autopick.star



```

**Comment by biochem-fan** [comment]
No. This is current limitation.

In general, I recommend to make a picking reference from the dataset itself to avoid bias.
