### ISSUE TITLE
Install on Ubuntu 20.04 broken

### ISSUE THREAD

**Issue by rshek351** [3dem/relion#758]
No longer able to install Relion.  Last weekend, I was able to install Relion on an AWS instane. This weekend, unable to reproduce the installation. On a fresh Ubuntu 20.04 AWS g.4.xlarge instance, I ran sudo apt install nvidia-driver-460 nvidia-utils-460 build-essential nvidia-cuda-toolkit git cmake mpi-default-bin mpi-default-dev libtiff-dev libxft-dev libfftw3-dev. Then git clone and made build directory etc...cmake -DDoubleprec_GPU=ON -DCUDA_ARCH=52 -DCMAKE_INSTALL_PREFIX=/opt/relion -j 16 ..Think there's may have been an update to nvidia-cuda-toolkit or something in build-essential that causes this error

Please write a clear description of what the problem is.
Running Make Install fails
```
-- BUILD TYPE set to the default type:  'Release'
-- Using provided CUDA_ARCH=52
-- ALLOW_CTF_IN_SAGD enabled - This build of RELION allows modulation of particle images by a contrast transfer function inside stochastic average gradient descent, as specified in Claim 1 of patent US10,282,513B2
-- CUDA enabled - Building CUDA-accelerated version of RELION
-- Setting cpu precision to double
-- Setting accelerated code precision to single
-- Using cuda wrapper to compile....
-- Cuda version is >= 7.5 and single-precision build, enable double usage warning.
-- MPI_INCLUDE_PATH : /usr/lib/x86_64-linux-gnu/openmpi/include/openmpi;/usr/lib/x86_64-linux-gnu/openmpi/include
-- MPI_LIBRARIES : /usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi_cxx.so;/usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi.so
-- MPI_CXX_INCLUDE_PATH : /usr/lib/x86_64-linux-gnu/openmpi/include/openmpi;/usr/lib/x86_64-linux-gnu/openmpi/include
-- MPI_CXX_LIBRARIES : /usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi_cxx.so;/usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi.so
-- CMAKE_C_COMPILER : /usr/bin/cc
-- CMAKE_CXX_COMPILER : /usr/bin/c++
-- MPI_C_COMPILER : /usr/bin/mpicc
-- MPI_CXX_COMPILER : /usr/bin/mpicxx
-- CMAKE_CXX_COMPILER_ID : GNU
-- CMAKE_C_COMPILER : /usr/bin/mpicc
-- CMAKE_CXX_COMPILER : /usr/bin/mpicxx
-- MPI_C_COMPILER : /usr/bin/mpicc
-- MPI_CXX_COMPILER : /usr/bin/mpicxx
-- Could NOT find FLTK (missing: FLTK_LIBRARIES FLTK_FLUID_EXECUTABLE) 
-- No FLTK installation was found
-- Found previously built non-system FLTK libraries that will be used.
-- FLTK_INCLUDE_DIR: /home/roger/relion/external/fltk/include
-- FLTK_LIBRARIES:   /home/roger/relion/external/fltk/lib/libfltk.so
-- Found FFTW
-- FFTW_PATH: /usr/include
-- FFTW_INCLUDES: /usr/include
-- FFTW_LIBRARIES: /usr/lib/x86_64-linux-gnu/libfftw3f.so;/usr/lib/x86_64-linux-gnu/libfftw3.so
BUILD_SHARED_LIBS = OFF
-- Building static libs (larger build size and binaries)
Running apps/CMakeLists.txt...
-- CMAKE_BINARY_DIR:/home/roger/relion/build
-- Git commit ID: 44d57634c042d240c9449227ca3bc5e3481d8b14
-- Found OpenMP_C: -fopenmp  
-- Found OpenMP_CXX: -fopenmp  
-- Found OpenMP: TRUE   
-- Configuring done
-- Generating done
-- Build files have been written to: /home/roger/relion/build
[  1%] Built target copy_scripts
[  1%] Building NVCC (Device) object src/apps/CMakeFiles/relion_gpu_util.dir/__/acc/cuda/relion_gpu_util_generated_cuda_projector_plan.cu.o
/usr/include/c++/9/bits/stl_function.h(437): error: identifier "__builtin_is_constant_evaluated" is undefined

1 error detected in the compilation of "/tmp/tmpxft_0000184e_00000000-6_cuda_projector_plan.cpp1.ii".
CMake Error at relion_gpu_util_generated_cuda_projector_plan.cu.o.Release.cmake:280 (message):
  Error generating file
  /home/roger/relion/build/src/apps/CMakeFiles/relion_gpu_util.dir/__/acc/cuda/./relion_gpu_util_generated_cuda_projector_plan.cu.o


make[2]: *** [src/apps/CMakeFiles/relion_gpu_util.dir/build.make:673: src/apps/CMakeFiles/relion_gpu_util.dir/__/acc/cuda/relion_gpu_util_generated_cuda_projector_plan.cu.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:675: src/apps/CMakeFiles/relion_gpu_util.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```

**Comment by biochem-fan** [comment]
What is the version of CUDA Toolkit and GCC?

(Not relevant for your error but why do you use `-DDoubleprec_GPU=ON`? This makes calculation very slow.)

**Comment by rshek351** [comment]
nvidia-cuda-toolkit is currently 11.2, GCC is ver. 8.4. I did try installing nvidia-cuda-toolkit-gcc which also didnt work

**Comment by rshek351** [comment]
right the make command didnt use the option when i included it last week. Wasn't sure if the Tesla gpus would benefit or not.

**Comment by biochem-fan** [comment]
I think your compiler environment is in a messy state.

> /usr/include/c++/9/bits/stl_function.h

You are using version 9 of C++ headers, not 8.4. If `gcc --version` says 8.4, your compiler binary and the include files are inconsistent.

Double precision performance is better in Tesla cards than GeForce cards but still much slower than single precision. Don't use it.

**Comment by rshek351** [comment]
you're right its gcc version 9.  Now i'm getting 

`  6%] Building NVCC (Device) object src/apps/CMakeFiles/relion_gpu_util.dir/__/acc/cuda/relion_gpu_util_generated_cuda_projector_plan.cu.o
In file included from /usr/include/cuda_runtime.h:83,
                 from <command-line>:
/usr/include/crt/host_config.h:138:2: error: #error -- unsupported GNU version! gcc versions later than 8 are not supported!
  138 | #error -- unsupported GNU version! gcc versions later than 8 are not supported!
      |  ^~~~~
CMake Error at relion_gpu_util_generated_cuda_projector_plan.cu.o.Release.cmake:220 (message):
  Error generating
  /home/ubuntu/relion/build/src/apps/CMakeFiles/relion_gpu_util.dir/__/acc/cuda/./relion_gpu_util_generated_cuda_projector_plan.cu.o


make[2]: *** [src/apps/CMakeFiles/relion_gpu_util.dir/build.make:114: src/apps/CMakeFiles/relion_gpu_util.dir/__/acc/cuda/relion_gpu_util_generated_cuda_projector_plan.cu.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:819: src/apps/CMakeFiles/relion_gpu_util.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
`

**Comment by rshek351** [comment]
okay, i was able to install it after following instructions here [https://linuxconfig.org/how-to-switch-between-multiple-gcc-and-g-compiler-versions-on-ubuntu-20-04-lts-focal-fossa](url). I just find this very strange since last weekend I didnt encounter any errors...
