### ISSUE TITLE
CTF estimation Did not find any of the expected EPS files to generate a PDF file

### ISSUE THREAD

**Issue by SoleMaple** [3dem/relion#760]
WARNING: skipping, since cannot get CTF values for MotionCorr/job002/Movies/20170629_00021_frameImage.mrc
 WARNING: skipping, since cannot get CTF values for MotionCorr/job002/Movies/20170629_00022_frameImage.mrc
 WARNING: skipping, since cannot get CTF values for MotionCorr/job002/Movies/20170629_00023_frameImage.mrc
 WARNING: skipping, since cannot get CTF values for MotionCorr/job002/Movies/20170629_00024_frameImage.mrc
 WARNING: skipping, since cannot get CTF values for MotionCorr/job002/Movies/20170629_00025_frameImage.mrc
 WARNING: skipping, since cannot get CTF values for MotionCorr/job002/Movies/20170629_00026_frameImage.mrc
 WARNING: skipping, since cannot get CTF values for MotionCorr/job002/Movies/20170629_00027_frameImage.mrc
 WARNING: skipping, since cannot get CTF values for MotionCorr/job002/Movies/20170629_00028_frameImage.mrc
 WARNING: skipping, since cannot get CTF values for MotionCorr/job002/Movies/20170629_00029_frameImage.mrc
 WARNING: skipping, since cannot get CTF values for MotionCorr/job002/Movies/20170629_00030_frameImage.mrc
 WARNING: skipping, since cannot get CTF values for MotionCorr/job002/Movies/20170629_00031_frameImage.mrc
 WARNING: skipping, since cannot get CTF values for MotionCorr/job002/Movies/20170629_00035_frameImage.mrc
 WARNING: skipping, since cannot get CTF values for MotionCorr/job002/Movies/20170629_00036_frameImage.mrc
 WARNING: skipping, since cannot get CTF values for MotionCorr/job002/Movies/20170629_00037_frameImage.mrc
 WARNING: skipping, since cannot get CTF values for MotionCorr/job002/Movies/20170629_00039_frameImage.mrc
 WARNING: skipping, since cannot get CTF values for MotionCorr/job002/Movies/20170629_00040_frameImage.mrc
 WARNING: skipping, since cannot get CTF values for MotionCorr/job002/Movies/20170629_00042_frameImage.mrc
 WARNING: skipping, since cannot get CTF values for MotionCorr/job002/Movies/20170629_00043_frameImage.mrc
 WARNING: skipping, since cannot get CTF values for MotionCorr/job002/Movies/20170629_00044_frameImage.mrc
 WARNING: skipping, since cannot get CTF values for MotionCorr/job002/Movies/20170629_00045_frameImage.mrc
 WARNING: skipping, since cannot get CTF values for MotionCorr/job002/Movies/20170629_00046_frameImage.mrc
 WARNING: skipping, since cannot get CTF values for MotionCorr/job002/Movies/20170629_00047_frameImage.mrc
 WARNING: skipping, since cannot get CTF values for MotionCorr/job002/Movies/20170629_00048_frameImage.mrc
 WARNING: skipping, since cannot get CTF values for MotionCorr/job002/Movies/20170629_00049_frameImage.mrc
 Did not find any of the expected EPS files to generate a PDF file
 + Will make an empty PDF-file in CtfFind/job008/logfile.pdf

**Comment by biochem-fan** [comment]
Is CTFFIND installed and properly specified from the GUI?

**Comment by SoleMaple** [comment]
Yes, I installed and specified the correct path, I have a GPU and tried GCTF, but it still failed

**Comment by biochem-fan** [comment]
Where are you running this? Isn't the project directory on a file system that does not support symbolic links (e.g. an external HDD formatted in FAT32)?

**Comment by SoleMaple** [comment]
I am running on Ubuntu18.04.
gpu:1080ti×2
cuda：cuda8.0
File system type is fuse

**Comment by SoleMaple** [comment]
I can run import and motion correction smoothly with the official tutorial dataset.But CTF estimation always fails

**Comment by biochem-fan** [comment]
> File system type is fuse

FUSE is **not** a file system. It is a library to mount file system on user-space.

I guess you mounted an NTFS drive with FUSE (ntfs-3g). This does not work, since it does not support symbolic links (there might be a workaround https://serverfault.com/questions/165389/create-ntfs-symbolic-links-from-within-linux).

**Comment by SoleMaple** [comment]
hi，I don’t have a mounted hard drive and my data in the home directory

**Comment by biochem-fan** [comment]
Why is your home directory mounted by FUSE? Tell me your real file system.
