### ISSUE TITLE
FSC dipped below 0.5 and rose again

### ISSUE THREAD

**Issue by yuanhaowang1213** [3dem/relion#761]
I ran relion_refine_mpi, and got this warning:

WARNING: FSC dipped below 0.5 and rose again. Using 
[logfile.pdf](https://github.com/3dem/relion/files/6245909/logfile.pdf)
higher resolution of 20.7907 A, instead of 29.1069 A.

However, I did not specify the mask. The command line goes like:
mpirun -np 3 `which relion_refine_mpi` --o Refine3D/run --auto_refine --split_random_halves --i particles_subtomo.star --particle_diameter 400 --angpix 2.17 --ini_high 60 --ctf --flatten_solvent --zero_mask --oversampling 1 --healpix_order 1 --auto_local_healpix_order 3 --offset_range 8 --offset_step 4 --sym C1 --low_resol_join_halves 40 --norm --scale  --j 6 --gpu

The particle is 200. And Ini high tried with 10 30 90. all the same output.

After running relion_postprocessing, the fsc curve goes like this:

![torelion](https://user-images.githubusercontent.com/20970968/113341912-77103500-9336-11eb-9c00-6f9404c8210d.PNG)

Is it normal the resolution is 9.5?

**Environment:**
 - OS: ubuntu 18.04
 - MPI runtime: Openmpi 4.0
 - RELION version  RELION-3.0.8
 - Memory: 256GB
 - GPU: RTX TITAN

**Dataset:**
 - Box size: [e.g. 256 px]
 - Pixel size: [e.g. 0.9 Å/px]
 - Number of particles: [e.g. 150,000]
 - Description: [e.g. A tetrameric protein of about 400 kDa in total]

**Comment by biochem-fan** [comment]
This is not a software bug. Data processing question should be posted in the CCPEM mailing list.

Your CTF parameters are very wrong. Probably you made a mistake in Cs or pixel size. Or you have a huge beam tilt. https://www3.mrc-lmb.cam.ac.uk/relion/index.php/FAQs#The_FSC_curve_shows_oscillations_and.2For_bumps

> RELION-3.0.8

This is no longer supported. Please use the latest version (RELION 3.1.2).
