### ISSUE TITLE
Masking with noise out of memory for GPU but not CPU

### ISSUE THREAD

**Issue by davidmbelnap** [3dem/relion#766]
This is a template for reporting bugs. Please fill in as much information as you can.

I am running a 2D classification job with 628477 particles, 50 classes, T=1, 25 iterations, particles 402 pixel boxes, 200 angs. mask, 1.093 angs/pixel.

If I mask with zeros, the job runs fine on my GPUs, but after I selected "no" for "mask individual particles with zeros?" the program crashes at the beginning of the first expectation iteration with an "out of memory" error.  This occurs regardless if I use the following MPI:thread ratios:  4:1, 2:2, 1:4, and 1:1.  The program is running fine (but slower) on my CPUs.

**Environment:**
 - OS: CentOS 7
 - MPI runtime: IMPI
 - RELION version 3.1.1
 - Memory: 384 GB
 - GPU: RTX 2080 Ti

**Dataset:**
 - Box size: 402 px
 - Pixel size: 1.093 Å/px
 - Number of particles: 628477
 - Description: A small tetrameric protein complex < 500 kDa

**Job options:**
 - Type of job: Class2D
 - Number of MPI processes: 4
 - Number of threads: 1
 - Full command (see `note.txt` in the job directory):
`which relion_refine` --o Class2D/job058/run --i Extract/job054/particles.star --dont_combine_weights_via_disc --pool 3 --pad 
2  --ctf  --ctf_intact_first_peak  --iter 25 --tau2_fudge 1 --particle_diameter 200 --K 50 --flatten_solvent  --oversampling 1
 --psi_step 12 --offset_range 5 --offset_step 2 --allow_coarser_sampling --norm --scale  --j 1 --gpu ""  --pipeline_control Cl
ass2D/job058/

**Error message:**
FROM RUN.ERR FILE:
in: /uufs/chpc.utah.edu/sys/srcdir/relion/3.1.1/src/acc/cuda/cuda_settings.h, line 81
ERROR: 

A GPU-function failed to execute.

 If this occured at the start of a run, you might have GPUs which
are incompatible with either the data or your installation of relion.
If you . . .

FROM RUN.OUT FILE:
Expectation iteration 1 of 25
000/??? sec ~~(,_,">                                                          [oo]KERNEL_ERROR: out of memory in /uufs/chpc.ut
ah.edu/sys/srcdir/relion/3.1.1/src/acc/utilities_impl.h at line 253 (error-code 2)

 RELION version: 3.1.1
 exiting with an error ...

**Comment by biochem-fan** [comment]
This is caused not by a bug but by your dataset characteristics.

"Mask by non zero" means broader posterior distributions for angles, translations and classes. Thus the program has to consider more possibilities, requiring more RAM and time.

There is no point using this option at early Class2D. This option can be useful in final Refine3D, after you removed junks, classified heterogeneity and applied all tweaks (Polish, CtfRefine).

P.S. I also recommend you to down-sample particles a lot for Class2D to save space and time.
