### ISSUE TITLE
3d refinement of shiny.star 

### ISSUE THREAD

**Issue by kmanikandan123** [3dem/relion#769]
The 3d refinement of shiny.star fails with the following error message.
----------------------------------------------------------
 Auto-refine: Resolution= 7.88571 (no gain for 2 iter) 
 Auto-refine: Changes in angles= 10.1864 degrees; and in offsets= 1.59291 Angstroms (no gain for 2 iter) 
 Estimating accuracies in the orientational assignment ... 
   4/   4 sec ............................................................~~(,_,">
 Auto-refine: Estimated accuracy angles= 1.938 degrees; offsets= 1.4559 Angstroms
 Auto-refine: Angular step= 3.75 degrees; local searches= false
 Auto-refine: Offset search range= 7.96457 Angstroms; offset step= 1.09192 Angstroms
 CurrentResolution= 7.88571 Angstroms, which requires orientationSampling of at least 2.43243 degrees for a particle of diameter 370 Angstroms
 Oversampling= 0 NrHiddenVariableSamplingPoints= 1658880
 OrientationalSampling= 7.5 NrOrientations= 36864
 TranslationalSampling= 2.18385 NrTranslations= 45
=============================
 Oversampling= 1 NrHiddenVariableSamplingPoints= 53084160
 OrientationalSampling= 3.75 NrOrientations= 294912
 TranslationalSampling= 1.09192 NrTranslations= 180
=============================
 Expectation iteration 9
000/??? sec ~~(,_,">                                                          [oo]ERROR: CudaCustomAllocator out of memory
 [requestedSpace:             803059200 B]
 [largestContinuousFreeSpace: 67155456 B]
 [totalFreeSpace:             67337728 B]
(518656B) (521728B) (518656B) (521728B) (518656B) (521728B) (188416B) (2560B) (94208B) (188416B) (2560B) (94208B) (188416B) (2560B) (94208B) (188416B) (2560B) (94208B) [182272B] (518656B) (521728B) (518656B) (521728B) (176048640B) (352097280B) (352097280B) (352097280B) (352097280B) (704194560B) (8802816B) (184521728B) (369043456B) (369043456B) (369043456B) (369043456B) (738086400B) (9226240B) (212336640B) (424673280B) (424673280B) (424673280B) (424673280B) (849346560B) (10616832B) (154126336B) (308252160B) (308252160B) (308252160B) (308252160B) (616504320B) (7706624B) (200764928B) (401529856B) (401529856B) (401529856B) (401529856B) [67155456B] = 11368347136B
-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
-------------------------------------------------------

The gpus are having 12GB memory (please see the attached image). 
The dataset details : 
box size = 360 x 360 px
# particles = 360 k
Movies are 30 frames from FIII detector.
Using:
RELION version: 3.1.0-commit-87c294 

Please help to understand the problem.
Thank you.

![maxgpu3_3p14t](https://user-images.githubusercontent.com/82946825/115549120-e8a02b00-a2c5-11eb-8263-772baae4ced5.png)

**Comment by biochem-fan** [comment]
Please run Class2D on shiny.star and remove particles with defects.
