### ISSUE TITLE
Issues to get a proper Autopick-2D classification

### ISSUE THREAD

**Issue by Ulvetanna3** [3dem/relion#770]
Hi,

I'm trying to Autopick (Laplacian) a set of elongated particles that are around 150A long. I manage to get a nice 2D classes in Cryosparc but, since I have preferential orientation, people recommend me to use Relion to redo my dataset analysis.
But I'm really stuck, I have no experience with Relion and I don't manage to get any good autopicking that lead me to a 2D classification (even a preliminar one to re do the picking after), I just get black images in the 2D classification, even when I check the autopick and it doesn't look that bad.

Honestly idk what to put here about the parameters that I'm using because I tried a bunch but blindly (since I have no idea neither experience).

I was hoping someone could give me some suggestions that help me to overcome that point because I'm desperated.

Thanks!

**Comment by biochem-fan** [comment]
Please post data processing questions to CCPEM, not here.
