### ISSUE TITLE
Problem with RELION_JOB_ABORT_NOW high frequency checking

### ISSUE THREAD

**Issue by thiell** [3dem/relion#772]
**Describe your problem**

Hello, I am a HPC sysadmin and we have users running `relion_refine_mpi` and we keep noticing thousands of lookup for a file named RELION_JOB_ABORT_NOW from their jobs. I know it's common to do that in HPC, but with Relion, the frequency of checking this file is crazy. Parallel filesystems are not the best way to communicate between processes for that kind of thing, as it involves negative dentry caching and it's not always available/performant.

If we strace rank #0, we're seeing relion doing this:
```
[pid 23134] stat("Class3D/job020/RELION_JOB_ABORT_NOW", 0x7ffccde437a0) = -1 ENOENT (No such file or directory) <0.000277>
[pid 23134] stat("Class3D/job020/RELION_JOB_ABORT_NOW", 0x7ffccde437a0) = -1 ENOENT (No such file or directory) <0.000383>
[pid 23134] stat("Class3D/job020/RELION_JOB_ABORT_NOW", 0x7ffccde437a0) = -1 ENOENT (No such file or directory) <0.000539>
[pid 23134] stat("Class3D/job020/RELION_JOB_ABORT_NOW", 0x7ffccde437a0) = -1 ENOENT (No such file or directory) <0.000374>
[pid 23134] stat("Class3D/job020/RELION_JOB_ABORT_NOW", 0x7ffccde437a0) = -1 ENOENT (No such file or directory) <0.000281>
[pid 23134] stat("Class3D/job020/RELION_JOB_ABORT_NOW", 0x7ffccde437a0) = -1 ENOENT (No such file or directory) <0.000336>
^Cstrace: Process 23134 detached
strace: Process 23186 detached
```

Basically, in that case, more than 1,000 stat per second:

```
# strace -e stat -fp 23134 |& pv -rl >/dev/null
[1.05k/s]
```

**Environment:**
 - OS: CentOS 7
 - MPI runtime: OpenMPI 2.0.2
 - RELION version 3.1.0
 - Memory: 128GB - 4TB
 - GPU: many

**Dataset:**
- unknown

**Job options:**
 - Type of job: relion_refine_mpi
 - Number of MPI processes: 140
 - Number of threads: ?
 - Full command (see `note.txt` in the job directory):
```
 srun `which relion_refine_mpi` --o Class3D/job020/run --i Refine3D/job019/run_ct6_data.star --ref Refine3D/job019/run_ct6_class001.mrc --firstiter_cc --ini_high 60 --dont_combine_weights_via_disc --pool 3 --pad 2  --skip_gridding  --ctf --iter 100 --tau2_fudge 4 --particle_diameter 156 --K 10 --flatten_solvent --zero_mask --solvent_mask masks_20200814_covid177uncut_20uM_TEM1_130K/job149/mask.mrc --skip_align  --sym C1 --norm --scale  --j 2  --pipeline_control Class3D/job020/
```

**Error message:**

no specific error

**Comment by biochem-fan** [comment]
@scheres please consider reducing the checking frequency.

**Comment by scheres** [comment]
It is not recommended to run relion_refine_mpi with 140 followers... Anyway, the frequency of checking has been decreased and with MPI only the leader will now check, not the followers.
