### ISSUE TITLE
Nvidia A100 support

### ISSUE THREAD

**Issue by imukovvn** [3dem/relion#774]
Hello
I have relion 3.1.2 installation with enabled CUDA support. It works perfectly on AWS instances with NVIDIA T4 Tensor Core GPUs.
But something goes wrong if I'm trying to run it on instances with NVIDIA A100 Tensor Core GPUs, build options are the same as for T4 GPUs:
```
ERROR:

A GPU-function failed to execute.

 If this occured at the start of a run, you might have GPUs which
are incompatible with either the data or your installation of relion.
If you

        -> INSTALLED RELION YOURSELF: if you e.g. specified -DCUDA_ARCH=50
           and are trying ot run on a compute 3.5 GPU (-DCUDA_ARCH=3.5),
           this may happen.

        -> HAVE MULTIPLE GPUS OF DIFFERNT VERSIONS: relion needs GPUS with
           at least compute 3.5. You may be trying to use a GPU older than
           this. If you have multiple generations, try specifying --gpu <X>
           with X=0. Then try X=1 in a new run, and so on. The numbering of
           GPUs may not be obvious from the driver or intuition. For a list
           of GPU compute generations, see

           en.wikipedia.org/wiki/CUDA#Version_features_and_specifications

        -> ARE USING DOUBLE-PRECISION GPU CODE: relion was been written so
           as to not require this, and may thus have unforeseen requirements
           when run in this mode. If you think it is nonetheless necessary,
           please consult the developers with this error.

If this occurred at the middle or end of a run, it might be that

        -> YOUR DATA OR PARAMETERS WERE UNEXPECTED: execution on GPUs is
           subject to many restrictions, and relion is written to work within
           common restraints. If you have exotic data or settings, unexpected
           configurations may occur. See also above point regarding
           double precision.
If none of the above applies, please report the error to the relion
developers at    github.com/3dem/relion/issues
```

I found that A100 GPUs have a different genencode=arch and rebuilt the relion with options as in doc:
https://docs.nvidia.com/cuda/ampere-compatibility-guide/index.html#building-ampere-compatible-apps-using-cuda-11-0

But no luck, still getiing the same error message. 

Just as test I removed all other gencodes except 80, and when I trying to launch relion it says that it was built without GPU support.
I'm not sure this issue relates to relion, but I would be really appreciate for any help.

I'm using
gcc ver 10.2
cuda ver 11.2

**Comment by biochem-fan** [comment]
Did you run `cmake` with `-DCUDA_ARCH=80`? Don't modify any other files.

**Comment by imukovvn** [comment]
> Did you run `cmake` with `-DCUDA_ARCH=80`? Don't modify any other files.

Yes, I tried to set up arch like this. Doesn't work for me.

**Comment by biochem-fan** [comment]
Are you using CUDA 11.0 for both compilation and execution? Did you make sure the binary is linked to CUDA 11.0 by `ldd /path/to/relion_refine`?

**Comment by imukovvn** [comment]
> Are you using CUDA 11.0 for both compilation and execution? Did you make sure the binary is linked to CUDA 11.0 by `ldd /path/to/relion_refine`?

To be more clear, I'm using Easybuild to build the Relion, so all the packages/dependecies are the same
Here is the ldd output:
```
[ec2-user@i-08c3e6202e9f59ff0 ~]$ ldd /usr/prog/software/RELION/3.1.1_EER-fosscuda-2020b/bin/relion_refine | grep -i cuda
        libcufft.so.10 => /usr/prog/software/CUDAcore/11.1.1/lib/libcufft.so.10 (0x00007ff58d111000)
        libmpi.so.40 => /usr/prog/software/OpenMPI/4.0.5-gcccuda-2020b/lib/libmpi.so.40 (0x00007ff59f6fe000)
        libcurand.so.10 => /usr/prog/software/CUDAcore/11.1.1/lib/libcurand.so.10 (0x00007ff587d69000)
        libopen-rte.so.40 => /usr/prog/software/OpenMPI/4.0.5-gcccuda-2020b/lib/libopen-rte.so.40 (0x00007ff586fd3000)
        libopen-pal.so.40 => /usr/prog/software/OpenMPI/4.0.5-gcccuda-2020b/lib/libopen-pal.so.40 (0x00007ff586eea000)
        libcudart.so.11.0 => /usr/prog/software/CUDAcore/11.1.1/lib/libcudart.so.11.0 (0x00007ff586a62000)

```

**Comment by biochem-fan** [comment]
Hmm, I don't know. We don't have A100 at hand, so we cannot investigate. I recommend you to ask in CCPEM, where your message is more visible.

**Comment by imukovvn** [comment]
Just found a reason of such behavior, to initialize A100 GPUs system nvidia-fabric service should be installed and running.
