### ISSUE TITLE
MlOptimiserMpi::initialiseWorkLoad: at least 3 MPI processes are required when splitting data into random halves

### ISSUE THREAD

**Issue by yongshuo-Z** [3dem/relion#777]
**Describe your problem**

When working with 3D auto-refine, error occurs as the title says.  The 3d initial model and 3d classification finished successfully.

I set the MPI process to 3 in GUI, but as can be seen in the error log, the MPI process is still 1. I wonder how can I set it to 3 to make this step work?

I've seen this #470 , but the solution doesn't seem to work for me. 
For more information, I run the command:

`which mpicc`
-->/usr/bin/mpicc

`which mpirun`
--> /usr/bin/mpirun

`mpicc --version`
-->gcc (Ubuntu 8.4.0-1ubuntu1~18.04) 8.4.0

`mpirun --version`
-->mpirun (Open MPI) 2.1.1

**Environment:**
 - OS: Ubuntu 18.04
 - MPI runtime: OpenMPI 2.1.1
 - RELION version: RELION-2.1.b1-devel-commit-6ba935 (also tried  version 3.1.2)
 - Memory: 256 GB
 - GPU: GTX 2080Ti

**Dataset:**

 - Box size: 128 px
 - Pixel size: 1.9 Å/px
 - Number of particles: 40000
 - Description: empiar10017

**Job options:**
 - Type of job: Refine3D
 - Number of MPI processes: 3
 - Number of threads: 3
 - Full command (see `note.txt` in the job directory):
   ```
   `which relion_refine_mpi` --o Refine3D/job019/run --auto_refine --split_random_halves --i CtfRefine/job018/particles_ctf_refine.star --ref PostProcess/job001/postprocess.mrc --firstiter_cc --ini_high 12 --dont_combine_weights_via_disc --scratch_dir /ssd --pool 3 --pad 2  --ctf --ctf_corrected_ref --particle_diameter 142 --flatten_solvent --zero_mask --solvent_mask Result-by-Rado/run_class001_mask_th0.01_ns3_ngs7_box400.mrc --solvent_correct_fsc  --oversampling 1 --healpix_order 3 --auto_local_healpix_order 4 --offset_range 5 --offset_step 2 --sym O --low_resol_join_halves 40 --norm --scale  --j 8 --gpu "" --keep_scratch --pipeline_control Refine3D/job019/
   ```

**Error message:**

Please cite the *full* error message as the example below.

```
 === RELION MPI setup ===
 + Number of MPI processes             = 1
 + Number of threads per MPI process  = 3
 + Total number of threads therefore  = 3
 + Master  (0) runs on host            = xxx
 =================
The following warnings were encountered upon command-line parsing: 
WARNING: Option --allow-run-as-root	is not a valid RELION argument
 Running CPU instructions in double precision. 
ERROR: 
MlOptimiserMpi::initialiseWorkLoad: at least 3 MPI processes are required when splitting data into random halves
File: /root/cryo/code/relion/relion-2.1.b1/src/ml_optimiser_mpi.cpp line: 561
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 0 in communicator MPI_COMM_WORLD
with errorcode 1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
```

**Comment by WeiZhang-12** [comment]
Try this.
mpirun -n x `which relion_refine_mpi` --o Refine3D/job019/run --auto_refine **********

**Comment by KrisJanssen** [comment]
@WeiZhang-12 : can you clarify your suggestion? Users in our organization are hitting the same error as original author here. They use the GUI to create jobs and run them locally. However, it seems relion is not explicitly prepending mpirun -n to the generated command.

**Comment by biochem-fan** [comment]
Please show us your job submission template.

**Comment by WeiZhang-12** [comment]
"
Re3Working=/home/*/*/CryoEM_data/*
cd ${Re3Working}
mkdir ${Re3Working}/Class2D/job006
mpirun -n 5 relion_refine_mpi --o Class2D/job006/run --i Extract/job005/particles.star  --dont_combine_weights_via_disc --pool 3 --pad 2 --ctf --iter 25 --tau2_fudge 2 --particle_diameter 180 --K 15 --flatten_solvent  --zero_mask  --oversampling 1 --psi_step 12 --offset_range 5 --offset_step 2 --norm --scale  --j 5 --gpu ""  --pipeline_control Class2D/job006/

"
This is one template for class2D using the PBS script.
And the following is the run log.

"
process will start at : 
Wed May 18 15:36:43 CST 2022
++++++++++++++++++++++++++++++++++++++++
RELION version: 3.1.3-commit-fa923d 
Precision: BASE=double

 === RELION MPI setup ===
 + Number of MPI processes             = 5
 + Number of threads per MPI process   = 5
 + Total number of threads therefore   = 25
 + Leader  (0) runs on host            = gpu01
 + Follower     1 runs on host            = gpu01
 + Follower     2 runs on host            = gpu01
 + Follower     3 runs on host            = gpu01
 + Follower     4 runs on host            = gpu01
 =================
 Running CPU instructions in double precision. 
 Estimating initial noise spectra 
000/??? sec ~~(,_,">                                                          [oo]
   0/   0 sec ~~(,_,">
   1/  30 sec .~~(,_,">
   1/  20 sec ..~~(,_,">
   1/  15 sec ...~~(,_,">
   1/  12 sec ....~~(,_,">
   1/  10 sec .....~~(,_,">
   1/   8 sec ......~~(,_,">
   1/   7 sec .......~~(,_,">
   1/   6 sec ........~~(,_,">
   1/   6 sec .........~~(,_,">
   1/   5 sec ..........~~(,_,">
   1/   5 sec ...........~~(,_,">
   1/   4 sec ............~~(,_,">
   1/   4 sec .............~~(,_,">
   1/   4 sec ..............~~(,_,">
   2/   7 sec ...............~~(,_,">
   2/   7 sec ................~~(,_,">
   2/   6 sec .................~~(,_,">
   2/   6 sec ..................~~(,_,">
   2/   6 sec ...................~~(,_,">
   2/   5 sec ....................~~(,_,">
   2/   5 sec .....................~~(,_,">
   2/   5 sec ......................~~(,_,">
   2/   5 sec .......................~~(,_,">
   2/   4 sec ........................~~(,_,">
   2/   4 sec .........................~~(,_,">
   2/   4 sec ..........................~~(,_,">
   2/   4 sec ...........................~~(,_,">
   2/   4 sec ............................~~(,_,">
   2/   4 sec .............................~~(,_,">
   2/   3 sec ..............................~~(,_,">
   3/   5 sec ...............................~~(,_,">
   3/   5 sec ................................~~(,_,">
   3/   5 sec .................................~~(,_,">
   3/   5 sec ..................................~~(,_,">
   3/   5 sec ...................................~~(,_,">
   3/   4 sec ....................................~~(,_,">
   3/   4 sec .....................................~~(,_,">
   3/   4 sec ......................................~~(,_,">
   3/   4 sec .......................................~~(,_,">
   3/   4 sec ........................................~~(,_,">
   3/   4 sec .........................................~~(,_,">
   3/   4 sec ..........................................~~(,_,">
   3/   4 sec ...........................................~~(,_,">
   3/   4 sec ............................................~~(,_,">
   3/   3 sec .............................................~~(,_,">
   4/   5 sec ..............................................~~(,_,">
   4/   5 sec ...............................................~~(,_,">
   4/   4 sec ................................................~~(,_,">
   4/   4 sec .................................................~~(,_,">
   4/   4 sec ..................................................~~(,_,">
   4/   4 sec ...................................................~~(,_,">
   4/   4 sec ....................................................~~(,_,">
   4/   4 sec ....................................................~~(,_,">
   4/   4 sec .....................................................~~(,_,">
   4/   4 sec ......................................................~~(,_,">
   4/   4 sec .......................................................~~(,_,">
   4/   4 sec ........................................................~~(,_,">
   4/   4 sec .........................................................~~(,_,">
   4/   4 sec ..........................................................~~(,_,">
   4/   4 sec ...........................................................~~(,_,">
   4/   4 sec ............................................................~~(,_,">
 Estimating accuracies in the orientational assignment ... 
000/??? sec ~~(,_,">                                                          [oo]
   0/   0 sec ~~(,_,">
   0/   0 sec ~~(,_,">
   0/   0 sec .~~(,_,">
   0/   0 sec .~~(,_,">
   0/   0 sec ..~~(,_,">
   0/   0 sec ..~~(,_,">
   0/   0 sec ..~~(,_,">
   0/   0 sec ...~~(,_,">
   0/   0 sec ...~~(,_,">
   0/   0 sec ...~~(,_,">
   0/   0 sec ....~~(,_,">
   0/   0 sec ....~~(,_,">
   0/   0 sec .....~~(,_,">
   0/   0 sec .....~~(,_,">
   0/   0 sec ......~~(,_,">
   0/   0 sec ......~~(,_,">
   0/   0 sec ......~~(,_,">
   0/   0 sec .......~~(,_,">
   0/   0 sec .......~~(,_,">
   0/   0 sec .......~~(,_,">
   0/   0 sec ........~~(,_,">
   0/   0 sec ........~~(,_,">
   0/   0 sec .........~~(,_,">
   0/   0 sec .........~~(,_,">
   0/   0 sec ..........~~(,_,">
   0/   0 sec ..........~~(,_,">
   0/   0 sec ..........~~(,_,">
   0/   0 sec ...........~~(,_,">
   0/   0 sec ...........~~(,_,">
   0/   0 sec ...........~~(,_,">
   0/   0 sec ............~~(,_,">
   0/   0 sec ............~~(,_,">
   0/   0 sec .............~~(,_,">
   0/   0 sec .............~~(,_,">
   0/   0 sec ..............~~(,_,">
   0/   0 sec ..............~~(,_,">
   0/   0 sec ..............~~(,_,">
   0/   0 sec ...............~~(,_,">
   0/   0 sec ...............~~(,_,">
   0/   0 sec ...............~~(,_,">
   0/   0 sec ................~~(,_,">
   0/   0 sec ................~~(,_,">
   0/   0 sec .................~~(,_,">
   0/   0 sec .................~~(,_,">
   0/   0 sec ..................~~(,_,">
   0/   0 sec ..................~~(,_,">
   0/   0 sec ..................~~(,_,">
   0/   0 sec ...................~~(,_,">
   0/   0 sec ...................~~(,_,">
   0/   0 sec ...................~~(,_,">
   0/   0 sec ....................~~(,_,">
   0/   0 sec ....................~~(,_,">
   0/   0 sec .....................~~(,_,">
   0/   0 sec .....................~~(,_,">
   0/   0 sec ......................~~(,_,">
   0/   0 sec ......................~~(,_,">
   0/   0 sec ......................~~(,_,">
   0/   0 sec .......................~~(,_,">
   0/   0 sec .......................~~(,_,">
   0/   0 sec .......................~~(,_,">
   0/   0 sec ........................~~(,_,">
   0/   0 sec ........................~~(,_,">
   0/   0 sec .........................~~(,_,">
   0/   0 sec .........................~~(,_,">
   0/   0 sec ..........................~~(,_,">
   0/   0 sec ..........................~~(,_,">
   0/   0 sec ..........................~~(,_,">
   0/   0 sec ...........................~~(,_,">
   0/   0 sec ...........................~~(,_,">
   0/   0 sec ...........................~~(,_,">
   0/   0 sec ............................~~(,_,">
   0/   0 sec ............................~~(,_,">
   0/   0 sec .............................~~(,_,">
   0/   0 sec .............................~~(,_,">
   0/   0 sec ..............................~~(,_,">
   0/   0 sec ..............................~~(,_,">
   0/   0 sec ..............................~~(,_,">
   0/   0 sec ...............................~~(,_,">
   0/   0 sec ...............................~~(,_,">
   0/   0 sec ...............................~~(,_,">
   0/   0 sec ................................~~(,_,">
   0/   0 sec ................................~~(,_,">
   0/   0 sec .................................~~(,_,">
   0/   0 sec .................................~~(,_,">
   0/   0 sec ..................................~~(,_,">
   0/   0 sec ..................................~~(,_,">
   0/   0 sec ..................................~~(,_,">
   0/   0 sec ...................................~~(,_,">
   0/   0 sec ...................................~~(,_,">
   0/   0 sec ....................................~~(,_,">
   0/   0 sec ....................................~~(,_,">
   0/   0 sec ....................................~~(,_,">
   0/   0 sec .....................................~~(,_,">
   0/   0 sec .....................................~~(,_,">
   0/   0 sec ......................................~~(,_,">
   0/   0 sec ......................................~~(,_,">
   0/   0 sec ......................................~~(,_,">
   0/   0 sec .......................................~~(,_,">
   0/   0 sec .......................................~~(,_,">
   0/   0 sec .......................................~~(,_,">
   0/   0 sec ........................................~~(,_,">
   0/   0 sec ........................................~~(,_,">
   0/   0 sec .........................................~~(,_,">
   0/   0 sec .........................................~~(,_,">
   0/   0 sec ..........................................~~(,_,">
   0/   0 sec ..........................................~~(,_,">
   0/   0 sec ..........................................~~(,_,">
   0/   0 sec ...........................................~~(,_,">
   0/   0 sec ...........................................~~(,_,">
   0/   0 sec ............................................~~(,_,">
   0/   0 sec ............................................~~(,_,">
   0/   0 sec ............................................~~(,_,">
   0/   0 sec .............................................~~(,_,">
   0/   0 sec .............................................~~(,_,">
   0/   0 sec ..............................................~~(,_,">
   0/   0 sec ..............................................~~(,_,">
   0/   0 sec ..............................................~~(,_,">
   0/   0 sec ...............................................~~(,_,">
   0/   0 sec ...............................................~~(,_,">
   0/   0 sec ................................................~~(,_,">
   0/   0 sec ................................................~~(,_,">
   0/   0 sec ................................................~~(,_,">
   0/   0 sec .................................................~~(,_,">
   0/   0 sec .................................................~~(,_,">
   0/   0 sec ..................................................~~(,_,">
   0/   0 sec ..................................................~~(,_,">
   0/   0 sec ..................................................~~(,_,">
   0/   0 sec ...................................................~~(,_,">
   0/   0 sec ...................................................~~(,_,">
   0/   0 sec ....................................................~~(,_,">
   0/   0 sec ....................................................~~(,_,">
   0/   0 sec ....................................................~~(,_,">
   0/   0 sec .....................................................~~(,_,">
   0/   0 sec .....................................................~~(,_,">
   0/   0 sec ......................................................~~(,_,">
   0/   0 sec ......................................................~~(,_,">
   0/   0 sec ......................................................~~(,_,">
   0/   0 sec .......................................................~~(,_,">
   0/   0 sec .......................................................~~(,_,">
   0/   0 sec ........................................................~~(,_,">
   0/   0 sec ........................................................~~(,_,">
   0/   0 sec ........................................................~~(,_,">
   0/   0 sec .........................................................~~(,_,">
   0/   0 sec .........................................................~~(,_,">
   0/   0 sec ..........................................................~~(,_,">
   0/   0 sec ..........................................................~~(,_,">
   0/   0 sec ..........................................................~~(,_,">
   0/   0 sec ...........................................................~~(,_,">
   0/   0 sec ...........................................................~~(,_,">
   0/   0 sec ............................................................~~(,_,">
 Auto-refine: Estimated accuracy angles= 30.1 degrees; offsets= 8.9385 Angstroms
 CurrentResolution= 12.2917 Angstroms, which requires orientationSampling of at least 7.65957 degrees for a particle of diameter 180 Angstroms
 Oversampling= 0 NrHiddenVariableSamplingPoints= 9450
 OrientationalSampling= 12 NrOrientations= 30
 TranslationalSampling= 1.77 NrTranslations= 21
=============================
 Oversampling= 1 NrHiddenVariableSamplingPoints= 302400
 OrientationalSampling= 6 NrOrientations= 240
 TranslationalSampling= 0.885 NrTranslations= 84
=============================
 Expectation iteration 1 of 25
…………
“

**Comment by KrisJanssen** [comment]
Thanks @WeiZhang-12  and @biochem-fan : but I would like to know why relion GUI seems to generate a command line like:

` ``which relion_refine_mpi`` --o Refine3D/job019/run blablabla` whereas it seems to be suggested instead to run things like `**mpirun -n 5** relion_refine_mpi --o Class2D/job006/run`

I.e. why is it necessary to explicitly prepend mpirun -n xx?

**Comment by biochem-fan** [comment]
@KrisJanssen

First of all, are you using `Submit to queue?: Yes`? In this case, as I wrote before,

> Please show us your job submission template.

Otherwise we cannot investigate. Study [our documentation](https://relion.readthedocs.io/en/release-3.1/Installation.html#set-up-queue-job-submission) carefully.

If you are using "Submit to queue?: No", do you run a job from the `Run!` button? In this case, `mpirun` is appended automatically. The "note.txt" in a job folder and the `Check command line` button do not say `mpirun`, but it is actually used.

If you are not using a queue system and not using the `Run!` button, but copy-and-pasting the line from the `Check command line` button, then this is not a recommended way. In this case you have to manually prepend `mpirun`.
