### ISSUE TITLE
Motion correction jobs can't process EER files with MotionCor2, incorrect flags

### ISSUE THREAD

**Issue by mokca** [3dem/relion#778]
One of our group wanted to use MotionCor2 to process .eer movies as a Relion job.  This fails because the command constructed by Relion to run MotionCor2 uses the '-InMrc' flag.  The correct flag is '-InEer'.

I've had a look at the code in motioncorr_runner.cpp and the logic seems to be along the lines of

`If file extension is 'tif' or 'tiff'
    use -InTiff
else
    use -InMrc`

Would it be possible to add -InEer as an option to this code block?  I'm assuming there isn't something bad about MotionCor2 and eer files that I don't know about.

This is with Relion 3.1.2 (commit da0b41c appears to do this).

**Comment by biochem-fan** [comment]
It is not so simple as changing `-InTiFF` to `-InEER`; RELION also has to save EER related metadata to the STAR file for Polish. I myself no longer support UCSF MotionCor2. I hope others can make a patch.

**Comment by mokca** [comment]
We have a GPU-heavy but CPU-light environment so GPU-accelerated motion correction is very useful for large datasets.

Is polishing the only step that needs the EER related metadata?  Could I bodge the patch myself, accepting the fact that data processed this way couldn't be polished?

**Comment by biochem-fan** [comment]
Another possibility is to convert EER movies to TIFF by `relion_convert_to_tiff` beforehand. You won't need/utilize high temporal resolution of EER anyway. This also has the benefit of making the movie files smaller. See https://relion.readthedocs.io/en/latest/Reference/MovieCompression.html#falcon4-eer.
