### ISSUE TITLE
JoinStar, ERROR in appending metadata tables with not the same columns!

### ISSUE THREAD

**Issue by h-ehara** [3dem/relion#779]
JoinStar function sometimes fails saying "ERROR in appending metadata tables with not the same columns!" when you have many different labels.

This is probably because the "Also disable any labels of any of the input tables that do not occur in all input tables" part of MetaDataTable::combineMetaDataTables is not working, as this loop calls deactivateLabel() while looping by activeLabels.

The *easiest* patch I could think of was to add j=0; just after calling deactivateLabel().

```
if (!commonLabels.containsLabel(thisLabel, unknownLabel))
{
	MDin[i].deactivateLabel(thisLabel, unknownLabel);
	j=0; //PATCH
	std::cerr << " + WARNING: ignoring label " << (unknownLabel == "" ? EMDL::label2Str(thisLabel) : unknownLabel) << " in " << i+1 << "th STAR file because it is not present in all STAR files to be combined." << std::endl;
}
```

**Comment by biochem-fan** [comment]
Yes, your analysis is correct. This problem has been already fixed in RELION 4.0, which we will start beta testing (hopefully) soon. This bug will not be fixed in 3.1.
