### ISSUE TITLE
2D classification error

### ISSUE THREAD

**Issue by Citompi** [3dem/relion#781]
Dear EM people,

Recently in the processing of one dataset I encountered a weird issue about 2D classification with relion, which I never had before with my other datasets. The 2D classification can not be launched and gave error before the 1st iteration as follows:

No orientation was found as better than any other.

A particle image was compared to the reference and resulted in all-zero
weights (for all orientations). This should not happen, unless your data
has very special characteristics. This has historically happened for some 
lower-precision calculations, but multiple fallbacks have since been 
implemented. Please report this error to the relion developers at 
	         github.com/3dem/relion/issues

This error only shows for one of my datasets, I have tried different versions of relion, however it did not work, could anyone give some possible inputs? Thank you!

Best wishes!
Wen

**Comment by biochem-fan** [comment]
See the FAQ: https://www3.mrc-lmb.cam.ac.uk/relion/index.php/FAQs#Refinement_or_Classification_crash_saying_.22No_orientation_was_found.22
