### ISSUE TITLE
Issue with Bayesian Polishing

### ISSUE THREAD

**Issue by shawn-egri** [3dem/relion#785]
I am attempting to run a Bayesian Polishing job in polishing mode and experiencing the follow issue:

Job input:
- 200,000 particles originating from approx 3,000 micrographs
- 20 MPI processors, 10 threads

My job ran overnight on Relion, and proceeded through the following steps:
 + Masking references ...
 + Transforming references ...
 + Initializing motion estimator ...
 + Performing loop over micrographs ... 

During the Performing loop step, I received the following message in the terminal roughly halfway through this step of the job:
 "Message from syslogd@spgpu at Jun 30 19:55:12 ... kernel:PANIC: zfs: accessing past end of object 36/11ff11 (size=33280 access=32765+8201)"

What does this error message indicate? The job continued to run and write files in the Relion /Polish/job081/rawTIFF directory after the message, so it appears that the error did not completely disrupt the ability of Relion to run. For each of the input micrographs it wrote five files: a tracks.star, tracks.eps, FCC_cc.mrc, FCC_w0.mrc, and FCC_w1.mrc files. The only issue is that the job did not write a shiny.star output in the Relion directory, which I thought it should have? 

When I check the status of my MPI processors it is showing me that all 20 are still active and being used at 100% CPU, which makes me think that the Relion job has moved on to the next step of the Polish job. My current plan is to let it run for the next few hours and decide what to do from there. Additionally, I can't open a relion window, it gives the error: "WARNING: trying to read pipeline.star, but directory .relion_lock exists (which protects against simultaneous writing by multiple instances of the GUI)."

Any suggestions?

Thanks in advance!
-Shawn

**Comment by biochem-fan** [comment]
This is probably not a RELION issue but a hardware (corrupted disk) or a kernel (ZFS driver bug). Please contact your system administrator.
