### ISSUE TITLE
Symbolic link does not get created

### ISSUE THREAD

**Issue by aseedb** [3dem/relion#787]
I'm following relion 3.1 tutorial. At the import step, the folder Import/job001 is created and it contains the expected files. However the symbolic link "movies" is not created in Import folder. 
I can create it manually though:
```
cd Import
ln -s job001 movies
```

**Environment:**
 - OS: CentOS Linux release 7.9.2009 (Core)
 - MPI runtime: Open MPI 4.0.5
 - RELION: RELION-3.1.2-commit-0e9e83 
 - Memory: 62G
 - GPU: none (running relion on Slurm submit host)

**Dataset:**
relion 3.0 tutorial datset

**Job options:**
 - Type of job: relion_import
 - Number of MPI processes: 0
 - Number of threads: 1
 - Full command :
```relion_import  --do_movies  --optics_group_name "opticsGroup1" --optics_group_mtf ../PrecalculatedResults/mtf_k2_200kV.star --angpix 0.885 --kV 200 --Cs 1.4 --Q0 0.1 --beamtilt_x 0 --beamtilt_y 0 --i "Movies/*.tiff" --odir Import/job001/ --ofile movies.star --continue  --pipeline_control Import/job001/```

**Error message:**

None

**Comment by biochem-fan** [comment]
> I'm following relion 3.1 tutorial. At the import step, the folder Import/job001 is created and it contains the expected files. However the symbolic link "movies" is not created in Import folder.

Do you mean the GUI does not create the link even though you named (aliased) the job as "movies"?

**Comment by aseedb** [comment]
> Do you mean the GUI does not create the link even though you named (aliased) the job as "movies"?

My bad! typical case of did not RTFM. I read the tutorial too quickly and did not see I had to enter something in the "Current" textbox empty. Sorry about that and thanks for your quick help!
