### ISSUE TITLE
Explain error messages from MotioncorrRunner::executeMotioncor2

### ISSUE THREAD

**Issue by tobydarling** [3dem/relion#792]
In trying to help diagnose a failed job, I noticed the .err file had errors of the form `ERROR in renaming: foo.mrc to foo_noDW.mrc`, but no indication why. 

And a few lines above, in the same function, I notice that there's
````
std::cerr << " WARNING: there was an error executing: " << command << std::endl;
return false;
````
Could perror() or similar be added to the error messages? Thanks!

**Comment by biochem-fan** [comment]
Resolved in 0820b89 (4.0 only).

Note that in general we do not actively support/improve the UCSF MotionCor2 wrapper. It is provided as is. Our focus is on our own motion correction routine.
