### ISSUE TITLE
MotionCorr doesn't work, no output or errors

### ISSUE THREAD

**Issue by NuwandaCZ** [3dem/relion#798]
Hello, I've installed relion 3.1 on a new machine. While installing I had to install older cuda (9.1) to make it work, but there didn't seem to be an issue. Now after acquiring data, I've tried to import data (no problem) and it hangs on MotionCorr job, without any outputs or errors. The MotionCorr job is however in the running window. I've also tried downloading motioncorr from UCSF, but the issue is exactly the same.

Is this a known issue? How could I get more information about what's going on?

Thank you for any advice in advance :)

**Comment by biochem-fan** [comment]
You didn't provide enough information for us to investigate. Please respect our issue template.

**Comment by NuwandaCZ** [comment]
I'm sorry @biochem-fan, I absolutely missed this, my bad, here I go:


**Describe your problem**
Here I'd just copy the previous message, see the first post please :)

**Environment:**
 - OS: CentOS 7
 - MPI runtime: mpirun (Open MPI) 3.1.4
 - RELION version: RELION-3.1.2-commit-dcab79
 - RAM: 256GB
 - GPU: 4x Quadro RTX 5000

**Dataset:**
 - Box size: 4096x4096x40
 - Pixel size: 0.5976A
 - Number of particles: 10 000
 - Description: Apoferritin dataset

**Job options:**
 - Type of job: Motion Correction
 - Number of MPI processes: 4 (tried multiple combinations with threads)
 - Number of threads: 6 (tried multiple combinations with MPI procs)
 - Full command (see `note.txt` in the job directory):
 
```
`which relion_run_motioncorr_mpi` --i Import/job006/movies.star --o MotionCorr/job011/ --first_frame_sum 1 --last_frame_sum -1 --use_own  --j 6 --bin_factor 1 --bfactor 100 --dose_per_frame 1 --preexposure 0 --patch_x 5 --patch_y 5 --eer_grouping 32 --dose_weighting  --grouping_for_ps 4   --pipeline_control MotionCorr/job011/
```

**Error message:**

There is **no** error message, no output. The process is in running category and hangs in there.

**Comment by biochem-fan** [comment]
What happens if you specify 1 process? What does the per-movie log file say?

**Comment by NuwandaCZ** [comment]
I can't believe I didn't think of this, thank you! Your comment was more than helpful. It was a problem regarding mpi, a certain program overwrote default systemwide openmpi path and relion was trying to use that. All fixed and working now. Thanks for a fast respons!
