### ISSUE TITLE
Euler angles corrupted when combining --gpu and --skip_rotate options

### ISSUE THREAD

**Issue by cvsindelar** [3dem/relion#803]
This is definitely a bug, but luckily there is an easy workaround. I am posting because it cost me a couple days of testing to find the problem. In tests with relion_refine (relion v3.08 and relion v3.1), I have been refining shifts only on a star file whose particle euler angles are well defined (but shifts need refinement due to unbinning). To do so, I used various combinations of -skip_rotate, or imposing very tight constraints on the euler search (sigma_ang = 0.0001). However, I discovered all these approaches failed, despite output messages stating that only one orientation would be searched.  Instead, particle euler angles became randomized for an apparently random subset of the particles, with each iteration of refinement. After several iterations, most particles no longer had useful euler angles. 

I finally realized that if I turned off the --gpu option, the refinement produced the expected results (no changes in the euler angles). In hindsight, this makes some sense given that --gpu is not even allowed for the --skip_align type of refinement. However, I had assumed that if the --gpu option was available, the results would be meaningful. 

So- at the very least, it would be nice if RELION would produce an error message if a combination of --gpu and --skip_rotate is attempted!!

**Comment by biochem-fan** [comment]
Thank you very much for your report. We added this check.

> However, I discovered all these approaches failed, despite output messages stating that only one orientation would be searched. Instead, particle euler angles became randomized for an apparently random subset of the particles, with each iteration of refinement

Perhaps `--perturb 0` helps?

**Comment by cvsindelar** [comment]
--perturb 0 was one of the things I tried, but did not fix the problem.
