### ISSUE TITLE
RELION 4.0b compiling on Arch

### ISSUE THREAD

**Issue by rbs-sci** [3dem/relion#804]
Not sure if a pull request is really needed for such a simple fix, but will make one if required (although am new to github).

**Issue:**
Compiling RELION v4.0b on Arch linux fails with errors for tilt_geometry.cpp and Euler_angles_dynamo.h

**Environment:**
 - OS: Arch Linux
 - MPI runtime: OpenMPI 4.1.1
 - Compiler: gcc 9.3/10.3/11.1
 - RELION version: RELION-4.0-beta-1-commit-33f934 

**Solution:**
Add lines:

```
#include <stdexcept>
#include <limits>
```

To tilt_geometry.cpp and Euler_angles_dynamo.h

And compilation will succeed. Not tested exhaustively yet.

**Comment by biochem-fan** [comment]
Thank you very much for your feedback. I applied your suggestion in commit c8ab56d.

**Comment by rbs-sci** [comment]
The commit modifies Euler_angles_relion.h, not Euler_angles_dynamo.h? The build still fails because of the missing includes in Euler_angles_dynamo.h

**Comment by biochem-fan** [comment]
Oops. This is my mistake.

**Comment by rbs-sci** [comment]
RELION-4.0-beta-1-commit-bee2ef compiles and runs, thank you.
