### ISSUE TITLE
Building RELION-4 requires a library not listed in the installation instructions

### ISSUE THREAD

**Issue by Guillawme** [3dem/relion#806]
Hello,

This is not really a bug, more an update for the installation instructions at https://relion.readthedocs.io/en/release-4.0/Installation.html

With all required packages to build RELION-3.1.3 successfully, RELION-4 won't build. Turns out it needs an additional library that I did not have. Installing the package `libjpeg-turbo-devel` (in Rocky; it may have a different name in other distributions) resolved the problem and allowed me to successfully build RELION-4. This should be added to the installation documentation.

**Environment:**
 - OS: Rocky 8.4
 - MPI runtime: OpenMPI 3.1.6
 - RELION version: RELION-4.0-beta1 as of commit 1d8333c
 - Memory: 128 GB
 - GPU: GTX 1070Ti

(other info in the bug report template either does not apply of is irrelevant to this report).

**Comment by Guillawme** [comment]
I did not save the error message, but I can replicate the error next week and I will let you know.

The first indication was in the output of the `cmake` command, where a line reported that JPEG had not been found, which I noticed when scrolling back after the compilation failed.

**Comment by liupppppp** [comment]
I'm having the same problem, but I'm having a problem with make after specifying a custom installed libjpeg as an argument.  

cmake error:
`BUILD_SHARED_LIBS = OFF
-- Building static libs (larger build size and binaries)
Running apps/CMakeLists.txt...
-- CMAKE_BINARY_DIR:/Share/app/relion/4.0_intel/build
PNG FOUND
-- Could NOT find JPEG (missing: JPEG_LIBRARY JPEG_INCLUDE_DIR) 
JPEG NOT FOUND
-- Found OpenMP_C: -qopenmp (found version "5.0") 
-- Found OpenMP_CXX: -qopenmp (found version "5.0") 
-- Found OpenMP: TRUE (found version "5.0")  
-- Configuring done
-- Generating done
-- Build files have been written to: /Share/app/relion/4.0_intel/build`

----------------------------------------------------------------------------------------------------------

make error:

`[  0%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/autopicker.cpp.o
In file included from /Share/app/relion/4.0_intel/src/jaz/gravis/tImage.h(295),
                 from /Share/app/relion/4.0_intel/src/jaz/image/raw_image.h(7),
                 from /Share/app/relion/4.0_intel/src/jaz/image/buffered_image.h(4),
                 from /Share/app/relion/4.0_intel/src/jaz/single_particle/obs_model.h(29),
                 from /Share/app/relion/4.0_intel/src/helix.h(34),
                 from /Share/app/relion/4.0_intel/src/healpix_sampling.h(31),
                 from /Share/app/relion/4.0_intel/src/autopicker.h(15),
                 from /Share/app/relion/4.0_intel/src/autopicker.cpp(21):
/Share/app/relion/4.0_intel/src/jaz/gravis/private/tImageIO_JPG.hxx(14): catastrophic error: cannot open source file "jpeglib.h"
  #include <jpeglib.h>
                      ^

compilation aborted for /Share/app/relion/4.0_intel/src/autopicker.cpp (code 4)
make[2]: *** [src/apps/CMakeFiles/relion_lib.dir/__/autopicker.cpp.o] Error 4
make[1]: *** [src/apps/CMakeFiles/relion_lib.dir/all] Error 2
make: *** [all] Error 2
`

----------------------------------------------------------------------------------------------------------

`CC=mpiicc CXX=mpiicpc cmake .. -DCUDA_ARCH=70 -DJPEG_LIBRARY=/Share/app/libjpeg/6b/lib/libjpeg.so.62 -DJPEG_INCLUDE_DIR=/Share/app/libjpeg/6b/include -DTIFF_INCLUDE_DIR=/Share/app/libtiff/2.42.6/include -DTIFF_LIBRARY=/Share/app/libtiff/2.42.6/lib/libtiff.so.5 -DMKLFFT=ON`

Cmake error after modification:
`[ 47%] Linking CXX executable ../../bin/relion_exp_suppress_cone
CMakeFiles/suppress_cone.dir/__/jaz/scripts/suppress_cone.cpp.o: In function `gravis::priv::JPGImageReader<float>::canHandle(std::string const&)':
suppress_cone.cpp:(.text._ZN6gravis4priv14JPGImageReaderIfE9canHandleERKSs[_ZN6gravis4priv14JPGImageReaderIfE9canHandleERKSs]+0x44): undefined reference to `jpeg_std_error(jpeg_error_mgr*)'
suppress_cone.cpp:(.text._ZN6gravis4priv14JPGImageReaderIfE9canHandleERKSs[_ZN6gravis4priv14JPGImageReaderIfE9canHandleERKSs]+0x7c): undefined reference to `jpeg_CreateDecompress(jpeg_decompress_struct*, int, unsigned long)'
suppress_cone.cpp:(.text._ZN6gravis4priv14JPGImageReaderIfE9canHandleERKSs[_ZN6gravis4priv14JPGImageReaderIfE9canHandleERKSs]+0x8c): undefined reference to `jpeg_stdio_src(jpeg_decompress_struct*, _IO_FILE*)'
suppress_cone.cpp:(.text._ZN6gravis4priv14JPGImageReaderIfE9canHandleERKSs[_ZN6gravis4priv14JPGImageReaderIfE9canHandleERKSs]+0x9d): undefined reference to `jpeg_read_header(jpeg_decompress_struct*, int)'
suppress_cone.cpp:(.text._ZN6gravis4priv14JPGImageReaderIfE9canHandleERKSs[_ZN6gravis4priv14JPGImageReaderIfE9canHandleERKSs]+0xc7): undefined reference to `jpeg_destroy_decompress(jpeg_decompress_struct*)'
CMakeFiles/suppress_cone.dir/__/jaz/scripts/suppress_cone.cpp.o: In function `gravis::priv::JPGImageReader<float>::read(gravis::tImage<float>&, std::string const&)':
suppress_cone.cpp:(.text._ZN6gravis4priv14JPGImageReaderIfE4readERNS_6tImageIfEERKSs[_ZN6gravis4priv14JPGImageReaderIfE4readERNS_6tImageIfEERKSs]+0x49): undefined reference to `jpeg_std_error(jpeg_error_mgr*)'
suppress_cone.cpp:(.text._ZN6gravis4priv14JPGImageReaderIfE4readERNS_6tImageIfEERKSs[_ZN6gravis4priv14JPGImageReaderIfE4readERNS_6tImageIfEERKSs]+0x85): undefined reference to `jpeg_CreateDecompress(jpeg_decompress_struct*, int, unsigned long)'
suppress_cone.cpp:(.text._ZN6gravis4priv14JPGImageReaderIfE4readERNS_6tImageIfEERKSs[_ZN6gravis4priv14JPGImageReaderIfE4readERNS_6tImageIfEERKSs]+0x95): undefined reference to `jpeg_stdio_src(jpeg_decompress_struct*, _IO_FILE*)'
suppress_cone.cpp:(.text._ZN6gravis4priv14JPGImageReaderIfE4readERNS_6tImageIfEERKSs[_ZN6gravis4priv14JPGImageReaderIfE4readERNS_6tImageIfEERKSs]+0xa6): undefined reference to `jpeg_read_header(jpeg_decompress_struct*, int)'
suppress_cone.cpp:(.text._ZN6gravis4priv14JPGImageReaderIfE4readERNS_6tImageIfEERKSs[_ZN6gravis4priv14JPGImageReaderIfE4readERNS_6tImageIfEERKSs]+0xb2): undefined reference to `jpeg_start_decompress(jpeg_decompress_struct*)'
suppress_cone.cpp:(.text._ZN6gravis4priv14JPGImageReaderIfE4readERNS_6tImageIfEERKSs[_ZN6gravis4priv14JPGImageReaderIfE4readERNS_6tImageIfEERKSs]+0x116): undefined reference to `jpeg_read_scanlines(jpeg_decompress_struct*, unsigned char**, unsigned int)'
suppress_cone.cpp:(.text._ZN6gravis4priv14JPGImageReaderIfE4readERNS_6tImageIfEERKSs[_ZN6gravis4priv14JPGImageReaderIfE4readERNS_6tImageIfEERKSs]+0x377): undefined reference to `jpeg_finish_decompress(jpeg_decompress_struct*)'
suppress_cone.cpp:(.text._ZN6gravis4priv14JPGImageReaderIfE4readERNS_6tImageIfEERKSs[_ZN6gravis4priv14JPGImageReaderIfE4readERNS_6tImageIfEERKSs]+0x383): undefined reference to `jpeg_destroy_decompress(jpeg_decompress_struct*)'
suppress_cone.cpp:(.text._ZN6gravis4priv14JPGImageReaderIfE4readERNS_6tImageIfEERKSs[_ZN6gravis4priv14JPGImageReaderIfE4readERNS_6tImageIfEERKSs]+0x57d): undefined reference to `jpeg_destroy_decompress(jpeg_decompress_struct*)'
make[2]: *** [bin/relion_exp_suppress_cone] Error 1
make[1]: *** [src/apps/CMakeFiles/suppress_cone.dir/all] Error 2
make: *** [all] Error 2
`

**Comment by Guillawme** [comment]
> I did not save the error message, but I can replicate the error next week and I will let you know.

I just replicated this build error as follows:

```
cd relion-git/build
cmake -DCMAKE_INSTALL_PREFIX=/opt/relion-4.0-beta -DCUDA_ARCH=61 -DMKLFFT=ON -DFORCE_OWN_FLTK=OFF ..
```

Relevant output (the entire one is in the attached cmake-stdout.txt file):

```
-- Could NOT find JPEG (missing: JPEG_LIBRARY JPEG_INCLUDE_DIR) 
```

But `cmake` completed otherwise, so from this log it seemed like I could still proceed. Then `make` failed as follows (there is more than one error, I also attached the entire log, see make-stdout.txt):

```
/home/guillaume/software/relion/src/jaz/gravis/private/tImageIO_JPG.hxx:14:10: fatal error: jpeglib.h: No such file or directory
 #include <jpeglib.h>
          ^~~~~~~~~~~
compilation terminated.
make[2]: *** [src/apps/CMakeFiles/relion_lib.dir/build.make:147: src/apps/CMakeFiles/relion_lib.dir/__/autopicker_mpi.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1979: src/apps/CMakeFiles/relion_lib.dir/all] Error 2
make: *** [Makefile:149: all] Error 2
```

Installing package `libjpeg-turbo-devel` completely fixes the problem.

**Comment by biochem-fan** [comment]
It turned out that we actually never write JPEG. So I made this dependency optional in the commit d75c80e. Could you please test this commit?

**Comment by Guillawme** [comment]
I confirm that d75c80e builds fine even after I uninstalled `libjpeg-turbo-devel` from my system. Thank you.
