### ISSUE TITLE
Continuation of VDAM Class2D is broken

### ISSUE THREAD

**Issue by biochem-fan** [3dem/relion#807]
Reported in CCPEM https://www.jiscmail.ac.uk/cgi-bin/wa-jisc.exe?A2=CCPEM;a28746eb.2109.

Reproduced locally.

**Comment by biochem-fan** [comment]
EMDL_MLMODEL_GRADIENT_MOMENT1_IMAGE is `run_itNNN_1moment.mrcs` but somehow it tries to read `run_itNNN_1mom050.mrcs`.

**Comment by biochem-fan** [comment]
@dkimanius Can you look at this?

- `pseudo_halfsets` is true. Is this intended for Class2D?
- `EMDL_MLMODEL_GRADIENT_MOMENT1_IMAGE` is `run_itNNN_1moment.mrcs` for all classes. Shouldn't we add `1@`, `2@` ...?

**Comment by biochem-fan** [comment]
`MlModel::write()` in https://github.com/3dem/relion/blob/ver4.0/src/ml_model.cpp#L481:
For 2D processing, pseudo_halfsets for all classes are recorded in one MRCS file.
However, this is not recorded in the model STAR file.
https://github.com/3dem/relion/blob/ver4.0/src/ml_model.cpp#L693

Also:
> `bool is_2d(Iref[0].zdim == 1);`
https://github.com/3dem/relion/blob/ver4.0/src/ml_model.cpp#L693

Shouldn't this be 2?

**Comment by biochem-fan** [comment]
First try:

```diff
diff --git a/src/ml_model.cpp b/src/ml_model.cpp
index dcf78c6..84d9b1a 100644
--- a/src/ml_model.cpp
+++ b/src/ml_model.cpp
@@ -690,8 +691,8 @@ void MlModel::write(FileName fn_out, HealpixSampling &sampling, bool do_write_bi
                        }
                        fn_tmp.compose(iclass+1, fn_tmp); // fn_tmp = integerToString(iclass) + "@" + fn_tmp;
 
-                       fn_mom1 = fn_out + "_1moment.mrcs";
-                       fn_mom2 = fn_out + "_2moment.mrcs";
+                       fn_mom1.compose(iclass + 1, fn_out + "_1moment.mrcs");
+                       fn_mom2.compose(iclass + 1, fn_out + "_2moment.mrcs");
                }
```

This led to SEGV in MlModel::read().

**Comment by biochem-fan** [comment]
This looks OK.

**Comment by dkimanius** [comment]
Looks good! 
Thanks @biochem-fan
