### ISSUE TITLE
torch_models download failed

### ISSUE THREAD

**Issue by gaorongchao** [3dem/relion#809]
```
[ 97%] [ 98%] Built target vis_delocalisation
Built target display
CMake Error at /cm/shared/apps/relion/relion-4.0-beta/build/class_ranker_model_file-prefix/src/class_ranker_model_file-stamp/download-class_ranker_model_file.cmake:9 (file):
  file DOWNLOAD HASH mismatch

    for file: [/cm/shared/apps/relion/relion-4.0-beta/external/torch_models/class_ranker_0.1.3_torch_1.0.1.pt.tar.gz]
      expected hash: [b39f0cbc31f510e3a03e89f1e11110fe]
        actual hash: [d41d8cd98f00b204e9800998ecf8427e]



make[2]: *** [class_ranker_model_file-prefix/src/class_ranker_model_file-stamp/class_ranker_model_file-download] Error 1
make[1]: *** [CMakeFiles/class_ranker_model_file.dir/all] Error 2
make: *** [all] Error 2
```
is there a way to download the torch models and put them to external by user like fftw and fltk?

**Comment by biochem-fan** [comment]
This is your network problem. Did you first contact your IT manager?

**Comment by gaorongchao** [comment]
if your cannot download this file like this. Your can find the url in `cmake/BuildTorch.cmake` . the url is ftp://ftp.mrc-lmb.cam.ac.uk/pub/dari/class_ranker_0.1.3_torch_1.0.1.pt.tar.gz`. so your can download this file use ftp. and then put it to `external/torch_models/`

or your can download from  https://pan.baidu.com/s/1uKzct6iGzSy5MDjZ6rZqSQ 
提取码：mr4d

**Comment by biochem-fan** [comment]
(Clarification for others: the above Baidu link is not maintained and/or confirmed by RELION developers.)

**Comment by gaorongchao** [comment]
@biochem-fan your can provide a url in ReadMe for all user to download the model by themself.
