### ISSUE TITLE
running class2D with a star file with 0 particles gives a non-informative segmentation fault error

### ISSUE THREAD

**Issue by xeniorn** [3dem/relion#814]
this is just an improvement that will make it more user-friendly for beginners and save some time troubleshooting, not a bug per se

happens on every version of relion in the 2 years and any machine

**Comment by biochem-fan** [comment]
I fixed this in the commit 137e73e to `ver4.0`. I will leave 3.1.x as is (we want to focus on 4.0, so we will repair only serious bugs in 3.1).
