### ISSUE TITLE
Relion4: Class3D - weird particle class assignment behaviour when skipping alignment

### ISSUE THREAD

**Issue by ashpike** [3dem/relion#821]
Hi – We are seeing odd behaviour when running 3D classification (w/o alignment) in RELION 4.0beta (4.0-beta-1-commit-11e38b and commit-1fb5b8). During runs initial ptcl class assignment proceeds as expected but at cycle2 some classes collapse to 0. Depopulated classes don’t recover in subsequent cycles. In one case, 7 of 10 classes vanish at cycle2. Input ptcls around 300K.
Any idea what is going on? 
**This behaviour is not seen with 3.1**
Egs.
Cycle 1 – each class gets a fifth of ptcls as expected:
Class3D/job002/run_it001_class001.mrc     0.200000     0.000000     0.000000    49.739998     1.000000 
Class3D/job002/run_it001_class002.mrc     0.200000     0.000000     0.000000    49.739998     0.000000 
Class3D/job002/run_it001_class003.mrc     0.200000     0.000000     0.000000    49.739998     0.000000 
Class3D/job002/run_it001_class004.mrc     0.200000     0.000000     0.000000    49.739998     0.000000 
Class3D/job002/run_it001_class005.mrc     0.200000     0.000000     0.000000    49.739998     0.000000

Cycle2 – ptcls in class 1/3 drop to zero:
Class3D/job002/run_it002_class001.mrc     0.000000    30.100000     8.372900    49.739998     1.000000 
Class3D/job002/run_it002_class002.mrc     0.333332    30.100000     8.372900    15.304615     1.000000 
Class3D/job002/run_it002_class003.mrc     0.000000    30.100000     8.372900    49.739998     0.000000 
Class3D/job002/run_it002_class004.mrc     0.333336    30.100000     8.372900    15.304615     1.000000 
Class3D/job002/run_it002_class005.mrc     0.333332    30.100000     8.372900    15.304615     1.000000

Command is:
relion_refine_mpi --o Class3D/job002/run --i Import/job001/J327-ptcl.star --ref J327-NU-ref-map.mrc --firstiter_cc --ini_high 60 --dont_combine_weights_via_disc --pool 3 --pad 2  --skip_gridding  --ctf --iter 25 --tau2_fudge 8 --particle_diameter 130 --K 5 --flatten_solvent --zero_mask --skip_align  --sym C1 --norm --scale  --j 1  --pipeline_control Class3D/job002/

Similarly in a 10 class job – 7 of classes collapse to zero at cycle2:
Class3D/job005/run_it002_class001.mrc     0.333332    30.100000     8.372900    15.304615     1.000000 
Class3D/job005/run_it002_class002.mrc     0.000000    30.100000     8.372900    49.739998     0.000000 
Class3D/job005/run_it002_class003.mrc     0.000000    30.100000     8.372900    49.739998     0.000000 
Class3D/job005/run_it002_class004.mrc     0.000000    30.100000     8.372900    49.739998     0.000000 
Class3D/job005/run_it002_class005.mrc     0.333332    30.100000     8.372900    15.304615     1.000000 
Class3D/job005/run_it002_class006.mrc     0.000000    30.100000     8.372900    49.739998     0.000000 
Class3D/job005/run_it002_class007.mrc     0.000000    30.100000     8.372900    49.739998     0.000000 
Class3D/job005/run_it002_class008.mrc     0.333336    30.100000     8.372900    15.304615     1.000000 
Class3D/job005/run_it002_class009.mrc     0.000000    30.100000     8.372900    49.739998     0.000000 
Class3D/job005/run_it002_class010.mrc     0.000000    30.100000     8.372900    49.739998     0.000000

For info -- here is a run on another target / ptcl set:
Cycle1:
Class3D/job013/run_it001_class001.mrc     0.166667     0.000000     0.000000    58.944000     1.000000 
Class3D/job013/run_it001_class002.mrc     0.166667     0.000000     0.000000    58.944000     0.000000 
Class3D/job013/run_it001_class003.mrc     0.166667     0.000000     0.000000    58.944000     0.000000 
Class3D/job013/run_it001_class004.mrc     0.166667     0.000000     0.000000    58.944000     0.000000 
Class3D/job013/run_it001_class005.mrc     0.166667     0.000000     0.000000    58.944000     0.000000 
Class3D/job013/run_it001_class006.mrc     0.166667     0.000000     0.000000    58.944000     0.000000

Cycle2: - class 5 drops out………..large jump in ptcls in class2
Class3D/job013/run_it002_class001.mrc     0.100003    30.100000     9.283680    19.648000     0.997987 
Class3D/job013/run_it002_class002.mrc     0.400000    30.100000     9.283680    19.648000     1.000000 
Class3D/job013/run_it002_class003.mrc     0.200000    30.100000     9.283680    19.648000     0.999973 
Class3D/job013/run_it002_class004.mrc     0.200000    30.100000     9.283680    19.648000     0.999920 
Class3D/job013/run_it002_class005.mrc     0.000000    30.100000     9.283680    58.944000     0.000000 
Class3D/job013/run_it002_class006.mrc     0.099997    30.100000     9.283680    19.648000     0.997508

**Environment:**
 - OS: Centos 7
 - MPI runtime: OpenMPI 2.1.1
 - 4.0-beta-1-commit-11e38b and commit-1fb5b8
 - Memory: 128GB
 - GPU: P100

`which relion_refine_mpi` --o Class3D/job002/run --i Import/job001/J327-ptcl.star --ref J327-NU-ref-map.mrc --firstiter_cc --ini_high 60 --dont_combine_weights_via_disc --pool 3 --pad 2  --skip_gridding  --ctf --iter 25 --tau2_fudge 8 --particle_diameter 130 --K 5 --flatten_solvent --zero_mask --skip_align  --sym C1 --norm --scale  --j 1  --pipeline_control Class3D/job002/

**Comment by ashpike** [comment]
Will do - thanks. So far have seen this behaviour with n=2 from ptcls coming from CS -> R4; completely unrelated samples

**Comment by phexorb** [comment]
Experiencing exactly the same problem. Particles are from Relion all the way from motioncor.  Classes collapses in 3D..

**Comment by vamikirt** [comment]
HI,
I also see the exact same behaviour in Class3D in relion4-beta in Subtomogram Averaging mode.

**Comment by vamikirt** [comment]
BTW
In my hands the issue disappears wo --firstiter_cc flag (tested on the exact same job with and without this option), so I guess it's is indeed noise estimation. Although my particles come from relion I've always used this flag to be on a safe side, guess won't do that in classification jobs for now. Is it still safe for refinement jobs though?

**Comment by biochem-fan** [comment]
To be sure, please compare commits adc8e84c and 494bdb8b.
It the former is broken and the latter is fine, the change in noise estimation is the likely cause. Because these are older versions with many other bugs, please use them only for testing.

See also this thread: https://www.jiscmail.ac.uk/cgi-bin/wa-jisc.exe?A2=ind2202&L=CCPEM&D=0&O=D&P=47161

**Comment by scheres** [comment]
Would someone be willing to share their particle stack and initial reference/mask to reproduce the problem here? Preferably, the data set would not be very large and was pre-processed in relion.

**Comment by vamikirt** [comment]
Dear Sjors,

I could only provide a small Subtomogram dataset, but I guess it would be
more convenient with SPA




чт, 24 февр. 2022 г. в 10:00, Sjors Scheres ***@***.***>:

**Comment by scheres** [comment]
Thanks @vamikirt. Yes, SPA data would be better suited for reproducing the problem at LMB. Anyone else? We of course keep everything confidential!

**Comment by scheres** [comment]
I have found a bug in src/ml_optimiser.cpp and made a new commit to 3dem/relion-devel:  https://github.com/3dem/relion-devel/commit/44ea964bc519bf26f1c05804c0f40baeaca25a88
It could surely explain the original issue raised by @ashpike, especially if few threads and pooled particles were used.

**Comment by vamikirt** [comment]
So it's not publicly available yet? the link is 404 for me

**Comment by scheres** [comment]
Sorry my mistake. It should be now: https://github.com/3dem/relion/commit/44ea964bc519bf26f1c05804c0f40baeaca25a88

**Comment by vamikirt** [comment]
I do
git checkout 44ea964
and get 
error: pathspec 'ver44ea964' did not match any file(s) known to git.

**Comment by scheres** [comment]
Can't you just update the code, using 'git pull'?

**Comment by ashpike** [comment]
@scheres @biochem-fan . Have re-run jobs mentioned at beginning of this issue with latest version (4.0-beta-2-commit-ce2e93)  and can confirm that class distributions are now as expected. So for me at least, the problem is solved. Many thanks

**Comment by scheres** [comment]
Thanks a lot @ashpike!
