### ISSUE TITLE
Relion 4 reconstruct particle bug

### ISSUE THREAD

**Issue by tom-o-gram** [3dem/relion#828]
In the newest commit of the relion 4 beta (commit 2fba16), I am encountering a bug in the ReconstructParticleTomo function - when reconstructing the map from the 2D tilt series, the PostProcess job fails with the error "Postprocessing::run ERROR: FSC curve never drops below randomise_fsc_at". When checking the reconstructed half maps and full maps, the only density is a small blob in the centre of the box, with CTF-like ripples around it. If I run the same job without using the 2D tilt series, the output maps look completely fine. This happens for both the tutorial dataset and my own data, and switching back to the initial commit (1fb5b8) fixes the issue. Running on a Linux cluster (CentOS 7, openMPI 1.10.3)

**Comment by scheres** [comment]
Hi tom, is this still the case with the current code?

**Comment by tom-o-gram** [comment]
Hi Sjors,

No it has been fixed, maybe a couple of commits after the time of posting.
