### ISSUE TITLE
3D reconstruction using imported particles

### ISSUE THREAD

**Issue by yyyancey** [3dem/relion#839]
Hello everyone,
I tried to import particles from another relion project using the 'particles.star'. These particles can generate the initial model normally, however, when I tried the 3D refinement I found that the resolution of the generated model is very low and the model looks very weird. In the original project, the same particles with the same steps can generate a much better 3D model.
I think there is something wrong with my operation or the particles import module, can anybody help me?

**Comment by biochem-fan** [comment]
What happens if you import `run_data.star` from the successful Refine3D job in the original project? You should also compare the file before and after import and make sure the optics group table remains the same.

**Comment by yyyancey** [comment]
> What happens if you import `run_data.star` from the successful Refine3D job in the original project? You should also compare the files before and after import and make sure the optics group table remains the same.

Thank you for your prompt reply and kindly support, I'll do the experiment soon and reply to you.

**Comment by yyyancey** [comment]
> What happens if you import `run_data.star` from the successful Refine3D job in the original project? You should also compare the files before and after import and make sure the optics group table remains the same.

I have tried to import `run_data.star` instead (both in the original project or in a new project) and found that the 3D refinement is back to normal. In fact, I wrote a particles clustering program on my own and I want to test it on relion. On the first try, I replaced particles item in the `particles.star` in the first extraction job according to my clustering selection result. Compared to  `run_data.star`, the `particles.star` I used lost information like 

> _rlnGroupNumber #17 
_rlnAngleRot #18 
_rlnAngleTilt #19 
_rlnOriginXAngst #20 
_rlnOriginYAngst #21 
_rlnNormCorrection #22 
_rlnLogLikeliContribution #23 
_rlnMaxValueProbDistribution #24 
_rlnNrOfSignificantSamples #25 
_rlnRandomSubset #26 

I'm curious about which of them play an important role in the refinement job, maybe I can add them by myself. I'm also curious about why these imported particles in my first try together with the initial model in the original project can generate the refined model normally (I'm confused because it looks like the initial model went wrong, but the model is not different from it in the original project as far as I can see).

**Comment by biochem-fan** [comment]
Are you sure `particle.star` and `run_data.star` have exactly the same box size and the pixel size? This is the most probable mistake.

Are particles very off-centered? If so, Refine3D sometimes cannot find the right shift without good starting points in `rlnOriginXAngst` and `rlnOriginYAngst`. Otherwise, all of these columns can be regenerated.
(Strictly speaking you should inherit `RandomSubset` from your earlier Refine3D runs to keep half sets intact)

**Comment by yyyancey** [comment]
Thank you for your advice!
I have performed my experiment on the beta-galactosidase dataset provided in the `relion31_tutorial` and the results stat the same. I imported my particles.star and generated initial model ( looks quite similar as generated in original project, only the Euler angle in 3D space is different), then I performed  3D refine and found the newly generated initial can't be refined normally. However, the same particles with initial model generated in original project (masked with 50A low pass filter) can perform 3D refinement normally.

> Are you sure particle.star and run_data.star have exactly the same box size and the pixel size? This is the most probable mistake.

Yes, in the experiment I don't change box size and pixel size.

> Are particles very off-centered? If so, Refine3D sometimes cannot find the right shift without good starting points in rlnOriginXAngst and rlnOriginYAngst. Otherwise, all of these columns can be regenerated.
(Strictly speaking you should inherit RandomSubset from your earlier Refine3D runs to keep half sets intact)

Maybe these variables didn't affect the final outcome so much because the same particles with initial model can perform 3D refinement normally (╯︵╰).

> Does your program only remove some particles or change values of some columns?

According to the clustering result of my program, I just removed some particles in particles.star from extraction job and the others stay the same.

**Comment by biochem-fan** [comment]
Just to make sure: is your new initial model properly aligned to the symmetry axis? What happens if you refine in C1?

**Comment by yyyancey** [comment]
The model can be refined successfully in C1. How can I make my  initial model properly aligned? Thanks!

**Comment by biochem-fan** [comment]
It is mentioned in the tutorial.

**Comment by yyyancey** [comment]
I have solved this problem using the command line instruction `relion_align_symmetry --i InitialModel/job015/run_it150_class001.mrc \--o InitialModel/job015/run_it150_class001_alignD2.mrc --sym D2` .
Thank you very much!
