### ISSUE TITLE
Misleading error message from obs_model.cpp

### ISSUE THREAD

**Issue by cdienem** [3dem/relion#842]
The error message in the below referenced code requests rlnPixelSize as a label. According to the meta data labels checked in the lines before, it should be rlnImagePixelSize or rlnMicrographPixelSize or rlnOriginalMicrographPixelSize. Without reading the code, it would be very difficult to troubleshoot this. Maye this is worth a small edit.

https://github.com/3dem/relion/blob/72bbf0c06cea68f8992328703ee5ae5f3d1fc9b7/src/jaz/obs_model.cpp#L190-L201

**Comment by biochem-fan** [comment]
Thank you very much for pointing this out. Repaired for 4.0 in a45103f9.
