### ISSUE TITLE
Unsupported MRC mode 154285104

### ISSUE THREAD

**Issue by Rick-Baker** [3dem/relion#844]
Hello,

we are trying to do an Extract job in Relion 4-beta-2 using micrographs that were motion corrected in cryoSPARC. We have recently gotten a new error that states "readMRC: unsupported MRC mode 154285104". We have used these micrographs successfully for particle extraction in the same Relion processing directory, but it has stopped working. Even trying to re-run previously successful jobs fail. We can still use the micrographs for a CtfFind job and they can be read by relion_image_handler, but Relion won't display them or use them for Extraction.

I just updated to the newest commit (a26bd45) and the issue is still there.

Thanks for any insight!

-Rick Baker

**Comment by biochem-fan** [comment]
I have never heard of such an MRC file mode. It should be 2 (float32) or 12 (float16). Note that we don't support big-endian MRC files.

> We have used these micrographs successfully for particle extraction in the same Relion processing directory, but it has stopped working. Even trying to re-run previously successful jobs fail.

Are you sure the image is not corrupted on your disk?

What does the `header` command from IMOD say?

If you are certain your files are OK, can you compile earlier commits of RELION and see which commit is offending?

**Comment by Rick-Baker** [comment]
Yes, the very first file in our dataset was corrupted. We removed that and it fixed the problem. Thanks.
