### ISSUE TITLE
How the GPU memory consumption scales in relion_refine with the number of threads per MPI?

### ISSUE THREAD

**Issue by vamikirt** [3dem/relion#846]
Dear Developers,

I have a perhaps naive question regarding how the GPU memory consumption scales in relion_refine with the number of threads per MPI
I am runnin relion_refine in relion4 in subtomogram averaging mode, with ~12k particles (and 33 projections in each "Pseudo Subtomogram") with 320 px box size. The system specs are below:

 - OS: CentOS-7
 - MPI runtime: OpenMPI 3.1.3
 - RELION version 4.0-beta-2-commit-b44f96
 - RAM: 187 Gb 
 - GPU: 4x V100 32 Gb
 - 32 threads
 
I run with 5 MPIs (1 per GPU), and when I try to use 8 threads (i.e. to utilize all cores) I get an error indicating the GPU memory was insufficient, in fact I get the error with even 4 threads per MPI, but with 2 threads/MPI it works, however it's quite slow.
Other relevant arguments I'm using: 
--pool 1 --pad 2 --dont_combine_weights_via_disc --free_gpu_memory 1000

In this context it's hard for me to comprehend for example this:
"For RELION, I don't recommend 4x 3080 Ti/3090 setup. Typical Refine3D jobs need 2-3 MPI processes/GPU, each with 8-12 threads, to fully saturate these latest GPUs. Unless you have a dual socket workstation, you cannot fully utilize four of these Ampere-generation GPUs."
Or is it only relevant for SPA, not StA relion_refine?

My other question is, how can I check how much memory relion tries to allocate and what would be the best strategy to speed up the calculations w/o sacrificing the resolution significantly in my case (e.g. disable ctf padding, increase nr of pooled ptcls, etc.)?

ERROR message:
____________________________________________________________________
in: .../relion/src/acc/cuda/cuda_fft.h, line 226
ERROR: 

When trying to plan one or more Fourier transforms, it was found that the available
GPU memory was insufficient. Relion attempts to reduce the memory by segmenting
the required number of transformations, but in this case not even a single
transform could fit into memory. Either you are (1) performing very large transforms,
or (2) the GPU had very little available memory.

	(1) may occur during autopicking if the 'shrink' parameter was set to 1. The 
	recommended value is 0 (--shrink 0), which is argued in the RELION-2 paper (eLife).
	This reduces memory requirements proportionally to the low-pass used. 

	(2) may occur if multiple processes were using the same GPU without being aware
	of each other, or if there were too many such processes. Parallel execution of 
	relion binaries ending with _mpi ARE aware, but you may need to reduce the number
	of mpi-ranks to equal the total number of GPUs. If you are running other instances 
	of GPU-accelerated programs (relion or other), these may be competing for space.
	Relion currently reserves all available space during initialization and distributes
	this space across all sub-processes using the available resources. This behaviour 
	can be escaped by the auxiliary flag --free_gpu_memory X [MB]. You can also go 
	further and force use of full dynamic runtime memory allocation, relion can be 
	built with the cmake -DCachedAlloc=OFF
_____________________________________________________________________

Thanks in advance,
Vasilii

Kudryashev Lab
MDC Berlin

**Comment by biochem-fan** [comment]
The exact amount of required GPU memory depends on the dataset. If the data is hard to align, the program needs to consider more possibilities and consumes more memory. Still, three volumes (reference, backprojection of images and weights) dominate the memory usage in SPA. Thus, the GPU memory consumption roughly scales with the number of MPI processes (not threads) on a GPU and the number of classes in SPA. On the other hand, STA needs more memory per "particles", becaue each "particle" is actually 3D. So the number of pooled particles and threads have more influence than in SPA.

> Or is it only relevant for SPA, not StA relion_refine?

In practice, probably you cannot run many MPI processes per GPU for STA.

This is a general remark. I myself never work on STA, so I hope others can give a more concrete advice.

> --free_gpu_memory 1000

Why did you put this argument? What if you remove this?

**Comment by vamikirt** [comment]
Dear Nakane-san,

If I don't put the argument --free_gpu_memory 1000 the job fails with any settings, e.g. nr of MPIs, threads, etc.
I don't exactly understand why this is happening, but my gut feeling is that relion overallocates the gpu memory somehow. Bc when I use --free_gpu_memory 1000 and check nvidia-smi, I see that actually less than 1 GB is free on the GPUs.

Thanks
Vasilii

**Comment by scheres** [comment]
It's hard to predict GPU memory usage. Therefore, RELION will grab all it can. Please run one MPI process per GPU, especially for something as memory-hungry as 3D data.
