### ISSUE TITLE
Micelle density artifacts (streaky) during multibody refinement

### ISSUE THREAD

**Issue by diffracteD** [3dem/relion#855]
Hi,
I'm not sure if this is the correct forum for it but I'm having trouble with micelle density while running multibody refinement.
My density of the membrane region looks fine before starting multibody (after segmenting map and masking 0.0017 threshold). But after the multibody run most of the micelle densities are becoming streaky with stronger signal intensity than some transmembrane helices.
Due to this reason I'm also not being able to mask them out.
Please suggest if I need to change something in multibody.star file to avoid overfitting micelles.
Here's the parameter set I was using:

```
data_
loop_
_rlnBodyMaskName
_rlnBodyRotateRelativeTo
_rlnBodySigmaAngles
_rlnBodySigmaOffset
_rlnBodyReferenceName
/multibodyFiles/headMask.mrc 2 10 2 /multibodyFiles/head_ref.mrc 
/multibodyFiles/tailMask.mrc 1 15 3 /multibodyFiles/tail_ref.mrc
/multibodyFiles/Tm_Mask.mrc 1 25 5 multibodyFiles/Tm_ref.mrc (transmembrane flexible body, body I'm having overfitting issue)

```
Thank you.

**Comment by biochem-fan** [comment]
This is not a bug report but a usage question. Please post to CCPEM.
