### ISSUE TITLE
illegal memory access error during VDAM 2D classification

### ISSUE THREAD

**Issue by eariascib** [3dem/relion#859]
Good morning,

I am trying to run the new VDAM 2D classification with some negative staining data and I am getting a GPU illegal memory access error. Strikingly, this only happens with negative staining data. The program seems to run fine with cryo data.

We have collected the data using a TVIPS CMOS detector on a 120 kV microscope. The images are saved in TIF format, but we converted them to mrc using EMAN2 (_e2proc2d.py *.tif @.mrc_). After that we have imported the images and performed all the preprocessing into Relion (CTFfind, Topaz, particle extraction without inverting the contrast).

Interestingly, the classical algorithm (EM) works fine, and it's only the new one that gets stalled at iter 3 and gives the error.

The only difference (besides the nature of the data and camera) during processing is that for the negative staining data we do not run motioncor. Maybe the new algorithm is more sensitive to hot pixels or other outliers in the images that are normally discarded/corrected during motioncor?

I would be very grateful if you could give me some assistance to solve this issue.

**Environment:**
OS: Linux Mint 18.1. Linux kernel 4.4.0-53-generic
MPI runtime: mpich-3.1.4
RELION version Relion4.0
Memory: 128 GB
GPU: 2x GTX 1080Ti
CUDA 8.0

**Dataset:**
 - Box size: 128 px
 - Pixel size: 2.8 Å/px
 - Voltage: 100 kV
 - Cs: 2.9 mm
 - Number of particles: 18,000 (negative staining data. White particles over dark background)
 - Description: tetrameric protein of about 350 kDa in total.

**Job options:**
 - Type of job: Class2D (VDAM)
 - Number of MPI processes: 1
 - Number of threads: 12
 - Full command (see `note.txt` in the job directory): we've tried several options, but they all get stuck at iter 3.
   ```
  `which relion_refine` --o Class2D/job011/run --grad --class_inactivity_threshold 0.1 --grad_write_iter 10 --iter 200 --i Extract/job007/particles.star --dont_combine_weights_via_disc --no_parallel_disc_io --scratch_dir /scratch2/ernesto/relion --pool 60 --pad 2  --tau2_fudge 2 --particle_diameter 350 --K 100 --flatten_solvent  --zero_mask  --center_classes  --oversampling 1 --psi_step 12 --offset_range 5 --offset_step 2 --norm --scale  --j 12 --gpu "0, 1"  --pipeline_control Class2D/job011/

   ```

**Error message:**

This is the output of the out file:

 Will distribute threads over devices  0  1
 Thread 0 mapped to device 0
 Thread 1 mapped to device 1
 Thread 2 mapped to device 0
 Thread 3 mapped to device 1
 Thread 4 mapped to device 0
 Thread 5 mapped to device 1
 Thread 6 mapped to device 0
 Thread 7 mapped to device 1
 Thread 8 mapped to device 0
 Thread 9 mapped to device 1
 Thread 10 mapped to device 0
 Thread 11 mapped to device 1
 Running CPU instructions in double precision. 
 + WARNING: Changing psi sampling rate (before oversampling) to 11.25 degrees, for more efficient GPU calculations
 Initial subset size set to 200
 Final subset size set to 1000
 + On host osaka: free scratch space = 1862.08 Gb.
 Copying particles to scratch directory: /scratch2/ernesto/relion/relion_volatile/
   2/   2 sec ............................................................~~(,_,">
 For optics_group 1, there are 18428 particles on the scratch disk.
 Estimating initial noise spectra 
   0/   0 sec ............................................................~~(,_,">
 Estimating accuracies in the orientational assignment ... 
   1/   1 sec ............................................................~~(,_,">
 Auto-refine: Estimated accuracy angles= 20.1 degrees; offsets= 25.48 Angstroms
 CurrentResolution= 39.8222 Angstroms, which requires orientationSampling of at least 12.8571 degrees for a particle of diameter 350 Angstroms
 Oversampling= 0 NrHiddenVariableSamplingPoints= 67200
 OrientationalSampling= 11.25 NrOrientations= 32
 TranslationalSampling= 5.6 NrTranslations= 21
=============================
 Oversampling= 1 NrHiddenVariableSamplingPoints= 2150400
 OrientationalSampling= 5.625 NrOrientations= 256
 TranslationalSampling= 2.8 NrTranslations= 84
=============================
 Gradient optimisation iteration 1 of 200 with 200 particles (Step size 0.9)
   1/   1 sec ............................................................~~(,_,">
 Maximization ...
   0/   0 sec ............................................................~~(,_,">
 CurrentResolution= 71.68 Angstroms, which requires orientationSampling of at least 22.5 degrees for a particle of diameter 350 Angstroms
 Oversampling= 0 NrHiddenVariableSamplingPoints= 67200
 OrientationalSampling= 11.25 NrOrientations= 32
 TranslationalSampling= 5.6 NrTranslations= 21
=============================
 Oversampling= 1 NrHiddenVariableSamplingPoints= 2150400
 OrientationalSampling= 5.625 NrOrientations= 256
 TranslationalSampling= 2.8 NrTranslations= 84
=============================
 Gradient optimisation iteration 2 of 200 with 200 particles (Step size 0.9)
   0/   0 sec ............................................................~~(,_,">
 Maximization ...
   0/   0 sec ............................................................~~(,_,">
 CurrentResolution= 71.68 Angstroms, which requires orientationSampling of at least 22.5 degrees for a particle of diameter 350 Angstroms
 Oversampling= 0 NrHiddenVariableSamplingPoints= 67200
 OrientationalSampling= 11.25 NrOrientations= 32
 TranslationalSampling= 5.6 NrTranslations= 21
=============================
 Oversampling= 1 NrHiddenVariableSamplingPoints= 2150400
 OrientationalSampling= 5.625 NrOrientations= 256
 TranslationalSampling= 2.8 NrTranslations= 84
=============================
 Gradient optimisation iteration 3 of 200 with 200 particles (Step size 0.9)
000/??? sec ~~(,_,">                                                          [oo](512B) (1536B) (512B) (1536B) [512B] (512B) (1536B) [512B] (512B) (1536B) [512B] (512B) (1536B) (512B) [512B] (512B) (1536B) [512B] (512B) (1536B) [512B] (512B) (1536B) [512B] (512B) (1536B) (512B) (1536B) (512B) (1536B) (512B) (1536B) [512B] (512B) (1536B) [512B] (512B) (1536B) [512B] (512B) (1536B) [512B] (512B) (1536B) [512B] (512B) (1536B) [512B] (512B) (1536B) [512B] (512B) (1536B) (512B) (1536B) (512B) (1536B) [512B] (512B) (1536B) [512B] (512B) (1536B) [512B] (512B) (1536B) [512B] (512B) (1536B) [512B] (512B) (1536B) [512B] (512B) (1536B) (512B) (1536B) (512B) (1536B) (512B) (1536B) [512B] (512B) (1536B) (512B) (1536B) (512B) (1536B) (512B) (1536B) [512B] (512B) (1536B) (512B) (1536B) (512B) (1536B) (512B) (1536B) (512B) (1536B) (512B) (1536B) (512B) (1536B) (512B) (1536B) (512B) (1536B) (512B) (1536B) (512B) (1536B) (512B) (1536B) (512B) (1536B) (512B) (1536B) (512B) (1536B) (512B) (1536B) (512B) (1536B) (512B) (1536B) (512B) (1536B) (512B) (1536B) (512B) (1536B) (512B) (1536B) (512B) (1536B) (512B) (1536B) (512B) (1536B) (512B) (1536B) (512B) (1536B) (512B) (1536B) (512B) (1536B) (512B) (1536B) (512B) (1536B) (512B) (1536B) (512B) (1536B) (512B) (1536B) (512B) (1536B) (512B) (1536B) (512B) (1536B) (512B) (1536B) (512B) (1536B) (512B) (1536B) (512B) (1536B) (512B) (1536B) (512B) (1536B) (512B) (1536B) (512B) (1536B) (512B) (1536B) (512B) (1536B) (1536B) (512B) (1536B) (512B) (1536B) (512B) (1536B) (512B) (1536B) (512B) (1536B) (512B) (1536B) (512B) (1536B) (512B) (1536B) (512B) (1536B) (512B) (1536B) (512B) (1536B) (512B) (1536B) (512B) (1536B) (512B) (1536B) (512B) (1536B) (512B) (1536B) (512B) (1536B) (512B) (1536B) (65536B) (66560B) (65536B) (66560B) (65536B) <65536B> [9915867136B] = 9916478464B

######################

And this is the err file:

ERROR: an illegal memory access was encountered in /usr/local/relion_4.0_beta/src/acc/cuda/custom_allocator.cuh at line 175 (error-code 77)
in: /usr/local/relion_4.0_beta/src/acc/cuda/cuda_settings.h, line 65
ERROR: 

A GPU-function failed to execute.

 If this occured at the start of a run, you might have GPUs which
are incompatible with either the data or your installation of relion.
If you 

	-> INSTALLED RELION YOURSELF: if you e.g. specified -DCUDA_ARCH=50
	   and are trying ot run on a compute 3.5 GPU (-DCUDA_ARCH=3.5), 
	   this may happen.

	-> HAVE MULTIPLE GPUS OF DIFFERNT VERSIONS: relion needs GPUS with
	   at least compute 3.5. You may be trying to use a GPU older than
	   this. If you have multiple generations, try specifying --gpu <X>
	   with X=0. Then try X=1 in a new run, and so on. The numbering of
	   GPUs may not be obvious from the driver or intuition. For a list
	   of GPU compute generations, see 

	   en.wikipedia.org/wiki/CUDA#Version_features_and_specifications

	-> ARE USING DOUBLE-PRECISION GPU CODE: relion was been written so
	   as to not require this, and may thus have unforeseen requirements
	   when run in this mode. If you think it is nonetheless necessary,
	   please consult the developers with this error.

If this occurred at the middle or end of a run, it might be that

	-> YOUR DATA OR PARAMETERS WERE UNEXPECTED: execution on GPUs is 
	   subject to many restrictions, and relion is written to work within
	   common restraints. If you have exotic data or settings, unexpected
	   configurations may occur. See also above point regarding 
	   double precision.
If none of the above applies, please report the error to the relion
developers at    github.com/3dem/relion/issues

**Comment by eariascib** [comment]
Thanks for the quick reply.

I obtain the same error disabling CTF correction and also enabling it with and without ignoring the CTF until the first peak.

I've tried to include the --maxsig 100 option with and without CTF correction and the error is quite similar. It has an additional line at the end of the run.out file, so I'm pasting it here in casi it's useful:

 Will distribute threads over devices  0  1
 Thread 0 mapped to device 0
 Thread 1 mapped to device 1
 Thread 2 mapped to device 0
 Thread 3 mapped to device 1
 Thread 4 mapped to device 0
 Thread 5 mapped to device 1
 Thread 6 mapped to device 0
 Thread 7 mapped to device 1
 Thread 8 mapped to device 0
 Thread 9 mapped to device 1
 Thread 10 mapped to device 0
 Thread 11 mapped to device 1
 Running CPU instructions in double precision. 
 + WARNING: Changing psi sampling rate (before oversampling) to 11.25 degrees, for more efficient GPU calculations
 Initial subset size set to 200
 Final subset size set to 1000
 + On host osaka: free scratch space = 1862.08 Gb.
 Copying particles to scratch directory: /scratch2/ernesto/relion/relion_volatile/
   2/   2 sec ............................................................~~(,_,">
 For optics_group 1, there are 18428 particles on the scratch disk.
 Estimating initial noise spectra 
   1/   1 sec ............................................................~~(,_,">
 Estimating accuracies in the orientational assignment ... 
   1/   1 sec ............................................................~~(,_,">
 Auto-refine: Estimated accuracy angles= 8.6 degrees; offsets= 12.04 Angstroms
 CurrentResolution= 39.8222 Angstroms, which requires orientationSampling of at least 12.8571 degrees for a particle of diameter 350 Angstroms
 Oversampling= 0 NrHiddenVariableSamplingPoints= 67200
 OrientationalSampling= 11.25 NrOrientations= 32
 TranslationalSampling= 5.6 NrTranslations= 21
=============================
 Oversampling= 1 NrHiddenVariableSamplingPoints= 2150400
 OrientationalSampling= 5.625 NrOrientations= 256
 TranslationalSampling= 2.8 NrTranslations= 84
=============================
 Gradient optimisation iteration 1 of 200 with 200 particles (Step size 0.9)
   0/   0 sec ............................................................~~(,_,">
 Maximization ...
   1/   1 sec ............................................................~~(,_,">
 CurrentResolution= 71.68 Angstroms, which requires orientationSampling of at least 22.5 degrees for a particle of diameter 350 Angstroms
 Oversampling= 0 NrHiddenVariableSamplingPoints= 67200
 OrientationalSampling= 11.25 NrOrientations= 32
 TranslationalSampling= 5.6 NrTranslations= 21
=============================
 Oversampling= 1 NrHiddenVariableSamplingPoints= 2150400
 OrientationalSampling= 5.625 NrOrientations= 256
 TranslationalSampling= 2.8 NrTranslations= 84
=============================
 Gradient optimisation iteration 2 of 200 with 200 particles (Step size 0.9)
   1/   1 sec ............................................................~~(,_,">
 Maximization ...
   0/   0 sec ............................................................~~(,_,">
 CurrentResolution= 71.68 Angstroms, which requires orientationSampling of at least 22.5 degrees for a particle of diameter 350 Angstroms
 Oversampling= 0 NrHiddenVariableSamplingPoints= 67200
 OrientationalSampling= 11.25 NrOrientations= 32
 TranslationalSampling= 5.6 NrTranslations= 21
=============================
 Oversampling= 1 NrHiddenVariableSamplingPoints= 2150400
 OrientationalSampling= 5.625 NrOrientations= 256
 TranslationalSampling= 2.8 NrTranslations= 84
=============================
 Gradient optimisation iteration 3 of 200 with 200 particles (Step size 0.9)
000/??? sec ~~(,_,">                                                          [oo](512B) (1536B) (512B) (1536B) [512B] (512B) (1536B) [512B] (512B) (1536B) (512B) [512B] (512B) (1536B) [512B] (512B) (1536B) [512B] (512B) (1536B) [512B] (512B) (1536B) [512B] (512B) (1536B) (512B) (1536B) [512B] (512B) (1536B) [512B] (512B) (1536B) (512B) (1536B) [512B] (512B) (1536B) [512B] (512B) (1536B) [512B] (512B) (1536B) [512B] (512B) (1536B) [512B] (512B) (1536B) [512B] (512B) (1536B) [512B] (512B) (1536B) [512B] (512B) (1536B) [512B] (512B) (1536B) (512B) (1536B) [512B] (512B) (1536B) (512B) (1536B) (512B) (1536B) [512B] (512B) (1536B) [512B] (512B) (1536B) (512B) (1536B) [512B] (512B) (1536B) [512B] (512B) (1536B) [512B] (512B) (1536B) [512B] (512B) (1536B) (512B) (1536B) (512B) (1536B) (512B) (1536B) (512B) (1536B) [512B] (512B) (1536B) (512B) (1536B) [512B] (512B) (1536B) (512B) (1536B) (512B) (1536B) (512B) (1536B) (512B) (1536B) [512B] (512B) (1536B) (512B) (1536B) (512B) (1536B) (512B) (1536B) (512B) (1536B) [512B] (512B) (1536B) (512B) (1536B) (512B) (1536B) [512B] (512B) (1536B) (512B) (1536B) (512B) (1536B) (512B) (1536B) (512B) (1536B) (512B) (1536B) (512B) (1536B) (512B) (1536B) (512B) (1536B) (512B) (1536B) (512B) (1536B) (512B) (1536B) (512B) (1536B) (512B) (1536B) (512B) (1536B) (512B) (1536B) (512B) (1536B) (1536B) (512B) (1536B) (512B) (1536B) (512B) (1536B) (512B) (1536B) (512B) (1536B) (512B) (1536B) (512B) (1536B) (512B) (1536B) (512B) (1536B) (512B) (1536B) (512B) (1536B) (512B) (1536B) (512B) (1536B) (512B) (1536B) (512B) (1536B) (512B) (1536B) (512B) (1536B) (512B) (1536B) (512B) (1536B) (512B) (1536B) (512B) (1536B) (512B) (1536B) (512B) (1536B) (512B) (1536B) (512B) (1536B) (512B) (1536B) (512B) (1536B) (512B) (1536B) (512B) (1536B) (512B) (1536B) (65536B) (66560B) (65536B) (66560B) (65536B) (66560B) (65536B) <65536B> [9988082688B] = 9988830208B
KERNEL_ERROR: an illegal memory access was encountered in /usr/local/relion_4.0_beta/src/acc/acc_ml_optimiser_impl.h at line 428 (error-code 77)

**Comment by drawoliver** [comment]
Still having the same problem — any thoughts / help / assistance please?

KERNEL_ERROR: an illegal memory access was encountered in /usr/local/git_source/relion-4.0-20220817/src/acc/acc_ml_optimiser_impl.h at line 428 (error-code 700)

**Comment by eariascib** [comment]
Hi,

Since we had the issue, and for different reasons, we had to update the compiler and cuda to newer versions (gcc 9.4; cuda 11.1) and compile relion-4 again. Apparently, that has solved the issue, although we have not done extensive tests.

HTH,
Ernesto.
