### ISSUE TITLE
Missing google drive file for RELION 3.0?

### ISSUE THREAD

**Issue by anaphaze** [3dem/relion#860]
I am re-building RELION 3.0 on a computer that previously succeeded. In the make -j step, I get an error that suggests that a file stored on google drive is missing (see below).

**Environment:**
 - OS: e.g. Ubuntu 18.04.5 LTS
 - MPI runtime: OpenMPI 2.1.0
 - RELION version RELION 3.0.8 commit 5a8f82785e53bc8ed271b096c3f7afff09e5e82f
 - Memory: 128 GB
 - GPU: RTX 2080

**Error message:** (this message repeats itself; the full log is attached)
[error_20220309.txt](https://github.com/3dem/relion/files/8211200/error_20220309.txt)

[ 92%] Built target prepare_subtomo
-- Using src='https://drive.google.com/uc?export=download&id=0B942d76zVnSeazZWcExRaXIyVDg'
CMake Error at /home/dbsganl/linux/temp/relion/build/OWN_FLTK-prefix/src/OWN_FLTK-stamp/download-OWN_FLTK.cmake:157 (message):
  Each download failed!

    error: downloading 'https://drive.google.com/uc?export=download&id=0B942d76zVnSeazZWcExRaXIyVDg' failed
         status_code: 22
         status_string: "HTTP response code said error"
         log:
         --- LOG BEGIN ---
           Trying 172.217.194.138...

  TCP_NODELAY set

  Connected to drive.google.com (172.217.194.138) port 443 (#0)

  ALPN, offering http/1.1

  successfully set certificate verify locations:

    CAfile: /etc/ssl/certs/ca-certificates.crt
    CApath: /etc/ssl/certs

  [5 bytes data]

  TLSv1.3 (OUT), TLS handshake, Client hello (1):

  [512 bytes data]

  [5 bytes data]

  TLSv1.3 (IN), TLS handshake, Server hello (2):

  [122 bytes data]

  [5 bytes data]

  [5 bytes data]

  TLSv1.3 (IN), TLS Unknown, Certificate Status (22):

  [1 bytes data]

  TLSv1.3 (IN), TLS handshake, Unknown (8):

  [21 bytes data]

  TLSv1.3 (IN), TLS handshake, Certificate (11):

  [6387 bytes data]

  TLSv1.3 (IN), TLS handshake, CERT verify (15):

  [78 bytes data]

  TLSv1.3 (IN), TLS handshake, Finished (20):

  [52 bytes data]

  [5 bytes data]

  TLSv1.3 (OUT), TLS change cipher, Client hello (1):

  [1 bytes data]

  [5 bytes data]

  TLSv1.3 (OUT), TLS Unknown, Certificate Status (22):

  [1 bytes data]

  TLSv1.3 (OUT), TLS handshake, Finished (20):

  [52 bytes data]

  SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384

  ALPN, server accepted to use http/1.1

  Server certificate:

   subject: CN=*.google.com
   start date: Feb 17 10:22:00 2022 GMT
   expire date: May 12 10:21:59 2022 GMT
   subjectAltName: host "drive.google.com" matched cert's "*.google.com"
   issuer: C=US; O=Google Trust Services LLC; CN=GTS CA 1C3
   SSL certificate verify ok.

  [5 bytes data]

**Comment by biochem-fan** [comment]
We no longer support RELION 3.0.x.

You can download `fltk-1.3.3-source.tar.gz` from https://www.fltk.org/software.php and put it in `/path_to_your_git_project_root/external/fltk`. Then the installer will use it.
