### ISSUE TITLE
Equivalent of "SkipCTFCorrection" in RELION 4?

### ISSUE THREAD

**Issue by anaphaze** [3dem/relion#861]
I'm not sure if this is a bug or a deprecated feature, so please feel free to close this report:

In RELION 2 & 3, the relion_prepare_subtomograms.py script had a flag "SkipCTFCorrection". When this flag was set to False, RELION would still create a 3-D CTF model, thereby compensating for the missing wedge, but not perform CTF fitting. This feature was extremely useful for Volta phase plate data or when the tomogram is already CTF corrected. In the RELION 4.0 tutorial, there doesn't seem to be an equivalent SkipCTFCorrection flag in the tomogram import steps, or as an "additional argument" of the relion_refine program. Is there a flag or sequence of steps to disable RELION's internal CTF correction while keeping the equivalent of missing-wedge correction functional? Or does the pseudosubtomogram paradigm prevent the separation of CTF fitting and tilt angle "awareness"?

Thanks.

**Environment:**
 - RELION-4.0-beta-2-commit-ce2e935

**Dataset:**
 - Volta phase plate tilt series

**Comment by biochem-fan** [comment]
I know almost nothing about STA, but cannot you model Volta phase plate as phase-shift as is done in SPA?

**Comment by anaphaze** [comment]
Thanks. I will give the new flag "rlnPhaseShift" a try.

**Comment by biochem-fan** [comment]
That is not a flag; the CTF estimation program has to put the right value in that column.

**Comment by anaphaze** [comment]
Thanks again. I was able to get RELION 4 to run with a star file modified to include the new rlnPhaseShift column.

**Comment by xinsheng44** [comment]
> Thanks again. I was able to get RELION 4 to run with a star file modified to include the new rlnPhaseShift column.

Hello, I have the same problem as you, can you tell me how you solved it?
