### ISSUE TITLE
All-zero weights in refinement after polishing 

### ISSUE THREAD

**Issue by abiester** [3dem/relion#862]
I am processing a dataset in relion and tried to run a refinement after polishing, and my error directed me here.

After my initial classifications and refinements, I completed CtfRefine and successfully completed another Refine3D job. Then I ran polishing, which completed successfully. However, when I tried to run a Refine3D job on my polished particles, I got an error message saying that comparison of particle image to reference resulted in all zero weights, and the job failed.

**Environment:**
 - OS: Red Hat Enterprise Linux 8.3
 - MPI runtime: openmpi 3.1.4
 - RELION version: RELION-4.0-beta-2-commit-a26bd4
 - Memory: 512 GB
 - GPU: ASPEED Graphics Family [1a03:2000] (rev 41)

**Dataset:**
 - Box size: 240 px (downscaled from 960 px)
 - Pixel size: 0.8697 Å (superres binned 2) -- but processing with 3.4788 Angstrom/pixel
 - Number of particles: 516,059
 - Description: A 40-meric protein of about 22200 kDa in total

**Job options:**
 - Type of job: Refine3D
 - Number of MPI processes: 3
 - Number of threads: 16
 - Full command (submitted as sbatch job):
   ```
mpirun -n 17 -bind-to none `which relion_refine_mpi` --o Refine3D/job086/run --auto_refine --split_random_halves \
 --i Polish/job085/shiny.star --ref Refine3D/job082/run_half1_class001_unfil.mrc \
 --ini_high 60 --dont_combine_weights_via_disc --pool 3 --pad 2 --skip_gridding \
 --ctf --particle_diameter 400 --flatten_solvent --zero_mask --oversampling 1 \
 --healpix_order 2 --auto_local_healpix_order 4 --offset_range 5 --offset_step 2 \
 --sym C1 --low_resol_join_halves 40 --norm --scale --j 16 --gpu "" --pipeline_control Refine3D/job086/ --scratch_dir /dev/shm/abiester \
 > logs/Refine3D_job086.log_$$ 2>&1
   ```

**Error message:**

follower 2 encountered error: === Backtrace  ===
/programs/x86_64-linux/relion/4.0-beta_cu9.2/bin/relion_refine_mpi(_ZN11RelionErrorC2ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES7_l+0x66) [0x44bc66]
/programs/x86_64-linux/relion/4.0-beta_cu9.2/bin/relion_refine_mpi(_Z36globalThreadExpectationSomeParticlesR14ThreadArgument+0x92) [0x618732]
/programs/x86_64-linux/relion/4.0-beta_cu9.2/bin/relion_refine_mpi(_Z11_threadMainPv+0x15) [0x490345]
/lib64/libpthread.so.0(+0x7e65) [0x7f915a204e65]
/lib64/libc.so.6(clone+0x6d) [0x7f915921b88d]
==================
ERROR: 
No orientation was found as better than any other.

A particle image was compared to the reference and resulted in all-zero
weights (for all orientations). This should not happen, unless your data
has very special characteristics. This has historically happened for some 
lower-precision calculations, but multiple fallbacks have since been 
implemented. Please report this error to the relion developers at 

	         github.com/3dem/relion/issues  
 
[cd-nessie.mit.edu:17326] 1 more process has sent help message help-mpi-api.txt / mpi-abort
[cd-nessie.mit.edu:17326] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages

**Comment by biochem-fan** [comment]
This is an FAQ; see https://www3.mrc-lmb.cam.ac.uk/relion/index.php/FAQs#Refinement_or_Classification_crash_saying_.22No_orientation_was_found.22.
Also search this GitHub issue and CCPEM archive.
