### ISSUE TITLE
automate pick- ERROR: MetaDataTable::Write: cannot write to file: [fileName}

### ISSUE THREAD

**Issue by Bontix77** [3dem/relion#863]
i tried the Auto-picking all the time i get this annoyng ERROR:

ERROR: MetaDataTable::Write: cannot write to file: [fileName]

What is now the problem here?!
I never been able to use this program cause has every single time a problem.

**Comment by biochem-fan** [comment]
Isn't your disk full? How about the permission?

You didn't provide enough information about your system. Please respect the issue template.
