### ISSUE TITLE
Compiling Relion 4.0-beta commit 543db0a using CMake 3.20.1

### ISSUE THREAD

**Issue by mruetter** [3dem/relion#864]
Hi Together,

in order to compile the Relion 4.0-beta version (commit 543db0a) using CMake 3.20.1 with a self-build easyconfig on our HPC cluster, we had to comment out the following lines beginning 216 in the CMakeLists.txt:
```#if ("${MPI_CXX_INCLUDE_DIRS}" STREQUAL "")
#      include_directories("${MPI_CXX_INCLUDE_PATH}")
#else()
#      include_directories("${MPI_CXX_INCLUDE_DIRS}")
#endif()
```

Maybe it helps if somebody else runs into the same issue.

Best,
Max

**Comment by biochem-fan** [comment]
Thanks for information. I will close the issue though, because we won't "fix" this.
