### ISSUE TITLE
Local resolution underestimated after signal subtraction

### ISSUE THREAD

**Issue by cgisriel** [3dem/relion#865]
I have a single particle data set, processing with Relion 3.1, containing 7 subunits (~100 kDa each, no symmetry), but two subunits are at extremely low occupancy. This is solved to 3.3-angstrom resolution (FSC looks good) and I can produce a reasonable local resolution map. To improve the resolution of the 5 high occupancy subunits, I have then masked out signal from the two low occupancy subunits and used a particle subtraction job and subsequent Refine3D. This brings the resolution to 3.1 angstroms after subtraction. The FSC curves look good, and a map comparison shows better defined structural features after subtraction, therefore the increase in resolution seems "real". However, every time I try to run Relion's local resolution job after subtraction, the minimum is always 3.2 to 4.1 or so. This of course does not make sense with the 3.1 global resolution determined from the postprocess job. Any idea how I can get the local resolution job to better reflect what would be expected from the global resolution?

**Comment by biochem-fan** [comment]
What is the local resolution of the globally-3.3 A map before signal subtraction?

Note that a mask is used only to make a histogram of local resolutions; it is not used for local resolution calculation itself.
Thus if the moving window for local resolution estimation is large and almost always contains solvent densities, the result can be lower than masked global resolutions.

**Comment by cgisriel** [comment]
So actually, even before subtraction the minimum local resolution doesn't quite reach the global resolution. But, the problem seems worse upon subtraction.

Before subtraction (PP resolution is 3.328, B=-87.6143):
Number of items: 1112392
Min: 3.30611 Q1: 3.47204 Median: 3.62294 Q3: 3.89735 Max: 6.4641
Mean: 3.76197 Std: 0.427907

After subtraction (PP resolution is 3.09363, B=-70.6088):
Number of items: 365834
Min: 3.249 Q1: 3.34391 Median: 3.41699 Q3: 3.53422 Max: 4.1123
Mean: 3.4524 Std: 0.140789

**Comment by biochem-fan** [comment]
>  worse upon subtraction.

In what sense? Your Min, Q1, Median, Q3, Max, Mean, all improved after subtraction.

There are many algorithms to calculate local resolution. You might want to try other implementations.

**Comment by cgisriel** [comment]
I meant that before subtraction, the PP resolution is 3.328 and minimum local resolution is 3.3 which doesn't seem right, and then after subtraction, the PP resolution is 3.094 and minimum local resolution is 3.34 which is even further separated from the global resolution. Yes, I may try another program.

I get your point about the moving window and I see the local resolution options. This would make sense because the complex is actual helical (don't get me started on symmetry there... that will be a posting for a later date), so there is basically a long string of protein, and thus a low protein-to-solvent ratio.

Maybe I will try altering some of these parameters. Any suggestions as to which?
====== Local-resolution options =====
                   --locres (false) : Perform local resolution estimation
            --locres_sampling (25.) : Sampling rate (in Angstroms) with which to sample the local-resolution map
              --locres_maskrad (-1) : Radius (in A) of spherical mask for local-resolution map (default = 0.5*sampling)
             --locres_edgwidth (-1) : Width of soft edge (in A) on masks for local-resolution map (default = sampling)
        --locres_randomize_at (25.) : Randomize phases from this resolution (in A)
              --locres_minres (50.) : Lowest local resolution allowed (in A)

**Comment by cgisriel** [comment]
I guess the sampling one...

**Comment by biochem-fan** [comment]
Yes.

**Comment by cgisriel** [comment]
@biochem-fan It worked! Decreasing the sampling from the default of 25 to 15 now gives me a minimum of about 3.04 which is more reasonable. I am trying 10, though it takes exponentially longer to process, of course. Thank you so much for your help!
