### ISSUE TITLE
How to use relion in a system without graphical desktop?

### ISSUE THREAD

**Issue by lsy0509** [3dem/relion#866]
How to use relion in a system without graphical desktop?
I couldn't find something useful in tutorial.

**Comment by biochem-fan** [comment]
Do you mean running RELION on a cluster node without X11?
Note that you can usually run GUI via SSH X11 forwarding.

If the node does not have necessary headers, RELION can be compiled without GUI by `cmake -DGUI=OFF`. In this case you should run GUI on another machine with X and then submit a job to the head-less node.
