### ISSUE TITLE
Relion 4.0 Bayesian Polishing Runing so slower than before questions.

### ISSUE THREAD

**Issue by zxianren** [3dem/relion#870]
our workstation has stalled Relion.4.0-beta just last week,and we process the same sample dataset(Falcon 4 EER file)，but slower than before. Especially when is runing Bayesian Polishing， it needs one week!!!
![d9932f8bbad00073483b994a367f63e](https://user-images.githubusercontent.com/103344140/163152712-246ea47d-4044-4ade-a235-54d285f9f767.png)
Here is the little difference than before:
·········································································
Now：
relion4.0
Falcon 4 EER file
process on the External Mechanical hard drives（because the dataset is  much bigger than before and our workstation in not enough）

Before:
Relion 3.0
K2 mrc file
process on the workstation itself.

----------------------------------
The datasets are the same sample, also 3K~ micrographs.Before we only need 5h by the first round polish, but now ,we need more than 7 days!!!
could someone give us good ideas? Thanks so much！！！

**Comment by biochem-fan** [comment]
What is the number of frames in K2 and EER?
What is the grouping for EER? (the number you put in the MotionCorr job)

> process on the workstation itself.
Were the K2 movies on SSD, or RAID HDD?

An external mechanical drive is significantly slower than internal SSD or RAID HDD.
Parallel access from multiple threads/MPI makes it even slower.

**Comment by zxianren** [comment]
Here is the suply information:
Our station：
Relion-4.0-beta  
250G memory
GPU: 4X1080TI

dataset：3000 eer file from Falcon 4

Job: Bayesian Polishing
![f7c802fc0fbcd91460fd2efe02df933](https://user-images.githubusercontent.com/103344140/163157624-0c62d0ee-5a71-4e7c-bb16-6cc164cdb07a.png)

**Comment by biochem-fan** [comment]
Please answer my question.

**Comment by zxianren** [comment]
> Please answer my question.
Sorry for late reply.Here is the information：
40 frames in K2, 48 frames in EER.

K2 movies are on RAID HDD，EER movies are on external mechanical drive.
motioncor number here:(sorry for understanding your question about groupping number,i guss 1?)
![image](https://user-images.githubusercontent.com/103344140/163164868-b7e08601-2f2d-49d6-9a06-5f2d8e6a1bc0.png)
![image](https://user-images.githubusercontent.com/103344140/163165167-55211dd7-ad97-4748-9de6-026f0bbff8dd.png)
![image](https://user-images.githubusercontent.com/103344140/163165210-769f5589-32b9-444d-ba5b-24ffa4a99695.png)

**Comment by biochem-fan** [comment]
48 means you group 48 raw EER frames into one fraction. But how many raw frames do you have in a movie?

Anyway, there is little we can do. As I said, an external HDD is slow and bad at parallel random access. Moreover, probably your EER movies contain more raw frames and thus are larger than K2 movies.

Next time, convert EER movies to TIFF files before processing. It makes files much smaller and faster to process.

**Comment by zxianren** [comment]
> 48 means you group 48 raw EER frames into one fraction. But how many raw frames do you have in a movie?
> 
> Anyway, there is little we can do. As I said, an external HDD is slow and bad at parallel random access. Moreover, probably your EER movies contain more raw frames and thus are larger than K2 movies.
> 
> Next time, convert EER movies to TIFF files before processing. It makes files much smaller and faster to process.

Thaks for your nice reply!!! Have a good day!

**Comment by zxianren** [comment]
> > 48 means you group 48 raw EER frames into one fraction. But how many raw frames do you have in a movie?
> > Anyway, there is little we can do. As I said, an external HDD is slow and bad at parallel random access. Moreover, probably your EER movies contain more raw frames and thus are larger than K2 movies.
> > Next time, convert EER movies to TIFF files before processing. It makes files much smaller and faster to process.
> 
> Thaks for your nice reply!!! Have a good day!

sorry for rebon to ask another question about Convet_to_tif command.
In the tutrioal, it says that Due to the different meanings of the gain reference for EER and TIFF, you have to take the inverse of the EER gain reference before processing the resulting TIFF files. 
![image](https://user-images.githubusercontent.com/103344140/163193838-4a4e4431-42b9-499c-9279-c0adf0f59e8e.png)

We collect the data by **Using EPU** and get a gain file. So it means that I shoud give a gain file when running converting_tif_tools?(The convert tools will autotake the inverse of the EER gain reference，don't need another command? )  At the Motioncorr  stage, I don't have to give a gain reference file again for normalise?
 
Hope your sincerenly reply.Thank you so so so much!!!

**Comment by biochem-fan** [comment]
You should give the gain reference from EPU to `relion_convert_to_tiff`. It will write a new gain file, which should be used in a MotionCorr job.
