### ISSUE TITLE
Particles Extraction error - particle outside of the micrographs

### ISSUE THREAD

**Issue by CFDavidHou** [3dem/relion#872]
Hi there,

I have a quick question about particle extraction.

I am doing localized reconstruction of a long-tail phage that I need to do Z-shift re-extraction of refined/aligned particles. However, if any of the particles that is outside of the micrographs, the job will be terminated.

Is there an argument that I can skip the error. So that I only extract the particles that are inside the micrograph?

Thank you!

David

**Comment by biochem-fan** [comment]
Filter your input by `rlnCoordinateX` and `rlnCoordinateY` and make sure they are far from micrograph edges.

**Comment by CFDavidHou** [comment]
Thank you!
