### ISSUE TITLE
RELION 4.0 pseudo subtomogram Z dimension does not equal number of tilts

### ISSUE THREAD

**Issue by anaphaze** [3dem/relion#873]
I noticed that the Z dimension (Zdim) of the RELION 4 beta pseudo subtomogram _data.mrc files equals the cropped box size. Given that the pseudo subtomograms appears like a mini tilt series, I assumed the Z dimension to equal the number of tilts (Ntilt). This assumption is reinforced by the preprint's sentece that says pseudo subtomograms are: "explicitly constructed sets of 3D data arrays that contain sums of CTF pre-multiplied tilt series images".  My concern is that when the cropped box size is lower than the number of tilts, the pseudo subtomograms would lose information because one would expect an extracted subtomogram (like the ones written by RELION 3) would have Xdim * Ydim * Ntilt voxels worth of information.
So is the fact that the pseudo subtomogram Zdim ≠ tilt number a feature or a bug?

**Environment:**
 - RELION commit 9b23e50e5d8f51b16e6f315e3b59777b5c44cc35

**Dataset**
- Tilt series: 61 total tilt images, ±60° @ 2° increment

**Comment by scheres** [comment]
The assumption that the Zdim equals the number of tilt images is incorrect. An arbitrary number of 2D tilt series images could be put into a user-specific pseudo-subtomogram.
