### ISSUE TITLE
FLTK error in relion3.0 installation

### ISSUE THREAD

**Issue by eariascib** [3dem/relion#874]
Good evening,

I am trying to install relion3.0 to access and re-process some jobs of a couple of years old dataset. However, I obtain an error while downloading the FTLK libraries (see below). Is the link to download this files still valid?

I would be very grateful if you could give me some assistance to solve this issue.

Kind regards,
Ernesto.

**Environment:**

OS: Linux Mint 18.1. Linux kernel 4.4.0-53-generic
MPI runtime: mpich-3.1.4
RELION version Relion4.0
Memory: 128 GB
GPU: 2x GTX 1080Ti
CUDA 11.1

**Error message:**

osaka build # cmake -DCUDA_ARCH=61 ..
-- The C compiler identification is GNU 9.4.0
-- The CXX compiler identification is GNU 9.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- BUILD TYPE set to the default type:  'Release'
-- Using provided CUDA_ARCH=61
-- CUDA enabled - Building CUDA-accelerated version of RELION
-- Setting cpu precision to double
-- Setting accelerated code precision to single
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found CUDA: /usr/local/cuda (found version "11.1") 
-- Using cuda wrapper to compile....
-- Cuda version is >= 7.5 and single-precision build, enable double usage warning.
-- Found MPI_C: /usr/local/mpich-3.1.4/lib/libmpi.so  
-- Found MPI_CXX: /usr/local/mpich-3.1.4/lib/libmpicxx.so;/usr/local/mpich-3.1.4/lib/libmpi.so  
-- MPI_INCLUDE_PATH : /usr/local/mpich-3.1.4/include
-- MPI_LIBRARIES : /usr/local/mpich-3.1.4/lib/libmpicxx.so;/usr/local/mpich-3.1.4/lib/libmpi.so
-- MPI_CXX_INCLUDE_PATH : /usr/local/mpich-3.1.4/include
-- MPI_CXX_LIBRARIES : /usr/local/mpich-3.1.4/lib/libmpicxx.so;/usr/local/mpich-3.1.4/lib/libmpi.so
-- CMAKE_C_COMPILER : /usr/bin/cc
-- CMAKE_CXX_COMPILER : /usr/bin/c++
-- MPI_C_COMPILER : /usr/local/mpich-3.1.4/bin/mpicc
-- MPI_CXX_COMPILER : /usr/local/mpich-3.1.4/bin/mpicxx
-- CMAKE_CXX_COMPILER_ID : GNU
-- CMAKE_C_COMPILER : /usr/local/mpich-3.1.4/bin/mpicc
-- CMAKE_CXX_COMPILER : /usr/local/mpich-3.1.4/bin/mpicxx
-- MPI_C_COMPILER : /usr/local/mpich-3.1.4/bin/mpicc
-- MPI_CXX_COMPILER : /usr/local/mpich-3.1.4/bin/mpicxx
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Looking for IceConnectionNumber in ICE
-- Looking for IceConnectionNumber in ICE - found
-- Found X11: /usr/lib/x86_64-linux-gnu/libX11.so
-- Could NOT find FLTK (missing:  FLTK_INCLUDE_DIR FLTK_FLUID_EXECUTABLE) 
-- No FLTK installation was found
-- --------------------------------------------------------
-- -------- NO EXISTING FLTK LIBRARIES WHERE FOUND. -------
-- -------------- FLTK WILL BE DOWNLOADED AND -------------
-- --------------- BUILT DURING COMPILE-TIME. -------------
-- --------------------------------------------------------
-- ---- A WORKING INTERNET CONNECTION WILL BE REQUIRED. ---
-- --------------------------------------------------------
-- no previous fltk found, the following paths are set for libs/headers TO BE built
-- FLTK_INCLUDE_DIR: /usr/local/relion-3.0/external/fltk/include
-- FLTK_LIBRARIES:   /usr/local/relion-3.0/external/fltk/lib/libfltk.so
-- Found FFTW
-- FFTW_PATH: /usr/include
-- FFTW_INCLUDES: /usr/include
-- FFTW_LIBRARIES: /usr/local/lib/libfftw3f.so;/usr/local/lib/libfftw3.so
-- Looking for sincos
-- Looking for sincos - found
-- Looking for __sincos
-- Looking for __sincos - not found
-- Found TIFF: /usr/lib/x86_64-linux-gnu/libtiff.so (found version "4.0.6") 
BUILD_SHARED_LIBS = OFF
-- Building static libs (larger build size and binaries)
Running apps/CMakeLists.txt...
-- CMAKE_BINARY_DIR:/usr/local/relion-3.0/build
TIFF FOUND
-- Try OpenMP C flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Try OpenMP CXX flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Found OpenMP: -fopenmp  
OPENMP FOUND
-- Configuring done
-- Generating done
-- Build files have been written to: /usr/local/relion-3.0/build
osaka build # make -j 6
Scanning dependencies of target copy_scripts
[  1%] Building NVCC (Device) object src/apps/CMakeFiles/relion_gpu_util.dir/__/acc/cuda/relion_gpu_util_generated_cuda_projector.cu.o
Scanning dependencies of target OWN_FLTK
[  1%] Building NVCC (Device) object src/apps/CMakeFiles/relion_gpu_util.dir/__/acc/cuda/relion_gpu_util_generated_cuda_helper_functions.cu.o
[  2%] Building NVCC (Device) object src/apps/CMakeFiles/relion_gpu_util.dir/__/acc/cuda/cuda_kernels/relion_gpu_util_generated_helper.cu.o
[  3%] Building NVCC (Device) object src/apps/CMakeFiles/relion_gpu_util.dir/__/acc/cuda/relion_gpu_util_generated_cuda_ml_optimiser.cu.o
[  4%] Creating directories for 'OWN_FLTK'
[  4%] Built target copy_scripts
[  4%] Performing download step (download, verify and extract) for 'OWN_FLTK'
[  4%] Building NVCC (Device) object src/apps/CMakeFiles/relion_gpu_util.dir/__/acc/cuda/relion_gpu_util_generated_cuda_projector_plan.cu.o
-- downloading...
     src='https://drive.google.com/uc?export=download&id=0B942d76zVnSeazZWcExRaXIyVDg'
     dst='/usr/local/relion-3.0/external/fltk/fltk-1.3.3-source.tar.gz'
     timeout='none'
-- downloading... done
-- verifying file...
     file='/usr/local/relion-3.0/external/fltk/fltk-1.3.3-source.tar.gz'
-- MD5 hash of /usr/local/relion-3.0/external/fltk/fltk-1.3.3-source.tar.gz
does not match expected value
  expected: 9ccdb0d19dc104b87179bd9fd10822e3
    actual: 0fffe091602069287593150ca8122a31
Retrying download.

-- downloading...
     src='https://drive.google.com/uc?export=download&id=0B942d76zVnSeazZWcExRaXIyVDg'
     dst='/usr/local/relion-3.0/external/fltk/fltk-1.3.3-source.tar.gz'
     timeout='none'
-- downloading... done
-- MD5 hash of /usr/local/relion-3.0/external/fltk/fltk-1.3.3-source.tar.gz
does not match expected value
  expected: 9ccdb0d19dc104b87179bd9fd10822e3
    actual: 6a6902fe2f56ae1945f66e57644f216c
Retrying download.

-- downloading...
     src='https://drive.google.com/uc?export=download&id=0B942d76zVnSeazZWcExRaXIyVDg'
     dst='/usr/local/relion-3.0/external/fltk/fltk-1.3.3-source.tar.gz'
     timeout='none'
-- downloading... done
-- MD5 hash of /usr/local/relion-3.0/external/fltk/fltk-1.3.3-source.tar.gz
does not match expected value
  expected: 9ccdb0d19dc104b87179bd9fd10822e3
    actual: 2a3fc51d758aae9caab15f902f8bbea8
Retrying download.

-- downloading...
     src='https://drive.google.com/uc?export=download&id=0B942d76zVnSeazZWcExRaXIyVDg'
     dst='/usr/local/relion-3.0/external/fltk/fltk-1.3.3-source.tar.gz'
     timeout='none'
[  4%] Building NVCC (Device) object src/apps/CMakeFiles/relion_gpu_util.dir/__/acc/cuda/relion_gpu_util_generated_cuda_backprojector.cu.o
-- downloading... done
CMake Error at /usr/local/relion-3.0/build/OWN_FLTK-prefix/src/OWN_FLTK-stamp/verify-OWN_FLTK.cmake:27 (message):
  error: MD5 hash of

    /usr/local/relion-3.0/external/fltk/fltk-1.3.3-source.tar.gz

  does not match expected value

    expected: 9ccdb0d19dc104b87179bd9fd10822e3
      actual: 296c200839c014e0332196168537ddba

CMakeFiles/OWN_FLTK.dir/build.make:89: recipe for target 'OWN_FLTK-prefix/src/OWN_FLTK-stamp/OWN_FLTK-download' failed
make[2]: *** [OWN_FLTK-prefix/src/OWN_FLTK-stamp/OWN_FLTK-download] Error 1
CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/OWN_FLTK.dir/all' failed
make[1]: *** [CMakeFiles/OWN_FLTK.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[  5%] Building NVCC (Device) object src/apps/CMakeFiles/relion_gpu_util.dir/__/acc/cuda/relion_gpu_util_generated_cuda_benchmark_utils.cu.o
[  5%] Building NVCC (Device) object src/apps/CMakeFiles/relion_gpu_util.dir/__/acc/cuda/relion_gpu_util_generated_cuda_autopicker.cu.o
Scanning dependencies of target relion_gpu_util
[  5%] Linking CXX static library ../../lib/librelion_gpu_util.a
[  5%] Built target relion_gpu_util
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
osaka build #

**Comment by biochem-fan** [comment]
Download https://www.fltk.org/pub/fltk/1.3.3/fltk-1.3.3-source.tar.gz and put it in the external/fltk directory.

**Comment by eariascib** [comment]
We were able to compile the program following your suggestions. Thank you very much for your help!
Best,
Ernesto.
