### ISSUE TITLE
About 3D classfication

### ISSUE THREAD

**Issue by lsy0509** [3dem/relion#875]
Hello, I am very interested in how to generate different kinds of 3D models in 3D classification. I only found in "https://doi.org/10.1016/bs.mie.2016.04.012" that particles were randomly assigned to different kinds of models in the first iteration, but it was not clear how to deal with the relationship between particle images and 3D models in the follow-up. I guess all particles were allocated by comparing reprojection of these 3D models from various  angles , but I failed to find the relevant source code. I would appreciate it if you could give me an overview of what happens in this process and give me the name of the source code file associated with it.

**Comment by biochem-fan** [comment]
See ml_optimiser.cpp.

**Comment by lsy0509** [comment]
Thanks a lot and are there guides or publications that explain the 3D classification process in detail?

**Comment by biochem-fan** [comment]
See Scheres, Sjors HW. "RELION: implementation of a Bayesian approach to cryo-EM structure determination." Journal of structural biology 180.3 (2012): 519-530 and papers referenced from it.

**Comment by lsy0509** [comment]
Thank you so much for your help.
