### ISSUE TITLE
 install error FLTK_LIBRARY notfound

### ISSUE THREAD

**Issue by RiceOwlXinTan** [3dem/relion#876]
I am stuck in the installation, where everything seems to go right except for the FLTK library. I installed the fltk library according to their official website: https://www.linuxfromscratch.org/blfs/view/svn/x/fltk.html. However, I still cannot resolve the following error:

![Screenshot 2022-05-10 205822](https://user-images.githubusercontent.com/36173011/167753578-79ffb412-6a1b-4902-87ea-7579111fac63.png)

Is it possible that you could share some resources on how to address the issue? Thanks!

**Comment by biochem-fan** [comment]
You don't have to manually install FLTK.

Delete your build directory and run `cmake` with `-DFORCE_OWN_FLTK=ON`.

**Comment by biochem-fan** [comment]
Why is your working directory `/mnt/c`?

Are you working on Windows Subsystem for Linux (WSL)? This is not impossible but tricky. If are you are very familiar with Linux, I don't recommend this.

Check your `cmake` log to see which compiler it is using. Aren't you using a compiler from conda which doesn't search the system's include path?

**Comment by RiceOwlXinTan** [comment]
Hi, I tried to install it without GUI, and it worked but was very inconvenient. I then checked many times, and find the libx11-dev is indeed installed. I added the path to PATH. However, the issue still exists. Do you think I may need to add some path to some variables other than PATH?
![image](https://user-images.githubusercontent.com/36173011/169568041-30b1b36a-075a-478d-aa4c-e7b13ba7bea2.png)

**Comment by biochem-fan** [comment]
You didn't answer my previous comments and work within the conda environment.

**Comment by scheres** [comment]
This is a site-specific installation issue. Better use ccp-em mailing list.
