### ISSUE TITLE
Error in submiting job to Slurm

### ISSUE THREAD

**Issue by doug-oneal-nih** [3dem/relion#877]
Environment:
```
CentOS 7.9
Slurm 21.08
MPI 3.1.0 (Intel Parallel Studio 2020.2.109)
Memory 768GB
GPU P100 or V100
```

Dataset: N/A

relion_sbatch.sh submit script
```
#!/bin/bash

#SBATCH --ntasks=XXXmpinodesXXX
#SBATCH --partition=XXXqueueXXX
#SBATCH --cpus-per-task=XXXthreadsXXX
#SBATCH --error=XXXerrfileXXX
#SBATCH --output=XXXoutfileXXX
#SBATCH --open-mode=append
#SBATCH --time=XXXextra1XXX
#SBATCH --mem-per-cpu=XXXextra2XXX
#SBATCH --gres=XXXextra3XXX
#SBATCH --no-requeue
#SBATCH XXXextra4XXX
#SBATCH XXXextra5XXX
#SBATCH XXXextra6XXX

#module load intel_parallel/parallel_studio_2020.2.109
module load relion/3.1.3

export MV2_DEFAULT_TIME_OUT=180
export FI_PROVIDER=sockets
export I_MPI_HYDRA_TOPOLIB=ipl

if [ XXXmpinodesXXX -eq 1 ]; then
  time -p XXXcommandXXX
else
  time -p mpirun XXXcommandXXX
fi
```

The job options is the issue. In cases where a GPU is not requested, the token XXXextra3XXX is empty. This results in the line `#SBATCH --gres=` in the script submitted to slurm. In versions of slurm prior to 21.08 the scheduler would ignore this line. With 21.08 (the currently supported version), the scheduler throws the error
`sbatch: error: Batch job submission failed: Invalid Trackable RESource (TRES) specification
`
and the job is rejected. There is no option within the template to conditionally not insert directives. Current workaround is to have a modified submit script template that will be used when the end user knows that GPUs will not be allocated.

**Comment by biochem-fan** [comment]
Cannot you use `--gres=gpu:0`?

> Current workaround is to have a modified submit script template that will be used when the end user knows that GPUs will not be allocated.

I would do this.

**Comment by doug-oneal-nih** [comment]
I will pass this information back to the four researchers in NCI who have brought this issue to me.

Dr. Douglas O'Neal (contractor)
Manager, HPC Systems Administration Group, ITOG
Frederick National Laboratory for Cancer Research
Leidos Biomedical Research, Inc.
Phone: 301-228-4656
Email: ***@***.******@***.***%3e>

From: biochem_fan ***@***.***>
Sent: Wednesday, May 11, 2022 7:40 PM
To: 3dem/relion ***@***.***>
Cc: O'Neal, Doug (NIH/NCI) [C] ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [3dem/relion] Error in submiting job to Slurm (Issue #877)


Cannot you use --gres=gpu:0?

Current workaround is to have a modified submit script template that will be used when the end user knows that GPUs will not be allocated.

I would do this.

-
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2F3dem%2Frelion%2Fissues%2F877%23issuecomment-1124386314&data=05%7C01%7Cdouglas.o%27neal%40nih.gov%7C6094f0ce7b5243e79c8708da33a7937f%7C14b77578977342d58507251ca2dc2b06%7C0%7C0%7C637879092086781808%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=lG5sCXk4vPHQKunIzdEUh5kMOd04X0SIkoCKMvtLPSo%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FATQHMK2KERMVAFPMLQ5DHOLVJRANDANCNFSM5VVIN7ZA&data=05%7C01%7Cdouglas.o%27neal%40nih.gov%7C6094f0ce7b5243e79c8708da33a7937f%7C14b77578977342d58507251ca2dc2b06%7C0%7C0%7C637879092086781808%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=q%2FGTZMtQ5jyJssz%2BW2I0zjg4erNwcRJ6Yr%2Bq13FGHfo%3D&reserved=0>.
You are receiving this because you authored the thread.Message ID: ***@***.******@***.***>>
CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and are confident the content is safe.
