### ISSUE TITLE
Convert EER to Tif

### ISSUE THREAD

**Issue by klmcguire** [3dem/relion#880]
I am using the relion_convert_to_tiff command to convert our EERs to Tiffs.  However, it doesn't convert all of the EER files in my directory. It starts with the first, converts it, and then it's done.  How do I get this command to convert all of the files?  The names of the EER files are not straight forward in terms of patterns, so simple for loop would not work.

**Comment by biochem-fan** [comment]
`relion_convert_to_tiff` accepts in the `--i` option:

- a **single** movie file
- a movie STAR file
- a simple text file with file names

In other words, you cannot say `-i *.eer`. Instead, use:

```bash
find . -name '*.eer' > movies.lst
relion_convert_to_tiff --i movies.lst # ... other options
```

**Comment by klmcguire** [comment]
> `relion_convert_to_tiff` accepts in the `--i` option:
> 
> * a **single** movie file
> * a movie STAR file
> * a simple text file with file names
> 
> In other words, you cannot say `-i *.eer`. Instead, use:
> 
> ```shell
> find . -name '*.eer' > movies.lst
> relion_convert_to_tiff --i movies.lst # ... other options
> ```

Awesome! Thanks biochem-fan, works perfect.
