### ISSUE TITLE
Vertical White Line After Relion Convert to Tiff from EER

### ISSUE THREAD

**Issue by klmcguire** [3dem/relion#881]
I use relion_convert_to_tiff to convert my EER files to TIFF.  The only issue we are seeing is a consistent vertical white line of pixels in all of the TIFFs.  The line is not there in the EERs.  Has anyone seen this before, and is there a solution to the problem? Thanks!

**Comment by biochem-fan** [comment]
> consistent vertical white line of pixels in all of the TIFFs

Are you inspecting individual frames or aligned and summed images after motion correction from TIFF?
Are you using RELION's motion correction or UCSF MotionCor2?
Did you use the gain reference written by `relion_convert_to_tiff`?

These lines are defective pixels. They are present in the original EER files as well but concealed during motion correction.
I don't know why this concealment did not work automatically in TIFF.
You can make a defect list file by manually entering the coordinates, though.

**Comment by klmcguire** [comment]
> > consistent vertical white line of pixels in all of the TIFFs
> 
> Are you inspecting individual frames or aligned and summed images after motion correction from TIFF? Are you using RELION's motion correction or UCSF MotionCor2? Did you use the gain reference written by `relion_convert_to_tiff`?
> 
> These lines are defective pixels. They are present in the original EER files as well but concealed during motion correction. I don't know why this concealment did not work automatically in TIFF. You can make a defect list file by manually entering the coordinates, though.

These are the raw images, not aligned or summed nor motion corrected yet. This line shows up right after using the relion convert command.  It is there before I use the gain for any corrections, and it's still there after I use it for corrections.

What do you think is creating the defective pixels?  This is a brand new microscope.

**Comment by biochem-fan** [comment]
> This line shows up right after using the relion convert command.

How did you confirm the original EER file does not have the lines?
How did you view it?

> What do you think is creating the defective pixels? This is a brand new microscope.

Most Falcon cameras have one or two defective lines. This is within their spec.

**Comment by klmcguire** [comment]
> > This line shows up right after using the relion convert command.
> 
> How did you confirm the original EER file does not have the lines? How did you view it?
> 
> > What do you think is creating the defective pixels? This is a brand new microscope.
> 
> Most Falcon cameras have one or two defective lines. This is within their spec.

While we were collecting, we imported on the fly in to Cryosparc Live and we don't see that line.

Good to know about the Falcon cameras, thanks.

**Comment by biochem-fan** [comment]
> While we were collecting, we imported on the fly in to Cryosparc Live and we don't see that line.

Then you are not comparing consistently.

You are looking at raw, uncorrected frames for TIFF, while you are looking at motion corrected, aligned and defect-patched frames for EER.

**Comment by klmcguire** [comment]
> > While we were collecting, we imported on the fly in to Cryosparc Live and we don't see that line.
> 
> Then you are not comparing consistently.
> 
> You are looking at raw, uncorrected frames for TIFF, while you are looking at motion corrected, aligned and defect-patched frames for EER.

Right, of course. But when I import the EERs into Cryosparc (not Live) using the import job, the line is still not there.  That's before I run any correction.

**Comment by klmcguire** [comment]
> I don't know what CryoSPARC is showing.
> 
> Please compare (1) raw TIFF frames and (2) raw EER frames (fractionated in the same way as TIFF) _without any correction_ (e.g. using ImageJ or IMOD). If only 1 shows the defects, it is a problem in `relion_convert_to_tiff` and I will investigate.

Ok, I'll give that a try.

**Comment by biochem-fan** [comment]
> The TIFFs open but are mostly black with some sporadic grey pixels.

Of course, because each frame contains very small numbers of electrons.

The latest version of IMOD supports EER and TIFF. Sum all frames _without_ alignment and gain correction, because you are interested in the fixed pattern defect on the detector. Study the `IMOD_READ_EER_Z_SUMMING` option in the document.

**Comment by klmcguire** [comment]
> > The TIFFs open but are mostly black with some sporadic grey pixels.
> 
> Of course, because each frame contains very small numbers of electrons.
> 
> The latest version of IMOD supports EER and TIFF. Sum all frames _without_ alignment and gain correction, because you are interested in the fixed pattern defect on the detector. Study the `IMOD_READ_EER_Z_SUMMING` option in the document.

Ok great, I'll look at that.
