### ISSUE TITLE
relion can't open display

### ISSUE THREAD

**Issue by RiceOwlXinTan** [3dem/relion#882]
After the installation is complete on a server, the relion cannot open with a GUI, which is specified as ON during installation. Is there any resources to look into this issue?

![image](https://user-images.githubusercontent.com/36173011/169605905-4dec051b-2a63-4ba8-9f06-b9fd65b27d9a.png)

**Comment by biochem-fan** [comment]
You didn't set up X11 forwarding. Use `ssh -Y` or something appropriate.
This is a basic Linux question and this forum is not for it.
