### ISSUE TITLE
mpi error in refinement

### ISSUE THREAD

**Issue by RiceOwlXinTan** [3dem/relion#884]
Hi,  
I am currently in the phase of refinement, but it shows the following MPI error:

![image](https://user-images.githubusercontent.com/36173011/170392262-b82982f9-b690-42d3-b8a1-aabd2b22b203.png)

The open mpi is in the following path: 
![image](https://user-images.githubusercontent.com/36173011/170392377-1b43aac3-49c0-454c-80c3-50ac55d504b3.png)
In the cmake command, the mpi path is 
![image](https://user-images.githubusercontent.com/36173011/170392386-3cd03c28-6f64-45e2-b224-8dc278974d66.png)

So, it seems that the mpi in the installation is the same mpi in the computer. Where do you think might be the problem?

**Comment by biochem-fan** [comment]
Please show full error messages from RELION. **DO NOT USE** screenshots!

**Comment by RiceOwlXinTan** [comment]
Thanks. I am wondering how I can copy error messages from RELION? On my PC,
it doesn't seem to support copying or screwing up or down these 2 little
windows.

**Comment by biochem-fan** [comment]
Double click it.

**Comment by RiceOwlXinTan** [comment]
Thanks!

[owls.stat.rice.edu:106232] PMIX ERROR: UNPACK-PAST-END in file unpack.c at
line 205
[owls.stat.rice.edu:106232] PMIX ERROR: UNPACK-PAST-END in file unpack.c at
line 146
[owls.stat.rice.edu:106232] PMIX ERROR: UNPACK-PAST-END in file
client/pmix_client.c at line 231
[owls.stat.rice.edu:106232] OPAL ERROR: Error in file pmix3x_client.c at
line 112
[owls.stat.rice.edu:106231] PMIX ERROR: UNPACK-PAST-END in file unpack.c at
line 205
[owls.stat.rice.edu:106231] PMIX ERROR: UNPACK-PAST-END in file unpack.c at
line 146
[owls.stat.rice.edu:106231] PMIX ERROR: UNPACK-PAST-END in file
client/pmix_client.c at line 231
[owls.stat.rice.edu:106231] OPAL ERROR: Error in file pmix3x_client.c at
line 112
*** An error occurred in MPI_Init
*** on a NULL communicator
*** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
***    and potentially your MPI job)
[owls.stat.rice.edu:106232] Local abort before MPI_INIT completed completed
successfully, but am not able to aggregate error messages, and not able to
guarantee that all other processes were killed!
*** An error occurred in MPI_Init
*** on a NULL communicator
*** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
***    and potentially your MPI job)
[owls.stat.rice.edu:106231] Local abort before MPI_INIT completed completed
successfully, but am not able to aggregate error messages, and not able to
guarantee that all other processes were killed!

**Comment by RiceOwlXinTan** [comment]
Hi,It shows the following:
(base) bash-4.2$ which mpirun
/opt2/software/ompi/4.0.3/bin/mpirun

**Comment by biochem-fan** [comment]
Are you running this locally, or submitting this to a cluster? In the latter case, are you sure the same OpenMPI is used on the cluster's worker node?

Can you run other MPI programs (e.g. Class2D, AutoPick)?

**Comment by RiceOwlXinTan** [comment]
Yeah. I am submitting to the cluster, and other mpi programs won't work
either if I specified MPI.
How can I make the entire cluster use the same OpenMPI? I just used module
load ompi to select the version.

**Comment by biochem-fan** [comment]
This is cluster specific and I cannot help. This is not really a RELION problem. Can you ask people in the same institute (e.g. IT manager)?

**Comment by biochem-fan** [comment]
Prepend `mpirun -n X` where X is the number of processes.
