### ISSUE TITLE
Import Particle Coordinates into Relion 4

### ISSUE THREAD

**Issue by RobSaintLoup** [3dem/relion#890]
Hi everybody,

I have a project where I want to use CryoSPARC and Relion 4 on the same micrographes. That is why for Relion I created a subfolder with symbolic links to the micrographes. I managed to work on them untill 2D classification. Since I hadn't any good classes I decided to import the particle coordinates from CryoSPARC and reextract in Relion.  I used cryosparc2star --swapxy to create the star file and modified it so that it points to the symbolic links in the relion project directory. I further tried to make it ressemble a star file that relion would normally use for an extrection job. I stored it in the relion directory in a directory that i named: Autopick/Cryosparc. The first lines of the document are:

```
data_optics

loop_

_rlnVoltage #1 
_rlnSphericalAberration #2 
_rlnAmplitudeContrast #3 
_rlnOpticsGroup #4
_rlnImagePixelSize #5
_rlnImageDimensionality #6 
_rlnOpticsGroupName #7 
_rlnMtfFileName #8
_rlnMicrographPixelSize #9 
_rlnMicrographOriginalPixelSize #10
300.000000 2.700000 0.100000 1 0.84 2 opticsGroup1 MTF_K3.star 0.840000 0.840000

data_particles

loop_

_rlnMicrographName #1 
_rlnCoordinateX #2 
_rlnCoordinateY #3  
_rlnAutopickFigureOfMerit #4 
_rlnClassNumber #5 
_rlnAnglePsi #6
Movies/grid5/GridSquare_8572820_Data_FoilHole_8636125_Data_8578080_8578082_20220309_232859_fractions_aligned_mic_DW.mrc 2996 3059 3 0 0.0
```

(note : I added dummy values for _rlnAutopickFigureOfMerit #4,  _rlnClassNumber #5, and _rlnAnglePsi #6 )

When I try to use this star file as an imput to an extraction job Relion extracts 0 particles. 

`Joining metadata of all particles from 6613 micrographs in one STAR file...
 The pixel size of the extracted particles in optics group 1 is 0.84 Angstrom/pixel.
 Written out STAR file with 0 particles in Extract/job053/particles.star
 Done preprocessing!`

When I try to use the import particle coordinates job I only get the error:

`ERROR: 
Import: Cannot write file: Import/job052/coords_suffixAutoPick/Cryosparc/P362_J11_particles_exported.star`

I hope someone can give me a hint or help me in any way.

**Comment by biochem-fan** [comment]
Hi, this is not a bug report but a usage question. Please ask in the CCPEM mailing list.
