### ISSUE TITLE
a bug in relion-3.1.3/src/acc/cuda/cuda_kernels/helper.cuh:932    & has lower precedence than !=; != will be evaluated first

### ISSUE THREAD

**Issue by baichenhan** [3dem/relion#894]
if((x ^ y ^ z)&1 != 0)
{
	img_in[pixel].x *= -1;
	img_in[pixel].y *= -1;
}
(the same as ver4.0)

I don`t know why use " if((x ^ y ^ z)&1 != 0)", maybe it just like "if((x ^ y ^ z)& 1)", Is it a mistake or something I can`t understand?

**Comment by biochem-fan** [comment]
Thank you very much for pointing this out. Fortunately this is harmless (see https://github.com/3dem/relion/issues/637) but I will fix this in version 4.0.

**Comment by biochem-fan** [comment]
Fixed in 44c8b38.
