### ISSUE TITLE
Building with CMake newer than 3.9.6 does not work

### ISSUE THREAD

**Issue by clil16** [3dem/relion#906]
Using a CMake version greater than CMake v3.9.6 results in an error.  My guess is that it has to do with the changes made to the FindMPI module when CMake version 3.10.0 was released.  I can confirm the issue is present in version 3.10.0, 3.18.2, and 3.22.2 of CMake.

To clarify:
CMake 3.9.6 - works
CMake 3.10.0 - does not work
CMake 3.18.2 - does not work
CMake 3.22.2 - does not work

**Environment:**
 - OS: Red Hat Enterprise Linux release 8.4
 - Compiler: Intel Compiler 2021.5.0 20211109
 - MPI runtime: OpenMPI 4.1.4
 - RELION version: RELION ver4.0 branch commit 2dffb8415a7e09f14532668b06e353fad1c46b2a
 - CMake version: 3.10.0+
 - Memory: 196 GB
 - GPU: None

**CMake command:**
 - Full command:
   ```
   cmake -DCMAKE_C_COMPILER=mpicc -DCMAKE_CXX_COMPILER=mpicxx -DALTCPU=ON -DMKLFFT=ON -DGUI=ON -DCUDA=OFF -DCudaTexture=OFF -DFORCE_OWN_FLTK=ON -DCMAKE_C_FLAGS="-O3 -ip -g -xCOMMON-AVX512 -restrict" -DCMAKE_CXX_FLAGS="-O3 -ip -g -xCOMMON-AVX512 -restrict" -DCMAKE_BUILD_TYPE=Release -DTIFF_INCLUDE_DIR=/sw/pkgs/coe/o/image-libraries/220318/include -DTIFF_LIBRARY=/sw/pkgs/coe/o/image-libraries/220318/lib/libtiff.so -DPNG_INCLUDE_DIR=/sw/pkgs/coe/o/image-libraries/220318/include -DPNG_PNG_INCLUDE_DIR=/sw/pkgs/coe/o/image-libraries/220318/include -DPNG_LIBRARY=/sw/pkgs/coe/o/image-libraries/220318/lib/libpng16.so -DJPEG_INCLUDE_DIR=/sw/pkgs/coe/o/image-libraries/220318/include -DJPEG_LIBRARY_RELEASE=/sw/pkgs/coe/o/image-libraries/220318/lib/libjpeg.so -DCMAKE_INSTALL_PREFIX=/sw/pkgs/lsi/relion-cpu/4.0 ..
   ```

**Error message:**

```
-- The C compiler identification is Intel 20.2.5.20211109
-- The CXX compiler identification is Intel 20.2.5.20211109
-- Check for working C compiler: /sw/pkgs/arc/stacks/intel/2022.1.2/openmpi/4.1.4/bin/mpicc
-- Check for working C compiler: /sw/pkgs/arc/stacks/intel/2022.1.2/openmpi/4.1.4/bin/mpicc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /sw/pkgs/arc/stacks/intel/2022.1.2/openmpi/4.1.4/bin/mpicxx
-- Check for working CXX compiler: /sw/pkgs/arc/stacks/intel/2022.1.2/openmpi/4.1.4/bin/mpicxx -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- BUILD TYPE set to 'Release'
-- Setting fallback CUDA_ARCH=50
-- ALTCPU enabled - Building CPU-accelerated version of RELION
-- Setting cpu precision to double
-- Setting accelerated code precision to single
-- Using non-cuda compilation....
-- Found TBB: /sw/pkgs/arc/intel/2022.1.2/tbb/2021.5.1/include (found version "2021.5")  
-- TBB_FOUND :        TRUE
-- TBB_INCLUDE_DIRS : /sw/pkgs/arc/intel/2022.1.2/tbb/2021.5.1/include
-- TBB_VERSION :      2021.5
-- TBB_LIBRARIES :    /sw/pkgs/arc/intel/2022.1.2/tbb/2021.5.1/lib/intel64/gcc4.8/libtbb.so
-- Found MPI_C: /sw/pkgs/arc/stacks/intel/2022.1.2/openmpi/4.1.4/bin/mpicc (found version "3.1") 
-- Found MPI_CXX: /sw/pkgs/arc/stacks/intel/2022.1.2/openmpi/4.1.4/bin/mpicxx (found version "3.1") 
-- Found MPI: TRUE (found version "3.1")  
CMake Error at CMakeLists.txt:216 (include_directories):
  include_directories given empty-string as include directory.


-- MPI_INCLUDE_PATH : 
-- MPI_LIBRARIES : 
-- MPI_CXX_INCLUDE_PATH : 
-- MPI_CXX_LIBRARIES : 
-- CMAKE_C_COMPILER : /sw/pkgs/arc/stacks/intel/2022.1.2/openmpi/4.1.4/bin/mpicc
-- CMAKE_CXX_COMPILER : /sw/pkgs/arc/stacks/intel/2022.1.2/openmpi/4.1.4/bin/mpicxx
-- MPI_C_COMPILER : /sw/pkgs/arc/stacks/intel/2022.1.2/openmpi/4.1.4/bin/mpicc
-- MPI_CXX_COMPILER : /sw/pkgs/arc/stacks/intel/2022.1.2/openmpi/4.1.4/bin/mpicxx
-- CMAKE_CXX_COMPILER_ID : Intel
-- MKL FFTW wrapper header files: /sw/pkgs/arc/intel/2022.1.2/mkl/2022.0.2/include/fftw
-- Texture interpolation is omitted.
-- Looking for XOpenDisplay in /usr/lib64/libX11.so;/usr/lib64/libXext.so
-- Looking for XOpenDisplay in /usr/lib64/libX11.so;/usr/lib64/libXext.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Looking for IceConnectionNumber in ICE
-- Looking for IceConnectionNumber in ICE - found
-- Found X11: /usr/lib64/libX11.so
-- --------------------------------------------------------
-- -------- NO EXISTING FLTK LIBRARIES WHERE FOUND. -------
-- -------------- FLTK WILL BE DOWNLOADED AND -------------
-- --------------- BUILT DURING COMPILE-TIME. -------------
-- --------------------------------------------------------
-- ---- A WORKING INTERNET CONNECTION WILL BE REQUIRED. ---
-- --------------------------------------------------------
-- no previous fltk found, the following paths are set for libs/headers TO BE built
-- FLTK_INCLUDE_DIR: /tmp/liliensw/relion-cpu/external/fltk/include
-- FLTK_LIBRARIES:   /tmp/liliensw/relion-cpu/external/fltk/lib/libfltk.so
-- Looking for sincos
-- Looking for sincos - found
-- Looking for __sincos
-- Looking for __sincos - not found
-- Found TIFF: /sw/pkgs/coe/o/image-libraries/220318/lib/libtiff.so (found version "4.3.0") 
-- Found ZLIB: /usr/lib64/libz.so (found version "1.2.11") 
-- Found PNG: /sw/pkgs/coe/o/image-libraries/220318/lib/libpng16.so (found version "1.6.37") 
-- Checking class ranker model file...
-- --------------------------------------------------------
-- --------- FOUND NO LOCAL COPY OF TORCH MODELS. ---------
-- ------- WILL BE DOWNLOADED DURING COMPILE-TIME. --------
-- --------------------------------------------------------
-- ---- A WORKING INTERNET CONNECTION WILL BE REQUIRED. ---
-- -- TO SKIP, RECONFIGURE WITH -DFETCH_TORCH_MODELS=OFF --
-- --------------------------------------------------------
BUILD_SHARED_LIBS = OFF
-- Building static libs (larger build size and binaries)
Running apps/CMakeLists.txt...
-- CMAKE_BINARY_DIR:/tmp/liliensw/relion-cpu/build-cmake-3.10.0
-- Git commit ID: 2dffb8415a7e09f14532668b06e353fad1c46b2a
PNG FOUND
-- Found JPEG: /usr/lib64/libjpeg.so  
JPEG FOUND
-- Found OpenMP_C: -qopenmp (found version "5.0") 
-- Found OpenMP_CXX: -qopenmp (found version "5.0") 
-- Found OpenMP: TRUE (found version "5.0")  
-- Configuring incomplete, errors occurred!
See also "/tmp/liliensw/relion-cpu/build-cmake-3.10.0/CMakeFiles/CMakeOutput.log".
See also "/tmp/liliensw/relion-cpu/build-cmake-3.10.0/CMakeFiles/CMakeError.log".
```

I am attaching the CMakeCache.txt, CMakeOutput.log, and CMakeError.log files for your reference.  These were generated using CMake 3.10.0.

[CMakeCache.txt](https://github.com/3dem/relion/files/9396342/CMakeCache.txt)
[CMakeOutput.log](https://github.com/3dem/relion/files/9396343/CMakeOutput.log)
[CMakeError.log](https://github.com/3dem/relion/files/9396345/CMakeError.log)

**Comment by biochem-fan** [comment]
Interesting. I am using CMake version 3.16.3, gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0, mpirun (Open MPI) 4.0.3 without problems.

I don't know why all these variables are empty.

> -- MPI_INCLUDE_PATH : 
> -- MPI_LIBRARIES : 
> -- MPI_CXX_INCLUDE_PATH : 
> -- MPI_CXX_LIBRARIES : 

Do you know what are "the changes made to the FindMPI module"?

Does it help to comment out line 216 of `CMakeLists.txt`?

**Comment by do-jason** [comment]
Could you test by replacing the below

https://github.com/3dem/relion/blob/2dffb8415a7e09f14532668b06e353fad1c46b2a/CMakeLists.txt#L215-L219

as

```cmake
if ("${MPI_CXX_INCLUDE_DIRS}" STREQUAL "")
    if (NOT "${MPI_CXX_INCLUDE_PATH}" STREQUAL "")
        include_directories("${MPI_CXX_INCLUDE_PATH}")
    endif()
else()
    include_directories("${MPI_CXX_INCLUDE_DIRS}")
endif()

```

**Comment by clil16** [comment]
> Interesting. I am using CMake version 3.16.3, gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0, mpirun (Open MPI) 4.0.3 without problems.

Interesting.  I just tried it with GCC 10.3.0, OpenMPI 4.1.4, and CMake 3.10.0 and received the same message as before.

> Do you know what are "the changes made to the FindMPI module"?

The release notes for CMake 3.10.0 contains a blurb about the FindMPI module being updated and improved but nothing noting a compatibility break.  https://cmake.org/cmake/help/v3.10/release/3.10.html

I did find this issue and subsequent discussion about some of the changes:  https://gitlab.kitware.com/cmake/cmake/-/issues/17538

> Does it help to comment out line 216 of `CMakeLists.txt`?

When I comment out line 216 of `CMakeLists.txt` it doesn't throw an error but those variables are still empty.
```
...
-- Found MPI_C: /sw/pkgs/arc/stacks/intel/2022.1.2/openmpi/4.1.4/bin/mpicc (found version "3.1")
-- Found MPI_CXX: /sw/pkgs/arc/stacks/intel/2022.1.2/openmpi/4.1.4/bin/mpicxx (found version "3.1")
-- Found MPI: TRUE (found version "3.1")  
-- MPI_INCLUDE_PATH : 
-- MPI_LIBRARIES : 
-- MPI_CXX_INCLUDE_PATH : 
-- MPI_CXX_LIBRARIES : 
...
```

Interestingly, the make step succeeded and `relion_refine_mpi` looks to be linked correctly to libmpi.so.40 but I haven't tried running it yet.




> Could you test by replacing the below
> 
> https://github.com/3dem/relion/blob/2dffb8415a7e09f14532668b06e353fad1c46b2a/CMakeLists.txt#L215-L219
> 
> as
> 
> ```cmake
> if ("${MPI_CXX_INCLUDE_DIRS}" STREQUAL "")
>     if (NOT "${MPI_CXX_INCLUDE_PATH}" STREQUAL "")
>         include_directories("${MPI_CXX_INCLUDE_PATH}")
>     endif()
> else()
>     include_directories("${MPI_CXX_INCLUDE_DIRS}")
> endif()
> ```

Once I did the patch it no longer threw an error during the cmake step but the varibales are still empty.
```
...
-- Found MPI_C: /sw/pkgs/arc/stacks/intel/2022.1.2/openmpi/4.1.4/bin/mpicc (found version "3.1")
-- Found MPI_CXX: /sw/pkgs/arc/stacks/intel/2022.1.2/openmpi/4.1.4/bin/mpicxx (found version "3.1")
-- Found MPI: TRUE (found version "3.1")  
-- MPI_INCLUDE_PATH : 
-- MPI_LIBRARIES : 
-- MPI_CXX_INCLUDE_PATH : 
-- MPI_CXX_LIBRARIES : 
...
```

As before, the make step succeeded and `relion_refine_mpi` looks to be linked correctly to libmpi.so.40 but I haven't tried running it yet.

I suppose it may be a non-issue but the printing of empty variables is odd.  I can provide whatever logs or Makefiles you may want.

**Comment by biochem-fan** [comment]
Perhaps your environment does not need any special paths to link OpenMPI. This is why the build succeeds with empty variables. I don't know how common this is but let's incorporate @do-jason's patch.

@do-jason: can you make a pull request to the `ver3.1` branch of `relion-devel`? The commit will be propagated to ver 4.0 and 4.1 (unreleased) as well.

**Comment by do-jason** [comment]
@biochem-fan Will do soon. I think it has almost no harm for existing configuration and just checks if $MPI_CXX_INCLUDE_PATH is empty as well.

**Comment by biochem-fan** [comment]
Thank you very much. Your pull request was directed to `master` on `relion-devel`, which is 4.0, so I cherry-picked the patch to `ver3.1` as well.
