### ISSUE TITLE
MlOptimiserMpi::reconstructUnregularisedMapAndCalculateSolventCorrectedFSC without disk I/O

### ISSUE THREAD

**Issue by do-jason** [3dem/relion#908]
During other workload test, I've found that MlOptimiserMpi::reconstructUnregularisedMapAndCalculateSolventCorrectedFSC function is doing data exchange with file read/write even if "--dont_combine_weights_via_disc" is set.
If this function also check "--dont_combine_weights_via_disc" flag and have capability of data transfer without file I/O, then it will improve performance and scalability.

**Comment by biochem-fan** [comment]
Do you mean `run_itXXX_halfY_unfil.mrc`? These files are used later in some cases, so worth writing out.

**Comment by do-jason** [comment]
@biochem-fan I see. Is it only necessary for the last iteration? or for all iterations?

**Comment by biochem-fan** [comment]
For most jobs, only for the last iteration. But when something goes wrong, looking at these files from earlier iterations often helps. Is this such a big bottleneck? In most (realistic) runs, E steps take much longer than M steps.

**Comment by do-jason** [comment]
Okay, understood. It was just idea when I found this. And it looks like it must be as is.
