### ISSUE TITLE
Add a RELION_PYTHON_EXECUTABLE configuration variable to RELION-4

### ISSUE THREAD

**Issue by Guillawme** [3dem/relion#910]
Hello,

Python is a mess, not your fault... here is a problem I have been running into, and a proposed solution (maybe not optimal though, so let's discuss it).

I set up my RELION environment so that it also brings the conda env containing topaz in scope, so I can use topaz from within RELION. This is working great, and it is so convenient to have topaz available directly in RELION. :+1:

Then I tried to use the class ranker. I learned from [a recent discussion on CCPEM](https://www.jiscmail.ac.uk/cgi-bin/wa-jisc.exe?A2=CCPEM;f07ae656.2207) that it is known to work with specific versions of Python and Pytorch. I went with the suggestions from this message, and created a dedicated conda env for the Python and Pytorch versions known to work with the class ranker, because I didn't want to mess up my topaz environment (I also want to be able to upgrade topaz without breaking the class ranker).

But now there's a problem: I need two different conda envs for different functionalities in RELION, but if I bring them both in scope when loading the RELION environment, one will take precedence over the other. My current solution is to remember to go through the following ceremony when I want to use the class ranker after I used topaz:

1. quit RELION
2. unload the RELION env
3. edit some configuration to switch which conda env is brought into scope with RELION
4. load the RELION env
5. restart RELION
6. where was I in my analysis? 😕 

Hence this suggestion: with an environment variable `RELION_PYTHON_EXECUTABLE` (named after similar ones for CTFFIND et al), one could point RELION to the Python version that will work with the class ranker, while otherwise having the topaz environment active. Or is this going to break with e.g. the Python from the class-ranker conda env trying to use the libraries installed in the topaz env?

Another solution would be to keep the class ranker script compatible with the same versions of Python and Pytorch used by topaz, but I don't know how feasible this is since it is exactly the problem that isolated environments are meant to solve.

**Comment by biochem-fan** [comment]
We use a wrapper to Topaz, which activates its own conda environment.

```
#!/bin/bash

source /home1/software/packages/miniconda3/etc/profile.d/conda.sh
conda activate topaz
topaz $@
```

This wrapper is specified in `RELION_TOPAZ_EXECUTABLE`.

**Comment by Guillawme** [comment]
Thank you, this is a much easier solution!
