### ISSUE TITLE
Relion / Slurm Issue

### ISSUE THREAD

**Issue by JuergenUniVie** [3dem/relion#923]
Dear all,

I'm not sure if it's a RELION or a SLURM problem, but maybe someone has some advice for me.
I have the following SLURM submit script created from RELION:

#!/bin/tcsh
#SBATCH --job-name=Relion4Job
#SBATCH --nodes=1
#SBATCH --ntasks=XXXmpinodesXXX
#SBATCH --gres=gpu:XXXextra1XXX
#SBATCH --cpus-per-task=XXXthreadsXXX
#SBATCH --mem-per-cpu=XXXextra2XXX
#SBATCH --partition=XXXqueueXXX
#SBATCH --output=XXXoutfileXXX
#SBATCH --error=XXXerrfileXXX

module purge
module load RELION

srun --mpi=pmi2 XXXcommandXXX

The script works the same way, but the --output and --error data are not written as run.out and err.out but in the "root directory" as submission.script-oJOBID and submission.script-eJOBID.

I have no more ideas. Without RELION it works with every submitjob.

Thanks in advance,
all the best.
Juergen

**Comment by biochem-fan** [comment]
@JuergenUniVie 

If you managed to solve the issue yourself, please post the solution so that others can learn.
