### ISSUE TITLE
Relion 4.0 - build problem - CXX object - jaz/tomography/fidcucials.cpp

### ISSUE THREAD

**Issue by drawoliver** [3dem/relion#925]
This is a template for reporting bugs. Please fill in as much information as you can.

**Compilation problem, Relion 4**

I appear to be having problems building the latest source code (git pull, v 4.0)
I am using CXX from a separate standalone openmpi installation configured with the -DMPI_CXX_COMPILER switch, and have not had any problems issues until now.  I have tried several different openmpi versions (2.16, 3.15, 4.02) but encounter the same problem; I have used 2.16 successfully for several previous builds on different machines.
I would be appreciative of any help / assistance.

Antony.

[ 21%] Building CXX object src/apps/CMakeFiles/relion_lib.dir/__/jaz/tomography/fiducials.cpp.o
/usr/local/git_repository/relion-4.0/src/jaz/tomography/local_particle_refinement.cpp: In member function ‘double LocalParticleRefinement::f(const std::vector<double>&, void*) const’:
/usr/local/git_repository/relion-4.0/src/jaz/tomography/local_particle_refinement.cpp:138:17: error: ‘isnan’ was not declared in this scope
   if (isnan(x[i])) return std::numeric_limits<double>::max();
                 ^
/usr/local/git_repository/relion-4.0/src/jaz/tomography/local_particle_refinement.cpp:138:17: note: suggested alternative:
In file included from /usr/local/git_repository/relion-4.0/src/funcs.h:50:0,
                 from /usr/local/git_repository/relion-4.0/src/metadata_table.h:43,
                 from /usr/local/git_repository/relion-4.0/src/jaz/tomography/particle_set.h:4,
                 from /usr/local/git_repository/relion-4.0/src/jaz/tomography/local_particle_refinement.h:5,
                 from /usr/local/git_repository/relion-4.0/src/jaz/tomography/local_particle_refinement.cpp:1:
/usr/include/c++/5/cmath:641:5: note:   ‘std::isnan’
     isnan(_Tp __x)
     ^
/usr/local/git_repository/relion-4.0/src/jaz/tomography/local_particle_refinement.cpp: In member function ‘void LocalParticleRefinement::grad(const std::vector<double>&, std::vector<double>&, void*) const’:
/usr/local/git_repository/relion-4.0/src/jaz/tomography/local_particle_refinement.cpp:225:17: error: ‘isnan’ was not declared in this scope
   if (isnan(x[i])) return;
                 ^
/usr/local/git_repository/relion-4.0/src/jaz/tomography/local_particle_refinement.cpp:225:17: note: suggested alternative:
In file included from /usr/local/git_repository/relion-4.0/src/funcs.h:50:0,
                 from /usr/local/git_repository/relion-4.0/src/metadata_table.h:43,
                 from /usr/local/git_repository/relion-4.0/src/jaz/tomography/particle_set.h:4,
                 from /usr/local/git_repository/relion-4.0/src/jaz/tomography/local_particle_refinement.h:5,
                 from /usr/local/git_repository/relion-4.0/src/jaz/tomography/local_particle_refinement.cpp:1:
/usr/include/c++/5/cmath:641:5: note:   ‘std::isnan’
     isnan(_Tp __x)
     ^
/usr/local/git_repository/relion-4.0/src/jaz/tomography/local_particle_refinement.cpp: In member function ‘virtual double LocalParticleRefinement::gradAndValue(const std::vector<double>&, std::vector<double>&) const’:
/usr/local/git_repository/relion-4.0/src/jaz/tomography/local_particle_refinement.cpp:401:17: error: ‘isnan’ was not declared in this scope
   if (isnan(x[i])) return std::numeric_limits<double>::max();
                 ^
/usr/local/git_repository/relion-4.0/src/jaz/tomography/local_particle_refinement.cpp:401:17: note: suggested alternative:
In file included from /usr/local/git_repository/relion-4.0/src/funcs.h:50:0,
                 from /usr/local/git_repository/relion-4.0/src/metadata_table.h:43,
                 from /usr/local/git_repository/relion-4.0/src/jaz/tomography/particle_set.h:4,
                 from /usr/local/git_repository/relion-4.0/src/jaz/tomography/local_particle_refinement.h:5,
                 from /usr/local/git_repository/relion-4.0/src/jaz/tomography/local_particle_refinement.cpp:1:
/usr/include/c++/5/cmath:641:5: note:   ‘std::isnan’
     isnan(_Tp __x)
     ^
src/apps/CMakeFiles/relion_lib.dir/build.make:2438: recipe for target 'src/apps/CMakeFiles/relion_lib.dir/__/jaz/tomography/local_particle_refinement.cpp.o' failed
make[2]: *** [src/apps/CMakeFiles/relion_lib.dir/__/jaz/tomography/local_particle_refinement.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:2982: recipe for target 'src/apps/CMakeFiles/relion_lib.dir/all' failed
make[1]: *** [src/apps/CMakeFiles/relion_lib.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by biochem-fan** [comment]
Which version of GCC is your OpenMPI wrapper using? Perhaps it is too old?

Anyway, a quick fix is to add `std::` before `isnan` in the offending lines.

**Comment by biochem-fan** [comment]
I pushed a fix to the `ver4.0` branch. Please confirm it.

**Comment by drawoliver** [comment]
I can confirm that the change has allow the full build process to complete using CXX in openmpi 2.16.
Many thanks for the prompt answer and for the fix.
