### ISSUE TITLE
Relion 4.0-beta-2:  Initial Model fails / crashes

### ISSUE THREAD

**Issue by drawoliver** [3dem/relion#927]
We are having some issues with getting Initial Model to run - I suspect a memory issue, but do not know how / if this can be resolved.
As other tasks using the GPUs appear to run correctly, I do not believe that it is a compute code problem per se, especially as we manage to run 10-15 cycles before the error appears.

Ubuntu 20.04.4 LTS
Nvidia driver 515.76
Cuda 11.7

4 x NVIDIA GeForce RTX 3090; compute capability = 8.6 = 86
compiled with standalone installation of openmpi-2.16 

I would be grateful for any thoughts / suggestions.
With thanks,

Antony.

RELION version: 4.0-beta-2-commit-2dffb8

ERROR: an illegal memory access was encountered in /usr/local/git_source/relion_20220817/src/acc/cuda/custom_allocator.cuh at line 175 (error-code 700)
in: /usr/local/git_source/relion_20220817/src/acc/cuda/cuda_settings.h, line 79
in: /usr/local/git_source/relion_20220817/src/acc/cuda/cuda_settings.h, line 65
ERROR:
 
A GPU-function failed to execute.
 
If this occured at the start of a run, you might have GPUs which
are incompatible with either the data or your installation of relion.
If you
 
                -> INSTALLED RELION YOURSELF: if you e.g. specified -DCUDA_ARCH=50
                   and are trying ot run on a compute 3.5 GPU (-DCUDA_ARCH=3.5),
                   this may happen.
 
                -> HAVE MULTIPLE GPUS OF DIFFERNT VERSIONS: relion needs GPUS with
                   at least compute 3.5. You may be trying to use a GPU older than
                   this. If you have multiple generations, try specifying --gpu <X>
                   with X=0. Then try X=1 in a new run, and so on. The numbering of
                   GPUs may not be obvious from the driver or intuition. For a list
                   of GPU compute generations, see
 
                   en.wikipedia.org/wiki/CUDA#Version_features_and_specifications
 
                -> ARE USING DOUBLE-PRECISION GPU CODE: relion was been written so
                   as to not require this, and may thus have unforeseen requirements
                   when run in this mode. If you think it is nonetheless necessary,
                   please consult the developers with this error.
 
If this occurred at the middle or end of a run, it might be that
 
                -> YOUR DATA OR PARAMETERS WERE UNEXPECTED: execution on GPUs is
                   subject to many restrictions, and relion is written to work within
                   common restraints. If you have exotic data or settings, unexpected
                   configurations may occur. See also above point regarding
                   double precision.
If none of the above applies, please report the error to the relion
developers at    github.com/3dem/relion/issues

**Comment by biochem-fan** [comment]
> As other tasks using the GPUs appear to run correctly

Do you mean other GPU jobs in RELION, or other non-RELION programs using GPU?

What happens if you compile without `-DCUDA_ARCH`?

**Comment by drawoliver** [comment]
Sorry — I meant that other jobs / tasks within relion that use the GPUs, appear to run and finish.
I will compile leaving out -DCUDA_ARCH as suggested.

**Comment by drawoliver** [comment]
Rebuilding without -DCUDA_ARCH did not solve the issue.
 
I have — downgraded CUDA to 11.6 and downgraded the Nvidia driver to 510.68.02 and recompiled relion exactly as before (after git pull) using openmpi-2.16 and specifying -DCUDA_ARCH = 86.

The 3D initial model job is now running and has not crashed (yet).  
I have one further parameter to check -  as I am now not copying particles across to SSD/scratch.  
I will rerun and check if this makes any difference once the current job has successfully finished.

So ... I'm thinking a potential CUDA / Driver issue?

**Comment by drawoliver** [comment]
Everything was looking okay, but then we had a segmentation fault/core dump. 

Gradient optimisation iteration 59 of 100 with 30694 particles (Step size 0.5)
4.95/4.95 min ............................................................~~(,_,">
 Maximization ...
   0/   0 sec ............................................................~~(,_,">
 Estimating accuracies in the orientational assignment ... 
   0/   0 sec ............................................................~~(,_,">
 Auto-refine: Estimated accuracy angles= 4.215 degrees; offsets= 3.08568 Angstroms
 Auto-refine: Angular step= 3.75 degrees; local searches= true
 Auto-refine: Offset search range= 9.32343 Angstroms; offset step= 1.5 Angstroms
 CurrentResolution= 10.32 Angstroms, which requires orientationSampling of at least 5.90164 degrees for a particle of diameter 200 Angstroms
 Oversampling= 0 NrHiddenVariableSamplingPoints= 1069056
 OrientationalSampling= 7.5 NrOrientations= 36864
 TranslationalSampling= 3 NrTranslations= 29
=============================
 Oversampling= 1 NrHiddenVariableSamplingPoints= 34209792
 OrientationalSampling= 3.75 NrOrientations= 294912
 TranslationalSampling= 1.5 NrTranslations= 116
=============================
 Gradient optimisation iteration 60 of 100 with 31613 particles (Step size 0.5)
000/??? sec ~~(,_,">                                                          [oo]KERNEL_ERROR: an illegal memory access was encountered in /usr/local/git_source/relion-4.0-20220817/src/acc/acc_ml_optimiser_impl.h at line 2371 (error-code 700)

**Comment by biochem-fan** [comment]
Not sure if this is still relevant. Closing.
