### ISSUE TITLE
out of memory for particle subtraction

### ISSUE THREAD

**Issue by diffracteD** [3dem/relion#932]
Hi,
I'm facing an odd issue with particle subtraction. I have a set of ~200k particles with 440 pix box size which I'm trying to run particle subtraction with. 
I'm using 2 MPI and 503 GB RAM (all available RAM). But the job is crashing at the very end due to out of memory.
Please advise if this can be avoided or I'm missing something. I tried higher MPI but it still doesn't go through.
Thanks.

**Comment by biochem-fan** [comment]
Please try the workaround in https://github.com/3dem/relion/issues/673#issuecomment-773200651.

**Comment by diffracteD** [comment]
Found an easier way without modifying system environment (I guess).
Split the particle set in two halves and ran particle subtraction on both halves. Then joined them together before running Class3D on the complete set. Refine3D map turns out to be good as expected.
Thanks.
