### ISSUE TITLE
Bayesian polishing leads to empty reconstruction and Refine3D error

### ISSUE THREAD

**Issue by dbhella** [3dem/relion#937]
I have run into issues with Bayesian polishing in Relion 4 for two different datasets this past month. Briefly - after running polishing, Refine3D fails with an error:

ERROR: 
No orientation was found as better than any other.

A particle image was compared to the reference and resulted in all-zero
weights (for all orientations). This should not happen, unless your data
has very special characteristics. This has historically happened for some 
lower-precision calculations, but multiple fallbacks have since been 
implemented. Please report this error to the relion developers at 

I found that running relion_reconstruct on the shiny.star file gives an empty volume.

I have tried to understand what is causing this problem and so far I have discovered that splitting the data into smaller groups and polishing them separately results in a shiny.star file that processes fine. 

I have not concluded my investigation yet - I have split one of the datasets into 10 subsets - the full dataset is 290k particles (400 pixel box size - apoferritin). So far the first subset has polished and refined correctly.  There are however other reports of this problem in the list of bugs - so I think it maybe warrants further investigation. 

**Environment:**
 - OS: CentOS 7
 - MPI runtime: [e.g. OpenMPI 2.0.1]
 - RELION version Relion-4.0-beta-2-commit-b5a555
 - Memory: 380 GB (CPU node used for polishing) 256 GB (GPU node used for Refine 3D)
 - GPU: N/A for polishing -  P100 for Refine3D

**Dataset 1 **
 - Box size: 400
 - Pixel size: 0.491
 - Number of particles: 290,000
 - Description: Apoferritin 

**Dataset 1 **
 - Box size: 500
 - Pixel size: 0.774
 - Number of particles: 498,000
 - Description: TMV 

**Job options:**
 - Type of job: Polish
 - Number of MPI processes: 1-3
 - Number of threads: 40
 - Full command

**Comment by dbhella** [comment]
I have now run the polishing on all ten subsets and joined them into a single STAR file. The Refine3D job failed.
So, if something is wrong with some of the data (although they have refined OK so far) - I expect to discover this by refining each subset separately  - I am running this now. More soon.

**Comment by biochem-fan** [comment]
Could you please check if the resulting MRCS files contain NaNs by running `relion_image_handler --stats`?

**Comment by dbhella** [comment]
for i in *shiny.mrcs; do relion_image_handler --stats --I $i | grep NaN ; done
did not return anything (there are a lot of files). However I noticed that in the prior Refine3D runs before polishing, I did get some warnings about particles with abnormally high normalisation. I thought I would try to exclude them by using subset selection on _rlnNormCorrection - to exclude the bad particles from the shiny.star but I get an error saying  "can only make a selection based on numbers" which is confusing as that value is a number!

**Comment by dbhella** [comment]
That's maybe a red herring - I didn't get that error in my other dataset (TMV)

**Comment by biochem-fan** [comment]
Does `--stats` show abnormal particles?

Try running Class2D (with/without alignment). Apollo may have defect line(s) or hot pixels that RELION cannot mask well and Polish put very wrong scale factors on them.

**Comment by dbhella** [comment]
2D classification gave the same error as refine3d (no orientation better than any other)
