### ISSUE TITLE
RELION build fails with CUDA 12

### ISSUE THREAD

**Issue by rbs-sci** [3dem/relion#939]
RELION 3.1 compilation fails with CUDA 12.

Compilation succeeds with CUDA 11.8.

I see from the release notes that 3.1 will have no further bug fixes, so I'm not asking for a fix, this is more of a heads up for the RELION community who might update to the new CUDA release.

Will investigate further if time, but reverted to CUDA 11.8 as that system is needed.

**Environment:**
 - OS: Ubuntu 22.04
 - MPI runtime: OpenMPI 4.1.2
 - RELION version: 3.1 (checkout ver3.1)
- gcc: 11.3
- CUDA: 12

**Error message:**

/usr/local/cuda/include/cub/util_debug.cuh(184): error: function "cub::Debug" has already been defined

1 error detected in the compilation of "/home/builder/build/relion/src/acc/cuda/cuda_projector_plan.cu".
CMake Error at relion_gpu_util_generated_cuda_projector_plan.cu.o.Release.cmake:280 (message):
  Error generating file
  /home/builder/build/relion/build31/src/apps/CMakeFiles/relion_gpu_util.dir/__/acc/cuda/./relion_gpu_util_generated_cuda_projector_plan.cu.o

make[2]: *** [src/apps/CMakeFiles/relion_gpu_util.dir/build.make:4219: src/apps/CMakeFiles/relion_gpu_util.dir/__/acc/cuda/relion_gpu_util_generated_cuda_projector_plan.cu.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:297: src/apps/CMakeFiles/relion_gpu_util.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

(All .cu files throw the same cub::Debug error)

**Comment by MoritzWM** [comment]
I found the same issue when compiling the master branch. Reverting to Cuda-11.8 fixed the issue for me

**Comment by biochem-fan** [comment]
@xiaoqiang0313 
Please try the above commit 39c3538 to compile RELION 4.0 with CUDA 12.

@rbs-sci @MoritzWM
I won't update 3.1, but if you manually apply the same change, 3.1 should become compatible with CUDA 12.0.

**Comment by rbs-sci** [comment]
Thanks, @biochem-fan - I'll apply it and test as soon as possible (which may be a week or so...)
