### ISSUE TITLE
RELION 4.0 installation error 

### ISSUE THREAD

**Issue by 2019C** [3dem/relion#940]
Hello,

I am trying to install RELION 4.0 on CentOS 7. I followed the instructions and everything was fine until the "make -J N" step.  I don't understand why it was trying to find libstdc++.so.6. 

Here are my system info:
  Operating System: CentOS Linux 7 (Core)
  CPE OS Name: cpe:/o:centos:centos:7
  Kernel: Linux 3.10.0-1160.76.1.el7.x86_64
  Architecture: x86-64
  CUDA V11.2.152

Below is the error message:
../fluid/fluid: /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by ../fluid/fluid)
../fluid/fluid: /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by ../fluid/fluid)
make[4]: *** [fast_slow.h] Error 1
make[4]: *** Waiting for unfinished jobs....
make[4]: *** [fast_slow.cxx] Error 1
[ 70%] Built target relion_lib

I would be grateful for any thoughts / suggestions.

With thanks,
Chen

**Comment by biochem-fan** [comment]
Probably your system has various versions of GLIBC and compilers, linkers and shell are using different ones.

Aren't you compiling RELION when conda is activated? This causes a mess, because conda provides its own libraries. Please compile (and use) RELION outside conda.

**Comment by 2019C** [comment]
Thank you for your prompt reply. I didn't load any conda environment when installing relion but I did have anaconda in my $PATH. So I switched to a new user account and set $PATH to default. Now it is installed successfully.
