### ISSUE TITLE
Intel GPU support

### ISSUE THREAD

**Issue by biochem-fan** [3dem/relion#941]
Are there plans to port RELION's GPU kernels to Intel oneAPI ecosystem, @CharlesCongdon and @do-jason? AMD recently contributed their HIP/ROCm port (#936).

Although consumer grade Intel GPUs are not as powerful as NVIDIA 40x0s, A770 has 16 GB of RAM and similar (theoretical) FP32 FLOPS as 2080 Ti. Considering that it is difficult for RELION to fully utilize 40x0s (they have too high TFLOPS compared with the memory size and bandwidth) and Intel Arcs are significantly cheaper, Intel Arcs can potentially be a very good choice for SPA.

**Comment by do-jason** [comment]
Intel is working on porting RELION's GPU kernels to SYCL and Intel oneAPI.

**Comment by biochem-fan** [comment]
This is wonderful!

I bought Intel Arc A770 (16 GB). I am happy to test your codes.
