### ISSUE TITLE
Relion 4.0 installation error with CUDA 12

### ISSUE THREAD

**Issue by xiaoqiang0313** [3dem/relion#942]
Error on compiling Relion 4.0 with CUDA 12.0

**Error in compilation of /usr/local/relion/src/acc/cuda/cuda_projector_plan.cu**

I tried to install Relion 4.0 on my workstations. The configuration worksed with no error message but when compiling, it returned an error messages mentioned above.

**Environment:**
 - OS:  Ubuntu 22.04.01 LTS
 - MPI runtime: OpenMPI 4.1.2
 - RELION version :Relion 4.0 
 - GCC: 11.3.0
 - GPU: NVIDIA RTX A4000
 - CUDA Version:12.0
 - NVIDIA Driver: 525.60.3

**Error message:**
[  1%] No update step for 'class_ranker_model_file'
[  1%] No patch step for 'class_ranker_model_file'
[  1%] No configure step for 'class_ranker_model_file'
[  1%] No build step for 'class_ranker_model_file'
[  1%] No install step for 'class_ranker_model_file'
[  1%] Completed 'class_ranker_model_file'
[  1%] Built target class_ranker_model_file
[  1%] Built target copy_scripts
[  2%] Building NVCC (Device) object src/apps/CMakeFiles/relion_jaz_gpu_util.dir/__/jaz/cuda/relion_jaz_gpu_util_generated_test00.cu.o
[  2%] Building NVCC (Device) object src/apps/CMakeFiles/relion_jaz_gpu_util.dir/__/jaz/cuda/kernels/relion_jaz_gpu_util_generated_add.cu.o
[  2%] Linking CXX static library ../../lib/librelion_jaz_gpu_util.a
[  2%] Built target relion_jaz_gpu_util
[  2%] Building NVCC (Device) object src/apps/CMakeFiles/relion_gpu_util.dir/__/acc/cuda/relion_gpu_util_generated_cuda_projector_plan.cu.o
/usr/local/cuda/include/cub/util_debug.cuh(184): error: function "cub::Debug" has already been defined

1 error detected in the compilation of "/usr/local/relion/src/acc/cuda/cuda_projector_plan.cu".
CMake Error at relion_gpu_util_generated_cuda_projector_plan.cu.o.Release.cmake:280 (message):
  Error generating file
  /usr/local/relion/build/src/apps/CMakeFiles/relion_gpu_util.dir/__/acc/cuda/./relion_gpu_util_generated_cuda_projector_plan.cu.o

make[2]: *** [src/apps/CMakeFiles/relion_gpu_util.dir/build.make:126: src/apps/CMakeFiles/relion_gpu_util.dir/__/acc/cuda/relion_gpu_util_generated_cuda_projector_plan.cu.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:406: src/apps/CMakeFiles/relion_gpu_util.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

**Comment by biochem-fan** [comment]
Please use CUDA 11.x. See https://github.com/3dem/relion/issues/939.

**Comment by biochem-fan** [comment]
Closing this as we will track this issue in #939.
