### ISSUE TITLE
After opening the working directory with relion4, relion3.1 cannot be opened;

### ISSUE THREAD

**Issue by willi7758521** [3dem/relion#943]
after use relion4 open the work directory , it'll display those error message after use relion 3.1.2 to open the directiry again:
============================="error message"===============================================
 + WARNING: will ignore (but maintain) values for the unknown label: rlnPipeLineNodeTypeLabel
in: /home/user/Downloads/relion-3.1.2/src/pipeliner.cpp, line 1970
ERROR:
PipeLine::read: cannot find name or type in pipeline_nodes table
=== Backtrace  ===
relion(_ZN11RelionErrorC1ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES7_l+0x77) [0x55d56ae54a57]
relion(_ZN8PipeLine4readEbNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x893) [0x55d56af84513]
relion(_ZN13GuiMainWindowC2EiiPKc8FileNameS2_iib+0x3ab) [0x55d56b0260cb]
relion(main+0x830) [0x55d56ae45fb0]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3) [0x7f6eaf4fd0b3]
relion(_start+0x2e) [0x55d56ae4ca3e]
==================
ERROR:
PipeLine::read: cannot find name or type in pipeline_nodes table
======================================================================================
after Ctrl+C, use relion 3.1.2 open the directory again ,it will display those warning message:
=============================="warning message"============================================
 WARNING: trying to read pipeline.star, but directory .relion_lock exists (which protects against simultaneous writing by multiple instances of the GUI)
======================================================================================

**Comment by biochem-fan** [comment]
This is by design. You cannot go back.
