### ISSUE TITLE
polish error 

### ISSUE THREAD

**Issue by zhoujingyu13687306871** [3dem/relion#946]
hello dear authors
I would like to ask a question. When Ido polish with relion 4.0, the previous steps are fine, but an error occurs at the polish step, as shown in the figure below. I have found the file mentioned in the error, and the file from rawdata path(see figure 2) , the file also exists in the motion file, but  relion can’t read it.my machine configuration is the operating system
Operating system: CentOS7.9
Resource model: RTX3090
GPU information: 8 cards 192GB memory
Configuration specifications: 92 cores 480GB memory
System storage: standard cloud disk 240GB
Data storage: standard cloud disk 18730GB
The peak memory usage is only 25%, and the memory overflow is excluded to cause errors. Have you encountered similar errors?

<img width="1201" alt="86dffab4b6027c80a016d28ef84840b" src="https://user-images.githubusercontent.com/47057417/210193091-2ae67ae4-5b8f-4d17-9a48-24ce6cd70440.png">
<img width="1750" alt="be601d50bf44cdff8a7833e135e68f2" src="https://user-images.githubusercontent.com/47057417/210193103-34dc77be-2981-495d-8238-d614cbac04de.png">

<img width="1195" alt="5658e6ff05e510ebe9428c1b146601e" src="https://user-images.githubusercontent.com/47057417/210193102-1e8c63f3-9d02-4d80-af0d-a1d96989b533.png">

**Comment by biochem-fan** [comment]
First of all, please don't use screenshots to cite error messages.
Images are not searchable.

Anyway, the messages like `LZWDecode: corruprted LZW table at scanline XXX` suggest your movies are corrupted. Can you open the movies in other programs like IMOD and ImageJ?

**Comment by zhoujingyu13687306871** [comment]
> First of all, please don't use screenshots to cite error messages. Images are not searchable.
> 
> Anyway, the messages like `LZWDecode: corruprted LZW table at scanline XXX` suggest your movies are corrupted. Can you open the movies in other programs like IMOD and ImageJ?

I used DigitalMicrograph to open .tiff pictures ，but it looks dark and nothing
![image](https://user-images.githubusercontent.com/47057417/210250127-2491fffa-f930-4392-b803-5dca7b80200a.png)

**Comment by zhoujingyu13687306871** [comment]
> First of all, please don't use screenshots to cite error messages. Images are not searchable.
> 
> Anyway, the messages like `LZWDecode: corruprted LZW table at scanline XXX` suggest your movies are corrupted. Can you open the movies in other programs like IMOD and ImageJ?

I used ImageJ open .tiff pictures but it show me dark and nothing
![image](https://user-images.githubusercontent.com/47057417/210255043-ba67a60b-f2bd-4dc1-8486-6d7f72fd736e.png)

**Comment by biochem-fan** [comment]
Is the Windows machine running DM and ImageJ looking at the same storage as the Linux machine running Linux? Perhaps the files were corrupted during transfer between two machines?

**Comment by zhoujingyu13687306871** [comment]
> 运行 DM 和 ImageJ 的 Windows 机器是否正在查看与运行 Linux 的 Linux 机器相同的存储？也许文件在两台机器之间传输期间损坏了？

I open .tiff picture on linux machine , but lt looks dark and nothing too
![image](https://user-images.githubusercontent.com/47057417/210291516-f2419b03-3468-4b8e-bb3a-fec894f8053b.png)

**Comment by zhoujingyu13687306871** [comment]
params set:
I/O:
Micrographs:/data/taar4-20221111/.Nodes/MicrographsData/MotionCorr/job019/corrected_micrographs.star
Particles:/data/taar4-20221111/.Nodes/ParticlesData/CtfRefine/job192/particles_ctf_refine.star
Postprocess STAR :/data/taar4-20221111/.Nodes/ProcessData/PostProcess/job189/postprocess.star
<img width="603" alt="企业微信截图_16726565096626" src="https://user-images.githubusercontent.com/47057417/210292299-f86c3b06-8cfe-45bf-9587-528e14d98306.png">

train set:
<img width="595" alt="企业微信截图_16726565223881" src="https://user-images.githubusercontent.com/47057417/210292322-b04cbec1-239b-442c-a04a-cf9d4df40ced.png">

Polish set:
<img width="599" alt="企业微信截图_16726565448605" src="https://user-images.githubusercontent.com/47057417/210292341-0f8bcea6-4a4a-495d-8ce5-1f0fa2f7dbde.png">

running set:
<img width="596" alt="企业微信截图_16726565573337" src="https://user-images.githubusercontent.com/47057417/210292353-10750858-8d52-400e-afb2-fffc113811f1.png">


I run polish with relion 4.0  again, As shown in the run.out and run.err below
**cat run.out**
 === RELION MPI setup ===
 + Number of MPI processes             = 9
 + Leader  (0) runs on host            = gt-centos7-9-desktop-v2-6-32gb-100m.novalocal
 =================
 + Follower     1 runs on host            = gt-centos7-9-desktop-v2-6-32gb-100m.novalocal
 + Follower     2 runs on host            = gt-centos7-9-desktop-v2-6-32gb-100m.novalocal
 + Follower     3 runs on host            = gt-centos7-9-desktop-v2-6-32gb-100m.novalocal
 + Follower     4 runs on host            = gt-centos7-9-desktop-v2-6-32gb-100m.novalocal
 + Follower     5 runs on host            = gt-centos7-9-desktop-v2-6-32gb-100m.novalocal
 + Follower     6 runs on host            = gt-centos7-9-desktop-v2-6-32gb-100m.novalocal
 + Follower     7 runs on host            = gt-centos7-9-desktop-v2-6-32gb-100m.novalocal
 + Follower     8 runs on host            = gt-centos7-9-desktop-v2-6-32gb-100m.novalocal
 + Reading CtfRefine/job192/particles_ctf_refine.star...
 + Using movie pixel size from MotionCorr/job019/rawdata/FoilHole_11515528_Data_11514783_11514785_20221111_171451_fractions.star: 0.425 A
 + Using coord. pixel size from MotionCorr/job019/rawdata/FoilHole_11515528_Data_11514783_11514785_20221111_171451_fractions.star: 0.85 A
 + Using dose per frame from MotionCorr/job019/rawdata/FoilHole_11515528_Data_11514783_11514785_20221111_171451_fractions.star: 1.875 e/A^2
 + Reading references ...
 + The names of the reference half maps and the mask were taken from the PostProcess STAR file.
   - Half map 1: Refine3D/job187/run_half1_class001_unfil.mrc
   - Half map 2: Refine3D/job187/run_half2_class001_unfil.mrc
   - Mask: MaskCreate/job188/mask.mrc
 + Masking references ...
 + Transforming references ...
 + Initializing motion estimator ...
 + using parameters from: Polish/job193/opt_params_all_groups.txt
   s_vel: 0.783, s_div: 8475, s_acc: 1.065
 + Performing loop over micrographs ... 
13.85/21.02 hrs .......................................~~(,_,">

**cat run.out**
WARNING: You did not specify --angpix_ref. The pixel size in the image header of Refine3D/job187/run_half1_class001_unfil.mrc, 0.85 A/px, is used.
WARNING: You did not specify --angpix_ref. The pixel size in the image header of Refine3D/job187/run_half1_class001_unfil.mrc, 0.85 A/px, is used.
WARNING: You did not specify --angpix_ref. The pixel size in the image header of Refine3D/job187/run_half1_class001_unfil.mrc, 0.85 A/px, is used.
WARNING: You did not specify --angpix_ref. The pixel size in the image header of Refine3D/job187/run_half1_class001_unfil.mrc, 0.85 A/px, is used.
WARNING: You did not specify --angpix_ref. The pixel size in the image header of Refine3D/job187/run_half1_class001_unfil.mrc, 0.85 A/px, is used.
WARNING: You did not specify --angpix_ref. The pixel size in the image header of Refine3D/job187/run_half1_class001_unfil.mrc, 0.85 A/px, is used.
WARNING: You did not specify --angpix_ref. The pixel size in the image header of Refine3D/job187/run_half1_class001_unfil.mrc, 0.85 A/px, is used.
WARNING: You did not specify --angpix_ref. The pixel size in the image header of Refine3D/job187/run_half1_class001_unfil.mrc, 0.85 A/px, is used.
WARNING: You did not specify --angpix_ref. The pixel size in the image header of Refine3D/job187/run_half1_class001_unfil.mrc, 0.85 A/px, is used.
LZWDecode: Wrong length of decoded string: data probably corrupted at scanline 0.
in: /home/centos/relion-4.0.0/src/rwTIFF.h, line 212
ERROR:
Failed to read an image data from rawdata/FoilHole_11541912_Data_11514783_11514785_20221112_081232_fractions.tiff
 - Warning: unable to load raw movie frames for MotionCorr/job019/rawdata/FoilHole_11541912_Data_11514783_11514785_20221112_081232_fractions.mrc.  Possible reasons include lack of the metadata STAR file, the gain reference and/or the movie.
LZWDecode: Wrong length of decoded string: data probably corrupted at scanline 2046.
in: /home/centos/relion-4.0.0/src/rwTIFF.h, line 212
ERROR:
Failed to read an image data from rawdata/FoilHole_11552064_Data_11514783_11514785_20221112_131140_fractions.tiff
 - Warning: unable to load raw movie frames for MotionCorr/job019/rawdata/FoilHole_11552064_Data_11514783_11514785_20221112_131140_fractions.mrc.  Possible reasons include lack of the metadata STAR file, the gain reference and/or the movie.
LZWDecode: Wrong length of decoded string: data probably corrupted at scanline 1364.
in: /home/centos/relion-4.0.0/src/rwTIFF.h, line 212
ERROR:
Failed to read an image data from rawdata/FoilHole_11541935_Data_11514783_11514785_20221112_080501_fractions.tiff
 - Warning: unable to load raw movie frames for MotionCorr/job019/rawdata/FoilHole_11541935_Data_11514783_11514785_20221112_080501_fractions.mrc.  Possible reasons include lack of the metadata STAR file, the gain reference and/or the movie.
LZWDecode: Wrong length of decoded string: data probably corrupted at scanline 2728.
in: /home/centos/relion-4.0.0/src/rwTIFF.h, line 212
ERROR:
Failed to read an image data from rawdata/FoilHole_11515588_Data_11514783_11514785_20221111_174245_fractions.tiff
 - Warning: unable to load raw movie frames for MotionCorr/job019/rawdata/FoilHole_11515588_Data_11514783_11514785_20221111_174245_fractions.mrc.  Possible reasons include lack of the metadata STAR file, the gain reference and/or the movie.
LZWDecode: Wrong length of decoded string: data probably corrupted at scanline 1364.
in: /home/centos/relion-4.0.0/src/rwTIFF.h, line 212
ERROR:
Failed to read an image data from rawdata/FoilHole_11552077_Data_11514783_11514785_20221112_130508_fractions.tiff
 - Warning: unable to load raw movie frames for MotionCorr/job019/rawdata/FoilHole_11552077_Data_11514783_11514785_20221112_130508_fractions.mrc.  Possible reasons include lack of the metadata STAR file, the gain reference and/or the movie.
LZWDecode: Wrong length of decoded string: data probably corrupted at scanline 2046.
in: /home/centos/relion-4.0.0/src/rwTIFF.h, line 212
ERROR:
Failed to read an image data from rawdata/FoilHole_11535166_Data_11514783_11514785_20221112_041631_fractions.tiff
 - Warning: unable to load raw movie frames for MotionCorr/job019/rawdata/FoilHole_11535166_Data_11514783_11514785_20221112_041631_fractions.mrc.  Possible reasons include lack of the metadata STAR file, the gain reference and/or the movie.
LZWDecode: Corrupted LZW table at scanline 682.
in: /home/centos/relion-4.0.0/src/rwTIFF.h, line 212
ERROR:
Failed to read an image data from rawdata/FoilHole_11552091_Data_11514783_11514785_20221112_131159_fractions.tiff
 - Warning: unable to load raw movie frames for MotionCorr/job019/rawdata/FoilHole_11552091_Data_11514783_11514785_20221112_131159_fractions.mrc.  Possible reasons include lack of the metadata STAR file, the gain reference and/or the movie.
LZWDecode: Not enough data at scanline 0 (short 5967221 bytes).
in: /home/centos/relion-4.0.0/src/rwTIFF.h, line 212
ERROR:
Failed to read an image data from rawdata/FoilHole_11529240_Data_11514783_11514785_20221112_011420_fractions.tiff
 - Warning: unable to load raw movie frames for MotionCorr/job019/rawdata/FoilHole_11529240_Data_11514783_11514785_20221112_011420_fractions.mrc.  Possible reasons include lack of the metadata STAR file, the gain reference and/or the movie.
LZWDecode: Wrong length of decoded string: data probably corrupted at scanline 5456.
in: /home/centos/relion-4.0.0/src/rwTIFF.h, line 212
 - Warning: unable to load raw movie frames for MotionCorr/job019/rawdata/FoilHole_11515588_Data_11514783_11514785_20221111_174245_fractions.mrc.  Possible reasons include lack of the metadata STAR file, the gain reference and/or the movie.
LZWDecode: Wrong length of decoded string: data probably corrupted at scanline 1364.
in: /home/centos/relion-4.0.0/src/rwTIFF.h, line 212
ERROR:
Failed to read an image data from rawdata/FoilHole_11552077_Data_11514783_11514785_20221112_130508_fractions.tiff
 - Warning: unable to load raw movie frames for MotionCorr/job019/rawdata/FoilHole_11552077_Data_11514783_11514785_20221112_130508_fractions.mrc.  Possible reasons include lack of the metadata STAR file, the gain reference and/or the movie.
LZWDecode: Wrong length of decoded string: data probably corrupted at scanline 2046.
in: /home/centos/relion-4.0.0/src/rwTIFF.h, line 212
ERROR:
Failed to read an image data from rawdata/FoilHole_11535166_Data_11514783_11514785_20221112_041631_fractions.tiff
 - Warning: unable to load raw movie frames for MotionCorr/job019/rawdata/FoilHole_11535166_Data_11514783_11514785_20221112_041631_fractions.mrc.  Possible reasons include lack of the metadata STAR file, the gain reference and/or the movie.
LZWDecode: Corrupted LZW table at scanline 682.
in: /home/centos/relion-4.0.0/src/rwTIFF.h, line 212
ERROR:
Failed to read an image data from rawdata/FoilHole_11552091_Data_11514783_11514785_20221112_131159_fractions.tiff
 - Warning: unable to load raw movie frames for MotionCorr/job019/rawdata/FoilHole_11552091_Data_11514783_11514785_20221112_131159_fractions.mrc.  Possible reasons include lack of the metadata STAR file, the gain reference and/or the movie.
LZWDecode: Not enough data at scanline 0 (short 5967221 bytes).
in: /home/centos/relion-4.0.0/src/rwTIFF.h, line 212
ERROR:
Failed to read an image data from rawdata/FoilHole_11529240_Data_11514783_11514785_20221112_011420_fractions.tiff
 - Warning: unable to load raw movie frames for MotionCorr/job019/rawdata/FoilHole_11529240_Data_11514783_11514785_20221112_011420_fractions.mrc.  Possible reasons include lack of the metadata STAR file, the gain reference and/or the movie.
LZWDecode: Wrong length of decoded string: data probably corrupted at scanline 5456.
in: /home/centos/relion-4.0.0/src/rwTIFF.h, line 212
 - Warning: unable to load raw movie frames for MotionCorr/job019/rawdata/FoilHole_11515588_Data_11514783_11514785_20221111_174245_fractions.mrc.  Possible reasons include lack of the metadata STAR file, the gain reference and/or the movie.
LZWDecode: Wrong length of decoded string: data probably corrupted at scanline 1364.
in: /home/centos/relion-4.0.0/src/rwTIFF.h, line 212
ERROR:
Failed to read an image data from rawdata/FoilHole_11552077_Data_11514783_11514785_20221112_130508_fractions.tiff
 - Warning: unable to load raw movie frames for MotionCorr/job019/rawdata/FoilHole_11552077_Data_11514783_11514785_20221112_130508_fractions.mrc.  Possible reasons include lack of the metadata STAR file, the gain reference and/or the movie.
LZWDecode: Wrong length of decoded string: data probably corrupted at scanline 2046.
in: /home/centos/relion-4.0.0/src/rwTIFF.h, line 212
ERROR:
Failed to read an image data from rawdata/FoilHole_11535166_Data_11514783_11514785_20221112_041631_fractions.tiff
 - Warning: unable to load raw movie frames for MotionCorr/job019/rawdata/FoilHole_11535166_Data_11514783_11514785_20221112_041631_fractions.mrc.  Possible reasons include lack of the metadata STAR file, the gain reference and/or the movie.
LZWDecode: Corrupted LZW table at scanline 682.
in: /home/centos/relion-4.0.0/src/rwTIFF.h, line 212
ERROR:
Failed to read an image data from rawdata/FoilHole_11552091_Data_11514783_11514785_20221112_131159_fractions.tiff
 - Warning: unable to load raw movie frames for MotionCorr/job019/rawdata/FoilHole_11552091_Data_11514783_11514785_20221112_131159_fractions.mrc.  Possible reasons include lack of the metadata STAR file, the gain reference and/or the movie.
LZWDecode: Not enough data at scanline 0 (short 5967221 bytes).
in: /home/centos/relion-4.0.0/src/rwTIFF.h, line 212
ERROR:
Failed to read an image data from rawdata/FoilHole_11529240_Data_11514783_11514785_20221112_011420_fractions.tiff
 - Warning: unable to load raw movie frames for MotionCorr/job019/rawdata/FoilHole_11529240_Data_11514783_11514785_20221112_011420_fractions.mrc.  Possible reasons include lack of the metadata STAR file, the gain reference and/or the movie.
LZWDecode: Wrong length of decoded string: data probably corrupted at scanline 5456.
in: /home/centos/relion-4.0.0/src/rwTIFF.h, line 212
in: /home/centos/relion-4.0.0/src/rwTIFF.h, line 212
ERROR:
Failed to read an image data from rawdata/FoilHole_11535260_Data_11514783_11514785_20221112_035020_fractions.tiff
 - Warning: unable to load raw movie frames for MotionCorr/job019/rawdata/FoilHole_11535260_Data_11514783_11514785_20221112_035020_fractions.mrc.  Possible reasons include lack of the metadata STAR file, the gain reference and/or the movie.
LZWDecode: Wrong length of decoded string: data probably corrupted at scanline 1364.
in: /home/centos/relion-4.0.0/src/rwTIFF.h, line 212
ERROR:
Failed to read an image data from rawdata/FoilHole_11522296_Data_11514783_11514785_20221111_211335_fractions.tiff
 - Warning: unable to load raw movie frames for MotionCorr/job019/rawdata/FoilHole_11522296_Data_11514783_11514785_20221111_211335_fractions.mrc.  Possible reasons include lack of the metadata STAR file, the gain reference and/or the movie.
LZWDecode: Wrong length of decoded string: data probably corrupted at scanline 3410.
in: /home/centos/relion-4.0.0/src/rwTIFF.h, line 212
ERROR:
Failed to read an image data from rawdata/FoilHole_11552179_Data_11514783_11514785_20221112_131553_fractions.tiff
 - Warning: unable to load raw movie frames for MotionCorr/job019/rawdata/FoilHole_11552179_Data_11514783_11514785_20221112_131553_fractions.mrc.  Possible reasons include lack of the metadata STAR file, the gain reference and/or the movie.
LZWDecode: Corrupted LZW table at scanline 2728.
in: /home/centos/relion-4.0.0/src/rwTIFF.h, line 212
ERROR:
Failed to read an image data from rawdata/FoilHole_11525190_Data_11514783_11514785_20221111_225630_fractions.tiff
 - Warning: unable to load raw movie frames for MotionCorr/job019/rawdata/FoilHole_11525190_Data_11514783_11514785_20221111_225630_fractions.mrc.  Possible reasons include lack of the metadata STAR file, the gain reference and/or the movie.
LZWDecode: Wrong length of decoded string: data probably corrupted at scanline 4092.
in: /home/centos/relion-4.0.0/src/rwTIFF.h, line 212
ERROR:
Failed to read an image data from rawdata/FoilHole_11542380_Data_11514783_11514785_20221112_082209_fractions.tiff
 - Warning: unable to load raw movie frames for MotionCorr/job019/rawdata/FoilHole_11542380_Data_11514783_11514785_20221112_082209_fractions.mrc.  Possible reasons include lack of the metadata STAR file, the gain reference and/or the movie.
LZWDecode: Wrong length of decoded string: data probably corrupted at scanline 1364.
in: /home/centos/relion-4.0.0/src/rwTIFF.h, line 212

**Comment by biochem-fan** [comment]
Because each frame in raw movies contains very few electrons, it is normal you cannot see anything. You have to sum all frames and adjust the level and contrast.

Please also check your RELION is compiled against libtiff that supports BigTIFF.

**Comment by zhoujingyu13687306871** [comment]
> Because each frame in raw movies contains very few electrons, it is normal you cannot see anything. You have to sum all frames and adjust the level and contrast.
> 
> Please also check your RELION is compiled against libtiff that supports BigTIFF.

when I installed relion 4.0, I have installed libtiff with "sudo yum install libtiff-devel libpng-devel" , libtiff.so on /usr/lib64

**Comment by zhoujingyu13687306871** [comment]
![image](https://user-images.githubusercontent.com/47057417/210305148-c86b626f-f21c-472b-be5d-c900d59bf76f.png)

**Comment by zhoujingyu13687306871** [comment]
> Because each frame in raw movies contains very few electrons, it is normal you cannot see anything. You have to sum all frames and adjust the level and contrast.
> 
> Please also check your RELION is compiled against libtiff that supports BigTIFF.

each .tiff picture in rawdata up to 300-400MB,So I doubt that libtiff installed by sudo yum install libtiff-dev can support such a large image?  if libtiff.so not support big .tiff picture, what should I do ?

**Comment by zhoujingyu13687306871** [comment]
> Can you show me the result of the following command?
> 
> ```
> ldd `which relion_refine`
> ```

sure,
[centos@gt-centos7-9-desktop-v2-6-32gb-100m bin]$ ldd `which relion_refine` 
	linux-vdso.so.1 =>  (0x00007fffe95cc000)
	libcufft.so.10 => /usr/local/cuda/lib64/libcufft.so.10 (0x00007f88358b1000)
	libmpi.so.40 => /opt/bin/apps/openmpi-install/lib/libmpi.so.40 (0x00007f8835599000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f8835395000)
	libtiff.so.5 => /lib64/libtiff.so.5 (0x00007f8835121000)
	libfftw3.so.3 => /opt/bin/apps/relion-4.0.0/lib/libfftw3.so.3 (0x00007f88349ed000)
	libfftw3f.so.3 => /opt/bin/apps/relion-4.0.0/lib/libfftw3f.so.3 (0x00007f88341f2000)
	libcurand.so.10 => /usr/local/cuda/lib64/libcurand.so.10 (0x00007f882e602000)
	libpng15.so.15 => /lib64/libpng15.so.15 (0x00007f882e3d7000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f882e1bb000)
	librt.so.1 => /lib64/librt.so.1 (0x00007f882dfb3000)
	libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007f882dcab000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f882d9a9000)
	libgomp.so.1 => /lib64/libgomp.so.1 (0x00007f882d783000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f882d56d000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f882d19f000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f883e33e000)
	libopen-rte.so.40 => /opt/bin/apps/openmpi-install/lib/libopen-rte.so.40 (0x00007f882cee9000)
	libopen-orted-mpir.so => /opt/bin/apps/openmpi-install/lib/libopen-orted-mpir.so (0x00007f882cce7000)
	libopen-pal.so.40 => /opt/bin/apps/openmpi-install/lib/libopen-pal.so.40 (0x00007f882c9d7000)
	libutil.so.1 => /lib64/libutil.so.1 (0x00007f882c7d4000)
	libjbig.so.2.0 => /lib64/libjbig.so.2.0 (0x00007f882c5c8000)
	libjpeg.so.62 => /lib64/libjpeg.so.62 (0x00007f882c373000)
	libz.so.1 => /lib64/libz.so.1 (0x00007f882c15d000)

**Comment by biochem-fan** [comment]
This looks fine.

Can you run `tif2mrc` from IMOD suite on `rawdata/FoilHole_11542380_Data_11514783_11514785_20221112_082209_fractions.tiff` and convert it to an MRC file?
Look at the console and see if it shows any errors.

**Comment by biochem-fan** [comment]
No response for many months. Closing.
