### ISSUE TITLE
Relion and Ampere ARM for CPU jobs?

### ISSUE THREAD

**Issue by Qiangong2** [3dem/relion#954]
Are there any benchmarks available showing Ampere ARM servers being used for CPU (or GPU) jobs? We're looking into purchasing a new server for CPU jobs specifically, and we're finding that Ampere ARM servers are cheaper and have more cores (128 vs 56) than intel servers. Nvidia provides an ARM container of Relion, so I know it's possible, I'd just be interested in seeing any benchmarks (if they exist)

**Comment by biochem-fan** [comment]
No, as far as I know. I recommend you to ask in CCPEM, because this is not a bug report and more people are reading CCPEM than GitHub.
