### ISSUE TITLE
 "Ordered comparison of pointer with integer zero (‘Fl_Tree_Item*’ and ‘int’)" error on compile

### ISSUE THREAD

**Issue by Qiangong2** [3dem/relion#956]
**Describe your problem**

When trying to compile 3.0.8 on Ubuntu 22.04 using the intel MPI tools, we receive an FL error.

**Environment:**
 - OS: Ubuntu 22.04
 - MPI runtime: Intel MPI 2023.01
 - RELION version 3.0.8 
 - Memory: 540GB
 - GPU: N/A

**Error message:**
```
Fl_Table.cxx: In member function ‘void Fl_Table::recalc_dimensions()’:
Fl_Table.cxx:494:10: warning: suggest parentheses around operand of ‘!’ or change ‘&’ to ‘&&’ or ‘!’ to ‘~’ [-Wparentheses]
  494 |     if ( !hideh & hidev ) { hidev = (( table_h - tih + scrollsize ) <= 0 ); }
      |          ^~~~~~
Fl_Table.cxx:495:10: warning: suggest parentheses around operand of ‘!’ or change ‘&’ to ‘&&’ or ‘!’ to ‘~’ [-Wparentheses]
  495 |     if ( !hidev & hideh ) { hideh = (( table_w - tiw + scrollsize ) <= 0 ); }
      |          ^~~~~~
Compiling Fl_Table_Row.cxx...
Compiling Fl_Tabs.cxx...
Compiling Fl_Text_Buffer.cxx...
Compiling Fl_Text_Display.cxx...
Compiling Fl_Text_Editor.cxx...
Compiling Fl_Tile.cxx...
Compiling Fl_Tiled_Image.cxx...
Compiling Fl_Tree.cxx...
Compiling Fl_Tree_Item.cxx...
Fl_Tree_Item.cxx: In member function ‘int Fl_Tree_Item::move(Fl_Tree_Item*, int, int)’:
Fl_Tree_Item.cxx:552:38: error: ordered comparison of pointer with integer zero (‘Fl_Tree_Item*’ and ‘int’)
  552 |     if ( from_parent->deparent(from) < 0 )      // deparent self from current parent
      |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~
make[4]: *** [../makeinclude:150: Fl_Tree_Item.o] Error 1
make[3]: *** [Makefile:24: all] Error 1
make[2]: *** [CMakeFiles/OWN_FLTK.dir/build.make:86: OWN_FLTK-prefix/src/OWN_FLTK-stamp/OWN_FLTK-build] Error 2
make[1]: *** [CMakeFiles/Makefile2:200: CMakeFiles/OWN_FLTK.dir/all] Error 2
make: *** [Makefile:146: all] Error 2
```

**Comment by Qiangong2** [comment]
This error also occurs when I do not use the intel compiler

**Comment by biochem-fan** [comment]
- What is your compiler version?
- Does this happen in RELION 4.0.1 as well? (We no longer support 3.0.x)
- Does this happen even with `cmake -DFORCE_OWN_FLTK=ON`)?

**Comment by Qiangong2** [comment]
When using the intel 2023.01 compiler, I use this cmake build: 
```
cmake -DCUDA_ARCH=86 -DMKLFFT=ON -DALTCPU=ON -DCMAKE_C_COMPILER=icc -DCMAKE_CXX_COMPILER=icpc -DMPI_C_COMPILER=mpiicc -DMPI_CXX_COMPILER=mpiicpc -DCMAKE_C_FLAGS="-O3 -ip -g -xCOMMON-AVX512 -restrict " -DCMAKE_CXX_FLAGS="-O3 -ip -g -xCOMMON-AVX512 -restrict "  -DFORCE_OWN_FLTK=ON ..
```
When using gcc 11.3.0, I use the following:
`cmake -DCUDA_ARCH=86 -DFORCE_OWN_FLTK=ON ..`

Same fltk error on both

4.0.1 can build with both compilers fine.

I noticed that 4.0.1 uses fltk 1.3.5, whereas 3.0.8 uses fltk 1.3.3. Is there a way to override the fltk version and use 1.3.5 instead?

**Comment by biochem-fan** [comment]
> I noticed that 4.0.1 uses fltk 1.3.5, whereas 3.0.8 uses fltk 1.3.3. Is there a way to override the fltk version and use 1.3.5 instead?

Probably backporting this commit will do the trick.
https://github.com/3dem/relion/commit/33574c47e51546baa91dd93e3a570d9b644f23e3

> 4.0.1 can build with both compilers fine.

Then I close this issue, because we no longer support 3.0.x.
