### ISSUE TITLE
CTFFIND is not estimating ctf when running in RELION 4.0

### ISSUE THREAD

**Issue by erikzupa** [3dem/relion#957]
**Describe your problem**
CTFFIND is not estimating CTF when running in RELION-4.0. There is an issue of loading library but I could not find if this is serious issue for CTFFIND. CTFFIND is working normally when I ran it on one micrograph.

**Environment:**
 - MPI runtime: [openmpi/gcc/4.1.0]
 - RELION version [RELION-4.0]
 - CTFFIND version [ctffind-4.1.14]

**Dataset:**
 - MotionCorrected EER data

**Job options:**
 - Type of job: [CtfFind]
 - Number of MPI processes: [10]
 - Number of threads: [1]
 - Full command (`which relion_run_ctffind` --i MotionCorr/job003/corrected_micrographs.star --o CtfFind/job011/ --Box 512 --ResMin 30 --ResMax 5 --dFMin 5000 --dFMax 50000 --FStep 500 --dAst 2000 --ctffind_exe /tigress/MOLBIO/local/ctffind-4.1.14/bin/ctffind --ctfWin -1 --is_ctffind4  --fast_search  --use_given_ps  --only_do_unfinished   --pipeline_control CtfFind/job011/ )

**Error message:**
Firstly I get-
/tigress/MOLBIO/local/ctffind-4.1.14/bin/ctffind: error while loading shared libraries: libwx_baseu-3.2.so.0: cannot open shared object file: No such file or directory

Then, it is just going through all files and not estimating CTF
 WARNING: skipping, since cannot get CTF values for

log files are empty and com files contain just this:

#!/usr/bin/env /bin/sh
/tigress/MOLBIO/local/ctffind-4.1.14/bin/ctffind --amplitude-spectrum-input > CtfFind/job011/movies/FoilHole_2333672_Data_2311602_2311604_20230303_164812_EER_PS_ctffind4.log << EOF
CtfFind/job011/movies/FoilHole_2333672_Data_2311602_2311604_20230303_164812_EER_PS.mrc
CtfFind/job011/movies/FoilHole_2333672_Data_2311602_2311604_20230303_164812_EER_PS.ctf
1.39925
300
2.7
0.1
512
30
5
5000
50000
500
no
no
yes
2000
no
no
EOF
exit 0
~           

I have no CTF files produced.

**Comment by biochem-fan** [comment]
This is not a RELION issue.

> CTFFIND is working normally when I ran it on one micrograph.

Do you mean running it from a command line, not via RELION?

> /tigress/MOLBIO/local/ctffind-4.1.14/bin/ctffind: error while loading shared libraries: libwx_baseu-3.2.so.0:

Are you running CTF estimation job of RELION on a cluster?
Probably you have a problem in your cluster job submission script.
Please make sure `libwx_baseu-3.2.so.0` is present on all worker nodes and within your `LD_LIBRARY_PATH`.

`ldd /tigress/MOLBIO/local/ctffind-4.1.14/bin/ctffind` will show you where `libwx_baseu-3.2.so.0` is located.

**Comment by biochem-fan** [comment]
No response for more than one month. Closing.
