### ISSUE TITLE
WARNING: particles in the optics group were removed.

### ISSUE THREAD

**Issue by DrJesseHansen** [3dem/relion#962]
Hi,

I am running particle polishing on 56k particles (320 box size) on 24 CPUs (see below).  This is being run on a HPC cluster.

It appears to run fine for about 30 minutes (concerningly faster than I would expect for a polishing job).   Then it outputs the error below, stating that the majority of the particles were removed and it kept ~5000.    Have never seen this before.

thanks. 

job script:
`#!/bin/bash
#SBATCH --nodes=1
#SBATCH --ntasks=24
#SBATCH --time=24:00:00
#SBATCH --mem-per-cpu=8G
#SBATCH --partition=defaultp
#SBATCH --export=NONE
#SBATCH --cpus-per-task=1

cd $SLURM_SUBMIT_DIR

export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK
module load relion/4.0-beta2
module load openmpi/3.1.3
unset SLURM_EXPORT_ENV

mpirun -np 12 relion_motion_refine_mpi --i Refine3D/job013b_tops/run_data.star --f PostProcess/job047/postprocess.star --corr_mic MotionCorr/job001/micrographs_full.star --first_frame 1 --last_frame -1 --o Polish/job080b/ --float16  --params_file Polish/job080b/opt_params_all_groups.txt --combine_frames --bfac_minfreq 20 --bfac_maxfreq -1 --window 320 --scale 320 --j 2  --pipeline_control Polish/job048/`

tail end of the output:
`WARNING: pixel size (--angpix) is smaller than the movie pixel size (--movie_angpix)
        This is probably a rounding error. It is recommended to set --angpix (1.06) to at least 1.06
 + Performing loop over micrographs ... 
30.08/30.08 min ............................................................~~(,_,">
 + Fitting B/k-factors for optics-group-1 using FCCs from all particles between 16 and 79 pixels, or 20 and 4.29367 Angstrom ...
 + Combining frames for micrographs ... 
34.65/34.65 min ............................................................~~(,_,">
 + Aligning and combining frames for micrographs ... 
 + Combining all EPS and STAR files ... 
gs: /mnt/nfs/clustersw/Debian/bullseye/tiff/4.2.0/lib/libtiff.so.5: no version information available (required by /lib/x86_64-linux-gnu/libgs.so.9)
 + Pixel size for optics group 1: 1.06
WARNING: 48301 particles in the optics group 1 were removed.
 + Done! 
 + Written logfile in Polish/job080b/logfile.pdf
 + Written new particle STAR file in Polish/job080b/shiny.star
 ERROR: cannot touch file: Polish/job048/RELION_JOB_EXIT_SUCCESS
 ERROR: cannot touch file:  ERROR: cannot touch file: Polish/job048/RELION_JOB_EXIT_SUCCESS
 ERROR: cannot touch file: Polish/job048/RELION_JOB_EXIT_SUCCESS
 ERROR: cannot touch file: Polish/job048/RELION_JOB_EXIT_SUCCESS
 ERROR: cannot touch file: Polish/job048/RELION_JOB_EXIT_SUCCESS
 ERROR: cannot touch file: Polish/job048/RELION_JOB_EXIT_SUCCESS
 ERROR: cannot touch file: Polish/job048/RELION_JOB_EXIT_SUCCESS
 ERROR: cannot touch file: Polish/job048/RELION_JOB_EXIT_SUCCESS
 ERROR: cannot touch file: Polish/job048/RELION_JOB_EXIT_SUCCESS
 ERROR: cannot touch file: Polish/job048/RELION_JOB_EXIT_SUCCESS
Polish/job048/RELION_JOB_EXIT_SUCCESS
 ERROR: cannot touch file: Polish/job048/RELION_JOB_EXIT_SUCCESS
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[41270,1],3]
  Exit code:    13
`

**Comment by biochem-fan** [comment]
This happens when you don't have source movies for some particles.
Make sure `MotionCorr/job001/micrographs_full.star` contains all micrographs and motion trajectory STAR files are present in the job folder.

> ERROR: cannot touch file: Polish/job048/RELION_JOB_EXIT_SUCCESS

This is also strange. Make sure your disk is not full.

**Comment by DrJesseHansen** [comment]
thank you, this resolved it.  I appreciate it!
