### ISSUE TITLE
WARNING: Refined helical symmetry is out of the search range

### ISSUE THREAD

**Issue by Nayun424** [3dem/relion#964]
Hi,
I am using relion version 4.0.0 and performing helical processing.
I used the non-uniform refinement map from cryosparc as a reference for 3D classification in relion. Despite obtaining helical parameters in cryoSPARC, I keep encountering warning message in the 3D classification job.

"WARNING: Refined helical symmetry is out of the search range. Check whether the initial guess of helical symmetry is reasonable. Or you may want to modify the search range."

I have tried changing the search range and using a cylinder as the reference map, but I am still encountering this error message not only during the initial iteration but also in subsequent iterations.

Is it a simple resolution issue that I can ignore and proceed to the next job?
Running 3D auto-refinement with the same values does not result in any warnings
If there are anything that I might have overlooked, please let me know.

Box size : 564 pix
Mask diameter : 420 A

<img width="601" alt="image" src="https://user-images.githubusercontent.com/127122811/232424713-47f545a8-1acc-4c71-9f45-f6a8ca102bff.png">
<img width="591" alt="image" src="https://user-images.githubusercontent.com/127122811/232424774-4c6bba90-6f8c-4a3b-b79d-570117c85450.png">

Warning message...
<img width="770" alt="image" src="https://user-images.githubusercontent.com/127122811/232424838-e96ff475-b380-4cdd-b68a-0ce1f03eab1c.png">

**Comment by biochem-fan** [comment]
This is probably OK as long as each class refines fine.

I recommend you to ask this in the CCPEM mailing list, because this is not a bug report and there are more people reading CCPEM than this.

**Comment by Nayun424** [comment]
Okay, Thanks!
