### ISSUE TITLE
Cancel Slurm job when Job is canceled in GUI

### ISSUE THREAD

**Issue by yghorbal** [3dem/relion#967]
RELION is configured to submit jobs on an HPC cluster (through RELION_QSUB_XXXXX env vars). It's working fine, but when a user issues a "cancel" Job in the GUI the HPC job (Slurm job for instance) is not canceled as well and can still continue to run for hours.
Is there any hook that can be leveraged to make RELION issue an scancel on the job when the  user issues a cancel in the GUI?

**Comment by biochem-fan** [comment]
Do you mean `abort job` menu item?
This creates `RELION_JOB_ABORT_NOW` file in the job directory.
RELION programs checks the presence of this file periodically and terminates itself.
So the SLURM job should also exit automatically.

**Comment by yghorbal** [comment]
> Do you mean `abort job` menu item? 

Correct! 

> This creates `RELION_JOB_ABORT_NOW` file in the job directory. RELION programs checks the presence of this file periodically and terminates itself. So the SLURM job should also exit automatically.

Ah! I wasn't aware of that! Do you have a rough estimation of the `periodically`? Is it in minutes or secondes?
Maybe I did'nt wait that much before jumping to conclusions!

**Comment by biochem-fan** [comment]
> Ah! I wasn't aware of that! Do you have a rough estimation of the periodically? Is it in minutes or secondes?
Maybe I did'nt wait that much before jumping to conclusions!

This depends on the job type. For motion correction and Polish, this is per movie, so can
take a few minutes. For refinement and classification, this is every few particles.
(Initially we checked every particle but some IT people complained it put too much metadata load on their distributed file system)

**Comment by biochem-fan** [comment]
Note that depending on the caching policy of the file system, the system "remembers" the absence of a file and does not "notice" its creation. This must be checked.

Going back to the original question, RELION does not have hook mechanisms.
The new GUI being developed by CCPEM might have it, but I don't know. Please ask in CCPEM.

**Comment by yghorbal** [comment]
Awsome! This cover all the questions I had in mind!
Thank you.
