### ISSUE TITLE
Star file parsing causes segfault

### ISSUE THREAD

**Issue by HamishGBrown** [3dem/relion#974]
We are attempting Bayesian polishing of particles exported from cryosparc via pyem. Pyem adds an attribute ucsfID to the header for the star file of each micrograph (ie. the star files that would usually be created in motion correction). Relion should ignore and give a warning over attributes that it doesn't recognize however reading this attribute causes an immediate segmentation fault. By placing `cout` commands throughout the code, rebuilding and running I was able to track down the source of the seg fault. Offending function is this one from metadata_table.cpp:

```
bool MetaDataTable::setUnknownValue(int labelPosition, const std::string &value)
{
	long offset = unknownLabelPosition2Offset[labelPosition];
	if (offset < 0) REPORT_ERROR("MetaDataTable::setValueFromString BUG: offset should not be negative here....");
	if (offset > -1)
	{
		objects[current_objectID]->unknowns[offset] = value;
		return true;
	}
	else
	{
		return false;
	}
}
```

`offset` is assigned a large value (94426340490624) and the line with `unkowns[offset]` causes the seg-fault

**Environment:**
 - OS: Linux Mint 20.1
 - MPI runtime: OpenMPI 4.0.3
 - RELION version Relion 4.0.1-commit-e16f79
 - Memory: 188 GB
 - GPU: 4 x GeForce RTX 3090 24 GB

**Dataset:**
 - Box size: 256
 - Pixel size: 0.655
 - Number of particles: 243,000 (all deleted bar 1 in the attached to make the star file easy to send.)
 - Description: Good ol' ApoF

**Job options:**
 - Type of job: Bayesian Polishing
 - Number of MPI processes: 1
 - Number of threads: 1
 - Full command (see `note.txt` in the job directory):
```
which relion_motion_refine --i run_data.star --f postprocess.star --corr_mic test.star --first_frame 1 --last_frame -1 --o Polish/job031/ --float16  --min_p 5000 --eval_frac 0.5 --align_frac 0.5 --params3  --only_do_unfinished  --j 1 --gi true --pipeline_control Polish/job031/
```
Here are the star files etc to make the command run:
[bugreproduce.zip](https://github.com/3dem/relion/files/11549085/bugreproduce.zip)

**Error message:**

`Segmentation fault (core dumped)`

**Comment by biochem-fan** [comment]
The problem is that you have duplicated lines of `rlnVoltage`.

**Comment by HamishGBrown** [comment]
Hi @biochem-fan, I did notice that and I'll try and track this down in pyem. Shouldn't this error be caught and handled in relion though?

**Comment by biochem-fan** [comment]
> Shouldn't this error also be caught and handled in relion though?

Ideally yes, but RELION is not designed to be safe against corrupted inputs in general.
There are many such cases. We welcome pull request to fix them but it is not my main priority.
