### ISSUE TITLE
Relion limited to 64 MPI procs through GUI

### ISSUE THREAD

**Issue by Qiangong2** [3dem/relion#975]
When you compile Relion (any version) it limits the maximum number of MPI procs to 64. On machines without GPUs, this negatively affects performance on large-thread machines on certain jobs.

Autopicking for instance, is limited to 64 MPI Procs. This limits machines such as an Ampere Altra 128 core to half its total capacity, and a Power10 machine with 768 threads to 1/12th its capacity.

Is there any way to fix this?

**Comment by biochem-fan** [comment]
Please set the`RELION_MPI_MAX` environmental variable.
https://relion.readthedocs.io/en/release-3.1/Installation.html#edit-the-environment-set-up

**Comment by Qiangong2** [comment]
Is there a cmake flag to set so the end user doesn't have to do this every time?

**Comment by biochem-fan** [comment]
Are you a system admin? End users have to set several environmental variables
to run RELION anyway (e.g. CTFFIND path). Why don't you set `RELION_MPI_MAX` in the same way?

If you insist, the default value is hard-coded in:
https://github.com/3dem/relion/blob/e16f7968c3c522a6f255ba80b8b72f0b133201b1/src/pipeline_jobs.h#LL69C3-L69C25

You can change this before compiling.
