### ISSUE TITLE
error when install relion4.0 at the step of make

### ISSUE THREAD

**Issue by cryofib** [3dem/relion#978]
I tried to install Relion 4.0 and everything went smoothly until the last step, make install

**Environment:**
 - OS:  Ubuntu 22.04 LTS]
 - MPI runtime:  OpenMPI 4.1.2
 - RELION version 4.0 
 - Memory:  128 GB
 - GPU: Nvidia Geforce RTX 4090 

   ```

**Error message:**

```
[ 66%] Linking CXX executable ../../bin/relion_display
/usr/bin/ld: /usr/local/lib/libfltk.a(fl_font.o): in function `utf8extents(Fl_Font_Descriptor*, char const*, int, _XGlyphInfo*)':
fl_font.cxx:(.text._ZL11utf8extentsP18Fl_Font_DescriptorPKciP11_XGlyphInfo+0x46): undefined reference to `XftTextExtents32'
/usr/bin/ld: /usr/local/lib/libfltk.a(fl_font.o): in function `Fl_Font_Descriptor::Fl_Font_Descriptor(char const*, int, int)':
fl_font.cxx:(.text._ZN18Fl_Font_DescriptorC2EPKcii+0x7f): undefined reference to `FcPatternCreate'
/usr/bin/ld: fl_font.cxx:(.text._ZN18Fl_Font_DescriptorC2EPKcii+0x165): undefined reference to `FcPatternAddString'
/usr/bin/ld: fl_font.cxx:(.text._ZN18Fl_Font_DescriptorC2EPKcii+0x1b4): undefined reference to `FcPatternAddString'
/usr/bin/ld: fl_font.cxx:(.text._ZN18Fl_Font_DescriptorC2EPKcii+0x1c6): undefined reference to `FcPatternAddInteger'
/usr/bin/ld: fl_font.cxx:(.text._ZN18Fl_Font_DescriptorC2EPKcii+0x1dd): undefined reference to `FcPatternAddInteger'
/usr/bin/ld: fl_font.cxx:(.text._ZN18Fl_Font_DescriptorC2EPKcii+0x1fa): undefined reference to `FcPatternAddDouble'
/usr/bin/ld: fl_font.cxx:(.text._ZN18Fl_Font_DescriptorC2EPKcii+0x210): undefined reference to `FcPatternAddString'
/usr/bin/ld: fl_font.cxx:(.text._ZN18Fl_Font_DescriptorC2EPKcii+0x276): undefined reference to `FcMatrixRotate'
/usr/bin/ld: fl_font.cxx:(.text._ZN18Fl_Font_DescriptorC2EPKcii+0x288): undefined reference to `FcPatternAddMatrix'
/usr/bin/ld: fl_font.cxx:(.text._ZN18Fl_Font_DescriptorC2EPKcii+0x2a0): undefined reference to `XftFontMatch'
/usr/bin/ld: fl_font.cxx:(.text._ZN18Fl_Font_DescriptorC2EPKcii+0x2df): undefined reference to `XftFontOpen'
/usr/bin/ld: fl_font.cxx:(.text._ZN18Fl_Font_DescriptorC2EPKcii+0x2ea): undefined reference to `FcPatternDestroy'
/usr/bin/ld: fl_font.cxx:(.text._ZN18Fl_Font_DescriptorC2EPKcii+0x316): undefined reference to `XftFontOpenPattern'
/usr/bin/ld: fl_font.cxx:(.text._ZN18Fl_Font_DescriptorC2EPKcii+0x326): undefined reference to `FcPatternDestroy'
/usr/bin/ld: fl_font.cxx:(.text._ZN18Fl_Font_DescriptorC2EPKcii+0x33d): undefined reference to `XftFontOpenXlfd'
/usr/bin/ld: /usr/local/lib/libfltk.a(fl_font.o): in function `Fl_Xlib_Graphics_Driver::width(unsigned int)':
fl_font.cxx:(.text._ZN23Fl_Xlib_Graphics_Driver5widthEj+0x49): undefined reference to `XftTextExtents32'
/usr/bin/ld: /usr/local/lib/libfltk.a(fl_font.o): in function `fl_destroy_xft_draw(unsigned long)':
fl_font.cxx:(.text._Z19fl_destroy_xft_drawm+0x23): undefined reference to `XftDrawChange'
/usr/bin/ld: /usr/local/lib/libfltk.a(fl_font.o): in function `Fl_Xlib_Graphics_Driver::draw(char const*, int, int, int)':
fl_font.cxx:(.text._ZN23Fl_Xlib_Graphics_Driver4drawEPKciii+0x7e): undefined reference to `XftDrawCreate'
/usr/bin/ld: fl_font.cxx:(.text._ZN23Fl_Xlib_Graphics_Driver4drawEPKciii+0x93): undefined reference to `XftDrawChange'
/usr/bin/ld: fl_font.cxx:(.text._ZN23Fl_Xlib_Graphics_Driver4drawEPKciii+0xc6): undefined reference to `XftDrawSetClip'
/usr/bin/ld: fl_font.cxx:(.text._ZN23Fl_Xlib_Graphics_Driver4drawEPKciii+0x156): undefined reference to `XftDrawString32'
/usr/bin/ld: /usr/local/lib/libfltk.a(fl_font.o): in function `Fl_Xlib_Graphics_Driver::rtl_draw(char const*, int, int, int)':
fl_font.cxx:(.text._ZN23Fl_Xlib_Graphics_Driver8rtl_drawEPKciii+0x4c): undefined reference to `FcUtf8Len'
/usr/bin/ld: fl_font.cxx:(.text._ZN23Fl_Xlib_Graphics_Driver8rtl_drawEPKciii+0xb4): undefined reference to `FcUtf8ToUcs4'
/usr/bin/ld: fl_font.cxx:(.text._ZN23Fl_Xlib_Graphics_Driver8rtl_drawEPKciii+0xfa): undefined reference to `XftTextExtents32'
/usr/bin/ld: fl_font.cxx:(.text._ZN23Fl_Xlib_Graphics_Driver8rtl_drawEPKciii+0x146): undefined reference to `XftDrawCreate'
/usr/bin/ld: fl_font.cxx:(.text._ZN23Fl_Xlib_Graphics_Driver8rtl_drawEPKciii+0x15b): undefined reference to `XftDrawChange'
/usr/bin/ld: fl_font.cxx:(.text._ZN23Fl_Xlib_Graphics_Driver8rtl_drawEPKciii+0x18e): undefined reference to `XftDrawSetClip'
/usr/bin/ld: fl_font.cxx:(.text._ZN23Fl_Xlib_Graphics_Driver8rtl_drawEPKciii+0x20f): undefined reference to `XftDrawString32'
/usr/bin/ld: /usr/local/lib/libfltk.a(Fl_x.o): in function `fl_open_display(_XDisplay*)':
Fl_x.cxx:(.text._Z15fl_open_displayP9_XDisplay+0x4b3): undefined reference to `XFixesQueryExtension'
/usr/bin/ld: /usr/local/lib/libfltk.a(Fl_x.o): in function `Fl_X::xrender_supported()':
Fl_x.cxx:(.text._ZN4Fl_X17xrender_supportedEv+0x36): undefined reference to `XRenderQueryExtension'
/usr/bin/ld: /usr/local/lib/libfltk.a(Fl_x.o): in function `Fl_X::make_xid(Fl_Window*, XVisualInfo*, unsigned long)':
Fl_x.cxx:(.text._ZN4Fl_X8make_xidEP9Fl_WindowP11XVisualInfom+0x872): undefined reference to `XFixesSelectSelectionInput'
/usr/bin/ld: Fl_x.cxx:(.text._ZN4Fl_X8make_xidEP9Fl_WindowP11XVisualInfom+0x88e): undefined reference to `XFixesSelectSelectionInput'
/usr/bin/ld: /usr/local/lib/libfltk.a(Fl_Double_Window.o): in function `Fl_Xlib_Graphics_Driver::copy_offscreen_with_alpha(int, int, int, int, unsigned long, int, int)':
Fl_Double_Window.cxx:(.text._ZN23Fl_Xlib_Graphics_Driver25copy_offscreen_with_alphaEiiiimii+0x67): undefined reference to `XRenderFindStandardFormat'
/usr/bin/ld: Fl_Double_Window.cxx:(.text._ZN23Fl_Xlib_Graphics_Driver25copy_offscreen_with_alphaEiiiimii+0xa9): undefined reference to `XRenderFindVisualFormat'
/usr/bin/ld: Fl_Double_Window.cxx:(.text._ZN23Fl_Xlib_Graphics_Driver25copy_offscreen_with_alphaEiiiimii+0xd3): undefined reference to `XRenderCreatePicture'
/usr/bin/ld: Fl_Double_Window.cxx:(.text._ZN23Fl_Xlib_Graphics_Driver25copy_offscreen_with_alphaEiiiimii+0xf5): undefined reference to `XRenderCreatePicture'
/usr/bin/ld: Fl_Double_Window.cxx:(.text._ZN23Fl_Xlib_Graphics_Driver25copy_offscreen_with_alphaEiiiimii+0x147): undefined reference to `XRenderSetPictureClipRegion'
/usr/bin/ld: Fl_Double_Window.cxx:(.text._ZN23Fl_Xlib_Graphics_Driver25copy_offscreen_with_alphaEiiiimii+0x17f): undefined reference to `XRenderComposite'
/usr/bin/ld: Fl_Double_Window.cxx:(.text._ZN23Fl_Xlib_Graphics_Driver25copy_offscreen_with_alphaEiiiimii+0x192): undefined reference to `XRenderFreePicture'
/usr/bin/ld: Fl_Double_Window.cxx:(.text._ZN23Fl_Xlib_Graphics_Driver25copy_offscreen_with_alphaEiiiimii+0x1a1): undefined reference to `XRenderFreePicture'
**collect2: error: ld returned 1 exit status
**make[2]: *** [src/apps/CMakeFiles/display.dir/build.make:128: bin/relion_display] Error 1
make[1]: *** [CMakeFiles/Makefile2:825: src/apps/CMakeFiles/display.dir/all] Error 2
make: *** [Makefile:136: all] Error 2****

==================
```
Any suggestion?
Thank you.

**Comment by Conecsion** [comment]
Same error. Any solutions?
