### ISSUE TITLE
#error -- unsupported GNU version! gcc versions later than 8 are not supported!

### ISSUE THREAD

**Issue by CFDavidHou** [3dem/relion#981]
**Describe your problem**

Hi all, I have trouble installing RELION 4.0 on a workstation. Please see below environment and error message.

Please help. Much appreciate!

**Environment:**
 - OS: Ubuntu 20.04 LTS
 - MPI runtime: OpenMPI 2.0.1
 - RELION version RELION-4.0
 - Memory: 128 GB

$ gcc --version
gcc (Ubuntu 10.5.0-1ubuntu1~20.04) 10.5.0

$ nvidia-smi
| NVIDIA-SMI 510.108.03   Driver Version: 510.108.03   CUDA Version: 11.6     |

$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Sun_Jul_28_19:07:16_PDT_2019
Cuda compilation tools, release 10.1, V10.1.243

$ mpiexec --version
mpiexec (OpenRTE) 4.0.3

**Error message:**
$ make
[  0%] Built target copy_scripts
[  1%] Performing download step (download, verify and extract) for 'class_ranker_model_file'
-- verifying file...
       file='/home/user/relion/external/torch_models/class_ranker_0.1.3_torch_1.0.1.pt.tar.gz'
-- MD5 hash of
    /home/user/relion/external/torch_models/class_ranker_0.1.3_torch_1.0.1.pt.tar.gz
  does not match expected value
    expected: 'b39f0cbc31f510e3a03e89f1e11110fe'
      actual: 'd41d8cd98f00b204e9800998ecf8427e'
-- File already exists but hash mismatch. Removing...
-- Downloading...
   dst='/home/user/relion/external/torch_models/class_ranker_0.1.3_torch_1.0.1.pt.tar.gz'
   timeout='none'
-- Using src='ftp://ftp.mrc-lmb.cam.ac.uk/pub/dari/class_ranker_0.1.3_torch_1.0.1.pt.tar.gz'
-- [download 100% complete]
-- verifying file...
       file='/home/user/relion/external/torch_models/class_ranker_0.1.3_torch_1.0.1.pt.tar.gz'
-- Downloading... done
-- extracting...
     src='/home/user/relion/external/torch_models/class_ranker_0.1.3_torch_1.0.1.pt.tar.gz'
     dst='/home/user/relion/external/torch_models/class_ranker'
-- extracting... [tar xfz]
-- extracting... [analysis]
-- extracting... [rename]
-- extracting... [clean up]
-- extracting... done
[  1%] No patch step for 'class_ranker_model_file'
[  1%] No update step for 'class_ranker_model_file'
[  1%] No configure step for 'class_ranker_model_file'
[  1%] No build step for 'class_ranker_model_file'
[  1%] No install step for 'class_ranker_model_file'
[  1%] Completed 'class_ranker_model_file'
[  1%] Built target class_ranker_model_file
[  1%] Building NVCC (Device) object src/apps/CMakeFiles/relion_gpu_util.dir/__/acc/cuda/relion_gpu_util_generated_cuda_projector_plan.cu.o
In file included from /usr/include/cuda_runtime.h:83,
                 from <command-line>:
/usr/include/crt/host_config.h:138:2: error: #error -- unsupported GNU version! gcc versions later than 8 are not supported!
  138 | #error -- unsupported GNU version! gcc versions later than 8 are not supported!
      |  ^~~~~
CMake Error at relion_gpu_util_generated_cuda_projector_plan.cu.o.Release.cmake:220 (message):
  Error generating
  /home/user/relion/build/src/apps/CMakeFiles/relion_gpu_util.dir/__/acc/cuda/./relion_gpu_util_generated_cuda_projector_plan.cu.o

make[2]: *** [src/apps/CMakeFiles/relion_gpu_util.dir/build.make:114: src/apps/CMakeFiles/relion_gpu_util.dir/__/acc/cuda/relion_gpu_util_generated_cuda_projector_plan.cu.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1566: src/apps/CMakeFiles/relion_gpu_util.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
**End of error **

**Comment by biochem-fan** [comment]
You need a newer CUDA SDK to use GCC 10.5.
Please study NVIDIA's documentation.
