### ISSUE TITLE
relion_convert_to_tiff with the option --only_do_unfinished - slow 

### ISSUE THREAD

**Issue by eMKiso** [3dem/relion#985]
Dear all,

we have been using `relion_convert_to_tiff_(mpi)` for years with our Falcon 3 movies and it is an excellent tool.

[Relion convert_to_tiff](https://relion.readthedocs.io/en/release-3.1/Reference/MovieCompression.html#relion-convert-to-tiff)

Since the beginning we saw that the option `--only_do_unfinished` behaves a bit strange when used in combination with `relion_convert_to_tiff_mpi`. If we use it as a batch, so the input .star file (list of all movies to compress) doesn't change it works as expected i.e. if we dedicate 30 threads to compression then 30 movies are compressed in parallel. 
When we try to use the `relion_convert_to_tiff_mpi` as the movies are collected (and the .star file is regularly updated with a scheduled job in Relion GUI) and add the option `--only_do_unfinished` then it starts to behave a bit different. 
The command we use to regularly check for new movies and compress them is as follows:
`while true; do mpirun -np 30 --oversubscribe relion_convert_to_tiff_mpi --i Import/job001/movies.star --o /Converted/ --only_do_unfinished ; sleep 60; done`

When the `relion_convert_to_tiff_mpi` in the above command runs for the FIRST time it works on 30 threads, as expected. 
But all SUBSEQUENT repetitions of the command `relion_convert_to_tiff_mpi` convert only a handfull of movies in parallel (there are a lot of movies waiting to be compressed, so the reason is not a low number of unfinished movies). For example around 5 movies in parallel are transferred in parallel in subsequent repetitions.

We also tested just running the `relion_convert_to_tiff_mpi` manually one time and the issues appears once there are some finished or unfinished .tif files present in the /Converted/ folder. If we delete/move the files that were already compressed then we again get the full 'speed'.

Below is CPU utilization graph. In this case yellow colour represents busy CPU and it is doing something 'useful'. At the beginning all 30 threads are compressing movies and there is little system CPU time (purple).
Purple is busy CPU but it is not producing any compressed .tif files. So there are apparently 30 processes running, but only a few are producing new compressed .tif files. So the process of compression slows down significantly...
![image](https://github.com/3dem/relion/assets/16688247/e8a9c98e-35fb-42cd-a70b-c47e553e772b)

It is also nicely visible in the network traffic graph. 
![image](https://github.com/3dem/relion/assets/16688247/4f858e6d-1c52-4b96-af07-4cd8b1bdae38)

We use two Linux Ubuntu servers and in both cases we get the same behaviour. Relion 3 or 4 makes no difference.

The issue above is not really an issue if one uses just batch transfers (all the movies are present at the start of the compression process). But when you try to compress movies on the fly as they are collected it becomes quite slow.

Is this a `mpirun` issue or a `relion_convert_to_tiff_mpi` issue?

Best!

**Comment by biochem-fan** [comment]
Thank you very much for a great report. This is because input movies are allocated to MPI processes *before* being checked whether they have already been compressed.

Suppose you have 3 MPI processes and want to compress 6 movies. The first round is processed as [1 2] [3 4] [5 6], where [ ] indicates assignment to one MPI process. Now suppose you got 3 more movies. You have 9 movies in total, so the assignment becomes [1 2 3] [4 5 6] [7 8 9]. Notice that all the new movies got assigned to the last MPI process and the first two MPI processes have nothing to do, wasting time.

A quick fix would be to shuffle the input list randomly; this does NOT guarantee all processes get tasks but *probabilistically* they do. Please try the following patch and give us feedbacks. If this works fine and does not cause side effects, I will merge this into the distribution.

```diff
diff --git a/src/tiff_converter.cpp b/src/tiff_converter.cpp
index 41874080..6462bbf4 100644
--- a/src/tiff_converter.cpp
+++ b/src/tiff_converter.cpp
@@ -361,6 +361,10 @@ void TIFFConverter::initialise(int _rank, int _total_ranks)
                fn_first = fn_in;
        }
 
+       // Shuffle the input list so that (almost) all MPI processes get new movies
+       if (do_estimate || total_ranks > 1)
+               MD.randomiseOrder();
+
        if (fn_first.getExtension() != "mrc" && fn_first.getExtension() != "mrcs" && !EERRenderer::isEER(fn_first))
                REPORT_ERROR(fn_first + ": the input must be MRC, MRCS or EER files");
 
@@ -392,9 +396,6 @@ void TIFFConverter::initialise(int _rank, int _total_ranks)
        }
        else
        {
-               if (do_estimate)
-                       MD.randomiseOrder();    
-
                // Check type and mode of the input
                Image<RFLOAT> Ihead;
                Ihead.read(fn_first, false, -1, false, true); // select_img -1, mmap false, is_2D true
```

**Comment by eMKiso** [comment]
Hi @biochem-fan,

thank you for your quick reply, nice explanation and the quick fix.
I'll test it and come back to you!

Kind regards!

**Comment by biochem-fan** [comment]
Thank you very much for testing. I applied this change to the `ver4.0` branch (dd10f8a2).

**Comment by biochem-fan** [comment]
Unfortunately, the above fix turned out to be dangerous.
This fix assumes that `MD.randomiseOrder()` on all MPI ranks gives the identical ordering. However, this is implementation (compiler) dependent.

If the order is not identical, some movies can be left uncompressed.
