### ISSUE TITLE
CMake Error at relion_gpu_util_generated_cuda_projector_plan.cu.o.Release.cmake:280

### ISSUE THREAD

**Issue by CFDavidHou** [3dem/relion#988]
Hi everyone,

I just got a new workstation to work on RELION. All fresh install environment as below:

Intel® Xeon(R) Silver 4316 CPU @ 2.30GHz × 40
Ubuntu 22.04.3 LTS

I installed CUDA using the up-to-date method below:
#Install CUDA toolkit from https://developer.nvidia.com/cuda-downloads
#Installer Type choose deb (local)

$ wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/cuda-ubuntu2204.pin
$ sudo mv cuda-ubuntu2204.pin /etc/apt/preferences.d/cuda-repository-pin-600wget
$ https://developer.download.nvidia.com/compute/cuda/12.2.2/local_installers/cuda-repo-ubuntu2204-12-2-local_12.2.2-535.104.05-1_amd64.deb
$ sudo dpkg -i cuda-repo-ubuntu2204-12-2-local_12.2.2-535.104.05-1_amd64.deb
$ sudo cp /var/cuda-repo-ubuntu2204-12-2-local/cuda-*-keyring.gpg /usr/share/keyrings/
$ sudo apt-get update
$ sudo apt-get -y install cuda
$ nvidia-smi
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 4080        Off | 00000000:51:00.0  On |                  N/A |
|  0%   39C    P8              18W / 320W |    486MiB / 16376MiB |      9%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
|   1  NVIDIA GeForce RTX 4080        Off | 00000000:C3:00.0 Off |                  N/A |
|  0%   38C    P8              18W / 320W |     11MiB / 16376MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+

#Install nvidia-cuda-toolkit
$ sudo apt install nvidia-cuda-toolkit
$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Thu_Nov_18_09:45:30_PST_2021
Cuda compilation tools, release 11.5, V11.5.119
Build cuda_11.5.r11.5/compiler.30672275_0

Then I followed RELION installation method as below:

$ sudo apt install cmake git build-essential mpi-default-bin mpi-default-dev libfftw3-dev libtiff-dev
$ sudo apt-get -y install libxft-dev
$ sudo apt install libwxgtk3.0-gtk3-dev

$ git clone https://github.com/3dem/relion.git
$ cd relion
$ git checkout ver4.0
$ git pull
$ mkdir build
$ cd build
$ cd cmake ..
$ sudo make
I can install RELION 4 till sudo make this step.

ERROR message:
[  1%] No update step for 'class_ranker_model_file'
[  2%] No patch step for 'class_ranker_model_file'
[  2%] No configure step for 'class_ranker_model_file'
[  3%] No build step for 'class_ranker_model_file'
[  3%] No install step for 'class_ranker_model_file'
[  3%] Completed 'class_ranker_model_file'
[  3%] Built target class_ranker_model_file
[  3%] Built target copy_scripts
[  3%] Building NVCC (Device) object src/apps/CMakeFiles/relion_jaz_gpu_util.dir/__/jaz/cuda/relion_jaz_gpu_util_generated_test00.cu.o
nvcc warning : The 'compute_35', 'compute_37', 'compute_50', 'sm_35', 'sm_37' and 'sm_50' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
nvcc warning : The 'compute_35', 'compute_37', 'compute_50', 'sm_35', 'sm_37' and 'sm_50' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
[  4%] Linking CXX static library ../../lib/librelion_jaz_gpu_util.a
[  4%] Built target relion_jaz_gpu_util
[  4%] Building NVCC (Device) object src/apps/CMakeFiles/relion_gpu_util.dir/__/acc/cuda/relion_gpu_util_generated_cuda_projector_plan.cu.o
nvcc warning : The 'compute_35', 'compute_37', 'compute_50', 'sm_35', 'sm_37' and 'sm_50' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
nvcc warning : The 'compute_35', 'compute_37', 'compute_50', 'sm_35', 'sm_37' and 'sm_50' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
/usr/include/c++/11/bits/std_function.h:435:145: error: parameter packs not expanded with ‘...’:
  435 |         function(_Functor&& __f)
      |                                                                                                                                                 ^ 
/usr/include/c++/11/bits/std_function.h:435:145: note:         ‘_ArgTypes’
/usr/include/c++/11/bits/std_function.h:530:146: error: parameter packs not expanded with ‘...’:
  530 |         operator=(_Functor&& __f)
      |                                                                                                                                                  ^ 
/usr/include/c++/11/bits/std_function.h:530:146: note:         ‘_ArgTypes’
CMake Error at relion_gpu_util_generated_cuda_projector_plan.cu.o.Release.cmake:280 (message):
  Error generating file
  /home/anna/relion/build/src/apps/CMakeFiles/relion_gpu_util.dir/__/acc/cuda/./relion_gpu_util_generated_cuda_projector_plan.cu.o

make[2]: *** [src/apps/CMakeFiles/relion_gpu_util.dir/build.make:126: src/apps/CMakeFiles/relion_gpu_util.dir/__/acc/cuda/relion_gpu_util_generated_cuda_projector_plan.cu.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:434: src/apps/CMakeFiles/relion_gpu_util.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
===============================end of error message======================================

I appreciate your help and time! 

Thank you!

David

**Comment by biochem-fan** [comment]
Your `nvidia-smi` says CUDA 12.2 but your `nvcc` says:
```
Built on Thu_Nov_18_09:45:30_PST_2021
Cuda compilation tools, release 11.5, V11.5.119
```
Something is strange.
2021 means it is earlier than Ubuntu 22.04.
Are you sure your C++ compiler version is compatible with the CUDA SDK?

Why do you use `sudo` for make? You need `sudo` only for `make install`.

**Comment by biochem-fan** [comment]
No response for more than one month and this is probably a problem with a messy build environment. Closing.
