### ISSUE TITLE
using CLI of relion: cannot write file Import/job001/movies.star

### ISSUE THREAD

**Issue by von-elfen** [3dem/relion#989]
Command: 
`relion_import  --do_movies  --optics_group_name "opticsGroup1" --optics_group_mtf mtf_k2_200kV.star --angpix 0.885 --kV 200 --Cs 1.4 --Q0 0.1 --beamtilt_x 0 --beamtilt_y 0 --i "Movies/*.tiff" --odir Import/job001/ --ofile movies.star --pipeline_control Import/job001/`

error log:
` importing...
in: /home/elfen/software/relion/src/apps/import.cpp, line 196
ERROR:
**MlModel::write: Cannot write file: Import/job001/movies.star**
=== Backtrace  ===
relion_import(_ZN11RelionErrorC1ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES7_l+0x7d) [0x55ce4b56a0cd]
relion_import(_ZN17import_parameters3runEv+0x44f2) [0x55ce4b562e12]
relion_import(main+0x4d) [0x55ce4b55a51d]
/lib/x86_64-linux-gnu/libc.so.6(+0x29d90) [0x7fe4d92f0d90]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x80) [0x7fe4d92f0e40]
relion_import(_start+0x25) [0x55ce4b55adc5]
==================
ERROR:
MlModel::write: Cannot write file: Import/job001/movies.star

 RELION version: 4.0.1-commit-6ecbb2
 exiting with an error ...
 ERROR: cannot touch file: Import/job001/RELION_JOB_EXIT_FAILURE`

I am a beginner of relion4. I prefer command line than GUI,
and i run the official sample on my laptop: WSL2, RTX3050 GPU, 64G RAM, Ryzenn 5600H CPU. 
I am sure that the installation of relion4 is perfect.

First, I learn with GUI through Xlaunch (this could offer a display window for WSL2, ),  Relion4.0 works well!
BUt when I go back to bash,It goes wrong!!
**MlModel::write: Cannot write file: Import/job001/movies.star**
It seems that the program is not accessed to create the directory. 

Then I create the dir: Import/job001    before   i run the command,   it works well  (althrough there are fewer outcome files than the same command runned in GUI, the core file stay same !  it still can be used for further analysis!)

So, how to solve this problem ?    Is that a bug?  need i fix that in source code？

I would be appreciate if there are someone give nice advice!

**Comment by biochem-fan** [comment]
> Then I create the dir: Import/job001 before i run the command, it works well

The GUI is responsible for making a job folder.

If you are not using the GUI, you have to make the folder yourself.

**Comment by von-elfen** [comment]
thank you !!
