### ISSUE TITLE
Predict memory usage in Refine3D

### ISSUE THREAD

**Issue by dacolombo** [3dem/relion#993]
Dear Relion developers,

This is more of a question than a bug report, I don't know if CCPEM mailing list is a better channel to ask this question, feel free to close this if I should post it there instead.

I am managing the Relion installation on our HPC environment and I am facing some difficulties at finding the optimal ways in which jobs should be submitted, especially in terms of memory requirements. Our HPC uses cgroups to limit memory usage, so we end up having jobs killed due to out of memory errors if we don't have a general idea of what a job is going to need in terms of memory.

I have found that it is possible to predict the amount of RAM needed by each MPI rank when using the `--preread_images` flag to be: `number of particles * box_size * box_size * 4 / (1024 * 1024 * 1024)`.
But is there a way to make some predictions on how much memory is a job going to need based on the input particles?

The main issue I am having right now is when running Refine3D jobs, in which the trend for the memory usage is generally similar to the following:
<img width="600" alt="image" src="https://github.com/3dem/relion/assets/68348680/9305a139-18f7-48fe-b8c7-f0522d118a31">

With either one of the spikes, especially the last one, causing the job to go out of memory in most cases.

I have tried using valgrind's massif to check which part of the code causes the memory spike, but my knowledge on the insides of Relion is too limited to get a full understanding out of it. If they can be useful, I can attach the results I got from massif with a Refine3D job.

I can imagine that the fact that Refine3D uses a stochastic process and the fact that memory requirements highly depends also from the threads and ranks used makes it hard to exactly predict the memory usage, but is there a way to at least make an estimate? Or could you point me towards some variables in the dataset and/or running parameters that should be considered in making this estimate?

Thank you very much.

In case it's needed:
**Environment:**
 - MPI runtime: intel-oneapi-mpi 2021.4.0
 - RELION version: RELION 4.0.1
 - GPU: Tesla V100

**Comment by biochem-fan** [comment]
This depends on too many things to predict: box size, padding, difficulty of alignment etc.

The simplest way is to simply allocate one full node per job. If the node has 8 GPUs, one would request the half (4 GPUs and full memory size / 2) to allow two RELION jobs running simultaneously.

**Comment by dacolombo** [comment]
Thanks @biochem-fan for the quick reply! This is what I was expecting. I just wanted to make sure because, having a shared HPC system, jobs need to be in general as efficient as possible with the resources asked and used, also in terms of memory.

Thanks for your availability!

**Comment by biochem-fan** [comment]
If a job uses all GPUs and CPU cores on a node, even if some memory is free, other jobs cannot run. What is the goal of specifying tight memory limit?

**Comment by dacolombo** [comment]
In the case in which all cores and/or or GPUs are used by the job it's correct, it doesn't change requesting more or less memory.

But we usually have multiple users running jobs (Relion and non-Relion) that need GPU, and not all need or want to lock the whole node. Also not always a complete node is available in an HPC, so to not have long waiting times it makes more sense to request only a portion of the node at some times.

In those cases, users can for example submit the job asking for example 2 GPUs and 3 MPI tasks, sometimes only 1 GPU for small datasets, with the node having 4 GPUs in total. In this case asking for more or less the amount of memory that is actually needed makes more sense, since jobs will probably wait less before being launched and in the meantime other jobs could make use of these resources.

**Comment by biochem-fan** [comment]
I see. My recommendation is to have two submission patterns, one full node or half a node (half GPU, half memory of a node). Indeed this won't allow running another job that requires only half GPU but more than half memory. In RELION, I don't expect many such jobs. Molecular dynamics simulations need strong GPU but less memory so they happily coexist with RELION. But if your cluster have many other workloads that require CPU memory disproportionately large, I see your point. Eventually users learn how much memory is necessary for their own datasets by trials and errors. I agree that it is useful if one can estimate the necessary memory by analyzing the input beforehand but this is far from trivial.
