### ISSUE TITLE
output aligned movie stack

### ISSUE THREAD

**Issue by zhouxt17** [3dem/relion#994]
Dear Relion developer,

This is more like a question about relion function. I'm using relion own motioncor function, and I wonder if it can output the aligned movie stack instead of outputting the final single images. I knew MotionCor2 has this function but I kind of prefer the relion own mitioncor. Thank you very much.

**Comment by biochem-fan** [comment]
Why do you want to do this? This feature was removed because it is a waste of disk space.

**Comment by biochem-fan** [comment]
> Am I still able to do this using some commands?

No, but you should and can do this in Polish, because Polish, which is reference based, can find better trajectories than reference-free motion correction at the earliest stage of processing. How to do this was explained in the CCPEM mailing list before.

**Comment by zhouxt17** [comment]
May I know from which version, this function has been removed? Maybe I can try an old version with this feature. Thank you!

**Comment by biochem-fan** [comment]
I checked the commit logs. Apparently the feature was never released to public. It was present only during early stages of development.

> I want to use different frames to do the reconstruction.

Why don't you do this in Polish? That will give better results!
First of all, an Extract job cannot extract particles from aligned but non-averaged movie frames.
