### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by 799040451** [3dem/relion#995]
I,ve tried installed relion v4.0, but cmake told me that I haven't got X11 lib. I,ve got x11 lib in Ubuntu system
Here it shows:
-- ------------------ YOU HAVE NO X11-LIBS ------------------
-- CCmake found no X11-libs on your system, which are required for the GUI.
--  You CAN add the flag -DGUI=OFF to avoid using X11
CMake Error at CMakeLists.txt:311 (message):
  X11 is required for GUI.

-- Configuring incomplete, errors occurred!
See also "/home/yu_lei/relion/build/CMakeFiles/CMakeOutput.log".
See also "/home/yu_lei/relion/build/CMakeFiles/CMakeError.log".

And I searched
(base) yu_lei@13900K:~/relion$ sudo apt-cache search x11-dev
[sudo] password for yu_lei: 
libx11-dev - X11 client-side library (development headers)
libxkbcommon-x11-dev - library to create keymaps with the XKB X11 protocol - development files
libghc-gi-gdkx11-dev - GDKX11 bindings
libghc-x11-dev - Haskell X11 binding for GHC
libnx-x11-dev - nxagent's libNX_X11 client-part library (development headers)
librust-cairo-sys-rs-dev - FFI bindings to libcairo - Rust source code
librust-gdkx11-dev - Rust bindings for the GDK X11 library - Rust source code
librust-x11-dev - X11 library bindings for Rust - Rust source code
librust-xcb+x11-dev - Rust bindings and wrappers for XCB - feature "x11"
librust-xkbcommon-sys-dev - Bindings to libxkbcommon - Rust source code

**Comment by biochem-fan** [comment]
`apt-cache search` shows the list of packages `apt` knows. It does not necessarily mean the package in question is installed. Please look at https://askubuntu.com/questions/423355/how-do-i-check-if-a-package-is-installed-on-my-server.

**Comment by biochem-fan** [comment]
No response for more than one month. Closing.
