### ISSUE TITLE
Relion-Blush does not seem accesible to the public yet

### ISSUE THREAD

**Issue by dirrei** [3dem/relion#996]
**Environment:**
 - OS: [e.g. Ubuntu 20.04 LTS]
 - MPI runtime: [e.g. OpenMPI 4.0.3]
 - RELION version [e.g. RELION-5.0--commit-08be2f1
 - Memory: [e.g. 512GB]
 - GPU: [e.g. GTX 3090]

Problem description and **Error message:**

Problem:

 pip install git+https://github.com/3dem/relion-blush or conda env create -f environment.yml trigger a username and password request for github.
"
Collecting git+https://github.com/3dem/relion-blush
  Cloning https://github.com/3dem/relion-blush to /tmp/pip-req-build-icm_k8o_
  Running command git clone --filter=blob:none --quiet https://github.com/3dem/relion-blush /tmp/pip-req-build-icm_k8o_
Username for 'https://github.com':
"
I assume that is not intended.
As mentioned I first tried to install via the environment.yml, once that failed I used pip to pinpoint the problematic package. I assume the relion-blush  repo is currently not open to the public?

Thank you in advance

**Comment by scheres** [comment]
now fixed.
